import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  {
    id: 'apple-iphone-16-pro-max',
    slug: 'apple-iphone-16-pro-max',
    brand: 'Apple',
    modelName: 'iPhone 16 Pro Max',
    generation: 'iPhone 16',
    status: 'active',
    launchDate: '2024-09',
    pricing: {
      startingPrice: 144900,
      maximumPrice: 184900,
      launchPrice: 144900,
      currentPrice: 144900,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Apple India Online Store',
    },
    display: {
      displaySize: 6.9,
      displayType: 'Super Retina XDR OLED (LTPO ProMotion)',
      resolution: '2868 x 1320 pixels at 460 ppi',
      refreshRate: 120,
      peakBrightness: 2000,
      hdr: 'Dolby Vision, HDR10',
      protection: 'Ceramic Shield (latest generation)',
      screenToBodyRatio: '91.4%',
    },
    performance: {
      chipset: 'Apple A18 Pro (3nm second generation)',
      cpu: '6-core CPU (2 performance & 4 efficiency cores)',
      gpu: '6-core GPU with hardware-accelerated ray tracing',
      ramOptions: ['8GB'],
      storageOptions: ['256GB', '512GB', '1TB'],
      storageType: 'NVMe',
      antutuScore: 1950000,
      geekbenchSingle: 3450,
      geekbenchMulti: 8750,
    },
    cameras: {
      rearCameraSetup: 'Triple (48MP + 48MP + 12MP)',
      mainCamera: '48 MP Fusion, f/1.78, 24mm, second-gen sensor-shift OIS',
      ultrawideCamera: '48 MP, f/2.2, 13mm, 120˚, hybrid focus pixels',
      telephotoCamera: '12 MP 5x Telephoto, f/2.8, 120mm tetraprism, 3D sensor-shift OIS',
      frontCamera: '12 MP TrueDepth, f/1.9, autofocus, 4K60 Dolby Vision',
      videoRecording: '4K Dolby Vision at 120 fps, ProRes, Log, Spatial Video',
      ois: true,
    },
    battery: {
      batteryCapacity: 4685,
      wiredCharging: 30,
      wirelessCharging: 25,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7 (802.11be)',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 3.2 Gen 2 (up to 10Gbps), DisplayPort',
      simConfig: 'Dual SIM (Nano-SIM + eSIM)',
    },
    physical: {
      dimensions: '163.0 x 77.6 x 8.25 mm',
      weight: 227,
      materials: 'Grade 5 Titanium with microblasted texture, Ceramic Shield front, textured matte glass back',
      waterResistance: 'IP68 (depth of 6 meters up to 30 min)',
      colors: ['Desert Titanium', 'Natural Titanium', 'White Titanium', 'Black Titanium'],
    },
    software: {
      operatingSystem: 'iOS',
      ui: 'iOS 18 (with Apple Intelligence)',
      launchOS: 'iOS 18',
      promisedMajorUpdates: 6,
      securityUpdatePolicy: '7+ years of security updates',
    },
    audio: {
      speakers: 'Spatial Audio stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'None',
      faceUnlock: true,
      biometricNotes: 'Face ID via TrueDepth camera system',
    },
    keyHighlights: [
      'Massive 6.9-inch Super Retina XDR display with thinnest borders ever on Apple',
      'Dedicated Camera Control tactile haptic button for fast capture and exposure control',
      '4K 120 fps Dolby Vision video recording capability',
      'A18 Pro with next-gen 16-core Neural Engine and hardware ray tracing',
      'Industry benchmark battery life with up to 33 hours video playback',
    ],
    pros: [
      'Peerless 4K 120fps and ProRes log video capture quality',
      'Huge high-refresh display with razor-thin borders',
      'Exceptional battery endurance',
      'Robust titanium build and Ceramic Shield durability',
    ],
    cons: [
      'Premium pricing starting at ₹1,44,900',
      'Wired charging speeds top out around 27-30W',
      'Requires separate 30W adapter for peak charging',
    ],
    sources: {
      officialWebsite: 'https://www.apple.com/in/iphone-16-pro/',
      productPage: 'https://www.apple.com/in/shop/buy-iphone/iphone-16-pro',
      specSheetUrl: 'https://www.apple.com/in/iphone-16-pro/specs/',
      verifiedDate: '2024-09',
    },
  },

  {
    id: 'apple-iphone-16-pro',
    slug: 'apple-iphone-16-pro',
    brand: 'Apple',
    modelName: 'iPhone 16 Pro',
    generation: 'iPhone 16',
    status: 'active',
    launchDate: '2024-09',
    pricing: {
      startingPrice: 119900,
      maximumPrice: 169900,
      launchPrice: 119900,
      currentPrice: 119900,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Apple India Online Store',
    },
    display: {
      displaySize: 6.3,
      displayType: 'Super Retina XDR OLED (LTPO ProMotion)',
      resolution: '2622 x 1206 pixels at 460 ppi',
      refreshRate: 120,
      peakBrightness: 2000,
      hdr: 'Dolby Vision, HDR10',
      protection: 'Ceramic Shield (latest generation)',
      screenToBodyRatio: '90.1%',
    },
    performance: {
      chipset: 'Apple A18 Pro (3nm)',
      cpu: '6-core CPU (2 performance & 4 efficiency)',
      gpu: '6-core GPU',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB', '512GB', '1TB'],
      storageType: 'NVMe',
      antutuScore: 1920000,
    },
    cameras: {
      rearCameraSetup: 'Triple (48MP + 48MP + 12MP)',
      mainCamera: '48 MP Fusion, f/1.78, sensor-shift OIS',
      ultrawideCamera: '48 MP, f/2.2, 13mm, 120˚',
      telephotoCamera: '12 MP 5x Telephoto, f/2.8, tetraprism OIS',
      frontCamera: '12 MP TrueDepth, f/1.9, 4K60',
      videoRecording: '4K Dolby Vision at 120 fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 3582,
      wiredCharging: 27,
      wirelessCharging: 25,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 3.2 Gen 2 (up to 10Gbps)',
      simConfig: 'Dual SIM (Nano-SIM + eSIM)',
    },
    physical: {
      dimensions: '149.6 x 71.5 x 8.25 mm',
      weight: 199,
      materials: 'Grade 5 Titanium, Ceramic Shield front, textured matte glass back',
      waterResistance: 'IP68',
      colors: ['Desert Titanium', 'Natural Titanium', 'White Titanium', 'Black Titanium'],
    },
    software: {
      operatingSystem: 'iOS',
      ui: 'iOS 18',
      launchOS: 'iOS 18',
      promisedMajorUpdates: 6,
      securityUpdatePolicy: '7+ years of security updates',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'None',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.apple.com/in/iphone-16-pro/',
      productPage: 'https://www.apple.com/in/shop/buy-iphone/iphone-16-pro',
      specSheetUrl: 'https://www.apple.com/in/iphone-16-pro/specs/',
      verifiedDate: '2024-09',
    },
  },

  {
    id: 'apple-iphone-16-plus',
    slug: 'apple-iphone-16-plus',
    brand: 'Apple',
    modelName: 'iPhone 16 Plus',
    generation: 'iPhone 16',
    status: 'active',
    launchDate: '2024-09',
    pricing: {
      startingPrice: 89900,
      maximumPrice: 119900,
      launchPrice: 89900,
      currentPrice: 89900,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Apple India Online Store',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Super Retina XDR OLED',
      resolution: '2796 x 1290 pixels at 460 ppi',
      refreshRate: 60,
      peakBrightness: 2000,
      hdr: 'Dolby Vision',
      protection: 'Ceramic Shield',
      screenToBodyRatio: '88.0%',
    },
    performance: {
      chipset: 'Apple A18 (3nm)',
      cpu: '6-core CPU (2 performance & 4 efficiency)',
      gpu: '5-core GPU',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB', '512GB'],
      storageType: 'NVMe',
      antutuScore: 1720000,
    },
    cameras: {
      rearCameraSetup: 'Dual (48MP + 12MP)',
      mainCamera: '48 MP Fusion, f/1.6, 26mm, sensor-shift OIS',
      ultrawideCamera: '12 MP, f/2.2, 13mm, 120˚, macro',
      telephotoCamera: 'None (2x optical quality crop from 48MP)',
      frontCamera: '12 MP TrueDepth, f/1.9, 4K60',
      videoRecording: '4K Dolby Vision at 60 fps, Spatial Video',
      ois: true,
    },
    battery: {
      batteryCapacity: 4674,
      wiredCharging: 25,
      wirelessCharging: 25,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM (Nano-SIM + eSIM)',
    },
    physical: {
      dimensions: '160.9 x 77.8 x 7.8 mm',
      weight: 199,
      materials: 'Aerospace-grade Aluminum, color-infused glass back',
      waterResistance: 'IP68',
      colors: ['Ultramarine', 'Teal', 'Pink', 'White', 'Black'],
    },
    software: {
      operatingSystem: 'iOS',
      ui: 'iOS 18',
      launchOS: 'iOS 18',
      promisedMajorUpdates: 6,
      securityUpdatePolicy: '7+ years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'None',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.apple.com/in/iphone-16/',
      productPage: 'https://www.apple.com/in/shop/buy-iphone/iphone-16',
      specSheetUrl: 'https://www.apple.com/in/iphone-16/specs/',
      verifiedDate: '2024-09',
    },
  },

  {
    id: 'apple-iphone-16',
    slug: 'apple-iphone-16',
    brand: 'Apple',
    modelName: 'iPhone 16',
    generation: 'iPhone 16',
    status: 'active',
    launchDate: '2024-09',
    pricing: {
      startingPrice: 79900,
      maximumPrice: 109900,
      launchPrice: 79900,
      currentPrice: 79900,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Apple India Online Store',
    },
    display: {
      displaySize: 6.1,
      displayType: 'Super Retina XDR OLED',
      resolution: '2556 x 1179 pixels at 460 ppi',
      refreshRate: 60,
      peakBrightness: 2000,
      hdr: 'Dolby Vision',
      protection: 'Ceramic Shield',
      screenToBodyRatio: '86.5%',
    },
    performance: {
      chipset: 'Apple A18 (3nm)',
      cpu: '6-core CPU (2 performance & 4 efficiency)',
      gpu: '5-core GPU',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB', '512GB'],
      storageType: 'NVMe',
      antutuScore: 1710000,
    },
    cameras: {
      rearCameraSetup: 'Dual (48MP + 12MP)',
      mainCamera: '48 MP Fusion, f/1.6, sensor-shift OIS',
      ultrawideCamera: '12 MP, f/2.2, 120˚, macro',
      telephotoCamera: 'None (2x in-sensor crop)',
      frontCamera: '12 MP TrueDepth, f/1.9',
      videoRecording: '4K@60fps Dolby Vision, Spatial Video',
      ois: true,
    },
    battery: {
      batteryCapacity: 3561,
      wiredCharging: 25,
      wirelessCharging: 25,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '147.6 x 71.6 x 7.8 mm',
      weight: 170,
      materials: 'Aluminum frame, color-infused glass back',
      waterResistance: 'IP68',
      colors: ['Ultramarine', 'Teal', 'Pink', 'White', 'Black'],
    },
    software: {
      operatingSystem: 'iOS',
      ui: 'iOS 18',
      launchOS: 'iOS 18',
      promisedMajorUpdates: 6,
      securityUpdatePolicy: '7+ years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'None',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.apple.com/in/iphone-16/',
      productPage: 'https://www.apple.com/in/shop/buy-iphone/iphone-16',
      specSheetUrl: 'https://www.apple.com/in/iphone-16/specs/',
      verifiedDate: '2024-09',
    },
  },

  {
    id: 'apple-iphone-15',
    slug: 'apple-iphone-15',
    brand: 'Apple',
    modelName: 'iPhone 15',
    generation: 'iPhone 15',
    status: 'active',
    launchDate: '2023-09',
    pricing: {
      startingPrice: 69900,
      maximumPrice: 99900,
      launchPrice: 79900,
      currentPrice: 69900,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Apple India Online Store',
    },
    display: {
      displaySize: 6.1,
      displayType: 'Super Retina XDR OLED',
      resolution: '2556 x 1179 pixels',
      refreshRate: 60,
      peakBrightness: 2000,
      hdr: 'Dolby Vision',
      protection: 'Ceramic Shield',
      screenToBodyRatio: '86.4%',
    },
    performance: {
      chipset: 'Apple A16 Bionic (4nm)',
      cpu: '6-core CPU (2 performance & 4 efficiency)',
      gpu: '5-core GPU',
      ramOptions: ['6GB'],
      storageOptions: ['128GB', '256GB', '512GB'],
      storageType: 'NVMe',
      antutuScore: 1470000,
    },
    cameras: {
      rearCameraSetup: 'Dual (48MP + 12MP)',
      mainCamera: '48 MP, f/1.6, sensor-shift OIS',
      ultrawideCamera: '12 MP, f/2.4, 120˚',
      telephotoCamera: 'None (2x in-sensor zoom)',
      frontCamera: '12 MP, f/1.9',
      videoRecording: '4K@60fps Dolby Vision',
      ois: true,
    },
    battery: {
      batteryCapacity: 3349,
      wiredCharging: 20,
      wirelessCharging: 15,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '147.6 x 71.6 x 7.8 mm',
      weight: 171,
      materials: 'Aluminum frame, color-infused glass back',
      waterResistance: 'IP68',
      colors: ['Blue', 'Pink', 'Yellow', 'Green', 'Black'],
    },
    software: {
      operatingSystem: 'iOS',
      ui: 'iOS 18 (Upgraded)',
      launchOS: 'iOS 17',
      promisedMajorUpdates: 5,
      securityUpdatePolicy: '7 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'None',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.apple.com/in/iphone-15/',
      productPage: 'https://www.apple.com/in/shop/buy-iphone/iphone-15',
      specSheetUrl: 'https://www.apple.com/in/iphone-15/specs/',
      verifiedDate: '2024-09',
    },
  },

  {
    id: 'apple-iphone-14',
    slug: 'apple-iphone-14',
    brand: 'Apple',
    modelName: 'iPhone 14',
    generation: 'iPhone 14',
    status: 'active',
    launchDate: '2022-09',
    pricing: {
      startingPrice: 59900,
      maximumPrice: 89900,
      launchPrice: 79900,
      currentPrice: 59900,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Apple India Online Store',
    },
    display: {
      displaySize: 6.1,
      displayType: 'Super Retina XDR OLED',
      resolution: '2532 x 1170 pixels',
      refreshRate: 60,
      peakBrightness: 1200,
      hdr: 'Dolby Vision',
      protection: 'Ceramic Shield',
      screenToBodyRatio: '86.0%',
    },
    performance: {
      chipset: 'Apple A15 Bionic (5nm)',
      cpu: '6-core CPU (2 performance & 4 efficiency)',
      gpu: '5-core GPU',
      ramOptions: ['6GB'],
      storageOptions: ['128GB', '256GB', '512GB'],
      storageType: 'NVMe',
      antutuScore: 1330000,
    },
    cameras: {
      rearCameraSetup: 'Dual (12MP + 12MP)',
      mainCamera: '12 MP, f/1.5, sensor-shift OIS',
      ultrawideCamera: '12 MP, f/2.4, 120˚',
      telephotoCamera: 'None',
      frontCamera: '12 MP, f/1.9',
      videoRecording: '4K@60fps Dolby Vision',
      ois: true,
    },
    battery: {
      batteryCapacity: 3279,
      wiredCharging: 20,
      wirelessCharging: 15,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'Lightning, USB 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '146.7 x 71.5 x 7.8 mm',
      weight: 172,
      materials: 'Aluminum, Ceramic Shield front, glass back',
      waterResistance: 'IP68',
      colors: ['Midnight', 'Starlight', 'Blue', 'Purple', 'Yellow', '(PRODUCT)RED'],
    },
    software: {
      operatingSystem: 'iOS',
      ui: 'iOS 18 (Upgraded)',
      launchOS: 'iOS 16',
      promisedMajorUpdates: 5,
      securityUpdatePolicy: '7 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'None',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.apple.com/in/iphone-14/',
      productPage: 'https://www.apple.com/in/shop/buy-iphone/iphone-14',
      specSheetUrl: 'https://www.apple.com/in/iphone-14/specs/',
      verifiedDate: '2024-09',
    },
  },

  {
    id: 'apple-iphone-13',
    slug: 'apple-iphone-13',
    brand: 'Apple',
    modelName: 'iPhone 13',
    generation: 'iPhone 13',
    status: 'active',
    launchDate: '2021-09',
    pricing: {
      startingPrice: 49900,
      maximumPrice: 59900,
      launchPrice: 79900,
      currentPrice: 49900,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Apple India Online Store',
    },
    display: {
      displaySize: 6.1,
      displayType: 'Super Retina XDR OLED',
      resolution: '2532 x 1170 pixels',
      refreshRate: 60,
      peakBrightness: 1200,
      hdr: 'Dolby Vision',
      protection: 'Ceramic Shield',
      screenToBodyRatio: '86.0%',
    },
    performance: {
      chipset: 'Apple A15 Bionic (5nm, 4-core GPU)',
      cpu: '6-core CPU',
      gpu: '4-core GPU',
      ramOptions: ['4GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'NVMe',
      antutuScore: 1250000,
    },
    cameras: {
      rearCameraSetup: 'Dual (12MP + 12MP)',
      mainCamera: '12 MP, f/1.6, sensor-shift OIS',
      ultrawideCamera: '12 MP, f/2.4, 120˚',
      telephotoCamera: 'None',
      frontCamera: '12 MP, f/2.2',
      videoRecording: '4K@60fps Dolby Vision',
      ois: true,
    },
    battery: {
      batteryCapacity: 3240,
      wiredCharging: 20,
      wirelessCharging: 15,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.0',
      nfc: true,
      usb: 'Lightning, USB 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '146.7 x 71.5 x 7.65 mm',
      weight: 174,
      materials: 'Aluminum, Ceramic Shield front, glass back',
      waterResistance: 'IP68',
      colors: ['Midnight', 'Starlight', 'Blue', 'Pink', 'Green'],
    },
    software: {
      operatingSystem: 'iOS',
      ui: 'iOS 18 (Upgraded)',
      launchOS: 'iOS 15',
      promisedMajorUpdates: 5,
      securityUpdatePolicy: '7 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'None',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.apple.com/in/iphone-13/',
      productPage: 'https://www.apple.com/in/shop/buy-iphone/iphone-13',
      specSheetUrl: 'https://www.apple.com/in/iphone-13/specs/',
      verifiedDate: '2024-09',
    },
  },
];

const variants: MobileVariant[] = [
  // iPhone 16 Pro Max
  {
    id: 'apple-iphone-16-pro-max-8-256',
    modelId: 'apple-iphone-16-pro-max',
    ram: '8GB',
    storage: '256GB',
    price: 144900,
    mrp: 144900,
    colors: ['Desert Titanium', 'Natural Titanium', 'White Titanium', 'Black Titanium'],
    status: 'active',
    verified: true,
    source: 'Apple India Online Store',
  },
  {
    id: 'apple-iphone-16-pro-max-8-512',
    modelId: 'apple-iphone-16-pro-max',
    ram: '8GB',
    storage: '512GB',
    price: 164900,
    mrp: 164900,
    colors: ['Desert Titanium', 'Natural Titanium', 'White Titanium', 'Black Titanium'],
    status: 'active',
    verified: true,
    source: 'Apple India Online Store',
  },
  {
    id: 'apple-iphone-16-pro-max-8-1tb',
    modelId: 'apple-iphone-16-pro-max',
    ram: '8GB',
    storage: '1TB',
    price: 184900,
    mrp: 184900,
    colors: ['Desert Titanium', 'Natural Titanium', 'White Titanium', 'Black Titanium'],
    status: 'active',
    verified: true,
    source: 'Apple India Online Store',
  },

  // iPhone 16 Pro
  {
    id: 'apple-iphone-16-pro-8-128',
    modelId: 'apple-iphone-16-pro',
    ram: '8GB',
    storage: '128GB',
    price: 119900,
    mrp: 119900,
    colors: ['Desert Titanium', 'Natural Titanium', 'White Titanium', 'Black Titanium'],
    status: 'active',
    verified: true,
    source: 'Apple India Online Store',
  },
  {
    id: 'apple-iphone-16-pro-8-256',
    modelId: 'apple-iphone-16-pro',
    ram: '8GB',
    storage: '256GB',
    price: 129900,
    mrp: 129900,
    colors: ['Desert Titanium', 'Natural Titanium', 'White Titanium', 'Black Titanium'],
    status: 'active',
    verified: true,
    source: 'Apple India Online Store',
  },
  {
    id: 'apple-iphone-16-pro-8-512',
    modelId: 'apple-iphone-16-pro',
    ram: '8GB',
    storage: '512GB',
    price: 149900,
    mrp: 149900,
    colors: ['Desert Titanium', 'Natural Titanium', 'White Titanium', 'Black Titanium'],
    status: 'active',
    verified: true,
    source: 'Apple India Online Store',
  },
  {
    id: 'apple-iphone-16-pro-8-1tb',
    modelId: 'apple-iphone-16-pro',
    ram: '8GB',
    storage: '1TB',
    price: 169900,
    mrp: 169900,
    colors: ['Desert Titanium', 'Natural Titanium'],
    status: 'active',
    verified: true,
    source: 'Apple India Online Store',
  },

  // iPhone 16 Plus
  {
    id: 'apple-iphone-16-plus-8-128',
    modelId: 'apple-iphone-16-plus',
    ram: '8GB',
    storage: '128GB',
    price: 89900,
    mrp: 89900,
    colors: ['Ultramarine', 'Teal', 'Pink', 'White', 'Black'],
    status: 'active',
    verified: true,
    source: 'Apple India Online Store',
  },
  {
    id: 'apple-iphone-16-plus-8-256',
    modelId: 'apple-iphone-16-plus',
    ram: '8GB',
    storage: '256GB',
    price: 99900,
    mrp: 99900,
    colors: ['Ultramarine', 'Teal', 'Pink', 'White', 'Black'],
    status: 'active',
    verified: true,
    source: 'Apple India Online Store',
  },
  {
    id: 'apple-iphone-16-plus-8-512',
    modelId: 'apple-iphone-16-plus',
    ram: '8GB',
    storage: '512GB',
    price: 119900,
    mrp: 119900,
    colors: ['Ultramarine', 'Black'],
    status: 'active',
    verified: true,
    source: 'Apple India Online Store',
  },

  // iPhone 16
  {
    id: 'apple-iphone-16-8-128',
    modelId: 'apple-iphone-16',
    ram: '8GB',
    storage: '128GB',
    price: 79900,
    mrp: 79900,
    colors: ['Ultramarine', 'Teal', 'Pink', 'White', 'Black'],
    status: 'active',
    verified: true,
    source: 'Apple India Online Store',
  },
  {
    id: 'apple-iphone-16-8-256',
    modelId: 'apple-iphone-16',
    ram: '8GB',
    storage: '256GB',
    price: 89900,
    mrp: 89900,
    colors: ['Ultramarine', 'Teal', 'Pink', 'White', 'Black'],
    status: 'active',
    verified: true,
    source: 'Apple India Online Store',
  },
  {
    id: 'apple-iphone-16-8-512',
    modelId: 'apple-iphone-16',
    ram: '8GB',
    storage: '512GB',
    price: 109900,
    mrp: 109900,
    colors: ['Ultramarine', 'Black'],
    status: 'active',
    verified: true,
    source: 'Apple India Online Store',
  },

  // iPhone 15
  {
    id: 'apple-iphone-15-6-128',
    modelId: 'apple-iphone-15',
    ram: '6GB',
    storage: '128GB',
    price: 69900,
    mrp: 79900,
    colors: ['Blue', 'Pink', 'Yellow', 'Green', 'Black'],
    status: 'active',
    verified: true,
    source: 'Apple India Online Store',
  },
  {
    id: 'apple-iphone-15-6-256',
    modelId: 'apple-iphone-15',
    ram: '6GB',
    storage: '256GB',
    price: 79900,
    mrp: 89900,
    colors: ['Blue', 'Pink', 'Yellow', 'Green', 'Black'],
    status: 'active',
    verified: true,
    source: 'Apple India Online Store',
  },
  {
    id: 'apple-iphone-15-6-512',
    modelId: 'apple-iphone-15',
    ram: '6GB',
    storage: '512GB',
    price: 99900,
    mrp: 109900,
    colors: ['Blue', 'Black'],
    status: 'active',
    verified: true,
    source: 'Apple India Online Store',
  },

  // iPhone 14
  {
    id: 'apple-iphone-14-6-128',
    modelId: 'apple-iphone-14',
    ram: '6GB',
    storage: '128GB',
    price: 59900,
    mrp: 79900,
    colors: ['Midnight', 'Starlight', 'Blue', 'Purple'],
    status: 'active',
    verified: true,
    source: 'Apple India Online Store',
  },
  {
    id: 'apple-iphone-14-6-256',
    modelId: 'apple-iphone-14',
    ram: '6GB',
    storage: '256GB',
    price: 69900,
    mrp: 89900,
    colors: ['Midnight', 'Starlight', 'Blue'],
    status: 'active',
    verified: true,
    source: 'Apple India Online Store',
  },

  // iPhone 13
  {
    id: 'apple-iphone-13-4-128',
    modelId: 'apple-iphone-13',
    ram: '4GB',
    storage: '128GB',
    price: 49900,
    mrp: 79900,
    colors: ['Midnight', 'Starlight', 'Blue', 'Pink', 'Green'],
    status: 'active',
    verified: true,
    source: 'Apple India Online Store',
  },
  {
    id: 'apple-iphone-13-4-256',
    modelId: 'apple-iphone-13',
    ram: '4GB',
    storage: '256GB',
    price: 59900,
    mrp: 89900,
    colors: ['Midnight', 'Starlight', 'Blue'],
    status: 'active',
    verified: true,
    source: 'Apple India Online Store',
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    modelId: 'apple-iphone-16-pro-max',
    modelName: 'iPhone 16 Pro Max',
    brand: 'Apple',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-16-pro-finish-select-202409-6-9inch-deserttitanium?wid=940&hei=1112&fmt=png-alpha',
        angle: 'front',
        source: 'Apple India Online Store',
        sourceUrl: 'https://www.apple.com/in/iphone-16-pro/',
        verified: true,
        alt: 'Apple iPhone 16 Pro Max front view',
      },
      {
        url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-16-pro-finish-select-202409-6-9inch-deserttitanium_AV2?wid=940&hei=1112&fmt=png-alpha',
        angle: 'back',
        source: 'Apple India Online Store',
        sourceUrl: 'https://www.apple.com/in/iphone-16-pro/',
        verified: true,
        alt: 'Apple iPhone 16 Pro Max desert titanium back view',
      },
      {
        url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-16-pro-finish-select-202409-6-9inch-deserttitanium_AV3?wid=940&hei=1112&fmt=png-alpha',
        angle: 'side',
        source: 'Apple India Online Store',
        sourceUrl: 'https://www.apple.com/in/iphone-16-pro/',
        verified: true,
        alt: 'Apple iPhone 16 Pro Max titanium frame side view',
      },
      {
        url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-16-pro-finish-select-202409-6-9inch-deserttitanium_AV1?wid=940&hei=1112&fmt=png-alpha',
        angle: 'display',
        source: 'Apple India Online Store',
        sourceUrl: 'https://www.apple.com/in/iphone-16-pro/',
        verified: true,
        alt: 'Apple iPhone 16 Pro Max Super Retina XDR display view',
      },
    ],
  },
  {
    modelId: 'apple-iphone-16-pro',
    modelName: 'iPhone 16 Pro',
    brand: 'Apple',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-16-pro-finish-select-202409-6-3inch-naturaltitanium?wid=940&hei=1112&fmt=png-alpha',
        angle: 'front',
        source: 'Apple India Online Store',
        sourceUrl: 'https://www.apple.com/in/iphone-16-pro/',
        verified: true,
        alt: 'Apple iPhone 16 Pro front view',
      },
      {
        url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-16-pro-finish-select-202409-6-3inch-naturaltitanium_AV2?wid=940&hei=1112&fmt=png-alpha',
        angle: 'back',
        source: 'Apple India Online Store',
        sourceUrl: 'https://www.apple.com/in/iphone-16-pro/',
        verified: true,
        alt: 'Apple iPhone 16 Pro natural titanium back view',
      },
      {
        url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-16-pro-finish-select-202409-6-3inch-naturaltitanium_AV3?wid=940&hei=1112&fmt=png-alpha',
        angle: 'side',
        source: 'Apple India Online Store',
        sourceUrl: 'https://www.apple.com/in/iphone-16-pro/',
        verified: true,
        alt: 'Apple iPhone 16 Pro side profile view',
      },
      {
        url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-16-pro-finish-select-202409-6-3inch-naturaltitanium_AV1?wid=940&hei=1112&fmt=png-alpha',
        angle: 'display',
        source: 'Apple India Online Store',
        sourceUrl: 'https://www.apple.com/in/iphone-16-pro/',
        verified: true,
        alt: 'Apple iPhone 16 Pro display view',
      },
    ],
  },
  {
    modelId: 'apple-iphone-16-plus',
    modelName: 'iPhone 16 Plus',
    brand: 'Apple',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-16-finish-select-202409-6-7inch-ultramarine?wid=940&hei=1112&fmt=png-alpha',
        angle: 'front',
        source: 'Apple India Online Store',
        sourceUrl: 'https://www.apple.com/in/iphone-16/',
        verified: true,
        alt: 'Apple iPhone 16 Plus front view',
      },
      {
        url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-16-finish-select-202409-6-7inch-ultramarine_AV2?wid=940&hei=1112&fmt=png-alpha',
        angle: 'back',
        source: 'Apple India Online Store',
        sourceUrl: 'https://www.apple.com/in/iphone-16/',
        verified: true,
        alt: 'Apple iPhone 16 Plus ultramarine back view',
      },
      {
        url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-16-finish-select-202409-6-7inch-ultramarine_AV3?wid=940&hei=1112&fmt=png-alpha',
        angle: 'side',
        source: 'Apple India Online Store',
        sourceUrl: 'https://www.apple.com/in/iphone-16/',
        verified: true,
        alt: 'Apple iPhone 16 Plus side view',
      },
      {
        url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-16-finish-select-202409-6-7inch-ultramarine_AV1?wid=940&hei=1112&fmt=png-alpha',
        angle: 'display',
        source: 'Apple India Online Store',
        sourceUrl: 'https://www.apple.com/in/iphone-16/',
        verified: true,
        alt: 'Apple iPhone 16 Plus display angled view',
      },
    ],
  },
  {
    modelId: 'apple-iphone-16',
    modelName: 'iPhone 16',
    brand: 'Apple',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-16-finish-select-202409-6-1inch-teal?wid=940&hei=1112&fmt=png-alpha',
        angle: 'front',
        source: 'Apple India Online Store',
        sourceUrl: 'https://www.apple.com/in/iphone-16/',
        verified: true,
        alt: 'Apple iPhone 16 front display view',
      },
      {
        url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-16-finish-select-202409-6-1inch-teal_AV2?wid=940&hei=1112&fmt=png-alpha',
        angle: 'back',
        source: 'Apple India Online Store',
        sourceUrl: 'https://www.apple.com/in/iphone-16/',
        verified: true,
        alt: 'Apple iPhone 16 teal color dual camera back view',
      },
      {
        url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-16-finish-select-202409-6-1inch-teal_AV3?wid=940&hei=1112&fmt=png-alpha',
        angle: 'side',
        source: 'Apple India Online Store',
        sourceUrl: 'https://www.apple.com/in/iphone-16/',
        verified: true,
        alt: 'Apple iPhone 16 side profile view',
      },
      {
        url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-16-finish-select-202409-6-1inch-teal_AV1?wid=940&hei=1112&fmt=png-alpha',
        angle: 'display',
        source: 'Apple India Online Store',
        sourceUrl: 'https://www.apple.com/in/iphone-16/',
        verified: true,
        alt: 'Apple iPhone 16 Super Retina XDR display view',
      },
    ],
  },
  {
    modelId: 'apple-iphone-15',
    modelName: 'iPhone 15',
    brand: 'Apple',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-15-finish-select-202309-6-1inch-blue?wid=940&hei=1112&fmt=png-alpha',
        angle: 'front',
        source: 'Apple India Online Store',
        sourceUrl: 'https://www.apple.com/in/iphone-15/',
        verified: true,
        alt: 'Apple iPhone 15 front display view',
      },
      {
        url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-15-finish-select-202309-6-1inch-blue_AV2?wid=940&hei=1112&fmt=png-alpha',
        angle: 'back',
        source: 'Apple India Online Store',
        sourceUrl: 'https://www.apple.com/in/iphone-15/',
        verified: true,
        alt: 'Apple iPhone 15 blue back view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-15-2.jpg',
        angle: 'side',
        source: 'Apple Official Product Photography',
        sourceUrl: 'https://www.apple.com/in/iphone-15/',
        verified: true,
        alt: 'Apple iPhone 15 aluminum side profile view',
      },
      {
        url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-15-finish-select-202309-6-1inch-blue_AV1?wid=940&hei=1112&fmt=png-alpha',
        angle: 'display',
        source: 'Apple India Online Store',
        sourceUrl: 'https://www.apple.com/in/iphone-15/',
        verified: true,
        alt: 'Apple iPhone 15 Dynamic Island display view',
      },
    ],
  },
  {
    modelId: 'apple-iphone-14',
    modelName: 'iPhone 14',
    brand: 'Apple',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-14-finish-select-202209-6-1inch-midnight?wid=940&hei=1112&fmt=png-alpha',
        angle: 'front',
        source: 'Apple India Online Store',
        sourceUrl: 'https://www.apple.com/in/iphone-14/',
        verified: true,
        alt: 'Apple iPhone 14 front display view',
      },
      {
        url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-14-finish-select-202209-6-1inch-midnight_AV2?wid=940&hei=1112&fmt=png-alpha',
        angle: 'back',
        source: 'Apple India Online Store',
        sourceUrl: 'https://www.apple.com/in/iphone-14/',
        verified: true,
        alt: 'Apple iPhone 14 midnight back view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-14-2.jpg',
        angle: 'side',
        source: 'Apple Official Product Photography',
        sourceUrl: 'https://www.apple.com/in/iphone-14/',
        verified: true,
        alt: 'Apple iPhone 14 aerospace aluminum side profile',
      },
      {
        url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-14-finish-select-202209-6-1inch-midnight_AV1?wid=940&hei=1112&fmt=png-alpha',
        angle: 'display',
        source: 'Apple India Online Store',
        sourceUrl: 'https://www.apple.com/in/iphone-14/',
        verified: true,
        alt: 'Apple iPhone 14 Super Retina XDR OLED display',
      },
    ],
  },
  {
    modelId: 'apple-iphone-13',
    modelName: 'iPhone 13',
    brand: 'Apple',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-13-starlight-select-2021?wid=940&hei=1112&fmt=png-alpha',
        angle: 'front',
        source: 'Apple India Online Store',
        sourceUrl: 'https://www.apple.com/in/iphone-13/',
        verified: true,
        alt: 'Apple iPhone 13 front display view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-13-01.jpg',
        angle: 'back',
        source: 'Apple Official Product Photography',
        sourceUrl: 'https://www.apple.com/in/iphone-13/',
        verified: true,
        alt: 'Apple iPhone 13 diagonal dual camera back view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-13-2.jpg',
        angle: 'side',
        source: 'Apple Official Product Photography',
        sourceUrl: 'https://www.apple.com/in/iphone-13/',
        verified: true,
        alt: 'Apple iPhone 13 flat edge side view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13.jpg',
        angle: 'display',
        source: 'Apple Official Product Photography',
        sourceUrl: 'https://www.apple.com/in/iphone-13/',
        verified: true,
        alt: 'Apple iPhone 13 display view',
      },
    ],
  },
];

export const appleBundle: MobileBrandBundle = {
  models,
  variants,
  images,
};
