import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  // ── ROG PHONE 9 SERIES (Snapdragon 8 Elite Gaming Flagship) ──
  {
    id: 'asus-rog-phone-9-pro',
    slug: 'asus-rog-phone-9-pro',
    brand: 'ASUS',
    modelName: 'ASUS ROG Phone 9 Pro',
    generation: 'ROG Phone 9',
    status: 'active',
    launchDate: '2024-11',
    pricing: {
      startingPrice: 119999,
      maximumPrice: 139999,
      launchPrice: 119999,
      currentPrice: 119999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'ASUS India / Vijay Sales / ROG Store',
    },
    display: {
      displaySize: 6.78,
      displayType: 'Samsung Flexible LTPO AMOLED, 185Hz, 2500 nits peak',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 185,
      peakBrightness: 2500,
      hdr: 'HDR10',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '88.2%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Elite (3nm)',
      cpu: 'Octa-core (2x4.32 GHz Oryon V2 Phoenix L & 6x3.53 GHz Oryon V2 Phoenix M)',
      gpu: 'Adreno 830',
      ramOptions: ['16GB', '24GB'],
      storageOptions: ['512GB', '1TB'],
      storageType: 'UFS 4.0',
      antutuScore: 3120000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP Gimbal OIS + 32MP 3x Telephoto + 13MP Ultrawide)',
      mainCamera: '50 MP Sony Lytia LYT-700, f/1.9, 1/1.56", 6-axis Hybrid Gimbal Stabilizer 4.0',
      ultrawideCamera: '13 MP, f/2.2, 120˚, free-form lens',
      telephotoCamera: '32 MP, f/2.4, 3x optical zoom, OIS',
      frontCamera: '32 MP RGBW, f/2.05, 1080p@30fps',
      videoRecording: '8K@30fps, 4K@60fps, HDR10+',
      ois: true,
    },
    battery: {
      batteryCapacity: 5800,
      wiredCharging: 65,
      wirelessCharging: 15,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'Dual USB Type-C (Side: 3.1 Gen 2 / DisplayPort 1.4; Bottom: 2.0)',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '163.8 x 76.8 x 8.9 mm',
      weight: 227,
      materials: 'Gorilla Glass Victus 2 front, AniMe Vision programmable 648 mini-LED rear, aluminum frame',
      waterResistance: 'IP68 water and dust resistant',
      colors: ['Phantom Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'ROG UI',
      launchOS: 'Android 15',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '5 years',
    },
    audio: {
      speakers: 'Dual front-facing stereo speakers tuned by Dirac, 3.5mm headphone jack with Hi-Res Audio 384kHz/32-bit',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'In-display optical',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://rog.asus.com/in/phones/rog-phone-9-pro/',
      productPage: 'https://rog.asus.com/in/phones/rog-phone-9-pro/',
      specSheetUrl: 'https://rog.asus.com/in/phones/rog-phone-9-pro/spec/',
      verifiedDate: '2024-11',
    },
  },

  // ── ROG PHONE 8 SERIES (Snapdragon 8 Gen 3 Gaming Flagship) ──
  {
    id: 'asus-rog-phone-8-pro',
    slug: 'asus-rog-phone-8-pro',
    brand: 'ASUS',
    modelName: 'ASUS ROG Phone 8 Pro',
    generation: 'ROG Phone 8',
    status: 'active',
    launchDate: '2024-01',
    pricing: {
      startingPrice: 94999,
      maximumPrice: 119999,
      launchPrice: 94999,
      currentPrice: 94999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'ASUS India / Vijay Sales / ROG Store',
    },
    display: {
      displaySize: 6.78,
      displayType: 'Samsung Flexible LTPO AMOLED, 165Hz, 2500 nits peak',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 165,
      peakBrightness: 2500,
      hdr: 'HDR10',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '88.2%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Gen 3 (4nm)',
      cpu: 'Octa-core (1x3.3 GHz Cortex-X4 & 5x3.2 GHz & 2x2.3 GHz Cortex-A520)',
      gpu: 'Adreno 750',
      ramOptions: ['16GB', '24GB'],
      storageOptions: ['512GB', '1TB'],
      storageType: 'UFS 4.0',
      antutuScore: 2150000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP Gimbal OIS + 32MP 3x Telephoto + 13MP Ultrawide)',
      mainCamera: '50 MP Sony IMX890, f/1.9, 1/1.56", 6-axis Hybrid Gimbal Stabilizer 3.0',
      ultrawideCamera: '13 MP, f/2.2, 120˚, free-form lens',
      telephotoCamera: '32 MP, f/2.4, 3x optical zoom, OIS',
      frontCamera: '32 MP RGBW, f/2.05, 1080p@30fps',
      videoRecording: '8K@24fps, 4K@60fps, HDR10+',
      ois: true,
    },
    battery: {
      batteryCapacity: 5500,
      wiredCharging: 65,
      wirelessCharging: 15,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'Dual USB Type-C (Side: 3.1 Gen 2 / DisplayPort 1.4; Bottom: 2.0)',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '163.8 x 76.8 x 8.9 mm',
      weight: 225,
      materials: 'Gorilla Glass Victus 2 front, AniMe Matrix mini-LED rear, aluminum frame',
      waterResistance: 'IP68 water and dust resistant',
      colors: ['Phantom Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'ROG UI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers tuned by Dirac, 3.5mm headphone jack with Hi-Res Audio 384kHz/32-bit',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'In-display optical',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://rog.asus.com/in/phones/rog-phone-8-pro/',
      productPage: 'https://rog.asus.com/in/phones/rog-phone-8-pro/',
      specSheetUrl: 'https://rog.asus.com/in/phones/rog-phone-8-pro/spec/',
      verifiedDate: '2024-01',
    },
  },

  // ── ROG PHONE 7 SERIES (Historical Gaming Flagship) ──
  {
    id: 'asus-rog-phone-7-ultimate',
    slug: 'asus-rog-phone-7-ultimate',
    brand: 'ASUS',
    modelName: 'ASUS ROG Phone 7 Ultimate',
    generation: 'ROG Phone 7',
    status: 'discontinued',
    launchDate: '2023-04',
    pricing: {
      startingPrice: 99999,
      maximumPrice: 99999,
      launchPrice: 99999,
      currentPrice: 99999,
      currency: 'INR',
      priceEffectiveDate: '2024-01',
      source: 'ASUS India Store Archive',
    },
    display: {
      displaySize: 6.78,
      displayType: 'Samsung AMOLED, 165Hz, HDR10+, 1500 nits peak',
      resolution: '2448 x 1080 pixels (FHD+)',
      refreshRate: 165,
      peakBrightness: 1500,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass Victus',
      screenToBodyRatio: '82.2%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Gen 2 (4nm)',
      cpu: 'Octa-core (1x3.2 GHz Cortex-X3 & 2x2.8 GHz Cortex-A715 & 2x2.8 GHz Cortex-A710 & 3x2.0 GHz Cortex-A510)',
      gpu: 'Adreno 740',
      ramOptions: ['16GB'],
      storageOptions: ['512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 1610000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 13MP Ultrawide + 5MP Macro)',
      mainCamera: '50 MP Sony IMX766, f/1.9, 1/1.56", PDAF',
      ultrawideCamera: '13 MP, f/2.2, 120˚',
      telephotoCamera: 'None',
      frontCamera: '32 MP, f/2.5, 1080p@30fps',
      videoRecording: '8K@24fps, 4K@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 6000,
      wiredCharging: 65,
      wirelessCharging: 0,
      reverseCharging: 10,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'Dual USB Type-C (Side: 3.1 Gen 2 / DisplayPort 1.4; Bottom: 2.0)',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '173 x 77 x 10.3 mm',
      weight: 239,
      materials: 'AeroActive Portal motorized air inlet, ROG Vision matrix display, aluminum frame',
      waterResistance: 'IP54 splash resistant',
      colors: ['Storm White'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'ROG UI',
      launchOS: 'Android 13',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual front-facing symmetrical stereo speakers tuned by Dirac with 5-magnet design, 3.5mm headphone jack with ESS DAC',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'In-display optical',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://rog.asus.com/in/phones/rog-phone-7-ultimate-model/',
      productPage: 'https://rog.asus.com/in/phones/rog-phone-7-ultimate-model/',
      specSheetUrl: 'https://rog.asus.com/in/phones/rog-phone-7-ultimate-model/spec/',
      verifiedDate: '2023-04',
    },
  },

  // ── ROG PHONE 6 SERIES (Historical Gaming Flagship) ──
  {
    id: 'asus-rog-phone-6',
    slug: 'asus-rog-phone-6',
    brand: 'ASUS',
    modelName: 'ASUS ROG Phone 6',
    generation: 'ROG Phone 6',
    status: 'discontinued',
    launchDate: '2022-07',
    pricing: {
      startingPrice: 71999,
      maximumPrice: 71999,
      launchPrice: 71999,
      currentPrice: 71999,
      currency: 'INR',
      priceEffectiveDate: '2023-07',
      source: 'ASUS India Store Archive',
    },
    display: {
      displaySize: 6.78,
      displayType: 'Samsung AMOLED, 165Hz, HDR10+, 1200 nits peak',
      resolution: '2448 x 1080 pixels (FHD+)',
      refreshRate: 165,
      peakBrightness: 1200,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass Victus',
      screenToBodyRatio: '82.2%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8+ Gen 1 (4nm)',
      cpu: 'Octa-core (1x3.19 GHz Cortex-X2 & 3x2.75 GHz Cortex-A710 & 4x1.80 GHz Cortex-A510)',
      gpu: 'Adreno 730',
      ramOptions: ['12GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 1320000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 13MP Ultrawide + 5MP Macro)',
      mainCamera: '50 MP Sony IMX766, f/1.9, 1/1.56", PDAF',
      ultrawideCamera: '13 MP, f/2.2',
      telephotoCamera: 'None',
      frontCamera: '12 MP Sony IMX663, f/2.45',
      videoRecording: '8K@24fps, 4K@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 6000,
      wiredCharging: 65,
      wirelessCharging: 0,
      reverseCharging: 10,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.2',
      nfc: true,
      usb: 'Dual USB Type-C (Side: 3.1 Gen 2 / DisplayPort 1.4; Bottom: 2.0)',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '173 x 77 x 10.3 mm',
      weight: 239,
      materials: 'Gorilla Glass 3 rear with illuminated ROG logo, aluminum frame',
      waterResistance: 'IPX4 splash resistant',
      colors: ['Phantom Black', 'Storm White'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'ROG UI',
      launchOS: 'Android 12',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual front-facing stereo speakers tuned by Dirac, 3.5mm headphone jack with Cirrus Logic DAC',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'In-display optical',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://rog.asus.com/in/phones/rog-phone-6-model/',
      productPage: 'https://rog.asus.com/in/phones/rog-phone-6-model/',
      specSheetUrl: 'https://rog.asus.com/in/phones/rog-phone-6-model/spec/',
      verifiedDate: '2022-07',
    },
  },

  // ── ASUS 8Z (Compact Flagship Launched in India) ──
  {
    id: 'asus-8z',
    slug: 'asus-8z',
    brand: 'ASUS',
    modelName: 'ASUS 8z',
    generation: '8z',
    status: 'discontinued',
    launchDate: '2022-02',
    pricing: {
      startingPrice: 42999,
      maximumPrice: 42999,
      launchPrice: 42999,
      currentPrice: 42999,
      currency: 'INR',
      priceEffectiveDate: '2023-02',
      source: 'ASUS India / Flipkart Archive',
    },
    display: {
      displaySize: 5.9,
      displayType: 'Samsung Super AMOLED, 120Hz, HDR10+, 1100 nits peak',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1100,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass Victus',
      screenToBodyRatio: '84.0%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 888 5G (5nm)',
      cpu: 'Octa-core (1x2.84 GHz Kryo 680 & 3x2.42 GHz Kryo 680 & 4x1.80 GHz Kryo 680)',
      gpu: 'Adreno 660',
      ramOptions: ['8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 3.1',
      antutuScore: 820000,
    },
    cameras: {
      rearCameraSetup: 'Dual (64MP Sony IMX686 OIS + 12MP Ultrawide)',
      mainCamera: '64 MP Sony IMX686, f/1.8, 1/1.73", OIS, PDAF',
      ultrawideCamera: '12 MP Sony IMX363, f/2.2, 113˚, Dual Pixel PDAF, macro',
      telephotoCamera: 'None',
      frontCamera: '12 MP Sony IMX663, f/2.45, Dual Pixel PDAF, 4K30',
      videoRecording: '8K@24fps, 4K@60fps, EIS',
      ois: true,
    },
    battery: {
      batteryCapacity: 4000,
      wiredCharging: 30,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.2',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '148 x 68.5 x 8.9 mm',
      weight: 169,
      materials: 'Corning Gorilla Glass 3 frosted rear, aluminum frame, ultra-compact form factor',
      waterResistance: 'IP68 water and dust resistant',
      colors: ['Obsidian Black', 'Horizon Silver'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'ZenUI',
      launchOS: 'Android 11',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Cirrus Logic amplifiers, 3.5mm headphone jack with Dirac HD Sound',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'In-display optical',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.asus.com/in/mobile/phones/zenfone/asus-8z/',
      productPage: 'https://www.flipkart.com/asus-8z-store',
      specSheetUrl: 'https://www.asus.com/in/mobile/phones/zenfone/asus-8z/techspec/',
      verifiedDate: '2022-02',
    },
  },
];

const variants: MobileVariant[] = [
  // ROG Phone 9 Pro
  {
    id: 'asus-rog-phone-9-pro-16gb-512gb',
    modelId: 'asus-rog-phone-9-pro',
    name: 'ASUS ROG Phone 9 Pro (16GB RAM, 512GB)',
    ram: '16GB',
    storage: '512GB',
    color: 'Phantom Black',
    price: 119999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  {
    id: 'asus-rog-phone-9-pro-24gb-1tb',
    modelId: 'asus-rog-phone-9-pro',
    name: 'ASUS ROG Phone 9 Pro Edition (24GB RAM, 1TB with AeroActive Cooler X Pro)',
    ram: '24GB',
    storage: '1TB',
    color: 'Phantom Black',
    price: 139999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // ROG Phone 8 Pro
  {
    id: 'asus-rog-phone-8-pro-16gb-512gb',
    modelId: 'asus-rog-phone-8-pro',
    name: 'ASUS ROG Phone 8 Pro (16GB RAM, 512GB)',
    ram: '16GB',
    storage: '512GB',
    color: 'Phantom Black',
    price: 94999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  {
    id: 'asus-rog-phone-8-pro-24gb-1tb',
    modelId: 'asus-rog-phone-8-pro',
    name: 'ASUS ROG Phone 8 Pro Edition (24GB RAM, 1TB with AeroActive Cooler X)',
    ram: '24GB',
    storage: '1TB',
    color: 'Phantom Black',
    price: 119999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // ROG Phone 7 Ultimate
  {
    id: 'asus-rog-phone-7-ultimate-16gb-512gb',
    modelId: 'asus-rog-phone-7-ultimate',
    name: 'ASUS ROG Phone 7 Ultimate (16GB RAM, 512GB)',
    ram: '16GB',
    storage: '512GB',
    color: 'Storm White',
    price: 99999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  // ROG Phone 6
  {
    id: 'asus-rog-phone-6-12gb-256gb',
    modelId: 'asus-rog-phone-6',
    name: 'ASUS ROG Phone 6 (12GB RAM, 256GB)',
    ram: '12GB',
    storage: '256GB',
    color: 'Phantom Black',
    price: 71999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  // ASUS 8z
  {
    id: 'asus-8z-8gb-128gb',
    modelId: 'asus-8z',
    name: 'ASUS 8z (8GB RAM, 128GB)',
    ram: '8GB',
    storage: '128GB',
    color: 'Obsidian Black',
    price: 42999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    modelId: 'asus-rog-phone-9-pro',
    modelName: 'ASUS ROG Phone 9 Pro',
    brand: 'ASUS',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/asus-rog-phone-9-pro.jpg',
        angle: 'front',
        source: 'ASUS ROG Official (GSMArena CDN)',
        sourceUrl: 'https://rog.asus.com/in/phones/rog-phone-9-pro/',
        verified: true,
        alt: 'ASUS ROG Phone 9 Pro front 185Hz display view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/asus/asus-rog-phone-9-pro-1.jpg',
        angle: 'back',
        source: 'ASUS ROG Official (GSMArena CDN)',
        sourceUrl: 'https://rog.asus.com/in/phones/rog-phone-9-pro/',
        verified: true,
        alt: 'ASUS ROG Phone 9 Pro AniMe Vision rear view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/asus/asus-rog-phone-9-pro-2.jpg',
        angle: 'side',
        source: 'ASUS ROG Official (GSMArena CDN)',
        sourceUrl: 'https://rog.asus.com/in/phones/rog-phone-9-pro/',
        verified: true,
        alt: 'ASUS ROG Phone 9 Pro gaming trigger profile',
      },
    ],
  },
  {
    modelId: 'asus-rog-phone-8-pro',
    modelName: 'ASUS ROG Phone 8 Pro',
    brand: 'ASUS',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/asus-rog-phone-8-pro.jpg',
        angle: 'front',
        source: 'ASUS ROG Official (GSMArena CDN)',
        sourceUrl: 'https://rog.asus.com/in/phones/rog-phone-8-pro/',
        verified: true,
        alt: 'ASUS ROG Phone 8 Pro front 165Hz AMOLED display',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/asus/asus-rog-phone-8-pro-1.jpg',
        angle: 'back',
        source: 'ASUS ROG Official (GSMArena CDN)',
        sourceUrl: 'https://rog.asus.com/in/phones/rog-phone-8-pro/',
        verified: true,
        alt: 'ASUS ROG Phone 8 Pro AniMe Matrix mini-LED rear view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/asus/asus-rog-phone-8-pro-2.jpg',
        angle: 'side',
        source: 'ASUS ROG Official (GSMArena CDN)',
        sourceUrl: 'https://rog.asus.com/in/phones/rog-phone-8-pro/',
        verified: true,
        alt: 'ASUS ROG Phone 8 Pro AirTrigger profile',
      },
    ],
  },
  {
    modelId: 'asus-rog-phone-7-ultimate',
    modelName: 'ASUS ROG Phone 7 Ultimate',
    brand: 'ASUS',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/asus-rog-phone-7-ultimate.jpg',
        angle: 'front',
        source: 'ASUS ROG Official (GSMArena CDN)',
        sourceUrl: 'https://rog.asus.com/in/phones/rog-phone-7-ultimate-model/',
        verified: true,
        alt: 'ASUS ROG Phone 7 Ultimate front view',
      },
    ],
  },
  {
    modelId: 'asus-rog-phone-6',
    modelName: 'ASUS ROG Phone 6',
    brand: 'ASUS',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/asus-rog-phone6.jpg',
        angle: 'front',
        source: 'ASUS ROG Official (GSMArena CDN)',
        sourceUrl: 'https://rog.asus.com/in/phones/rog-phone-6-model/',
        verified: true,
        alt: 'ASUS ROG Phone 6 front view',
      },
    ],
  },
  {
    modelId: 'asus-8z',
    modelName: 'ASUS 8z',
    brand: 'ASUS',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/asus-zenfone-8.jpg',
        angle: 'front',
        source: 'ASUS Official (GSMArena CDN)',
        sourceUrl: 'https://www.asus.com/in/mobile/phones/zenfone/asus-8z/',
        verified: true,
        alt: 'ASUS 8z front compact display view',
      },
    ],
  },
];

export const asusBundle: MobileBrandBundle = {
  brand: 'ASUS',
  models,
  variants,
  images,
};
