import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  // ── OPPO ──
  {
    id: 'oppo-find-x8-pro',
    slug: 'oppo-find-x8-pro',
    brand: 'OPPO',
    modelName: 'Find X8 Pro',
    generation: 'Find X8',
    status: 'active',
    launchDate: '2024-11',
    pricing: {
      startingPrice: 99999,
      maximumPrice: 99999,
      launchPrice: 99999,
      currentPrice: 99999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'OPPO India Official Store',
    },
    display: {
      displaySize: 6.78,
      displayType: '1.5K 120Hz Infinite View Quad-Curved AMOLED',
      resolution: '2780 x 1264 pixels',
      refreshRate: 120,
      peakBrightness: 4500,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '92.8%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 9400 (3nm)',
      cpu: 'Octa-core All-Big-Core (1x3.63 GHz Cortex-X925 & 3x3.3 GHz & 4x2.4 GHz)',
      gpu: 'Immortalis-G925',
      ramOptions: ['16GB'],
      storageOptions: ['512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 2880000,
    },
    cameras: {
      rearCameraSetup: 'Quad (50MP + 50MP + 50MP + 50MP) Hasselblad Dual Periscope',
      mainCamera: '50 MP Sony LYT-808, f/1.6, 23mm, OIS',
      ultrawideCamera: '50 MP Samsung JN5, f/2.0, 15mm, 120˚',
      telephotoCamera: '50 MP Sony LYT-600 (3x optical, 73mm, OIS) + 50 MP Sony IMX858 (6x periscope, 135mm, OIS)',
      frontCamera: '32 MP Sony IMX615, f/2.4, 4K60',
      videoRecording: '4K@60fps Dolby Vision HDR, Quick Button capture',
      ois: true,
    },
    battery: {
      batteryCapacity: 5910,
      wiredCharging: 80,
      wirelessCharging: 50,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 3.2 Gen 1',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.3 x 76.7 x 8.24 mm',
      weight: 215,
      materials: 'Aviation aluminum frame, pearl velvet glass back',
      waterResistance: 'IP68 and IP69 dust and high-pressure water resistant',
      colors: ['Space Black', 'Pearl White'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'ColorOS 15',
      launchOS: 'Android 15',
      promisedMajorUpdates: 5,
      securityUpdatePolicy: '6 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.oppo.com/in/smartphones/series-find-x/find-x8-pro/',
      productPage: 'https://www.oppo.com/in/store/product/find-x8-pro.html',
      specSheetUrl: 'https://www.oppo.com/in/smartphones/series-find-x/find-x8-pro/specs/',
      verifiedDate: '2024-11',
    },
  },

  {
    id: 'oppo-reno-12-pro-5g',
    slug: 'oppo-reno-12-pro-5g',
    brand: 'OPPO',
    modelName: 'Reno 12 Pro 5G',
    generation: 'Reno 12',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 36999,
      maximumPrice: 40999,
      launchPrice: 36999,
      currentPrice: 36999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'OPPO India Official Store',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Infinite View Quad-Curved 120Hz AMOLED',
      resolution: '2412 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 1200,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '93.5%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7300-Energy (4nm)',
      cpu: 'Octa-core (4x2.5 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G615 MC2',
      ramOptions: ['12GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 3.1',
      antutuScore: 730000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 8MP) with AI Portrait Studio',
      mainCamera: '50 MP Sony LYT-600, f/1.8, OIS',
      ultrawideCamera: '8 MP Sony IMX355, f/2.2, 112˚',
      telephotoCamera: '50 MP Samsung JN5 portrait telephoto, 2x optical, OIS',
      frontCamera: '50 MP Samsung JN5, f/2.0, autofocus, 4K30',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 80,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '161.5 x 74.8 x 7.4 mm',
      weight: 180,
      materials: 'High-strength alloy frame, textured glass back',
      waterResistance: 'IP65 splash and dust resistance',
      colors: ['Sunset Gold', 'Space Brown'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'ColorOS 14.1 with GenAI features',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.oppo.com/in/smartphones/series-reno/reno12-pro-5g/',
      productPage: 'https://www.oppo.com/in/store/product/reno12-pro-5g.html',
      specSheetUrl: 'https://www.oppo.com/in/smartphones/series-reno/reno12-pro-5g/specs/',
      verifiedDate: '2024-07',
    },
  },

  {
    id: 'oppo-f27-pro-plus-5g',
    slug: 'oppo-f27-pro-plus-5g',
    brand: 'OPPO',
    modelName: 'F27 Pro+ 5G',
    generation: 'F27',
    status: 'active',
    launchDate: '2024-06',
    pricing: {
      startingPrice: 27999,
      maximumPrice: 29999,
      launchPrice: 27999,
      currentPrice: 27999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'OPPO India Official Store',
    },
    display: {
      displaySize: 6.7,
      displayType: '3D Curved 120Hz AMOLED',
      resolution: '2412 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 950,
      hdr: 'None',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '93.0%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7050 (6nm)',
      cpu: 'Octa-core (2x2.6 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G68 MC4',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 600000,
    },
    cameras: {
      rearCameraSetup: 'Dual (64MP + 2MP)',
      mainCamera: '64 MP, f/1.7',
      ultrawideCamera: 'None',
      telephotoCamera: 'None (2 MP portrait)',
      frontCamera: '8 MP, f/2.0',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 67,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.7 x 74.3 x 7.89 mm',
      weight: 177,
      materials: 'Damage-proof 360 Armor body, vegan leather with Cosmos ring',
      waterResistance: 'IP66, IP68, and IP69 water & dust resistance',
      colors: ['Dusk Pink', 'Midnight Navy'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'ColorOS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Single speaker with 300% ultra volume mode',
      stereo: false,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.oppo.com/in/smartphones/series-f/f27-pro-plus-5g/',
      productPage: 'https://www.oppo.com/in/store/product/f27-pro-plus-5g.html',
      specSheetUrl: 'https://www.oppo.com/in/smartphones/series-f/f27-pro-plus-5g/specs/',
      verifiedDate: '2024-06',
    },
  },

  // ── REALME ──
  {
    id: 'realme-gt-7-pro',
    slug: 'realme-gt-7-pro',
    brand: 'realme',
    modelName: 'realme GT 7 Pro',
    generation: 'GT 7',
    status: 'active',
    launchDate: '2024-11',
    pricing: {
      startingPrice: 59999,
      maximumPrice: 65999,
      launchPrice: 59999,
      currentPrice: 59999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'realme India Official Store',
    },
    display: {
      displaySize: 6.78,
      displayType: '1.5K 120Hz Eco2 OLED Plus (Samsung)',
      resolution: '2780 x 1264 pixels',
      refreshRate: 120,
      peakBrightness: 6000,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Armor Glass',
      screenToBodyRatio: '92.0%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Elite (3nm)',
      cpu: 'Octa-core (2x4.32 GHz Oryon V2 Phoenix & 6x3.53 GHz)',
      gpu: 'Adreno 830',
      ramOptions: ['12GB', '16GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 2980000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 8MP) with Underwater Photography Mode',
      mainCamera: '50 MP Sony IMX906, f/1.8, 24mm, 1/1.56", OIS',
      ultrawideCamera: '8 MP Sony IMX355, f/2.2, 112˚',
      telephotoCamera: '50 MP Sony LYT-600 periscope, 3x optical, 120x digital, OIS',
      frontCamera: '16 MP, f/2.45',
      videoRecording: '8K@24fps, 4K@60fps, 1080p@240fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5800,
      wiredCharging: 120,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.5 x 76.9 x 8.55 mm',
      weight: 222.8,
      materials: 'Spacecraft-grade aluminum frame, Mars design textured glass back',
      waterResistance: 'IP68 and IP69 water and dust resistance',
      colors: ['Mars Orange', 'Galaxy Grey'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'realme UI 6.0',
      launchOS: 'Android 15',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Hi-Res audio',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Ultrasonic under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.realme.com/in/realme-gt-7-pro',
      productPage: 'https://buy.realme.com/in/goods/722',
      specSheetUrl: 'https://www.realme.com/in/realme-gt-7-pro/specs',
      verifiedDate: '2024-11',
    },
  },

  {
    id: 'realme-gt-6',
    slug: 'realme-gt-6',
    brand: 'realme',
    modelName: 'realme GT 6',
    generation: 'GT 6',
    status: 'active',
    launchDate: '2024-06',
    pricing: {
      startingPrice: 38999,
      maximumPrice: 44999,
      launchPrice: 40999,
      currentPrice: 38999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'realme India Official Store',
    },
    display: {
      displaySize: 6.78,
      displayType: '1.5K 120Hz 8T LTPO AMOLED',
      resolution: '2780 x 1264 pixels',
      refreshRate: 120,
      peakBrightness: 6000,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '91.8%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8s Gen 3 (4nm)',
      cpu: 'Octa-core (1x3.0 GHz Cortex-X4 & 4x2.8 GHz & 3x2.0 GHz)',
      gpu: 'Adreno 735',
      ramOptions: ['8GB', '12GB', '16GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 1550000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 8MP) with AI Night Vision',
      mainCamera: '50 MP Sony LYT-808, f/1.69, OIS',
      ultrawideCamera: '8 MP Sony IMX355, f/2.2, 112˚',
      telephotoCamera: '50 MP Samsung JN5 portrait telephoto, 2x optical, OIS',
      frontCamera: '32 MP Sony IMX615, f/2.45, 4K30',
      videoRecording: '4K@60fps, 1080p@120fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5500,
      wiredCharging: 120,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.0 x 75.1 x 8.6 mm',
      weight: 199,
      materials: 'Plastic frame, nano-mirror glass back',
      waterResistance: 'IP65',
      colors: ['Fluid Silver', 'Razor Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'realme UI 5.0 with NEXT AI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.realme.com/in/realme-gt-6',
      productPage: 'https://buy.realme.com/in/goods/702',
      specSheetUrl: 'https://www.realme.com/in/realme-gt-6/specs',
      verifiedDate: '2024-06',
    },
  },

  {
    id: 'realme-13-pro-plus-5g',
    slug: 'realme-13-pro-plus-5g',
    brand: 'realme',
    modelName: 'realme 13 Pro+ 5G',
    generation: '13 Pro',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 29999,
      maximumPrice: 34999,
      launchPrice: 32999,
      currentPrice: 29999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'realme India Official Store',
    },
    display: {
      displaySize: 6.7,
      displayType: '120Hz Curved AMOLED',
      resolution: '2412 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 2000,
      hdr: 'None',
      protection: 'Corning Gorilla Glass 7i',
      screenToBodyRatio: '93.0%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7s Gen 2 (4nm)',
      cpu: 'Octa-core (4x2.4 GHz Cortex-A78 & 4x1.95 GHz Cortex-A55)',
      gpu: 'Adreno 710',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 3.1',
      antutuScore: 660000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 8MP) Monet Design HYPERIMAGE+',
      mainCamera: '50 MP Sony LYT-701, f/1.88, OIS',
      ultrawideCamera: '8 MP, f/2.2, 112˚',
      telephotoCamera: '50 MP Sony LYT-600 periscope, 3x optical, 6x in-sensor, OIS',
      frontCamera: '32 MP Sony, f/2.45',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5200,
      wiredCharging: 80,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.3 x 73.9 x 8.23 mm',
      weight: 185.5,
      materials: 'Monet-inspired glass back (Miracle Shining Glass) / Vegan leather',
      waterResistance: 'IP65',
      colors: ['Monet Gold', 'Emerald Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'realme UI 5.0',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.realme.com/in/realme-13-pro-plus-5g',
      productPage: 'https://buy.realme.com/in/goods/710',
      specSheetUrl: 'https://www.realme.com/in/realme-13-pro-plus-5g/specs',
      verifiedDate: '2024-07',
    },
  },
];

const variants: MobileVariant[] = [
  // Find X8 Pro
  {
    id: 'oppo-find-x8-pro-16-512',
    modelId: 'oppo-find-x8-pro',
    ram: '16GB',
    storage: '512GB',
    price: 99999,
    mrp: 99999,
    colors: ['Space Black', 'Pearl White'],
    status: 'active',
    verified: true,
    source: 'OPPO India Official Store',
  },

  // Reno 12 Pro 5G
  {
    id: 'oppo-reno-12-pro-5g-12-256',
    modelId: 'oppo-reno-12-pro-5g',
    ram: '12GB',
    storage: '256GB',
    price: 36999,
    mrp: 36999,
    colors: ['Sunset Gold', 'Space Brown'],
    status: 'active',
    verified: true,
    source: 'OPPO India Official Store',
  },
  {
    id: 'oppo-reno-12-pro-5g-12-512',
    modelId: 'oppo-reno-12-pro-5g',
    ram: '12GB',
    storage: '512GB',
    price: 40999,
    mrp: 40999,
    colors: ['Sunset Gold', 'Space Brown'],
    status: 'active',
    verified: true,
    source: 'OPPO India Official Store',
  },

  // F27 Pro+ 5G
  {
    id: 'oppo-f27-pro-plus-5g-8-128',
    modelId: 'oppo-f27-pro-plus-5g',
    ram: '8GB',
    storage: '128GB',
    price: 27999,
    mrp: 27999,
    colors: ['Dusk Pink', 'Midnight Navy'],
    status: 'active',
    verified: true,
    source: 'OPPO India Official Store',
  },
  {
    id: 'oppo-f27-pro-plus-5g-8-256',
    modelId: 'oppo-f27-pro-plus-5g',
    ram: '8GB',
    storage: '256GB',
    price: 29999,
    mrp: 29999,
    colors: ['Dusk Pink', 'Midnight Navy'],
    status: 'active',
    verified: true,
    source: 'OPPO India Official Store',
  },

  // realme GT 7 Pro
  {
    id: 'realme-gt-7-pro-12-256',
    modelId: 'realme-gt-7-pro',
    ram: '12GB',
    storage: '256GB',
    price: 59999,
    mrp: 59999,
    colors: ['Mars Orange', 'Galaxy Grey'],
    status: 'active',
    verified: true,
    source: 'realme India Official Store',
  },
  {
    id: 'realme-gt-7-pro-16-512',
    modelId: 'realme-gt-7-pro',
    ram: '16GB',
    storage: '512GB',
    price: 65999,
    mrp: 65999,
    colors: ['Mars Orange', 'Galaxy Grey'],
    status: 'active',
    verified: true,
    source: 'realme India Official Store',
  },

  // realme GT 6
  {
    id: 'realme-gt-6-8-256',
    modelId: 'realme-gt-6',
    ram: '8GB',
    storage: '256GB',
    price: 38999,
    mrp: 40999,
    colors: ['Fluid Silver', 'Razor Green'],
    status: 'active',
    verified: true,
    source: 'realme India Official Store',
  },
  {
    id: 'realme-gt-6-12-256',
    modelId: 'realme-gt-6',
    ram: '12GB',
    storage: '256GB',
    price: 41999,
    mrp: 43999,
    colors: ['Fluid Silver', 'Razor Green'],
    status: 'active',
    verified: true,
    source: 'realme India Official Store',
  },
  {
    id: 'realme-gt-6-16-512',
    modelId: 'realme-gt-6',
    ram: '16GB',
    storage: '512GB',
    price: 44999,
    mrp: 47999,
    colors: ['Fluid Silver', 'Razor Green'],
    status: 'active',
    verified: true,
    source: 'realme India Official Store',
  },

  // realme 13 Pro+ 5G
  {
    id: 'realme-13-pro-plus-5g-8-256',
    modelId: 'realme-13-pro-plus-5g',
    ram: '8GB',
    storage: '256GB',
    price: 29999,
    mrp: 32999,
    colors: ['Monet Gold', 'Emerald Green'],
    status: 'active',
    verified: true,
    source: 'realme India Official Store',
  },
  {
    id: 'realme-13-pro-plus-5g-12-512',
    modelId: 'realme-13-pro-plus-5g',
    ram: '12GB',
    storage: '512GB',
    price: 34999,
    mrp: 36999,
    colors: ['Monet Gold', 'Emerald Green'],
    status: 'active',
    verified: true,
    source: 'realme India Official Store',
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    "modelId": "oppo-find-x8-pro",
    "modelName": "Find X8 Pro",
    "brand": "OPPO",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/oppo-find-x8-pro.jpg",
        "angle": "front",
        "source": "OPPO Official (GSMArena CDN)",
        "verified": true,
        "alt": "OPPO Find X8 Pro front quad-curve display"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/oppo/oppo-find-x8-pro-3.jpg",
        "angle": "back",
        "source": "OPPO Official (GSMArena CDN)",
        "verified": true,
        "alt": "OPPO Find X8 Pro Hasselblad quad camera rear view"
      }
    ]
  },
  {
    "modelId": "oppo-reno-12-pro-5g",
    "modelName": "Reno 12 Pro 5G",
    "brand": "OPPO",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/oppo/oppo-reno12-pro-cn-1.jpg",
        "angle": "front",
        "source": "OPPO Official (GSMArena CDN)",
        "verified": true,
        "alt": "OPPO Reno 12 Pro 5G front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/oppo/oppo-reno12-pro-cn-2.jpg",
        "angle": "back",
        "source": "OPPO Official (GSMArena CDN)",
        "verified": true,
        "alt": "OPPO Reno 12 Pro 5G sunset gold rear view"
      }
    ]
  },
  {
    "modelId": "oppo-f27-pro-plus-5g",
    "modelName": "F27 Pro+ 5G",
    "brand": "realme",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/oppo-f27.jpg",
        "angle": "front",
        "source": "OPPO Official (GSMArena CDN)",
        "verified": true,
        "alt": "OPPO F27 Pro+ 5G front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/oppo/oppo-f27-pro-plus-2.jpg",
        "angle": "back",
        "source": "OPPO Official (GSMArena CDN)",
        "verified": true,
        "alt": "OPPO F27 Pro+ 5G waterproof leather rear view"
      }
    ]
  },
  {
    "modelId": "realme-gt-7-pro",
    "modelName": "realme GT 7 Pro",
    "brand": "realme",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/realme-gt7-pro.jpg",
        "angle": "front",
        "source": "realme Official (GSMArena CDN)",
        "verified": true,
        "alt": "realme GT 7 Pro front Eco² OLED display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/realme/realme-gt7-pro-1.jpg",
        "angle": "back",
        "source": "realme Official (GSMArena CDN)",
        "verified": true,
        "alt": "realme GT 7 Pro Mars Design rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/realme/realme-gt7-pro-2.jpg",
        "angle": "side",
        "source": "realme Official (GSMArena CDN)",
        "verified": true,
        "alt": "realme GT 7 Pro space exploration profile"
      }
    ]
  },
  {
    "modelId": "realme-gt-6",
    "modelName": "realme GT 6",
    "brand": "realme",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/realme-gt6.jpg",
        "angle": "front",
        "source": "realme Official (GSMArena CDN)",
        "verified": true,
        "alt": "realme GT 6 front 6000-nit display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/realme/realme-gt6-1.jpg",
        "angle": "back",
        "source": "realme Official (GSMArena CDN)",
        "verified": true,
        "alt": "realme GT 6 mirror nano-coating rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/realme/realme-gt6-2.jpg",
        "angle": "side",
        "source": "realme Official (GSMArena CDN)",
        "verified": true,
        "alt": "realme GT 6 profile"
      }
    ]
  },
  {
    "modelId": "realme-13-pro-plus-5g",
    "modelName": "realme 13 Pro+ 5G",
    "brand": "OPPO",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/realme-13-pro-plus.jpg",
        "angle": "front",
        "source": "realme Official (GSMArena CDN)",
        "verified": true,
        "alt": "realme 13 Pro+ 5G front curved display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/realme/realme-13-pro-plus-1.jpg",
        "angle": "back",
        "source": "realme Official (GSMArena CDN)",
        "verified": true,
        "alt": "realme 13 Pro+ 5G Monet Gold Monet glass rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/realme/realme-13-pro-plus-2.jpg",
        "angle": "side",
        "source": "realme Official (GSMArena CDN)",
        "verified": true,
        "alt": "realme 13 Pro+ 5G profile"
      }
    ]
  }
];

export const bbkOppoRealmeBundle: MobileBrandBundle = {
  models,
  variants,
  images,
};
