import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  // ── VIVO ──
  {
    id: 'vivo-x100-pro',
    slug: 'vivo-x100-pro',
    brand: 'Vivo',
    modelName: 'Vivo X100 Pro',
    generation: 'X100',
    status: 'active',
    launchDate: '2024-01',
    pricing: {
      startingPrice: 89999,
      maximumPrice: 89999,
      launchPrice: 89999,
      currentPrice: 89999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Vivo India Official Store',
    },
    display: {
      displaySize: 6.78,
      displayType: 'LTPO AMOLED (8T Backplane)',
      resolution: '2800 x 1260 pixels',
      refreshRate: 120,
      peakBrightness: 3000,
      hdr: 'HDR10+',
      protection: 'Armor Glass / Victus',
      screenToBodyRatio: '89.8%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 9300 (4nm) with Vivo V3 Imaging Chip',
      cpu: 'Octa-core All-Big-Core (1x3.25 GHz Cortex-X4 & 3x2.85 GHz Cortex-X4 & 4x2.0 GHz Cortex-A720)',
      gpu: 'Immortalis-G720 MC12',
      ramOptions: ['16GB'],
      storageOptions: ['512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 2160000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 50MP) ZEISS APO',
      mainCamera: '50 MP 1-inch Sony IMX989, f/1.75, OIS, ZEISS T* coating',
      ultrawideCamera: '50 MP Samsung JN1, f/2.0, 119˚',
      telephotoCamera: '50 MP ZEISS APO Floating Periscope, 4.3x optical zoom, 100x digital, OIS, macro',
      frontCamera: '32 MP, f/2.0',
      videoRecording: '8K@30fps, 4K@60fps Cinematic Portrait Video',
      ois: true,
    },
    battery: {
      batteryCapacity: 5400,
      wiredCharging: 100,
      wirelessCharging: 50,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 3.2 Gen 1',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '164.1 x 75.3 x 8.9 mm',
      weight: 225,
      materials: 'Sunburst stainless steel camera bezel, Fluorite AG Glass back',
      waterResistance: 'IP68',
      colors: ['Asteroid Black', 'Sunset Orange'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 14 (Upgradable to 15)',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.vivo.com/in/products/x100-pro',
      productPage: 'https://shop.vivo.com/in/product/10293',
      specSheetUrl: 'https://www.vivo.com/in/products/param/x100-pro',
      verifiedDate: '2024-01',
    },
  },

  {
    id: 'vivo-v40-pro',
    slug: 'vivo-v40-pro',
    brand: 'Vivo',
    modelName: 'Vivo V40 Pro',
    generation: 'V40',
    status: 'active',
    launchDate: '2024-08',
    pricing: {
      startingPrice: 49999,
      maximumPrice: 55999,
      launchPrice: 49999,
      currentPrice: 49999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Vivo India Official Store',
    },
    display: {
      displaySize: 6.78,
      displayType: '1.5K 120Hz 3D Curved AMOLED',
      resolution: '2800 x 1260 pixels',
      refreshRate: 120,
      peakBrightness: 4500,
      hdr: 'HDR10+',
      protection: 'Schott Xensation α',
      screenToBodyRatio: '90.1%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 9200+ (4nm)',
      cpu: 'Octa-core (1x3.35 GHz Cortex-X3 & 3x3.0 GHz & 4x2.0 GHz)',
      gpu: 'Immortalis-G715 MC11',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 3.1',
      antutuScore: 1610000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 50MP) ZEISS with Smart Aura Light',
      mainCamera: '50 MP Sony IMX921, f/1.88, OIS',
      ultrawideCamera: '50 MP, f/2.0, 119˚',
      telephotoCamera: '50 MP Sony IMX816 portrait telephoto, 2x optical, OIS',
      frontCamera: '50 MP ZEISS Group Selfie, f/2.0, 92˚, autofocus',
      videoRecording: '4K@60fps (front and rear)',
      ois: true,
    },
    battery: {
      batteryCapacity: 5500,
      wiredCharging: 80,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '164.4 x 75.1 x 7.58 mm',
      weight: 192,
      materials: 'Ultra-slim glass body, metallic frame',
      waterResistance: 'IP68 and IP69 dust & water resistance',
      colors: ['Ganges Blue', 'Titanium Grey'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.vivo.com/in/products/v40-pro',
      productPage: 'https://shop.vivo.com/in/product/10344',
      specSheetUrl: 'https://www.vivo.com/in/products/param/v40-pro',
      verifiedDate: '2024-08',
    },
  },

  {
    id: 'vivo-t3-ultra',
    slug: 'vivo-t3-ultra',
    brand: 'Vivo',
    modelName: 'Vivo T3 Ultra',
    generation: 'T3',
    status: 'active',
    launchDate: '2024-09',
    pricing: {
      startingPrice: 31999,
      maximumPrice: 35999,
      launchPrice: 31999,
      currentPrice: 31999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Vivo India / Flipkart',
    },
    display: {
      displaySize: 6.78,
      displayType: '1.5K 120Hz 3D Curved AMOLED',
      resolution: '2800 x 1260 pixels',
      refreshRate: 120,
      peakBrightness: 4500,
      hdr: 'HDR10+',
      protection: 'Schott Xensation α',
      screenToBodyRatio: '90.1%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 9200+ (4nm)',
      cpu: 'Octa-core (1x3.35 GHz Cortex-X3 & 3x3.0 GHz & 4x2.0 GHz)',
      gpu: 'Immortalis-G715 MC11',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 1600000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 8MP) with Smart Aura Light',
      mainCamera: '50 MP Sony IMX921, f/1.88, OIS',
      ultrawideCamera: '8 MP, f/2.2, 120˚',
      telephotoCamera: 'None',
      frontCamera: '50 MP, f/2.0, autofocus',
      videoRecording: '4K@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5500,
      wiredCharging: 80,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '164.2 x 74.9 x 7.58 mm',
      weight: 192,
      materials: 'Curved glass back, plastic frame',
      waterResistance: 'IP68 water & dust resistance',
      colors: ['Frost Green', 'Lunar Grey'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.vivo.com/in/products/t3-ultra',
      productPage: 'https://shop.vivo.com/in/product/10355',
      specSheetUrl: 'https://www.vivo.com/in/products/param/t3-ultra',
      verifiedDate: '2024-09',
    },
  },

  {
    id: 'vivo-t3x-5g',
    slug: 'vivo-t3x-5g',
    brand: 'Vivo',
    modelName: 'Vivo T3x 5G',
    generation: 'T3',
    status: 'active',
    launchDate: '2024-04',
    pricing: {
      startingPrice: 13499,
      maximumPrice: 16499,
      launchPrice: 13499,
      currentPrice: 13499,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Vivo India / Flipkart',
    },
    display: {
      displaySize: 6.72,
      displayType: '120Hz Ultra Vision FHD+ LCD',
      resolution: '2408 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 1000,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '86.4%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 6 Gen 1 (4nm)',
      cpu: 'Octa-core (4x2.2 GHz Cortex-A78 & 4x1.8 GHz Cortex-A55)',
      gpu: 'Adreno 710',
      ramOptions: ['4GB', '6GB', '8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 560000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP)',
      mainCamera: '50 MP, f/1.8',
      ultrawideCamera: 'None',
      telephotoCamera: 'None (2 MP Bokeh)',
      frontCamera: '8 MP, f/2.05',
      videoRecording: '4K@30fps (on 8GB RAM variant)',
      ois: false,
    },
    battery: {
      batteryCapacity: 6000,
      wiredCharging: 44,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.1',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '165.7 x 76.0 x 7.99 mm',
      weight: 199,
      materials: 'Plastic frame & 2.5D composite back',
      waterResistance: 'IP64 dust and water resistance',
      colors: ['Celestial Green', 'Crimson Bliss'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with 300% audio booster',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.vivo.com/in/products/t3x-5g',
      productPage: 'https://shop.vivo.com/in/product/10321',
      specSheetUrl: 'https://www.vivo.com/in/products/param/t3x-5g',
      verifiedDate: '2024-04',
    },
  },

  // ── iQOO ──
  {
    id: 'iqoo-13-5g',
    slug: 'iqoo-13-5g',
    brand: 'iQOO',
    modelName: 'iQOO 13 5G',
    generation: '13',
    status: 'active',
    launchDate: '2024-12',
    pricing: {
      startingPrice: 54999,
      maximumPrice: 59999,
      launchPrice: 54999,
      currentPrice: 54999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'iQOO India / Amazon India',
    },
    display: {
      displaySize: 6.82,
      displayType: '2K 144Hz BOE Q10 Ultra Eyecare LTPO AMOLED',
      resolution: '3168 x 1440 pixels',
      refreshRate: 144,
      peakBrightness: 4500,
      hdr: 'HDR10+, Dolby Vision',
      protection: 'Crystal Armor Glass',
      screenToBodyRatio: '90.4%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Elite (3nm) with SuperComputing Chip Q2',
      cpu: 'Octa-core (2x4.32 GHz Oryon V2 & 6x3.53 GHz)',
      gpu: 'Adreno 830',
      ramOptions: ['12GB', '16GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 2950000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 50MP) with Monster Halo LED ring',
      mainCamera: '50 MP Sony IMX921, f/1.88, VCS, OIS',
      ultrawideCamera: '50 MP Samsung JN1, f/2.0, 119˚',
      telephotoCamera: '50 MP Sony IMX816 portrait telephoto, 2x/4x optical zoom, OIS',
      frontCamera: '32 MP, f/2.45, 4K60',
      videoRecording: '8K@30fps, 4K@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 6000,
      wiredCharging: 120,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 3.2 Gen 1',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '163.4 x 76.7 x 7.99 mm',
      weight: 207,
      materials: 'Aviation-grade aluminum frame, AG glass back, Monster Halo RGB lighting',
      waterResistance: 'IP68 and IP69 water and dust resistance',
      colors: ['Legend (BMW M Motorsport)', 'Nardo Grey'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 15',
      launchOS: 'Android 15',
      promisedMajorUpdates: 4,
      securityUpdatePolicy: '5 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Ultrasonic under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.iqoo.com/in/products/iqoo13',
      productPage: 'https://shop.iqoo.com/in/product/10360',
      specSheetUrl: 'https://www.iqoo.com/in/products/param/iqoo13',
      verifiedDate: '2024-12',
    },
  },

  {
    id: 'iqoo-neo-9-pro-5g',
    slug: 'iqoo-neo-9-pro-5g',
    brand: 'iQOO',
    modelName: 'iQOO Neo 9 Pro 5G',
    generation: 'Neo 9',
    status: 'active',
    launchDate: '2024-02',
    pricing: {
      startingPrice: 35999,
      maximumPrice: 39999,
      launchPrice: 37999,
      currentPrice: 35999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'iQOO India / Amazon India',
    },
    display: {
      displaySize: 6.78,
      displayType: '1.5K 144Hz 8T LTPO AMOLED',
      resolution: '2800 x 1260 pixels',
      refreshRate: 144,
      peakBrightness: 3000,
      hdr: 'HDR10+',
      protection: 'Schott Xensation Up',
      screenToBodyRatio: '89.7%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Gen 2 (4nm) with SuperComputing Chip Q1',
      cpu: 'Octa-core (1x3.2 GHz Cortex-X3 & 4x2.8 GHz & 3x2.0 GHz)',
      gpu: 'Adreno 740',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 4.0',
      antutuScore: 1680000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 8MP)',
      mainCamera: '50 MP Sony IMX920, f/1.88, VCS, OIS',
      ultrawideCamera: '8 MP, f/2.2, 116˚',
      telephotoCamera: 'None',
      frontCamera: '16 MP, f/2.5',
      videoRecording: '8K@30fps, 4K@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5160,
      wiredCharging: 120,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '163.5 x 75.7 x 7.99 mm (Leather: 8.34mm)',
      weight: 190,
      materials: 'Dual-tone vegan leather (Fiery Red) / AG glass (Conqueror Black)',
      waterResistance: 'IP54',
      colors: ['Fiery Red', 'Conqueror Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.iqoo.com/in/products/neo9pro',
      productPage: 'https://shop.iqoo.com/in/product/10311',
      specSheetUrl: 'https://www.iqoo.com/in/products/param/neo9pro',
      verifiedDate: '2024-02',
    },
  },

  {
    id: 'iqoo-z9s-pro-5g',
    slug: 'iqoo-z9s-pro-5g',
    brand: 'iQOO',
    modelName: 'iQOO Z9s Pro 5G',
    generation: 'Z9s',
    status: 'active',
    launchDate: '2024-08',
    pricing: {
      startingPrice: 24999,
      maximumPrice: 28999,
      launchPrice: 24999,
      currentPrice: 24999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'iQOO India / Amazon India',
    },
    display: {
      displaySize: 6.77,
      displayType: '120Hz 3D Curved AMOLED',
      resolution: '2392 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 4500,
      hdr: 'HDR10+',
      protection: 'Schott Xensation Up',
      screenToBodyRatio: '90.2%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7 Gen 3 (4nm)',
      cpu: 'Octa-core (1x2.63 GHz Cortex-A715 & 4x2.4 GHz & 3x1.8 GHz)',
      gpu: 'Adreno 720',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 820000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 8MP) with Aura Light',
      mainCamera: '50 MP Sony IMX882, f/1.79, OIS',
      ultrawideCamera: '8 MP, f/2.2, 120˚',
      telephotoCamera: 'None',
      frontCamera: '16 MP, f/2.45',
      videoRecording: '4K@30fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5500,
      wiredCharging: 80,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.4',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '163.7 x 75.0 x 7.49 mm',
      weight: 185,
      materials: 'Vegan leather (Luxe Marble) / matte composite (Flamboyant Orange)',
      waterResistance: 'IP64 dust and splash resistant',
      colors: ['Luxe Marble', 'Flamboyant Orange'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.iqoo.com/in/products/z9spro',
      productPage: 'https://shop.iqoo.com/in/product/10350',
      specSheetUrl: 'https://www.iqoo.com/in/products/param/z9spro',
      verifiedDate: '2024-08',
    },
  },
];

const variants: MobileVariant[] = [
  // Vivo X100 Pro
  {
    id: 'vivo-x100-pro-16-512',
    modelId: 'vivo-x100-pro',
    ram: '16GB',
    storage: '512GB',
    price: 89999,
    mrp: 89999,
    colors: ['Asteroid Black', 'Sunset Orange'],
    status: 'active',
    verified: true,
    source: 'Vivo India Official Store',
  },

  // Vivo V40 Pro
  {
    id: 'vivo-v40-pro-8-256',
    modelId: 'vivo-v40-pro',
    ram: '8GB',
    storage: '256GB',
    price: 49999,
    mrp: 49999,
    colors: ['Ganges Blue', 'Titanium Grey'],
    status: 'active',
    verified: true,
    source: 'Vivo India Official Store',
  },
  {
    id: 'vivo-v40-pro-12-512',
    modelId: 'vivo-v40-pro',
    ram: '12GB',
    storage: '512GB',
    price: 55999,
    mrp: 55999,
    colors: ['Ganges Blue', 'Titanium Grey'],
    status: 'active',
    verified: true,
    source: 'Vivo India Official Store',
  },

  // Vivo T3 Ultra
  {
    id: 'vivo-t3-ultra-8-128',
    modelId: 'vivo-t3-ultra',
    ram: '8GB',
    storage: '128GB',
    price: 31999,
    mrp: 31999,
    colors: ['Frost Green', 'Lunar Grey'],
    status: 'active',
    verified: true,
    source: 'Vivo India / Flipkart',
  },
  {
    id: 'vivo-t3-ultra-8-256',
    modelId: 'vivo-t3-ultra',
    ram: '8GB',
    storage: '256GB',
    price: 33999,
    mrp: 33999,
    colors: ['Frost Green', 'Lunar Grey'],
    status: 'active',
    verified: true,
    source: 'Vivo India / Flipkart',
  },
  {
    id: 'vivo-t3-ultra-12-256',
    modelId: 'vivo-t3-ultra',
    ram: '12GB',
    storage: '256GB',
    price: 35999,
    mrp: 35999,
    colors: ['Frost Green', 'Lunar Grey'],
    status: 'active',
    verified: true,
    source: 'Vivo India / Flipkart',
  },

  // Vivo T3x 5G
  {
    id: 'vivo-t3x-5g-4-128',
    modelId: 'vivo-t3x-5g',
    ram: '4GB',
    storage: '128GB',
    price: 13499,
    mrp: 13499,
    colors: ['Celestial Green', 'Crimson Bliss'],
    status: 'active',
    verified: true,
    source: 'Vivo India / Flipkart',
  },
  {
    id: 'vivo-t3x-5g-6-128',
    modelId: 'vivo-t3x-5g',
    ram: '6GB',
    storage: '128GB',
    price: 14999,
    mrp: 14999,
    colors: ['Celestial Green', 'Crimson Bliss'],
    status: 'active',
    verified: true,
    source: 'Vivo India / Flipkart',
  },
  {
    id: 'vivo-t3x-5g-8-128',
    modelId: 'vivo-t3x-5g',
    ram: '8GB',
    storage: '128GB',
    price: 16499,
    mrp: 16499,
    colors: ['Celestial Green', 'Crimson Bliss'],
    status: 'active',
    verified: true,
    source: 'Vivo India / Flipkart',
  },

  // iQOO 13
  {
    id: 'iqoo-13-5g-12-256',
    modelId: 'iqoo-13-5g',
    ram: '12GB',
    storage: '256GB',
    price: 54999,
    mrp: 54999,
    colors: ['Legend (BMW M Motorsport)', 'Nardo Grey'],
    status: 'active',
    verified: true,
    source: 'iQOO India / Amazon India',
  },
  {
    id: 'iqoo-13-5g-16-512',
    modelId: 'iqoo-13-5g',
    ram: '16GB',
    storage: '512GB',
    price: 59999,
    mrp: 59999,
    colors: ['Legend (BMW M Motorsport)', 'Nardo Grey'],
    status: 'active',
    verified: true,
    source: 'iQOO India / Amazon India',
  },

  // iQOO Neo 9 Pro
  {
    id: 'iqoo-neo-9-pro-5g-8-128',
    modelId: 'iqoo-neo-9-pro-5g',
    ram: '8GB',
    storage: '128GB',
    price: 35999,
    mrp: 37999,
    colors: ['Fiery Red', 'Conqueror Black'],
    status: 'active',
    verified: true,
    source: 'iQOO India / Amazon India',
  },
  {
    id: 'iqoo-neo-9-pro-5g-8-256',
    modelId: 'iqoo-neo-9-pro-5g',
    ram: '8GB',
    storage: '256GB',
    price: 37999,
    mrp: 39999,
    colors: ['Fiery Red', 'Conqueror Black'],
    status: 'active',
    verified: true,
    source: 'iQOO India / Amazon India',
  },

  // iQOO Z9s Pro
  {
    id: 'iqoo-z9s-pro-5g-8-128',
    modelId: 'iqoo-z9s-pro-5g',
    ram: '8GB',
    storage: '128GB',
    price: 24999,
    mrp: 24999,
    colors: ['Luxe Marble', 'Flamboyant Orange'],
    status: 'active',
    verified: true,
    source: 'iQOO India / Amazon India',
  },
  {
    id: 'iqoo-z9s-pro-5g-8-256',
    modelId: 'iqoo-z9s-pro-5g',
    ram: '8GB',
    storage: '256GB',
    price: 26999,
    mrp: 26999,
    colors: ['Luxe Marble', 'Flamboyant Orange'],
    status: 'active',
    verified: true,
    source: 'iQOO India / Amazon India',
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    "modelId": "vivo-x100-pro",
    "modelName": "Vivo X100 Pro",
    "brand": "Vivo",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/vivo-x100-pro.jpg",
        "angle": "front",
        "source": "Vivo Official (GSMArena CDN)",
        "verified": true,
        "alt": "Vivo X100 Pro front curved display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/vivo/vivo-x100-pro-1.jpg",
        "angle": "back",
        "source": "Vivo Official (GSMArena CDN)",
        "verified": true,
        "alt": "Vivo X100 Pro Zeiss sun halo rear camera view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/vivo/vivo-x100-pro-2.jpg",
        "angle": "side",
        "source": "Vivo Official (GSMArena CDN)",
        "verified": true,
        "alt": "Vivo X100 Pro profile"
      }
    ]
  },
  {
    "modelId": "vivo-v40-pro",
    "modelName": "Vivo V40 Pro",
    "brand": "Vivo",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/vivo-v40-pro.jpg",
        "angle": "front",
        "source": "Vivo Official (GSMArena CDN)",
        "verified": true,
        "alt": "Vivo V40 Pro front curved display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/vivo/vivo-v40-pro-1.jpg",
        "angle": "back",
        "source": "Vivo Official (GSMArena CDN)",
        "verified": true,
        "alt": "Vivo V40 Pro Zeiss multi-focal portrait rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/vivo/vivo-v40-pro-2.jpg",
        "angle": "side",
        "source": "Vivo Official (GSMArena CDN)",
        "verified": true,
        "alt": "Vivo V40 Pro profile"
      }
    ]
  },
  {
    "modelId": "vivo-t3-ultra",
    "modelName": "Vivo T3 Ultra",
    "brand": "Vivo",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/vivo-t3-ultra.jpg",
        "angle": "front",
        "source": "Vivo Official (GSMArena CDN)",
        "verified": true,
        "alt": "Vivo T3 Ultra front curved AMOLED view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/vivo/vivo-t3-ultra-1.jpg",
        "angle": "back",
        "source": "Vivo Official (GSMArena CDN)",
        "verified": true,
        "alt": "Vivo T3 Ultra rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/vivo/vivo-t3-ultra-2.jpg",
        "angle": "side",
        "source": "Vivo Official (GSMArena CDN)",
        "verified": true,
        "alt": "Vivo T3 Ultra profile"
      }
    ]
  },
  {
    "modelId": "vivo-t3x-5g",
    "modelName": "Vivo T3x 5G",
    "brand": "iQOO",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/vivo-t3x.jpg",
        "angle": "front",
        "source": "Vivo Official (GSMArena CDN)",
        "verified": true,
        "alt": "Vivo T3x 5G front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/vivo/vivo-t3x-1.jpg",
        "angle": "back",
        "source": "Vivo Official (GSMArena CDN)",
        "verified": true,
        "alt": "Vivo T3x 5G celestial green rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/vivo/vivo-t3x-2.jpg",
        "angle": "side",
        "source": "Vivo Official (GSMArena CDN)",
        "verified": true,
        "alt": "Vivo T3x 5G profile"
      }
    ]
  },
  {
    "modelId": "iqoo-13-5g",
    "modelName": "iQOO 13 5G",
    "brand": "iQOO",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/vivo-iqoo-13.jpg",
        "angle": "front",
        "source": "iQOO Official (GSMArena CDN)",
        "verified": true,
        "alt": "iQOO 13 5G front 2K AMOLED display"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/vivo/vivo-iqoo-13-1.jpg",
        "angle": "back",
        "source": "iQOO Official (GSMArena CDN)",
        "verified": true,
        "alt": "iQOO 13 5G RGB halo ring rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/vivo/vivo-iqoo-13-2.jpg",
        "angle": "side",
        "source": "iQOO Official (GSMArena CDN)",
        "verified": true,
        "alt": "iQOO 13 5G profile"
      }
    ]
  },
  {
    "modelId": "iqoo-neo-9-pro-5g",
    "modelName": "iQOO Neo 9 Pro 5G",
    "brand": "iQOO",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/vivo-neo9-pro.jpg",
        "angle": "front",
        "source": "iQOO Official (GSMArena CDN)",
        "verified": true,
        "alt": "iQOO Neo 9 Pro 5G front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/vivo/vivo-neo9-1.jpg",
        "angle": "back",
        "source": "iQOO Official (GSMArena CDN)",
        "verified": true,
        "alt": "iQOO Neo 9 Pro 5G dual-tone fiery red rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/vivo/vivo-neo9-2.jpg",
        "angle": "side",
        "source": "iQOO Official (GSMArena CDN)",
        "verified": true,
        "alt": "iQOO Neo 9 Pro 5G profile"
      }
    ]
  },
  {
    "modelId": "iqoo-z9s-pro-5g",
    "modelName": "iQOO Z9s Pro 5G",
    "brand": "Vivo",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/vivo-iqoo-z9s-pro.jpg",
        "angle": "front",
        "source": "iQOO Official (GSMArena CDN)",
        "verified": true,
        "alt": "iQOO Z9s Pro 5G front 3D curved display"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/vivo/vivo-iqoo-z9s-pro-1.jpg",
        "angle": "back",
        "source": "iQOO Official (GSMArena CDN)",
        "verified": true,
        "alt": "iQOO Z9s Pro 5G luxe marble rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/vivo/vivo-iqoo-z9s-pro-2.jpg",
        "angle": "side",
        "source": "iQOO Official (GSMArena CDN)",
        "verified": true,
        "alt": "iQOO Z9s Pro 5G profile"
      }
    ]
  }
];

export const bbkVivoBundle: MobileBrandBundle = {
  models,
  variants,
  images,
};
