import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  {
    id: 'google-pixel-9-pro-xl',
    slug: 'google-pixel-9-pro-xl',
    brand: 'Google',
    modelName: 'Pixel 9 Pro XL',
    generation: 'Pixel 9',
    status: 'active',
    launchDate: '2024-08',
    pricing: {
      startingPrice: 124999,
      maximumPrice: 139999,
      launchPrice: 124999,
      currentPrice: 124999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Google Store India / Flipkart',
    },
    display: {
      displaySize: 6.8,
      displayType: 'Super Actua LTPO OLED',
      resolution: '2992 x 1344 pixels (486 ppi)',
      refreshRate: 120,
      peakBrightness: 3000,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '87.8%',
    },
    performance: {
      chipset: 'Google Tensor G4 with Titan M2 security coprocessor',
      cpu: 'Octa-core (1x3.1 GHz Cortex-X4 & 3x2.6 GHz Cortex-A720 & 4x1.92 GHz Cortex-A520)',
      gpu: 'Mali-G715 MC7',
      ramOptions: ['16GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 3.1',
      antutuScore: 1350000,
      geekbenchSingle: 1980,
      geekbenchMulti: 5050,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 48MP + 48MP)',
      mainCamera: '50 MP Octa PD, f/1.68, 25mm, 1/1.31", Dual Pixel PDAF, OIS',
      ultrawideCamera: '48 MP Quad PD, f/1.7, 12mm, 123˚, Macro Focus',
      telephotoCamera: '48 MP Quad PD, f/2.8, 110mm, 5x optical zoom, 30x Super Res Zoom, OIS',
      frontCamera: '42 MP Dual PD, f/2.2, 103˚ ultrawide with autofocus, 4K60',
      videoRecording: '8K@30fps (via Video Boost), 4K@60fps, Night Sight Video, 10-bit HDR',
      ois: true,
    },
    battery: {
      batteryCapacity: 5060,
      wiredCharging: 37,
      wirelessCharging: 23,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7 (802.11be)',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 3.2',
      simConfig: 'Dual SIM (Nano-SIM and eSIM)',
    },
    physical: {
      dimensions: '162.8 x 76.6 x 8.5 mm',
      weight: 221,
      materials: 'Polished metal frame, silky matte glass back (Victus 2)',
      waterResistance: 'IP68 dust/water resistant',
      colors: ['Obsidian', 'Porcelain', 'Hazel', 'Rose Quartz'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Pixel UI (Gemini Nano on-device)',
      launchOS: 'Android 14 (Upgradable to 15)',
      promisedMajorUpdates: 7,
      securityUpdatePolicy: '7 years of OS, security and Pixel Drop updates',
    },
    audio: {
      speakers: 'Stereo speakers with Spatial Audio',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Ultrasonic under display',
      faceUnlock: true,
      biometricNotes: 'Class 3 biometrics eligible for banking authentication',
    },
    keyHighlights: [
      'Gemini Nano multimodal on-device AI integration and Pixel Studio',
      'Class-leading computational photography with 50MP + 48MP + 48MP sensors',
      'Super Actua display hitting up to 3000 nits peak outdoor brightness',
      'Upgraded ultrasonic fingerprint scanner with instant recognition',
      'Guaranteed 7 full years of Android OS and Feature Drop updates',
    ],
    pros: [
      'Best-in-class still photography with effortless point-and-shoot accuracy',
      '7 years of guaranteed updates direct from Google',
      'Clean pure Android software with useful Pixel intelligence features',
      'Gorgeous matte glass design and premium IP68 build',
    ],
    cons: [
      'Peak benchmark scores lag behind Snapdragon 8 Elite',
      'High price point in the Indian market',
      '37W charging is slower than Chinese flagship competitors',
    ],
    sources: {
      officialWebsite: 'https://store.google.com/in/product/pixel_9_pro',
      productPage: 'https://store.google.com/in/product/pixel_9_pro_specs',
      specSheetUrl: 'https://support.google.com/pixelphone/answer/7158570',
      verifiedDate: '2024-08',
    },
  },

  {
    id: 'google-pixel-9-pro',
    slug: 'google-pixel-9-pro',
    brand: 'Google',
    modelName: 'Pixel 9 Pro',
    generation: 'Pixel 9',
    status: 'active',
    launchDate: '2024-08',
    pricing: {
      startingPrice: 109999,
      maximumPrice: 109999,
      launchPrice: 109999,
      currentPrice: 109999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Google Store India / Flipkart',
    },
    display: {
      displaySize: 6.3,
      displayType: 'Super Actua LTPO OLED',
      resolution: '2856 x 1280 pixels (495 ppi)',
      refreshRate: 120,
      peakBrightness: 3000,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '87.6%',
    },
    performance: {
      chipset: 'Google Tensor G4 with Titan M2 coprocessor',
      cpu: 'Octa-core (1x3.1 GHz & 3x2.6 GHz & 4x1.92 GHz)',
      gpu: 'Mali-G715 MC7',
      ramOptions: ['16GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 1340000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 48MP + 48MP)',
      mainCamera: '50 MP, f/1.68, OIS',
      ultrawideCamera: '48 MP, f/1.7, 123˚, Macro Focus',
      telephotoCamera: '48 MP, f/2.8, 5x optical, OIS',
      frontCamera: '42 MP Dual PD, f/2.2, 4K60',
      videoRecording: '8K@30fps (Video Boost), 4K@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4700,
      wiredCharging: 27,
      wirelessCharging: 21,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 3.2',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '152.8 x 72.0 x 8.5 mm',
      weight: 199,
      materials: 'Polished aluminum frame, matte Victus 2 back',
      waterResistance: 'IP68',
      colors: ['Obsidian', 'Porcelain', 'Hazel', 'Rose Quartz'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Pixel UI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 7,
      securityUpdatePolicy: '7 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Ultrasonic under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://store.google.com/in/product/pixel_9_pro',
      productPage: 'https://store.google.com/in/product/pixel_9_pro_specs',
      specSheetUrl: 'https://support.google.com/pixelphone/answer/7158570',
      verifiedDate: '2024-08',
    },
  },

  {
    id: 'google-pixel-9',
    slug: 'google-pixel-9',
    brand: 'Google',
    modelName: 'Pixel 9',
    generation: 'Pixel 9',
    status: 'active',
    launchDate: '2024-08',
    pricing: {
      startingPrice: 79999,
      maximumPrice: 79999,
      launchPrice: 79999,
      currentPrice: 79999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Google Store India / Flipkart',
    },
    display: {
      displaySize: 6.3,
      displayType: 'Actua OLED',
      resolution: '2424 x 1080 pixels (422 ppi)',
      refreshRate: 120,
      peakBrightness: 2700,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '86.1%',
    },
    performance: {
      chipset: 'Google Tensor G4 (4nm)',
      cpu: 'Octa-core (1x3.1 GHz & 3x2.6 GHz & 4x1.92 GHz)',
      gpu: 'Mali-G715 MC7',
      ramOptions: ['12GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 1280000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 48MP)',
      mainCamera: '50 MP Octa PD, f/1.68, OIS',
      ultrawideCamera: '48 MP Quad PD, f/1.7, 123˚, Macro Focus',
      telephotoCamera: 'None (2x in-sensor zoom)',
      frontCamera: '10.5 MP Dual PD, f/2.2, autofocus',
      videoRecording: '4K@60fps, 10-bit HDR',
      ois: true,
    },
    battery: {
      batteryCapacity: 4700,
      wiredCharging: 27,
      wirelessCharging: 15,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 3.2',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '152.8 x 72.0 x 8.5 mm',
      weight: 198,
      materials: 'Satin metal frame, polished glass back (Victus 2)',
      waterResistance: 'IP68',
      colors: ['Peony', 'Wintergreen', 'Porcelain', 'Obsidian'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Pixel UI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 7,
      securityUpdatePolicy: '7 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Ultrasonic under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://store.google.com/in/product/pixel_9',
      productPage: 'https://store.google.com/in/product/pixel_9_specs',
      specSheetUrl: 'https://support.google.com/pixelphone/answer/7158570',
      verifiedDate: '2024-08',
    },
  },

  {
    id: 'google-pixel-8a',
    slug: 'google-pixel-8a',
    brand: 'Google',
    modelName: 'Pixel 8a',
    generation: 'Pixel 8',
    status: 'active',
    launchDate: '2024-05',
    pricing: {
      startingPrice: 43999,
      maximumPrice: 49999,
      launchPrice: 52999,
      currentPrice: 43999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Google Store India / Flipkart',
    },
    display: {
      displaySize: 6.1,
      displayType: 'Actua OLED',
      resolution: '2400 x 1080 pixels (430 ppi)',
      refreshRate: 120,
      peakBrightness: 2000,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '81.6%',
    },
    performance: {
      chipset: 'Google Tensor G3 (4nm)',
      cpu: 'Nona-core (1x3.0 GHz Cortex-X3 & 4x2.45 GHz & 4x2.15 GHz)',
      gpu: 'Immortalis-G715s MC10',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 1080000,
    },
    cameras: {
      rearCameraSetup: 'Dual (64MP + 13MP)',
      mainCamera: '64 MP Quad PD, f/1.89, OIS',
      ultrawideCamera: '13 MP, f/2.2, 120˚',
      telephotoCamera: 'None',
      frontCamera: '13 MP, f/2.2, 4K30',
      videoRecording: '4K@60fps, 1080p@240fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4492,
      wiredCharging: 18,
      wirelessCharging: 7.5,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 3.2',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '152.1 x 72.7 x 8.9 mm',
      weight: 188,
      materials: 'Matte composite back, aluminum frame',
      waterResistance: 'IP67',
      colors: ['Aloe', 'Bay', 'Porcelain', 'Obsidian'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Pixel UI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 7,
      securityUpdatePolicy: '7 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://store.google.com/in/product/pixel_8a',
      productPage: 'https://store.google.com/in/product/pixel_8a_specs',
      specSheetUrl: 'https://support.google.com/pixelphone/answer/7158570',
      verifiedDate: '2024-05',
    },
  },

  {
    id: 'google-pixel-8',
    slug: 'google-pixel-8',
    brand: 'Google',
    modelName: 'Pixel 8',
    generation: 'Pixel 8',
    status: 'active',
    launchDate: '2023-10',
    pricing: {
      startingPrice: 54999,
      maximumPrice: 61999,
      launchPrice: 75999,
      currentPrice: 54999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Google Store India / Flipkart',
    },
    display: {
      displaySize: 6.2,
      displayType: 'Actua OLED',
      resolution: '2400 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 2000,
      hdr: 'HDR10+',
      protection: 'Gorilla Glass Victus',
      screenToBodyRatio: '85.5%',
    },
    performance: {
      chipset: 'Google Tensor G3 (4nm)',
      cpu: 'Nona-core (1x3.0 GHz & 4x2.45 GHz & 4x2.15 GHz)',
      gpu: 'Immortalis-G715s MC10',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 1120000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 12MP)',
      mainCamera: '50 MP, f/1.68, OIS',
      ultrawideCamera: '12 MP, f/2.2, 126˚, macro',
      telephotoCamera: 'None',
      frontCamera: '10.5 MP, f/2.2',
      videoRecording: '4K@60fps, 10-bit HDR',
      ois: true,
    },
    battery: {
      batteryCapacity: 4575,
      wiredCharging: 27,
      wirelessCharging: 18,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 3.2',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '150.5 x 70.8 x 8.9 mm',
      weight: 187,
      materials: 'Aluminum frame, Gorilla Glass Victus back',
      waterResistance: 'IP68',
      colors: ['Hazel', 'Obsidian', 'Rose', 'Mint'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Pixel UI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 7,
      securityUpdatePolicy: '7 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://store.google.com/in/product/pixel_8',
      productPage: 'https://store.google.com/in/product/pixel_8_specs',
      specSheetUrl: 'https://support.google.com/pixelphone/answer/7158570',
      verifiedDate: '2023-10',
    },
  },

  {
    id: 'google-pixel-7a',
    slug: 'google-pixel-7a',
    brand: 'Google',
    modelName: 'Pixel 7a',
    generation: 'Pixel 7',
    status: 'active',
    launchDate: '2023-05',
    pricing: {
      startingPrice: 34999,
      maximumPrice: 34999,
      launchPrice: 43999,
      currentPrice: 34999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Google Store India / Flipkart',
    },
    display: {
      displaySize: 6.1,
      displayType: 'OLED',
      resolution: '2400 x 1080 pixels',
      refreshRate: 90,
      peakBrightness: 1000,
      hdr: 'HDR',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '81.8%',
    },
    performance: {
      chipset: 'Google Tensor G2 (5nm)',
      cpu: 'Octa-core (2x2.85 GHz Cortex-X1 & 2x2.35 GHz & 4x1.8 GHz)',
      gpu: 'Mali-G710 MP7',
      ramOptions: ['8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 3.1',
      antutuScore: 890000,
    },
    cameras: {
      rearCameraSetup: 'Dual (64MP + 13MP)',
      mainCamera: '64 MP Quad PD, f/1.89, OIS',
      ultrawideCamera: '13 MP, f/2.2, 120˚',
      telephotoCamera: 'None',
      frontCamera: '13 MP, f/2.2',
      videoRecording: '4K@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4385,
      wiredCharging: 18,
      wirelessCharging: 7.5,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 3.2',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '152.0 x 72.9 x 9.0 mm',
      weight: 193,
      materials: 'Aluminum frame, thermoformed plastic back',
      waterResistance: 'IP67',
      colors: ['Charcoal', 'Snow', 'Sea', 'Coral'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Pixel UI',
      launchOS: 'Android 13',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '5 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://store.google.com/in/product/pixel_7a',
      productPage: 'https://store.google.com/in/product/pixel_7a_specs',
      specSheetUrl: 'https://support.google.com/pixelphone/answer/7158570',
      verifiedDate: '2023-05',
    },
  },

  {
    id: 'google-pixel-9-pro-fold',
    slug: 'google-pixel-9-pro-fold',
    brand: 'Google',
    modelName: 'Pixel 9 Pro Fold',
    generation: 'Pixel 9',
    status: 'active',
    launchDate: '2024-08',
    pricing: {
      startingPrice: 172999,
      maximumPrice: 172999,
      launchPrice: 172999,
      currentPrice: 172999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Google Store India / Flipkart',
    },
    display: {
      displaySize: 8.0,
      displayType: 'Foldable LTPO Super Actua OLED (Inner) + 6.3" Actua OLED (Outer)',
      resolution: '2076 x 2152 pixels (Inner), 2424 x 1080 pixels (Outer)',
      refreshRate: 120,
      peakBrightness: 2700,
      hdr: 'HDR10+',
      protection: 'Ultra Thin Glass inner, Gorilla Glass Victus 2 cover',
      screenToBodyRatio: '88.9%',
    },
    performance: {
      chipset: 'Google Tensor G4 (4nm)',
      cpu: 'Octa-core (1x3.1 GHz Cortex-X4 & 3x2.6 GHz Cortex-A720 & 4x1.92 GHz Cortex-A520)',
      gpu: 'Mali-G715 MC7',
      ramOptions: ['16GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 4.0',
      antutuScore: 1250000,
    },
    cameras: {
      rearCameraSetup: 'Triple (48MP + 10.5MP + 10.8MP)',
      mainCamera: '48 MP Quad PD, f/1.7, 25mm, Dual Pixel PDAF, OIS',
      ultrawideCamera: '10.5 MP, f/2.2, 127˚, macro focus',
      telephotoCamera: '10.8 MP Dual PD telephoto, 5x optical zoom, OIS',
      frontCamera: '10 MP inner + 10 MP cover, f/2.2, 4K60',
      videoRecording: '4K@60fps, 10-bit HDR',
      ois: true,
    },
    battery: {
      batteryCapacity: 4650,
      wiredCharging: 21,
      wirelessCharging: 7.5,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7 (802.11be)',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 3.2',
      simConfig: 'Dual SIM (Nano-SIM + eSIM)',
    },
    physical: {
      dimensions: '155.2 x 150.2 x 5.1 mm (unfolded), 155.2 x 77.1 x 10.5 mm (folded)',
      weight: 257,
      materials: 'Aerospace grade high-strength aluminum alloy, Gorilla Glass Victus 2 back',
      waterResistance: 'IPX8 (water resistant up to 1.5m for 30 min)',
      colors: ['Obsidian', 'Porcelain'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Pixel UI (Gemini Nano on-device)',
      launchOS: 'Android 14',
      promisedMajorUpdates: 7,
      securityUpdatePolicy: '7 years of OS and security updates',
    },
    audio: {
      speakers: 'Spatial Audio stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://store.google.com/in/product/pixel_9_pro_fold',
      productPage: 'https://store.google.com/in/product/pixel_9_pro_fold_specs',
      verifiedDate: '2024-08',
    },
  },

  {
    id: 'google-pixel-8-pro',
    slug: 'google-pixel-8-pro',
    brand: 'Google',
    modelName: 'Pixel 8 Pro',
    generation: 'Pixel 8',
    status: 'active',
    launchDate: '2023-10',
    pricing: {
      startingPrice: 79999,
      maximumPrice: 94999,
      launchPrice: 106999,
      currentPrice: 79999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Google Store India / Flipkart',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Super Actua LTPO OLED',
      resolution: '2992 x 1344 pixels at 489 ppi',
      refreshRate: 120,
      peakBrightness: 2400,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '87.4%',
    },
    performance: {
      chipset: 'Google Tensor G3 (4nm)',
      cpu: 'Nona-core (1x3.0 GHz Cortex-X3 & 4x2.45 GHz Cortex-A715 & 4x2.15 GHz Cortex-A510)',
      gpu: 'Immortalis-G715s MC10',
      ramOptions: ['12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 1180000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 48MP + 48MP)',
      mainCamera: '50 MP Octa PD, f/1.68, multi-directional PDAF, Laser AF, OIS',
      ultrawideCamera: '48 MP Quad PD, f/1.95, 126˚, macro focus',
      telephotoCamera: '48 MP Quad PD telephoto, 5x optical zoom, OIS',
      frontCamera: '10.5 MP Dual PD, f/2.2, autofocus, 4K60',
      videoRecording: '4K@60fps, 10-bit HDR, Video Boost, Night Sight Video',
      ois: true,
    },
    battery: {
      batteryCapacity: 5050,
      wiredCharging: 30,
      wirelessCharging: 23,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 3.2',
      simConfig: 'Dual SIM (Nano-SIM + eSIM)',
    },
    physical: {
      dimensions: '162.6 x 76.5 x 8.8 mm',
      weight: 213,
      materials: 'Polished aluminum frame, matte Gorilla Glass Victus 2 back',
      waterResistance: 'IP68',
      colors: ['Bay', 'Porcelain', 'Obsidian'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Pixel UI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 7,
      securityUpdatePolicy: '7 years of OS & security updates',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
      biometricNotes: 'Includes integrated rear infrared thermometer sensor',
    },
    sources: {
      officialWebsite: 'https://store.google.com/in/product/pixel_8_pro',
      productPage: 'https://store.google.com/in/product/pixel_8_pro_specs',
      verifiedDate: '2023-10',
    },
  },

  {
    id: 'google-pixel-7-pro',
    slug: 'google-pixel-7-pro',
    brand: 'Google',
    modelName: 'Pixel 7 Pro',
    generation: 'Pixel 7',
    status: 'discontinued',
    launchDate: '2022-10',
    pricing: {
      startingPrice: 54999,
      maximumPrice: 62999,
      launchPrice: 84999,
      currentPrice: 54999,
      currency: 'INR',
      priceEffectiveDate: '2024-06',
      source: 'Google Store India / Flipkart',
    },
    display: {
      displaySize: 6.7,
      displayType: 'LTPO AMOLED',
      resolution: '3120 x 1440 pixels (QHD+)',
      refreshRate: 120,
      peakBrightness: 1500,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass Victus',
      screenToBodyRatio: '88.7%',
    },
    performance: {
      chipset: 'Google Tensor G2 (5nm)',
      cpu: 'Octa-core (2x2.85 GHz Cortex-X1 & 2x2.35 GHz Cortex-A78 & 4x1.80 GHz Cortex-A55)',
      gpu: 'Mali-G710 MP7',
      ramOptions: ['12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 920000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 12MP + 48MP)',
      mainCamera: '50 MP, f/1.85, multi-directional PDAF, Laser AF, OIS',
      ultrawideCamera: '12 MP, f/2.2, 126˚, AF macro',
      telephotoCamera: '48 MP telephoto, 5x optical zoom, OIS',
      frontCamera: '10.8 MP, f/2.2, 4K60',
      videoRecording: '4K@60fps, 10-bit HDR',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 23,
      wirelessCharging: 23,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.2',
      nfc: true,
      usb: 'USB Type-C 3.2',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.9 x 76.6 x 8.9 mm',
      weight: 212,
      materials: 'Polished aluminum frame, Gorilla Glass Victus front and back',
      waterResistance: 'IP68',
      colors: ['Hazel', 'Snow', 'Obsidian'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Pixel UI',
      launchOS: 'Android 13',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '5 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://store.google.com/in/product/pixel_7_pro',
      productPage: 'https://support.google.com/pixelphone/answer/7158570',
      verifiedDate: '2022-10',
    },
  },

  {
    id: 'google-pixel-7',
    slug: 'google-pixel-7',
    brand: 'Google',
    modelName: 'Pixel 7',
    generation: 'Pixel 7',
    status: 'discontinued',
    launchDate: '2022-10',
    pricing: {
      startingPrice: 39999,
      maximumPrice: 44999,
      launchPrice: 59999,
      currentPrice: 39999,
      currency: 'INR',
      priceEffectiveDate: '2024-06',
      source: 'Google Store India / Flipkart',
    },
    display: {
      displaySize: 6.3,
      displayType: 'AMOLED',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 90,
      peakBrightness: 1400,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass Victus',
      screenToBodyRatio: '84.9%',
    },
    performance: {
      chipset: 'Google Tensor G2 (5nm)',
      cpu: 'Octa-core (2x2.85 GHz Cortex-X1 & 2x2.35 GHz & 4x1.80 GHz)',
      gpu: 'Mali-G710 MP7',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 900000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 12MP)',
      mainCamera: '50 MP, f/1.85, PDAF, Laser AF, OIS',
      ultrawideCamera: '12 MP, f/2.2, 114˚',
      telephotoCamera: 'None',
      frontCamera: '10.8 MP, f/2.2, 4K60',
      videoRecording: '4K@60fps, 10-bit HDR',
      ois: true,
    },
    battery: {
      batteryCapacity: 4355,
      wiredCharging: 20,
      wirelessCharging: 20,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.2',
      nfc: true,
      usb: 'USB Type-C 3.2',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '155.6 x 73.2 x 8.7 mm',
      weight: 197,
      materials: 'Matte aluminum frame, Gorilla Glass Victus front and back',
      waterResistance: 'IP68',
      colors: ['Lemongrass', 'Snow', 'Obsidian'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Pixel UI',
      launchOS: 'Android 13',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '5 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://store.google.com/in/product/pixel_7',
      productPage: 'https://support.google.com/pixelphone/answer/7158570',
      verifiedDate: '2022-10',
    },
  },

  {
    id: 'google-pixel-6a',
    slug: 'google-pixel-6a',
    brand: 'Google',
    modelName: 'Pixel 6a',
    generation: 'Pixel 6',
    status: 'discontinued',
    launchDate: '2022-07',
    pricing: {
      startingPrice: 27999,
      maximumPrice: 29999,
      launchPrice: 43999,
      currentPrice: 27999,
      currency: 'INR',
      priceEffectiveDate: '2024-06',
      source: 'Google Store India / Flipkart',
    },
    display: {
      displaySize: 6.1,
      displayType: 'OLED',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 60,
      peakBrightness: 800,
      hdr: 'HDR',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '83.0%',
    },
    performance: {
      chipset: 'Google Tensor (5nm)',
      cpu: 'Octa-core (2x2.80 GHz Cortex-X1 & 2x2.25 GHz & 4x1.80 GHz)',
      gpu: 'Mali-G78 MP20',
      ramOptions: ['6GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 3.1',
      antutuScore: 810000,
    },
    cameras: {
      rearCameraSetup: 'Dual (12.2MP + 12MP)',
      mainCamera: '12.2 MP, f/1.7, Dual Pixel PDAF, OIS',
      ultrawideCamera: '12 MP, f/2.2, 114˚',
      telephotoCamera: 'None',
      frontCamera: '8 MP, f/2.0',
      videoRecording: '4K@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4410,
      wiredCharging: 18,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.2',
      nfc: true,
      usb: 'USB Type-C 3.1',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '152.2 x 71.8 x 8.9 mm',
      weight: 178,
      materials: 'Aluminum frame, plastic back, Gorilla Glass 3 front',
      waterResistance: 'IP67',
      colors: ['Chalk', 'Charcoal', 'Sage'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Pixel UI',
      launchOS: 'Android 12',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '5 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: false,
    },
    sources: {
      officialWebsite: 'https://store.google.com/in/product/pixel_6a',
      productPage: 'https://support.google.com/pixelphone/answer/7158570',
      verifiedDate: '2022-07',
    },
  },
];

const variants: MobileVariant[] = [
  // Pixel 9 Pro XL
  {
    id: 'google-pixel-9-pro-xl-16-256',
    modelId: 'google-pixel-9-pro-xl',
    ram: '16GB',
    storage: '256GB',
    price: 124999,
    mrp: 124999,
    colors: ['Obsidian', 'Porcelain', 'Hazel', 'Rose Quartz'],
    status: 'active',
    verified: true,
    source: 'Google Store India / Flipkart',
  },
  {
    id: 'google-pixel-9-pro-xl-16-512',
    modelId: 'google-pixel-9-pro-xl',
    ram: '16GB',
    storage: '512GB',
    price: 139999,
    mrp: 139999,
    colors: ['Obsidian', 'Hazel'],
    status: 'active',
    verified: true,
    source: 'Google Store India / Flipkart',
  },

  // Pixel 9 Pro
  {
    id: 'google-pixel-9-pro-16-256',
    modelId: 'google-pixel-9-pro',
    ram: '16GB',
    storage: '256GB',
    price: 109999,
    mrp: 109999,
    colors: ['Obsidian', 'Porcelain', 'Hazel', 'Rose Quartz'],
    status: 'active',
    verified: true,
    source: 'Google Store India / Flipkart',
  },

  // Pixel 9
  {
    id: 'google-pixel-9-12-256',
    modelId: 'google-pixel-9',
    ram: '12GB',
    storage: '256GB',
    price: 79999,
    mrp: 79999,
    colors: ['Peony', 'Wintergreen', 'Porcelain', 'Obsidian'],
    status: 'active',
    verified: true,
    source: 'Google Store India / Flipkart',
  },

  // Pixel 8a
  {
    id: 'google-pixel-8a-8-128',
    modelId: 'google-pixel-8a',
    ram: '8GB',
    storage: '128GB',
    price: 43999,
    mrp: 52999,
    colors: ['Aloe', 'Bay', 'Porcelain', 'Obsidian'],
    status: 'active',
    verified: true,
    source: 'Google Store India / Flipkart',
  },
  {
    id: 'google-pixel-8a-8-256',
    modelId: 'google-pixel-8a',
    ram: '8GB',
    storage: '256GB',
    price: 49999,
    mrp: 59999,
    colors: ['Obsidian'],
    status: 'active',
    verified: true,
    source: 'Google Store India / Flipkart',
  },

  // Pixel 8
  {
    id: 'google-pixel-8-8-128',
    modelId: 'google-pixel-8',
    ram: '8GB',
    storage: '128GB',
    price: 54999,
    mrp: 75999,
    colors: ['Hazel', 'Obsidian', 'Rose'],
    status: 'active',
    verified: true,
    source: 'Google Store India / Flipkart',
  },
  {
    id: 'google-pixel-8-8-256',
    modelId: 'google-pixel-8',
    ram: '8GB',
    storage: '256GB',
    price: 61999,
    mrp: 82999,
    colors: ['Hazel', 'Obsidian'],
    status: 'active',
    verified: true,
    source: 'Google Store India / Flipkart',
  },

  // Pixel 7a
  {
    id: 'google-pixel-7a-8-128',
    modelId: 'google-pixel-7a',
    ram: '8GB',
    storage: '128GB',
    price: 34999,
    mrp: 43999,
    colors: ['Charcoal', 'Snow', 'Sea'],
    status: 'active',
    verified: true,
    source: 'Google Store India / Flipkart',
  },

  // Pixel 9 Pro Fold
  {
    id: 'google-pixel-9-pro-fold-16-256',
    modelId: 'google-pixel-9-pro-fold',
    ram: '16GB',
    storage: '256GB',
    price: 172999,
    mrp: 172999,
    colors: ['Obsidian', 'Porcelain'],
    status: 'active',
    verified: true,
    source: 'Google Store India / Flipkart',
  },
  {
    id: 'google-pixel-9-pro-fold-16-512',
    modelId: 'google-pixel-9-pro-fold',
    ram: '16GB',
    storage: '512GB',
    price: 189999,
    mrp: 189999,
    colors: ['Obsidian'],
    status: 'active',
    verified: true,
    source: 'Google Store India / Flipkart',
  },

  // Pixel 8 Pro
  {
    id: 'google-pixel-8-pro-12-128',
    modelId: 'google-pixel-8-pro',
    ram: '12GB',
    storage: '128GB',
    price: 79999,
    mrp: 106999,
    colors: ['Bay', 'Porcelain', 'Obsidian'],
    status: 'active',
    verified: true,
    source: 'Google Store India / Flipkart',
  },
  {
    id: 'google-pixel-8-pro-12-256',
    modelId: 'google-pixel-8-pro',
    ram: '12GB',
    storage: '256GB',
    price: 86999,
    mrp: 113999,
    colors: ['Bay', 'Obsidian'],
    status: 'active',
    verified: true,
    source: 'Google Store India / Flipkart',
  },

  // Pixel 7 Pro
  {
    id: 'google-pixel-7-pro-12-128',
    modelId: 'google-pixel-7-pro',
    ram: '12GB',
    storage: '128GB',
    price: 54999,
    mrp: 84999,
    colors: ['Hazel', 'Snow', 'Obsidian'],
    status: 'discontinued',
    verified: true,
    source: 'Google Store India / Flipkart',
  },
  {
    id: 'google-pixel-7-pro-12-256',
    modelId: 'google-pixel-7-pro',
    ram: '12GB',
    storage: '256GB',
    price: 62999,
    mrp: 92999,
    colors: ['Hazel', 'Obsidian'],
    status: 'discontinued',
    verified: true,
    source: 'Google Store India / Flipkart',
  },

  // Pixel 7
  {
    id: 'google-pixel-7-8-128',
    modelId: 'google-pixel-7',
    ram: '8GB',
    storage: '128GB',
    price: 39999,
    mrp: 59999,
    colors: ['Lemongrass', 'Snow', 'Obsidian'],
    status: 'discontinued',
    verified: true,
    source: 'Google Store India / Flipkart',
  },
  {
    id: 'google-pixel-7-8-256',
    modelId: 'google-pixel-7',
    ram: '8GB',
    storage: '256GB',
    price: 44999,
    mrp: 64999,
    colors: ['Snow', 'Obsidian'],
    status: 'discontinued',
    verified: true,
    source: 'Google Store India / Flipkart',
  },

  // Pixel 6a
  {
    id: 'google-pixel-6a-6-128',
    modelId: 'google-pixel-6a',
    ram: '6GB',
    storage: '128GB',
    price: 27999,
    mrp: 43999,
    colors: ['Chalk', 'Charcoal', 'Sage'],
    status: 'discontinued',
    verified: true,
    source: 'Google Store India / Flipkart',
  },
  {
    id: 'google-pixel-6a-6-256',
    modelId: 'google-pixel-6a',
    ram: '6GB',
    storage: '256GB',
    price: 29999,
    mrp: 47999,
    colors: ['Charcoal'],
    status: 'discontinued',
    verified: true,
    source: 'Google Store India / Flipkart',
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    "modelId": "google-pixel-9-pro-xl",
    "modelName": "Pixel 9 Pro XL",
    "brand": "Google",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-9-pro-xl-1.jpg",
        "angle": "front",
        "source": "Google Official (GSMArena CDN)",
        "verified": true,
        "alt": "Google Pixel 9 Pro XL front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-9-pro-xl-2.jpg",
        "angle": "back",
        "source": "Google Official (GSMArena CDN)",
        "verified": true,
        "alt": "Google Pixel 9 Pro XL camera visor rear view"
      }
    ]
  },
  {
    "modelId": "google-pixel-9-pro",
    "modelName": "Pixel 9 Pro",
    "brand": "Google",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-9-pro-1.jpg",
        "angle": "front",
        "source": "Google Official (GSMArena CDN)",
        "verified": true,
        "alt": "Google Pixel 9 Pro front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-9-pro-2.jpg",
        "angle": "back",
        "source": "Google Official (GSMArena CDN)",
        "verified": true,
        "alt": "Google Pixel 9 Pro camera visor rear view"
      }
    ]
  },
  {
    "modelId": "google-pixel-9",
    "modelName": "Pixel 9",
    "brand": "Google",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-9-1.jpg",
        "angle": "front",
        "source": "Google Official (GSMArena CDN)",
        "verified": true,
        "alt": "Google Pixel 9 front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-9-2.jpg",
        "angle": "back",
        "source": "Google Official (GSMArena CDN)",
        "verified": true,
        "alt": "Google Pixel 9 dual camera rear view"
      }
    ]
  },
  {
    "modelId": "google-pixel-8a",
    "modelName": "Pixel 8a",
    "brand": "Google",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-8a.jpg",
        "angle": "front",
        "source": "Google Official (GSMArena CDN)",
        "verified": true,
        "alt": "Google Pixel 8a front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-8a-1.jpg",
        "angle": "back",
        "source": "Google Official (GSMArena CDN)",
        "verified": true,
        "alt": "Google Pixel 8a matte rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-8a-2.jpg",
        "angle": "side",
        "source": "Google Official (GSMArena CDN)",
        "verified": true,
        "alt": "Google Pixel 8a aluminum frame profile"
      }
    ]
  },
  {
    "modelId": "google-pixel-8",
    "modelName": "Pixel 8",
    "brand": "Google",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-8.jpg",
        "angle": "front",
        "source": "Google Official (GSMArena CDN)",
        "verified": true,
        "alt": "Google Pixel 8 front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-8-1.jpg",
        "angle": "back",
        "source": "Google Official (GSMArena CDN)",
        "verified": true,
        "alt": "Google Pixel 8 camera bar rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-8-2.jpg",
        "angle": "side",
        "source": "Google Official (GSMArena CDN)",
        "verified": true,
        "alt": "Google Pixel 8 profile"
      }
    ]
  },
  {
    "modelId": "google-pixel-7a",
    "modelName": "Pixel 7a",
    "brand": "Google",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-7a.jpg",
        "angle": "front",
        "source": "Google Official (GSMArena CDN)",
        "verified": true,
        "alt": "Google Pixel 7a front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-7a-1.jpg",
        "angle": "back",
        "source": "Google Official (GSMArena CDN)",
        "verified": true,
        "alt": "Google Pixel 7a Sea blue rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-7a-2.jpg",
        "angle": "side",
        "source": "Google Official (GSMArena CDN)",
        "verified": true,
        "alt": "Google Pixel 7a profile"
      }
    ]
  }
,

  {
    "modelId": "google-pixel-9-pro-fold",
    "modelName": "Pixel 9 Pro Fold",
    "brand": "Google",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-9-pro-fold-.jpg",
        "angle": "front",
        "source": "Google Official (GSMArena CDN)",
        "verified": true,
        "alt": "Google Pixel 9 Pro Fold unfolded display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-9-pro-fold-1.jpg",
        "angle": "back",
        "source": "Google Official (GSMArena CDN)",
        "verified": true,
        "alt": "Google Pixel 9 Pro Fold rear camera view"
      }
    ]
  },
  {
    "modelId": "google-pixel-8-pro",
    "modelName": "Pixel 8 Pro",
    "brand": "Google",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-8-pro.jpg",
        "angle": "front",
        "source": "Google Official (GSMArena CDN)",
        "verified": true,
        "alt": "Google Pixel 8 Pro front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-8-pro-1.jpg",
        "angle": "back",
        "source": "Google Official (GSMArena CDN)",
        "verified": true,
        "alt": "Google Pixel 8 Pro Bay blue rear view"
      }
    ]
  },
  {
    "modelId": "google-pixel-7-pro",
    "modelName": "Pixel 7 Pro",
    "brand": "Google",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel7-pro.jpg",
        "angle": "front",
        "source": "Google Official (GSMArena CDN)",
        "verified": true,
        "alt": "Google Pixel 7 Pro front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/google/google-pixel7-pro-1.jpg",
        "angle": "back",
        "source": "Google Official (GSMArena CDN)",
        "verified": true,
        "alt": "Google Pixel 7 Pro Hazel rear camera visor"
      }
    ]
  },
  {
    "modelId": "google-pixel-7",
    "modelName": "Pixel 7",
    "brand": "Google",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel7.jpg",
        "angle": "front",
        "source": "Google Official (GSMArena CDN)",
        "verified": true,
        "alt": "Google Pixel 7 front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-7-1.jpg",
        "angle": "back",
        "source": "Google Official (GSMArena CDN)",
        "verified": true,
        "alt": "Google Pixel 7 rear camera visor"
      }
    ]
  },
  {
    "modelId": "google-pixel-6a",
    "modelName": "Pixel 6a",
    "brand": "Google",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-6a.jpg",
        "angle": "front",
        "source": "Google Official (GSMArena CDN)",
        "verified": true,
        "alt": "Google Pixel 6a front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-6a-1.jpg",
        "angle": "back",
        "source": "Google Official (GSMArena CDN)",
        "verified": true,
        "alt": "Google Pixel 6a two-tone rear view"
      }
    ]
  },
];

export const googleBundle: MobileBrandBundle = {
  models,
  variants,
  images,
};
