import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  {
    id: 'hmd-skyline',
    slug: 'hmd-skyline',
    brand: 'HMD',
    modelName: 'HMD Skyline',
    generation: 'Skyline',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 35999,
      maximumPrice: 35999,
      launchPrice: 35999,
      currentPrice: 35999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'HMD India / Amazon Store',
    },
    display: {
      displaySize: 6.55,
      displayType: '144Hz FHD+ pOLED, 1000 nits peak',
      resolution: '2400 x 1080 pixels',
      refreshRate: 144,
      peakBrightness: 1000,
      hdr: 'HDR10',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '87.8%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7s Gen 2 (4nm)',
      cpu: 'Octa-core (4x2.40 GHz Cortex-A78 & 4x1.95 GHz Cortex-A55)',
      gpu: 'Adreno 710',
      ramOptions: ['12GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 610000,
    },
    cameras: {
      rearCameraSetup: 'Triple (108MP Hybrid OIS + 50MP 50mm Telephoto + 13MP Ultrawide)',
      mainCamera: '108 MP, f/1.8, Hybrid OIS + EIS, Capture Fusion tech',
      ultrawideCamera: '13 MP, f/2.4, 123˚',
      telephotoCamera: '50 MP, f/2.0, 2x-4x optical/in-sensor zoom',
      frontCamera: '50 MP, f/2.45, Eye-tracking AF, 4K video, Selfie gestures',
      videoRecording: '4K@30fps, 1080p@60fps, OZO Audio capture',
      ois: true,
    },
    battery: {
      batteryCapacity: 4600,
      wiredCharging: 33,
      wirelessCharging: 15,
      reverseCharging: 5,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.2',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '159.84 x 75.66 x 8.9 mm',
      weight: 209.5,
      materials: 'Gen2 Repairability (user-replaceable screen/battery with iFixit tools), recycled aluminum frame, toughened glass back',
      waterResistance: 'IP54 dust and splash resistant',
      colors: ['Neon Pink', 'Topaz Blue', 'Twisted Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Clean Android with Custom Detox Mode',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with OZO Audio playback',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted capacitive in power button',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.hmd.com/en_in/hmd-skyline',
      productPage: 'https://www.amazon.in/dp/B0D9W1WJ6Q',
      specSheetUrl: 'https://www.hmd.com/en_in/hmd-skyline/specs',
      verifiedDate: '2024-07',
    },
  },
  {
    id: 'hmd-crest-max-5g',
    slug: 'hmd-crest-max-5g',
    brand: 'HMD',
    modelName: 'HMD Crest Max 5G',
    generation: 'Crest',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 14999,
      maximumPrice: 14999,
      launchPrice: 14999,
      currentPrice: 14999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'HMD India / Amazon Store',
    },
    display: {
      displaySize: 6.67,
      displayType: '90Hz FHD+ OLED',
      resolution: '2400 x 1080 pixels',
      refreshRate: 90,
      peakBrightness: 800,
      hdr: 'None',
      protection: 'Toughened glass',
      screenToBodyRatio: '86.5%',
    },
    performance: {
      chipset: 'Unisoc T760 5G (6nm EUV)',
      cpu: 'Octa-core (4x2.2 GHz Cortex-A76 & 4x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC4',
      ramOptions: ['8GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 510000,
    },
    cameras: {
      rearCameraSetup: 'Triple (64MP + 5MP Ultrawide + 2MP Macro)',
      mainCamera: '64 MP Sony, f/1.79, PDAF',
      ultrawideCamera: '5 MP, f/2.2',
      telephotoCamera: 'None',
      frontCamera: '50 MP, f/2.0, Selfie gestures, Flash',
      videoRecording: '1080p@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 33,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5 (ac)',
      bluetooth: 'Bluetooth 5.0',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '163.86 x 76.42 x 8.95 mm',
      weight: 205,
      materials: 'Gen1 Self-repairable design (1-Screw back cover access), Glass Back',
      waterResistance: 'IP52 splash resistant',
      colors: ['Aqua Green', 'Deep Purple'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Clean Stock Android',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Single bottom loudspeaker with OZO Playback',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.hmd.com/en_in/hmd-crest-max-5g',
      productPage: 'https://www.amazon.in/dp/B0D9W55J6Q',
      specSheetUrl: 'https://www.hmd.com/en_in/hmd-crest-max-5g/specs',
      verifiedDate: '2024-07',
    },
  },
  {
    id: 'hmd-crest-5g',
    slug: 'hmd-crest-5g',
    brand: 'HMD',
    modelName: 'HMD Crest 5G',
    generation: 'Crest',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 12999,
      maximumPrice: 12999,
      launchPrice: 12999,
      currentPrice: 12999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'HMD India / Amazon Store',
    },
    display: {
      displaySize: 6.67,
      displayType: '90Hz FHD+ OLED',
      resolution: '2400 x 1080 pixels',
      refreshRate: 90,
      peakBrightness: 800,
      hdr: 'None',
      protection: 'Toughened glass',
      screenToBodyRatio: '86.5%',
    },
    performance: {
      chipset: 'Unisoc T760 5G (6nm EUV)',
      cpu: 'Octa-core (4x2.2 GHz Cortex-A76 & 4x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC4',
      ramOptions: ['6GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 505000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP Depth)',
      mainCamera: '50 MP, f/1.8, PDAF, AI Super Portrait',
      ultrawideCamera: 'None',
      telephotoCamera: 'None',
      frontCamera: '50 MP, f/2.0, Selfie gestures, Flash',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 33,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5 (ac)',
      bluetooth: 'Bluetooth 5.0',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '163.86 x 76.42 x 8.95 mm',
      weight: 205,
      materials: 'Gen1 Self-repairable design (accessible battery and display), Glass Back',
      waterResistance: 'IP52 splash resistant',
      colors: ['Midnight Blue', 'Royal Pink'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Clean Stock Android',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Single bottom loudspeaker with OZO Playback',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.hmd.com/en_in/hmd-crest-5g',
      productPage: 'https://www.amazon.in/dp/B0D9W1WJ6R',
      specSheetUrl: 'https://www.hmd.com/en_in/hmd-crest-5g/specs',
      verifiedDate: '2024-07',
    },
  },
];

const variants: MobileVariant[] = [
  // Skyline
  {
    id: 'hmd-skyline-12-256',
    modelId: 'hmd-skyline',
    name: 'HMD Skyline (12GB RAM, 256GB, Qi2 Wireless)',
    ram: '12GB',
    storage: '256GB',
    color: 'Topaz Blue',
    price: 35999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Crest Max 5G
  {
    id: 'hmd-crest-max-5g-8-256',
    modelId: 'hmd-crest-max-5g',
    name: 'HMD Crest Max 5G (8GB RAM, 256GB, Self-Repairable)',
    ram: '8GB',
    storage: '256GB',
    color: 'Aqua Green',
    price: 14999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Crest 5G
  {
    id: 'hmd-crest-5g-6-128',
    modelId: 'hmd-crest-5g',
    name: 'HMD Crest 5G (6GB RAM, 128GB, Self-Repairable)',
    ram: '6GB',
    storage: '128GB',
    color: 'Midnight Blue',
    price: 12999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    modelId: 'hmd-skyline',
    modelName: 'HMD Skyline',
    brand: 'HMD',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/hmd-skyline.jpg',
        angle: 'front',
        source: 'HMD Official (GSMArena CDN)',
        sourceUrl: 'https://www.hmd.com/en_in/hmd-skyline',
        verified: true,
        alt: 'HMD Skyline front 144Hz pOLED display',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/hmd/hmd-skyline-1.jpg',
        angle: 'back',
        source: 'HMD Official (GSMArena CDN)',
        sourceUrl: 'https://www.hmd.com/en_in/hmd-skyline',
        verified: true,
        alt: 'HMD Skyline Gen2 repairable back view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/hmd/hmd-skyline-2.jpg',
        angle: 'side',
        source: 'HMD Official (GSMArena CDN)',
        sourceUrl: 'https://www.hmd.com/en_in/hmd-skyline',
        verified: true,
        alt: 'HMD Skyline profile',
      },
    ],
  },
  {
    modelId: 'hmd-crest-max-5g',
    modelName: 'HMD Crest Max 5G',
    brand: 'HMD',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/hmd-crest-max.jpg',
        angle: 'front',
        source: 'HMD Official (GSMArena CDN)',
        sourceUrl: 'https://www.hmd.com/en_in/hmd-crest-max-5g',
        verified: true,
        alt: 'HMD Crest Max 5G front display view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/hmd/hmd-crest-max-1.jpg',
        angle: 'back',
        source: 'HMD Official (GSMArena CDN)',
        sourceUrl: 'https://www.hmd.com/en_in/hmd-crest-max-5g',
        verified: true,
        alt: 'HMD Crest Max 5G glass back rear view',
      },
    ],
  },
  {
    modelId: 'hmd-crest-5g',
    modelName: 'HMD Crest 5G',
    brand: 'HMD',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/hmd-crest.jpg',
        angle: 'front',
        source: 'HMD Official (GSMArena CDN)',
        sourceUrl: 'https://www.hmd.com/en_in/hmd-crest-5g',
        verified: true,
        alt: 'HMD Crest 5G front display view',
      },
    ],
  },
];

export const hmdBundle: MobileBrandBundle = {
  brand: 'HMD',
  models,
  variants,
  images,
};
