import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  // ── HONOR ──
  {
    id: 'honor-magic-6-pro',
    slug: 'honor-magic-6-pro',
    brand: 'Honor',
    modelName: 'Honor Magic 6 Pro',
    generation: 'Magic 6',
    status: 'active',
    launchDate: '2024-08',
    pricing: {
      startingPrice: 89999,
      maximumPrice: 89999,
      launchPrice: 89999,
      currentPrice: 89999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'HTech Official / ExploreHonor India',
    },
    display: {
      displaySize: 6.8,
      displayType: 'LTPO Curved OLED with 4320Hz PWM Dimming',
      resolution: '2800 x 1280 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 5000,
      hdr: 'Dolby Vision, HDR Vivid',
      protection: 'Honor NanoCrystal Shield',
      screenToBodyRatio: '91.6%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Gen 3 (4nm)',
      cpu: 'Octa-core (1x3.3 GHz Cortex-X4 & 5x3.2 GHz & 2x2.3 GHz)',
      gpu: 'Adreno 750',
      ramOptions: ['12GB'],
      storageOptions: ['512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 2080000,
      geekbenchSingle: 2210,
      geekbenchMulti: 6850,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 180MP) Falcon Camera System',
      mainCamera: '50 MP OmniVision OV50H, variable f/1.4-f/2.0, 1/1.3", OIS',
      ultrawideCamera: '50 MP, f/2.0, 122˚, 2.5cm macro',
      telephotoCamera: '180 MP periscope, 1/1.49", 2.5x optical, 100x digital, OIS',
      frontCamera: '50 MP + 3D ToF Depth sensor, 4K60',
      videoRecording: '4K@60fps 10-bit Log, HDR Vivid',
      ois: true,
    },
    battery: {
      batteryCapacity: 5600,
      wiredCharging: 80,
      wirelessCharging: 66,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 3.2 Gen 1, DisplayPort 1.2',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.5 x 75.8 x 8.9 mm',
      weight: 229,
      materials: 'Cushion-shaped camera module, eco-leather or glass back, aluminum frame',
      waterResistance: 'IP68 water and dust resistant',
      colors: ['Epi Green', 'Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MagicOS 8.0 (AI-powered Magic Portal)',
      launchOS: 'Android 14',
      promisedMajorUpdates: 4,
      securityUpdatePolicy: '5 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with spatial audio',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: '3D Ultrasonic in-display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.explorehonor.com/in/shop/honor-magic6-pro/',
      productPage: 'https://www.amazon.in/dp/B0D9VR6X64',
      specSheetUrl: 'https://www.explorehonor.com/in/phones/honor-magic6-pro/spec/',
      verifiedDate: '2024-08',
    },
  },
  {
    id: 'honor-200-pro',
    slug: 'honor-200-pro',
    brand: 'Honor',
    modelName: 'Honor 200 Pro',
    generation: '200',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 49999,
      maximumPrice: 49999,
      launchPrice: 57999,
      currentPrice: 49999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'HTech Official / ExploreHonor India',
    },
    display: {
      displaySize: 6.78,
      displayType: 'Quad-Curved 1.5K 120Hz OLED with 3840Hz PWM',
      resolution: '2700 x 1224 pixels',
      refreshRate: 120,
      peakBrightness: 4000,
      hdr: 'HDR Vivid',
      protection: 'Aluminosilicate glass',
      screenToBodyRatio: '90.8%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8s Gen 3 (4nm)',
      cpu: 'Octa-core (1x3.0 GHz Cortex-X4 & 4x2.8 GHz & 3x2.0 GHz)',
      gpu: 'Adreno 735',
      ramOptions: ['12GB'],
      storageOptions: ['512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 1510000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 12MP + 50MP) Studio Harcourt Portrait',
      mainCamera: '50 MP OmniVision H9000, f/1.9, 1/1.3", OIS',
      ultrawideCamera: '12 MP, f/2.2, 112˚, 2.5cm macro',
      telephotoCamera: '50 MP Sony IMX856, 2.5x optical, 50x digital, OIS',
      frontCamera: '50 MP + 2MP 3D depth, 4K30',
      videoRecording: '4K@60fps, EIS + OIS Studio portrait video',
      ois: true,
    },
    battery: {
      batteryCapacity: 5200,
      wiredCharging: 100,
      wirelessCharging: 66,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '163.3 x 75.2 x 8.2 mm',
      weight: 199,
      materials: 'Coastline natural texture design, curved glass back',
      waterResistance: 'IP65 water and dust resistant',
      colors: ['Ocean Cyan', 'Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MagicOS 8.0 (Studio Harcourt Portrait Engine)',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.explorehonor.com/in/shop/honor-200-pro/',
      productPage: 'https://www.amazon.in/dp/B0D7D7R3D7',
      specSheetUrl: 'https://www.explorehonor.com/in/phones/honor-200-pro/spec/',
      verifiedDate: '2024-07',
    },
  },
  {
    id: 'honor-200',
    slug: 'honor-200',
    brand: 'Honor',
    modelName: 'Honor 200',
    generation: '200',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 31999,
      maximumPrice: 34999,
      launchPrice: 34999,
      currentPrice: 31999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'HTech Official / ExploreHonor India',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Quad-Curved 1.5K 120Hz OLED with 3840Hz PWM',
      resolution: '2664 x 1200 pixels',
      refreshRate: 120,
      peakBrightness: 4000,
      hdr: 'HDR Vivid',
      protection: 'Aluminosilicate glass',
      screenToBodyRatio: '90.0%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7 Gen 3 (4nm)',
      cpu: 'Octa-core (1x2.63 GHz Cortex-A715 & 4x2.4 GHz & 3x1.8 GHz)',
      gpu: 'Adreno 720',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 3.1',
      antutuScore: 840000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 12MP + 50MP) Studio Harcourt',
      mainCamera: '50 MP Sony IMX906, f/1.95, 1/1.56", OIS',
      ultrawideCamera: '12 MP, f/2.2, 112˚, macro',
      telephotoCamera: '50 MP Sony IMX856, 2.5x optical, OIS',
      frontCamera: '50 MP, f/2.1, 4K30',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5200,
      wiredCharging: 100,
      wirelessCharging: 0,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.5 x 74.6 x 7.7 mm',
      weight: 187,
      materials: 'Ultra-slim lightweight quad-curved design',
      waterResistance: 'Splash resistant',
      colors: ['Moonlight White', 'Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MagicOS 8.0',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.explorehonor.com/in/shop/honor-200/',
      productPage: 'https://www.amazon.in/dp/B0D7D7R3D8',
      specSheetUrl: 'https://www.explorehonor.com/in/phones/honor-200/spec/',
      verifiedDate: '2024-07',
    },
  },
  {
    id: 'honor-x9b',
    slug: 'honor-x9b',
    brand: 'Honor',
    modelName: 'Honor X9b',
    generation: 'X9b',
    status: 'active',
    launchDate: '2024-02',
    pricing: {
      startingPrice: 19999,
      maximumPrice: 19999,
      launchPrice: 25999,
      currentPrice: 19999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'HTech Official / ExploreHonor India',
    },
    display: {
      displaySize: 6.78,
      displayType: '1.5K 120Hz Curved AMOLED with Ultra-Bounce 360° Anti-Drop Protection',
      resolution: '2652 x 1200 pixels',
      refreshRate: 120,
      peakBrightness: 1200,
      hdr: 'None',
      protection: 'Honor Ultra-Bounce Anti-Drop Glass (SGS 5-star drop certified)',
      screenToBodyRatio: '91.2%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 6 Gen 1 (4nm)',
      cpu: 'Octa-core (4x2.2 GHz Cortex-A78 & 4x1.8 GHz Cortex-A55)',
      gpu: 'Adreno 710',
      ramOptions: ['8GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 520000,
    },
    cameras: {
      rearCameraSetup: 'Triple (108MP + 5MP + 2MP) Matrix Ring',
      mainCamera: '108 MP, f/1.75, 1/1.67", 3x lossless zoom',
      ultrawideCamera: '5 MP, f/2.2, 110˚',
      telephotoCamera: 'None (2 MP Macro)',
      frontCamera: '16 MP, f/2.45',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5800,
      wiredCharging: 35,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.1',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '163.6 x 75.5 x 7.98 mm',
      weight: 185,
      materials: 'Ultra-Bounce anti-drop cushioning, vegan leather back or matte glass',
      waterResistance: 'IP53 dust and splash resistant',
      colors: ['Sunrise Orange', 'Midnight Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MagicOS 7.2 (Upgraded to 8.0)',
      launchOS: 'Android 13',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Single loudspeaker',
      stereo: false,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.explorehonor.com/in/shop/honor-x9b/',
      productPage: 'https://www.amazon.in/dp/B0CT43R5H8',
      specSheetUrl: 'https://www.explorehonor.com/in/phones/honor-x9b/spec/',
      verifiedDate: '2024-02',
    },
  },

  // ── ITEL ──
  {
    id: 'itel-color-pro-5g',
    slug: 'itel-color-pro-5g',
    brand: 'Itel',
    modelName: 'Itel Color Pro 5G',
    generation: 'Color Pro',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 9999,
      maximumPrice: 9999,
      launchPrice: 9999,
      currentPrice: 9999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Itel Mobile India / Amazon India',
    },
    display: {
      displaySize: 6.6,
      displayType: 'HD+ IPS LCD with 90Hz Refresh Rate',
      resolution: '1612 x 720 pixels',
      refreshRate: 90,
      peakBrightness: 500,
      hdr: 'None',
      protection: 'Panda Glass',
      screenToBodyRatio: '84.6%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6080 5G (6nm)',
      cpu: 'Octa-core (2x2.4 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['6GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 420000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP AI Dual Rear)',
      mainCamera: '50 MP, f/1.8, PDAF',
      ultrawideCamera: 'None',
      telephotoCamera: 'None (AI auxiliary lens)',
      frontCamera: '8 MP with front flash',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 18,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.1',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM with dedicated microSD',
    },
    physical: {
      dimensions: '164.0 x 75.8 x 8.4 mm',
      weight: 190,
      materials: 'IVCO colour-changing back cover technology (changes color under sunlight)',
      waterResistance: 'Splash resistant',
      colors: ['River Blue', 'Lavender Fantasy'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'itel OS 13',
      launchOS: 'Android 13 (Go edition)',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Single bottom firing speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.itel-india.com/product/color-pro-5g/',
      productPage: 'https://www.amazon.in/dp/B0D938VRM8',
      specSheetUrl: 'https://www.itel-india.com/product/color-pro-5g/',
      verifiedDate: '2024-07',
    },
  },
  {
    id: 'itel-p55-5g',
    slug: 'itel-p55-5g',
    brand: 'Itel',
    modelName: 'Itel P55 5G',
    generation: 'P55',
    status: 'active',
    launchDate: '2023-10',
    pricing: {
      startingPrice: 8999,
      maximumPrice: 9999,
      launchPrice: 9699,
      currentPrice: 8999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Itel Mobile India / Amazon India',
    },
    display: {
      displaySize: 6.6,
      displayType: 'HD+ 90Hz IPS Display',
      resolution: '1600 x 720 pixels',
      refreshRate: 90,
      peakBrightness: 480,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '84.0%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6080 5G (6nm)',
      cpu: 'Octa-core (2x2.4 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['4GB', '6GB'],
      storageOptions: ['64GB', '128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 415000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP AI Dual Camera)',
      mainCamera: '50 MP, f/1.8, AF',
      ultrawideCamera: 'None',
      telephotoCamera: 'None (AI auxiliary)',
      frontCamera: '8 MP',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 18,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.1',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM with dedicated microSD',
    },
    physical: {
      dimensions: '164.0 x 75.1 x 8.4 mm',
      weight: 198,
      materials: 'Glossy textured plastic unibody',
      waterResistance: 'Splash resistant',
      colors: ['Galaxy Blue', 'Mint Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'itel OS 13',
      launchOS: 'Android 13',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.itel-india.com/product/p55-5g/',
      productPage: 'https://www.amazon.in/dp/B0CGJ6J21W',
      specSheetUrl: 'https://www.itel-india.com/product/p55-5g/',
      verifiedDate: '2023-10',
    },
  },
  {
    id: 'itel-s24',
    slug: 'itel-s24',
    brand: 'Itel',
    modelName: 'Itel S24',
    generation: 'S24',
    status: 'active',
    launchDate: '2024-04',
    pricing: {
      startingPrice: 8499,
      maximumPrice: 8499,
      launchPrice: 9999,
      currentPrice: 8499,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Itel Mobile India / Amazon India',
    },
    display: {
      displaySize: 6.6,
      displayType: 'HD+ 90Hz Punch-Hole IPS Display with Dynamic Bar',
      resolution: '1612 x 720 pixels',
      refreshRate: 90,
      peakBrightness: 480,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '85.0%',
    },
    performance: {
      chipset: 'MediaTek Helio G91 (12nm)',
      cpu: 'Octa-core (2x2.0 GHz Cortex-A75 & 6x1.8 GHz Cortex-A55)',
      gpu: 'Mali-G52 MC2',
      ramOptions: ['8GB'],
      storageOptions: ['128GB'],
      storageType: 'eMMC 5.1',
      antutuScore: 270000,
    },
    cameras: {
      rearCameraSetup: 'Dual (108MP AI Ultra-Clear)',
      mainCamera: '108 MP Samsung HM6, f/1.6, 3x in-sensor zoom',
      ultrawideCamera: 'None',
      telephotoCamera: 'None (AI auxiliary lens)',
      frontCamera: '8 MP, front LED flash',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 18,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: false,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.0',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM with dedicated microSD',
    },
    physical: {
      dimensions: '163.5 x 75.5 x 8.3 mm',
      weight: 192,
      materials: 'Color-changing UV texture back panel',
      waterResistance: 'Splash resistant',
      colors: ['Starry Black', 'Coastline Blue'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'itel OS 13.5 (Dynamic Bar notification island)',
      launchOS: 'Android 13',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Dual stereo speakers tuned by DTS',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.itel-india.com/product/s24/',
      productPage: 'https://www.amazon.in/dp/B0D1N9N19T',
      specSheetUrl: 'https://www.itel-india.com/product/s24/',
      verifiedDate: '2024-04',
    },
  },
  {
    id: 'itel-a70',
    slug: 'itel-a70',
    brand: 'Itel',
    modelName: 'Itel A70',
    generation: 'A70',
    status: 'active',
    launchDate: '2024-01',
    pricing: {
      startingPrice: 5999,
      maximumPrice: 6799,
      launchPrice: 6299,
      currentPrice: 5999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Itel Mobile India / Amazon India',
    },
    display: {
      displaySize: 6.6,
      displayType: 'HD+ IPS Display with Dynamic Bar',
      resolution: '1612 x 720 pixels',
      refreshRate: 60,
      peakBrightness: 500,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '84.0%',
    },
    performance: {
      chipset: 'Unisoc T603 (12nm)',
      cpu: 'Octa-core (4x1.8 GHz Cortex-A55 & 4x1.2 GHz Cortex-A55)',
      gpu: 'PowerVR GE8322',
      ramOptions: ['3GB', '4GB'],
      storageOptions: ['64GB', '128GB'],
      storageType: 'eMMC 5.1',
      antutuScore: 165000,
    },
    cameras: {
      rearCameraSetup: 'Dual (13MP HDR Dual Rear)',
      mainCamera: '13 MP, f/1.8, AF',
      ultrawideCamera: 'None',
      telephotoCamera: 'None (AI auxiliary)',
      frontCamera: '8 MP',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 10,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: false,
      has4G: true,
      wifi: 'Wi-Fi 4',
      bluetooth: 'Bluetooth 4.2',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM with dedicated microSD',
    },
    physical: {
      dimensions: '164.0 x 75.6 x 8.6 mm',
      weight: 187,
      materials: 'Matte composite curved back',
      waterResistance: 'Splash resistant',
      colors: ['Brilliant Gold', 'Stylish Black', 'Field Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'itel OS 13 (Go edition)',
      launchOS: 'Android 13 Go',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.itel-india.com/product/a70/',
      productPage: 'https://www.amazon.in/dp/B0CQ4K912M',
      specSheetUrl: 'https://www.itel-india.com/product/a70/',
      verifiedDate: '2024-01',
    },
  },
];

const variants: MobileVariant[] = [
  // Honor Magic 6 Pro
  {
    id: 'honor-magic-6-pro-12gb-512gb',
    modelId: 'honor-magic-6-pro',
    modelName: 'Honor Magic 6 Pro',
    brand: 'Honor',
    variantName: '12GB + 512GB',
    ram: '12GB',
    storage: '512GB',
    price: 89999,
    mrp: 109999,
    colors: ['Epi Green', 'Black'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },
  // Honor 200 Pro
  {
    id: 'honor-200-pro-12gb-512gb',
    modelId: 'honor-200-pro',
    modelName: 'Honor 200 Pro',
    brand: 'Honor',
    variantName: '12GB + 512GB',
    ram: '12GB',
    storage: '512GB',
    price: 49999,
    mrp: 64999,
    colors: ['Ocean Cyan', 'Black'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },
  // Honor 200
  {
    id: 'honor-200-8gb-256gb',
    modelId: 'honor-200',
    modelName: 'Honor 200',
    brand: 'Honor',
    variantName: '8GB + 256GB',
    ram: '8GB',
    storage: '256GB',
    price: 31999,
    mrp: 39999,
    colors: ['Moonlight White', 'Black'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },
  {
    id: 'honor-200-12gb-512gb',
    modelId: 'honor-200',
    modelName: 'Honor 200',
    brand: 'Honor',
    variantName: '12GB + 512GB',
    ram: '12GB',
    storage: '512GB',
    price: 34999,
    mrp: 44999,
    colors: ['Moonlight White', 'Black'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },
  // Honor X9b
  {
    id: 'honor-x9b-8gb-256gb',
    modelId: 'honor-x9b',
    modelName: 'Honor X9b',
    brand: 'Honor',
    variantName: '8GB + 256GB',
    ram: '8GB',
    storage: '256GB',
    price: 19999,
    mrp: 28999,
    colors: ['Sunrise Orange', 'Midnight Black'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },

  // Itel Color Pro 5G
  {
    id: 'itel-color-pro-5g-6gb-128gb',
    modelId: 'itel-color-pro-5g',
    modelName: 'Itel Color Pro 5G',
    brand: 'Itel',
    variantName: '6GB + 128GB',
    ram: '6GB',
    storage: '128GB',
    price: 9999,
    mrp: 12999,
    colors: ['River Blue', 'Lavender Fantasy'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },
  // Itel P55 5G
  {
    id: 'itel-p55-5g-4gb-64gb',
    modelId: 'itel-p55-5g',
    modelName: 'Itel P55 5G',
    brand: 'Itel',
    variantName: '4GB + 64GB',
    ram: '4GB',
    storage: '64GB',
    price: 8999,
    mrp: 10999,
    colors: ['Galaxy Blue', 'Mint Green'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },
  {
    id: 'itel-p55-5g-6gb-128gb',
    modelId: 'itel-p55-5g',
    modelName: 'Itel P55 5G',
    brand: 'Itel',
    variantName: '6GB + 128GB',
    ram: '6GB',
    storage: '128GB',
    price: 9999,
    mrp: 11999,
    colors: ['Galaxy Blue', 'Mint Green'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },
  // Itel S24
  {
    id: 'itel-s24-8gb-128gb',
    modelId: 'itel-s24',
    modelName: 'Itel S24',
    brand: 'Itel',
    variantName: '8GB + 128GB',
    ram: '8GB',
    storage: '128GB',
    price: 8499,
    mrp: 11999,
    colors: ['Starry Black', 'Coastline Blue'],
    connectivity: '4G',
    inStock: true,
    verified: true,
  },
  // Itel A70
  {
    id: 'itel-a70-3gb-64gb',
    modelId: 'itel-a70',
    modelName: 'Itel A70',
    brand: 'Itel',
    variantName: '3GB + 64GB',
    ram: '3GB',
    storage: '64GB',
    price: 5999,
    mrp: 7999,
    colors: ['Brilliant Gold', 'Stylish Black'],
    connectivity: '4G',
    inStock: true,
    verified: true,
  },
  {
    id: 'itel-a70-4gb-128gb',
    modelId: 'itel-a70',
    modelName: 'Itel A70',
    brand: 'Itel',
    variantName: '4GB + 128GB',
    ram: '4GB',
    storage: '128GB',
    price: 6799,
    mrp: 8999,
    colors: ['Brilliant Gold', 'Field Green'],
    connectivity: '4G',
    inStock: true,
    verified: true,
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    "modelId": "honor-magic-6-pro",
    "modelName": "Honor Magic 6 Pro",
    "brand": "Honor",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/honor/honor-magic6-pro-1.jpg",
        "angle": "front",
        "source": "Honor Official (GSMArena CDN)",
        "verified": true,
        "alt": "Honor Magic 6 Pro front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/honor/honor-magic6-pro-2.jpg",
        "angle": "back",
        "source": "Honor Official (GSMArena CDN)",
        "verified": true,
        "alt": "Honor Magic 6 Pro star wheel camera rear view"
      }
    ]
  },
  {
    "modelId": "honor-200-pro",
    "modelName": "Honor 200 Pro",
    "brand": "Honor",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/honor/honor-200-pro-1.jpg",
        "angle": "front",
        "source": "Honor Official (GSMArena CDN)",
        "verified": true,
        "alt": "Honor 200 Pro front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/honor/honor-200-pro-2.jpg",
        "angle": "back",
        "source": "Honor Official (GSMArena CDN)",
        "verified": true,
        "alt": "Honor 200 Pro Studio Harcourt portrait camera rear view"
      }
    ]
  },
  {
    "modelId": "honor-200",
    "modelName": "Honor 200",
    "brand": "Honor",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/honor/honor-200-1.jpg",
        "angle": "front",
        "source": "Honor Official (GSMArena CDN)",
        "verified": true,
        "alt": "Honor 200 front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/honor/honor-200-2.jpg",
        "angle": "back",
        "source": "Honor Official (GSMArena CDN)",
        "verified": true,
        "alt": "Honor 200 rear view"
      }
    ]
  },
  {
    "modelId": "honor-x9b",
    "modelName": "Honor X9b",
    "brand": "Itel",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/honor/honor-x9b-1.jpg",
        "angle": "front",
        "source": "Honor Official (GSMArena CDN)",
        "verified": true,
        "alt": "Honor X9b front anti-drop curved display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/honor/honor-x9b-2.jpg",
        "angle": "back",
        "source": "Honor Official (GSMArena CDN)",
        "verified": true,
        "alt": "Honor X9b Sunrise Orange vegan leather rear view"
      }
    ]
  },
  {
    "modelId": "itel-color-pro-5g",
    "modelName": "Itel Color Pro 5G",
    "brand": "Itel",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/itel/itel-color-pro-5g-1.jpg",
        "angle": "front",
        "source": "Itel Official (GSMArena CDN)",
        "verified": true,
        "alt": "Itel Color Pro 5G front view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/itel/itel-color-pro-5g-2.jpg",
        "angle": "back",
        "source": "Itel Official (GSMArena CDN)",
        "verified": true,
        "alt": "Itel Color Pro 5G color-changing IVCO technology rear view"
      }
    ]
  },
  {
    "modelId": "itel-p55-5g",
    "modelName": "Itel P55 5G",
    "brand": "Itel",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/itel-p55.jpg",
        "angle": "front",
        "source": "Itel Official (GSMArena CDN)",
        "verified": true,
        "alt": "Itel P55 5G front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/itel/itel-p55-1.jpg",
        "angle": "back",
        "source": "Itel Official (GSMArena CDN)",
        "verified": true,
        "alt": "Itel P55 5G rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/itel/itel-p55-2.jpg",
        "angle": "side",
        "source": "Itel Official (GSMArena CDN)",
        "verified": true,
        "alt": "Itel P55 5G profile"
      }
    ]
  },
  {
    "modelId": "itel-s24",
    "modelName": "Itel S24",
    "brand": "Itel",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/itel/itel-s24-1.jpg",
        "angle": "front",
        "source": "Itel Official (GSMArena CDN)",
        "verified": true,
        "alt": "Itel S24 front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/itel/itel-s24-2.jpg",
        "angle": "back",
        "source": "Itel Official (GSMArena CDN)",
        "verified": true,
        "alt": "Itel S24 108MP circular camera rear view"
      }
    ]
  },
  {
    "modelId": "itel-a70",
    "modelName": "Itel A70",
    "brand": "Honor",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/itel/itel-a70-1.jpg",
        "angle": "front",
        "source": "Itel Official (GSMArena CDN)",
        "verified": true,
        "alt": "Itel A70 front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/itel/itel-a70-2.jpg",
        "angle": "back",
        "source": "Itel Official (GSMArena CDN)",
        "verified": true,
        "alt": "Itel A70 rear view"
      }
    ]
  }
];

export const honorItelBundle: MobileBrandBundle = {
  models,
  variants,
  images,
};
