import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  // ── HONOR MAGIC SERIES ──
  {
    id: 'honor-magic-6-pro',
    slug: 'honor-magic-6-pro',
    brand: 'Honor',
    modelName: 'Honor Magic 6 Pro',
    generation: 'Magic 6',
    status: 'active',
    launchDate: '2024-08',
    pricing: {
      startingPrice: 89999,
      maximumPrice: 89999,
      launchPrice: 89999,
      currentPrice: 89999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'HTech Official / ExploreHonor India',
    },
    display: {
      displaySize: 6.8,
      displayType: 'LTPO Curved OLED with 4320Hz PWM Dimming',
      resolution: '2800 x 1280 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 5000,
      hdr: 'Dolby Vision, HDR Vivid',
      protection: 'Honor NanoCrystal Shield',
      screenToBodyRatio: '91.6%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Gen 3 (4nm)',
      cpu: 'Octa-core (1x3.3 GHz Cortex-X4 & 5x3.2 GHz & 2x2.3 GHz)',
      gpu: 'Adreno 750',
      ramOptions: ['12GB'],
      storageOptions: ['512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 2080000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 180MP) Falcon Camera System',
      mainCamera: '50 MP OmniVision OV50H, variable f/1.4-f/2.0, 1/1.3", OIS',
      ultrawideCamera: '50 MP, f/2.0, 122˚, 2.5cm macro',
      telephotoCamera: '180 MP periscope, 1/1.49", 2.5x optical, 100x digital, OIS',
      frontCamera: '50 MP + 3D ToF Depth sensor, 4K60',
      videoRecording: '4K@60fps 10-bit Log, HDR Vivid',
      ois: true,
    },
    battery: {
      batteryCapacity: 5600,
      wiredCharging: 80,
      wirelessCharging: 66,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 3.2 Gen 1, DisplayPort 1.2',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.5 x 75.8 x 8.9 mm',
      weight: 229,
      materials: 'NanoCrystal Shield front, vegan leather or glass back, aluminum frame',
      waterResistance: 'IP68 water and dust resistant',
      colors: ['Epi Green', 'Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MagicOS 8.0 with Magic Portal AI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 4,
      securityUpdatePolicy: '5 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with spatial audio',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: '3D Face Recognition + Optical in-display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.explorehonor.com/in/shop/honor-magic-6-pro/',
      productPage: 'https://www.amazon.in/dp/B0DB567Z9V',
      specSheetUrl: 'https://www.explorehonor.com/in/phones/honor-magic-6-pro/spec/',
      verifiedDate: '2024-08',
    },
  },

  // ── HONOR NUMBER SERIES ──
  {
    id: 'honor-200-pro',
    slug: 'honor-200-pro',
    brand: 'Honor',
    modelName: 'Honor 200 Pro',
    generation: 'Honor 200',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 49999,
      maximumPrice: 57999,
      launchPrice: 57999,
      currentPrice: 49999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'HTech Official / Amazon India',
    },
    display: {
      displaySize: 6.78,
      displayType: 'Quad-curved 120Hz OLED, 3840Hz PWM Dimming',
      resolution: '2700 x 1224 pixels (1.5K)',
      refreshRate: 120,
      peakBrightness: 4000,
      hdr: 'HDR10+',
      protection: 'Aluminosilicate glass',
      screenToBodyRatio: '90.8%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8s Gen 3 (4nm)',
      cpu: 'Octa-core (1x3.0 GHz Cortex-X4 & 4x2.8 GHz & 3x2.0 GHz)',
      gpu: 'Adreno 735',
      ramOptions: ['12GB'],
      storageOptions: ['512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 1540000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 12MP) Studio Harcourt Portrait',
      mainCamera: '50 MP OmniVision OV50H (Super Dynamic H9000), f/1.9, 1/1.3", OIS',
      ultrawideCamera: '12 MP, f/2.2, 112˚, AF macro',
      telephotoCamera: '50 MP Sony IMX856, f/2.4, 2.5x optical zoom, 50x digital, OIS',
      frontCamera: '50 MP + 2MP 3D depth sensor, f/2.1, 4K30',
      videoRecording: '4K@60fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5200,
      wiredCharging: 100,
      wirelessCharging: 66,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '163.3 x 75.2 x 8.2 mm',
      weight: 199,
      materials: 'Quad-curved glass back with Casa Mila coastline texture, plastic frame',
      waterResistance: 'IP55 dust and water splash resistance',
      colors: ['Ocean Cyan', 'Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MagicOS 8.0 with AI Harcourt Portrait Engine',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'In-display optical',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.explorehonor.com/in/shop/honor-200-pro/',
      productPage: 'https://www.amazon.in/dp/B0D9W1WJ6Q',
      specSheetUrl: 'https://www.explorehonor.com/in/phones/honor-200-pro/spec/',
      verifiedDate: '2024-07',
    },
  },
  {
    id: 'honor-200',
    slug: 'honor-200',
    brand: 'Honor',
    modelName: 'Honor 200',
    generation: 'Honor 200',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 31999,
      maximumPrice: 34999,
      launchPrice: 34999,
      currentPrice: 31999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'HTech Official / Amazon India',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Quad-curved 120Hz OLED, 3840Hz PWM Dimming',
      resolution: '2664 x 1200 pixels (1.5K)',
      refreshRate: 120,
      peakBrightness: 4000,
      hdr: 'HDR10+',
      protection: 'Aluminosilicate glass',
      screenToBodyRatio: '90.5%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7 Gen 3 (4nm)',
      cpu: 'Octa-core (1x2.63 GHz Cortex-A715 & 4x2.4 GHz & 3x1.8 GHz)',
      gpu: 'Adreno 720',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 3.1',
      antutuScore: 840000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 12MP) Studio Harcourt Portrait',
      mainCamera: '50 MP Sony IMX906, f/1.95, 1/1.56", OIS',
      ultrawideCamera: '12 MP, f/2.2, 112˚, AF macro',
      telephotoCamera: '50 MP Sony IMX856, f/2.4, 2.5x optical zoom, 50x digital, OIS',
      frontCamera: '50 MP, f/2.1, 4K30',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5200,
      wiredCharging: 100,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.5 x 74.6 x 7.7 mm',
      weight: 187,
      materials: 'Glass back with coastline ripple pattern, slim profile',
      waterResistance: 'None',
      colors: ['Moonlight White', 'Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MagicOS 8.0 with Studio Harcourt Portrait',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'In-display optical',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.explorehonor.com/in/shop/honor-200/',
      productPage: 'https://www.amazon.in/dp/B0D9W1WJ6R',
      specSheetUrl: 'https://www.explorehonor.com/in/phones/honor-200/spec/',
      verifiedDate: '2024-07',
    },
  },

  // ── HONOR X SERIES ──
  {
    id: 'honor-x9b',
    slug: 'honor-x9b',
    brand: 'Honor',
    modelName: 'Honor X9b',
    generation: 'Honor X',
    status: 'active',
    launchDate: '2024-02',
    pricing: {
      startingPrice: 19999,
      maximumPrice: 21999,
      launchPrice: 25999,
      currentPrice: 19999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'HTech Official / Amazon India',
    },
    display: {
      displaySize: 6.78,
      displayType: '120Hz Curved AMOLED with Ultra-Bounce Anti-Drop 360° Display',
      resolution: '2652 x 1200 pixels (1.5K)',
      refreshRate: 120,
      peakBrightness: 1200,
      hdr: 'None',
      protection: 'Honor Ultra-Bounce Anti-Drop Glass (5-star SGS drop resistance)',
      screenToBodyRatio: '91.2%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 6 Gen 1 (4nm)',
      cpu: 'Octa-core (4x2.2 GHz Cortex-A78 & 4x1.8 GHz Cortex-A55)',
      gpu: 'Adreno 710',
      ramOptions: ['8GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 520000,
    },
    cameras: {
      rearCameraSetup: 'Triple (108MP + 5MP Ultrawide + 2MP Macro) Matrix Ring',
      mainCamera: '108 MP, f/1.75, 1/1.67", 3x lossless zoom, PDAF',
      ultrawideCamera: '5 MP, f/2.2, 110˚',
      telephotoCamera: 'None',
      frontCamera: '16 MP, f/2.45',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5800,
      wiredCharging: 35,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.1',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '163.6 x 75.5 x 7.98 mm',
      weight: 185,
      materials: 'Ultra-Bounce cushioning structure, vegan leather or glossy back',
      waterResistance: 'IP53 splash resistant',
      colors: ['Sunrise Orange', 'Midnight Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MagicOS 7.2',
      launchOS: 'Android 13 (Upgraded to 14)',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Single loudspeaker',
      stereo: false,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.explorehonor.com/in/shop/honor-x9b/',
      productPage: 'https://www.amazon.in/dp/B0CT43R5H8',
      specSheetUrl: 'https://www.explorehonor.com/in/phones/honor-x9b/spec/',
      verifiedDate: '2024-02',
    },
  },
];

const variants: MobileVariant[] = [
  // Honor Magic 6 Pro
  {
    id: 'honor-magic-6-pro-12gb-512gb',
    modelId: 'honor-magic-6-pro',
    name: 'Honor Magic 6 Pro (12GB RAM, 512GB)',
    ram: '12GB',
    storage: '512GB',
    color: 'Epi Green',
    price: 89999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Honor 200 Pro
  {
    id: 'honor-200-pro-12gb-512gb',
    modelId: 'honor-200-pro',
    name: 'Honor 200 Pro (12GB RAM, 512GB)',
    ram: '12GB',
    storage: '512GB',
    color: 'Ocean Cyan',
    price: 49999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Honor 200
  {
    id: 'honor-200-8gb-256gb',
    modelId: 'honor-200',
    name: 'Honor 200 (8GB RAM, 256GB)',
    ram: '8GB',
    storage: '256GB',
    color: 'Moonlight White',
    price: 31999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  {
    id: 'honor-200-12gb-512gb',
    modelId: 'honor-200',
    name: 'Honor 200 (12GB RAM, 512GB)',
    ram: '12GB',
    storage: '512GB',
    color: 'Black',
    price: 34999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Honor X9b
  {
    id: 'honor-x9b-8gb-256gb',
    modelId: 'honor-x9b',
    name: 'Honor X9b (8GB RAM, 256GB)',
    ram: '8GB',
    storage: '256GB',
    color: 'Sunrise Orange',
    price: 19999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    modelId: 'honor-magic-6-pro',
    modelName: 'Honor Magic 6 Pro',
    brand: 'Honor',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/honor/honor-magic6-pro-1.jpg',
        angle: 'front',
        source: 'Honor Official (GSMArena CDN)',
        sourceUrl: 'https://www.explorehonor.com/in/shop/honor-magic-6-pro/',
        verified: true,
        alt: 'Honor Magic 6 Pro front display view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/honor/honor-magic6-pro-2.jpg',
        angle: 'back',
        source: 'Honor Official (GSMArena CDN)',
        sourceUrl: 'https://www.explorehonor.com/in/shop/honor-magic-6-pro/',
        verified: true,
        alt: 'Honor Magic 6 Pro star wheel camera rear view',
      },
    ],
  },
  {
    modelId: 'honor-200-pro',
    modelName: 'Honor 200 Pro',
    brand: 'Honor',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/honor/honor-200-pro-1.jpg',
        angle: 'front',
        source: 'Honor Official (GSMArena CDN)',
        sourceUrl: 'https://www.explorehonor.com/in/shop/honor-200-pro/',
        verified: true,
        alt: 'Honor 200 Pro front display view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/honor/honor-200-pro-2.jpg',
        angle: 'back',
        source: 'Honor Official (GSMArena CDN)',
        sourceUrl: 'https://www.explorehonor.com/in/shop/honor-200-pro/',
        verified: true,
        alt: 'Honor 200 Pro Studio Harcourt portrait camera rear view',
      },
    ],
  },
  {
    modelId: 'honor-200',
    modelName: 'Honor 200',
    brand: 'Honor',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/honor/honor-200-1.jpg',
        angle: 'front',
        source: 'Honor Official (GSMArena CDN)',
        sourceUrl: 'https://www.explorehonor.com/in/shop/honor-200/',
        verified: true,
        alt: 'Honor 200 front display view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/honor/honor-200-2.jpg',
        angle: 'back',
        source: 'Honor Official (GSMArena CDN)',
        sourceUrl: 'https://www.explorehonor.com/in/shop/honor-200/',
        verified: true,
        alt: 'Honor 200 rear view',
      },
    ],
  },
  {
    modelId: 'honor-x9b',
    modelName: 'Honor X9b',
    brand: 'Honor',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/honor/honor-x9b-1.jpg',
        angle: 'front',
        source: 'Honor Official (GSMArena CDN)',
        sourceUrl: 'https://www.explorehonor.com/in/shop/honor-x9b/',
        verified: true,
        alt: 'Honor X9b front anti-drop curved display view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/honor/honor-x9b-2.jpg',
        angle: 'back',
        source: 'Honor Official (GSMArena CDN)',
        sourceUrl: 'https://www.explorehonor.com/in/shop/honor-x9b/',
        verified: true,
        alt: 'Honor X9b Sunrise Orange vegan leather rear view',
      },
    ],
  },
];

export const honorBundle: MobileBrandBundle = {
  brand: 'Honor',
  models,
  variants,
  images,
};
