import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  // ── GT SERIES (Gaming Flagships) ──
  {
    id: 'infinix-gt-20-pro',
    slug: 'infinix-gt-20-pro',
    brand: 'Infinix',
    modelName: 'Infinix GT 20 Pro',
    generation: 'GT 20',
    status: 'active',
    launchDate: '2024-05',
    pricing: {
      startingPrice: 22999,
      maximumPrice: 24999,
      launchPrice: 24999,
      currentPrice: 22999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Infinix India / Flipkart',
    },
    display: {
      displaySize: 6.78,
      displayType: '144Hz FHD+ Bezel-less LTPS AMOLED',
      resolution: '2436 x 1080 pixels',
      refreshRate: 144,
      peakBrightness: 1300,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '94.3%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 8200 Ultimate (4nm) with Pixelworks X5 Turbo Gaming Display Chip',
      cpu: 'Octa-core (1x3.1 GHz Cortex-A78 & 3x3.0 GHz & 4x2.0 GHz)',
      gpu: 'Mali-G610 MC6',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 950000,
    },
    cameras: {
      rearCameraSetup: 'Triple (108MP + 2MP + 2MP) with Mecha Loop LED',
      mainCamera: '108 MP Samsung HM6, f/1.75, OIS',
      ultrawideCamera: 'None',
      telephotoCamera: 'None (2 MP Macro + 2 MP Depth)',
      frontCamera: '32 MP, f/2.2',
      videoRecording: '4K@60fps, 1080p@120fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 45,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '164.26 x 75.43 x 8.15 mm',
      weight: 194,
      materials: 'Cyber Mecha design with Mecha Loop RGB mini-LED interface',
      waterResistance: 'IP54 splash resistant',
      colors: ['Mecha Blue', 'Mecha Orange', 'Mecha Silver'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'XOS 14 (Clean OS without bloatware)',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers tuned by JBL',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'In-display optical',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.infinixmobiles.in/gt-20-pro/',
      productPage: 'https://www.flipkart.com/infinix-gt-20-pro-store',
      specSheetUrl: 'https://www.infinixmobiles.in/gt-20-pro/',
      verifiedDate: '2024-05',
    },
  },
  {
    id: 'infinix-gt-10-pro',
    slug: 'infinix-gt-10-pro',
    brand: 'Infinix',
    modelName: 'Infinix GT 10 Pro',
    generation: 'GT 10',
    status: 'discontinued',
    launchDate: '2023-08',
    pricing: {
      startingPrice: 19999,
      maximumPrice: 21999,
      launchPrice: 21999,
      currentPrice: 19999,
      currency: 'INR',
      priceEffectiveDate: '2024-04',
      source: 'Infinix India Store Archive',
    },
    display: {
      displaySize: 6.67,
      displayType: '120Hz 10-bit FHD+ AMOLED, 900 nits',
      resolution: '2400 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 900,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '87.0%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 8050 (6nm)',
      cpu: 'Octa-core (1x3.0 GHz Cortex-A78 & 3x2.6 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G77 MC9',
      ramOptions: ['8GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 780000,
    },
    cameras: {
      rearCameraSetup: 'Triple (108MP + 2MP Macro + 2MP Depth)',
      mainCamera: '108 MP, f/1.75, 1/1.67", AF',
      ultrawideCamera: 'None',
      telephotoCamera: 'None',
      frontCamera: '32 MP, f/2.5',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 45,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.7 x 75.9 x 8.1 mm',
      weight: 187,
      materials: 'Cyber Mecha transparent-style back with mini-LED strip, plastic frame',
      waterResistance: 'IP53 splash resistant',
      colors: ['Cyber Black', 'Mirage Silver'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'XOS 13 for GT',
      launchOS: 'Android 13',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Hi-Res Audio certification',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'In-display optical',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.infinixmobiles.in/gt-10-pro/',
      productPage: 'https://www.flipkart.com/infinix-gt-10-pro-store',
      specSheetUrl: 'https://www.infinixmobiles.in/gt-10-pro/',
      verifiedDate: '2023-08',
    },
  },

  // ── ZERO SERIES (Flagship Imaging) ──
  {
    id: 'infinix-zero-40-5g',
    slug: 'infinix-zero-40-5g',
    brand: 'Infinix',
    modelName: 'Infinix Zero 40 5G',
    generation: 'Zero 40',
    status: 'active',
    launchDate: '2024-09',
    pricing: {
      startingPrice: 27999,
      maximumPrice: 30999,
      launchPrice: 27999,
      currentPrice: 27999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Infinix India / Flipkart',
    },
    display: {
      displaySize: 6.78,
      displayType: '144Hz 3D Curved 10-bit AMOLED, 1300 nits peak',
      resolution: '2436 x 1080 pixels',
      refreshRate: 144,
      peakBrightness: 1300,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '93.4%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 8200 Ultimate (4nm)',
      cpu: 'Octa-core (1x3.1 GHz Cortex-A78 & 3x3.0 GHz & 4x2.0 GHz)',
      gpu: 'Mali-G610 MC6',
      ramOptions: ['12GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 3.1',
      antutuScore: 960000,
    },
    cameras: {
      rearCameraSetup: 'Triple (108MP OIS + 50MP Ultrawide + 2MP Depth) with GoPro mode',
      mainCamera: '108 MP Samsung ISOCELL HM6, f/1.75, 1/1.67", OIS + EIS',
      ultrawideCamera: '50 MP, f/2.0, 120˚, PDAF',
      telephotoCamera: 'None',
      frontCamera: '50 MP Samsung ISOCELL JN1, f/2.45, PDAF, 4K@60fps',
      videoRecording: '4K@60fps front and back, ProStable EIS',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 45,
      wirelessCharging: 20,
      reverseCharging: 10,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '164.31 x 74.47 x 7.9 mm',
      weight: 198,
      materials: 'Curved glass back / eco leather finish, plastic frame',
      waterResistance: 'IP54 splash resistant',
      colors: ['Violet Garden', 'Blossom Glow', 'Rock Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'XOS 14.5',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers tuned by JBL',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'In-display optical',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.infinixmobiles.in/zero-40-5g/',
      productPage: 'https://www.flipkart.com/infinix-zero-40-5g-store',
      specSheetUrl: 'https://www.infinixmobiles.in/zero-40-5g/',
      verifiedDate: '2024-09',
    },
  },
  {
    id: 'infinix-zero-30-5g',
    slug: 'infinix-zero-30-5g',
    brand: 'Infinix',
    modelName: 'Infinix Zero 30 5G',
    generation: 'Zero 30',
    status: 'discontinued',
    launchDate: '2023-09',
    pricing: {
      startingPrice: 21999,
      maximumPrice: 23999,
      launchPrice: 23999,
      currentPrice: 21999,
      currency: 'INR',
      priceEffectiveDate: '2024-05',
      source: 'Infinix India Store Archive',
    },
    display: {
      displaySize: 6.78,
      displayType: '144Hz 3D Curved 10-bit AMOLED, 950 nits',
      resolution: '2400 x 1080 pixels',
      refreshRate: 144,
      peakBrightness: 950,
      hdr: 'HDR10',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '90.0%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 8020 (6nm)',
      cpu: 'Octa-core (4x2.6 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G77 MC9',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 760000,
    },
    cameras: {
      rearCameraSetup: 'Triple (108MP OIS + 13MP Ultrawide + 2MP Depth)',
      mainCamera: '108 MP Samsung ISOCELL HM6, f/1.65, 1/1.67", OIS, PDAF',
      ultrawideCamera: '13 MP, f/2.2, 120˚',
      telephotoCamera: 'None',
      frontCamera: '50 MP Samsung ISOCELL JN1, f/2.45, PDAF, 4K@60fps',
      videoRecording: '4K@60fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 68,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '164.5 x 75 x 7.9 mm',
      weight: 185,
      materials: 'Corning Gorilla Glass 5 front/back or vegan leather, plastic frame',
      waterResistance: 'IP53 splash resistant',
      colors: ['Golden Hour', 'Rome Green', 'Fantasy Purple'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'XOS 13',
      launchOS: 'Android 13',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Dual stereo speakers tuned by JBL',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'In-display optical',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.infinixmobiles.in/zero-30-5g/',
      productPage: 'https://www.flipkart.com/infinix-zero-30-5g-store',
      specSheetUrl: 'https://www.infinixmobiles.in/zero-30-5g/',
      verifiedDate: '2023-09',
    },
  },
  {
    id: 'infinix-zero-ultra',
    slug: 'infinix-zero-ultra',
    brand: 'Infinix',
    modelName: 'Infinix Zero Ultra',
    generation: 'Zero Ultra',
    status: 'discontinued',
    launchDate: '2022-12',
    pricing: {
      startingPrice: 32999,
      maximumPrice: 36999,
      launchPrice: 36999,
      currentPrice: 32999,
      currency: 'INR',
      priceEffectiveDate: '2023-09',
      source: 'Infinix India Store Archive',
    },
    display: {
      displaySize: 6.8,
      displayType: '120Hz 3D Curved AMOLED, 900 nits',
      resolution: '2400 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 900,
      hdr: 'HDR10',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '90.7%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 920 5G (6nm)',
      cpu: 'Octa-core (2x2.5 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G68 MC4',
      ramOptions: ['8GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 510000,
    },
    cameras: {
      rearCameraSetup: 'Triple (200MP OIS + 13MP Ultrawide + 2MP Depth)',
      mainCamera: '200 MP Samsung HP1, f/2.0, 1/1.22", OIS, Dual Pixel PDAF',
      ultrawideCamera: '13 MP, f/2.4, AF',
      telephotoCamera: 'None',
      frontCamera: '32 MP, f/2.0',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4500,
      wiredCharging: 180,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '165.5 x 74.5 x 8.8 mm',
      weight: 213,
      materials: '3D textured glass back (Cosima design) / vegan leather, plastic frame',
      waterResistance: 'Splash resistant',
      colors: ['Cosima Silver', 'Genesis Noir'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'XOS 12',
      launchOS: 'Android 12',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'In-display optical',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.infinixmobiles.in/zero-ultra/',
      productPage: 'https://www.flipkart.com/infinix-zero-ultra-store',
      specSheetUrl: 'https://www.infinixmobiles.in/zero-ultra/',
      verifiedDate: '2022-12',
    },
  },
  {
    id: 'infinix-zero-5g-2023',
    slug: 'infinix-zero-5g-2023',
    brand: 'Infinix',
    modelName: 'Infinix Zero 5G 2023',
    generation: 'Zero 5G',
    status: 'discontinued',
    launchDate: '2023-02',
    pricing: {
      startingPrice: 16999,
      maximumPrice: 19999,
      launchPrice: 19999,
      currentPrice: 16999,
      currency: 'INR',
      priceEffectiveDate: '2023-11',
      source: 'Infinix India Store Archive',
    },
    display: {
      displaySize: 6.78,
      displayType: '120Hz IPS LCD, 500 nits',
      resolution: '2460 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 500,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '84.6%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 1080 (6nm)',
      cpu: 'Octa-core (2x2.6 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G68 MC4',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 530000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 2MP Macro + 2MP Depth)',
      mainCamera: '50 MP, f/1.6, PDAF',
      ultrawideCamera: 'None',
      telephotoCamera: 'None',
      frontCamera: '16 MP, f/2.0',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 33,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dedicated Dual SIM + microSD',
    },
    physical: {
      dimensions: '168.7 x 76.5 x 8.9 mm',
      weight: 201,
      materials: 'Uni-curve camera bump polycarbonate design',
      waterResistance: 'None',
      colors: ['Submarine Black', 'Coral Orange', 'Pearly White'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'XOS 12',
      launchOS: 'Android 12',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Single bottom speaker with Hi-Res Audio certification',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.infinixmobiles.in/zero-5g-2023/',
      productPage: 'https://www.flipkart.com/infinix-zero-5g-2023-store',
      specSheetUrl: 'https://www.infinixmobiles.in/zero-5g-2023/',
      verifiedDate: '2023-02',
    },
  },

  // ── NOTE SERIES (Mid-Range Value & Sound) ──
  {
    id: 'infinix-note-30-5g',
    slug: 'infinix-note-30-5g',
    brand: 'Infinix',
    modelName: 'Infinix Note 30 5G',
    generation: 'Note 30',
    status: 'discontinued',
    launchDate: '2023-06',
    pricing: {
      startingPrice: 14999,
      maximumPrice: 15999,
      launchPrice: 15999,
      currentPrice: 14999,
      currency: 'INR',
      priceEffectiveDate: '2024-03',
      source: 'Infinix India Store Archive',
    },
    display: {
      displaySize: 6.78,
      displayType: '120Hz FHD+ IPS LCD, 580 nits peak',
      resolution: '2460 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 580,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '84.7%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6080 (6nm)',
      cpu: 'Octa-core (2x2.4 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['4GB', '8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 410000,
    },
    cameras: {
      rearCameraSetup: 'Triple (108MP + 2MP Depth + AI Camera)',
      mainCamera: '108 MP Samsung HM6, f/1.75, 1/1.67", PDAF',
      ultrawideCamera: 'None',
      telephotoCamera: 'None',
      frontCamera: '16 MP, f/2.0',
      videoRecording: '1440p@30fps, 1080p@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 45,
      wirelessCharging: 0,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5 (ac)',
      bluetooth: 'Bluetooth 5.1',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dedicated Dual SIM + microSD',
    },
    physical: {
      dimensions: '168.5 x 76.5 x 8.5 mm',
      weight: 205,
      materials: 'Glass front, glass back or eco leather back, plastic frame',
      waterResistance: 'IP53 splash resistant',
      colors: ['Magic Black', 'Interstellar Blue', 'Sunset Gold'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'XOS 13',
      launchOS: 'Android 13',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Dual stereo speakers tuned by JBL with Hi-Res Audio certification',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.infinixmobiles.in/note-30-5g/',
      productPage: 'https://www.flipkart.com/infinix-note-30-5g-store',
      specSheetUrl: 'https://www.infinixmobiles.in/note-30-5g/',
      verifiedDate: '2023-06',
    },
  },

  // ── HOT SERIES (Budget Performance) ──
  {
    id: 'infinix-hot-40-pro',
    slug: 'infinix-hot-40-pro',
    brand: 'Infinix',
    modelName: 'Infinix Hot 40 Pro',
    generation: 'Hot 40',
    status: 'active',
    launchDate: '2024-01',
    pricing: {
      startingPrice: 12999,
      maximumPrice: 12999,
      launchPrice: 12999,
      currentPrice: 12999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Infinix India / Flipkart',
    },
    display: {
      displaySize: 6.78,
      displayType: '120Hz FHD+ IPS LCD, 500 nits, Magic Ring notch',
      resolution: '2460 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 500,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '84.5%',
    },
    performance: {
      chipset: 'MediaTek Helio G99 (6nm)',
      cpu: 'Octa-core (2x2.2 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 420000,
    },
    cameras: {
      rearCameraSetup: 'Triple (108MP + 2MP Macro + 0.08MP Auxiliary)',
      mainCamera: '108 MP, f/1.8, 1/1.67", AF',
      ultrawideCamera: 'None',
      telephotoCamera: 'None',
      frontCamera: '32 MP, f/2.2',
      videoRecording: '1440p@30fps, 1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 33,
      wirelessCharging: 0,
      reverseCharging: true,
    },
    connectivity: {
      has5G: false,
      has4G: true,
      wifi: 'Wi-Fi 5 (ac)',
      bluetooth: 'Bluetooth 5.0',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dedicated Dual SIM + microSD',
    },
    physical: {
      dimensions: '168.6 x 76.6 x 8.3 mm',
      weight: 199,
      materials: 'Sparkle layered plastic back, flat frame',
      waterResistance: 'None',
      colors: ['Palm Blue', 'Horizon Gold', 'Starlit Black', 'Starfall Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'XOS 13.5',
      launchOS: 'Android 13',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Hi-Res Audio certification',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.infinixmobiles.in/hot-40-pro/',
      productPage: 'https://www.flipkart.com/infinix-hot-40-pro-store',
      specSheetUrl: 'https://www.infinixmobiles.in/hot-40-pro/',
      verifiedDate: '2024-01',
    },
  },
  {
    id: 'infinix-hot-30-5g',
    slug: 'infinix-hot-30-5g',
    brand: 'Infinix',
    modelName: 'Infinix Hot 30 5G',
    generation: 'Hot 30',
    status: 'discontinued',
    launchDate: '2023-07',
    pricing: {
      startingPrice: 11499,
      maximumPrice: 12499,
      launchPrice: 12499,
      currentPrice: 11499,
      currency: 'INR',
      priceEffectiveDate: '2024-03',
      source: 'Infinix India Store Archive',
    },
    display: {
      displaySize: 6.78,
      displayType: '120Hz FHD+ IPS LCD, 580 nits peak',
      resolution: '2460 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 580,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '84.7%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6020 (7nm)',
      cpu: 'Octa-core (2x2.2 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['4GB', '8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 390000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + AI Lens)',
      mainCamera: '50 MP, f/1.6, Quad-LED flash, PDAF',
      ultrawideCamera: 'None',
      telephotoCamera: 'None',
      frontCamera: '8 MP, f/2.0',
      videoRecording: '1440p@30fps, 1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 6000,
      wiredCharging: 18,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5 (ac)',
      bluetooth: 'Bluetooth 5.1',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dedicated Dual SIM + microSD',
    },
    physical: {
      dimensions: '168.5 x 76.5 x 9.2 mm',
      weight: 215,
      materials: 'Water repellent polycarbonate body, 6000mAh high-capacity battery',
      waterResistance: 'IP53 splash resistant',
      colors: ['Knight Black', 'Aurora Blue'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'XOS 13',
      launchOS: 'Android 13',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with DTS sound',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.infinixmobiles.in/hot-30-5g/',
      productPage: 'https://www.flipkart.com/infinix-hot-30-5g-store',
      specSheetUrl: 'https://www.infinixmobiles.in/hot-30-5g/',
      verifiedDate: '2023-07',
    },
  },

  // ── SMART SERIES (Entry-Level Value) ──
  {
    id: 'infinix-smart-8-hd',
    slug: 'infinix-smart-8-hd',
    brand: 'Infinix',
    modelName: 'Infinix Smart 8 HD',
    generation: 'Smart 8',
    status: 'active',
    launchDate: '2023-12',
    pricing: {
      startingPrice: 6299,
      maximumPrice: 6999,
      launchPrice: 6299,
      currentPrice: 6299,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Infinix India / Flipkart',
    },
    display: {
      displaySize: 6.6,
      displayType: '90Hz HD+ IPS LCD, 500 nits, Magic Ring interactive punch hole',
      resolution: '1612 x 720 pixels',
      refreshRate: 90,
      peakBrightness: 500,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '84.6%',
    },
    performance: {
      chipset: 'Unisoc T606 (12nm)',
      cpu: 'Octa-core (2x1.6 GHz Cortex-A75 & 6x1.6 GHz Cortex-A55)',
      gpu: 'Mali-G57 MP1',
      ramOptions: ['3GB', '4GB'],
      storageOptions: ['64GB'],
      storageType: 'UFS 2.2',
      antutuScore: 235000,
    },
    cameras: {
      rearCameraSetup: 'Dual (13MP + AI Lens)',
      mainCamera: '13 MP, f/2.0, Ring-LED flash',
      ultrawideCamera: 'None',
      telephotoCamera: 'None',
      frontCamera: '8 MP, f/2.0, front LED flash',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 10,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: false,
      has4G: true,
      wifi: 'Wi-Fi 5 (ac)',
      bluetooth: 'Bluetooth 5.0',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dedicated Dual SIM + microSD',
    },
    physical: {
      dimensions: '163.6 x 75.6 x 8.5 mm',
      weight: 184,
      materials: 'Timber textured plastic back finish, flat edges',
      waterResistance: 'None',
      colors: ['Crystal Green', 'Shiny Gold', 'Timber Black', 'Galaxy White'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'XOS 13 (Android 13 Go edition)',
      launchOS: 'Android 13 (Go edition)',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Single bottom loudspeaker with DTS audio processing',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.infinixmobiles.in/smart-8-hd/',
      productPage: 'https://www.flipkart.com/infinix-smart-8-hd-store',
      specSheetUrl: 'https://www.infinixmobiles.in/smart-8-hd/',
      verifiedDate: '2023-12',
    },
  },
];

const variants: MobileVariant[] = [
  // GT 20 Pro
  {
    id: 'infinix-gt-20-pro-8-256',
    modelId: 'infinix-gt-20-pro',
    name: 'Infinix GT 20 Pro (8GB RAM, 256GB)',
    ram: '8GB',
    storage: '256GB',
    color: 'Mecha Silver',
    price: 22999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  {
    id: 'infinix-gt-20-pro-12-256',
    modelId: 'infinix-gt-20-pro',
    name: 'Infinix GT 20 Pro (12GB RAM, 256GB)',
    ram: '12GB',
    storage: '256GB',
    color: 'Mecha Blue',
    price: 24999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // GT 10 Pro
  {
    id: 'infinix-gt-10-pro-8-256',
    modelId: 'infinix-gt-10-pro',
    name: 'Infinix GT 10 Pro (8GB RAM, 256GB)',
    ram: '8GB',
    storage: '256GB',
    color: 'Cyber Black',
    price: 19999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  // Zero 40 5G
  {
    id: 'infinix-zero-40-5g-12-256',
    modelId: 'infinix-zero-40-5g',
    name: 'Infinix Zero 40 5G (12GB RAM, 256GB)',
    ram: '12GB',
    storage: '256GB',
    color: 'Violet Garden',
    price: 27999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  {
    id: 'infinix-zero-40-5g-12-512',
    modelId: 'infinix-zero-40-5g',
    name: 'Infinix Zero 40 5G (12GB RAM, 512GB)',
    ram: '12GB',
    storage: '512GB',
    color: 'Rock Black',
    price: 30999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Zero 30 5G
  {
    id: 'infinix-zero-30-5g-8-256',
    modelId: 'infinix-zero-30-5g',
    name: 'Infinix Zero 30 5G (8GB RAM, 256GB)',
    ram: '8GB',
    storage: '256GB',
    color: 'Golden Hour',
    price: 21999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  {
    id: 'infinix-zero-30-5g-12-256',
    modelId: 'infinix-zero-30-5g',
    name: 'Infinix Zero 30 5G (12GB RAM, 256GB)',
    ram: '12GB',
    storage: '256GB',
    color: 'Rome Green',
    price: 23999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  // Zero Ultra
  {
    id: 'infinix-zero-ultra-8-256',
    modelId: 'infinix-zero-ultra',
    name: 'Infinix Zero Ultra (8GB RAM, 256GB, 180W Charge)',
    ram: '8GB',
    storage: '256GB',
    color: 'Cosima Silver',
    price: 32999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  // Zero 5G 2023
  {
    id: 'infinix-zero-5g-2023-8-128',
    modelId: 'infinix-zero-5g-2023',
    name: 'Infinix Zero 5G 2023 (8GB RAM, 128GB)',
    ram: '8GB',
    storage: '128GB',
    color: 'Submarine Black',
    price: 16999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  // Note 30 5G
  {
    id: 'infinix-note-30-5g-4-128',
    modelId: 'infinix-note-30-5g',
    name: 'Infinix Note 30 5G (4GB RAM, 128GB)',
    ram: '4GB',
    storage: '128GB',
    color: 'Magic Black',
    price: 14999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  {
    id: 'infinix-note-30-5g-8-256',
    modelId: 'infinix-note-30-5g',
    name: 'Infinix Note 30 5G (8GB RAM, 256GB)',
    ram: '8GB',
    storage: '256GB',
    color: 'Sunset Gold',
    price: 15999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  // Hot 40 Pro
  {
    id: 'infinix-hot-40-pro-8-128',
    modelId: 'infinix-hot-40-pro',
    name: 'Infinix Hot 40 Pro (8GB RAM, 128GB)',
    ram: '8GB',
    storage: '128GB',
    color: 'Palm Blue',
    price: 12999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Hot 30 5G
  {
    id: 'infinix-hot-30-5g-4-128',
    modelId: 'infinix-hot-30-5g',
    name: 'Infinix Hot 30 5G (4GB RAM, 128GB)',
    ram: '4GB',
    storage: '128GB',
    color: 'Knight Black',
    price: 11499,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  // Smart 8 HD
  {
    id: 'infinix-smart-8-hd-3-64',
    modelId: 'infinix-smart-8-hd',
    name: 'Infinix Smart 8 HD (3GB RAM, 64GB)',
    ram: '3GB',
    storage: '64GB',
    color: 'Crystal Green',
    price: 6299,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    modelId: 'infinix-gt-20-pro',
    modelName: 'Infinix GT 20 Pro',
    brand: 'Infinix',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/infinix-gt20-pro.jpg',
        angle: 'front',
        source: 'Infinix Official (GSMArena CDN)',
        sourceUrl: 'https://www.infinixmobiles.in/gt-20-pro/',
        verified: true,
        alt: 'Infinix GT 20 Pro front display view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/infinix/infinix-gt-20-pro-01.jpg',
        angle: 'back',
        source: 'Infinix Official (GSMArena CDN)',
        sourceUrl: 'https://www.infinixmobiles.in/gt-20-pro/',
        verified: true,
        alt: 'Infinix GT 20 Pro Mecha Loop mini-LED rear view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/infinix/infinix-gt-20-pro-02.jpg',
        angle: 'side',
        source: 'Infinix Official (GSMArena CDN)',
        sourceUrl: 'https://www.infinixmobiles.in/gt-20-pro/',
        verified: true,
        alt: 'Infinix GT 20 Pro profile',
      },
    ],
  },
  {
    modelId: 'infinix-gt-10-pro',
    modelName: 'Infinix GT 10 Pro',
    brand: 'Infinix',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/infinix-gt10-pro.jpg',
        angle: 'front',
        source: 'Infinix Official (GSMArena CDN)',
        sourceUrl: 'https://www.infinixmobiles.in/gt-10-pro/',
        verified: true,
        alt: 'Infinix GT 10 Pro front display view',
      },
    ],
  },
  {
    modelId: 'infinix-zero-40-5g',
    modelName: 'Infinix Zero 40 5G',
    brand: 'Infinix',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://global.pro.infinixmobility.com/media/wysiwyg/X6861_ZERO_40_5G_base4_family.png',
        angle: 'front',
        source: 'Infinix Official CDN',
        sourceUrl: 'https://www.infinixmobiles.in/zero-40-5g/',
        verified: true,
        alt: 'Infinix Zero 40 5G front and rear official view',
      },
      {
        url: 'https://d3o31au25zfcly.cloudfront.net/newfileadmin/usp/zero/zero-40-5g/section-1/mb/new-kv-mb-v2.webp',
        angle: 'back',
        source: 'Infinix CloudFront CDN',
        sourceUrl: 'https://www.infinixmobiles.in/zero-40-5g/',
        verified: true,
        alt: 'Infinix Zero 40 5G 108MP OIS camera array view',
      },
    ],
  },
  {
    modelId: 'infinix-zero-30-5g',
    modelName: 'Infinix Zero 30 5G',
    brand: 'Infinix',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/infinix-zero30-5g.jpg',
        angle: 'front',
        source: 'Infinix Official (GSMArena CDN)',
        sourceUrl: 'https://www.infinixmobiles.in/zero-30-5g/',
        verified: true,
        alt: 'Infinix Zero 30 5G front curved display view',
      },
    ],
  },
  {
    modelId: 'infinix-zero-ultra',
    modelName: 'Infinix Zero Ultra',
    brand: 'Infinix',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/infinix-zero-ultra.jpg',
        angle: 'front',
        source: 'Infinix Official (GSMArena CDN)',
        sourceUrl: 'https://www.infinixmobiles.in/zero-ultra/',
        verified: true,
        alt: 'Infinix Zero Ultra front curved display view',
      },
    ],
  },
  {
    modelId: 'infinix-zero-5g-2023',
    modelName: 'Infinix Zero 5G 2023',
    brand: 'Infinix',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/infinix-zero-5g-2023.jpg',
        angle: 'front',
        source: 'Infinix Official (GSMArena CDN)',
        sourceUrl: 'https://www.infinixmobiles.in/zero-5g-2023/',
        verified: true,
        alt: 'Infinix Zero 5G 2023 front display view',
      },
    ],
  },
  {
    modelId: 'infinix-note-30-5g',
    modelName: 'Infinix Note 30 5G',
    brand: 'Infinix',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/infinix-note-30-5g.jpg',
        angle: 'front',
        source: 'Infinix Official (GSMArena CDN)',
        sourceUrl: 'https://www.infinixmobiles.in/note-30-5g/',
        verified: true,
        alt: 'Infinix Note 30 5G front display view',
      },
    ],
  },
  {
    modelId: 'infinix-hot-40-pro',
    modelName: 'Infinix Hot 40 Pro',
    brand: 'Infinix',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/infinix-hot-40-pro.jpg',
        angle: 'front',
        source: 'Infinix Official (GSMArena CDN)',
        sourceUrl: 'https://www.infinixmobiles.in/hot-40-pro/',
        verified: true,
        alt: 'Infinix Hot 40 Pro front display view',
      },
    ],
  },
  {
    modelId: 'infinix-hot-30-5g',
    modelName: 'Infinix Hot 30 5G',
    brand: 'Infinix',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/infinix-hot-30-5g.jpg',
        angle: 'front',
        source: 'Infinix Official (GSMArena CDN)',
        sourceUrl: 'https://www.infinixmobiles.in/hot-30-5g/',
        verified: true,
        alt: 'Infinix Hot 30 5G front display view',
      },
    ],
  },
  {
    modelId: 'infinix-smart-8-hd',
    modelName: 'Infinix Smart 8 HD',
    brand: 'Infinix',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/infinix-smart-8-hd.jpg',
        angle: 'front',
        source: 'Infinix Official (GSMArena CDN)',
        sourceUrl: 'https://www.infinixmobiles.in/smart-8-hd/',
        verified: true,
        alt: 'Infinix Smart 8 HD front display view',
      },
    ],
  },
];

export const infinixBundle: MobileBrandBundle = {
  brand: 'Infinix',
  models,
  variants,
  images,
};
