import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  // ── iQOO NUMBERED FLAGSHIPS ──
  {
    id: 'iqoo-13-5g',
    slug: 'iqoo-13-5g',
    brand: 'iQOO',
    modelName: 'iQOO 13 5G',
    generation: '13',
    status: 'active',
    launchDate: '2024-12',
    pricing: {
      startingPrice: 54999,
      maximumPrice: 59999,
      launchPrice: 54999,
      currentPrice: 54999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Amazon India / iQOO India',
    },
    display: {
      displaySize: 6.82,
      displayType: '2K 144Hz LTPO AMOLED BOE Q10 panel',
      resolution: '3168 x 1440 pixels (2K)',
      refreshRate: 144,
      peakBrightness: 4500,
      hdr: 'HDR10+',
      protection: 'Crystal Armor Glass',
      screenToBodyRatio: '90.4%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Elite (3nm)',
      cpu: 'Octa-core (2x4.32 GHz Oryon V2 Phoenix L & 6x3.53 GHz Oryon V2 Phoenix M)',
      gpu: 'Adreno 830',
      ramOptions: ['12GB', '16GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 2950000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 50MP) with Monster Halo RGB ring',
      mainCamera: '50 MP Sony IMX921, 1/1.56", f/1.88, VCS, OIS',
      ultrawideCamera: '50 MP Samsung JN1, f/2.0, 119˚',
      telephotoCamera: '50 MP Sony IMX816 2x telephoto, f/1.85, OIS',
      frontCamera: '32 MP, f/2.45',
      videoRecording: '8K@30fps, 4K@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 6000,
      wiredCharging: 120,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 3.2 Gen 1',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '163.37 x 76.71 x 7.99 mm',
      weight: 207,
      materials: 'Glass front, aerospace-grade aluminum frame, AG glass back',
      waterResistance: 'IP68/IP69',
      colors: ['Legend (BMW M Motorsport)', 'Nardo Grey'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 15',
      launchOS: 'Android 15',
      promisedMajorUpdates: 4,
      securityUpdatePolicy: '5 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: '3D Ultrasonic under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.iqoo.com/in/products/iqoo13',
      productPage: 'https://www.amazon.in/dp/B0DJF6P6L4',
      specSheetUrl: 'https://www.iqoo.com/in/products/param/iqoo13',
      verifiedDate: '2024-12',
    },
  },

  {
    id: 'iqoo-12-5g',
    slug: 'iqoo-12-5g',
    brand: 'iQOO',
    modelName: 'iQOO 12 5G',
    generation: '12',
    status: 'active',
    launchDate: '2023-12',
    pricing: {
      startingPrice: 52999,
      maximumPrice: 57999,
      launchPrice: 52999,
      currentPrice: 52999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Amazon India / iQOO India',
    },
    display: {
      displaySize: 6.78,
      displayType: '1.5K 144Hz LTPO AMOLED, 1B colors, HDR10+',
      resolution: '2800 x 1260 pixels',
      refreshRate: 144,
      peakBrightness: 3000,
      hdr: 'HDR10+',
      protection: 'Toughened Glass',
      screenToBodyRatio: '89.6%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Gen 3 (4nm)',
      cpu: 'Octa-core (1x3.3 GHz Cortex-X4 & 5x3.2 GHz & 2x2.3 GHz)',
      gpu: 'Adreno 750 (with Q1 Supercomputing gaming chip)',
      ramOptions: ['12GB', '16GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 2120000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 64MP + 50MP) Astrography',
      mainCamera: '50 MP OmniVision OV50H, 1/1.3", f/1.68, VCS, OIS',
      ultrawideCamera: '50 MP Samsung JN1, f/2.0, 119˚',
      telephotoCamera: '64 MP OmniVision OV64B 3x periscope, 70mm, 100x digital, OIS',
      frontCamera: '16 MP, f/2.45',
      videoRecording: '8K@30fps, 4K@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 120,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '163.22 x 75.88 x 8.1 mm',
      weight: 203.7,
      materials: 'Glass front, aluminum frame, porthole design glass back',
      waterResistance: 'IP64',
      colors: ['Legend (White)', 'Alpha (Black)'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 14 (upgraded to 15)',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.iqoo.com/in/products/iqoo12',
      productPage: 'https://www.amazon.in/dp/B07WGNK9P2',
      specSheetUrl: 'https://www.iqoo.com/in/products/param/iqoo12',
      verifiedDate: '2023-12',
    },
  },

  {
    id: 'iqoo-11-5g',
    slug: 'iqoo-11-5g',
    brand: 'iQOO',
    modelName: 'iQOO 11 5G',
    generation: '11',
    status: 'discontinued',
    launchDate: '2023-01',
    pricing: {
      startingPrice: 49999,
      maximumPrice: 54999,
      launchPrice: 59999,
      currentPrice: 49999,
      currency: 'INR',
      priceEffectiveDate: '2024-01',
      source: 'Amazon India / iQOO India',
    },
    display: {
      displaySize: 6.78,
      displayType: '2K 144Hz E6 AMOLED, 1B colors, HDR10+',
      resolution: '3200 x 1440 pixels (WQHD+)',
      refreshRate: 144,
      peakBrightness: 1800,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass Victus',
      screenToBodyRatio: '87.3%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Gen 2 (4nm)',
      cpu: 'Octa-core (1x3.2 GHz Cortex-X3 & 4x2.8 GHz & 3x2.0 GHz)',
      gpu: 'Adreno 740 (with V2 chip)',
      ramOptions: ['8GB', '16GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 4.0',
      antutuScore: 1330000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 13MP + 8MP) with V2 imaging chip',
      mainCamera: '50 MP Samsung ISOCELL GN5, f/1.88, OIS',
      ultrawideCamera: '8 MP, f/2.2, 116˚',
      telephotoCamera: '13 MP 2x telephoto, f/2.46, 50mm portrait',
      frontCamera: '16 MP, f/2.45',
      videoRecording: '8K@30fps, 4K@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 120,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '164.86 x 77.07 x 8.4 mm',
      weight: 205,
      materials: 'Glass front (Victus), aluminum frame, silicone polymer (vegan leather) / glass back',
      waterResistance: 'None',
      colors: ['Legend (White)', 'Alpha (Black)'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 13',
      launchOS: 'Android 13',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.iqoo.com/in/products/iqoo11',
      productPage: 'https://www.amazon.in/dp/B07WDKLR1V',
      specSheetUrl: 'https://www.iqoo.com/in/products/param/iqoo11',
      verifiedDate: '2023-01',
    },
  },

  // ── iQOO NEO SERIES (Performance Flagship Killers) ──
  {
    id: 'iqoo-neo-9-pro-5g',
    slug: 'iqoo-neo-9-pro-5g',
    brand: 'iQOO',
    modelName: 'iQOO Neo 9 Pro 5G',
    generation: 'Neo 9',
    status: 'active',
    launchDate: '2024-02',
    pricing: {
      startingPrice: 35999,
      maximumPrice: 39999,
      launchPrice: 37999,
      currentPrice: 35999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Amazon India / iQOO India',
    },
    display: {
      displaySize: 6.78,
      displayType: '1.5K 144Hz LTPO AMOLED, HDR10+',
      resolution: '2800 x 1260 pixels',
      refreshRate: 144,
      peakBrightness: 3000,
      hdr: 'HDR10+',
      protection: 'Schott Xensation Up',
      screenToBodyRatio: '89.7%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Gen 2 (4nm)',
      cpu: 'Octa-core (1x3.2 GHz Cortex-X3 & 4x2.8 GHz & 3x2.0 GHz)',
      gpu: 'Adreno 740 (with Q1 Supercomputing chip)',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 4.0',
      antutuScore: 1680000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 8MP)',
      mainCamera: '50 MP Sony IMX920, 1/1.49", f/1.88, VCS, OIS',
      ultrawideCamera: '8 MP, f/2.2, 119˚',
      telephotoCamera: 'None',
      frontCamera: '16 MP, f/2.45',
      videoRecording: '8K@30fps, 4K@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5160,
      wiredCharging: 120,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '163.53 x 75.68 x 7.99 mm',
      weight: 190,
      materials: 'Glass front, plastic frame, dual-tone vegan leather / AG glass back',
      waterResistance: 'IP54',
      colors: ['Fiery Red', 'Conqueror Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.iqoo.com/in/products/neo9pro',
      productPage: 'https://www.amazon.in/dp/B07WHS748Q',
      specSheetUrl: 'https://www.iqoo.com/in/products/param/neo9pro',
      verifiedDate: '2024-02',
    },
  },

  {
    id: 'iqoo-neo-7-pro-5g',
    slug: 'iqoo-neo-7-pro-5g',
    brand: 'iQOO',
    modelName: 'iQOO Neo 7 Pro 5G',
    generation: 'Neo 7',
    status: 'discontinued',
    launchDate: '2023-07',
    pricing: {
      startingPrice: 29999,
      maximumPrice: 33999,
      launchPrice: 34999,
      currentPrice: 29999,
      currency: 'INR',
      priceEffectiveDate: '2024-03',
      source: 'Amazon India / iQOO India',
    },
    display: {
      displaySize: 6.78,
      displayType: 'AMOLED, 120Hz, HDR10+',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1300,
      hdr: 'HDR10+',
      protection: 'Schott Xensation Up',
      screenToBodyRatio: '87.6%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8+ Gen 1 (4nm)',
      cpu: 'Octa-core (1x3.19 GHz Cortex-X2 & 3x2.75 GHz Cortex-A710 & 4x1.80 GHz Cortex-A510)',
      gpu: 'Adreno 730 (with independent gaming chip)',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 1250000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 8MP + 2MP)',
      mainCamera: '50 MP Samsung GN5, f/1.88, OIS',
      ultrawideCamera: '8 MP, f/2.2, 120˚',
      telephotoCamera: '2 MP macro, f/2.4',
      frontCamera: '16 MP, f/2.45',
      videoRecording: '4K@60fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 120,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '164.81 x 76.9 x 8.5 mm',
      weight: 199.5,
      materials: 'Glass front, plastic frame, vegan leather / AG glass back',
      waterResistance: 'None',
      colors: ['Fearless Flame (Orange Leather)', 'Dark Storm'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 13',
      launchOS: 'Android 13',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.iqoo.com/in/products/neo7pro',
      productPage: 'https://www.amazon.in/dp/B07WJTTN8G',
      specSheetUrl: 'https://www.iqoo.com/in/products/param/neo7pro',
      verifiedDate: '2023-07',
    },
  },

  {
    id: 'iqoo-neo-7-5g',
    slug: 'iqoo-neo-7-5g',
    brand: 'iQOO',
    modelName: 'iQOO Neo 7 5G',
    generation: 'Neo 7',
    status: 'discontinued',
    launchDate: '2023-02',
    pricing: {
      startingPrice: 24999,
      maximumPrice: 27999,
      launchPrice: 29999,
      currentPrice: 24999,
      currency: 'INR',
      priceEffectiveDate: '2024-01',
      source: 'Amazon India / iQOO India',
    },
    display: {
      displaySize: 6.78,
      displayType: 'AMOLED, 120Hz, HDR10+',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1300,
      hdr: 'HDR10+',
      protection: 'Schott Xensation Up',
      screenToBodyRatio: '87.6%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 8200 (4nm)',
      cpu: 'Octa-core (1x3.1 GHz Cortex-A78 & 3x3.0 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G610 MC6',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 890000,
    },
    cameras: {
      rearCameraSetup: 'Triple (64MP + 2MP + 2MP)',
      mainCamera: '64 MP, f/1.79, OIS',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP macro + 2 MP depth',
      frontCamera: '16 MP, f/2.45',
      videoRecording: '4K@60fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 120,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '164.81 x 76.9 x 8.58 mm',
      weight: 193,
      materials: 'Glass front, plastic frame and back',
      waterResistance: 'None',
      colors: ['Frost Blue', 'Interstellar Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 13',
      launchOS: 'Android 13',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.iqoo.com/in/products/neo7',
      productPage: 'https://www.amazon.in/dp/B07WDKLR1U',
      specSheetUrl: 'https://www.iqoo.com/in/products/param/neo7',
      verifiedDate: '2023-02',
    },
  },

  // ── iQOO Z SERIES (Mid-range Performance) ──
  {
    id: 'iqoo-z9s-pro-5g',
    slug: 'iqoo-z9s-pro-5g',
    brand: 'iQOO',
    modelName: 'iQOO Z9s Pro 5G',
    generation: 'Z9',
    status: 'active',
    launchDate: '2024-08',
    pricing: {
      startingPrice: 24999,
      maximumPrice: 28999,
      launchPrice: 24999,
      currentPrice: 24999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Amazon India / iQOO India',
    },
    display: {
      displaySize: 6.77,
      displayType: '120Hz 3D Curved AMOLED',
      resolution: '2392 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 4500,
      hdr: 'HDR10+',
      protection: 'Schott Xensation Up',
      screenToBodyRatio: '90.3%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7 Gen 3 (4nm)',
      cpu: 'Octa-core (1x2.63 GHz Cortex-A715 & 4x2.4 GHz Cortex-A715 & 3x1.8 GHz Cortex-A510)',
      gpu: 'Adreno 720',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 820000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 8MP)',
      mainCamera: '50 MP Sony IMX882, f/1.79, OIS, Aura Light',
      ultrawideCamera: '8 MP, f/2.2, 120˚',
      telephotoCamera: 'None',
      frontCamera: '16 MP, f/2.45',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5500,
      wiredCharging: 80,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.4',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '163.72 x 75.0 x 7.49 mm',
      weight: 185,
      materials: 'Glass front, plastic frame, vegan leather / marble-textured back',
      waterResistance: 'IP64',
      colors: ['Luxe Marble', 'Flamboyant Orange'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.iqoo.com/in/products/z9spro',
      productPage: 'https://www.amazon.in/dp/B0D9D5Q59B',
      specSheetUrl: 'https://www.iqoo.com/in/products/param/z9spro',
      verifiedDate: '2024-08',
    },
  },

  {
    id: 'iqoo-z9s-5g',
    slug: 'iqoo-z9s-5g',
    brand: 'iQOO',
    modelName: 'iQOO Z9s 5G',
    generation: 'Z9',
    status: 'active',
    launchDate: '2024-08',
    pricing: {
      startingPrice: 19999,
      maximumPrice: 23999,
      launchPrice: 19999,
      currentPrice: 19999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Amazon India / iQOO India',
    },
    display: {
      displaySize: 6.77,
      displayType: '120Hz 3D Curved AMOLED',
      resolution: '2392 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1800,
      hdr: 'HDR10+',
      protection: 'Schott Xensation Up',
      screenToBodyRatio: '90.3%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7300 (4nm)',
      cpu: 'Octa-core (4x2.5 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G615 MC2',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 710000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP)',
      mainCamera: '50 MP Sony IMX882, f/1.79, OIS, Aura Light',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP depth sensor',
      frontCamera: '16 MP, f/2.45',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5500,
      wiredCharging: 44,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.4',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '163.72 x 75.0 x 7.49 mm',
      weight: 182,
      materials: 'Glass front, plastic frame and back',
      waterResistance: 'IP64',
      colors: ['Titanium Matte', 'Onyx Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.iqoo.com/in/products/z9s',
      productPage: 'https://www.amazon.in/dp/B0D9D5Q59C',
      specSheetUrl: 'https://www.iqoo.com/in/products/param/z9s',
      verifiedDate: '2024-08',
    },
  },

  {
    id: 'iqoo-z9-5g',
    slug: 'iqoo-z9-5g',
    brand: 'iQOO',
    modelName: 'iQOO Z9 5G',
    generation: 'Z9',
    status: 'active',
    launchDate: '2024-03',
    pricing: {
      startingPrice: 17999,
      maximumPrice: 19999,
      launchPrice: 19999,
      currentPrice: 17999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Amazon India / iQOO India',
    },
    display: {
      displaySize: 6.67,
      displayType: 'AMOLED, 120Hz, HDR10+',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1800,
      hdr: 'HDR10+',
      protection: 'Asahi Glass DT-Star2 Plus',
      screenToBodyRatio: '86.8%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7200 (4nm)',
      cpu: 'Octa-core (2x2.8 GHz Cortex-A715 & 6x2.0 GHz Cortex-A510)',
      gpu: 'Mali-G610 MC4',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 730000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP)',
      mainCamera: '50 MP Sony IMX882, f/1.79, OIS',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP depth sensor',
      frontCamera: '16 MP, f/2.0',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 44,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '163.17 x 75.81 x 7.83 mm',
      weight: 188,
      materials: 'Glass front, plastic frame, textured pattern back',
      waterResistance: 'IP54',
      colors: ['Brushed Green', 'Graphene Blue'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with 300% volume boost',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.iqoo.com/in/products/z9',
      productPage: 'https://www.amazon.in/dp/B07WGNK9P1',
      specSheetUrl: 'https://www.iqoo.com/in/products/param/z9',
      verifiedDate: '2024-03',
    },
  },

  {
    id: 'iqoo-z9x-5g',
    slug: 'iqoo-z9x-5g',
    brand: 'iQOO',
    modelName: 'iQOO Z9x 5G',
    generation: 'Z9',
    status: 'active',
    launchDate: '2024-05',
    pricing: {
      startingPrice: 12499,
      maximumPrice: 15499,
      launchPrice: 12999,
      currentPrice: 12499,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Amazon India / iQOO India',
    },
    display: {
      displaySize: 6.72,
      displayType: 'IPS LCD, 120Hz',
      resolution: '2408 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1000,
      hdr: 'None',
      protection: 'Toughened Glass',
      screenToBodyRatio: '86.4%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 6 Gen 1 (4nm)',
      cpu: 'Octa-core (4x2.2 GHz Cortex-A78 & 4x1.8 GHz Cortex-A55)',
      gpu: 'Adreno 710',
      ramOptions: ['4GB', '6GB', '8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 560000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP)',
      mainCamera: '50 MP, f/1.8',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP depth sensor',
      frontCamera: '8 MP, f/2.05',
      videoRecording: '4K@30fps, 1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 6000,
      wiredCharging: 44,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.1',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '165.7 x 76.0 x 7.99 mm',
      weight: 199,
      materials: 'Glass front, plastic frame and back',
      waterResistance: 'IP64',
      colors: ['Tornado Green', 'Storm Grey'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with 300% volume audio booster',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.iqoo.com/in/products/z9x',
      productPage: 'https://www.amazon.in/dp/B07WGNK9P3',
      specSheetUrl: 'https://www.iqoo.com/in/products/param/z9x',
      verifiedDate: '2024-05',
    },
  },
];

const variants: MobileVariant[] = [
  // iQOO 13 5G
  {
    id: 'iqoo-13-5g-12-256',
    modelId: 'iqoo-13-5g',
    ram: '12GB',
    storage: '256GB',
    price: 54999,
    mrp: 54999,
    colors: ['Legend (BMW M Motorsport)', 'Nardo Grey'],
    status: 'active',
    verified: true,
    source: 'Amazon India / iQOO India',
  },
  {
    id: 'iqoo-13-5g-16-512',
    modelId: 'iqoo-13-5g',
    ram: '16GB',
    storage: '512GB',
    price: 59999,
    mrp: 59999,
    colors: ['Legend (BMW M Motorsport)', 'Nardo Grey'],
    status: 'active',
    verified: true,
    source: 'Amazon India / iQOO India',
  },
  // iQOO 12 5G
  {
    id: 'iqoo-12-5g-12-256',
    modelId: 'iqoo-12-5g',
    ram: '12GB',
    storage: '256GB',
    price: 52999,
    mrp: 52999,
    colors: ['Legend (White)', 'Alpha (Black)'],
    status: 'active',
    verified: true,
    source: 'Amazon India / iQOO India',
  },
  {
    id: 'iqoo-12-5g-16-512',
    modelId: 'iqoo-12-5g',
    ram: '16GB',
    storage: '512GB',
    price: 57999,
    mrp: 57999,
    colors: ['Legend (White)', 'Alpha (Black)'],
    status: 'active',
    verified: true,
    source: 'Amazon India / iQOO India',
  },
  // iQOO 11 5G
  {
    id: 'iqoo-11-5g-8-256',
    modelId: 'iqoo-11-5g',
    ram: '8GB',
    storage: '256GB',
    price: 49999,
    mrp: 59999,
    colors: ['Legend (White)', 'Alpha (Black)'],
    status: 'discontinued',
    verified: true,
    source: 'Amazon India / iQOO India',
  },
  {
    id: 'iqoo-11-5g-16-256',
    modelId: 'iqoo-11-5g',
    ram: '16GB',
    storage: '256GB',
    price: 54999,
    mrp: 64999,
    colors: ['Legend (White)', 'Alpha (Black)'],
    status: 'discontinued',
    verified: true,
    source: 'Amazon India / iQOO India',
  },
  // iQOO Neo 9 Pro 5G
  {
    id: 'iqoo-neo-9-pro-5g-8-128',
    modelId: 'iqoo-neo-9-pro-5g',
    ram: '8GB',
    storage: '128GB',
    price: 35999,
    mrp: 37999,
    colors: ['Fiery Red', 'Conqueror Black'],
    status: 'active',
    verified: true,
    source: 'Amazon India / iQOO India',
  },
  {
    id: 'iqoo-neo-9-pro-5g-12-256',
    modelId: 'iqoo-neo-9-pro-5g',
    ram: '12GB',
    storage: '256GB',
    price: 39999,
    mrp: 41999,
    colors: ['Fiery Red', 'Conqueror Black'],
    status: 'active',
    verified: true,
    source: 'Amazon India / iQOO India',
  },
  // iQOO Neo 7 Pro 5G
  {
    id: 'iqoo-neo-7-pro-5g-8-128',
    modelId: 'iqoo-neo-7-pro-5g',
    ram: '8GB',
    storage: '128GB',
    price: 29999,
    mrp: 34999,
    colors: ['Fearless Flame', 'Dark Storm'],
    status: 'discontinued',
    verified: true,
    source: 'Amazon India / iQOO India',
  },
  {
    id: 'iqoo-neo-7-pro-5g-12-256',
    modelId: 'iqoo-neo-7-pro-5g',
    ram: '12GB',
    storage: '256GB',
    price: 33999,
    mrp: 37999,
    colors: ['Fearless Flame', 'Dark Storm'],
    status: 'discontinued',
    verified: true,
    source: 'Amazon India / iQOO India',
  },
  // iQOO Neo 7 5G
  {
    id: 'iqoo-neo-7-5g-8-128',
    modelId: 'iqoo-neo-7-5g',
    ram: '8GB',
    storage: '128GB',
    price: 24999,
    mrp: 29999,
    colors: ['Frost Blue', 'Interstellar Black'],
    status: 'discontinued',
    verified: true,
    source: 'Amazon India / iQOO India',
  },
  {
    id: 'iqoo-neo-7-5g-12-256',
    modelId: 'iqoo-neo-7-5g',
    ram: '12GB',
    storage: '256GB',
    price: 27999,
    mrp: 33999,
    colors: ['Frost Blue', 'Interstellar Black'],
    status: 'discontinued',
    verified: true,
    source: 'Amazon India / iQOO India',
  },
  // iQOO Z9s Pro 5G
  {
    id: 'iqoo-z9s-pro-5g-8-128',
    modelId: 'iqoo-z9s-pro-5g',
    ram: '8GB',
    storage: '128GB',
    price: 24999,
    mrp: 24999,
    colors: ['Luxe Marble', 'Flamboyant Orange'],
    status: 'active',
    verified: true,
    source: 'Amazon India / iQOO India',
  },
  {
    id: 'iqoo-z9s-pro-5g-12-256',
    modelId: 'iqoo-z9s-pro-5g',
    ram: '12GB',
    storage: '256GB',
    price: 28999,
    mrp: 28999,
    colors: ['Luxe Marble', 'Flamboyant Orange'],
    status: 'active',
    verified: true,
    source: 'Amazon India / iQOO India',
  },
  // iQOO Z9s 5G
  {
    id: 'iqoo-z9s-5g-8-128',
    modelId: 'iqoo-z9s-5g',
    ram: '8GB',
    storage: '128GB',
    price: 19999,
    mrp: 19999,
    colors: ['Titanium Matte', 'Onyx Green'],
    status: 'active',
    verified: true,
    source: 'Amazon India / iQOO India',
  },
  {
    id: 'iqoo-z9s-5g-12-256',
    modelId: 'iqoo-z9s-5g',
    ram: '12GB',
    storage: '256GB',
    price: 23999,
    mrp: 23999,
    colors: ['Titanium Matte', 'Onyx Green'],
    status: 'active',
    verified: true,
    source: 'Amazon India / iQOO India',
  },
  // iQOO Z9 5G
  {
    id: 'iqoo-z9-5g-8-128',
    modelId: 'iqoo-z9-5g',
    ram: '8GB',
    storage: '128GB',
    price: 17999,
    mrp: 19999,
    colors: ['Brushed Green', 'Graphene Blue'],
    status: 'active',
    verified: true,
    source: 'Amazon India / iQOO India',
  },
  {
    id: 'iqoo-z9-5g-8-256',
    modelId: 'iqoo-z9-5g',
    ram: '8GB',
    storage: '256GB',
    price: 19999,
    mrp: 21999,
    colors: ['Brushed Green', 'Graphene Blue'],
    status: 'active',
    verified: true,
    source: 'Amazon India / iQOO India',
  },
  // iQOO Z9x 5G
  {
    id: 'iqoo-z9x-5g-4-128',
    modelId: 'iqoo-z9x-5g',
    ram: '4GB',
    storage: '128GB',
    price: 12499,
    mrp: 12999,
    colors: ['Tornado Green', 'Storm Grey'],
    status: 'active',
    verified: true,
    source: 'Amazon India / iQOO India',
  },
  {
    id: 'iqoo-z9x-5g-8-128',
    modelId: 'iqoo-z9x-5g',
    ram: '8GB',
    storage: '128GB',
    price: 15499,
    mrp: 15999,
    colors: ['Tornado Green', 'Storm Grey'],
    status: 'active',
    verified: true,
    source: 'Amazon India / iQOO India',
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    modelId: 'iqoo-13-5g',
    modelName: 'iQOO 13 5G',
    brand: 'iQOO',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-iqoo-13.jpg',
        angle: 'front',
        source: 'iQOO Official (GSMArena CDN)',
        sourceUrl: 'https://www.iqoo.com/in/products/iqoo13',
        verified: true,
        alt: 'iQOO 13 5G front 2K AMOLED display',
      },
    ],
  },
  {
    modelId: 'iqoo-12-5g',
    modelName: 'iQOO 12 5G',
    brand: 'iQOO',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-iqoo12.jpg',
        angle: 'front',
        source: 'iQOO Official (GSMArena CDN)',
        sourceUrl: 'https://www.iqoo.com/in/products/iqoo12',
        verified: true,
        alt: 'iQOO 12 5G front display view',
      },
    ],
  },
  {
    modelId: 'iqoo-11-5g',
    modelName: 'iQOO 11 5G',
    brand: 'iQOO',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-iqoo11.jpg',
        angle: 'front',
        source: 'iQOO Official (GSMArena CDN)',
        sourceUrl: 'https://www.iqoo.com/in/products/iqoo11',
        verified: true,
        alt: 'iQOO 11 5G front 2K E6 display',
      },
    ],
  },
  {
    modelId: 'iqoo-neo-9-pro-5g',
    modelName: 'iQOO Neo 9 Pro 5G',
    brand: 'iQOO',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-neo9-pro.jpg',
        angle: 'front',
        source: 'iQOO Official (GSMArena CDN)',
        sourceUrl: 'https://www.iqoo.com/in/products/neo9pro',
        verified: true,
        alt: 'iQOO Neo 9 Pro 5G front display view',
      },
    ],
  },
  {
    modelId: 'iqoo-neo-7-pro-5g',
    modelName: 'iQOO Neo 7 Pro 5G',
    brand: 'iQOO',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/iqoo-neo-7-pro-1.jpg',
        angle: 'front',
        source: 'iQOO Official (GSMArena CDN)',
        sourceUrl: 'https://www.iqoo.com/in/products/neo7pro',
        verified: true,
        alt: 'iQOO Neo 7 Pro 5G front display view',
      },
    ],
  },
  {
    modelId: 'iqoo-neo-7-5g',
    modelName: 'iQOO Neo 7 5G',
    brand: 'iQOO',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-iqoo-neo7.jpg',
        angle: 'front',
        source: 'iQOO Official (GSMArena CDN)',
        sourceUrl: 'https://www.iqoo.com/in/products/neo7',
        verified: true,
        alt: 'iQOO Neo 7 5G front display view',
      },
    ],
  },
  {
    modelId: 'iqoo-z9s-pro-5g',
    modelName: 'iQOO Z9s Pro 5G',
    brand: 'iQOO',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-iqoo-z9s-pro.jpg',
        angle: 'front',
        source: 'iQOO Official (GSMArena CDN)',
        sourceUrl: 'https://www.iqoo.com/in/products/z9spro',
        verified: true,
        alt: 'iQOO Z9s Pro 5G front curved display view',
      },
    ],
  },
  {
    modelId: 'iqoo-z9s-5g',
    modelName: 'iQOO Z9s 5G',
    brand: 'iQOO',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-iqoo-z9s.jpg',
        angle: 'front',
        source: 'iQOO Official (GSMArena CDN)',
        sourceUrl: 'https://www.iqoo.com/in/products/z9s',
        verified: true,
        alt: 'iQOO Z9s 5G front curved display view',
      },
    ],
  },
  {
    modelId: 'iqoo-z9-5g',
    modelName: 'iQOO Z9 5G',
    brand: 'iQOO',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-iqoo-z9.jpg',
        angle: 'front',
        source: 'iQOO Official (GSMArena CDN)',
        sourceUrl: 'https://www.iqoo.com/in/products/z9',
        verified: true,
        alt: 'iQOO Z9 5G front display view',
      },
    ],
  },
  {
    modelId: 'iqoo-z9x-5g',
    modelName: 'iQOO Z9x 5G',
    brand: 'iQOO',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-iqoo-z9x.jpg',
        angle: 'front',
        source: 'iQOO Official (GSMArena CDN)',
        sourceUrl: 'https://www.iqoo.com/in/products/z9x',
        verified: true,
        alt: 'iQOO Z9x 5G front display view',
      },
    ],
  },
];

export const iqooBundle: MobileBrandBundle = {
  brand: 'iQOO',
  models,
  variants,
  images,
};
