import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  // ── ITEL COLOR PRO ──
  {
    id: 'itel-color-pro-5g',
    slug: 'itel-color-pro-5g',
    brand: 'Itel',
    modelName: 'Itel Color Pro 5G',
    generation: 'Color Pro',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 9999,
      maximumPrice: 9999,
      launchPrice: 9999,
      currentPrice: 9999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Itel Mobile India / Amazon India',
    },
    display: {
      displaySize: 6.6,
      displayType: 'HD+ IPS LCD with 90Hz Refresh Rate',
      resolution: '1612 x 720 pixels',
      refreshRate: 90,
      peakBrightness: 500,
      hdr: 'None',
      protection: 'Panda Glass',
      screenToBodyRatio: '84.6%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6080 5G (6nm)',
      cpu: 'Octa-core (2x2.4 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['6GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 420000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP AI Dual Rear)',
      mainCamera: '50 MP, f/1.8, PDAF',
      ultrawideCamera: 'None',
      telephotoCamera: 'None (AI auxiliary lens)',
      frontCamera: '8 MP with front flash',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 18,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.1',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM with dedicated microSD',
    },
    physical: {
      dimensions: '164.0 x 75.8 x 8.4 mm',
      weight: 190,
      materials: 'IVCO colour-changing back cover technology (changes color under sunlight)',
      waterResistance: 'Splash resistant',
      colors: ['River Blue', 'Lavender Fantasy'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'itel OS 13',
      launchOS: 'Android 13 (Go edition)',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Single loudspeaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.itel-india.com/product/color-pro-5g/',
      productPage: 'https://www.amazon.in/dp/B0D9W1WJ6S',
      specSheetUrl: 'https://www.itel-india.com/product/color-pro-5g/',
      verifiedDate: '2024-07',
    },
  },

  // ── ITEL P SERIES (Power & 5G) ──
  {
    id: 'itel-p55-5g',
    slug: 'itel-p55-5g',
    brand: 'Itel',
    modelName: 'Itel P55 5G',
    generation: 'P55',
    status: 'active',
    launchDate: '2023-09',
    pricing: {
      startingPrice: 8999,
      maximumPrice: 9999,
      launchPrice: 9999,
      currentPrice: 8999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Itel Mobile India / Amazon India',
    },
    display: {
      displaySize: 6.6,
      displayType: 'HD+ IPS LCD with 90Hz Refresh Rate',
      resolution: '1600 x 720 pixels',
      refreshRate: 90,
      peakBrightness: 480,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '84.0%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6080 5G (6nm)',
      cpu: 'Octa-core (2x2.4 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['4GB', '6GB'],
      storageOptions: ['64GB', '128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 410000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP AI Dual Rear)',
      mainCamera: '50 MP, f/1.8, PDAF',
      ultrawideCamera: 'None',
      telephotoCamera: 'None (secondary AI lens)',
      frontCamera: '8 MP',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 18,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.1',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM with dedicated microSD',
    },
    physical: {
      dimensions: '164.0 x 75.1 x 8.4 mm',
      weight: 198,
      materials: 'Glossy textured plastic back',
      waterResistance: 'Splash resistant',
      colors: ['Galaxy Blue', 'Mint Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'itel OS 13',
      launchOS: 'Android 13',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Single loudspeaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.itel-india.com/product/p55-5g/',
      productPage: 'https://www.amazon.in/dp/B0CHZ49H7H',
      specSheetUrl: 'https://www.itel-india.com/product/p55-5g/',
      verifiedDate: '2023-09',
    },
  },

  // ── ITEL S SERIES (Camera Focused) ──
  {
    id: 'itel-s24',
    slug: 'itel-s24',
    brand: 'Itel',
    modelName: 'Itel S24',
    generation: 'S24',
    status: 'active',
    launchDate: '2024-04',
    pricing: {
      startingPrice: 8499,
      maximumPrice: 8499,
      launchPrice: 8499,
      currentPrice: 8499,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Itel Mobile India / Amazon India',
    },
    display: {
      displaySize: 6.6,
      displayType: 'HD+ IPS LCD with 90Hz Refresh Rate, Punch Hole',
      resolution: '1612 x 720 pixels',
      refreshRate: 90,
      peakBrightness: 480,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '84.4%',
    },
    performance: {
      chipset: 'MediaTek Helio G91 (12nm)',
      cpu: 'Octa-core (2x2.0 GHz Cortex-A75 & 6x1.8 GHz Cortex-A55)',
      gpu: 'Mali-G52 MC2',
      ramOptions: ['8GB'],
      storageOptions: ['128GB'],
      storageType: 'eMMC 5.1',
      antutuScore: 275000,
    },
    cameras: {
      rearCameraSetup: 'Dual (108MP Ultra-Clear + AI Lens)',
      mainCamera: '108 MP Samsung ISOCELL HM6, f/1.6, 3x in-sensor zoom, PDAF',
      ultrawideCamera: 'None',
      telephotoCamera: 'None',
      frontCamera: '8 MP with dual flash',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 18,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: false,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.0',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM with dedicated microSD',
    },
    physical: {
      dimensions: '163.5 x 75.5 x 8.3 mm',
      weight: 192,
      materials: 'Color changing photochromic rear cover (Coastline Blue changes under UV)',
      waterResistance: 'Splash resistant',
      colors: ['Coastline Blue', 'Starry Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'itel OS 13.5 with Dynamic Bar',
      launchOS: 'Android 13',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with DTS Audio',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.itel-india.com/product/s24/',
      productPage: 'https://www.amazon.in/dp/B0D1K75H8S',
      specSheetUrl: 'https://www.itel-india.com/product/s24/',
      verifiedDate: '2024-04',
    },
  },

  // ── ITEL A SERIES (Budget Entry) ──
  {
    id: 'itel-a70',
    slug: 'itel-a70',
    brand: 'Itel',
    modelName: 'Itel A70',
    generation: 'A70',
    status: 'active',
    launchDate: '2024-01',
    pricing: {
      startingPrice: 5999,
      maximumPrice: 6799,
      launchPrice: 6299,
      currentPrice: 5999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Itel Mobile India / Amazon India',
    },
    display: {
      displaySize: 6.6,
      displayType: 'HD+ IPS LCD with Dynamic Bar Notch',
      resolution: '1612 x 720 pixels',
      refreshRate: 60,
      peakBrightness: 500,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '84.6%',
    },
    performance: {
      chipset: 'Unisoc T603 (12nm)',
      cpu: 'Octa-core 1.8 GHz Cortex-A55',
      gpu: 'PowerVR GE8322',
      ramOptions: ['3GB', '4GB'],
      storageOptions: ['64GB', '128GB'],
      storageType: 'eMMC 5.1',
      antutuScore: 195000,
    },
    cameras: {
      rearCameraSetup: 'Dual (13MP HDR + AI Lens)',
      mainCamera: '13 MP, f/1.8, dual LED flash',
      ultrawideCamera: 'None',
      telephotoCamera: 'None',
      frontCamera: '8 MP with front flash',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 10,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: false,
      has4G: true,
      wifi: 'Wi-Fi 4 (b/g/n)',
      bluetooth: 'Bluetooth 5.0',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM with dedicated microSD up to 2TB',
    },
    physical: {
      dimensions: '164.0 x 75.6 x 8.6 mm',
      weight: 187,
      materials: 'Matte composite curved back',
      waterResistance: 'Splash resistant',
      colors: ['Brilliant Gold', 'Stylish Black', 'Field Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'itel OS 13 (Go edition)',
      launchOS: 'Android 13 Go',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.itel-india.com/product/a70/',
      productPage: 'https://www.amazon.in/dp/B0CQ4K912M',
      specSheetUrl: 'https://www.itel-india.com/product/a70/',
      verifiedDate: '2024-01',
    },
  },
];

const variants: MobileVariant[] = [
  // Itel Color Pro 5G
  {
    id: 'itel-color-pro-5g-6gb-128gb',
    modelId: 'itel-color-pro-5g',
    name: 'Itel Color Pro 5G (6GB RAM, 128GB)',
    ram: '6GB',
    storage: '128GB',
    color: 'River Blue',
    price: 9999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Itel P55 5G
  {
    id: 'itel-p55-5g-4gb-64gb',
    modelId: 'itel-p55-5g',
    name: 'Itel P55 5G (4GB RAM, 64GB)',
    ram: '4GB',
    storage: '64GB',
    color: 'Galaxy Blue',
    price: 8999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  {
    id: 'itel-p55-5g-6gb-128gb',
    modelId: 'itel-p55-5g',
    name: 'Itel P55 5G (6GB RAM, 128GB)',
    ram: '6GB',
    storage: '128GB',
    color: 'Mint Green',
    price: 9999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Itel S24
  {
    id: 'itel-s24-8gb-128gb',
    modelId: 'itel-s24',
    name: 'Itel S24 (8GB RAM, 128GB)',
    ram: '8GB',
    storage: '128GB',
    color: 'Starry Black',
    price: 8499,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Itel A70
  {
    id: 'itel-a70-3gb-64gb',
    modelId: 'itel-a70',
    name: 'Itel A70 (3GB RAM, 64GB)',
    ram: '3GB',
    storage: '64GB',
    color: 'Brilliant Gold',
    price: 5999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  {
    id: 'itel-a70-4gb-128gb',
    modelId: 'itel-a70',
    name: 'Itel A70 (4GB RAM, 128GB)',
    ram: '4GB',
    storage: '128GB',
    color: 'Field Green',
    price: 6799,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    modelId: 'itel-color-pro-5g',
    modelName: 'Itel Color Pro 5G',
    brand: 'Itel',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/itel/itel-color-pro-5g-1.jpg',
        angle: 'front',
        source: 'Itel Official (GSMArena CDN)',
        sourceUrl: 'https://www.itel-india.com/product/color-pro-5g/',
        verified: true,
        alt: 'Itel Color Pro 5G front view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/itel/itel-color-pro-5g-2.jpg',
        angle: 'back',
        source: 'Itel Official (GSMArena CDN)',
        sourceUrl: 'https://www.itel-india.com/product/color-pro-5g/',
        verified: true,
        alt: 'Itel Color Pro 5G color-changing IVCO technology rear view',
      },
    ],
  },
  {
    modelId: 'itel-p55-5g',
    modelName: 'Itel P55 5G',
    brand: 'Itel',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/itel-p55.jpg',
        angle: 'front',
        source: 'Itel Official (GSMArena CDN)',
        sourceUrl: 'https://www.itel-india.com/product/p55-5g/',
        verified: true,
        alt: 'Itel P55 5G front display view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/itel/itel-p55-1.jpg',
        angle: 'back',
        source: 'Itel Official (GSMArena CDN)',
        sourceUrl: 'https://www.itel-india.com/product/p55-5g/',
        verified: true,
        alt: 'Itel P55 5G rear view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/itel/itel-p55-2.jpg',
        angle: 'side',
        source: 'Itel Official (GSMArena CDN)',
        sourceUrl: 'https://www.itel-india.com/product/p55-5g/',
        verified: true,
        alt: 'Itel P55 5G profile',
      },
    ],
  },
  {
    modelId: 'itel-s24',
    modelName: 'Itel S24',
    brand: 'Itel',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/itel/itel-s24-1.jpg',
        angle: 'front',
        source: 'Itel Official (GSMArena CDN)',
        sourceUrl: 'https://www.itel-india.com/product/s24/',
        verified: true,
        alt: 'Itel S24 front display view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/itel/itel-s24-2.jpg',
        angle: 'back',
        source: 'Itel Official (GSMArena CDN)',
        sourceUrl: 'https://www.itel-india.com/product/s24/',
        verified: true,
        alt: 'Itel S24 108MP circular camera rear view',
      },
    ],
  },
  {
    modelId: 'itel-a70',
    modelName: 'Itel A70',
    brand: 'Itel',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/itel/itel-a70-1.jpg',
        angle: 'front',
        source: 'Itel Official (GSMArena CDN)',
        sourceUrl: 'https://www.itel-india.com/product/a70/',
        verified: true,
        alt: 'Itel A70 front display view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/itel/itel-a70-2.jpg',
        angle: 'back',
        source: 'Itel Official (GSMArena CDN)',
        sourceUrl: 'https://www.itel-india.com/product/a70/',
        verified: true,
        alt: 'Itel A70 rear view',
      },
    ],
  },
];

export const itelBundle: MobileBrandBundle = {
  brand: 'Itel',
  models,
  variants,
  images,
};
