import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  // ── AGNI SERIES (Flagship Indigenous Performance) ──
  {
    id: 'lava-agni-3-5g',
    slug: 'lava-agni-3-5g',
    brand: 'Lava',
    modelName: 'Lava Agni 3 5G',
    generation: 'Agni 3',
    status: 'active',
    launchDate: '2024-10',
    pricing: {
      startingPrice: 20999,
      maximumPrice: 24999,
      launchPrice: 20999,
      currentPrice: 20999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Lava International Official Store',
    },
    display: {
      displaySize: 6.78,
      displayType: '1.5K 120Hz 3D Curved AMOLED with 1.74" Secondary Rear AMOLED',
      resolution: '2652 x 1200 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1200,
      hdr: 'HDR10+',
      protection: 'Double reinforced Schott glass',
      screenToBodyRatio: '92.5%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7300X (4nm dual-screen chipset)',
      cpu: 'Octa-core (4x2.5 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G615 MC2',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 680000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP Sony OIS + 8MP 3x Telephoto OIS + 8MP Ultrawide) with InstaScreen rear viewfinder',
      mainCamera: '50 MP Sony IMX766, f/1.88, 1/1.56", OIS',
      ultrawideCamera: '8 MP, f/2.2, 119˚',
      telephotoCamera: '8 MP, 3x optical telephoto with OIS',
      frontCamera: '16 MP Samsung, f/2.0',
      videoRecording: '4K@30fps, 1080p@60fps (Rear selfie enabled)',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 66,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.4',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '163.7 x 75.53 x 8.8 mm',
      weight: 212,
      materials: 'Action Key customizable button, secondary rear AMOLED display, glass back',
      waterResistance: 'IP64 dust and water splash resistance',
      colors: ['Heather Glass', 'Pristine Glass'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Clean Android (Zero ads, zero bloatware)',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers tuned by Dolby Atmos',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'In-display optical',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.lavamobiles.com/smartphones/agni-3',
      productPage: 'https://www.amazon.in/dp/B0DJ227RPS',
      specSheetUrl: 'https://www.lavamobiles.com/smartphones/agni-3',
      verifiedDate: '2024-10',
    },
  },
  {
    id: 'lava-agni-5g',
    slug: 'lava-agni-5g',
    brand: 'Lava',
    modelName: 'Lava Agni 5G',
    generation: 'Agni',
    status: 'discontinued',
    launchDate: '2021-11',
    pricing: {
      startingPrice: 17999,
      maximumPrice: 19999,
      launchPrice: 19999,
      currentPrice: 17999,
      currency: 'INR',
      priceEffectiveDate: '2022-12',
      source: 'Lava International Archive',
    },
    display: {
      displaySize: 6.78,
      displayType: '90Hz FHD+ IPS LCD',
      resolution: '2460 x 1080 pixels',
      refreshRate: 90,
      peakBrightness: 500,
      hdr: 'None',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '84.8%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 810 (6nm)',
      cpu: 'Octa-core (2x2.4 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 385000,
    },
    cameras: {
      rearCameraSetup: 'Quad (64MP + 5MP Ultrawide + 2MP Macro + 2MP Depth)',
      mainCamera: '64 MP, f/1.79, PDAF',
      ultrawideCamera: '5 MP, f/2.2',
      telephotoCamera: 'None',
      frontCamera: '16 MP, f/2.0',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 30,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5 (ac)',
      bluetooth: 'Bluetooth 5.1',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '168.8 x 76.8 x 9.1 mm',
      weight: 204,
      materials: 'Plastic frame, Fiery Blue glossy back',
      waterResistance: 'None',
      colors: ['Fiery Blue'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Clean Stock Android',
      launchOS: 'Android 11',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Single bottom speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.lavamobiles.com/smartphones/agni-5g',
      productPage: 'https://www.amazon.in/dp/B09LPZ5J7K',
      specSheetUrl: 'https://www.lavamobiles.com/smartphones/agni-5g',
      verifiedDate: '2021-11',
    },
  },

  // ── BLAZE SERIES (Curved & Mass 5G) ──
  {
    id: 'lava-blaze-curve-5g',
    slug: 'lava-blaze-curve-5g',
    brand: 'Lava',
    modelName: 'Lava Blaze Curve 5G',
    generation: 'Blaze Curve',
    status: 'active',
    launchDate: '2024-03',
    pricing: {
      startingPrice: 17999,
      maximumPrice: 18999,
      launchPrice: 17999,
      currentPrice: 17999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Lava International Official Store',
    },
    display: {
      displaySize: 6.67,
      displayType: '120Hz 3D Curved AMOLED, 800 nits peak',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 800,
      hdr: 'HDR10+',
      protection: 'Double reinforced Schott glass',
      screenToBodyRatio: '93.2%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7050 (6nm)',
      cpu: 'Octa-core (2x2.6 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G68 MC4',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 570000,
    },
    cameras: {
      rearCameraSetup: 'Triple (64MP Sony + 8MP Ultrawide + 2MP Macro)',
      mainCamera: '64 MP Sony, f/1.89, EIS',
      ultrawideCamera: '8 MP, f/2.2, 120˚',
      telephotoCamera: 'None',
      frontCamera: '32 MP, f/2.2',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 33,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.8 x 73.8 x 8.8 mm',
      weight: 189,
      materials: '3D Curved Glass Back with AG Matte finish, metallic frame',
      waterResistance: 'None',
      colors: ['Iron Glass', 'Viridian Glass'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Clean Android (Ad-free experience)',
      launchOS: 'Android 13 (Upgraded to 14)',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers tuned by Dolby Atmos',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'In-display optical',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.lavamobiles.com/smartphones/blaze-curve-5g',
      productPage: 'https://www.amazon.in/dp/B0CX25LBRS',
      specSheetUrl: 'https://www.lavamobiles.com/smartphones/blaze-curve-5g',
      verifiedDate: '2024-03',
    },
  },
  {
    id: 'lava-blaze-x-5g',
    slug: 'lava-blaze-x-5g',
    brand: 'Lava',
    modelName: 'Lava Blaze X 5G',
    generation: 'Blaze X',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 14999,
      maximumPrice: 16999,
      launchPrice: 14999,
      currentPrice: 14999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Lava International Official Store',
    },
    display: {
      displaySize: 6.67,
      displayType: '120Hz 3D Curved AMOLED, 800 nits peak',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 800,
      hdr: 'None',
      protection: 'Double reinforced Schott glass',
      screenToBodyRatio: '93.0%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6300 (6nm)',
      cpu: 'Octa-core (2x2.4 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['4GB', '6GB', '8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 420000,
    },
    cameras: {
      rearCameraSetup: 'Dual (64MP Sony + 2MP Secondary)',
      mainCamera: '64 MP Sony, f/1.8, EIS',
      ultrawideCamera: 'None',
      telephotoCamera: 'None',
      frontCamera: '16 MP, f/2.0',
      videoRecording: '1080p@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 33,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5 (ac)',
      bluetooth: 'Bluetooth 5.2',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.4 x 74.3 x 8.45 mm',
      weight: 183,
      materials: '3D Curved glass-feel composite back, slim curved profile',
      waterResistance: 'None',
      colors: ['Starlight Purple', 'Titanium Grey'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Clean Android (Ad-free)',
      launchOS: 'Android 14',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Single bottom speaker',
      stereo: false,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'In-display optical',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.lavamobiles.com/smartphones/blaze-x-5g',
      productPage: 'https://www.amazon.in/dp/B0D8JZ5365',
      specSheetUrl: 'https://www.lavamobiles.com/smartphones/blaze-x-5g',
      verifiedDate: '2024-07',
    },
  },
  {
    id: 'lava-blaze-5g',
    slug: 'lava-blaze-5g',
    brand: 'Lava',
    modelName: 'Lava Blaze 5G',
    generation: 'Blaze',
    status: 'discontinued',
    launchDate: '2022-11',
    pricing: {
      startingPrice: 9999,
      maximumPrice: 11499,
      launchPrice: 9999,
      currentPrice: 9999,
      currency: 'INR',
      priceEffectiveDate: '2023-11',
      source: 'Lava International Store Archive',
    },
    display: {
      displaySize: 6.5,
      displayType: '90Hz HD+ IPS LCD',
      resolution: '1600 x 720 pixels',
      refreshRate: 90,
      peakBrightness: 450,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '81.9%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 700 5G (7nm)',
      cpu: 'Octa-core (2x2.2 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['4GB', '6GB', '8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 360000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 2MP Macro + VGA)',
      mainCamera: '50 MP, f/1.8, PDAF',
      ultrawideCamera: 'None',
      telephotoCamera: 'None',
      frontCamera: '8 MP, f/2.0',
      videoRecording: '1440p@30fps, 1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 15,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5 (ac)',
      bluetooth: 'Bluetooth 5.1',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '165.3 x 76.4 x 8.9 mm',
      weight: 207,
      materials: 'Premium Glass Back design, India\'s pioneer sub-10k 5G phone',
      waterResistance: 'None',
      colors: ['Glass Blue', 'Glass Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Clean Stock Android',
      launchOS: 'Android 12 (Upgraded to 13)',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Single bottom speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.lavamobiles.com/smartphones/blaze-5g',
      productPage: 'https://www.amazon.in/dp/B0BKT4461T',
      specSheetUrl: 'https://www.lavamobiles.com/smartphones/blaze-5g',
      verifiedDate: '2022-11',
    },
  },
  {
    id: 'lava-blaze-2',
    slug: 'lava-blaze-2',
    brand: 'Lava',
    modelName: 'Lava Blaze 2',
    generation: 'Blaze 2',
    status: 'active',
    launchDate: '2023-04',
    pricing: {
      startingPrice: 8999,
      maximumPrice: 8999,
      launchPrice: 8999,
      currentPrice: 8999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Lava International / Amazon',
    },
    display: {
      displaySize: 6.5,
      displayType: '90Hz HD+ IPS LCD, Punch Hole',
      resolution: '1600 x 720 pixels',
      refreshRate: 90,
      peakBrightness: 450,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '82.0%',
    },
    performance: {
      chipset: 'Unisoc T616 (12nm)',
      cpu: 'Octa-core (2x2.0 GHz Cortex-A75 & 6x1.8 GHz Cortex-A55)',
      gpu: 'Mali-G57 MP1',
      ramOptions: ['6GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 280000,
    },
    cameras: {
      rearCameraSetup: 'Dual (13MP + 2MP AI)',
      mainCamera: '13 MP, f/1.8, LED flash',
      ultrawideCamera: 'None',
      telephotoCamera: 'None',
      frontCamera: '8 MP, f/2.0',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 18,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: false,
      has4G: true,
      wifi: 'Wi-Fi 5 (ac)',
      bluetooth: 'Bluetooth 5.0',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dedicated Dual SIM + microSD',
    },
    physical: {
      dimensions: '165 x 76.1 x 8.6 mm',
      weight: 203,
      materials: 'Premium Glass Back finish, circular camera rings',
      waterResistance: 'None',
      colors: ['Glass Blue', 'Glass Black', 'Glass Orange'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Clean Stock Android',
      launchOS: 'Android 12',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Single bottom speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.lavamobiles.com/smartphones/blaze-2',
      productPage: 'https://www.amazon.in/dp/B0BZCS774Q',
      specSheetUrl: 'https://www.lavamobiles.com/smartphones/blaze-2',
      verifiedDate: '2023-04',
    },
  },

  // ── STORM SERIES (Mid Budget Power) ──
  {
    id: 'lava-storm-5g',
    slug: 'lava-storm-5g',
    brand: 'Lava',
    modelName: 'Lava Storm 5G',
    generation: 'Storm',
    status: 'active',
    launchDate: '2023-12',
    pricing: {
      startingPrice: 11999,
      maximumPrice: 11999,
      launchPrice: 11999,
      currentPrice: 11999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Lava International / Amazon',
    },
    display: {
      displaySize: 6.78,
      displayType: '120Hz FHD+ IPS LCD, 580 nits',
      resolution: '2460 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 580,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '84.8%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6080 (6nm)',
      cpu: 'Octa-core (2x2.4 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 420000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 8MP Ultrawide)',
      mainCamera: '50 MP, f/1.8, PDAF',
      ultrawideCamera: '8 MP, f/2.2, 119˚',
      telephotoCamera: 'None',
      frontCamera: '16 MP, f/2.0',
      videoRecording: '1080p@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 33,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5 (ac)',
      bluetooth: 'Bluetooth 5.1',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dedicated Dual SIM + microSD',
    },
    physical: {
      dimensions: '168.7 x 76.7 x 8.96 mm',
      weight: 214,
      materials: 'Premium Glass Back design, flat edges',
      waterResistance: 'None',
      colors: ['Gale Green', 'Thunder Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Clean Stock Android (Ad-free)',
      launchOS: 'Android 13',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Single bottom speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.lavamobiles.com/smartphones/storm-5g',
      productPage: 'https://www.amazon.in/dp/B0CP28Y4MS',
      specSheetUrl: 'https://www.lavamobiles.com/smartphones/storm-5g',
      verifiedDate: '2023-12',
    },
  },

  // ── YUVA SERIES (Entry-Level Stylish) ──
  {
    id: 'lava-yuva-3-pro',
    slug: 'lava-yuva-3-pro',
    brand: 'Lava',
    modelName: 'Lava Yuva 3 Pro',
    generation: 'Yuva 3',
    status: 'active',
    launchDate: '2023-12',
    pricing: {
      startingPrice: 8999,
      maximumPrice: 8999,
      launchPrice: 8999,
      currentPrice: 8999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Lava International / Amazon',
    },
    display: {
      displaySize: 6.5,
      displayType: '90Hz HD+ IPS LCD, Punch Hole',
      resolution: '1600 x 720 pixels',
      refreshRate: 90,
      peakBrightness: 450,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '82.0%',
    },
    performance: {
      chipset: 'Unisoc T616 (12nm)',
      cpu: 'Octa-core (2x2.0 GHz Cortex-A75 & 6x1.8 GHz Cortex-A55)',
      gpu: 'Mali-G57 MP1',
      ramOptions: ['8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 280000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + AI Lens)',
      mainCamera: '50 MP, f/1.8, LED flash',
      ultrawideCamera: 'None',
      telephotoCamera: 'None',
      frontCamera: '8 MP, f/2.0',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 18,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: false,
      has4G: true,
      wifi: 'Wi-Fi 5 (ac)',
      bluetooth: 'Bluetooth 5.0',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dedicated Dual SIM + microSD',
    },
    physical: {
      dimensions: '164.2 x 76 x 8.45 mm',
      weight: 200,
      materials: 'Premium AG Glass Back finish',
      waterResistance: 'None',
      colors: ['Desert Gold', 'Forest Viridian', 'Meadow Purple'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Clean Stock Android',
      launchOS: 'Android 13',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Single bottom speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.lavamobiles.com/smartphones/yuva-3-pro',
      productPage: 'https://www.amazon.in/dp/B0CP97W743',
      specSheetUrl: 'https://www.lavamobiles.com/smartphones/yuva-3-pro',
      verifiedDate: '2023-12',
    },
  },
];

const variants: MobileVariant[] = [
  // Agni 3 5G
  {
    id: 'lava-agni-3-5g-8-128',
    modelId: 'lava-agni-3-5g',
    name: 'Lava Agni 3 5G (8GB RAM, 128GB without charger)',
    ram: '8GB',
    storage: '128GB',
    color: 'Heather Glass',
    price: 20999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  {
    id: 'lava-agni-3-5g-8-256',
    modelId: 'lava-agni-3-5g',
    name: 'Lava Agni 3 5G (8GB RAM, 256GB with 66W charger)',
    ram: '8GB',
    storage: '256GB',
    color: 'Pristine Glass',
    price: 24999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Agni 5G
  {
    id: 'lava-agni-5g-8-128',
    modelId: 'lava-agni-5g',
    name: 'Lava Agni 5G (8GB RAM, 128GB)',
    ram: '8GB',
    storage: '128GB',
    color: 'Fiery Blue',
    price: 17999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  // Blaze Curve 5G
  {
    id: 'lava-blaze-curve-5g-8-128',
    modelId: 'lava-blaze-curve-5g',
    name: 'Lava Blaze Curve 5G (8GB RAM, 128GB)',
    ram: '8GB',
    storage: '128GB',
    color: 'Iron Glass',
    price: 17999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  {
    id: 'lava-blaze-curve-5g-8-256',
    modelId: 'lava-blaze-curve-5g',
    name: 'Lava Blaze Curve 5G (8GB RAM, 256GB)',
    ram: '8GB',
    storage: '256GB',
    color: 'Viridian Glass',
    price: 18999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Blaze X 5G
  {
    id: 'lava-blaze-x-5g-6-128',
    modelId: 'lava-blaze-x-5g',
    name: 'Lava Blaze X 5G (6GB RAM, 128GB)',
    ram: '6GB',
    storage: '128GB',
    color: 'Starlight Purple',
    price: 14999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  {
    id: 'lava-blaze-x-5g-8-128',
    modelId: 'lava-blaze-x-5g',
    name: 'Lava Blaze X 5G (8GB RAM, 128GB)',
    ram: '8GB',
    storage: '128GB',
    color: 'Titanium Grey',
    price: 16999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Blaze 5G
  {
    id: 'lava-blaze-5g-6-128',
    modelId: 'lava-blaze-5g',
    name: 'Lava Blaze 5G (6GB RAM, 128GB)',
    ram: '6GB',
    storage: '128GB',
    color: 'Glass Blue',
    price: 9999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  // Blaze 2
  {
    id: 'lava-blaze-2-6-128',
    modelId: 'lava-blaze-2',
    name: 'Lava Blaze 2 (6GB RAM, 128GB)',
    ram: '6GB',
    storage: '128GB',
    color: 'Glass Black',
    price: 8999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Storm 5G
  {
    id: 'lava-storm-5g-8-128',
    modelId: 'lava-storm-5g',
    name: 'Lava Storm 5G (8GB RAM, 128GB)',
    ram: '8GB',
    storage: '128GB',
    color: 'Gale Green',
    price: 11999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Yuva 3 Pro
  {
    id: 'lava-yuva-3-pro-8-128',
    modelId: 'lava-yuva-3-pro',
    name: 'Lava Yuva 3 Pro (8GB RAM, 128GB)',
    ram: '8GB',
    storage: '128GB',
    color: 'Desert Gold',
    price: 8999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    modelId: 'lava-agni-3-5g',
    modelName: 'Lava Agni 3 5G',
    brand: 'Lava',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/lava-agni3.jpg',
        angle: 'front',
        source: 'Lava Official (GSMArena CDN)',
        sourceUrl: 'https://www.lavamobiles.com/smartphones/agni-3',
        verified: true,
        alt: 'Lava Agni 3 5G front and rear dual AMOLED display view',
      },
    ],
  },
  {
    modelId: 'lava-agni-5g',
    modelName: 'Lava Agni 5G',
    brand: 'Lava',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/lava-agni-5g.jpg',
        angle: 'front',
        source: 'Lava Official (GSMArena CDN)',
        sourceUrl: 'https://www.lavamobiles.com/smartphones/agni-5g',
        verified: true,
        alt: 'Lava Agni 5G front display view',
      },
    ],
  },
  {
    modelId: 'lava-blaze-curve-5g',
    modelName: 'Lava Blaze Curve 5G',
    brand: 'Lava',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/lava-blaze-curve-5g.jpg',
        angle: 'front',
        source: 'Lava Official (GSMArena CDN)',
        sourceUrl: 'https://www.lavamobiles.com/smartphones/blaze-curve-5g',
        verified: true,
        alt: 'Lava Blaze Curve 5G front 3D curved display',
      },
    ],
  },
  {
    modelId: 'lava-blaze-x-5g',
    modelName: 'Lava Blaze X 5G',
    brand: 'Lava',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/lava-blaze-x.jpg',
        angle: 'front',
        source: 'Lava Official (GSMArena CDN)',
        sourceUrl: 'https://www.lavamobiles.com/smartphones/blaze-x-5g',
        verified: true,
        alt: 'Lava Blaze X 5G front curved display view',
      },
    ],
  },
  {
    modelId: 'lava-blaze-5g',
    modelName: 'Lava Blaze 5G',
    brand: 'Lava',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/lava-blaze-5g.jpg',
        angle: 'front',
        source: 'Lava Official (GSMArena CDN)',
        sourceUrl: 'https://www.lavamobiles.com/smartphones/blaze-5g',
        verified: true,
        alt: 'Lava Blaze 5G front display view',
      },
    ],
  },
  {
    modelId: 'lava-blaze-2',
    modelName: 'Lava Blaze 2',
    brand: 'Lava',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/lava-blaze-2.jpg',
        angle: 'front',
        source: 'Lava Official (GSMArena CDN)',
        sourceUrl: 'https://www.lavamobiles.com/smartphones/blaze-2',
        verified: true,
        alt: 'Lava Blaze 2 front display view',
      },
    ],
  },
  {
    modelId: 'lava-storm-5g',
    modelName: 'Lava Storm 5G',
    brand: 'Lava',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/lava-storm-5g.jpg',
        angle: 'front',
        source: 'Lava Official (GSMArena CDN)',
        sourceUrl: 'https://www.lavamobiles.com/smartphones/storm-5g',
        verified: true,
        alt: 'Lava Storm 5G front display view',
      },
    ],
  },
  {
    modelId: 'lava-yuva-3-pro',
    modelName: 'Lava Yuva 3 Pro',
    brand: 'Lava',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/lava-yuva-3-pro.jpg',
        angle: 'front',
        source: 'Lava Official (GSMArena CDN)',
        sourceUrl: 'https://www.lavamobiles.com/smartphones/yuva-3-pro',
        verified: true,
        alt: 'Lava Yuva 3 Pro front display view',
      },
    ],
  },
];

export const lavaBundle: MobileBrandBundle = {
  brand: 'Lava',
  models,
  variants,
  images,
};
