import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  // ── RAZR SERIES (Foldable Flagships) ──
  {
    id: 'motorola-razr-50-ultra',
    slug: 'motorola-razr-50-ultra',
    brand: 'Motorola',
    modelName: 'Motorola Razr 50 Ultra',
    generation: 'Razr 50',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 89999,
      maximumPrice: 99999,
      launchPrice: 99999,
      currentPrice: 89999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Motorola India Official Store',
    },
    display: {
      displaySize: 6.9,
      displayType: 'Foldable LTPO AMOLED, 165Hz, Dolby Vision, HDR10+, 3000 nits (peak) + 4.0" LTPO AMOLED 165Hz Cover Display',
      resolution: '1080 x 2640 pixels (Main) / 1272 x 1080 pixels (Cover)',
      refreshRate: 165,
      peakBrightness: 3000,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass Victus (Cover)',
      screenToBodyRatio: '85.3%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8s Gen 3 (4nm)',
      cpu: 'Octa-core (1x3.0 GHz Cortex-X4 & 4x2.8 GHz & 3x2.0 GHz)',
      gpu: 'Adreno 735',
      ramOptions: ['12GB'],
      storageOptions: ['512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 1510000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 50MP 2x Telephoto)',
      mainCamera: '50 MP, f/1.7, 1/1.95", PDAF, OIS',
      ultrawideCamera: 'N/A',
      telephotoCamera: '50 MP, f/2.0, 1/1.95", 2x optical zoom, PDAF',
      frontCamera: '32 MP, f/2.4, 4K60 video',
      videoRecording: '4K@60fps, 1080p@120fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4000,
      wiredCharging: 45,
      wirelessCharging: 15,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'eSIM + Nano-SIM',
    },
    physical: {
      dimensions: '171.4 x 74 x 7.1 mm (unfolded) / 88.1 x 74 x 15.3 mm (folded)',
      weight: 189,
      materials: 'Eco leather back, 6000-series aluminum frame, stainless steel hinge',
      waterResistance: 'IPX8 water resistant (submersible up to 1.5m for 30 min)',
      colors: ['Midnight Blue', 'Spring Green', 'Peach Fuzz'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Hello UI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Dolby Atmos and Spatial Audio',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-motorola-razr-50-ultra/p',
      productPage: 'https://www.amazon.in/dp/B0D7MVT8S3',
      specSheetUrl: 'https://www.motorola.in/smartphones-motorola-razr-50-ultra/p',
      verifiedDate: '2024-07',
    },
  },
  {
    id: 'motorola-razr-40-ultra',
    slug: 'motorola-razr-40-ultra',
    brand: 'Motorola',
    modelName: 'Motorola Razr 40 Ultra',
    generation: 'Razr 40',
    status: 'discontinued',
    launchDate: '2023-07',
    pricing: {
      startingPrice: 49999,
      maximumPrice: 89999,
      launchPrice: 89999,
      currentPrice: 49999,
      currency: 'INR',
      priceEffectiveDate: '2024-06',
      source: 'Motorola India Store Archive',
    },
    display: {
      displaySize: 6.9,
      displayType: 'Foldable LTPO AMOLED, 165Hz, HDR10+, 1400 nits + 3.6" AMOLED 144Hz Cover Display',
      resolution: '1080 x 2640 pixels (Main) / 1056 x 1066 pixels (Cover)',
      refreshRate: 165,
      peakBrightness: 1400,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass Victus (Cover)',
      screenToBodyRatio: '85.1%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8+ Gen 1 (4nm)',
      cpu: 'Octa-core (1x3.19 GHz Cortex-X2 & 3x2.75 GHz & 4x1.80 GHz)',
      gpu: 'Adreno 730',
      ramOptions: ['8GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 1250000,
    },
    cameras: {
      rearCameraSetup: 'Dual (12MP Main + 13MP Ultrawide)',
      mainCamera: '12 MP, f/1.5, 1/2.55", 1.4µm, PDAF, OIS',
      ultrawideCamera: '13 MP, f/2.2, 108˚, AF, macro',
      telephotoCamera: 'N/A',
      frontCamera: '32 MP, f/2.4, 4K30 video',
      videoRecording: '4K@60fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 3800,
      wiredCharging: 30,
      wirelessCharging: 5,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'eSIM + Nano-SIM',
    },
    physical: {
      dimensions: '170.8 x 74 x 7 mm (unfolded) / 88.4 x 74 x 15.1 mm (folded)',
      weight: 188,
      materials: 'Glass back (Gorilla Glass Victus) or vegan leather, 7000-series aluminum frame',
      waterResistance: 'IP52 water repellent',
      colors: ['Infinite Black', 'Glacier Blue', 'Viva Magenta'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MyUX',
      launchOS: 'Android 13',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Dolby Atmos',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-motorola-razr-40-ultra/p',
      productPage: 'https://www.amazon.in/dp/B0C8NXMV32',
      specSheetUrl: 'https://www.motorola.in/smartphones-motorola-razr-40-ultra/p',
      verifiedDate: '2023-07',
    },
  },

  // ── EDGE 50 SERIES (Current Premium / Flagships) ──
  {
    id: 'motorola-edge-50-ultra',
    slug: 'motorola-edge-50-ultra',
    brand: 'Motorola',
    modelName: 'Motorola Edge 50 Ultra',
    generation: 'Edge 50',
    status: 'active',
    launchDate: '2024-06',
    pricing: {
      startingPrice: 54999,
      maximumPrice: 54999,
      launchPrice: 59999,
      currentPrice: 54999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Motorola India Official Store',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Super HD 1.5K 144Hz pOLED',
      resolution: '2712 x 1220 pixels',
      refreshRate: 144,
      peakBrightness: 2500,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass Victus',
      screenToBodyRatio: '92.1%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8s Gen 3 (4nm)',
      cpu: 'Octa-core (1x3.0 GHz Cortex-X4 & 4x2.8 GHz & 3x2.0 GHz)',
      gpu: 'Adreno 735',
      ramOptions: ['12GB'],
      storageOptions: ['512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 1540000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 64MP) Pantone Validated',
      mainCamera: '50 MP, f/1.6, 1/1.3", omni-directional PDAF, Laser AF, OIS',
      ultrawideCamera: '50 MP, f/2.0, 122˚, macro',
      telephotoCamera: '64 MP periscope, f/2.4, 3x optical, 100x hybrid, OIS',
      frontCamera: '50 MP, f/1.9, autofocus, 4K60',
      videoRecording: '4K@60fps, 1080p@960fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4500,
      wiredCharging: 125,
      wirelessCharging: 50,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 3.1 Gen 2, DisplayPort 1.4',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.09 x 72.38 x 8.59 mm',
      weight: 197,
      materials: 'Real wood (Nordic Wood) / Vegan leather, sandblasted aluminum frame',
      waterResistance: 'IP68 water and dust resistant',
      colors: ['Nordic Wood', 'Peach Fuzz', 'Forest Grey'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Hello UI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers tuned by Dolby Atmos',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-motorola-edge-50-ultra/p',
      productPage: 'https://www.flipkart.com/motorola-edge-50-ultra-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-motorola-edge-50-ultra/p',
      verifiedDate: '2024-06',
    },
  },
  {
    id: 'motorola-edge-50-pro',
    slug: 'motorola-edge-50-pro',
    brand: 'Motorola',
    modelName: 'Motorola Edge 50 Pro',
    generation: 'Edge 50',
    status: 'active',
    launchDate: '2024-04',
    pricing: {
      startingPrice: 29999,
      maximumPrice: 33999,
      launchPrice: 31999,
      currentPrice: 29999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Motorola India Official Store',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Super HD 1.5K 144Hz curved pOLED',
      resolution: '2712 x 1220 pixels',
      refreshRate: 144,
      peakBrightness: 2000,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass',
      screenToBodyRatio: '93%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7 Gen 3 (4nm)',
      cpu: 'Octa-core (1x2.63 GHz Cortex-A715 & 4x2.4 GHz & 3x1.8 GHz)',
      gpu: 'Adreno 720',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 840000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 13MP + 10MP)',
      mainCamera: '50 MP, f/1.4, 1/1.55", omni-directional PDAF, Laser AF, OIS',
      ultrawideCamera: '13 MP, f/2.2, 120˚, autofocus, macro',
      telephotoCamera: '10 MP, f/2.0, 3x optical zoom, OIS, PDAF',
      frontCamera: '50 MP, f/1.9, quad pixel, AF, 4K video',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4500,
      wiredCharging: 125,
      wirelessCharging: 50,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 3.1 Gen 2, DisplayPort 1.4',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.23 x 72.4 x 8.19 mm',
      weight: 186,
      materials: 'Vegan leather / handcrafted acetate pearl finish, aluminum frame',
      waterResistance: 'IP68 water and dust resistant',
      colors: ['Black Beauty', 'Luxe Lavender', 'Moonlight Pearl'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Hello UI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Dolby Atmos tuning',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-motorola-edge-50-pro/p',
      productPage: 'https://www.flipkart.com/motorola-edge-50-pro-5g-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-motorola-edge-50-pro/p',
      verifiedDate: '2024-04',
    },
  },
  {
    id: 'motorola-edge-50-fusion',
    slug: 'motorola-edge-50-fusion',
    brand: 'Motorola',
    modelName: 'Motorola Edge 50 Fusion',
    generation: 'Edge 50',
    status: 'active',
    launchDate: '2024-05',
    pricing: {
      startingPrice: 20999,
      maximumPrice: 22999,
      launchPrice: 22999,
      currentPrice: 20999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Motorola India Official Store',
    },
    display: {
      displaySize: 6.67,
      displayType: 'Full HD+ 144Hz 3D curved pOLED',
      resolution: '2400 x 1080 pixels',
      refreshRate: 144,
      peakBrightness: 1600,
      hdr: 'HDR10',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '92%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7s Gen 2 (4nm)',
      cpu: 'Octa-core (4x2.40 GHz Cortex-A78 & 4x1.95 GHz Cortex-A55)',
      gpu: 'Adreno 710',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 610000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP Sony LYT-700C + 13MP Ultrawide)',
      mainCamera: '50 MP Sony LYTIA LYT-700C, f/1.88, 1/1.56", all-pixel focus, OIS',
      ultrawideCamera: '13 MP, f/2.2, 120˚, macro vision',
      telephotoCamera: 'N/A',
      frontCamera: '32 MP, f/2.45, 4K video recording',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 68,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.9 x 73.1 x 7.9 mm',
      weight: 174.9,
      materials: 'Vegan leather / PMMA glass finish, curved polycarbonate frame',
      waterResistance: 'IP68 water and dust resistant',
      colors: ['Marshmallow Blue', 'Hot Pink', 'Forest Blue'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Hello UI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Dolby Atmos tuning',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-motorola-edge-50-fusion/p',
      productPage: 'https://www.flipkart.com/motorola-edge-50-fusion-5g-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-motorola-edge-50-fusion/p',
      verifiedDate: '2024-05',
    },
  },
  {
    id: 'motorola-edge-50-neo',
    slug: 'motorola-edge-50-neo',
    brand: 'Motorola',
    modelName: 'Motorola Edge 50 Neo',
    generation: 'Edge 50',
    status: 'active',
    launchDate: '2024-09',
    pricing: {
      startingPrice: 23999,
      maximumPrice: 23999,
      launchPrice: 23999,
      currentPrice: 23999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Motorola India Official Store',
    },
    display: {
      displaySize: 6.4,
      displayType: 'Super HD 1.5K 120Hz flat LTPO pOLED',
      resolution: '2670 x 1220 pixels',
      refreshRate: 120,
      peakBrightness: 3000,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '90.7%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7300 (4nm)',
      cpu: 'Octa-core (4x2.5 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G615 MC2',
      ramOptions: ['8GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 670000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP Sony LYT-700C + 13MP Ultrawide + 10MP 3x Telephoto)',
      mainCamera: '50 MP Sony LYTIA 700C, f/1.8, 1/1.56", OIS',
      ultrawideCamera: '13 MP, f/2.2, 120˚, macro',
      telephotoCamera: '10 MP, f/2.0, 3x optical zoom, OIS',
      frontCamera: '32 MP, f/2.4, 4K30',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4310,
      wiredCharging: 68,
      wirelessCharging: 15,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '154.1 x 71.2 x 8.1 mm',
      weight: 171,
      materials: 'Vegan leather rear, military grade MIL-STD-810H durability',
      waterResistance: 'IP68 water and dust resistant (submersible 1.5m for 30m)',
      colors: ['Poinciana', 'Lattè', 'Grisaille', 'Nautical Blue'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Hello UI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 5,
      securityUpdatePolicy: '5 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Dolby Atmos tuning',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-motorola-edge-50-neo/p',
      productPage: 'https://www.flipkart.com/motorola-edge-50-neo-5g-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-motorola-edge-50-neo/p',
      verifiedDate: '2024-09',
    },
  },

  // ── EDGE 40 SERIES (Bestseller Mid-Range) ──
  {
    id: 'motorola-edge-40',
    slug: 'motorola-edge-40',
    brand: 'Motorola',
    modelName: 'Motorola Edge 40',
    generation: 'Edge 40',
    status: 'discontinued',
    launchDate: '2023-05',
    pricing: {
      startingPrice: 26999,
      maximumPrice: 29999,
      launchPrice: 29999,
      currentPrice: 26999,
      currency: 'INR',
      priceEffectiveDate: '2024-05',
      source: 'Motorola India Store Archive',
    },
    display: {
      displaySize: 6.55,
      displayType: 'FHD+ 144Hz 3D curved pOLED, HDR10+, 1200 nits',
      resolution: '2400 x 1080 pixels',
      refreshRate: 144,
      peakBrightness: 1200,
      hdr: 'HDR10+',
      protection: 'NEG Glass',
      screenToBodyRatio: '90.8%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 8020 (6nm)',
      cpu: 'Octa-core (4x2.6 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G77 MC9',
      ramOptions: ['8GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 760000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 13MP Ultrawide)',
      mainCamera: '50 MP, f/1.4, 1/1.55", 1.0µm, multi-directional PDAF, OIS',
      ultrawideCamera: '13 MP, f/2.2, 120˚, AF, macro',
      telephotoCamera: 'N/A',
      frontCamera: '32 MP, f/2.4, 4K30 video',
      videoRecording: '4K@30fps, 1080p@120fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4400,
      wiredCharging: 68,
      wirelessCharging: 15,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '158.4 x 72 x 7.6 mm',
      weight: 167,
      materials: 'Vegan leather rear, sandblasted aluminum frame',
      waterResistance: 'IP68 water and dust resistant',
      colors: ['Eclipse Black', 'Nebula Green', 'Viva Magenta'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MyUX',
      launchOS: 'Android 13',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Dolby Atmos tuning',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-motorola-edge-40/p',
      productPage: 'https://www.flipkart.com/motorola-edge-40-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-motorola-edge-40/p',
      verifiedDate: '2023-05',
    },
  },
  {
    id: 'motorola-edge-40-neo',
    slug: 'motorola-edge-40-neo',
    brand: 'Motorola',
    modelName: 'Motorola Edge 40 Neo',
    generation: 'Edge 40',
    status: 'discontinued',
    launchDate: '2023-09',
    pricing: {
      startingPrice: 20999,
      maximumPrice: 22999,
      launchPrice: 23999,
      currentPrice: 20999,
      currency: 'INR',
      priceEffectiveDate: '2024-05',
      source: 'Motorola India Store Archive',
    },
    display: {
      displaySize: 6.55,
      displayType: 'FHD+ 144Hz 10-bit 3D curved pOLED, HDR10+, 1300 nits',
      resolution: '2400 x 1080 pixels',
      refreshRate: 144,
      peakBrightness: 1300,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '90.1%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7030 (6nm)',
      cpu: 'Octa-core (2x2.5 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G610 MC3',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'uMCP',
      antutuScore: 520000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 13MP Ultrawide)',
      mainCamera: '50 MP, f/1.8, 1/1.5", 1.0µm, omni-directional PDAF, OIS',
      ultrawideCamera: '13 MP, f/2.2, 120˚, AF, macro',
      telephotoCamera: 'N/A',
      frontCamera: '32 MP, f/2.4, 4K30 video',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 68,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '159.6 x 72 x 7.9 mm',
      weight: 172,
      materials: 'Vegan leather rear (Pantone curated), curved polycarbonate frame',
      waterResistance: 'IP68 water and dust resistant',
      colors: ['Black Onyx', 'Soothing Sea', 'Caneel Bay'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MyUX',
      launchOS: 'Android 13',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Dolby Atmos tuning',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-motorola-edge-40-neo/p',
      productPage: 'https://www.flipkart.com/motorola-edge-40-neo-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-motorola-edge-40-neo/p',
      verifiedDate: '2023-09',
    },
  },

  // ── EDGE 30 SERIES (Historical Flagships) ──
  {
    id: 'motorola-edge-30-ultra',
    slug: 'motorola-edge-30-ultra',
    brand: 'Motorola',
    modelName: 'Motorola Edge 30 Ultra',
    generation: 'Edge 30',
    status: 'discontinued',
    launchDate: '2022-09',
    pricing: {
      startingPrice: 44999,
      maximumPrice: 59999,
      launchPrice: 59999,
      currentPrice: 44999,
      currency: 'INR',
      priceEffectiveDate: '2023-12',
      source: 'Motorola India Store Archive',
    },
    display: {
      displaySize: 6.67,
      displayType: 'FHD+ 144Hz 10-bit curved OLED, HDR10+, 1250 nits',
      resolution: '2400 x 1080 pixels',
      refreshRate: 144,
      peakBrightness: 1250,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '90.3%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8+ Gen 1 (4nm)',
      cpu: 'Octa-core (1x3.19 GHz Cortex-X2 & 3x2.75 GHz & 4x1.80 GHz)',
      gpu: 'Adreno 730',
      ramOptions: ['8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 3.1',
      antutuScore: 1080000,
    },
    cameras: {
      rearCameraSetup: 'Triple (200MP + 50MP Ultrawide + 12MP 2x Telephoto)',
      mainCamera: '200 MP, f/1.9, 1/1.22", 0.64µm, PDAF, OIS',
      ultrawideCamera: '50 MP, f/2.2, 114˚, AF, macro',
      telephotoCamera: '12 MP, f/1.6, 2x optical zoom, PDAF',
      frontCamera: '60 MP, f/2.2, 4K30 video',
      videoRecording: '8K@30fps, 4K@60fps, 1080p@120fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4610,
      wiredCharging: 125,
      wirelessCharging: 50,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.2',
      nfc: true,
      usb: 'USB Type-C 3.1, DisplayPort 1.4',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.8 x 73.5 x 8.4 mm',
      weight: 198.5,
      materials: 'Corning Gorilla Glass 5 front and back, aluminum frame',
      waterResistance: 'IP52 splash resistant',
      colors: ['Interstellar Black', 'Starlight White'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MyUX',
      launchOS: 'Android 12',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Dolby Atmos tuning',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-motorola-edge-30-ultra/p',
      productPage: 'https://www.flipkart.com/motorola-edge-30-ultra-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-motorola-edge-30-ultra/p',
      verifiedDate: '2022-09',
    },
  },
  {
    id: 'motorola-edge-30-fusion',
    slug: 'motorola-edge-30-fusion',
    brand: 'Motorola',
    modelName: 'Motorola Edge 30 Fusion',
    generation: 'Edge 30',
    status: 'discontinued',
    launchDate: '2022-09',
    pricing: {
      startingPrice: 34999,
      maximumPrice: 42999,
      launchPrice: 42999,
      currentPrice: 34999,
      currency: 'INR',
      priceEffectiveDate: '2023-10',
      source: 'Motorola India Store Archive',
    },
    display: {
      displaySize: 6.55,
      displayType: 'FHD+ 144Hz 10-bit curved OLED, HDR10+, 1100 nits',
      resolution: '2400 x 1080 pixels',
      refreshRate: 144,
      peakBrightness: 1100,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '91.5%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 888+ 5G (5nm)',
      cpu: 'Octa-core (1x2.99 GHz Kryo 680 & 3x2.42 GHz & 4x1.80 GHz)',
      gpu: 'Adreno 660',
      ramOptions: ['8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 3.1',
      antutuScore: 860000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 13MP Ultrawide + 2MP Depth)',
      mainCamera: '50 MP, f/1.8, 1/1.55", omni-directional PDAF, OIS',
      ultrawideCamera: '13 MP, f/2.2, 120˚, AF, macro',
      telephotoCamera: 'N/A',
      frontCamera: '32 MP, f/2.5, autofocus, 4K30',
      videoRecording: '8K@30fps, 4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4400,
      wiredCharging: 68,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.2',
      nfc: true,
      usb: 'USB Type-C 3.1',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '158.5 x 72 x 7.5 mm',
      weight: 175,
      materials: 'Corning Gorilla Glass 5 back, aluminum frame',
      waterResistance: 'IP52 splash resistant',
      colors: ['Cosmic Grey', 'Solar Gold', 'Viva Magenta'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MyUX',
      launchOS: 'Android 12',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Dolby Atmos tuning',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-motorola-edge-30-fusion/p',
      productPage: 'https://www.flipkart.com/motorola-edge-30-fusion-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-motorola-edge-30-fusion/p',
      verifiedDate: '2022-09',
    },
  },
  {
    id: 'motorola-edge-30-pro',
    slug: 'motorola-edge-30-pro',
    brand: 'Motorola',
    modelName: 'Motorola Edge 30 Pro',
    generation: 'Edge 30',
    status: 'discontinued',
    launchDate: '2022-02',
    pricing: {
      startingPrice: 39999,
      maximumPrice: 49999,
      launchPrice: 49999,
      currentPrice: 39999,
      currency: 'INR',
      priceEffectiveDate: '2023-06',
      source: 'Motorola India Store Archive',
    },
    display: {
      displaySize: 6.7,
      displayType: 'FHD+ 144Hz 10-bit OLED, HDR10+, 1000 nits',
      resolution: '2400 x 1080 pixels',
      refreshRate: 144,
      peakBrightness: 1000,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '87.4%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Gen 1 (4nm)',
      cpu: 'Octa-core (1x3.00 GHz Cortex-X2 & 3x2.50 GHz & 4x1.80 GHz)',
      gpu: 'Adreno 730',
      ramOptions: ['8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 3.1',
      antutuScore: 980000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP Ultrawide + 2MP Depth)',
      mainCamera: '50 MP, f/1.8, 1/1.55", omni-directional PDAF, OIS',
      ultrawideCamera: '50 MP, f/2.2, 114˚, AF, macro',
      telephotoCamera: 'N/A',
      frontCamera: '60 MP, f/2.2, 4K30 video',
      videoRecording: '8K@24fps, 4K@60fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4800,
      wiredCharging: 68,
      wirelessCharging: 15,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.2',
      nfc: true,
      usb: 'USB Type-C 3.1, DisplayPort 1.4',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '163.1 x 76 x 8.8 mm',
      weight: 196,
      materials: 'Corning Gorilla Glass 5 back, plastic frame',
      waterResistance: 'IP52 water repellent',
      colors: ['Cosmos Blue', 'Stardust White'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MyUX',
      launchOS: 'Android 12',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Dolby Atmos tuning',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-motorola-edge-30-pro/p',
      productPage: 'https://www.flipkart.com/motorola-edge-30-pro-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-motorola-edge-30-pro/p',
      verifiedDate: '2022-02',
    },
  },

  // ── MOTO G SERIES (Mass-Market Best Sellers) ──
  {
    id: 'moto-g85-5g',
    slug: 'moto-g85-5g',
    brand: 'Motorola',
    modelName: 'Moto G85 5G',
    generation: 'Moto G',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 16999,
      maximumPrice: 18999,
      launchPrice: 17999,
      currentPrice: 16999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Motorola India Official Store',
    },
    display: {
      displaySize: 6.67,
      displayType: 'Full HD+ 120Hz 3D curved pOLED',
      resolution: '2400 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 1600,
      hdr: 'HDR10',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '92.7%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 6s Gen 3 (6nm)',
      cpu: 'Octa-core (2x2.3 GHz Kryo 660 Gold & 6x1.7 GHz Kryo 660 Silver)',
      gpu: 'Adreno 619',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 470000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP Sony LYT-600 + 8MP Ultrawide)',
      mainCamera: '50 MP Sony LYTIA 600, f/1.79, Quad Pixel, OIS',
      ultrawideCamera: '8 MP, f/2.2, 118˚, AF, macro vision',
      telephotoCamera: 'N/A',
      frontCamera: '32 MP, f/2.45, Quad Pixel',
      videoRecording: '1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 33,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5 (ac)',
      bluetooth: 'Bluetooth 5.1',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.91 x 73.06 x 7.59 mm',
      weight: 173,
      materials: 'Vegan leather rear / PMMA glass finish, curved polycarbonate frame',
      waterResistance: 'IP52 water repellent',
      colors: ['Olive Green', 'Cobalt Blue', 'Urban Grey'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Hello UI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers tuned by Dolby Atmos',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'In-display optical',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-moto-g85-5g/p',
      productPage: 'https://www.flipkart.com/moto-g85-5g-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-moto-g85-5g/p',
      verifiedDate: '2024-07',
    },
  },
  {
    id: 'motorola-moto-g84-5g',
    slug: 'motorola-moto-g84-5g',
    brand: 'Motorola',
    modelName: 'Moto G84 5G',
    generation: 'Moto G',
    status: 'discontinued',
    launchDate: '2023-09',
    pricing: {
      startingPrice: 16999,
      maximumPrice: 18999,
      launchPrice: 19999,
      currentPrice: 16999,
      currency: 'INR',
      priceEffectiveDate: '2024-06',
      source: 'Motorola India Store Archive',
    },
    display: {
      displaySize: 6.55,
      displayType: 'Full HD+ 120Hz 10-bit pOLED, 1300 nits',
      resolution: '2400 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 1300,
      hdr: 'HDR10',
      protection: 'Panda Glass',
      screenToBodyRatio: '87.2%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 695 5G (6nm)',
      cpu: 'Octa-core (2x2.2 GHz Kryo 660 Gold & 6x1.7 GHz Kryo 660 Silver)',
      gpu: 'Adreno 619',
      ramOptions: ['12GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 430000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 8MP Ultrawide)',
      mainCamera: '50 MP, f/1.9, 1/1.5", 1.0µm, PDAF, OIS',
      ultrawideCamera: '8 MP, f/2.2, 118˚, AF, macro',
      telephotoCamera: 'N/A',
      frontCamera: '16 MP, f/2.5',
      videoRecording: '1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 30,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5 (ac)',
      bluetooth: 'Bluetooth 5.1',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '160 x 74.4 x 7.6 mm',
      weight: 166.8,
      materials: 'Vegan leather / PMMA glass finish, plastic frame',
      waterResistance: 'IP54 splash resistant',
      colors: ['Viva Magenta', 'Marshmallow Blue', 'Midnight Blue'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MyUX',
      launchOS: 'Android 13',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Dolby Atmos tuning',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'In-display optical',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-moto-g84-5g/p',
      productPage: 'https://www.flipkart.com/moto-g84-5g-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-moto-g84-5g/p',
      verifiedDate: '2023-09',
    },
  },
  {
    id: 'moto-g64-5g',
    slug: 'moto-g64-5g',
    brand: 'Motorola',
    modelName: 'Moto G64 5G',
    generation: 'Moto G',
    status: 'active',
    launchDate: '2024-04',
    pricing: {
      startingPrice: 13999,
      maximumPrice: 15999,
      launchPrice: 14999,
      currentPrice: 13999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Motorola India Official Store',
    },
    display: {
      displaySize: 6.5,
      displayType: 'Full HD+ 120Hz IPS LCD',
      resolution: '2400 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 560,
      hdr: 'None',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '85.5%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7025 (6nm)',
      cpu: 'Octa-core (2x2.5 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)',
      gpu: 'IMG BXM-8-256',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 500000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP OIS + 8MP Ultrawide)',
      mainCamera: '50 MP, f/1.8, 0.61µm, PDAF, OIS',
      ultrawideCamera: '8 MP, f/2.2, 118˚, AF, macro vision',
      telephotoCamera: 'N/A',
      frontCamera: '16 MP, f/2.4',
      videoRecording: '1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 6000,
      wiredCharging: 33,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5 (ac)',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '161.56 x 73.82 x 8.89 mm',
      weight: 192,
      materials: 'Polycarbonate with 3D acrylic glass-like back',
      waterResistance: 'IP52 water repellent',
      colors: ['Mint Green', 'Pearl Blue', 'Ice Lilac'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MyUX',
      launchOS: 'Android 14',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers tuned by Dolby Atmos',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-moto-g64-5g/p',
      productPage: 'https://www.flipkart.com/moto-g64-5g-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-moto-g64-5g/p',
      verifiedDate: '2024-04',
    },
  },
  {
    id: 'motorola-moto-g54-5g',
    slug: 'motorola-moto-g54-5g',
    brand: 'Motorola',
    modelName: 'Moto G54 5G',
    generation: 'Moto G',
    status: 'discontinued',
    launchDate: '2023-09',
    pricing: {
      startingPrice: 12999,
      maximumPrice: 14999,
      launchPrice: 15999,
      currentPrice: 12999,
      currency: 'INR',
      priceEffectiveDate: '2024-05',
      source: 'Motorola India Store Archive',
    },
    display: {
      displaySize: 6.5,
      displayType: 'Full HD+ 120Hz IPS LCD',
      resolution: '2400 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 560,
      hdr: 'None',
      protection: 'Panda Glass',
      screenToBodyRatio: '85.5%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7020 (6nm)',
      cpu: 'Octa-core (2x2.2 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)',
      gpu: 'IMG BXM-8-256',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 460000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP OIS + 8MP Ultrawide)',
      mainCamera: '50 MP, f/1.8, 1/2.76", 0.64µm, PDAF, OIS',
      ultrawideCamera: '8 MP, f/2.2, 118˚, AF, macro',
      telephotoCamera: 'N/A',
      frontCamera: '16 MP, f/2.4',
      videoRecording: '1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 6000,
      wiredCharging: 33,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5 (ac)',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '161.6 x 73.8 x 8.9 mm',
      weight: 192,
      materials: 'Water-repellent plastic body',
      waterResistance: 'IP52 splash resistant',
      colors: ['Midnight Blue', 'Pearl Blue', 'Mint Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MyUX',
      launchOS: 'Android 13',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Dolby Atmos tuning',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-moto-g54-5g/p',
      productPage: 'https://www.flipkart.com/moto-g54-5g-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-moto-g54-5g/p',
      verifiedDate: '2023-09',
    },
  },
  {
    id: 'moto-g45-5g',
    slug: 'moto-g45-5g',
    brand: 'Motorola',
    modelName: 'Moto G45 5G',
    generation: 'Moto G',
    status: 'active',
    launchDate: '2024-08',
    pricing: {
      startingPrice: 9999,
      maximumPrice: 11999,
      launchPrice: 10999,
      currentPrice: 9999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Motorola India Official Store',
    },
    display: {
      displaySize: 6.5,
      displayType: 'HD+ 120Hz IPS LCD',
      resolution: '1600 x 720 pixels',
      refreshRate: 120,
      peakBrightness: 500,
      hdr: 'None',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '85.4%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 6s Gen 3 (6nm)',
      cpu: 'Octa-core (2x2.3 GHz Kryo 660 Gold & 6x2.0 GHz Kryo 660 Silver)',
      gpu: 'Adreno 619',
      ramOptions: ['4GB', '8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 450000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP Macro)',
      mainCamera: '50 MP, f/1.8, 0.64µm, Quad Pixel, PDAF',
      ultrawideCamera: 'N/A',
      telephotoCamera: 'N/A',
      frontCamera: '16 MP, f/2.4',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 18,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5 (ac)',
      bluetooth: 'Bluetooth 5.1',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '162.7 x 74.64 x 8.03 mm',
      weight: 183,
      materials: 'Vegan leather rear finish, plastic frame',
      waterResistance: 'IP52 water repellent',
      colors: ['Brilliant Blue', 'Viva Magenta', 'Brilliant Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Hello UI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers tuned by Dolby Atmos',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-moto-g45-5g/p',
      productPage: 'https://www.flipkart.com/moto-g45-5g-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-moto-g45-5g/p',
      verifiedDate: '2024-08',
    },
  },
  {
    id: 'motorola-moto-g24-power',
    slug: 'motorola-moto-g24-power',
    brand: 'Motorola',
    modelName: 'Moto G24 Power',
    generation: 'Moto G',
    status: 'active',
    launchDate: '2024-01',
    pricing: {
      startingPrice: 7999,
      maximumPrice: 8999,
      launchPrice: 8999,
      currentPrice: 7999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Motorola India Official Store',
    },
    display: {
      displaySize: 6.56,
      displayType: 'HD+ 90Hz IPS LCD, 537 nits',
      resolution: '1612 x 720 pixels',
      refreshRate: 90,
      peakBrightness: 537,
      hdr: 'None',
      protection: 'Panda Glass',
      screenToBodyRatio: '85.2%',
    },
    performance: {
      chipset: 'MediaTek Helio G85 (12nm)',
      cpu: 'Octa-core (2x2.0 GHz Cortex-A75 & 6x1.8 GHz Cortex-A55)',
      gpu: 'Mali-G52 MC2',
      ramOptions: ['4GB', '8GB'],
      storageOptions: ['128GB'],
      storageType: 'eMMC 5.1',
      antutuScore: 260000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP Macro)',
      mainCamera: '50 MP, f/1.8, 0.64µm, Quad Pixel, PDAF',
      ultrawideCamera: 'N/A',
      telephotoCamera: 'N/A',
      frontCamera: '16 MP, f/2.45',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 6000,
      wiredCharging: 33,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: false,
      has4G: true,
      wifi: 'Wi-Fi 5 (ac)',
      bluetooth: 'Bluetooth 5.0',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dedicated Dual SIM + microSD',
    },
    physical: {
      dimensions: '163.49 x 74.53 x 8.99 mm',
      weight: 197,
      materials: 'Water repellent 3D acrylic glass-like back',
      waterResistance: 'IP52 splash resistant',
      colors: ['Glacier Blue', 'Ink Blue'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MyUX',
      launchOS: 'Android 14',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Stereo speakers with Dolby Atmos tuning',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-moto-g24-power/p',
      productPage: 'https://www.flipkart.com/moto-g24-power-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-moto-g24-power/p',
      verifiedDate: '2024-01',
    },
  },
  {
    id: 'motorola-moto-g73-5g',
    slug: 'motorola-moto-g73-5g',
    brand: 'Motorola',
    modelName: 'Moto G73 5G',
    generation: 'Moto G',
    status: 'discontinued',
    launchDate: '2023-03',
    pricing: {
      startingPrice: 16999,
      maximumPrice: 18999,
      launchPrice: 18999,
      currentPrice: 16999,
      currency: 'INR',
      priceEffectiveDate: '2023-12',
      source: 'Motorola India Store Archive',
    },
    display: {
      displaySize: 6.5,
      displayType: 'Full HD+ 120Hz IPS LCD',
      resolution: '2400 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 500,
      hdr: 'None',
      protection: 'Panda Glass',
      screenToBodyRatio: '85.6%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 930 (6nm)',
      cpu: 'Octa-core (2x2.2 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)',
      gpu: 'IMG BXM-8-256',
      ramOptions: ['8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 430000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 8MP Ultrawide)',
      mainCamera: '50 MP, f/1.8, 1.0µm, 2.0µm Ultra Pixel, PDAF',
      ultrawideCamera: '8 MP, f/2.2, 118˚, AF, macro',
      telephotoCamera: 'N/A',
      frontCamera: '16 MP, f/2.4',
      videoRecording: '1080p@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 30,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5 (ac)',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '161.4 x 73.8 x 8.3 mm',
      weight: 181,
      materials: 'Water repellent polycarbonate body',
      waterResistance: 'IP52 splash resistant',
      colors: ['Midnight Blue', 'Lucent White'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MyUX',
      launchOS: 'Android 13',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Dolby Atmos tuning',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-moto-g73-5g/p',
      productPage: 'https://www.flipkart.com/moto-g73-5g-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-moto-g73-5g/p',
      verifiedDate: '2023-03',
    },
  },
  {
    id: 'motorola-moto-g82-5g',
    slug: 'motorola-moto-g82-5g',
    brand: 'Motorola',
    modelName: 'Moto G82 5G',
    generation: 'Moto G',
    status: 'discontinued',
    launchDate: '2022-06',
    pricing: {
      startingPrice: 19999,
      maximumPrice: 21499,
      launchPrice: 21499,
      currentPrice: 19999,
      currency: 'INR',
      priceEffectiveDate: '2023-06',
      source: 'Motorola India Store Archive',
    },
    display: {
      displaySize: 6.6,
      displayType: 'Full HD+ 120Hz 10-bit pOLED',
      resolution: '2400 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 1000,
      hdr: 'None',
      protection: 'Panda Glass',
      screenToBodyRatio: '87.7%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 695 5G (6nm)',
      cpu: 'Octa-core (2x2.2 GHz Kryo 660 Gold & 6x1.7 GHz Kryo 660 Silver)',
      gpu: 'Adreno 619',
      ramOptions: ['6GB', '8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 400000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP OIS + 8MP Ultrawide + 2MP Macro)',
      mainCamera: '50 MP, f/1.8, 0.64µm, PDAF, OIS',
      ultrawideCamera: '8 MP, f/2.2, 118˚',
      telephotoCamera: 'N/A',
      frontCamera: '16 MP, f/2.2',
      videoRecording: '1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 30,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5 (ac)',
      bluetooth: 'Bluetooth 5.1',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '160.9 x 74.5 x 8 mm',
      weight: 173,
      materials: 'Water repellent polycarbonate body',
      waterResistance: 'IP52 splash resistant',
      colors: ['Meteorite Gray', 'White Lily'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MyUX',
      launchOS: 'Android 12',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Dolby Atmos tuning',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-moto-g82-5g/p',
      productPage: 'https://www.flipkart.com/moto-g82-5g-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-moto-g82-5g/p',
      verifiedDate: '2022-06',
    },
  },
];

const variants: MobileVariant[] = [
  // Razr 50 Ultra
  {
    id: 'motorola-razr-50-ultra-12gb-512gb',
    modelId: 'motorola-razr-50-ultra',
    name: 'Motorola Razr 50 Ultra (12GB RAM, 512GB)',
    ram: '12GB',
    storage: '512GB',
    color: 'Midnight Blue',
    price: 89999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Razr 40 Ultra
  {
    id: 'motorola-razr-40-ultra-8gb-256gb',
    modelId: 'motorola-razr-40-ultra',
    name: 'Motorola Razr 40 Ultra (8GB RAM, 256GB)',
    ram: '8GB',
    storage: '256GB',
    color: 'Infinite Black',
    price: 49999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  // Edge 50 Ultra
  {
    id: 'motorola-edge-50-ultra-12gb-512gb',
    modelId: 'motorola-edge-50-ultra',
    name: 'Motorola Edge 50 Ultra (12GB RAM, 512GB)',
    ram: '12GB',
    storage: '512GB',
    color: 'Nordic Wood',
    price: 54999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Edge 50 Pro
  {
    id: 'motorola-edge-50-pro-8gb-256gb',
    modelId: 'motorola-edge-50-pro',
    name: 'Motorola Edge 50 Pro (8GB RAM, 256GB, 68W Charger)',
    ram: '8GB',
    storage: '256GB',
    color: 'Luxe Lavender',
    price: 29999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  {
    id: 'motorola-edge-50-pro-12gb-256gb',
    modelId: 'motorola-edge-50-pro',
    name: 'Motorola Edge 50 Pro (12GB RAM, 256GB, 125W Charger)',
    ram: '12GB',
    storage: '256GB',
    color: 'Black Beauty',
    price: 33999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Edge 50 Fusion
  {
    id: 'motorola-edge-50-fusion-8gb-128gb',
    modelId: 'motorola-edge-50-fusion',
    name: 'Motorola Edge 50 Fusion (8GB RAM, 128GB)',
    ram: '8GB',
    storage: '128GB',
    color: 'Marshmallow Blue',
    price: 20999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  {
    id: 'motorola-edge-50-fusion-12gb-256gb',
    modelId: 'motorola-edge-50-fusion',
    name: 'Motorola Edge 50 Fusion (12GB RAM, 256GB)',
    ram: '12GB',
    storage: '256GB',
    color: 'Hot Pink',
    price: 22999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Edge 50 Neo
  {
    id: 'motorola-edge-50-neo-8gb-256gb',
    modelId: 'motorola-edge-50-neo',
    name: 'Motorola Edge 50 Neo (8GB RAM, 256GB)',
    ram: '8GB',
    storage: '256GB',
    color: 'Poinciana',
    price: 23999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Edge 40
  {
    id: 'motorola-edge-40-8gb-256gb',
    modelId: 'motorola-edge-40',
    name: 'Motorola Edge 40 (8GB RAM, 256GB)',
    ram: '8GB',
    storage: '256GB',
    color: 'Eclipse Black',
    price: 26999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  // Edge 40 Neo
  {
    id: 'motorola-edge-40-neo-8gb-128gb',
    modelId: 'motorola-edge-40-neo',
    name: 'Motorola Edge 40 Neo (8GB RAM, 128GB)',
    ram: '8GB',
    storage: '128GB',
    color: 'Caneel Bay',
    price: 20999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  {
    id: 'motorola-edge-40-neo-12gb-256gb',
    modelId: 'motorola-edge-40-neo',
    name: 'Motorola Edge 40 Neo (12GB RAM, 256GB)',
    ram: '12GB',
    storage: '256GB',
    color: 'Black Onyx',
    price: 22999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  // Edge 30 Ultra
  {
    id: 'motorola-edge-30-ultra-8gb-128gb',
    modelId: 'motorola-edge-30-ultra',
    name: 'Motorola Edge 30 Ultra (8GB RAM, 128GB)',
    ram: '8GB',
    storage: '128GB',
    color: 'Interstellar Black',
    price: 44999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  // Edge 30 Fusion
  {
    id: 'motorola-edge-30-fusion-8gb-128gb',
    modelId: 'motorola-edge-30-fusion',
    name: 'Motorola Edge 30 Fusion (8GB RAM, 128GB)',
    ram: '8GB',
    storage: '128GB',
    color: 'Cosmic Grey',
    price: 34999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  // Edge 30 Pro
  {
    id: 'motorola-edge-30-pro-8gb-128gb',
    modelId: 'motorola-edge-30-pro',
    name: 'Motorola Edge 30 Pro (8GB RAM, 128GB)',
    ram: '8GB',
    storage: '128GB',
    color: 'Cosmos Blue',
    price: 39999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  // Moto G85 5G
  {
    id: 'moto-g85-5g-8gb-128gb',
    modelId: 'moto-g85-5g',
    name: 'Moto G85 5G (8GB RAM, 128GB)',
    ram: '8GB',
    storage: '128GB',
    color: 'Olive Green',
    price: 16999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  {
    id: 'moto-g85-5g-12gb-256gb',
    modelId: 'moto-g85-5g',
    name: 'Moto G85 5G (12GB RAM, 256GB)',
    ram: '12GB',
    storage: '256GB',
    color: 'Cobalt Blue',
    price: 18999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Moto G84 5G
  {
    id: 'motorola-moto-g84-5g-12gb-256gb',
    modelId: 'motorola-moto-g84-5g',
    name: 'Moto G84 5G (12GB RAM, 256GB)',
    ram: '12GB',
    storage: '256GB',
    color: 'Viva Magenta',
    price: 16999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  // Moto G64 5G
  {
    id: 'moto-g64-5g-8gb-128gb',
    modelId: 'moto-g64-5g',
    name: 'Moto G64 5G (8GB RAM, 128GB)',
    ram: '8GB',
    storage: '128GB',
    color: 'Pearl Blue',
    price: 13999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  {
    id: 'moto-g64-5g-12gb-256gb',
    modelId: 'moto-g64-5g',
    name: 'Moto G64 5G (12GB RAM, 256GB)',
    ram: '12GB',
    storage: '256GB',
    color: 'Mint Green',
    price: 15999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Moto G54 5G
  {
    id: 'motorola-moto-g54-5g-8gb-128gb',
    modelId: 'motorola-moto-g54-5g',
    name: 'Moto G54 5G (8GB RAM, 128GB)',
    ram: '8GB',
    storage: '128GB',
    color: 'Midnight Blue',
    price: 12999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  {
    id: 'motorola-moto-g54-5g-12gb-256gb',
    modelId: 'motorola-moto-g54-5g',
    name: 'Moto G54 5G (12GB RAM, 256GB)',
    ram: '12GB',
    storage: '256GB',
    color: 'Pearl Blue',
    price: 14999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  // Moto G45 5G
  {
    id: 'moto-g45-5g-4gb-128gb',
    modelId: 'moto-g45-5g',
    name: 'Moto G45 5G (4GB RAM, 128GB)',
    ram: '4GB',
    storage: '128GB',
    color: 'Brilliant Blue',
    price: 9999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  {
    id: 'moto-g45-5g-8gb-128gb',
    modelId: 'moto-g45-5g',
    name: 'Moto G45 5G (8GB RAM, 128GB)',
    ram: '8GB',
    storage: '128GB',
    color: 'Viva Magenta',
    price: 11999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Moto G24 Power
  {
    id: 'motorola-moto-g24-power-4gb-128gb',
    modelId: 'motorola-moto-g24-power',
    name: 'Moto G24 Power (4GB RAM, 128GB)',
    ram: '4GB',
    storage: '128GB',
    color: 'Glacier Blue',
    price: 7999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  {
    id: 'motorola-moto-g24-power-8gb-128gb',
    modelId: 'motorola-moto-g24-power',
    name: 'Moto G24 Power (8GB RAM, 128GB)',
    ram: '8GB',
    storage: '128GB',
    color: 'Ink Blue',
    price: 8999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Moto G73 5G
  {
    id: 'motorola-moto-g73-5g-8gb-128gb',
    modelId: 'motorola-moto-g73-5g',
    name: 'Moto G73 5G (8GB RAM, 128GB)',
    ram: '8GB',
    storage: '128GB',
    color: 'Midnight Blue',
    price: 16999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  // Moto G82 5G
  {
    id: 'motorola-moto-g82-5g-6gb-128gb',
    modelId: 'motorola-moto-g82-5g',
    name: 'Moto G82 5G (6GB RAM, 128GB)',
    ram: '6GB',
    storage: '128GB',
    color: 'Meteorite Gray',
    price: 19999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    modelId: 'motorola-razr-50-ultra',
    modelName: 'Motorola Razr 50 Ultra',
    brand: 'Motorola',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/motorola-razr-50-ultra.jpg',
        angle: 'front',
        source: 'Motorola Official (GSMArena CDN)',
        sourceUrl: 'https://www.motorola.in/smartphones-motorola-razr-50-ultra/p',
        verified: true,
        alt: 'Motorola Razr 50 Ultra front foldable view',
      },
    ],
  },
  {
    modelId: 'motorola-razr-40-ultra',
    modelName: 'Motorola Razr 40 Ultra',
    brand: 'Motorola',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/motorola-razr-40-ultra.jpg',
        angle: 'front',
        source: 'Motorola Official (GSMArena CDN)',
        sourceUrl: 'https://www.motorola.in/smartphones-motorola-razr-40-ultra/p',
        verified: true,
        alt: 'Motorola Razr 40 Ultra front foldable view',
      },
    ],
  },
  {
    modelId: 'motorola-edge-50-ultra',
    modelName: 'Motorola Edge 50 Ultra',
    brand: 'Motorola',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-50-ultra.jpg',
        angle: 'front',
        source: 'Motorola Official (GSMArena CDN)',
        sourceUrl: 'https://www.motorola.in/smartphones-motorola-edge-50-ultra/p',
        verified: true,
        alt: 'Motorola Edge 50 Ultra front view',
      },
    ],
  },
  {
    modelId: 'motorola-edge-50-pro',
    modelName: 'Motorola Edge 50 Pro',
    brand: 'Motorola',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-50-pro.jpg',
        angle: 'front',
        source: 'Motorola Official (GSMArena CDN)',
        sourceUrl: 'https://www.motorola.in/smartphones-motorola-edge-50-pro/p',
        verified: true,
        alt: 'Motorola Edge 50 Pro front curved view',
      },
    ],
  },
  {
    modelId: 'motorola-edge-50-fusion',
    modelName: 'Motorola Edge 50 Fusion',
    brand: 'Motorola',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-50-fusion.jpg',
        angle: 'front',
        source: 'Motorola Official (GSMArena CDN)',
        sourceUrl: 'https://www.motorola.in/smartphones-motorola-edge-50-fusion/p',
        verified: true,
        alt: 'Motorola Edge 50 Fusion front curved view',
      },
    ],
  },
  {
    modelId: 'motorola-edge-50-neo',
    modelName: 'Motorola Edge 50 Neo',
    brand: 'Motorola',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-50-neo.jpg',
        angle: 'front',
        source: 'Motorola Official (GSMArena CDN)',
        sourceUrl: 'https://www.motorola.in/smartphones-motorola-edge-50-neo/p',
        verified: true,
        alt: 'Motorola Edge 50 Neo front display view',
      },
    ],
  },
  {
    modelId: 'motorola-edge-40',
    modelName: 'Motorola Edge 40',
    brand: 'Motorola',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-40.jpg',
        angle: 'front',
        source: 'Motorola Official (GSMArena CDN)',
        sourceUrl: 'https://www.motorola.in/smartphones-motorola-edge-40/p',
        verified: true,
        alt: 'Motorola Edge 40 front curved display view',
      },
    ],
  },
  {
    modelId: 'motorola-edge-40-neo',
    modelName: 'Motorola Edge 40 Neo',
    brand: 'Motorola',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-40-neo.jpg',
        angle: 'front',
        source: 'Motorola Official (GSMArena CDN)',
        sourceUrl: 'https://www.motorola.in/smartphones-motorola-edge-40-neo/p',
        verified: true,
        alt: 'Motorola Edge 40 Neo front display view',
      },
    ],
  },
  {
    modelId: 'motorola-edge-30-ultra',
    modelName: 'Motorola Edge 30 Ultra',
    brand: 'Motorola',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-30-ultra.jpg',
        angle: 'front',
        source: 'Motorola Official (GSMArena CDN)',
        sourceUrl: 'https://www.motorola.in/smartphones-motorola-edge-30-ultra/p',
        verified: true,
        alt: 'Motorola Edge 30 Ultra front view',
      },
    ],
  },
  {
    modelId: 'motorola-edge-30-fusion',
    modelName: 'Motorola Edge 30 Fusion',
    brand: 'Motorola',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-30-fusion.jpg',
        angle: 'front',
        source: 'Motorola Official (GSMArena CDN)',
        sourceUrl: 'https://www.motorola.in/smartphones-motorola-edge-30-fusion/p',
        verified: true,
        alt: 'Motorola Edge 30 Fusion front view',
      },
    ],
  },
  {
    modelId: 'motorola-edge-30-pro',
    modelName: 'Motorola Edge 30 Pro',
    brand: 'Motorola',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-30-pro.jpg',
        angle: 'front',
        source: 'Motorola Official (GSMArena CDN)',
        sourceUrl: 'https://www.motorola.in/smartphones-motorola-edge-30-pro/p',
        verified: true,
        alt: 'Motorola Edge 30 Pro front view',
      },
    ],
  },
  {
    modelId: 'moto-g85-5g',
    modelName: 'Moto G85 5G',
    brand: 'Motorola',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-g85.jpg',
        angle: 'front',
        source: 'Motorola Official (GSMArena CDN)',
        sourceUrl: 'https://www.motorola.in/smartphones-moto-g85-5g/p',
        verified: true,
        alt: 'Moto G85 5G front 3D curved pOLED display',
      },
    ],
  },
  {
    modelId: 'motorola-moto-g84-5g',
    modelName: 'Moto G84 5G',
    brand: 'Motorola',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-g84.jpg',
        angle: 'front',
        source: 'Motorola Official (GSMArena CDN)',
        sourceUrl: 'https://www.motorola.in/smartphones-moto-g84-5g/p',
        verified: true,
        alt: 'Moto G84 5G front view',
      },
    ],
  },
  {
    modelId: 'moto-g64-5g',
    modelName: 'Moto G64 5G',
    brand: 'Motorola',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-g64.jpg',
        angle: 'front',
        source: 'Motorola Official (GSMArena CDN)',
        sourceUrl: 'https://www.motorola.in/smartphones-moto-g64-5g/p',
        verified: true,
        alt: 'Moto G64 5G front display view',
      },
    ],
  },
  {
    modelId: 'motorola-moto-g54-5g',
    modelName: 'Moto G54 5G',
    brand: 'Motorola',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-g54.jpg',
        angle: 'front',
        source: 'Motorola Official (GSMArena CDN)',
        sourceUrl: 'https://www.motorola.in/smartphones-moto-g54-5g/p',
        verified: true,
        alt: 'Moto G54 5G front view',
      },
    ],
  },
  {
    modelId: 'moto-g45-5g',
    modelName: 'Moto G45 5G',
    brand: 'Motorola',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-g45-5g.jpg',
        angle: 'front',
        source: 'Motorola Official (GSMArena CDN)',
        sourceUrl: 'https://www.motorola.in/smartphones-moto-g45-5g/p',
        verified: true,
        alt: 'Moto G45 5G front display view',
      },
    ],
  },
  {
    modelId: 'motorola-moto-g24-power',
    modelName: 'Moto G24 Power',
    brand: 'Motorola',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-g24-power.jpg',
        angle: 'front',
        source: 'Motorola Official (GSMArena CDN)',
        sourceUrl: 'https://www.motorola.in/smartphones-moto-g24-power/p',
        verified: true,
        alt: 'Moto G24 Power front view',
      },
    ],
  },
  {
    modelId: 'motorola-moto-g73-5g',
    modelName: 'Moto G73 5G',
    brand: 'Motorola',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-g73.jpg',
        angle: 'front',
        source: 'Motorola Official (GSMArena CDN)',
        sourceUrl: 'https://www.motorola.in/smartphones-moto-g73-5g/p',
        verified: true,
        alt: 'Moto G73 5G front view',
      },
    ],
  },
  {
    modelId: 'motorola-moto-g82-5g',
    modelName: 'Moto G82 5G',
    brand: 'Motorola',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-g82.jpg',
        angle: 'front',
        source: 'Motorola Official (GSMArena CDN)',
        sourceUrl: 'https://www.motorola.in/smartphones-moto-g82-5g/p',
        verified: true,
        alt: 'Moto G82 5G front view',
      },
    ],
  },
];

export const motorolaBundle: MobileBrandBundle = {
  brand: 'Motorola',
  models,
  variants,
  images,
};
