import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  {
    id: 'motorola-edge-50-ultra',
    slug: 'motorola-edge-50-ultra',
    brand: 'Motorola',
    modelName: 'Motorola Edge 50 Ultra',
    generation: 'Edge 50',
    status: 'active',
    launchDate: '2024-06',
    pricing: {
      startingPrice: 54999,
      maximumPrice: 54999,
      launchPrice: 59999,
      currentPrice: 54999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Motorola India Official Store',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Super HD 1.5K 144Hz pOLED',
      resolution: '2712 x 1220 pixels',
      refreshRate: 144,
      peakBrightness: 2500,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass Victus',
      screenToBodyRatio: '92.1%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8s Gen 3 (4nm)',
      cpu: 'Octa-core (1x3.0 GHz Cortex-X4 & 4x2.8 GHz & 3x2.0 GHz)',
      gpu: 'Adreno 735',
      ramOptions: ['12GB'],
      storageOptions: ['512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 1540000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 64MP) Pantone Validated',
      mainCamera: '50 MP, f/1.6, 1/1.3", omni-directional PDAF, Laser AF, OIS',
      ultrawideCamera: '50 MP, f/2.0, 122˚, macro',
      telephotoCamera: '64 MP periscope, f/2.4, 3x optical, 100x hybrid, OIS',
      frontCamera: '50 MP, f/1.9, autofocus, 4K60',
      videoRecording: '4K@60fps, 1080p@960fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4500,
      wiredCharging: 125,
      wirelessCharging: 50,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 3.1 Gen 2, DisplayPort 1.4',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.09 x 72.38 x 8.59 mm',
      weight: 197,
      materials: 'Real wood (Nordic Wood) / Vegan leather, sandblasted aluminum frame',
      waterResistance: 'IP68 water and dust resistant',
      colors: ['Nordic Wood', 'Peach Fuzz', 'Forest Grey'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Hello UI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers tuned by Dolby Atmos',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-motorola-edge-50-ultra/p',
      productPage: 'https://www.flipkart.com/motorola-edge-50-ultra-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-motorola-edge-50-ultra/p',
      verifiedDate: '2024-06',
    },
  },
  {
    id: 'motorola-edge-50-pro',
    slug: 'motorola-edge-50-pro',
    brand: 'Motorola',
    modelName: 'Motorola Edge 50 Pro',
    generation: 'Edge 50',
    status: 'active',
    launchDate: '2024-04',
    pricing: {
      startingPrice: 29999,
      maximumPrice: 34999,
      launchPrice: 31999,
      currentPrice: 29999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Motorola India Official Store',
    },
    display: {
      displaySize: 6.7,
      displayType: '1.5K 144Hz 3D Curved pOLED Pantone Validated',
      resolution: '2712 x 1220 pixels',
      refreshRate: 144,
      peakBrightness: 2000,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass',
      screenToBodyRatio: '93.0%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7 Gen 3 (4nm)',
      cpu: 'Octa-core (1x2.63 GHz Cortex-A715 & 4x2.4 GHz & 3x1.8 GHz)',
      gpu: 'Adreno 720',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 860000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 13MP + 10MP) Pantone Validated',
      mainCamera: '50 MP, f/1.4 (widest aperture in class), 1/1.55", OIS',
      ultrawideCamera: '13 MP, f/2.2, 120˚, macro',
      telephotoCamera: '10 MP, 3x optical zoom, 30x hybrid, OIS',
      frontCamera: '50 MP, f/1.9, autofocus, 4K30',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4500,
      wiredCharging: 125,
      wirelessCharging: 50,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 3.1, DisplayPort 1.4',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.23 x 72.4 x 8.19 mm',
      weight: 186,
      materials: 'Handmade Italian Acetate finish (Moonlight Pearl) or Vegan leather, aluminum frame',
      waterResistance: 'IP68 water and dust resistant',
      colors: ['Moonlight Pearl', 'Luxe Lavender', 'Black Beauty'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Hello UI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Dolby Atmos',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-motorola-edge-50-pro/p',
      productPage: 'https://www.flipkart.com/motorola-edge-50-pro-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-motorola-edge-50-pro/p',
      verifiedDate: '2024-04',
    },
  },
  {
    id: 'motorola-edge-50-fusion',
    slug: 'motorola-edge-50-fusion',
    brand: 'Motorola',
    modelName: 'Motorola Edge 50 Fusion',
    generation: 'Edge 50',
    status: 'active',
    launchDate: '2024-05',
    pricing: {
      startingPrice: 20999,
      maximumPrice: 22999,
      launchPrice: 22999,
      currentPrice: 20999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Motorola India Official Store',
    },
    display: {
      displaySize: 6.7,
      displayType: '144Hz Endless Edge Curved pOLED',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 144,
      peakBrightness: 1600,
      hdr: 'HDR10',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '92.0%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7s Gen 2 (4nm)',
      cpu: 'Octa-core (4x2.40 GHz Cortex-A78 & 4x1.95 GHz Cortex-A55)',
      gpu: 'Adreno 710',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 610000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 13MP)',
      mainCamera: '50 MP Sony LYTIA LYT-700C, f/1.88, OIS, all-pixel focus',
      ultrawideCamera: '13 MP, f/2.2, 120˚, macro',
      telephotoCamera: 'None',
      frontCamera: '32 MP, f/2.45, 4K30',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 68,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.2',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.9 x 73.1 x 7.9 mm',
      weight: 174.9,
      materials: 'Ultra-thin curved design, vegan leather or glass back',
      waterResistance: 'IP68 water and dust resistant',
      colors: ['Marshmallow Blue', 'Hot Pink', 'Forest Blue'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Hello UI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Dolby Atmos',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-motorola-edge-50-fusion/p',
      productPage: 'https://www.flipkart.com/motorola-edge-50-fusion-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-motorola-edge-50-fusion/p',
      verifiedDate: '2024-05',
    },
  },
  {
    id: 'motorola-edge-50-neo',
    slug: 'motorola-edge-50-neo',
    brand: 'Motorola',
    modelName: 'Motorola Edge 50 Neo',
    generation: 'Edge 50',
    status: 'active',
    launchDate: '2024-09',
    pricing: {
      startingPrice: 22999,
      maximumPrice: 22999,
      launchPrice: 23999,
      currentPrice: 22999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Motorola India Official Store',
    },
    display: {
      displaySize: 6.4,
      displayType: 'Super HD 1.5K 120Hz LTPO pOLED',
      resolution: '2670 x 1220 pixels',
      refreshRate: 120,
      peakBrightness: 3000,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '90.2%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7300 (4nm)',
      cpu: 'Octa-core (4x2.5 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G615 MC2',
      ramOptions: ['8GB'],
      storageOptions: ['256GB'],
      storageType: 'uMCP',
      antutuScore: 670000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 13MP + 10MP) with Dedicated 3x Telephoto',
      mainCamera: '50 MP Sony LYTIA LYT-700C, f/1.8, OIS',
      ultrawideCamera: '13 MP, f/2.2, 120˚, macro',
      telephotoCamera: '10 MP, 3x optical zoom, 30x digital, OIS',
      frontCamera: '32 MP, f/2.4, 4K30',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4310,
      wiredCharging: 68,
      wirelessCharging: 15,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '154.1 x 71.2 x 8.1 mm',
      weight: 171,
      materials: 'Compact MIL-STD-810H military certified durability + Vegan leather Pantone back',
      waterResistance: 'IP68 water and dust resistant',
      colors: ['Pantone Poinciana', 'Pantone Lattè', 'Pantone Grisaille', 'Pantone Nautical Blue'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Hello UI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 5,
      securityUpdatePolicy: '5 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Dolby Atmos',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-motorola-edge-50-neo/p',
      productPage: 'https://www.flipkart.com/motorola-edge-50-neo-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-motorola-edge-50-neo/p',
      verifiedDate: '2024-09',
    },
  },
  {
    id: 'moto-g85-5g',
    slug: 'moto-g85-5g',
    brand: 'Motorola',
    modelName: 'Moto G85 5G',
    generation: 'G85',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 16999,
      maximumPrice: 18999,
      launchPrice: 17999,
      currentPrice: 16999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Motorola India Official Store',
    },
    display: {
      displaySize: 6.67,
      displayType: '120Hz Endless Edge Curved 10-bit pOLED',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1600,
      hdr: 'None',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '92.7%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 6s Gen 3 (6nm)',
      cpu: 'Octa-core (2x2.3 GHz Kryo 660 Gold & 6x2.0 GHz Kryo 660 Silver)',
      gpu: 'Adreno 619',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 485000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 8MP)',
      mainCamera: '50 MP Sony LYTIA 600, f/1.79, Quad Pixel, OIS',
      ultrawideCamera: '8 MP, f/2.2, 118˚, macro',
      telephotoCamera: 'None',
      frontCamera: '32 MP, f/2.4',
      videoRecording: '1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 33,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.1',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.91 x 73.06 x 7.59 mm',
      weight: 171,
      materials: 'Curved vegan leather finish, water repellent design',
      waterResistance: 'IP54 splash and dust resistant',
      colors: ['Cobalt Blue', 'Olive Green', 'Urban Grey'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Hello UI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Dolby Atmos',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-moto-g85-5g/p',
      productPage: 'https://www.flipkart.com/moto-g85-5g-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-moto-g85-5g/p',
      verifiedDate: '2024-07',
    },
  },
  {
    id: 'moto-g64-5g',
    slug: 'moto-g64-5g',
    brand: 'Motorola',
    modelName: 'Moto G64 5G',
    generation: 'G64',
    status: 'active',
    launchDate: '2024-04',
    pricing: {
      startingPrice: 13999,
      maximumPrice: 15999,
      launchPrice: 14999,
      currentPrice: 13999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Motorola India Official Store',
    },
    display: {
      displaySize: 6.5,
      displayType: '120Hz FHD+ IPS Display',
      resolution: '2400 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 560,
      hdr: 'None',
      protection: 'Corning Gorilla Glass',
      screenToBodyRatio: '85.5%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7025 (6nm world premiere)',
      cpu: 'Octa-core (2x2.5 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)',
      gpu: 'IMG BXM-8-256',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 505000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 8MP) with OIS',
      mainCamera: '50 MP, f/1.8, Quad Pixel, OIS',
      ultrawideCamera: '8 MP, f/2.2, 118˚, macro',
      telephotoCamera: 'None',
      frontCamera: '16 MP, f/2.4',
      videoRecording: '1080p@30fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 6000,
      wiredCharging: 33,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM hybrid',
    },
    physical: {
      dimensions: '161.56 x 73.82 x 8.89 mm',
      weight: 192,
      materials: 'Water repellent PMMA matte finish',
      waterResistance: 'IP52 water repellent',
      colors: ['Mint Green', 'Pearl Blue', 'Ice Lilac'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'My UX',
      launchOS: 'Android 14',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Stereo speakers with Dolby Atmos',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-moto-g64-5g/p',
      productPage: 'https://www.flipkart.com/moto-g64-5g-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-moto-g64-5g/p',
      verifiedDate: '2024-04',
    },
  },
  {
    id: 'moto-g45-5g',
    slug: 'moto-g45-5g',
    brand: 'Motorola',
    modelName: 'Moto G45 5G',
    generation: 'G45',
    status: 'active',
    launchDate: '2024-08',
    pricing: {
      startingPrice: 9999,
      maximumPrice: 11999,
      launchPrice: 10999,
      currentPrice: 9999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Motorola India Official Store',
    },
    display: {
      displaySize: 6.5,
      displayType: '120Hz HD+ IPS Display with Smart Refresh Rate',
      resolution: '1600 x 720 pixels',
      refreshRate: 120,
      peakBrightness: 500,
      hdr: 'None',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '85.0%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 6s Gen 3 (6nm)',
      cpu: 'Octa-core (2x2.3 GHz Kryo 660 Gold & 6x2.0 GHz Kryo 660 Silver)',
      gpu: 'Adreno 619',
      ramOptions: ['4GB', '8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 470000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP Quad Pixel + 2MP Macro)',
      mainCamera: '50 MP, f/1.8, Quad Pixel, PDAF',
      ultrawideCamera: 'None',
      telephotoCamera: 'None (2 MP Macro)',
      frontCamera: '16 MP, f/2.4',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 18,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.1',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM hybrid',
    },
    physical: {
      dimensions: '162.7 x 74.6 x 8.0 mm',
      weight: 183,
      materials: 'Premium vegan leather back finish in Pantone curated colors',
      waterResistance: 'IP52 water repellent',
      colors: ['Brilliant Blue', 'Viva Magenta', 'Brilliant Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Hello UI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Dolby Atmos & Hi-Res audio',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-moto-g45-5g/p',
      productPage: 'https://www.flipkart.com/moto-g45-5g-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-moto-g45-5g/p',
      verifiedDate: '2024-08',
    },
  },
];

const variants: MobileVariant[] = [
  // Edge 50 Ultra
  {
    id: 'motorola-edge-50-ultra-12gb-512gb',
    modelId: 'motorola-edge-50-ultra',
    modelName: 'Motorola Edge 50 Ultra',
    brand: 'Motorola',
    variantName: '12GB + 512GB',
    ram: '12GB',
    storage: '512GB',
    price: 54999,
    mrp: 64999,
    colors: ['Nordic Wood', 'Peach Fuzz', 'Forest Grey'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },

  // Edge 50 Pro
  {
    id: 'motorola-edge-50-pro-8gb-256gb',
    modelId: 'motorola-edge-50-pro',
    modelName: 'Motorola Edge 50 Pro',
    brand: 'Motorola',
    variantName: '8GB + 256GB (68W Charger)',
    ram: '8GB',
    storage: '256GB',
    price: 29999,
    mrp: 36999,
    colors: ['Moonlight Pearl', 'Luxe Lavender', 'Black Beauty'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },
  {
    id: 'motorola-edge-50-pro-12gb-256gb',
    modelId: 'motorola-edge-50-pro',
    modelName: 'Motorola Edge 50 Pro',
    brand: 'Motorola',
    variantName: '12GB + 256GB (125W Charger)',
    ram: '12GB',
    storage: '256GB',
    price: 34999,
    mrp: 41999,
    colors: ['Moonlight Pearl', 'Luxe Lavender', 'Black Beauty'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },

  // Edge 50 Fusion
  {
    id: 'motorola-edge-50-fusion-8gb-128gb',
    modelId: 'motorola-edge-50-fusion',
    modelName: 'Motorola Edge 50 Fusion',
    brand: 'Motorola',
    variantName: '8GB + 128GB',
    ram: '8GB',
    storage: '128GB',
    price: 20999,
    mrp: 25999,
    colors: ['Marshmallow Blue', 'Hot Pink', 'Forest Blue'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },
  {
    id: 'motorola-edge-50-fusion-12gb-256gb',
    modelId: 'motorola-edge-50-fusion',
    modelName: 'Motorola Edge 50 Fusion',
    brand: 'Motorola',
    variantName: '12GB + 256GB',
    ram: '12GB',
    storage: '256GB',
    price: 22999,
    mrp: 27999,
    colors: ['Marshmallow Blue', 'Hot Pink', 'Forest Blue'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },

  // Edge 50 Neo
  {
    id: 'motorola-edge-50-neo-8gb-256gb',
    modelId: 'motorola-edge-50-neo',
    modelName: 'Motorola Edge 50 Neo',
    brand: 'Motorola',
    variantName: '8GB + 256GB',
    ram: '8GB',
    storage: '256GB',
    price: 22999,
    mrp: 29999,
    colors: ['Pantone Poinciana', 'Pantone Lattè', 'Pantone Grisaille', 'Pantone Nautical Blue'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },

  // Moto G85 5G
  {
    id: 'moto-g85-5g-8gb-128gb',
    modelId: 'moto-g85-5g',
    modelName: 'Moto G85 5G',
    brand: 'Motorola',
    variantName: '8GB + 128GB',
    ram: '8GB',
    storage: '128GB',
    price: 16999,
    mrp: 20999,
    colors: ['Cobalt Blue', 'Olive Green', 'Urban Grey'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },
  {
    id: 'moto-g85-5g-12gb-256gb',
    modelId: 'moto-g85-5g',
    modelName: 'Moto G85 5G',
    brand: 'Motorola',
    variantName: '12GB + 256GB',
    ram: '12GB',
    storage: '256GB',
    price: 18999,
    mrp: 22999,
    colors: ['Cobalt Blue', 'Olive Green', 'Urban Grey'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },

  // Moto G64 5G
  {
    id: 'moto-g64-5g-8gb-128gb',
    modelId: 'moto-g64-5g',
    modelName: 'Moto G64 5G',
    brand: 'Motorola',
    variantName: '8GB + 128GB',
    ram: '8GB',
    storage: '128GB',
    price: 13999,
    mrp: 17999,
    colors: ['Mint Green', 'Pearl Blue', 'Ice Lilac'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },
  {
    id: 'moto-g64-5g-12gb-256gb',
    modelId: 'moto-g64-5g',
    modelName: 'Moto G64 5G',
    brand: 'Motorola',
    variantName: '12GB + 256GB',
    ram: '12GB',
    storage: '256GB',
    price: 15999,
    mrp: 19999,
    colors: ['Mint Green', 'Pearl Blue', 'Ice Lilac'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },

  // Moto G45 5G
  {
    id: 'moto-g45-5g-4gb-128gb',
    modelId: 'moto-g45-5g',
    modelName: 'Moto G45 5G',
    brand: 'Motorola',
    variantName: '4GB + 128GB',
    ram: '4GB',
    storage: '128GB',
    price: 9999,
    mrp: 12999,
    colors: ['Brilliant Blue', 'Viva Magenta', 'Brilliant Green'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },
  {
    id: 'moto-g45-5g-8gb-128gb',
    modelId: 'moto-g45-5g',
    modelName: 'Moto G45 5G',
    brand: 'Motorola',
    variantName: '8GB + 128GB',
    ram: '8GB',
    storage: '128GB',
    price: 11999,
    mrp: 14999,
    colors: ['Brilliant Blue', 'Viva Magenta', 'Brilliant Green'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    "modelId": "motorola-edge-50-ultra",
    "modelName": "Motorola Edge 50 Ultra",
    "brand": "Motorola",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-50-ultra.jpg",
        "angle": "front",
        "source": "Motorola Official (GSMArena CDN)",
        "verified": true,
        "alt": "Motorola Edge 50 Ultra front curved pOLED display"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/motorola/motorola-edge-50-ultra-2.jpg",
        "angle": "back",
        "source": "Motorola Official (GSMArena CDN)",
        "verified": true,
        "alt": "Motorola Edge 50 Ultra Nordic Wood rear view"
      }
    ]
  },
  {
    "modelId": "motorola-edge-50-pro",
    "modelName": "Motorola Edge 50 Pro",
    "brand": "Motorola",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/motorola/motorola-edge-50-pro-01.jpg",
        "angle": "front",
        "source": "Motorola Official (GSMArena CDN)",
        "verified": true,
        "alt": "Motorola Edge 50 Pro front 144Hz display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/motorola/motorola-edge-50-pro-02.jpg",
        "angle": "back",
        "source": "Motorola Official (GSMArena CDN)",
        "verified": true,
        "alt": "Motorola Edge 50 Pro handcrafted Italian pearl rear view"
      }
    ]
  },
  {
    "modelId": "motorola-edge-50-fusion",
    "modelName": "Motorola Edge 50 Fusion",
    "brand": "Motorola",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-50-fusion.jpg",
        "angle": "front",
        "source": "Motorola Official (GSMArena CDN)",
        "verified": true,
        "alt": "Motorola Edge 50 Fusion front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/motorola/motorola-edge-50-fusion-1.jpg",
        "angle": "back",
        "source": "Motorola Official (GSMArena CDN)",
        "verified": true,
        "alt": "Motorola Edge 50 Fusion Marshmallow Blue suede rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/motorola/motorola-edge-50-fusion-2.jpg",
        "angle": "side",
        "source": "Motorola Official (GSMArena CDN)",
        "verified": true,
        "alt": "Motorola Edge 50 Fusion profile"
      }
    ]
  },
  {
    "modelId": "motorola-edge-50-neo",
    "modelName": "Motorola Edge 50 Neo",
    "brand": "Motorola",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-50-neo.jpg",
        "angle": "front",
        "source": "Motorola Official (GSMArena CDN)",
        "verified": true,
        "alt": "Motorola Edge 50 Neo front flat LTPO display"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/motorola/motorola-edge-50-neo-1.jpg",
        "angle": "back",
        "source": "Motorola Official (GSMArena CDN)",
        "verified": true,
        "alt": "Motorola Edge 50 Neo Pantone Poinciana vegan leather rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/motorola/motorola-edge-50-neo-2.jpg",
        "angle": "side",
        "source": "Motorola Official (GSMArena CDN)",
        "verified": true,
        "alt": "Motorola Edge 50 Neo profile"
      }
    ]
  },
  {
    "modelId": "moto-g85-5g",
    "modelName": "Moto G85 5G",
    "brand": "Motorola",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-g85.jpg",
        "angle": "front",
        "source": "Motorola Official (GSMArena CDN)",
        "verified": true,
        "alt": "Moto G85 5G front 3D curved pOLED display"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/motorola/motorola-moto-g85-1.jpg",
        "angle": "back",
        "source": "Motorola Official (GSMArena CDN)",
        "verified": true,
        "alt": "Moto G85 5G Olive Green vegan leather rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/motorola/motorola-moto-g85-2.jpg",
        "angle": "side",
        "source": "Motorola Official (GSMArena CDN)",
        "verified": true,
        "alt": "Moto G85 5G profile"
      }
    ]
  },
  {
    "modelId": "moto-g64-5g",
    "modelName": "Moto G64 5G",
    "brand": "Motorola",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-g64.jpg",
        "angle": "front",
        "source": "Motorola Official (GSMArena CDN)",
        "verified": true,
        "alt": "Moto G64 5G front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/motorola/motorola-moto-g64-1.jpg",
        "angle": "back",
        "source": "Motorola Official (GSMArena CDN)",
        "verified": true,
        "alt": "Moto G64 5G 6000mAh rear camera view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/motorola/motorola-moto-g64-2.jpg",
        "angle": "side",
        "source": "Motorola Official (GSMArena CDN)",
        "verified": true,
        "alt": "Moto G64 5G profile"
      }
    ]
  },
  {
    "modelId": "moto-g45-5g",
    "modelName": "Moto G45 5G",
    "brand": "Motorola",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-g45-5g.jpg",
        "angle": "front",
        "source": "Motorola Official (GSMArena CDN)",
        "verified": true,
        "alt": "Moto G45 5G front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/motorola/motorola-moto-g45-5g-1.jpg",
        "angle": "back",
        "source": "Motorola Official (GSMArena CDN)",
        "verified": true,
        "alt": "Moto G45 5G Brilliant Blue vegan leather rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/motorola/motorola-moto-g45-5g-2.jpg",
        "angle": "side",
        "source": "Motorola Official (GSMArena CDN)",
        "verified": true,
        "alt": "Moto G45 5G profile"
      }
    ]
  }
];

export const motorolaBundle: MobileBrandBundle = {
  models,
  variants,
  images,
};
