import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  // ── NOTHING ──
  {
    id: 'nothing-phone-2',
    slug: 'nothing-phone-2',
    brand: 'Nothing',
    modelName: 'Nothing Phone (2)',
    generation: 'Phone (2)',
    status: 'active',
    launchDate: '2023-07',
    pricing: {
      startingPrice: 36999,
      maximumPrice: 44999,
      launchPrice: 44999,
      currentPrice: 36999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Nothing India / Flipkart',
    },
    display: {
      displaySize: 6.7,
      displayType: 'LTPO OLED',
      resolution: '2412 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1600,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass',
      screenToBodyRatio: '87.2%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8+ Gen 1 (4nm)',
      cpu: 'Octa-core (1x3.0 GHz Cortex-X2 & 3x2.5 GHz & 4x1.8 GHz)',
      gpu: 'Adreno 730',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB', '512GB'],
      storageType: 'UFS 3.1',
      antutuScore: 1290000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 50MP) with Glyph Interface',
      mainCamera: '50 MP Sony IMX890, f/1.88, 1/1.56", OIS',
      ultrawideCamera: '50 MP Samsung JN1, f/2.2, 114˚',
      telephotoCamera: 'None',
      frontCamera: '32 MP Sony IMX615, f/2.45, 1080p@60fps',
      videoRecording: '4K@60fps, Live HDR',
      ois: true,
    },
    battery: {
      batteryCapacity: 4700,
      wiredCharging: 45,
      wirelessCharging: 15,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.1 x 76.4 x 8.6 mm',
      weight: 201.2,
      materials: '100% recycled aluminum midframe, transparent pillowed glass back with 33 Glyph LED zones',
      waterResistance: 'IP54 splash resistant',
      colors: ['Dark Grey', 'White'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Nothing OS 2.6 (Upgradable to 3.0)',
      launchOS: 'Android 13',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://in.nothing.tech/pages/phone-2',
      productPage: 'https://in.nothing.tech/products/phone-2',
      specSheetUrl: 'https://in.nothing.tech/pages/phone-2-specs',
      verifiedDate: '2023-07',
    },
  },
  {
    id: 'nothing-phone-2a-plus',
    slug: 'nothing-phone-2a-plus',
    brand: 'Nothing',
    modelName: 'Nothing Phone (2a) Plus',
    generation: 'Phone (2a)',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 27999,
      maximumPrice: 29999,
      launchPrice: 27999,
      currentPrice: 27999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Nothing India / Flipkart',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Flexible AMOLED 120Hz',
      resolution: '2412 x 1084 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1300,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '91.65%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7350 Pro 5G (4nm co-engineered)',
      cpu: 'Octa-core (2x3.0 GHz Cortex-A715 & 6x2.0 GHz Cortex-A510)',
      gpu: 'Mali-G615 MC4',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 805000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 50MP) Center Module',
      mainCamera: '50 MP Samsung GN9, f/1.88, 1/1.57", OIS',
      ultrawideCamera: '50 MP Samsung JN1, f/2.2, 114˚',
      telephotoCamera: 'None',
      frontCamera: '50 MP Samsung JN1, f/2.2, 4K30',
      videoRecording: '4K@30fps, Action Mode',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 50,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.7 x 76.3 x 8.5 mm',
      weight: 190,
      materials: 'Metallic sheen liquid aesthetic, transparent polycarbonate back with 3-part Glyph interface',
      waterResistance: 'IP54 splash resistant',
      colors: ['Metallic Grey', 'Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Nothing OS 2.6',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://in.nothing.tech/pages/phone-2a-plus',
      productPage: 'https://in.nothing.tech/products/phone-2a-plus',
      specSheetUrl: 'https://in.nothing.tech/pages/phone-2a-plus-specs',
      verifiedDate: '2024-07',
    },
  },
  {
    id: 'nothing-phone-2a',
    slug: 'nothing-phone-2a',
    brand: 'Nothing',
    modelName: 'Nothing Phone (2a)',
    generation: 'Phone (2a)',
    status: 'active',
    launchDate: '2024-03',
    pricing: {
      startingPrice: 23999,
      maximumPrice: 27999,
      launchPrice: 23999,
      currentPrice: 23999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Nothing India / Flipkart',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Flexible AMOLED 120Hz',
      resolution: '2412 x 1084 pixels',
      refreshRate: 120,
      peakBrightness: 1300,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '91.65%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7200 Pro 5G (4nm)',
      cpu: 'Octa-core (2x2.8 GHz Cortex-A715 & 6x2.0 GHz Cortex-A510)',
      gpu: 'Mali-G615 MC4',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 740000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 50MP) Center Eyes',
      mainCamera: '50 MP Samsung GN9, f/1.88, 1/1.57", OIS',
      ultrawideCamera: '50 MP Samsung JN1, f/2.2, 114˚',
      telephotoCamera: 'None',
      frontCamera: '32 MP, f/2.2, 1080p@60fps',
      videoRecording: '4K@30fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 45,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.7 x 76.3 x 8.55 mm',
      weight: 190,
      materials: 'Transparent back with horizontal dual camera eyes and 3-strip Glyph interface',
      waterResistance: 'IP54 splash resistant',
      colors: ['Black', 'White', 'Blue', 'Special Edition'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Nothing OS 2.5 (Upgraded to 3.0)',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://in.nothing.tech/pages/phone-2a',
      productPage: 'https://in.nothing.tech/products/phone-2a',
      specSheetUrl: 'https://in.nothing.tech/pages/phone-2a-specs',
      verifiedDate: '2024-03',
    },
  },
  {
    id: 'cmf-phone-1',
    slug: 'cmf-phone-1',
    brand: 'CMF',
    modelName: 'CMF Phone 1',
    generation: 'Phone 1',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 15999,
      maximumPrice: 17999,
      launchPrice: 15999,
      currentPrice: 15999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'CMF by Nothing India / Flipkart',
    },
    display: {
      displaySize: 6.67,
      displayType: 'Super AMOLED 120Hz',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 2000,
      hdr: 'Ultra HDR',
      protection: 'Glass front',
      screenToBodyRatio: '87.0%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7300 5G (4nm)',
      cpu: 'Octa-core (4x2.5 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G615 MC2',
      ramOptions: ['6GB', '8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 665000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP)',
      mainCamera: '50 MP Sony, f/1.8',
      ultrawideCamera: 'None',
      telephotoCamera: 'None (2 MP portrait)',
      frontCamera: '16 MP, f/2.0',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 33,
      wirelessCharging: 0,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM hybrid',
    },
    physical: {
      dimensions: '164 x 77 x 8 mm',
      weight: 197,
      materials: 'Modular interchangeable back cover with visible stainless steel screws and accessory point dial',
      waterResistance: 'IP52 splash resistant',
      colors: ['Black', 'Orange', 'Light Green', 'Blue'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Nothing OS 2.6',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://in.nothing.tech/pages/cmf-phone-1',
      productPage: 'https://in.nothing.tech/products/cmf-phone-1',
      specSheetUrl: 'https://in.nothing.tech/pages/cmf-phone-1-specs',
      verifiedDate: '2024-07',
    },
  },

  // ── ASUS ──
  {
    id: 'asus-rog-phone-8-pro',
    slug: 'asus-rog-phone-8-pro',
    brand: 'ASUS',
    modelName: 'ROG Phone 8 Pro',
    generation: 'ROG 8',
    status: 'active',
    launchDate: '2024-01',
    pricing: {
      startingPrice: 94999,
      maximumPrice: 119999,
      launchPrice: 94999,
      currentPrice: 94999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'ASUS India / Vijay Sales',
    },
    display: {
      displaySize: 6.78,
      displayType: 'Samsung E6 165Hz Flexible LTPO AMOLED',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 165,
      peakBrightness: 2500,
      hdr: 'HDR10',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '94.0%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Gen 3 (4nm)',
      cpu: 'Octa-core (1x3.3 GHz Cortex-X4 & 5x3.2 GHz & 2x2.3 GHz)',
      gpu: 'Adreno 750',
      ramOptions: ['16GB', '24GB'],
      storageOptions: ['512GB', '1TB'],
      storageType: 'UFS 4.0',
      antutuScore: 2210000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 32MP + 13MP) with 6-Axis Hybrid Gimbal Stabilizer',
      mainCamera: '50 MP Sony IMX890, f/1.9, 6-Axis Hybrid Gimbal Stabilizer 3.0',
      ultrawideCamera: '13 MP, f/2.2, 120˚ free-form lens',
      telephotoCamera: '32 MP, f/2.4, 3x optical zoom, OIS',
      frontCamera: '32 MP RGBW, f/2.05',
      videoRecording: '8K@24fps, 4K@60fps with Gimbal EIS',
      ois: true,
    },
    battery: {
      batteryCapacity: 5500,
      wiredCharging: 65,
      wirelessCharging: 15,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'Dual USB Type-C (Side-mounted USB 3.1 DP + Bottom USB 2.0)',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '163.8 x 76.8 x 8.9 mm',
      weight: 225,
      materials: 'Aluminum frame, AniMe Vision 341 mini-LED programmable matrix back',
      waterResistance: 'IP68 water and dust resistant',
      colors: ['Phantom Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'ROG UI / ZenUI (dual mode)',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual front-facing stereo speakers with Dirac Virtuo',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://rog.asus.com/in/phones/rog-phone-8-pro/',
      productPage: 'https://in.store.asus.com/rog-phone-8-pro.html',
      specSheetUrl: 'https://rog.asus.com/in/phones/rog-phone-8-pro/spec/',
      verifiedDate: '2024-01',
    },
  },
  {
    id: 'asus-rog-phone-9-pro',
    slug: 'asus-rog-phone-9-pro',
    brand: 'ASUS',
    modelName: 'ROG Phone 9 Pro',
    generation: 'ROG 9',
    status: 'active',
    launchDate: '2024-11',
    pricing: {
      startingPrice: 99999,
      maximumPrice: 129999,
      launchPrice: 99999,
      currentPrice: 99999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'ASUS India / Vijay Sales',
    },
    display: {
      displaySize: 6.78,
      displayType: 'Samsung E6 185Hz Flexible LTPO AMOLED',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 185,
      peakBrightness: 2500,
      hdr: 'HDR10',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '94.0%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Elite (3nm Oryon)',
      cpu: 'Octa-core (2x4.32 GHz Oryon Phoenix L & 6x3.53 GHz Oryon Phoenix M)',
      gpu: 'Adreno 830',
      ramOptions: ['16GB', '24GB'],
      storageOptions: ['512GB', '1TB'],
      storageType: 'UFS 4.0',
      antutuScore: 3120000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 32MP + 13MP) with 6-Axis Hybrid Gimbal 4.0',
      mainCamera: '50 MP Sony LYT-700, f/1.9, 6-Axis Hybrid Gimbal Stabilizer 4.0',
      ultrawideCamera: '13 MP, f/2.2, 120˚',
      telephotoCamera: '32 MP, f/2.4, 3x optical zoom, OIS',
      frontCamera: '32 MP RGBW, f/2.05',
      videoRecording: '8K@30fps, 4K@60/120fps with Gimbal EIS',
      ois: true,
    },
    battery: {
      batteryCapacity: 5800,
      wiredCharging: 65,
      wirelessCharging: 15,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'Dual USB Type-C (Side-mounted USB 3.2 Gen 2 DP + Bottom USB 2.0)',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '163.8 x 76.8 x 8.9 mm',
      weight: 227,
      materials: 'AniMe Vision 648 mini-LED programmable matrix with retro gaming interaction',
      waterResistance: 'IP68 water and dust resistant',
      colors: ['Phantom Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'ROG UI (Android 15)',
      launchOS: 'Android 15',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '5 years',
    },
    audio: {
      speakers: 'Dual front-facing stereo speakers with Dirac Virtuo & subwoofer in AeroActive Cooler X',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://rog.asus.com/in/phones/rog-phone-9-pro/',
      productPage: 'https://in.store.asus.com/rog-phone-9-pro.html',
      specSheetUrl: 'https://rog.asus.com/in/phones/rog-phone-9-pro/spec/',
      verifiedDate: '2024-11',
    },
  },
];

const variants: MobileVariant[] = [
  // Nothing Phone (2)
  {
    id: 'nothing-phone-2-8gb-128gb',
    modelId: 'nothing-phone-2',
    modelName: 'Nothing Phone (2)',
    brand: 'Nothing',
    variantName: '8GB + 128GB',
    ram: '8GB',
    storage: '128GB',
    price: 36999,
    mrp: 44999,
    colors: ['Dark Grey', 'White'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },
  {
    id: 'nothing-phone-2-12gb-256gb',
    modelId: 'nothing-phone-2',
    modelName: 'Nothing Phone (2)',
    brand: 'Nothing',
    variantName: '12GB + 256GB',
    ram: '12GB',
    storage: '256GB',
    price: 39999,
    mrp: 49999,
    colors: ['Dark Grey', 'White'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },
  {
    id: 'nothing-phone-2-12gb-512gb',
    modelId: 'nothing-phone-2',
    modelName: 'Nothing Phone (2)',
    brand: 'Nothing',
    variantName: '12GB + 512GB',
    ram: '12GB',
    storage: '512GB',
    price: 44999,
    mrp: 54999,
    colors: ['Dark Grey', 'White'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },

  // Nothing Phone (2a) Plus
  {
    id: 'nothing-phone-2a-plus-8gb-256gb',
    modelId: 'nothing-phone-2a-plus',
    modelName: 'Nothing Phone (2a) Plus',
    brand: 'Nothing',
    variantName: '8GB + 256GB',
    ram: '8GB',
    storage: '256GB',
    price: 27999,
    mrp: 29999,
    colors: ['Metallic Grey', 'Black'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },
  {
    id: 'nothing-phone-2a-plus-12gb-256gb',
    modelId: 'nothing-phone-2a-plus',
    modelName: 'Nothing Phone (2a) Plus',
    brand: 'Nothing',
    variantName: '12GB + 256GB',
    ram: '12GB',
    storage: '256GB',
    price: 29999,
    mrp: 31999,
    colors: ['Metallic Grey', 'Black'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },

  // Nothing Phone (2a)
  {
    id: 'nothing-phone-2a-8gb-128gb',
    modelId: 'nothing-phone-2a',
    modelName: 'Nothing Phone (2a)',
    brand: 'Nothing',
    variantName: '8GB + 128GB',
    ram: '8GB',
    storage: '128GB',
    price: 23999,
    mrp: 25999,
    colors: ['Black', 'White', 'Blue'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },
  {
    id: 'nothing-phone-2a-8gb-256gb',
    modelId: 'nothing-phone-2a',
    modelName: 'Nothing Phone (2a)',
    brand: 'Nothing',
    variantName: '8GB + 256GB',
    ram: '8GB',
    storage: '256GB',
    price: 25999,
    mrp: 27999,
    colors: ['Black', 'White', 'Blue'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },
  {
    id: 'nothing-phone-2a-12gb-256gb',
    modelId: 'nothing-phone-2a',
    modelName: 'Nothing Phone (2a)',
    brand: 'Nothing',
    variantName: '12GB + 256GB',
    ram: '12GB',
    storage: '256GB',
    price: 27999,
    mrp: 29999,
    colors: ['Black', 'White', 'Special Edition'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },

  // CMF Phone 1
  {
    id: 'cmf-phone-1-6gb-128gb',
    modelId: 'cmf-phone-1',
    modelName: 'CMF Phone 1',
    brand: 'CMF',
    variantName: '6GB + 128GB',
    ram: '6GB',
    storage: '128GB',
    price: 15999,
    mrp: 19999,
    colors: ['Black', 'Orange', 'Light Green'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },
  {
    id: 'cmf-phone-1-8gb-128gb',
    modelId: 'cmf-phone-1',
    modelName: 'CMF Phone 1',
    brand: 'CMF',
    variantName: '8GB + 128GB',
    ram: '8GB',
    storage: '128GB',
    price: 17999,
    mrp: 21999,
    colors: ['Black', 'Orange', 'Light Green', 'Blue'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },

  // ASUS ROG Phone 8 Pro
  {
    id: 'asus-rog-phone-8-pro-16gb-512gb',
    modelId: 'asus-rog-phone-8-pro',
    modelName: 'ROG Phone 8 Pro',
    brand: 'ASUS',
    variantName: '16GB + 512GB',
    ram: '16GB',
    storage: '512GB',
    price: 94999,
    mrp: 104999,
    colors: ['Phantom Black'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },
  {
    id: 'asus-rog-phone-8-pro-24gb-1tb',
    modelId: 'asus-rog-phone-8-pro',
    modelName: 'ROG Phone 8 Pro',
    brand: 'ASUS',
    variantName: '24GB + 1TB',
    ram: '24GB',
    storage: '1TB',
    price: 119999,
    mrp: 129999,
    colors: ['Phantom Black'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },

  // ASUS ROG Phone 9 Pro
  {
    id: 'asus-rog-phone-9-pro-16gb-512gb',
    modelId: 'asus-rog-phone-9-pro',
    modelName: 'ROG Phone 9 Pro',
    brand: 'ASUS',
    variantName: '16GB + 512GB',
    ram: '16GB',
    storage: '512GB',
    price: 99999,
    mrp: 119999,
    colors: ['Phantom Black'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },
  {
    id: 'asus-rog-phone-9-pro-24gb-1tb',
    modelId: 'asus-rog-phone-9-pro',
    modelName: 'ROG Phone 9 Pro',
    brand: 'ASUS',
    variantName: '24GB + 1TB',
    ram: '24GB',
    storage: '1TB',
    price: 129999,
    mrp: 149999,
    colors: ['Phantom Black'],
    connectivity: '5G',
    inStock: true,
    verified: true,
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    "modelId": "nothing-phone-2",
    "modelName": "Nothing Phone (2)",
    "brand": "Nothing",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-2.jpg",
        "angle": "front",
        "source": "Nothing Tech Official Assets",
        "verified": true,
        "alt": "Nothing Phone (2) front LTPO OLED display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/nothing/nothing-phone2-1_.jpg",
        "angle": "back",
        "source": "Nothing Tech Official Assets",
        "verified": true,
        "alt": "Nothing Phone (2) transparent Glyph back view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/nothing/nothing-phone2-2.jpg",
        "angle": "side",
        "source": "Nothing Tech Official Assets",
        "verified": true,
        "alt": "Nothing Phone (2) aluminum frame side view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/nothing/nothing-phone2-3.jpg",
        "angle": "display",
        "source": "Nothing Tech Official Assets",
        "verified": true,
        "alt": "Nothing Phone (2) OLED display view"
      }
    ]
  },
  {
    "modelId": "nothing-phone-2a-plus",
    "modelName": "Nothing Phone (2a) Plus",
    "brand": "Nothing",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-2a-plus.jpg",
        "angle": "front",
        "source": "Nothing Tech Official Assets",
        "verified": true,
        "alt": "Nothing Phone (2a) Plus front view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/nothing/nothing-phone-2a-1.jpg",
        "angle": "back",
        "source": "Nothing Tech Official Assets",
        "verified": true,
        "alt": "Nothing Phone (2a) Plus metallic back view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/nothing/nothing-phone-2a-2.jpg",
        "angle": "side",
        "source": "Nothing Tech Official Assets",
        "verified": true,
        "alt": "Nothing Phone (2a) Plus side profile view"
      }
    ]
  },
  {
    "modelId": "nothing-phone-2a",
    "modelName": "Nothing Phone (2a)",
    "brand": "CMF",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-2a.jpg",
        "angle": "front",
        "source": "Nothing Tech Official Assets",
        "verified": true,
        "alt": "Nothing Phone (2a) front view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/nothing/nothing-phone-2a-1.jpg",
        "angle": "back",
        "source": "Nothing Tech Official Assets",
        "verified": true,
        "alt": "Nothing Phone (2a) transparent eyes rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/nothing/nothing-phone-2a-3.jpg",
        "angle": "side",
        "source": "Nothing Tech Official Assets",
        "verified": true,
        "alt": "Nothing Phone (2a) side profile view"
      }
    ]
  },
  {
    "modelId": "cmf-phone-1",
    "modelName": "CMF Phone 1",
    "brand": "ASUS",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/nothing/nothing-cmf-phone-1-01.jpg",
        "angle": "front",
        "source": "Nothing CMF Official (GSMArena CDN)",
        "verified": true,
        "alt": "CMF Phone 1 front AMOLED display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/nothing/nothing-cmf-phone-1-02.jpg",
        "angle": "back",
        "source": "Nothing CMF Official (GSMArena CDN)",
        "verified": true,
        "alt": "CMF Phone 1 interchangeable modular case rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/nothing/nothing-cmf-phone-1-03.jpg",
        "angle": "side",
        "source": "Nothing CMF Official (GSMArena CDN)",
        "verified": true,
        "alt": "CMF Phone 1 profile and Accessory Point view"
      }
    ]
  },
  {
    "modelId": "asus-rog-phone-8-pro",
    "modelName": "ROG Phone 8 Pro",
    "brand": "ASUS",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/asus-rog-phone-8-pro.jpg",
        "angle": "front",
        "source": "ASUS ROG Official (GSMArena CDN)",
        "verified": true,
        "alt": "ASUS ROG Phone 8 Pro front 165Hz AMOLED display"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/asus/asus-rog-phone-8-pro-1.jpg",
        "angle": "back",
        "source": "ASUS ROG Official (GSMArena CDN)",
        "verified": true,
        "alt": "ASUS ROG Phone 8 Pro AniMe Matrix mini-LED rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/asus/asus-rog-phone-8-pro-2.jpg",
        "angle": "side",
        "source": "ASUS ROG Official (GSMArena CDN)",
        "verified": true,
        "alt": "ASUS ROG Phone 8 Pro AirTrigger profile"
      }
    ]
  },
  {
    "modelId": "asus-rog-phone-9-pro",
    "modelName": "ROG Phone 9 Pro",
    "brand": "Nothing",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/asus-rog-phone-9-pro.jpg",
        "angle": "front",
        "source": "ASUS ROG Official (GSMArena CDN)",
        "verified": true,
        "alt": "ASUS ROG Phone 9 Pro front 185Hz display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/asus/asus-rog-phone-9-pro-1.jpg",
        "angle": "back",
        "source": "ASUS ROG Official (GSMArena CDN)",
        "verified": true,
        "alt": "ASUS ROG Phone 9 Pro AniMe Vision rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/asus/asus-rog-phone-9-pro-2.jpg",
        "angle": "side",
        "source": "ASUS ROG Official (GSMArena CDN)",
        "verified": true,
        "alt": "ASUS ROG Phone 9 Pro gaming trigger profile"
      }
    ]
  }
];

export const nothingAsusBundle: MobileBrandBundle = {
  models,
  variants,
  images,
};
