import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  {
    id: 'nothing-phone-2',
    slug: 'nothing-phone-2',
    brand: 'Nothing',
    modelName: 'Nothing Phone (2)',
    generation: 'Phone (2)',
    status: 'active',
    launchDate: '2023-07',
    pricing: {
      startingPrice: 36999,
      maximumPrice: 44999,
      launchPrice: 44999,
      currentPrice: 36999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Nothing India / Flipkart',
    },
    display: {
      displaySize: 6.7,
      displayType: 'LTPO OLED',
      resolution: '2412 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1600,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass',
      screenToBodyRatio: '87.2%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8+ Gen 1 (4nm)',
      cpu: 'Octa-core (1x3.0 GHz Cortex-X2 & 3x2.5 GHz & 4x1.8 GHz)',
      gpu: 'Adreno 730',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB', '512GB'],
      storageType: 'UFS 3.1',
      antutuScore: 1290000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 50MP) with Glyph Interface',
      mainCamera: '50 MP Sony IMX890, f/1.88, 1/1.56", OIS',
      ultrawideCamera: '50 MP Samsung JN1, f/2.2, 114˚',
      telephotoCamera: 'None',
      frontCamera: '32 MP Sony IMX615, f/2.45, 1080p@60fps',
      videoRecording: '4K@60fps, Live HDR',
      ois: true,
    },
    battery: {
      batteryCapacity: 4700,
      wiredCharging: 45,
      wirelessCharging: 15,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.1 x 76.4 x 8.6 mm',
      weight: 201.2,
      materials: 'Corning Gorilla Glass transparent back, 100% recycled aluminum midframe',
      waterResistance: 'IP54 splash resistant',
      colors: ['White', 'Dark Grey'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Nothing OS 2.5',
      launchOS: 'Android 13',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'In-display optical',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://in.nothing.tech/pages/phone-2',
      productPage: 'https://www.flipkart.com/nothing-phone-2-store',
      specSheetUrl: 'https://in.nothing.tech/pages/phone-2',
      verifiedDate: '2023-07',
    },
  },
  {
    id: 'nothing-phone-2a-plus',
    slug: 'nothing-phone-2a-plus',
    brand: 'Nothing',
    modelName: 'Nothing Phone (2a) Plus',
    generation: 'Phone (2a)',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 27999,
      maximumPrice: 29999,
      launchPrice: 27999,
      currentPrice: 27999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Nothing India / Flipkart',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Flexible AMOLED, 1.07B colors, 120Hz',
      resolution: '2412 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1300,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '87.6%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7350 Pro 5G (4nm)',
      cpu: 'Octa-core (2x3.0 GHz Cortex-A715 & 6x2.0 GHz Cortex-A510)',
      gpu: 'Mali-G610 MC4',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 805000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 50MP) with Glyph Interface',
      mainCamera: '50 MP Samsung GN9, f/1.88, 1/1.57", OIS + EIS',
      ultrawideCamera: '50 MP Samsung JN1, f/2.2, 114˚',
      telephotoCamera: 'None',
      frontCamera: '50 MP Samsung JN1, f/2.2, 4K30 video',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 50,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.7 x 76.3 x 8.5 mm',
      weight: 190,
      materials: 'Transparent plastic back with metallic finish, plastic frame',
      waterResistance: 'IP54 dust and splash resistant',
      colors: ['Metallic Grey', 'Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Nothing OS 2.6',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'In-display optical',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://in.nothing.tech/pages/phone-2a-plus',
      productPage: 'https://www.flipkart.com/nothing-phone-2a-plus-store',
      specSheetUrl: 'https://in.nothing.tech/pages/phone-2a-plus',
      verifiedDate: '2024-07',
    },
  },
  {
    id: 'nothing-phone-2a',
    slug: 'nothing-phone-2a',
    brand: 'Nothing',
    modelName: 'Nothing Phone (2a)',
    generation: 'Phone (2a)',
    status: 'active',
    launchDate: '2024-03',
    pricing: {
      startingPrice: 23999,
      maximumPrice: 27999,
      launchPrice: 23999,
      currentPrice: 23999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Nothing India / Flipkart',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Flexible AMOLED, 1B colors, 120Hz',
      resolution: '2412 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1300,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '87.6%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7200 Pro (4nm)',
      cpu: 'Octa-core (2x2.8 GHz Cortex-A715 & 6x2.0 GHz Cortex-A510)',
      gpu: 'Mali-G610 MC4',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 740000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 50MP) with Glyph Interface',
      mainCamera: '50 MP Samsung GN9, f/1.88, 1/1.57", OIS + EIS',
      ultrawideCamera: '50 MP Samsung JN1, f/2.2, 114˚',
      telephotoCamera: 'None',
      frontCamera: '32 MP Sony IMX615, f/2.2, 1080p@60fps',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 45,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.7 x 76.3 x 8.55 mm',
      weight: 190,
      materials: 'Transparent polycarbonate back, plastic frame',
      waterResistance: 'IP54 dust and splash resistant',
      colors: ['Black', 'White', 'Milk', 'Special Edition'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Nothing OS 2.5',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'In-display optical',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://in.nothing.tech/pages/phone-2a',
      productPage: 'https://www.flipkart.com/nothing-phone-2a-store',
      specSheetUrl: 'https://in.nothing.tech/pages/phone-2a',
      verifiedDate: '2024-03',
    },
  },
  {
    id: 'nothing-phone-1',
    slug: 'nothing-phone-1',
    brand: 'Nothing',
    modelName: 'Nothing Phone (1)',
    generation: 'Phone (1)',
    status: 'discontinued',
    launchDate: '2022-07',
    pricing: {
      startingPrice: 27999,
      maximumPrice: 33999,
      launchPrice: 32999,
      currentPrice: 27999,
      currency: 'INR',
      priceEffectiveDate: '2023-07',
      source: 'Nothing India Archive / Flipkart',
    },
    display: {
      displaySize: 6.55,
      displayType: 'Flexible OLED, 1B colors, 120Hz',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1200,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '85.8%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 778G+ 5G (6nm)',
      cpu: 'Octa-core (1x2.5 GHz Cortex-A78 & 3x2.4 GHz Cortex-A78 & 4x1.8 GHz Cortex-A55)',
      gpu: 'Adreno 642L',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 605000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 50MP) with Glyph Interface',
      mainCamera: '50 MP Sony IMX766, f/1.88, 1/1.56", OIS',
      ultrawideCamera: '50 MP Samsung JN1, f/2.2, 114˚, AF, macro',
      telephotoCamera: 'None',
      frontCamera: '16 MP Sony IMX471, f/2.45, 1080p@30fps',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4500,
      wiredCharging: 33,
      wirelessCharging: 15,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '159.2 x 75.8 x 8.3 mm',
      weight: 193.5,
      materials: 'Transparent Gorilla Glass 5 back, 100% recycled aluminum frame',
      waterResistance: 'IP53 splash resistant',
      colors: ['White', 'Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Nothing OS',
      launchOS: 'Android 12',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'In-display optical',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://in.nothing.tech/pages/phone-1',
      productPage: 'https://www.flipkart.com/nothing-phone-1-store',
      specSheetUrl: 'https://in.nothing.tech/pages/phone-1',
      verifiedDate: '2022-07',
    },
  },
];

const variants: MobileVariant[] = [
  // Phone (2)
  {
    id: 'nothing-phone-2-8gb-128gb',
    modelId: 'nothing-phone-2',
    name: 'Nothing Phone (2) (8GB RAM, 128GB)',
    ram: '8GB',
    storage: '128GB',
    color: 'Dark Grey',
    price: 36999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  {
    id: 'nothing-phone-2-12gb-256gb',
    modelId: 'nothing-phone-2',
    name: 'Nothing Phone (2) (12GB RAM, 256GB)',
    ram: '12GB',
    storage: '256GB',
    color: 'White',
    price: 39999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  {
    id: 'nothing-phone-2-12gb-512gb',
    modelId: 'nothing-phone-2',
    name: 'Nothing Phone (2) (12GB RAM, 512GB)',
    ram: '12GB',
    storage: '512GB',
    color: 'Dark Grey',
    price: 44999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Phone (2a) Plus
  {
    id: 'nothing-phone-2a-plus-8gb-256gb',
    modelId: 'nothing-phone-2a-plus',
    name: 'Nothing Phone (2a) Plus (8GB RAM, 256GB)',
    ram: '8GB',
    storage: '256GB',
    color: 'Metallic Grey',
    price: 27999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  {
    id: 'nothing-phone-2a-plus-12gb-256gb',
    modelId: 'nothing-phone-2a-plus',
    name: 'Nothing Phone (2a) Plus (12GB RAM, 256GB)',
    ram: '12GB',
    storage: '256GB',
    color: 'Black',
    price: 29999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Phone (2a)
  {
    id: 'nothing-phone-2a-8gb-128gb',
    modelId: 'nothing-phone-2a',
    name: 'Nothing Phone (2a) (8GB RAM, 128GB)',
    ram: '8GB',
    storage: '128GB',
    color: 'Black',
    price: 23999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  {
    id: 'nothing-phone-2a-8gb-256gb',
    modelId: 'nothing-phone-2a',
    name: 'Nothing Phone (2a) (8GB RAM, 256GB)',
    ram: '8GB',
    storage: '256GB',
    color: 'White',
    price: 25999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  {
    id: 'nothing-phone-2a-12gb-256gb',
    modelId: 'nothing-phone-2a',
    name: 'Nothing Phone (2a) (12GB RAM, 256GB)',
    ram: '12GB',
    storage: '256GB',
    color: 'Special Edition',
    price: 27999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Phone (1)
  {
    id: 'nothing-phone-1-8gb-128gb',
    modelId: 'nothing-phone-1',
    name: 'Nothing Phone (1) (8GB RAM, 128GB)',
    ram: '8GB',
    storage: '128GB',
    color: 'Black',
    price: 27999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  {
    id: 'nothing-phone-1-8gb-256gb',
    modelId: 'nothing-phone-1',
    name: 'Nothing Phone (1) (8GB RAM, 256GB)',
    ram: '8GB',
    storage: '256GB',
    color: 'White',
    price: 29999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  {
    id: 'nothing-phone-1-12gb-256gb',
    modelId: 'nothing-phone-1',
    name: 'Nothing Phone (1) (12GB RAM, 256GB)',
    ram: '12GB',
    storage: '256GB',
    color: 'Black',
    price: 33999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    modelId: 'nothing-phone-2',
    modelName: 'Nothing Phone (2)',
    brand: 'Nothing',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-2.jpg',
        angle: 'front',
        source: 'Nothing Official (GSMArena CDN)',
        sourceUrl: 'https://in.nothing.tech/pages/phone-2',
        verified: true,
        alt: 'Nothing Phone (2) front transparent view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/nothing/nothing-phone-2-1.jpg',
        angle: 'back',
        source: 'Nothing Official (GSMArena CDN)',
        sourceUrl: 'https://in.nothing.tech/pages/phone-2',
        verified: true,
        alt: 'Nothing Phone (2) Glyph interface transparent rear view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/nothing/nothing-phone-2-2.jpg',
        angle: 'side',
        source: 'Nothing Official (GSMArena CDN)',
        sourceUrl: 'https://in.nothing.tech/pages/phone-2',
        verified: true,
        alt: 'Nothing Phone (2) recycled aluminum profile',
      },
    ],
  },
  {
    modelId: 'nothing-phone-2a-plus',
    modelName: 'Nothing Phone (2a) Plus',
    brand: 'Nothing',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-2a-plus.jpg',
        angle: 'front',
        source: 'Nothing Official (GSMArena CDN)',
        sourceUrl: 'https://in.nothing.tech/pages/phone-2a-plus',
        verified: true,
        alt: 'Nothing Phone (2a) Plus front AMOLED display view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/nothing/nothing-phone-2a-plus-01.jpg',
        angle: 'back',
        source: 'Nothing Official (GSMArena CDN)',
        sourceUrl: 'https://in.nothing.tech/pages/phone-2a-plus',
        verified: true,
        alt: 'Nothing Phone (2a) Plus metallic Glyph rear view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/nothing/nothing-phone-2a-plus-02.jpg',
        angle: 'side',
        source: 'Nothing Official (GSMArena CDN)',
        sourceUrl: 'https://in.nothing.tech/pages/phone-2a-plus',
        verified: true,
        alt: 'Nothing Phone (2a) Plus profile view',
      },
    ],
  },
  {
    modelId: 'nothing-phone-2a',
    modelName: 'Nothing Phone (2a)',
    brand: 'Nothing',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-2a.jpg',
        angle: 'front',
        source: 'Nothing Official (GSMArena CDN)',
        sourceUrl: 'https://in.nothing.tech/pages/phone-2a',
        verified: true,
        alt: 'Nothing Phone (2a) front flexible AMOLED view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/nothing/nothing-phone-2a-01.jpg',
        angle: 'back',
        source: 'Nothing Official (GSMArena CDN)',
        sourceUrl: 'https://in.nothing.tech/pages/phone-2a',
        verified: true,
        alt: 'Nothing Phone (2a) centered camera Glyph rear view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/nothing/nothing-phone-2a-02.jpg',
        angle: 'side',
        source: 'Nothing Official (GSMArena CDN)',
        sourceUrl: 'https://in.nothing.tech/pages/phone-2a',
        verified: true,
        alt: 'Nothing Phone (2a) polycarbonate profile',
      },
    ],
  },
  {
    modelId: 'nothing-phone-1',
    modelName: 'Nothing Phone (1)',
    brand: 'Nothing',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-1.jpg',
        angle: 'front',
        source: 'Nothing Official (GSMArena CDN)',
        sourceUrl: 'https://in.nothing.tech/pages/phone-1',
        verified: true,
        alt: 'Nothing Phone (1) front display view',
      },
    ],
  },
];

export const nothingBundle: MobileBrandBundle = {
  brand: 'Nothing',
  models,
  variants,
  images,
};
