import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  {
    id: 'oneplus-13',
    slug: 'oneplus-13',
    brand: 'OnePlus',
    modelName: 'OnePlus 13',
    generation: '13',
    status: 'active',
    launchDate: '2025-01',
    pricing: {
      startingPrice: 69999,
      maximumPrice: 89999,
      launchPrice: 69999,
      currentPrice: 69999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'OnePlus India Official Store',
    },
    display: {
      displaySize: 6.82,
      displayType: 'BOE X2 2K Oriental LTPO AMOLED',
      resolution: '3168 x 1440 pixels (QHD+)',
      refreshRate: 120,
      peakBrightness: 4500,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Crystal Shield Super Ceramic Glass',
      screenToBodyRatio: '90.7%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Elite (3nm)',
      cpu: 'Octa-core (2x4.32 GHz Oryon V2 Phoenix & 6x3.53 GHz)',
      gpu: 'Adreno 830',
      ramOptions: ['12GB', '16GB', '24GB'],
      storageOptions: ['256GB', '512GB', '1TB'],
      storageType: 'UFS 4.0',
      antutuScore: 2920000,
      geekbenchSingle: 3150,
      geekbenchMulti: 9750,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 50MP) Hasselblad',
      mainCamera: '50 MP Sony LYT-808, f/1.6, 23mm, 1/1.4", PDAF, OIS',
      ultrawideCamera: '50 MP Samsung JN5, f/2.0, 15mm, 120˚',
      telephotoCamera: '50 MP Sony LYT-600 periscope, f/2.6, 73mm, 3x optical zoom, OIS',
      frontCamera: '32 MP, f/2.4, 21mm, 4K60',
      videoRecording: '8K@30fps, 4K@30/60fps, Dolby Vision HDR',
      ois: true,
    },
    battery: {
      batteryCapacity: 6000,
      wiredCharging: 100,
      wirelessCharging: 50,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7 (802.11be)',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 3.2 Gen 1, OTG',
      simConfig: 'Dual SIM (Nano-SIM)',
    },
    physical: {
      dimensions: '162.9 x 76.5 x 8.5 mm',
      weight: 213,
      materials: 'Aluminum frame, Velvet Glass or microfiber leather back',
      waterResistance: 'IP68 and IP69 water and dust resistance',
      colors: ['Midnight Ocean', 'Black Eclipse', 'Arctic Dawn'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'OxygenOS 15',
      launchOS: 'Android 15',
      promisedMajorUpdates: 4,
      securityUpdatePolicy: '6 years of security patches',
    },
    audio: {
      speakers: 'Dual stereo speakers with spatial audio',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Ultrasonic under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.oneplus.in/13',
      productPage: 'https://www.oneplus.in/buy-oneplus-13',
      specSheetUrl: 'https://www.oneplus.in/13/specs',
      verifiedDate: '2025-01',
    },
  },

  {
    id: 'oneplus-13r',
    slug: 'oneplus-13r',
    brand: 'OnePlus',
    modelName: 'OnePlus 13R',
    generation: '13R',
    status: 'active',
    launchDate: '2025-01',
    pricing: {
      startingPrice: 42999,
      maximumPrice: 49999,
      launchPrice: 42999,
      currentPrice: 42999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'OnePlus India Official Store',
    },
    display: {
      displaySize: 6.78,
      displayType: '1.5K LTPO AMOLED',
      resolution: '2780 x 1264 pixels',
      refreshRate: 120,
      peakBrightness: 4500,
      hdr: 'HDR10+, Dolby Vision',
      protection: 'Corning Gorilla Glass 7i',
      screenToBodyRatio: '90.2%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Gen 3 (4nm)',
      cpu: 'Octa-core (1x3.3 GHz Cortex-X4 & 5x3.2 GHz & 2x2.3 GHz)',
      gpu: 'Adreno 750',
      ramOptions: ['12GB', '16GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 2150000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 8MP + 50MP)',
      mainCamera: '50 MP Sony LYT-700, f/1.8, OIS',
      ultrawideCamera: '8 MP, f/2.2, 112˚',
      telephotoCamera: '50 MP Telephoto, 2x/3x portrait',
      frontCamera: '16 MP, f/2.4',
      videoRecording: '4K@60fps, 1080p@240fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 6000,
      wiredCharging: 80,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.7 x 75.8 x 8.0 mm',
      weight: 202,
      materials: 'Aluminum alloy frame, glass back',
      waterResistance: 'IP65',
      colors: ['Nebula Noir', 'Astral Trail'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'OxygenOS 15',
      launchOS: 'Android 15',
      promisedMajorUpdates: 4,
      securityUpdatePolicy: '6 years of security patches',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.oneplus.in/13r',
      productPage: 'https://www.oneplus.in/buy-oneplus-13r',
      specSheetUrl: 'https://www.oneplus.in/13r/specs',
      verifiedDate: '2025-01',
    },
  },

  {
    id: 'oneplus-12',
    slug: 'oneplus-12',
    brand: 'OnePlus',
    modelName: 'OnePlus 12',
    generation: '12',
    status: 'active',
    launchDate: '2024-01',
    pricing: {
      startingPrice: 59999,
      maximumPrice: 64999,
      launchPrice: 64999,
      currentPrice: 59999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'OnePlus India Official Store',
    },
    display: {
      displaySize: 6.82,
      displayType: '2K 120Hz ProXDR LTPO AMOLED',
      resolution: '3168 x 1440 pixels',
      refreshRate: 120,
      peakBrightness: 4500,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '90.8%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Gen 3 (4nm)',
      cpu: 'Octa-core (1x3.3 GHz Cortex-X4 & 5x3.2 GHz & 2x2.3 GHz)',
      gpu: 'Adreno 750',
      ramOptions: ['12GB', '16GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 2110000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 48MP + 64MP) Hasselblad',
      mainCamera: '50 MP Sony LYT-808, f/1.6, OIS',
      ultrawideCamera: '48 MP Sony IMX581, f/2.2, 114˚',
      telephotoCamera: '64 MP OmniVision OV64B periscope, f/2.6, 3x optical, OIS',
      frontCamera: '32 MP, f/2.4, 4K30',
      videoRecording: '8K@24fps, 4K@60fps Dolby Vision',
      ois: true,
    },
    battery: {
      batteryCapacity: 5400,
      wiredCharging: 100,
      wirelessCharging: 50,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 3.2 Gen 1',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '164.3 x 75.8 x 9.15 mm',
      weight: 220,
      materials: 'Aluminum frame, Corning Gorilla Glass back',
      waterResistance: 'IP65',
      colors: ['Silky Black', 'Flowy Emerald', 'Glacial White'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'OxygenOS 14 (Upgradable to 15)',
      launchOS: 'Android 14',
      promisedMajorUpdates: 4,
      securityUpdatePolicy: '5 years of security patches',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.oneplus.in/12',
      productPage: 'https://www.oneplus.in/buy-oneplus-12',
      specSheetUrl: 'https://www.oneplus.in/12/specs',
      verifiedDate: '2024-01',
    },
  },

  {
    id: 'oneplus-12r',
    slug: 'oneplus-12r',
    brand: 'OnePlus',
    modelName: 'OnePlus 12R',
    generation: '12R',
    status: 'active',
    launchDate: '2024-01',
    pricing: {
      startingPrice: 35999,
      maximumPrice: 42999,
      launchPrice: 39999,
      currentPrice: 35999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'OnePlus India Official Store',
    },
    display: {
      displaySize: 6.78,
      displayType: '1.5K 120Hz ProXDR LTPO AMOLED',
      resolution: '2780 x 1264 pixels',
      refreshRate: 120,
      peakBrightness: 4500,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '90.9%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Gen 2 (4nm)',
      cpu: 'Octa-core (1x3.2 GHz Cortex-X3 & 4x2.8 GHz & 3x2.0 GHz)',
      gpu: 'Adreno 740',
      ramOptions: ['8GB', '16GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1 / 4.0',
      antutuScore: 1530000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 8MP + 2MP)',
      mainCamera: '50 MP Sony IMX890, f/1.8, OIS',
      ultrawideCamera: '8 MP, f/2.2, 112˚',
      telephotoCamera: 'None (2 MP Macro)',
      frontCamera: '16 MP, f/2.4',
      videoRecording: '4K@60fps, 1080p@240fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5500,
      wiredCharging: 100,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '163.3 x 75.3 x 8.8 mm',
      weight: 207,
      materials: 'Aluminum alloy frame, glass back',
      waterResistance: 'IP64',
      colors: ['Iron Gray', 'Cool Blue', 'Sunset Dune'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'OxygenOS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years of security patches',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.oneplus.in/12r',
      productPage: 'https://www.oneplus.in/buy-oneplus-12r',
      specSheetUrl: 'https://www.oneplus.in/12r/specs',
      verifiedDate: '2024-01',
    },
  },

  {
    id: 'oneplus-open',
    slug: 'oneplus-open',
    brand: 'OnePlus',
    modelName: 'OnePlus Open',
    generation: 'Open',
    status: 'active',
    launchDate: '2023-10',
    pricing: {
      startingPrice: 139999,
      maximumPrice: 139999,
      launchPrice: 139999,
      currentPrice: 139999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'OnePlus India Official Store',
    },
    display: {
      displaySize: 7.82,
      displayType: 'Foldable Flexi-fluid LTPO AMOLED (Cover: 6.31" 2K)',
      resolution: '2440 x 2268 pixels (Cover: 2484 x 1116)',
      refreshRate: 120,
      peakBrightness: 2800,
      hdr: 'Dolby Vision',
      protection: 'Ceramic Guard (Cover)',
      screenToBodyRatio: '89.6%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Gen 2 (4nm)',
      cpu: 'Octa-core (1x3.2 GHz Cortex-X3 & 4x2.8 GHz & 3x2.0 GHz)',
      gpu: 'Adreno 740',
      ramOptions: ['16GB'],
      storageOptions: ['512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 1540000,
    },
    cameras: {
      rearCameraSetup: 'Triple (48MP + 48MP + 64MP) Hasselblad',
      mainCamera: '48 MP Sony LYT-T808 Pixel Stacked, f/1.7, OIS',
      ultrawideCamera: '48 MP, f/2.2, 114˚',
      telephotoCamera: '64 MP periscope telephoto, 3x optical, 6x in-sensor, OIS',
      frontCamera: '20 MP internal + 32 MP cover camera',
      videoRecording: '4K@60fps Dolby Vision',
      ois: true,
    },
    battery: {
      batteryCapacity: 4805,
      wiredCharging: 67,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 3.1',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '153.5 x 143.1 x 5.8 mm (Folded: 153.5 x 73.3 x 11.7 mm)',
      weight: 239,
      materials: 'Titanium alloy hinge, carbon fiber, vegan leather or glass back',
      waterResistance: 'IPX4 splash resistant',
      colors: ['Emerald Dusk', 'Voyager Black', 'Apex Edition Crimson Shadow'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'OxygenOS 14 with Open Canvas',
      launchOS: 'Android 13',
      promisedMajorUpdates: 4,
      securityUpdatePolicy: '5 years of security patches',
    },
    audio: {
      speakers: 'Spatial Audio triple-speaker array',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.oneplus.in/open',
      productPage: 'https://www.oneplus.in/buy-oneplus-open',
      specSheetUrl: 'https://www.oneplus.in/open/specs',
      verifiedDate: '2023-10',
    },
  },

  {
    id: 'oneplus-nord-4',
    slug: 'oneplus-nord-4',
    brand: 'OnePlus',
    modelName: 'OnePlus Nord 4',
    generation: 'Nord 4',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 29999,
      maximumPrice: 35999,
      launchPrice: 29999,
      currentPrice: 29999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'OnePlus India Official Store',
    },
    display: {
      displaySize: 6.74,
      displayType: '1.5K 120Hz Super Fluid AMOLED',
      resolution: '2772 x 1240 pixels',
      refreshRate: 120,
      peakBrightness: 2150,
      hdr: 'HDR10+, Ultra HDR',
      protection: 'Glass front',
      screenToBodyRatio: '90.0%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7+ Gen 3 (4nm)',
      cpu: 'Octa-core (1x2.8 GHz Cortex-X4 & 4x2.6 GHz & 3x1.9 GHz)',
      gpu: 'Adreno 732',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 4.0 (256GB) / UFS 3.1 (128GB)',
      antutuScore: 1420000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 8MP)',
      mainCamera: '50 MP Sony LYT-600, f/1.8, OIS',
      ultrawideCamera: '8 MP Sony, f/2.2, 112˚',
      telephotoCamera: 'None',
      frontCamera: '16 MP, f/2.4',
      videoRecording: '4K@60fps, 1080p@120fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5500,
      wiredCharging: 100,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.6 x 75.0 x 7.99 mm',
      weight: 199,
      materials: 'All-metal unibody aluminum design',
      waterResistance: 'IP65',
      colors: ['Mercurial Silver', 'Oasis Green', 'Obsidian Midnight'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'OxygenOS 14.1',
      launchOS: 'Android 14',
      promisedMajorUpdates: 4,
      securityUpdatePolicy: '6 years of security patches',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.oneplus.in/nord-4',
      productPage: 'https://www.oneplus.in/buy-oneplus-nord-4',
      specSheetUrl: 'https://www.oneplus.in/nord-4/specs',
      verifiedDate: '2024-07',
    },
  },

  {
    id: 'oneplus-nord-ce4',
    slug: 'oneplus-nord-ce4',
    brand: 'OnePlus',
    modelName: 'OnePlus Nord CE4',
    generation: 'Nord CE4',
    status: 'active',
    launchDate: '2024-04',
    pricing: {
      startingPrice: 24999,
      maximumPrice: 26999,
      launchPrice: 24999,
      currentPrice: 24999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'OnePlus India Official Store',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Fluid AMOLED',
      resolution: '2412 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1100,
      hdr: 'HDR10+',
      protection: 'Glass front',
      screenToBodyRatio: '89.3%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7 Gen 3 (4nm)',
      cpu: 'Octa-core (1x2.63 GHz Cortex-A715 & 4x2.4 GHz & 3x1.8 GHz)',
      gpu: 'Adreno 720',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 820000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 8MP)',
      mainCamera: '50 MP Sony LYT-600, f/1.8, OIS',
      ultrawideCamera: '8 MP Sony IMX355, f/2.2, 112˚',
      telephotoCamera: 'None',
      frontCamera: '16 MP, f/2.4',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5500,
      wiredCharging: 100,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.4',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '162.5 x 75.3 x 8.4 mm',
      weight: 186,
      materials: 'Plastic frame, composite back',
      waterResistance: 'IP54',
      colors: ['Dark Chrome', 'Celadon Marble'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'OxygenOS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years of security patches',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.oneplus.in/nord-ce4',
      productPage: 'https://www.oneplus.in/buy-oneplus-nord-ce4',
      specSheetUrl: 'https://www.oneplus.in/nord-ce4/specs',
      verifiedDate: '2024-04',
    },
  },

  {
    id: 'oneplus-nord-ce4-lite-5g',
    slug: 'oneplus-nord-ce4-lite-5g',
    brand: 'OnePlus',
    modelName: 'OnePlus Nord CE4 Lite 5G',
    generation: 'Nord CE4 Lite',
    status: 'active',
    launchDate: '2024-06',
    pricing: {
      startingPrice: 19999,
      maximumPrice: 22999,
      launchPrice: 19999,
      currentPrice: 19999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'OnePlus India Official Store',
    },
    display: {
      displaySize: 6.67,
      displayType: '120Hz AMOLED',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 2100,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '88.2%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 695 5G (6nm)',
      cpu: 'Octa-core (2x2.2 GHz Kryo 660 Gold & 6x1.7 GHz Kryo 660 Silver)',
      gpu: 'Adreno 619',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 450000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP)',
      mainCamera: '50 MP Sony LYT-600, f/1.8, OIS',
      ultrawideCamera: 'None',
      telephotoCamera: 'None (2 MP depth)',
      frontCamera: '16 MP, f/2.4',
      videoRecording: '1080p@30fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5500,
      wiredCharging: 80,
      wirelessCharging: 0,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.1',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '162.9 x 75.6 x 8.1 mm',
      weight: 191,
      materials: 'Plastic frame & back',
      waterResistance: 'IP54',
      colors: ['Super Silver', 'Mega Blue', 'Ultra Orange'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'OxygenOS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years of security patches',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.oneplus.in/nord-ce4-lite-5g',
      productPage: 'https://www.oneplus.in/buy-oneplus-nord-ce4-lite-5g',
      specSheetUrl: 'https://www.oneplus.in/nord-ce4-lite-5g/specs',
      verifiedDate: '2024-06',
    },
  },
];

const variants: MobileVariant[] = [
  // OnePlus 13
  {
    id: 'oneplus-13-12-256',
    modelId: 'oneplus-13',
    ram: '12GB',
    storage: '256GB',
    price: 69999,
    mrp: 69999,
    colors: ['Midnight Ocean', 'Black Eclipse', 'Arctic Dawn'],
    status: 'active',
    verified: true,
    source: 'OnePlus India Official Store',
  },
  {
    id: 'oneplus-13-16-512',
    modelId: 'oneplus-13',
    ram: '16GB',
    storage: '512GB',
    price: 76999,
    mrp: 76999,
    colors: ['Midnight Ocean', 'Arctic Dawn'],
    status: 'active',
    verified: true,
    source: 'OnePlus India Official Store',
  },
  {
    id: 'oneplus-13-24-1tb',
    modelId: 'oneplus-13',
    ram: '24GB',
    storage: '1TB',
    price: 89999,
    mrp: 89999,
    colors: ['Black Eclipse'],
    status: 'active',
    verified: true,
    source: 'OnePlus India Official Store',
  },

  // OnePlus 13R
  {
    id: 'oneplus-13r-12-256',
    modelId: 'oneplus-13r',
    ram: '12GB',
    storage: '256GB',
    price: 42999,
    mrp: 42999,
    colors: ['Nebula Noir', 'Astral Trail'],
    status: 'active',
    verified: true,
    source: 'OnePlus India Official Store',
  },
  {
    id: 'oneplus-13r-16-512',
    modelId: 'oneplus-13r',
    ram: '16GB',
    storage: '512GB',
    price: 49999,
    mrp: 49999,
    colors: ['Nebula Noir', 'Astral Trail'],
    status: 'active',
    verified: true,
    source: 'OnePlus India Official Store',
  },

  // OnePlus 12
  {
    id: 'oneplus-12-12-256',
    modelId: 'oneplus-12',
    ram: '12GB',
    storage: '256GB',
    price: 59999,
    mrp: 64999,
    colors: ['Silky Black', 'Flowy Emerald'],
    status: 'active',
    verified: true,
    source: 'OnePlus India Official Store',
  },
  {
    id: 'oneplus-12-16-512',
    modelId: 'oneplus-12',
    ram: '16GB',
    storage: '512GB',
    price: 64999,
    mrp: 69999,
    colors: ['Silky Black', 'Flowy Emerald', 'Glacial White'],
    status: 'active',
    verified: true,
    source: 'OnePlus India Official Store',
  },

  // OnePlus 12R
  {
    id: 'oneplus-12r-8-128',
    modelId: 'oneplus-12r',
    ram: '8GB',
    storage: '128GB',
    price: 35999,
    mrp: 39999,
    colors: ['Iron Gray', 'Cool Blue'],
    status: 'active',
    verified: true,
    source: 'OnePlus India Official Store',
  },
  {
    id: 'oneplus-12r-16-256',
    modelId: 'oneplus-12r',
    ram: '16GB',
    storage: '256GB',
    price: 42999,
    mrp: 45999,
    colors: ['Iron Gray', 'Cool Blue', 'Sunset Dune'],
    status: 'active',
    verified: true,
    source: 'OnePlus India Official Store',
  },

  // OnePlus Open
  {
    id: 'oneplus-open-16-512',
    modelId: 'oneplus-open',
    ram: '16GB',
    storage: '512GB',
    price: 139999,
    mrp: 139999,
    colors: ['Emerald Dusk', 'Voyager Black'],
    status: 'active',
    verified: true,
    source: 'OnePlus India Official Store',
  },

  // OnePlus Nord 4
  {
    id: 'oneplus-nord-4-8-128',
    modelId: 'oneplus-nord-4',
    ram: '8GB',
    storage: '128GB',
    price: 29999,
    mrp: 29999,
    colors: ['Mercurial Silver', 'Obsidian Midnight'],
    status: 'active',
    verified: true,
    source: 'OnePlus India Official Store',
  },
  {
    id: 'oneplus-nord-4-8-256',
    modelId: 'oneplus-nord-4',
    ram: '8GB',
    storage: '256GB',
    price: 32999,
    mrp: 32999,
    colors: ['Mercurial Silver', 'Oasis Green', 'Obsidian Midnight'],
    status: 'active',
    verified: true,
    source: 'OnePlus India Official Store',
  },
  {
    id: 'oneplus-nord-4-12-256',
    modelId: 'oneplus-nord-4',
    ram: '12GB',
    storage: '256GB',
    price: 35999,
    mrp: 35999,
    colors: ['Mercurial Silver', 'Oasis Green', 'Obsidian Midnight'],
    status: 'active',
    verified: true,
    source: 'OnePlus India Official Store',
  },

  // OnePlus Nord CE4
  {
    id: 'oneplus-nord-ce4-8-128',
    modelId: 'oneplus-nord-ce4',
    ram: '8GB',
    storage: '128GB',
    price: 24999,
    mrp: 24999,
    colors: ['Dark Chrome', 'Celadon Marble'],
    status: 'active',
    verified: true,
    source: 'OnePlus India Official Store',
  },
  {
    id: 'oneplus-nord-ce4-8-256',
    modelId: 'oneplus-nord-ce4',
    ram: '8GB',
    storage: '256GB',
    price: 26999,
    mrp: 26999,
    colors: ['Dark Chrome', 'Celadon Marble'],
    status: 'active',
    verified: true,
    source: 'OnePlus India Official Store',
  },

  // OnePlus Nord CE4 Lite 5G
  {
    id: 'oneplus-nord-ce4-lite-5g-8-128',
    modelId: 'oneplus-nord-ce4-lite-5g',
    ram: '8GB',
    storage: '128GB',
    price: 19999,
    mrp: 19999,
    colors: ['Super Silver', 'Mega Blue'],
    status: 'active',
    verified: true,
    source: 'OnePlus India Official Store',
  },
  {
    id: 'oneplus-nord-ce4-lite-5g-8-256',
    modelId: 'oneplus-nord-ce4-lite-5g',
    ram: '8GB',
    storage: '256GB',
    price: 22999,
    mrp: 22999,
    colors: ['Super Silver', 'Mega Blue', 'Ultra Orange'],
    status: 'active',
    verified: true,
    source: 'OnePlus India Official Store',
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    "modelId": "oneplus-13",
    "modelName": "OnePlus 13",
    "brand": "OnePlus",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-13.jpg",
        "angle": "front",
        "source": "OnePlus Official (GSMArena CDN)",
        "verified": true,
        "alt": "OnePlus 13 front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-13-1.jpg",
        "angle": "back",
        "source": "OnePlus Official (GSMArena CDN)",
        "verified": true,
        "alt": "OnePlus 13 Hasselblad camera rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-13-2.jpg",
        "angle": "side",
        "source": "OnePlus Official (GSMArena CDN)",
        "verified": true,
        "alt": "OnePlus 13 profile view"
      }
    ]
  },
  {
    "modelId": "oneplus-13r",
    "modelName": "OnePlus 13R",
    "brand": "OnePlus",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-13r.jpg",
        "angle": "front",
        "source": "OnePlus Official (GSMArena CDN)",
        "verified": true,
        "alt": "OnePlus 13R front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-13r-1.jpg",
        "angle": "back",
        "source": "OnePlus Official (GSMArena CDN)",
        "verified": true,
        "alt": "OnePlus 13R rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-13r-2.jpg",
        "angle": "side",
        "source": "OnePlus Official (GSMArena CDN)",
        "verified": true,
        "alt": "OnePlus 13R profile view"
      }
    ]
  },
  {
    "modelId": "oneplus-12",
    "modelName": "OnePlus 12",
    "brand": "OnePlus",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-12.jpg",
        "angle": "front",
        "source": "OnePlus Official (GSMArena CDN)",
        "verified": true,
        "alt": "OnePlus 12 front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-12-1.jpg",
        "angle": "back",
        "source": "OnePlus Official (GSMArena CDN)",
        "verified": true,
        "alt": "OnePlus 12 Flowy Emerald rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-12-2.jpg",
        "angle": "side",
        "source": "OnePlus Official (GSMArena CDN)",
        "verified": true,
        "alt": "OnePlus 12 profile"
      }
    ]
  },
  {
    "modelId": "oneplus-12r",
    "modelName": "OnePlus 12R",
    "brand": "OnePlus",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-12r.jpg",
        "angle": "front",
        "source": "OnePlus Official (GSMArena CDN)",
        "verified": true,
        "alt": "OnePlus 12R front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-12r-1.jpg",
        "angle": "back",
        "source": "OnePlus Official (GSMArena CDN)",
        "verified": true,
        "alt": "OnePlus 12R Cool Blue rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-12r-2.jpg",
        "angle": "side",
        "source": "OnePlus Official (GSMArena CDN)",
        "verified": true,
        "alt": "OnePlus 12R profile"
      }
    ]
  },
  {
    "modelId": "oneplus-open",
    "modelName": "OnePlus Open",
    "brand": "OnePlus",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-open-2.jpg",
        "angle": "front",
        "source": "OnePlus Official (GSMArena CDN)",
        "verified": true,
        "alt": "OnePlus Open unfolded display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-open-3.jpg",
        "angle": "back",
        "source": "OnePlus Official (GSMArena CDN)",
        "verified": true,
        "alt": "OnePlus Open Emerald Dusk rear view"
      }
    ]
  },
  {
    "modelId": "oneplus-nord-4",
    "modelName": "OnePlus Nord 4",
    "brand": "OnePlus",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord4.jpg",
        "angle": "front",
        "source": "OnePlus Official (GSMArena CDN)",
        "verified": true,
        "alt": "OnePlus Nord 4 front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-nord4-1.jpg",
        "angle": "back",
        "source": "OnePlus Official (GSMArena CDN)",
        "verified": true,
        "alt": "OnePlus Nord 4 metal unibody rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-nord4-2.jpg",
        "angle": "side",
        "source": "OnePlus Official (GSMArena CDN)",
        "verified": true,
        "alt": "OnePlus Nord 4 profile"
      }
    ]
  },
  {
    "modelId": "oneplus-nord-ce4",
    "modelName": "OnePlus Nord CE4",
    "brand": "OnePlus",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord-ce4-.jpg",
        "angle": "front",
        "source": "OnePlus Official (GSMArena CDN)",
        "verified": true,
        "alt": "OnePlus Nord CE4 front and rear view"
      }
    ]
  },
  {
    "modelId": "oneplus-nord-ce4-lite-5g",
    "modelName": "OnePlus Nord CE4 Lite 5G",
    "brand": "OnePlus",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord-ce4-lite.jpg",
        "angle": "front",
        "source": "OnePlus Official (GSMArena CDN)",
        "verified": true,
        "alt": "OnePlus Nord CE4 Lite 5G front view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-nord-ce4-lite-1.jpg",
        "angle": "back",
        "source": "OnePlus Official (GSMArena CDN)",
        "verified": true,
        "alt": "OnePlus Nord CE4 Lite 5G rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-nord-ce4-lite-2.jpg",
        "angle": "side",
        "source": "OnePlus Official (GSMArena CDN)",
        "verified": true,
        "alt": "OnePlus Nord CE4 Lite 5G profile"
      }
    ]
  }
];

export const oneplusBundle: MobileBrandBundle = {
  models,
  variants,
  images,
};
