import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  // ── FIND SERIES (Hasselblad Flagships) ──
  {
    id: 'oppo-find-x8-pro',
    slug: 'oppo-find-x8-pro',
    brand: 'OPPO',
    modelName: 'OPPO Find X8 Pro',
    generation: 'Find X8',
    status: 'active',
    launchDate: '2024-11',
    pricing: {
      startingPrice: 99999,
      maximumPrice: 99999,
      launchPrice: 99999,
      currentPrice: 99999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'OPPO India Official Store',
    },
    display: {
      displaySize: 6.78,
      displayType: 'LTPO AMOLED, 1B colors, 120Hz, Dolby Vision, HDR10+',
      resolution: '2780 x 1264 pixels',
      refreshRate: 120,
      peakBrightness: 4500,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '89.8%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 9400 (3nm)',
      cpu: 'Octa-core (1x3.63 GHz Cortex-X925 & 3x3.3 GHz Cortex-X4 & 4x2.4 GHz Cortex-A720)',
      gpu: 'Immortalis-G925',
      ramOptions: ['16GB'],
      storageOptions: ['512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 2860000,
    },
    cameras: {
      rearCameraSetup: 'Quad (50MP + 50MP + 50MP + 50MP) Hasselblad Master Camera',
      mainCamera: '50 MP Sony LYT-808, 1/1.4", f/1.6, 23mm, OIS',
      ultrawideCamera: '50 MP Samsung JN5, f/2.0, 15mm, 120˚, AF',
      telephotoCamera: '50 MP Sony LYT-600 3x periscope (OIS) + 50 MP Sony IMX858 6x periscope (OIS)',
      frontCamera: '32 MP Sony IMX615, f/2.4',
      videoRecording: '4K@60fps, Dolby Vision HDR, Log',
      ois: true,
    },
    battery: {
      batteryCapacity: 5910,
      wiredCharging: 80,
      wirelessCharging: 50,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 3.2 Gen 1',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.27 x 76.67 x 8.24 mm',
      weight: 215,
      materials: 'Gorilla Glass Victus 2 front and back, aluminum frame',
      waterResistance: 'IP68/IP69',
      colors: ['Space Black', 'Pearl White'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'ColorOS 15',
      launchOS: 'Android 15',
      promisedMajorUpdates: 5,
      securityUpdatePolicy: '6 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.oppo.com/in/smartphones/series-find-x/find-x8-pro/',
      productPage: 'https://www.oppo.com/in/store/product/find-x8-pro',
      specSheetUrl: 'https://www.oppo.com/in/smartphones/series-find-x/find-x8-pro/specs/',
      verifiedDate: '2024-11',
    },
  },

  {
    id: 'oppo-find-x8',
    slug: 'oppo-find-x8',
    brand: 'OPPO',
    modelName: 'OPPO Find X8',
    generation: 'Find X8',
    status: 'active',
    launchDate: '2024-11',
    pricing: {
      startingPrice: 69999,
      maximumPrice: 79999,
      launchPrice: 69999,
      currentPrice: 69999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'OPPO India Official Store',
    },
    display: {
      displaySize: 6.59,
      displayType: 'AMOLED, 1B colors, 120Hz, Dolby Vision, HDR10+',
      resolution: '2760 x 1256 pixels',
      refreshRate: 120,
      peakBrightness: 4500,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass 7i',
      screenToBodyRatio: '90.3%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 9400 (3nm)',
      cpu: 'Octa-core (1x3.63 GHz Cortex-X925 & 3x3.3 GHz Cortex-X4 & 4x2.4 GHz Cortex-A720)',
      gpu: 'Immortalis-G925',
      ramOptions: ['12GB', '16GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 2800000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 50MP) Hasselblad Camera',
      mainCamera: '50 MP Sony LYT-700, 1/1.56", f/1.8, 24mm, OIS',
      ultrawideCamera: '50 MP Samsung JN5, f/2.0, 15mm, 120˚',
      telephotoCamera: '50 MP Sony LYT-600 3x periscope, 73mm, OIS',
      frontCamera: '32 MP Sony IMX615, f/2.4',
      videoRecording: '4K@60fps, Dolby Vision HDR',
      ois: true,
    },
    battery: {
      batteryCapacity: 5630,
      wiredCharging: 80,
      wirelessCharging: 50,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '157.35 x 74.33 x 7.85 mm',
      weight: 193,
      materials: 'Glass front, aluminum frame, frosted glass back',
      waterResistance: 'IP68/IP69',
      colors: ['Starry Black', 'Space Grey'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'ColorOS 15',
      launchOS: 'Android 15',
      promisedMajorUpdates: 5,
      securityUpdatePolicy: '6 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.oppo.com/in/smartphones/series-find-x/find-x8/',
      productPage: 'https://www.oppo.com/in/store/product/find-x8',
      specSheetUrl: 'https://www.oppo.com/in/smartphones/series-find-x/find-x8/specs/',
      verifiedDate: '2024-11',
    },
  },

  {
    id: 'oppo-find-n3-flip',
    slug: 'oppo-find-n3-flip',
    brand: 'OPPO',
    modelName: 'OPPO Find N3 Flip',
    generation: 'Find N3',
    status: 'active',
    launchDate: '2023-10',
    pricing: {
      startingPrice: 94999,
      maximumPrice: 94999,
      launchPrice: 94999,
      currentPrice: 94999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'OPPO India Official Store',
    },
    display: {
      displaySize: 6.8,
      displayType: 'Foldable LTPO AMOLED, 120Hz, HDR10+ (Cover: 3.26" AMOLED)',
      resolution: '2520 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1600,
      hdr: 'HDR10+',
      protection: 'UTG ultra-thin glass / Gorilla Glass Victus cover',
      screenToBodyRatio: '85.9%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 9200 (4nm)',
      cpu: 'Octa-core (1x3.05 GHz Cortex-X3 & 3x2.85 GHz Cortex-A715 & 4x1.80 GHz Cortex-A510)',
      gpu: 'Immortalis-G715 MC11',
      ramOptions: ['12GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 4.0',
      antutuScore: 1220000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 32MP + 48MP) Hasselblad Camera for Flip',
      mainCamera: '50 MP Sony IMX890, f/1.8, OIS',
      ultrawideCamera: '48 MP Sony IMX581, f/2.2, 114˚',
      telephotoCamera: '32 MP Sony IMX709 2x portrait telephoto, f/2.0',
      frontCamera: '32 MP Sony IMX709, f/2.4',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4300,
      wiredCharging: 44,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM (Nano-SIM + eSIM)',
    },
    physical: {
      dimensions: '166.4 x 75.8 x 7.79 mm (unfolded) / 85.5 x 75.8 x 16.45 mm (folded)',
      weight: 198,
      materials: 'Aluminum frame, Flexion hinge, glass back',
      waterResistance: 'IPX4',
      colors: ['Cream Gold', 'Sleek Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'ColorOS 13.2 (upgraded to 14)',
      launchOS: 'Android 13',
      promisedMajorUpdates: 4,
      securityUpdatePolicy: '5 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.oppo.com/in/smartphones/series-find-n/find-n3-flip/',
      productPage: 'https://www.oppo.com/in/store/product/find-n3-flip',
      specSheetUrl: 'https://www.oppo.com/in/smartphones/series-find-n/find-n3-flip/specs/',
      verifiedDate: '2023-10',
    },
  },

  // ── RENO SERIES (Portrait Specialists) ──
  {
    id: 'oppo-reno-12-pro-5g',
    slug: 'oppo-reno-12-pro-5g',
    brand: 'OPPO',
    modelName: 'OPPO Reno 12 Pro 5G',
    generation: 'Reno 12',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 36999,
      maximumPrice: 40999,
      launchPrice: 36999,
      currentPrice: 36999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'OPPO India Official Store',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Quad-Curved Infinite View AMOLED, 120Hz, HDR10+',
      resolution: '2412 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1200,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '93.5%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7300-Energy (4nm)',
      cpu: 'Octa-core (4x2.5 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G615 MC2',
      ramOptions: ['12GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 3.1',
      antutuScore: 710000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 8MP) AI Portrait Camera',
      mainCamera: '50 MP Sony LYT-600, f/1.8, OIS',
      ultrawideCamera: '8 MP Sony IMX355, f/2.2, 112˚',
      telephotoCamera: '50 MP Samsung JN5 2x portrait telephoto, f/2.0',
      frontCamera: '50 MP Samsung JN5 with AF, f/2.0',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 80,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '161.45 x 74.79 x 7.4 mm',
      weight: 180,
      materials: 'Gorilla Glass Victus 2 front, high-strength alloy frame, fluid-ripple glass back',
      waterResistance: 'IP65',
      colors: ['Sunset Gold', 'Space Brown'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'ColorOS 14.1 (AI Features: AI Eraser 2.0, AI Studio)',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with 300% Ultra Volume',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.oppo.com/in/smartphones/series-reno/reno12-pro-5g/',
      productPage: 'https://www.oppo.com/in/store/product/reno12-pro-5g',
      specSheetUrl: 'https://www.oppo.com/in/smartphones/series-reno/reno12-pro-5g/specs/',
      verifiedDate: '2024-07',
    },
  },

  {
    id: 'oppo-reno-12-5g',
    slug: 'oppo-reno-12-5g',
    brand: 'OPPO',
    modelName: 'OPPO Reno 12 5G',
    generation: 'Reno 12',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 32999,
      maximumPrice: 32999,
      launchPrice: 32999,
      currentPrice: 32999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'OPPO India Official Store',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Quad-Curved Infinite View AMOLED, 120Hz, HDR10+',
      resolution: '2412 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1200,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass 7i',
      screenToBodyRatio: '93.2%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7300-Energy (4nm)',
      cpu: 'Octa-core (4x2.5 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G615 MC2',
      ramOptions: ['8GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 710000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 8MP + 2MP)',
      mainCamera: '50 MP Sony LYT-600, f/1.8, OIS',
      ultrawideCamera: '8 MP, f/2.2, 112˚',
      telephotoCamera: '2 MP macro, f/2.4',
      frontCamera: '32 MP, f/2.0',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 80,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '161.4 x 74.1 x 7.6 mm',
      weight: 177,
      materials: 'Gorilla Glass 7i front, alloy frame, fluid design back',
      waterResistance: 'IP65',
      colors: ['Sunset Peach', 'Matte Brown', 'Astro Silver'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'ColorOS 14.1',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with 300% Ultra Volume',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.oppo.com/in/smartphones/series-reno/reno12-5g/',
      productPage: 'https://www.oppo.com/in/store/product/reno12-5g',
      specSheetUrl: 'https://www.oppo.com/in/smartphones/series-reno/reno12-5g/specs/',
      verifiedDate: '2024-07',
    },
  },

  {
    id: 'oppo-reno-11-pro-5g',
    slug: 'oppo-reno-11-pro-5g',
    brand: 'OPPO',
    modelName: 'OPPO Reno 11 Pro 5G',
    generation: 'Reno 11',
    status: 'active',
    launchDate: '2024-01',
    pricing: {
      startingPrice: 37999,
      maximumPrice: 37999,
      launchPrice: 39999,
      currentPrice: 37999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'OPPO India Official Store',
    },
    display: {
      displaySize: 6.7,
      displayType: '3D Curved AMOLED, 120Hz, HDR10+',
      resolution: '2412 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 950,
      hdr: 'HDR10+',
      protection: 'Asahi Glass AGC DT-Star2',
      screenToBodyRatio: '93.0%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 8200 (4nm)',
      cpu: 'Octa-core (1x3.1 GHz Cortex-A78 & 3x3.0 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G610 MC6',
      ramOptions: ['12GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 920000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 32MP + 8MP) Portrait Expert',
      mainCamera: '50 MP Sony IMX890, f/1.8, OIS',
      ultrawideCamera: '8 MP Sony IMX355, f/2.2, 112˚',
      telephotoCamera: '32 MP Sony IMX709 2x portrait telephoto, f/2.0',
      frontCamera: '32 MP Sony IMX709, f/2.4',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4600,
      wiredCharging: 80,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.4 x 74.1 x 7.66 mm',
      weight: 181,
      materials: 'Glass front, plastic frame, silk-textured glass back',
      waterResistance: 'None',
      colors: ['Pearl White', 'Rock Grey'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'ColorOS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.oppo.com/in/smartphones/series-reno/reno11-pro-5g/',
      productPage: 'https://www.oppo.com/in/store/product/reno11-pro-5g',
      specSheetUrl: 'https://www.oppo.com/in/smartphones/series-reno/reno11-pro-5g/specs/',
      verifiedDate: '2024-01',
    },
  },

  {
    id: 'oppo-reno-11-5g',
    slug: 'oppo-reno-11-5g',
    brand: 'OPPO',
    modelName: 'OPPO Reno 11 5G',
    generation: 'Reno 11',
    status: 'active',
    launchDate: '2024-01',
    pricing: {
      startingPrice: 27999,
      maximumPrice: 31999,
      launchPrice: 29999,
      currentPrice: 27999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'OPPO India Official Store',
    },
    display: {
      displaySize: 6.7,
      displayType: '3D Curved AMOLED, 120Hz, HDR10+',
      resolution: '2412 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 950,
      hdr: 'HDR10+',
      protection: 'Asahi Glass AGC DT-Star2',
      screenToBodyRatio: '93.0%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7050 (6nm)',
      cpu: 'Octa-core (2x2.6 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G68 MC4',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 560000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 32MP + 8MP)',
      mainCamera: '50 MP Sony LYT-600, f/1.8, OIS',
      ultrawideCamera: '8 MP, f/2.2, 112˚',
      telephotoCamera: '32 MP Sony IMX709 2x portrait telephoto, f/2.0',
      frontCamera: '32 MP OmniVision OV32C, f/2.4',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 67,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '162.4 x 74.3 x 7.99 mm',
      weight: 182,
      materials: 'Glass front, plastic frame and back',
      waterResistance: 'None',
      colors: ['Wave Green', 'Rock Grey'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'ColorOS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.oppo.com/in/smartphones/series-reno/reno11-5g/',
      productPage: 'https://www.oppo.com/in/store/product/reno11-5g',
      specSheetUrl: 'https://www.oppo.com/in/smartphones/series-reno/reno11-5g/specs/',
      verifiedDate: '2024-01',
    },
  },

  {
    id: 'oppo-reno-10-pro-plus-5g',
    slug: 'oppo-reno-10-pro-plus-5g',
    brand: 'OPPO',
    modelName: 'OPPO Reno 10 Pro+ 5G',
    generation: 'Reno 10',
    status: 'discontinued',
    launchDate: '2023-07',
    pricing: {
      startingPrice: 49999,
      maximumPrice: 54999,
      launchPrice: 54999,
      currentPrice: 49999,
      currency: 'INR',
      priceEffectiveDate: '2024-03',
      source: 'OPPO India Official Store',
    },
    display: {
      displaySize: 6.74,
      displayType: '1.5K 120Hz 3D Curved AMOLED, HDR10+',
      resolution: '2772 x 1240 pixels',
      refreshRate: 120,
      peakBrightness: 1400,
      hdr: 'HDR10+',
      protection: 'Asahi Glass AGC DT-Star2',
      screenToBodyRatio: '90.6%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8+ Gen 1 (4nm)',
      cpu: 'Octa-core (1x3.0 GHz Cortex-X2 & 3x2.5 GHz Cortex-A710 & 4x1.80 GHz Cortex-A510)',
      gpu: 'Adreno 730',
      ramOptions: ['12GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 1250000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 64MP + 8MP) Periscope Portrait',
      mainCamera: '50 MP Sony IMX890, 1/1.56", f/1.8, OIS',
      ultrawideCamera: '8 MP Sony IMX355, f/2.2, 112˚',
      telephotoCamera: '64 MP OmniVision OV64B 3x periscope telephoto, f/2.5, OIS',
      frontCamera: '32 MP Sony IMX709, f/2.4',
      videoRecording: '4K@60fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4700,
      wiredCharging: 100,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.9 x 74.0 x 8.28 mm',
      weight: 194,
      materials: 'Glass front, plastic frame, frosted AG glass back',
      waterResistance: 'None',
      colors: ['Glossy Purple', 'Silvery Grey'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'ColorOS 13.1 (upgraded to 14)',
      launchOS: 'Android 13',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.oppo.com/in/smartphones/series-reno/reno10-pro-plus-5g/',
      productPage: 'https://www.oppo.com/in/store/product/reno10-pro-plus-5g',
      specSheetUrl: 'https://www.oppo.com/in/smartphones/series-reno/reno10-pro-plus-5g/specs/',
      verifiedDate: '2023-07',
    },
  },

  // ── F SERIES (Lifestyle & Durability) ──
  {
    id: 'oppo-f27-pro-plus-5g',
    slug: 'oppo-f27-pro-plus-5g',
    brand: 'OPPO',
    modelName: 'OPPO F27 Pro+ 5G',
    generation: 'F27',
    status: 'active',
    launchDate: '2024-06',
    pricing: {
      startingPrice: 27999,
      maximumPrice: 29999,
      launchPrice: 27999,
      currentPrice: 27999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'OPPO India Official Store',
    },
    display: {
      displaySize: 6.7,
      displayType: '3D Curved AMOLED, 120Hz',
      resolution: '2412 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 950,
      hdr: 'None',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '93.0%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7050 (6nm)',
      cpu: 'Octa-core (2x2.6 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G68 MC4',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 560000,
    },
    cameras: {
      rearCameraSetup: 'Dual (64MP + 2MP)',
      mainCamera: '64 MP, f/1.7',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP portrait, f/2.4',
      frontCamera: '8 MP, f/2.0',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 67,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.7 x 74.3 x 7.89 mm',
      weight: 177,
      materials: 'Gorilla Glass Victus 2 front, waterproof vegan leather back with 360-degree Armour Body',
      waterResistance: 'IP69 / IP68 / IP66 (India’s first waterproof triple-certified phone)',
      colors: ['Dusk Pink', 'Midnight Navy'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'ColorOS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Single speaker with 300% Ultra Volume',
      stereo: false,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.oppo.com/in/smartphones/series-f/f27-pro-plus-5g/',
      productPage: 'https://www.oppo.com/in/store/product/f27-pro-plus-5g',
      specSheetUrl: 'https://www.oppo.com/in/smartphones/series-f/f27-pro-plus-5g/specs/',
      verifiedDate: '2024-06',
    },
  },

  {
    id: 'oppo-f27-5g',
    slug: 'oppo-f27-5g',
    brand: 'OPPO',
    modelName: 'OPPO F27 5G',
    generation: 'F27',
    status: 'active',
    launchDate: '2024-08',
    pricing: {
      startingPrice: 22999,
      maximumPrice: 24999,
      launchPrice: 22999,
      currentPrice: 22999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'OPPO India Official Store',
    },
    display: {
      displaySize: 6.67,
      displayType: 'AMOLED, 120Hz',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 2100,
      hdr: 'None',
      protection: 'Asahi Glass AGC DT-Star2 Plus',
      screenToBodyRatio: '87.9%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6300 (6nm)',
      cpu: 'Octa-core (2x2.4 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 420000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP) Halo Light',
      mainCamera: '50 MP OmniVision, f/1.8',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP depth sensor',
      frontCamera: '32 MP Sony IMX615, f/2.4',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 45,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '163.05 x 75.75 x 7.69 mm',
      weight: 187,
      materials: 'Glass front, Armour Body, Cosmos Ring design with Halo Light',
      waterResistance: 'IP64',
      colors: ['Amber Orange', 'Emerald Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'ColorOS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with 300% Ultra Volume',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.oppo.com/in/smartphones/series-f/f27-5g/',
      productPage: 'https://www.oppo.com/in/store/product/f27-5g',
      specSheetUrl: 'https://www.oppo.com/in/smartphones/series-f/f27-5g/specs/',
      verifiedDate: '2024-08',
    },
  },

  {
    id: 'oppo-f25-pro-5g',
    slug: 'oppo-f25-pro-5g',
    brand: 'OPPO',
    modelName: 'OPPO F25 Pro 5G',
    generation: 'F25',
    status: 'active',
    launchDate: '2024-02',
    pricing: {
      startingPrice: 23999,
      maximumPrice: 25999,
      launchPrice: 23999,
      currentPrice: 23999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'OPPO India Official Store',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Flexible AMOLED, 120Hz, HDR10+',
      resolution: '2412 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1100,
      hdr: 'HDR10+',
      protection: 'Panda Glass (twice-reinforced)',
      screenToBodyRatio: '93.4%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7050 (6nm)',
      cpu: 'Octa-core (2x2.6 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G68 MC4',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 560000,
    },
    cameras: {
      rearCameraSetup: 'Triple (64MP + 8MP + 2MP)',
      mainCamera: '64 MP OmniVision OV64B, f/1.7',
      ultrawideCamera: '8 MP Sony IMX355, f/2.2, 112˚',
      telephotoCamera: '2 MP macro, f/2.4',
      frontCamera: '32 MP Sony IMX615, 4K video recording, f/2.4',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 67,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '161.6 x 74.7 x 7.54 mm',
      weight: 177,
      materials: 'Glass front, polycarbonate frame, lava red glow back',
      waterResistance: 'IP65',
      colors: ['Lava Red', 'Ocean Blue'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'ColorOS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Single speaker with Ultra Volume mode',
      stereo: false,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.oppo.com/in/smartphones/series-f/f25-pro-5g/',
      productPage: 'https://www.oppo.com/in/store/product/f25-pro-5g',
      specSheetUrl: 'https://www.oppo.com/in/smartphones/series-f/f25-pro-5g/specs/',
      verifiedDate: '2024-02',
    },
  },

  // ── K SERIES (Online Performance) ──
  {
    id: 'oppo-k12x-5g',
    slug: 'oppo-k12x-5g',
    brand: 'OPPO',
    modelName: 'OPPO K12x 5G',
    generation: 'K12',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 12999,
      maximumPrice: 15999,
      launchPrice: 12999,
      currentPrice: 12999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Flipkart / OPPO India',
    },
    display: {
      displaySize: 6.67,
      displayType: 'IPS LCD, 120Hz',
      resolution: '1604 x 720 pixels (HD+)',
      refreshRate: 120,
      peakBrightness: 1000,
      hdr: 'None',
      protection: 'Panda Glass (twice-reinforced)',
      screenToBodyRatio: '85.1%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6300 (6nm)',
      cpu: 'Octa-core (2x2.4 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['6GB', '8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 420000,
    },
    cameras: {
      rearCameraSetup: 'Dual (32MP + 2MP)',
      mainCamera: '32 MP, f/1.85',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP portrait sensor',
      frontCamera: '8 MP, f/2.05',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5100,
      wiredCharging: 45,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.1',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '165.7 x 76.0 x 7.68 mm',
      weight: 186,
      materials: 'Military-Grade shock resistance (MIL-STD-810H), 360-degree damage-proof body',
      waterResistance: 'IP54',
      colors: ['Breeze Blue', 'Midnight Violet'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'ColorOS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Single speaker with 300% Ultra Volume',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.oppo.com/in/smartphones/series-k/k12x-5g/',
      productPage: 'https://www.flipkart.com/oppo-k12x-5g/p/itm123',
      specSheetUrl: 'https://www.oppo.com/in/smartphones/series-k/k12x-5g/specs/',
      verifiedDate: '2024-07',
    },
  },

  // ── A SERIES (Mass Market Durability) ──
  {
    id: 'oppo-a3-pro-5g',
    slug: 'oppo-a3-pro-5g',
    brand: 'OPPO',
    modelName: 'OPPO A3 Pro 5G',
    generation: 'A3',
    status: 'active',
    launchDate: '2024-06',
    pricing: {
      startingPrice: 17999,
      maximumPrice: 19999,
      launchPrice: 17999,
      currentPrice: 17999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'OPPO India Official Store',
    },
    display: {
      displaySize: 6.67,
      displayType: 'IPS LCD, 120Hz',
      resolution: '1604 x 720 pixels (HD+)',
      refreshRate: 120,
      peakBrightness: 1000,
      hdr: 'None',
      protection: 'Panda Glass (twice-reinforced)',
      screenToBodyRatio: '85.1%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6300 (6nm)',
      cpu: 'Octa-core (2x2.4 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 420000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP)',
      mainCamera: '50 MP, f/1.8',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP portrait, f/2.4',
      frontCamera: '8 MP, f/2.0',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5100,
      wiredCharging: 45,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '165.79 x 76.14 x 7.68 mm',
      weight: 186,
      materials: 'All-round Armour Body, SGS 5-star drop resistance certification',
      waterResistance: 'IP54',
      colors: ['Starry Black', 'Moonlight Purple'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'ColorOS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Single speaker with 300% Ultra Volume',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.oppo.com/in/smartphones/series-a/a3-pro-5g/',
      productPage: 'https://www.oppo.com/in/store/product/a3-pro-5g',
      specSheetUrl: 'https://www.oppo.com/in/smartphones/series-a/a3-pro-5g/specs/',
      verifiedDate: '2024-06',
    },
  },
];

const variants: MobileVariant[] = [
  // OPPO Find X8 Pro
  {
    id: 'oppo-find-x8-pro-16-512',
    modelId: 'oppo-find-x8-pro',
    ram: '16GB',
    storage: '512GB',
    price: 99999,
    mrp: 99999,
    colors: ['Space Black', 'Pearl White'],
    status: 'active',
    verified: true,
    source: 'OPPO India Official Store',
  },
  // OPPO Find X8
  {
    id: 'oppo-find-x8-12-256',
    modelId: 'oppo-find-x8',
    ram: '12GB',
    storage: '256GB',
    price: 69999,
    mrp: 69999,
    colors: ['Starry Black', 'Space Grey'],
    status: 'active',
    verified: true,
    source: 'OPPO India Official Store',
  },
  {
    id: 'oppo-find-x8-16-512',
    modelId: 'oppo-find-x8',
    ram: '16GB',
    storage: '512GB',
    price: 79999,
    mrp: 79999,
    colors: ['Starry Black', 'Space Grey'],
    status: 'active',
    verified: true,
    source: 'OPPO India Official Store',
  },
  // OPPO Find N3 Flip
  {
    id: 'oppo-find-n3-flip-12-256',
    modelId: 'oppo-find-n3-flip',
    ram: '12GB',
    storage: '256GB',
    price: 94999,
    mrp: 94999,
    colors: ['Cream Gold', 'Sleek Black'],
    status: 'active',
    verified: true,
    source: 'OPPO India Official Store',
  },
  // OPPO Reno 12 Pro 5G
  {
    id: 'oppo-reno-12-pro-5g-12-256',
    modelId: 'oppo-reno-12-pro-5g',
    ram: '12GB',
    storage: '256GB',
    price: 36999,
    mrp: 36999,
    colors: ['Sunset Gold', 'Space Brown'],
    status: 'active',
    verified: true,
    source: 'OPPO India Official Store',
  },
  {
    id: 'oppo-reno-12-pro-5g-12-512',
    modelId: 'oppo-reno-12-pro-5g',
    ram: '12GB',
    storage: '512GB',
    price: 40999,
    mrp: 40999,
    colors: ['Sunset Gold', 'Space Brown'],
    status: 'active',
    verified: true,
    source: 'OPPO India Official Store',
  },
  // OPPO Reno 12 5G
  {
    id: 'oppo-reno-12-5g-8-256',
    modelId: 'oppo-reno-12-5g',
    ram: '8GB',
    storage: '256GB',
    price: 32999,
    mrp: 32999,
    colors: ['Sunset Peach', 'Astro Silver'],
    status: 'active',
    verified: true,
    source: 'OPPO India Official Store',
  },
  // OPPO Reno 11 Pro 5G
  {
    id: 'oppo-reno-11-pro-5g-12-256',
    modelId: 'oppo-reno-11-pro-5g',
    ram: '12GB',
    storage: '256GB',
    price: 37999,
    mrp: 39999,
    colors: ['Pearl White', 'Rock Grey'],
    status: 'active',
    verified: true,
    source: 'OPPO India Official Store',
  },
  // OPPO Reno 11 5G
  {
    id: 'oppo-reno-11-5g-8-128',
    modelId: 'oppo-reno-11-5g',
    ram: '8GB',
    storage: '128GB',
    price: 27999,
    mrp: 29999,
    colors: ['Wave Green', 'Rock Grey'],
    status: 'active',
    verified: true,
    source: 'OPPO India Official Store',
  },
  {
    id: 'oppo-reno-11-5g-8-256',
    modelId: 'oppo-reno-11-5g',
    ram: '8GB',
    storage: '256GB',
    price: 31999,
    mrp: 33999,
    colors: ['Wave Green', 'Rock Grey'],
    status: 'active',
    verified: true,
    source: 'OPPO India Official Store',
  },
  // OPPO Reno 10 Pro+ 5G
  {
    id: 'oppo-reno-10-pro-plus-5g-12-256',
    modelId: 'oppo-reno-10-pro-plus-5g',
    ram: '12GB',
    storage: '256GB',
    price: 49999,
    mrp: 54999,
    colors: ['Glossy Purple', 'Silvery Grey'],
    status: 'discontinued',
    verified: true,
    source: 'OPPO India Official Store',
  },
  // OPPO F27 Pro+ 5G
  {
    id: 'oppo-f27-pro-plus-5g-8-128',
    modelId: 'oppo-f27-pro-plus-5g',
    ram: '8GB',
    storage: '128GB',
    price: 27999,
    mrp: 27999,
    colors: ['Dusk Pink', 'Midnight Navy'],
    status: 'active',
    verified: true,
    source: 'OPPO India Official Store',
  },
  {
    id: 'oppo-f27-pro-plus-5g-8-256',
    modelId: 'oppo-f27-pro-plus-5g',
    ram: '8GB',
    storage: '256GB',
    price: 29999,
    mrp: 29999,
    colors: ['Dusk Pink', 'Midnight Navy'],
    status: 'active',
    verified: true,
    source: 'OPPO India Official Store',
  },
  // OPPO F27 5G
  {
    id: 'oppo-f27-5g-8-128',
    modelId: 'oppo-f27-5g',
    ram: '8GB',
    storage: '128GB',
    price: 22999,
    mrp: 22999,
    colors: ['Amber Orange', 'Emerald Green'],
    status: 'active',
    verified: true,
    source: 'OPPO India Official Store',
  },
  {
    id: 'oppo-f27-5g-8-256',
    modelId: 'oppo-f27-5g',
    ram: '8GB',
    storage: '256GB',
    price: 24999,
    mrp: 24999,
    colors: ['Amber Orange', 'Emerald Green'],
    status: 'active',
    verified: true,
    source: 'OPPO India Official Store',
  },
  // OPPO F25 Pro 5G
  {
    id: 'oppo-f25-pro-5g-8-128',
    modelId: 'oppo-f25-pro-5g',
    ram: '8GB',
    storage: '128GB',
    price: 23999,
    mrp: 23999,
    colors: ['Lava Red', 'Ocean Blue'],
    status: 'active',
    verified: true,
    source: 'OPPO India Official Store',
  },
  {
    id: 'oppo-f25-pro-5g-8-256',
    modelId: 'oppo-f25-pro-5g',
    ram: '8GB',
    storage: '256GB',
    price: 25999,
    mrp: 25999,
    colors: ['Lava Red', 'Ocean Blue'],
    status: 'active',
    verified: true,
    source: 'OPPO India Official Store',
  },
  // OPPO K12x 5G
  {
    id: 'oppo-k12x-5g-6-128',
    modelId: 'oppo-k12x-5g',
    ram: '6GB',
    storage: '128GB',
    price: 12999,
    mrp: 12999,
    colors: ['Breeze Blue', 'Midnight Violet'],
    status: 'active',
    verified: true,
    source: 'Flipkart / OPPO India',
  },
  {
    id: 'oppo-k12x-5g-8-256',
    modelId: 'oppo-k12x-5g',
    ram: '8GB',
    storage: '256GB',
    price: 15999,
    mrp: 15999,
    colors: ['Breeze Blue', 'Midnight Violet'],
    status: 'active',
    verified: true,
    source: 'Flipkart / OPPO India',
  },
  // OPPO A3 Pro 5G
  {
    id: 'oppo-a3-pro-5g-8-128',
    modelId: 'oppo-a3-pro-5g',
    ram: '8GB',
    storage: '128GB',
    price: 17999,
    mrp: 17999,
    colors: ['Starry Black', 'Moonlight Purple'],
    status: 'active',
    verified: true,
    source: 'OPPO India Official Store',
  },
  {
    id: 'oppo-a3-pro-5g-8-256',
    modelId: 'oppo-a3-pro-5g',
    ram: '8GB',
    storage: '256GB',
    price: 19999,
    mrp: 19999,
    colors: ['Starry Black', 'Moonlight Purple'],
    status: 'active',
    verified: true,
    source: 'OPPO India Official Store',
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    modelId: 'oppo-find-x8-pro',
    modelName: 'OPPO Find X8 Pro',
    brand: 'OPPO',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/oppo-find-x8-pro.jpg',
        angle: 'front',
        source: 'OPPO Official (GSMArena CDN)',
        sourceUrl: 'https://www.oppo.com/in/smartphones/series-find-x/find-x8-pro/',
        verified: true,
        alt: 'OPPO Find X8 Pro front quad-curve display',
      },
    ],
  },
  {
    modelId: 'oppo-find-x8',
    modelName: 'OPPO Find X8',
    brand: 'OPPO',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/oppo-find-x8.jpg',
        angle: 'front',
        source: 'OPPO Official (GSMArena CDN)',
        sourceUrl: 'https://www.oppo.com/in/smartphones/series-find-x/find-x8/',
        verified: true,
        alt: 'OPPO Find X8 front view',
      },
    ],
  },
  {
    modelId: 'oppo-find-n3-flip',
    modelName: 'OPPO Find N3 Flip',
    brand: 'OPPO',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/oppo-find-n3-flip.jpg',
        angle: 'front',
        source: 'OPPO Official (GSMArena CDN)',
        sourceUrl: 'https://www.oppo.com/in/smartphones/series-find-n/find-n3-flip/',
        verified: true,
        alt: 'OPPO Find N3 Flip cover display view',
      },
    ],
  },
  {
    modelId: 'oppo-reno-12-pro-5g',
    modelName: 'OPPO Reno 12 Pro 5G',
    brand: 'OPPO',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/oppo/oppo-reno12-pro-cn-1.jpg',
        angle: 'front',
        source: 'OPPO Official (GSMArena CDN)',
        sourceUrl: 'https://www.oppo.com/in/smartphones/series-reno/reno12-pro-5g/',
        verified: true,
        alt: 'OPPO Reno 12 Pro 5G front display view',
      },
    ],
  },
  {
    modelId: 'oppo-reno-12-5g',
    modelName: 'OPPO Reno 12 5G',
    brand: 'OPPO',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/oppo-reno12.jpg',
        angle: 'front',
        source: 'OPPO Official (GSMArena CDN)',
        sourceUrl: 'https://www.oppo.com/in/smartphones/series-reno/reno12-5g/',
        verified: true,
        alt: 'OPPO Reno 12 5G front view',
      },
    ],
  },
  {
    modelId: 'oppo-reno-11-pro-5g',
    modelName: 'OPPO Reno 11 Pro 5G',
    brand: 'OPPO',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/oppo-reno11-china.jpg',
        angle: 'front',
        source: 'OPPO Official (GSMArena CDN)',
        sourceUrl: 'https://www.oppo.com/in/smartphones/series-reno/reno11-pro-5g/',
        verified: true,
        alt: 'OPPO Reno 11 Pro 5G front view',
      },
    ],
  },
  {
    modelId: 'oppo-reno-11-5g',
    modelName: 'OPPO Reno 11 5G',
    brand: 'OPPO',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/oppo-reno11-international.jpg',
        angle: 'front',
        source: 'OPPO Official (GSMArena CDN)',
        sourceUrl: 'https://www.oppo.com/in/smartphones/series-reno/reno11-5g/',
        verified: true,
        alt: 'OPPO Reno 11 5G front view',
      },
    ],
  },
  {
    modelId: 'oppo-reno-10-pro-plus-5g',
    modelName: 'OPPO Reno 10 Pro+ 5G',
    brand: 'OPPO',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/oppo-reno10-pro-plus.jpg',
        angle: 'front',
        source: 'OPPO Official (GSMArena CDN)',
        sourceUrl: 'https://www.oppo.com/in/smartphones/series-reno/reno10-pro-plus-5g/',
        verified: true,
        alt: 'OPPO Reno 10 Pro+ 5G periscope front view',
      },
    ],
  },
  {
    modelId: 'oppo-f27-pro-plus-5g',
    modelName: 'OPPO F27 Pro+ 5G',
    brand: 'OPPO',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/oppo-f27.jpg',
        angle: 'front',
        source: 'OPPO Official (GSMArena CDN)',
        sourceUrl: 'https://www.oppo.com/in/smartphones/series-f/f27-pro-plus-5g/',
        verified: true,
        alt: 'OPPO F27 Pro+ 5G IP69 waterproof body view',
      },
    ],
  },
  {
    id: 'oppo-f27-5g',
    modelId: 'oppo-f27-5g',
    modelName: 'OPPO F27 5G',
    brand: 'OPPO',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/oppo-f27.jpg',
        angle: 'front',
        source: 'OPPO Official (GSMArena CDN)',
        sourceUrl: 'https://www.oppo.com/in/smartphones/series-f/f27-5g/',
        verified: true,
        alt: 'OPPO F27 5G Halo Light front view',
      },
    ],
  },
  {
    modelId: 'oppo-f25-pro-5g',
    modelName: 'OPPO F25 Pro 5G',
    brand: 'OPPO',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/oppo-f25-pro.jpg',
        angle: 'front',
        source: 'OPPO Official (GSMArena CDN)',
        sourceUrl: 'https://www.oppo.com/in/smartphones/series-f/f25-pro-5g/',
        verified: true,
        alt: 'OPPO F25 Pro 5G front display view',
      },
    ],
  },
  {
    modelId: 'oppo-k12x-5g',
    modelName: 'OPPO K12x 5G',
    brand: 'OPPO',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/oppo-k12x.jpg',
        angle: 'front',
        source: 'OPPO Official (GSMArena CDN)',
        sourceUrl: 'https://www.oppo.com/in/smartphones/series-k/k12x-5g/',
        verified: true,
        alt: 'OPPO K12x 5G military grade shockproof front view',
      },
    ],
  },
  {
    modelId: 'oppo-a3-pro-5g',
    modelName: 'OPPO A3 Pro 5G',
    brand: 'OPPO',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/oppo-a3-pro.jpg',
        angle: 'front',
        source: 'OPPO Official (GSMArena CDN)',
        sourceUrl: 'https://www.oppo.com/in/smartphones/series-a/a3-pro-5g/',
        verified: true,
        alt: 'OPPO A3 Pro 5G front display view',
      },
    ],
  },
];

export const oppoBundle: MobileBrandBundle = {
  brand: 'OPPO',
  models,
  variants,
  images,
};
