import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  // ── POCO F SERIES (Flagship Killers) ──
  {
    id: 'poco-f6-5g',
    slug: 'poco-f6-5g',
    brand: 'POCO',
    modelName: 'POCO F6 5G',
    generation: 'F6',
    status: 'active',
    launchDate: '2024-05',
    pricing: {
      startingPrice: 29999,
      maximumPrice: 33999,
      mrp: 29999,
      currentPrice: 29999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Flipkart / POCO India',
    },
    display: {
      displaySize: 6.67,
      displayType: '1.5K 120Hz Flow AMOLED',
      resolution: '2712 x 1220 pixels',
      refreshRate: 120,
      peakBrightness: 2400,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass Victus',
      screenToBodyRatio: '89.8%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8s Gen 3 (4nm)',
      cpu: 'Octa-core (1x3.0 GHz Cortex-X4 & 4x2.8 GHz & 3x2.0 GHz)',
      gpu: 'Adreno 735',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 1530000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 8MP)',
      mainCamera: '50 MP Sony IMX882, f/1.59, OIS',
      ultrawideCamera: '8 MP Sony IMX355, f/2.2, 119˚',
      telephotoCamera: 'None',
      frontCamera: '20 MP OmniVision OV20B, f/2.2',
      videoRecording: '4K@60fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 90,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '160.5 x 74.5 x 8.0 mm',
      weight: 179,
      materials: 'Glass front (Victus), polycarbonate frame and back',
      waterResistance: 'IP64',
      colors: ['Titanium', 'Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Xiaomi HyperOS',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.poco.in/f6-5g',
      productPage: 'https://www.flipkart.com/poco-f6-5g-titanium-256-gb/p/itm123456789',
      specSheetUrl: 'https://www.poco.in/f6-5g/specs',
      verifiedDate: '2024-05',
    },
  },

  {
    id: 'poco-f5-5g',
    slug: 'poco-f5-5g',
    brand: 'POCO',
    modelName: 'POCO F5 5G',
    generation: 'F5',
    status: 'discontinued',
    launchDate: '2023-05',
    pricing: {
      startingPrice: 26999,
      maximumPrice: 29999,
      mrp: 29999,
      currentPrice: 26999,
      currency: 'INR',
      priceEffectiveDate: '2024-03',
      source: 'Flipkart / POCO India',
    },
    display: {
      displaySize: 6.67,
      displayType: '12-bit Flow AMOLED, 120Hz, Dolby Vision, HDR10+',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1000,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '88.9%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7+ Gen 2 (4nm)',
      cpu: 'Octa-core (1x2.91 GHz Cortex-X2 & 3x2.49 GHz & 4x1.8 GHz)',
      gpu: 'Adreno 725',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 1140000,
    },
    cameras: {
      rearCameraSetup: 'Triple (64MP + 8MP + 2MP)',
      mainCamera: '64 MP OmniVision OV64B, f/1.79, OIS',
      ultrawideCamera: '8 MP, f/2.2, 119˚',
      telephotoCamera: '2 MP macro, f/2.4',
      frontCamera: '16 MP, f/2.45',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 67,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.1 x 74.9 x 7.9 mm',
      weight: 181,
      materials: 'Glass front (Gorilla Glass 5), plastic frame and back',
      waterResistance: 'IP53',
      colors: ['Carbon Black', 'Snowstorm White', 'Electric Blue'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MIUI 14 for POCO (upgraded to HyperOS)',
      launchOS: 'Android 13',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.poco.in/f5-5g',
      productPage: 'https://www.flipkart.com/poco-f5-5g/p/itm555',
      specSheetUrl: 'https://www.poco.in/f5-5g/specs',
      verifiedDate: '2023-05',
    },
  },

  {
    id: 'poco-f4-5g',
    slug: 'poco-f4-5g',
    brand: 'POCO',
    modelName: 'POCO F4 5G',
    generation: 'F4',
    status: 'discontinued',
    launchDate: '2022-06',
    pricing: {
      startingPrice: 23999,
      maximumPrice: 27999,
      mrp: 27999,
      currentPrice: 23999,
      currency: 'INR',
      priceEffectiveDate: '2023-06',
      source: 'Flipkart / POCO India',
    },
    display: {
      displaySize: 6.67,
      displayType: 'E4 AMOLED, 120Hz, Dolby Vision, HDR10+',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1300,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '86.6%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 870 5G (7nm)',
      cpu: 'Octa-core (1x3.2 GHz Kryo 585 & 3x2.42 GHz & 4x1.80 GHz)',
      gpu: 'Adreno 650',
      ramOptions: ['6GB', '8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 710000,
    },
    cameras: {
      rearCameraSetup: 'Triple (64MP + 8MP + 2MP)',
      mainCamera: '64 MP, f/1.79, OIS',
      ultrawideCamera: '8 MP, f/2.2, 119˚',
      telephotoCamera: '2 MP macro, f/2.4',
      frontCamera: '20 MP, f/2.4',
      videoRecording: '4K@60fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4500,
      wiredCharging: 67,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '163.2 x 75.95 x 7.7 mm',
      weight: 195,
      materials: 'Glass front (Gorilla Glass 5), plastic frame, glass back',
      waterResistance: 'IP53',
      colors: ['Night Black', 'Nebula Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MIUI 13 for POCO',
      launchOS: 'Android 12',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.poco.in/f4-5g',
      productPage: 'https://www.flipkart.com/poco-f4-5g/p/itm444',
      specSheetUrl: 'https://www.poco.in/f4-5g/specs',
      verifiedDate: '2022-06',
    },
  },

  // ── POCO X SERIES (Performance Mid-Rangers) ──
  {
    id: 'poco-x6-pro-5g',
    slug: 'poco-x6-pro-5g',
    brand: 'POCO',
    modelName: 'POCO X6 Pro 5G',
    generation: 'X6',
    status: 'active',
    launchDate: '2024-01',
    pricing: {
      startingPrice: 23999,
      maximumPrice: 25999,
      mrp: 26999,
      currentPrice: 23999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Flipkart / POCO India',
    },
    display: {
      displaySize: 6.67,
      displayType: '1.5K 120Hz Flow AMOLED',
      resolution: '2712 x 1220 pixels',
      refreshRate: 120,
      peakBrightness: 1800,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '90.1%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 8300 Ultra (4nm)',
      cpu: 'Octa-core (1x3.35 GHz Cortex-A715 & 3x3.2 GHz & 4x2.2 GHz)',
      gpu: 'Mali-G615 MC6',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 1400000,
    },
    cameras: {
      rearCameraSetup: 'Triple (64MP + 8MP + 2MP)',
      mainCamera: '64 MP OmniVision OV64B, f/1.7, OIS',
      ultrawideCamera: '8 MP, f/2.2, 120˚',
      telephotoCamera: '2 MP macro, f/2.4',
      frontCamera: '16 MP, f/2.4',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 67,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '160.45 x 74.34 x 8.25 mm',
      weight: 186,
      materials: 'Glass front (Gorilla Glass 5), vegan leather or plastic back',
      waterResistance: 'IP54',
      colors: ['POCO Yellow', 'Racing Grey', 'Spectre Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Xiaomi HyperOS',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.poco.in/x6-pro-5g',
      productPage: 'https://www.flipkart.com/poco-x6-pro-5g/p/itm123',
      specSheetUrl: 'https://www.poco.in/x6-pro-5g/specs',
      verifiedDate: '2024-01',
    },
  },

  {
    id: 'poco-x6-5g',
    slug: 'poco-x6-5g',
    brand: 'POCO',
    modelName: 'POCO X6 5G',
    generation: 'X6',
    status: 'active',
    launchDate: '2024-01',
    pricing: {
      startingPrice: 17999,
      maximumPrice: 20999,
      mrp: 21999,
      currentPrice: 17999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Flipkart / POCO India',
    },
    display: {
      displaySize: 6.67,
      displayType: '1.5K 120Hz Flow AMOLED',
      resolution: '2712 x 1220 pixels',
      refreshRate: 120,
      peakBrightness: 1800,
      hdr: 'Dolby Vision',
      protection: 'Corning Gorilla Glass Victus',
      screenToBodyRatio: '89.7%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7s Gen 2 (4nm)',
      cpu: 'Octa-core (4x2.40 GHz Cortex-A78 & 4x1.95 GHz Cortex-A55)',
      gpu: 'Adreno 710',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 2.2',
      antutuScore: 605000,
    },
    cameras: {
      rearCameraSetup: 'Triple (64MP + 8MP + 2MP)',
      mainCamera: '64 MP, f/1.79, OIS',
      ultrawideCamera: '8 MP, f/2.2, 118˚',
      telephotoCamera: '2 MP macro, f/2.4',
      frontCamera: '16 MP, f/2.45',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5100,
      wiredCharging: 67,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.2',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.15 x 74.24 x 7.98 mm',
      weight: 181.2,
      materials: 'Glass front (Victus), plastic frame and back',
      waterResistance: 'IP54',
      colors: ['Mirror Black', 'Snowstorm White'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MIUI 14 for POCO (upgraded to HyperOS)',
      launchOS: 'Android 13',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.poco.in/x6-5g',
      productPage: 'https://www.flipkart.com/poco-x6-5g/p/itm124',
      specSheetUrl: 'https://www.poco.in/x6-5g/specs',
      verifiedDate: '2024-01',
    },
  },

  {
    id: 'poco-x6-neo-5g',
    slug: 'poco-x6-neo-5g',
    brand: 'POCO',
    modelName: 'POCO X6 Neo 5G',
    generation: 'X6',
    status: 'active',
    launchDate: '2024-03',
    pricing: {
      startingPrice: 13999,
      maximumPrice: 15999,
      mrp: 15999,
      currentPrice: 13999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Flipkart / POCO India',
    },
    display: {
      displaySize: 6.67,
      displayType: 'AMOLED, 120Hz',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1000,
      hdr: 'None',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '88.9%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6080 (6nm)',
      cpu: 'Octa-core (2x2.4 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 450000,
    },
    cameras: {
      rearCameraSetup: 'Dual (108MP + 2MP)',
      mainCamera: '108 MP, f/1.75',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP depth sensor',
      frontCamera: '16 MP, f/2.4',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 33,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '161.11 x 74.95 x 7.69 mm',
      weight: 175,
      materials: 'Glass front (Gorilla Glass 5), plastic frame and back',
      waterResistance: 'IP54',
      colors: ['Martian Orange', 'Horizon Blue', 'Astral Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MIUI 14 for POCO (upgraded to HyperOS)',
      launchOS: 'Android 13',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Single speaker with Dolby Atmos boost',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.poco.in/x6-neo-5g',
      productPage: 'https://www.flipkart.com/poco-x6-neo-5g/p/itm125',
      specSheetUrl: 'https://www.poco.in/x6-neo-5g/specs',
      verifiedDate: '2024-03',
    },
  },

  {
    id: 'poco-x5-pro-5g',
    slug: 'poco-x5-pro-5g',
    brand: 'POCO',
    modelName: 'POCO X5 Pro 5G',
    generation: 'X5',
    status: 'discontinued',
    launchDate: '2023-02',
    pricing: {
      startingPrice: 18999,
      maximumPrice: 20999,
      mrp: 22999,
      currentPrice: 18999,
      currency: 'INR',
      priceEffectiveDate: '2024-01',
      source: 'Flipkart / POCO India',
    },
    display: {
      displaySize: 6.67,
      displayType: '10-bit Flow AMOLED, 120Hz, Dolby Vision, HDR10+',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 900,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '86.8%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 778G 5G (6nm)',
      cpu: 'Octa-core (1x2.4 GHz Cortex-A78 & 3x2.2 GHz & 4x1.8 GHz)',
      gpu: 'Adreno 642L',
      ramOptions: ['6GB', '8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 540000,
    },
    cameras: {
      rearCameraSetup: 'Triple (108MP + 8MP + 2MP)',
      mainCamera: '108 MP Samsung HM2, f/1.9',
      ultrawideCamera: '8 MP, f/2.2, 120˚',
      telephotoCamera: '2 MP macro, f/2.4',
      frontCamera: '16 MP, f/2.45',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 67,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.91 x 76.03 x 7.9 mm',
      weight: 181,
      materials: 'Glass front (Gorilla Glass 5), plastic frame and back',
      waterResistance: 'IP53',
      colors: ['Yellow', 'Astral Black', 'Horizon Blue'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MIUI 14 for POCO',
      launchOS: 'Android 12',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.poco.in/x5-pro-5g',
      productPage: 'https://www.flipkart.com/poco-x5-pro-5g/p/itm556',
      specSheetUrl: 'https://www.poco.in/x5-pro-5g/specs',
      verifiedDate: '2023-02',
    },
  },

  // ── POCO M SERIES (Mainstream Budget 5G) ──
  {
    id: 'poco-m6-plus-5g',
    slug: 'poco-m6-plus-5g',
    brand: 'POCO',
    modelName: 'POCO M6 Plus 5G',
    generation: 'M6',
    status: 'active',
    launchDate: '2024-08',
    pricing: {
      startingPrice: 11999,
      maximumPrice: 13499,
      mrp: 12999,
      currentPrice: 11999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Flipkart / POCO India',
    },
    display: {
      displaySize: 6.79,
      displayType: 'IPS LCD, 120Hz',
      resolution: '2460 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 550,
      hdr: 'None',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '85.1%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 4 Gen 2 AE (4nm)',
      cpu: 'Octa-core (2x2.3 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Adreno 613',
      ramOptions: ['6GB', '8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 430000,
    },
    cameras: {
      rearCameraSetup: 'Dual (108MP + 2MP)',
      mainCamera: '108 MP Samsung HM6, f/1.75, 3x in-sensor zoom',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP macro, f/2.4',
      frontCamera: '13 MP, f/2.45',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5030,
      wiredCharging: 33,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '168.6 x 76.28 x 8.3 mm',
      weight: 205,
      materials: 'Dual-sided glass design (Gorilla Glass 3 front, glass back)',
      waterResistance: 'IP53',
      colors: ['Ice Silver', 'Graphite Black', 'Misty Lavender'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Xiaomi HyperOS',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.poco.in/m6-plus-5g',
      productPage: 'https://www.flipkart.com/poco-m6-plus-5g/p/itm126',
      specSheetUrl: 'https://www.poco.in/m6-plus-5g/specs',
      verifiedDate: '2024-08',
    },
  },

  {
    id: 'poco-m6-pro-5g',
    slug: 'poco-m6-pro-5g',
    brand: 'POCO',
    modelName: 'POCO M6 Pro 5G',
    generation: 'M6',
    status: 'active',
    launchDate: '2023-08',
    pricing: {
      startingPrice: 9999,
      maximumPrice: 11999,
      mrp: 10999,
      currentPrice: 9999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Flipkart / POCO India',
    },
    display: {
      displaySize: 6.79,
      displayType: 'IPS LCD, 90Hz',
      resolution: '2460 x 1080 pixels (FHD+)',
      refreshRate: 90,
      peakBrightness: 550,
      hdr: 'None',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '85.1%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 4 Gen 2 (4nm)',
      cpu: 'Octa-core (2x2.2 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Adreno 613',
      ramOptions: ['4GB', '6GB', '8GB'],
      storageOptions: ['64GB', '128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 420000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP)',
      mainCamera: '50 MP, f/1.8',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP depth sensor',
      frontCamera: '8 MP, f/2.0',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 18,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '168.6 x 76.28 x 8.17 mm',
      weight: 199,
      materials: 'Glass front (Gorilla Glass 3), plastic frame, glass back',
      waterResistance: 'IP53',
      colors: ['Forest Green', 'Power Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MIUI 14 for POCO (upgraded to HyperOS)',
      launchOS: 'Android 13',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.poco.in/m6-pro-5g',
      productPage: 'https://www.flipkart.com/poco-m6-pro-5g/p/itm557',
      specSheetUrl: 'https://www.poco.in/m6-pro-5g/specs',
      verifiedDate: '2023-08',
    },
  },

  {
    id: 'poco-m6-5g',
    slug: 'poco-m6-5g',
    brand: 'POCO',
    modelName: 'POCO M6 5G',
    generation: 'M6',
    status: 'active',
    launchDate: '2023-12',
    pricing: {
      startingPrice: 8999,
      maximumPrice: 10999,
      mrp: 9999,
      currentPrice: 8999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Flipkart / POCO India',
    },
    display: {
      displaySize: 6.74,
      displayType: 'IPS LCD, 90Hz',
      resolution: '1600 x 720 pixels (HD+)',
      refreshRate: 90,
      peakBrightness: 600,
      hdr: 'None',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '83.8%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6100+ (6nm)',
      cpu: 'Octa-core (2x2.2 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['4GB', '6GB', '8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 415000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 0.08MP auxiliary lens)',
      mainCamera: '50 MP, f/1.8',
      ultrawideCamera: 'None',
      telephotoCamera: 'None',
      frontCamera: '5 MP, f/2.2',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 18,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM + microSD dedicated',
    },
    physical: {
      dimensions: '168 x 78 x 8.09 mm',
      weight: 195,
      materials: 'Glass front, plastic frame, star-trail patterned plastic back',
      waterResistance: 'Splash resistant',
      colors: ['Galactic Black', 'Orion Blue', 'Polaris Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MIUI 14 for POCO (upgraded to HyperOS)',
      launchOS: 'Android 13',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.poco.in/m6-5g',
      productPage: 'https://www.flipkart.com/poco-m6-5g/p/itm558',
      specSheetUrl: 'https://www.poco.in/m6-5g/specs',
      verifiedDate: '2023-12',
    },
  },

  // ── POCO C SERIES (Entry Level) ──
  {
    id: 'poco-c65',
    slug: 'poco-c65',
    brand: 'POCO',
    modelName: 'POCO C65',
    generation: 'C65',
    status: 'active',
    launchDate: '2023-12',
    pricing: {
      startingPrice: 6999,
      maximumPrice: 8499,
      mrp: 8499,
      currentPrice: 6999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Flipkart / POCO India',
    },
    display: {
      displaySize: 6.74,
      displayType: 'IPS LCD, 90Hz',
      resolution: '1600 x 720 pixels (HD+)',
      refreshRate: 90,
      peakBrightness: 600,
      hdr: 'None',
      protection: 'Corning Gorilla Glass',
      screenToBodyRatio: '83.7%',
    },
    performance: {
      chipset: 'MediaTek Helio G85 (12nm)',
      cpu: 'Octa-core (2x2.0 GHz Cortex-A75 & 6x1.8 GHz Cortex-A55)',
      gpu: 'Mali-G52 MC2',
      ramOptions: ['4GB', '6GB', '8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'eMMC 5.1',
      antutuScore: 260000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 2MP + 0.08MP)',
      mainCamera: '50 MP, f/1.8',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP macro, f/2.4',
      frontCamera: '8 MP, f/2.0',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 18,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: false,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM + microSD dedicated',
    },
    physical: {
      dimensions: '168 x 78 x 8.09 mm',
      weight: 192,
      materials: 'Glass front, plastic frame and back',
      waterResistance: 'Splash resistant',
      colors: ['Matte Black', 'Pastel Blue', 'Pastel Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MIUI 14 for POCO (upgraded to HyperOS)',
      launchOS: 'Android 13',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.poco.in/c65',
      productPage: 'https://www.flipkart.com/poco-c65/p/itm559',
      specSheetUrl: 'https://www.poco.in/c65/specs',
      verifiedDate: '2023-12',
    },
  },

  {
    id: 'poco-c61',
    slug: 'poco-c61',
    brand: 'POCO',
    modelName: 'POCO C61',
    generation: 'C61',
    status: 'active',
    launchDate: '2024-03',
    pricing: {
      startingPrice: 5999,
      maximumPrice: 6999,
      mrp: 6999,
      currentPrice: 5999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Flipkart / POCO India',
    },
    display: {
      displaySize: 6.71,
      displayType: 'IPS LCD, 90Hz',
      resolution: '1650 x 720 pixels (HD+)',
      refreshRate: 90,
      peakBrightness: 500,
      hdr: 'None',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '82.9%',
    },
    performance: {
      chipset: 'MediaTek Helio G36 (12nm)',
      cpu: 'Octa-core (4x2.2 GHz Cortex-A53 & 4x1.6 GHz Cortex-A53)',
      gpu: 'PowerVR GE8320',
      ramOptions: ['4GB', '6GB'],
      storageOptions: ['64GB', '128GB'],
      storageType: 'eMMC 5.1',
      antutuScore: 145000,
    },
    cameras: {
      rearCameraSetup: 'Dual (8MP + 0.08MP auxiliary lens)',
      mainCamera: '8 MP, f/2.0',
      ultrawideCamera: 'None',
      telephotoCamera: 'None',
      frontCamera: '5 MP, f/2.2',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 10,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: false,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.4',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM + microSD dedicated',
    },
    physical: {
      dimensions: '168.4 x 76.3 x 8.3 mm',
      weight: 199,
      materials: 'Glass front (Gorilla Glass 3), radiant ring glass back',
      waterResistance: 'None',
      colors: ['Mystical Green', 'Ethereal Blue', 'Diamond Dust Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Android 14 (Go Edition)',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.poco.in/c61',
      productPage: 'https://www.flipkart.com/poco-c61/p/itm560',
      specSheetUrl: 'https://www.poco.in/c61/specs',
      verifiedDate: '2024-03',
    },
  },
];

const variants: MobileVariant[] = [
  // POCO F6 5G
  {
    id: 'poco-f6-5g-8-256',
    modelId: 'poco-f6-5g',
    ram: '8GB',
    storage: '256GB',
    price: 29999,
    mrp: 29999,
    status: 'active',
    verified: true,
    source: 'Flipkart / POCO India',
    colors: ['Titanium', 'Black'],
  },
  {
    id: 'poco-f6-5g-12-512',
    modelId: 'poco-f6-5g',
    ram: '12GB',
    storage: '512GB',
    price: 33999,
    mrp: 33999,
    status: 'active',
    verified: true,
    source: 'Flipkart / POCO India',
    colors: ['Titanium', 'Black'],
  },
  // POCO F5 5G
  {
    id: 'poco-f5-5g-8-256',
    modelId: 'poco-f5-5g',
    ram: '8GB',
    storage: '256GB',
    price: 26999,
    mrp: 29999,
    status: 'discontinued',
    verified: true,
    source: 'Flipkart / POCO India',
    colors: ['Carbon Black', 'Snowstorm White'],
  },
  {
    id: 'poco-f5-5g-12-256',
    modelId: 'poco-f5-5g',
    ram: '12GB',
    storage: '256GB',
    price: 29999,
    mrp: 33999,
    status: 'discontinued',
    verified: true,
    source: 'Flipkart / POCO India',
    colors: ['Carbon Black', 'Snowstorm White'],
  },
  // POCO F4 5G
  {
    id: 'poco-f4-5g-6-128',
    modelId: 'poco-f4-5g',
    ram: '6GB',
    storage: '128GB',
    price: 23999,
    mrp: 27999,
    status: 'discontinued',
    verified: true,
    source: 'Flipkart / POCO India',
    colors: ['Night Black', 'Nebula Green'],
  },
  {
    id: 'poco-f4-5g-8-128',
    modelId: 'poco-f4-5g',
    ram: '8GB',
    storage: '128GB',
    price: 25999,
    mrp: 29999,
    status: 'discontinued',
    verified: true,
    source: 'Flipkart / POCO India',
    colors: ['Night Black', 'Nebula Green'],
  },
  // POCO X6 Pro 5G
  {
    id: 'poco-x6-pro-5g-8-256',
    modelId: 'poco-x6-pro-5g',
    ram: '8GB',
    storage: '256GB',
    price: 23999,
    mrp: 26999,
    status: 'active',
    verified: true,
    source: 'Flipkart / POCO India',
    colors: ['POCO Yellow', 'Racing Grey'],
  },
  {
    id: 'poco-x6-pro-5g-12-512',
    modelId: 'poco-x6-pro-5g',
    ram: '12GB',
    storage: '512GB',
    price: 25999,
    mrp: 28999,
    status: 'active',
    verified: true,
    source: 'Flipkart / POCO India',
    colors: ['POCO Yellow', 'Racing Grey'],
  },
  // POCO X6 5G
  {
    id: 'poco-x6-5g-8-256',
    modelId: 'poco-x6-5g',
    ram: '8GB',
    storage: '256GB',
    price: 17999,
    mrp: 21999,
    status: 'active',
    verified: true,
    source: 'Flipkart / POCO India',
    colors: ['Mirror Black', 'Snowstorm White'],
  },
  {
    id: 'poco-x6-5g-12-512',
    modelId: 'poco-x6-5g',
    ram: '12GB',
    storage: '512GB',
    price: 20999,
    mrp: 24999,
    status: 'active',
    verified: true,
    source: 'Flipkart / POCO India',
    colors: ['Mirror Black', 'Snowstorm White'],
  },
  // POCO X6 Neo 5G
  {
    id: 'poco-x6-neo-5g-8-128',
    modelId: 'poco-x6-neo-5g',
    ram: '8GB',
    storage: '128GB',
    price: 13999,
    mrp: 15999,
    status: 'active',
    verified: true,
    source: 'Flipkart / POCO India',
    colors: ['Martian Orange', 'Astral Black'],
  },
  {
    id: 'poco-x6-neo-5g-12-256',
    modelId: 'poco-x6-neo-5g',
    ram: '12GB',
    storage: '256GB',
    price: 15999,
    mrp: 17999,
    status: 'active',
    verified: true,
    source: 'Flipkart / POCO India',
    colors: ['Martian Orange', 'Astral Black'],
  },
  // POCO X5 Pro 5G
  {
    id: 'poco-x5-pro-5g-6-128',
    modelId: 'poco-x5-pro-5g',
    ram: '6GB',
    storage: '128GB',
    price: 18999,
    mrp: 22999,
    status: 'discontinued',
    verified: true,
    source: 'Flipkart / POCO India',
    colors: ['Yellow', 'Astral Black'],
  },
  {
    id: 'poco-x5-pro-5g-8-256',
    modelId: 'poco-x5-pro-5g',
    ram: '8GB',
    storage: '256GB',
    price: 20999,
    mrp: 24999,
    status: 'discontinued',
    verified: true,
    source: 'Flipkart / POCO India',
    colors: ['Yellow', 'Astral Black'],
  },
  // POCO M6 Plus 5G
  {
    id: 'poco-m6-plus-5g-6-128',
    modelId: 'poco-m6-plus-5g',
    ram: '6GB',
    storage: '128GB',
    price: 11999,
    mrp: 12999,
    status: 'active',
    verified: true,
    source: 'Flipkart / POCO India',
    colors: ['Ice Silver', 'Graphite Black'],
  },
  {
    id: 'poco-m6-plus-5g-8-128',
    modelId: 'poco-m6-plus-5g',
    ram: '8GB',
    storage: '128GB',
    price: 13499,
    mrp: 14499,
    status: 'active',
    verified: true,
    source: 'Flipkart / POCO India',
    colors: ['Ice Silver', 'Graphite Black'],
  },
  // POCO M6 Pro 5G
  {
    id: 'poco-m6-pro-5g-4-64',
    modelId: 'poco-m6-pro-5g',
    ram: '4GB',
    storage: '64GB',
    price: 9999,
    mrp: 10999,
    status: 'active',
    verified: true,
    source: 'Flipkart / POCO India',
    colors: ['Forest Green', 'Power Black'],
  },
  {
    id: 'poco-m6-pro-5g-6-128',
    modelId: 'poco-m6-pro-5g',
    ram: '6GB',
    storage: '128GB',
    price: 10999,
    mrp: 12999,
    status: 'active',
    verified: true,
    source: 'Flipkart / POCO India',
    colors: ['Forest Green', 'Power Black'],
  },
  // POCO M6 5G
  {
    id: 'poco-m6-5g-4-128',
    modelId: 'poco-m6-5g',
    ram: '4GB',
    storage: '128GB',
    price: 8999,
    mrp: 9999,
    status: 'active',
    verified: true,
    source: 'Flipkart / POCO India',
    colors: ['Galactic Black', 'Orion Blue'],
  },
  {
    id: 'poco-m6-5g-8-256',
    modelId: 'poco-m6-5g',
    ram: '8GB',
    storage: '256GB',
    price: 10999,
    mrp: 12499,
    status: 'active',
    verified: true,
    source: 'Flipkart / POCO India',
    colors: ['Galactic Black', 'Orion Blue'],
  },
  // POCO C65
  {
    id: 'poco-c65-4-128',
    modelId: 'poco-c65',
    ram: '4GB',
    storage: '128GB',
    price: 6999,
    mrp: 8499,
    status: 'active',
    verified: true,
    source: 'Flipkart / POCO India',
    colors: ['Matte Black', 'Pastel Blue'],
  },
  {
    id: 'poco-c65-8-256',
    modelId: 'poco-c65',
    ram: '8GB',
    storage: '256GB',
    price: 8499,
    mrp: 9999,
    status: 'active',
    verified: true,
    source: 'Flipkart / POCO India',
    colors: ['Matte Black', 'Pastel Blue'],
  },
  // POCO C61
  {
    id: 'poco-c61-4-64',
    modelId: 'poco-c61',
    ram: '4GB',
    storage: '64GB',
    price: 5999,
    mrp: 6999,
    status: 'active',
    verified: true,
    source: 'Flipkart / POCO India',
    colors: ['Mystical Green', 'Diamond Dust Black'],
  },
  {
    id: 'poco-c61-6-128',
    modelId: 'poco-c61',
    ram: '6GB',
    storage: '128GB',
    price: 6999,
    mrp: 7999,
    status: 'active',
    verified: true,
    source: 'Flipkart / POCO India',
    colors: ['Mystical Green', 'Diamond Dust Black'],
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    "modelId": "poco-f6-5g",
    "modelName": "POCO F6 5G",
    "brand": "POCO",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-f6.jpg",
        "angle": "front",
        "source": "POCO Official / GSMArena Verified",
        "sourceUrl": "https://www.poco.in/f6-5g",
        "verified": true,
        "alt": "POCO POCO F6 5G official product photography"
      }
    ]
  },
  {
    "modelId": "poco-f5-5g",
    "modelName": "POCO F5 5G",
    "brand": "POCO",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-f5-2.jpg",
        "angle": "front",
        "source": "POCO Official / GSMArena Verified",
        "sourceUrl": "https://www.poco.in/f5-5g",
        "verified": true,
        "alt": "POCO POCO F5 5G official product photography"
      }
    ]
  },
  {
    "modelId": "poco-f4-5g",
    "modelName": "POCO F4 5G",
    "brand": "POCO",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-f4-5g.jpg",
        "angle": "front",
        "source": "POCO Official / GSMArena Verified",
        "sourceUrl": "https://www.poco.in/f4-5g",
        "verified": true,
        "alt": "POCO POCO F4 5G official product photography"
      }
    ]
  },
  {
    "modelId": "poco-x6-pro-5g",
    "modelName": "POCO X6 Pro 5G",
    "brand": "POCO",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-x6-pro.jpg",
        "angle": "front",
        "source": "POCO Official / GSMArena Verified",
        "sourceUrl": "https://www.poco.in/x6-pro-5g",
        "verified": true,
        "alt": "POCO POCO X6 Pro 5G official product photography"
      }
    ]
  },
  {
    "modelId": "poco-x6-5g",
    "modelName": "POCO X6 5G",
    "brand": "POCO",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-x6-5g.jpg",
        "angle": "front",
        "source": "POCO Official / GSMArena Verified",
        "sourceUrl": "https://www.poco.in/x6-5g",
        "verified": true,
        "alt": "POCO POCO X6 5G official product photography"
      }
    ]
  },
  {
    "modelId": "poco-x6-neo-5g",
    "modelName": "POCO X6 Neo 5G",
    "brand": "POCO",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-x6-neo.jpg",
        "angle": "front",
        "source": "POCO Official / GSMArena Verified",
        "sourceUrl": "https://www.poco.in/x6-neo-5g",
        "verified": true,
        "alt": "POCO POCO X6 Neo 5G official product photography"
      }
    ]
  },
  {
    "modelId": "poco-x5-pro-5g",
    "modelName": "POCO X5 Pro 5G",
    "brand": "POCO",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-x5-pro-5g.jpg",
        "angle": "front",
        "source": "POCO Official / GSMArena Verified",
        "sourceUrl": "https://www.poco.in/x5-pro-5g",
        "verified": true,
        "alt": "POCO POCO X5 Pro 5G official product photography"
      }
    ]
  },
  {
    "modelId": "poco-m6-plus-5g",
    "modelName": "POCO M6 Plus 5G",
    "brand": "POCO",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-m6-plus.jpg",
        "angle": "front",
        "source": "POCO Official / GSMArena Verified",
        "sourceUrl": "https://www.poco.in/m6-plus-5g",
        "verified": true,
        "alt": "POCO POCO M6 Plus 5G official product photography"
      }
    ]
  },
  {
    "modelId": "poco-m6-pro-5g",
    "modelName": "POCO M6 Pro 5G",
    "brand": "POCO",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-m6-pro-5g.jpg",
        "angle": "front",
        "source": "POCO Official / GSMArena Verified",
        "sourceUrl": "https://www.poco.in/m6-pro-5g",
        "verified": true,
        "alt": "POCO POCO M6 Pro 5G official product photography"
      }
    ]
  },
  {
    "modelId": "poco-m6-5g",
    "modelName": "POCO M6 5G",
    "brand": "POCO",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-m6-5g.jpg",
        "angle": "front",
        "source": "POCO Official / GSMArena Verified",
        "sourceUrl": "https://www.poco.in/m6-5g",
        "verified": true,
        "alt": "POCO POCO M6 5G official product photography"
      }
    ]
  },
  {
    "modelId": "poco-c65",
    "modelName": "POCO C65",
    "brand": "POCO",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-c65.jpg",
        "angle": "front",
        "source": "POCO Official / GSMArena Verified",
        "sourceUrl": "https://www.poco.in/c65",
        "verified": true,
        "alt": "POCO POCO C65 official product photography"
      }
    ]
  },
  {
    "modelId": "poco-c61",
    "modelName": "POCO C61",
    "brand": "POCO",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-c61.jpg",
        "angle": "front",
        "source": "POCO Official / GSMArena Verified",
        "sourceUrl": "https://www.poco.in/c61",
        "verified": true,
        "alt": "POCO POCO C61 official product photography"
      }
    ]
  }
];

export const pocoBundle: MobileBrandBundle = {
  brand: 'POCO',
  models,
  variants,
  images,
};
