import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  // ── REALME GT SERIES (Performance Flagships) ──
  {
    id: 'realme-gt-7-pro',
    slug: 'realme-gt-7-pro',
    brand: 'realme',
    modelName: 'realme GT 7 Pro',
    generation: 'GT 7',
    status: 'active',
    launchDate: '2024-11',
    pricing: {
      startingPrice: 59999,
      maximumPrice: 65999,
      launchPrice: 59999,
      currentPrice: 59999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Amazon India / realme India',
    },
    display: {
      displaySize: 6.78,
      displayType: 'Eco2 OLED Plus (Samsung), 120Hz, Dolby Vision, HDR10+',
      resolution: '2780 x 1264 pixels (1.5K)',
      refreshRate: 120,
      peakBrightness: 6000,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Armor Glass',
      screenToBodyRatio: '90.4%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Elite (3nm)',
      cpu: 'Octa-core (2x4.32 GHz Oryon V2 Phoenix L & 6x3.53 GHz Oryon V2 Phoenix M)',
      gpu: 'Adreno 830',
      ramOptions: ['12GB', '16GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 2950000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 8MP) Underwater Photography',
      mainCamera: '50 MP Sony IMX906, 1/1.56", f/1.8, OIS',
      ultrawideCamera: '8 MP Sony IMX355, f/2.2, 112˚',
      telephotoCamera: '50 MP Sony LYT-600 3x periscope telephoto, 73mm, OIS',
      frontCamera: '16 MP, f/2.45',
      videoRecording: '8K@24fps, 4K@60fps, Dolby Vision HDR',
      ois: true,
    },
    battery: {
      batteryCapacity: 5800,
      wiredCharging: 120,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.45 x 76.89 x 8.55 mm',
      weight: 222.8,
      materials: 'Glass front, aviation aluminum frame, Mars design textured back',
      waterResistance: 'IP68/IP69',
      colors: ['Mars Orange', 'Galaxy Grey'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'realme UI 6.0',
      launchOS: 'Android 15',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: '3D Ultrasonic under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.realme.com/in/realme-gt-7-pro',
      productPage: 'https://buy.realme.com/in/goods/729',
      specSheetUrl: 'https://www.realme.com/in/realme-gt-7-pro/specs',
      verifiedDate: '2024-11',
    },
  },

  {
    id: 'realme-gt-6',
    slug: 'realme-gt-6',
    brand: 'realme',
    modelName: 'realme GT 6',
    generation: 'GT 6',
    status: 'active',
    launchDate: '2024-06',
    pricing: {
      startingPrice: 38999,
      maximumPrice: 42999,
      launchPrice: 40999,
      currentPrice: 38999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Amazon India / realme India',
    },
    display: {
      displaySize: 6.78,
      displayType: '8T LTPO AMOLED, 120Hz, Dolby Vision, HDR10+',
      resolution: '2780 x 1264 pixels (1.5K)',
      refreshRate: 120,
      peakBrightness: 6000,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '89.8%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8s Gen 3 (4nm)',
      cpu: 'Octa-core (1x3.0 GHz Cortex-X4 & 4x2.8 GHz & 3x2.0 GHz)',
      gpu: 'Adreno 735',
      ramOptions: ['8GB', '12GB', '16GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 1610000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 8MP) SuperOIS',
      mainCamera: '50 MP Sony LYT-808, 1/1.4", f/1.69, OIS',
      ultrawideCamera: '8 MP Sony IMX355, f/2.2, 112˚',
      telephotoCamera: '50 MP Samsung JN5 2x telephoto, f/2.0, 47mm',
      frontCamera: '32 MP Sony IMX615, f/2.45',
      videoRecording: '4K@60fps, 1080p@60fps, Dolby Vision',
      ois: true,
    },
    battery: {
      batteryCapacity: 5500,
      wiredCharging: 120,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.0 x 75.1 x 8.6 mm',
      weight: 199,
      materials: 'Glass front (Victus 2), plastic frame, nano-mirror finish back',
      waterResistance: 'IP65',
      colors: ['Fluid Silver', 'Razor Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'realme UI 5.0 (AI Smart Removal, AI Night Vision)',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.realme.com/in/realme-gt-6',
      productPage: 'https://buy.realme.com/in/goods/708',
      specSheetUrl: 'https://www.realme.com/in/realme-gt-6/specs',
      verifiedDate: '2024-06',
    },
  },

  {
    id: 'realme-gt-6t',
    slug: 'realme-gt-6t',
    brand: 'realme',
    modelName: 'realme GT 6T',
    generation: 'GT 6',
    status: 'active',
    launchDate: '2024-05',
    pricing: {
      startingPrice: 30999,
      maximumPrice: 35999,
      launchPrice: 30999,
      currentPrice: 30999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Amazon India / realme India',
    },
    display: {
      displaySize: 6.78,
      displayType: '8T LTPO AMOLED, 120Hz, HDR10+',
      resolution: '2780 x 1264 pixels (1.5K)',
      refreshRate: 120,
      peakBrightness: 6000,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '89.8%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7+ Gen 3 (4nm)',
      cpu: 'Octa-core (1x2.8 GHz Cortex-X4 & 4x2.6 GHz & 3x1.9 GHz)',
      gpu: 'Adreno 732',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB', '512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 1450000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 8MP)',
      mainCamera: '50 MP Sony LYT-600, f/1.88, OIS',
      ultrawideCamera: '8 MP Sony IMX355, f/2.2, 112˚',
      telephotoCamera: 'None',
      frontCamera: '32 MP Sony IMX615, f/2.45',
      videoRecording: '4K@60fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5500,
      wiredCharging: 120,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.0 x 75.1 x 8.65 mm',
      weight: 191,
      materials: 'Glass front (Victus 2), plastic frame and mirror finish back',
      waterResistance: 'IP65',
      colors: ['Fluid Silver', 'Razor Green', 'Miracle Purple'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'realme UI 5.0',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.realme.com/in/realme-gt-6t',
      productPage: 'https://buy.realme.com/in/goods/706',
      specSheetUrl: 'https://www.realme.com/in/realme-gt-6t/specs',
      verifiedDate: '2024-05',
    },
  },

  // ── REALME NUMBERED SERIES (Premium Mid-Range) ──
  {
    id: 'realme-13-pro-plus-5g',
    slug: 'realme-13-pro-plus-5g',
    brand: 'realme',
    modelName: 'realme 13 Pro+ 5G',
    generation: '13',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 29999,
      maximumPrice: 34999,
      launchPrice: 32999,
      currentPrice: 29999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Flipkart / realme India',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Curved AMOLED, 120Hz, 1B colors',
      resolution: '2412 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 2000,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass 7i',
      screenToBodyRatio: '93.0%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7s Gen 2 (4nm)',
      cpu: 'Octa-core (4x2.40 GHz Cortex-A78 & 4x1.95 GHz Cortex-A55)',
      gpu: 'Adreno 710',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 3.1',
      antutuScore: 610000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 8MP) Monet Design / Dual Sony Lytia',
      mainCamera: '50 MP Sony LYT-701, 1/1.56", f/1.88, OIS',
      ultrawideCamera: '8 MP, f/2.2, 112˚',
      telephotoCamera: '50 MP Sony LYT-600 3x periscope telephoto, 73mm, OIS',
      frontCamera: '32 MP Sony, f/2.45',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5200,
      wiredCharging: 80,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.34 x 73.91 x 8.23 mm',
      weight: 185.5,
      materials: 'Glass front (Gorilla Glass 7i), vegan leather / Monet-inspired glass back',
      waterResistance: 'IP65',
      colors: ['Monet Gold', 'Emerald Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'realme UI 5.0 (AI Ultra Clarity, AI Smart Removal)',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Hi-Res Audio',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.realme.com/in/realme-13-pro-plus',
      productPage: 'https://buy.realme.com/in/goods/713',
      specSheetUrl: 'https://www.realme.com/in/realme-13-pro-plus/specs',
      verifiedDate: '2024-07',
    },
  },

  {
    id: 'realme-13-pro-5g',
    slug: 'realme-13-pro-5g',
    brand: 'realme',
    modelName: 'realme 13 Pro 5G',
    generation: '13',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 26999,
      maximumPrice: 29999,
      launchPrice: 26999,
      currentPrice: 26999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Flipkart / realme India',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Curved AMOLED, 120Hz',
      resolution: '2412 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 2000,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass 7i',
      screenToBodyRatio: '93.0%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7s Gen 2 (4nm)',
      cpu: 'Octa-core (4x2.40 GHz Cortex-A78 & 4x1.95 GHz Cortex-A55)',
      gpu: 'Adreno 710',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 610000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 8MP)',
      mainCamera: '50 MP Sony LYT-600, f/1.88, OIS',
      ultrawideCamera: '8 MP, f/2.2, 112˚',
      telephotoCamera: 'None',
      frontCamera: '32 MP, f/2.45',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5200,
      wiredCharging: 45,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.34 x 73.91 x 8.23 mm',
      weight: 183.5,
      materials: 'Glass front (Gorilla Glass 7i), Monet inspired glass/leather back',
      waterResistance: 'IP65',
      colors: ['Monet Gold', 'Monet Purple', 'Emerald Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'realme UI 5.0',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.realme.com/in/realme-13-pro',
      productPage: 'https://buy.realme.com/in/goods/712',
      specSheetUrl: 'https://www.realme.com/in/realme-13-pro/specs',
      verifiedDate: '2024-07',
    },
  },

  {
    id: 'realme-13-plus-5g',
    slug: 'realme-13-plus-5g',
    brand: 'realme',
    modelName: 'realme 13+ 5G',
    generation: '13',
    status: 'active',
    launchDate: '2024-08',
    pricing: {
      startingPrice: 22999,
      maximumPrice: 26999,
      launchPrice: 22999,
      currentPrice: 22999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Flipkart / realme India',
    },
    display: {
      displaySize: 6.67,
      displayType: 'OLED Esports Display, 120Hz',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 2000,
      hdr: 'HDR10+',
      protection: 'Toughened Glass',
      screenToBodyRatio: '88.9%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7300 Energy (4nm)',
      cpu: 'Octa-core (4x2.5 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G615 MC2 (90fps gaming in major titles)',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 750000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP)',
      mainCamera: '50 MP Sony LYT-600, f/1.8, OIS',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP depth sensor',
      frontCamera: '16 MP, f/2.4',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 80,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.4',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '161.7 x 74.7 x 7.6 mm',
      weight: 185,
      materials: 'Glass front, victory speed textured polycarbonate back',
      waterResistance: 'IP65',
      colors: ['Victory Gold', 'Speed Green', 'Dark Purple'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'realme UI 5.0',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.realme.com/in/realme-13-plus-5g',
      productPage: 'https://buy.realme.com/in/goods/717',
      specSheetUrl: 'https://www.realme.com/in/realme-13-plus-5g/specs',
      verifiedDate: '2024-08',
    },
  },

  {
    id: 'realme-13-5g',
    slug: 'realme-13-5g',
    brand: 'realme',
    modelName: 'realme 13 5G',
    generation: '13',
    status: 'active',
    launchDate: '2024-08',
    pricing: {
      startingPrice: 17999,
      maximumPrice: 19999,
      launchPrice: 17999,
      currentPrice: 17999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Flipkart / realme India',
    },
    display: {
      displaySize: 6.72,
      displayType: 'IPS LCD, 120Hz',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 580,
      hdr: 'None',
      protection: 'Toughened Glass',
      screenToBodyRatio: '86.5%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6300 (6nm)',
      cpu: 'Octa-core (2x2.4 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 430000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP)',
      mainCamera: '50 MP, f/1.8, OIS',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP depth sensor',
      frontCamera: '16 MP, f/2.45',
      videoRecording: '1080p@30fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 45,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '165.6 x 76.1 x 7.79 mm',
      weight: 190,
      materials: 'Glass front, speed halo textured back',
      waterResistance: 'IP64',
      colors: ['Speed Green', 'Dark Purple'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'realme UI 5.0',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.realme.com/in/realme-13-5g',
      productPage: 'https://buy.realme.com/in/goods/716',
      specSheetUrl: 'https://www.realme.com/in/realme-13-5g/specs',
      verifiedDate: '2024-08',
    },
  },

  {
    id: 'realme-12-pro-plus-5g',
    slug: 'realme-12-pro-plus-5g',
    brand: 'realme',
    modelName: 'realme 12 Pro+ 5G',
    generation: '12',
    status: 'discontinued',
    launchDate: '2024-01',
    pricing: {
      startingPrice: 27999,
      maximumPrice: 31999,
      launchPrice: 29999,
      currentPrice: 27999,
      currency: 'INR',
      priceEffectiveDate: '2024-09',
      source: 'Flipkart / realme India',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Curved AMOLED, 120Hz, 1B colors',
      resolution: '2412 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 950,
      hdr: 'None',
      protection: 'Toughened Glass',
      screenToBodyRatio: '93.0%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7s Gen 2 (4nm)',
      cpu: 'Octa-core (4x2.40 GHz Cortex-A78 & 4x1.95 GHz Cortex-A55)',
      gpu: 'Adreno 710',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 600000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 64MP + 8MP) Luxury Watch Design',
      mainCamera: '50 MP Sony IMX890, f/1.8, OIS',
      ultrawideCamera: '8 MP, f/2.2, 112˚',
      telephotoCamera: '64 MP OmniVision OV64B 3x periscope telephoto, 71mm, OIS',
      frontCamera: '32 MP Sony, f/2.4',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 67,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.47 x 74.02 x 8.75 mm',
      weight: 196,
      materials: 'Glass front, luxury watch fluted bezel, vegan leather back',
      waterResistance: 'IP65',
      colors: ['Submarine Blue', 'Navigator Beige', 'Explorer Red'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'realme UI 5.0',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.realme.com/in/realme-12-pro-plus',
      productPage: 'https://buy.realme.com/in/goods/682',
      specSheetUrl: 'https://www.realme.com/in/realme-12-pro-plus/specs',
      verifiedDate: '2024-01',
    },
  },

  {
    id: 'realme-12-pro-5g',
    slug: 'realme-12-pro-5g',
    brand: 'realme',
    modelName: 'realme 12 Pro 5G',
    generation: '12',
    status: 'discontinued',
    launchDate: '2024-01',
    pricing: {
      startingPrice: 23999,
      maximumPrice: 25999,
      launchPrice: 25999,
      currentPrice: 23999,
      currency: 'INR',
      priceEffectiveDate: '2024-09',
      source: 'Flipkart / realme India',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Curved AMOLED, 120Hz',
      resolution: '2412 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 950,
      hdr: 'None',
      protection: 'Toughened Glass',
      screenToBodyRatio: '93.0%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 6 Gen 1 (4nm)',
      cpu: 'Octa-core (4x2.2 GHz Cortex-A78 & 4x1.8 GHz Cortex-A55)',
      gpu: 'Adreno 710',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 575000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 32MP + 8MP)',
      mainCamera: '50 MP Sony IMX882, f/1.8, OIS',
      ultrawideCamera: '8 MP, f/2.2, 112˚',
      telephotoCamera: '32 MP Sony IMX709 2x portrait telephoto, f/2.0',
      frontCamera: '16 MP, f/2.4',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 67,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.47 x 74.02 x 8.75 mm',
      weight: 190,
      materials: 'Glass front, fluted bezel, vegan leather back',
      waterResistance: 'IP65',
      colors: ['Submarine Blue', 'Navigator Beige'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'realme UI 5.0',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.realme.com/in/realme-12-pro',
      productPage: 'https://buy.realme.com/in/goods/681',
      specSheetUrl: 'https://www.realme.com/in/realme-12-pro/specs',
      verifiedDate: '2024-01',
    },
  },

  {
    id: 'realme-12-plus-5g',
    slug: 'realme-12-plus-5g',
    brand: 'realme',
    modelName: 'realme 12+ 5G',
    generation: '12',
    status: 'active',
    launchDate: '2024-03',
    pricing: {
      startingPrice: 18999,
      maximumPrice: 21999,
      launchPrice: 20999,
      currentPrice: 18999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Flipkart / realme India',
    },
    display: {
      displaySize: 6.67,
      displayType: 'AMOLED, 120Hz, HDR10+',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 2000,
      hdr: 'HDR10+',
      protection: 'Toughened Glass',
      screenToBodyRatio: '87.9%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7050 (6nm)',
      cpu: 'Octa-core (2x2.6 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G68 MC4',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 580000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 8MP + 2MP)',
      mainCamera: '50 MP Sony LYT-600, f/1.88, OIS',
      ultrawideCamera: '8 MP, f/2.2, 112˚',
      telephotoCamera: '2 MP macro, f/2.4',
      frontCamera: '16 MP, f/2.45',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 67,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '162.95 x 75.45 x 7.87 mm',
      weight: 190,
      materials: 'Glass front, flat metallic frame, premium vegan leather back',
      waterResistance: 'IP54',
      colors: ['Pioneer Green', 'Navigator Beige'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'realme UI 5.0',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.realme.com/in/realme-12-plus-5g',
      productPage: 'https://buy.realme.com/in/goods/690',
      specSheetUrl: 'https://www.realme.com/in/realme-12-plus-5g/specs',
      verifiedDate: '2024-03',
    },
  },

  {
    id: 'realme-12x-5g',
    slug: 'realme-12x-5g',
    brand: 'realme',
    modelName: 'realme 12x 5G',
    generation: '12',
    status: 'active',
    launchDate: '2024-04',
    pricing: {
      startingPrice: 11999,
      maximumPrice: 13999,
      launchPrice: 11999,
      currentPrice: 11999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Flipkart / realme India',
    },
    display: {
      displaySize: 6.72,
      displayType: 'IPS LCD, 120Hz',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 950,
      hdr: 'None',
      protection: 'Toughened Glass',
      screenToBodyRatio: '86.5%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6100+ (6nm)',
      cpu: 'Octa-core (2x2.2 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['4GB', '6GB', '8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 415000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP)',
      mainCamera: '50 MP, f/1.8',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP depth sensor',
      frontCamera: '8 MP, f/2.0',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 45,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '165.6 x 76.1 x 7.69 mm',
      weight: 188,
      materials: 'Glass front, feather pattern polycarbonate back',
      waterResistance: 'IP54',
      colors: ['Twilight Purple', 'Woodland Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'realme UI 5.0',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.realme.com/in/realme-12x-5g',
      productPage: 'https://buy.realme.com/in/goods/697',
      specSheetUrl: 'https://www.realme.com/in/realme-12x-5g/specs',
      verifiedDate: '2024-04',
    },
  },

  // ── REALME P SERIES (Flipkart Performance Line) ──
  {
    id: 'realme-p1-pro-5g',
    slug: 'realme-p1-pro-5g',
    brand: 'realme',
    modelName: 'realme P1 Pro 5G',
    generation: 'P1',
    status: 'active',
    launchDate: '2024-04',
    pricing: {
      startingPrice: 19999,
      maximumPrice: 21999,
      launchPrice: 21999,
      currentPrice: 19999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Flipkart / realme India',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Curved Vision AMOLED, 120Hz',
      resolution: '2412 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 950,
      hdr: 'None',
      protection: 'Toughened Glass',
      screenToBodyRatio: '93.0%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 6 Gen 1 (4nm)',
      cpu: 'Octa-core (4x2.2 GHz Cortex-A78 & 4x1.8 GHz Cortex-A55)',
      gpu: 'Adreno 710',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 575000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 8MP)',
      mainCamera: '50 MP Sony LYT-600, f/1.8, OIS',
      ultrawideCamera: '8 MP, f/2.2, 112˚',
      telephotoCamera: 'None',
      frontCamera: '16 MP, f/2.4',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 45,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.47 x 74.02 x 8.35 mm',
      weight: 184,
      materials: 'Glass front, Phoenix feather textured back',
      waterResistance: 'IP65',
      colors: ['Parrot Blue', 'Phoenix Red'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'realme UI 5.0',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.realme.com/in/realme-p1-pro-5g',
      productPage: 'https://buy.realme.com/in/goods/701',
      specSheetUrl: 'https://www.realme.com/in/realme-p1-pro-5g/specs',
      verifiedDate: '2024-04',
    },
  },

  {
    id: 'realme-p1-5g',
    slug: 'realme-p1-5g',
    brand: 'realme',
    modelName: 'realme P1 5G',
    generation: 'P1',
    status: 'active',
    launchDate: '2024-04',
    pricing: {
      startingPrice: 14999,
      maximumPrice: 16999,
      launchPrice: 15999,
      currentPrice: 14999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Flipkart / realme India',
    },
    display: {
      displaySize: 6.67,
      displayType: 'AMOLED, 120Hz',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 2000,
      hdr: 'None',
      protection: 'Toughened Glass',
      screenToBodyRatio: '87.9%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7050 (6nm)',
      cpu: 'Octa-core (2x2.6 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G68 MC4',
      ramOptions: ['6GB', '8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 603000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP)',
      mainCamera: '50 MP, f/1.8',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP depth sensor',
      frontCamera: '16 MP, f/2.45',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 45,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '162.95 x 75.45 x 7.91 mm',
      weight: 188,
      materials: 'Glass front, Phoenix feather design back',
      waterResistance: 'IP54',
      colors: ['Peacock Green', 'Phoenix Red'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'realme UI 5.0',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.realme.com/in/realme-p1-5g',
      productPage: 'https://buy.realme.com/in/goods/700',
      specSheetUrl: 'https://www.realme.com/in/realme-p1-5g/specs',
      verifiedDate: '2024-04',
    },
  },

  {
    id: 'realme-p2-pro-5g',
    slug: 'realme-p2-pro-5g',
    brand: 'realme',
    modelName: 'realme P2 Pro 5G',
    generation: 'P2',
    status: 'active',
    launchDate: '2024-09',
    pricing: {
      startingPrice: 21999,
      maximumPrice: 27999,
      launchPrice: 21999,
      currentPrice: 21999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Flipkart / realme India',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Curved AMOLED, 120Hz',
      resolution: '2412 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 2000,
      hdr: 'None',
      protection: 'Corning Gorilla Glass 7i',
      screenToBodyRatio: '93.0%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7s Gen 2 (4nm)',
      cpu: 'Octa-core (4x2.40 GHz Cortex-A78 & 4x1.95 GHz Cortex-A55)',
      gpu: 'Adreno 710',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB', '512GB'],
      storageType: 'UFS 3.1',
      antutuScore: 615000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 8MP)',
      mainCamera: '50 MP Sony LYT-600, f/1.88, OIS',
      ultrawideCamera: '8 MP, f/2.2, 112˚',
      telephotoCamera: 'None',
      frontCamera: '32 MP, f/2.45',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5200,
      wiredCharging: 80,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.34 x 73.91 x 8.21 mm',
      weight: 180,
      materials: 'Glass front (Gorilla Glass 7i), bio-crystal textured back',
      waterResistance: 'IP65',
      colors: ['Parrot Green', 'Eagle Grey'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'realme UI 5.0',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.realme.com/in/realme-p2-pro-5g',
      productPage: 'https://buy.realme.com/in/goods/722',
      specSheetUrl: 'https://www.realme.com/in/realme-p2-pro-5g/specs',
      verifiedDate: '2024-09',
    },
  },

  // ── NARZO SERIES (Amazon Exclusive) ──
  {
    id: 'realme-narzo-70-pro-5g',
    slug: 'realme-narzo-70-pro-5g',
    brand: 'realme',
    modelName: 'realme Narzo 70 Pro 5G',
    generation: 'Narzo 70',
    status: 'active',
    launchDate: '2024-03',
    pricing: {
      startingPrice: 18999,
      maximumPrice: 20999,
      launchPrice: 19999,
      currentPrice: 18999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Amazon India / realme India',
    },
    display: {
      displaySize: 6.67,
      displayType: 'AMOLED, 120Hz, HDR10+',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 2000,
      hdr: 'HDR10+',
      protection: 'Toughened Glass',
      screenToBodyRatio: '87.9%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7050 (6nm)',
      cpu: 'Octa-core (2x2.6 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G68 MC4',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 590000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 8MP + 2MP) with Air Gestures',
      mainCamera: '50 MP Sony IMX890, 1/1.56", f/1.88, OIS',
      ultrawideCamera: '8 MP, f/2.2, 112˚',
      telephotoCamera: '2 MP macro, f/2.4',
      frontCamera: '16 MP, f/2.45',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 67,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '162.95 x 75.45 x 7.97 mm',
      weight: 195,
      materials: 'Duo Touch glass design (first in segment glass back)',
      waterResistance: 'IP54',
      colors: ['Glass Green', 'Glass Gold'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'realme UI 5.0 (Creative Air Gestures support)',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.realme.com/in/realme-narzo-70-pro-5g',
      productPage: 'https://buy.realme.com/in/goods/695',
      specSheetUrl: 'https://www.realme.com/in/realme-narzo-70-pro-5g/specs',
      verifiedDate: '2024-03',
    },
  },

  {
    id: 'realme-narzo-70-turbo-5g',
    slug: 'realme-narzo-70-turbo-5g',
    brand: 'realme',
    modelName: 'realme Narzo 70 Turbo 5G',
    generation: 'Narzo 70',
    status: 'active',
    launchDate: '2024-09',
    pricing: {
      startingPrice: 16999,
      maximumPrice: 20999,
      launchPrice: 16999,
      currentPrice: 16999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Amazon India / realme India',
    },
    display: {
      displaySize: 6.67,
      displayType: 'OLED Esports Display, 120Hz',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 2000,
      hdr: 'HDR10+',
      protection: 'Toughened Glass',
      screenToBodyRatio: '88.9%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7300 Energy (4nm)',
      cpu: 'Octa-core (4x2.5 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G615 MC2 (90fps gaming)',
      ramOptions: ['6GB', '8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 750000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP)',
      mainCamera: '50 MP, f/1.8',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP depth sensor',
      frontCamera: '16 MP, f/2.4',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 45,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.4',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '161.7 x 74.7 x 7.6 mm',
      weight: 185,
      materials: 'Motorsport-inspired Turbo yellow stripes polycarbonate back',
      waterResistance: 'IP65',
      colors: ['Turbo Yellow', 'Turbo Green', 'Turbo Purple'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'realme UI 5.0',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.realme.com/in/realme-narzo-70-turbo-5g',
      productPage: 'https://buy.realme.com/in/goods/721',
      specSheetUrl: 'https://www.realme.com/in/realme-narzo-70-turbo-5g/specs',
      verifiedDate: '2024-09',
    },
  },

  {
    id: 'realme-narzo-70x-5g',
    slug: 'realme-narzo-70x-5g',
    brand: 'realme',
    modelName: 'realme Narzo 70x 5G',
    generation: 'Narzo 70',
    status: 'active',
    launchDate: '2024-04',
    pricing: {
      startingPrice: 11999,
      maximumPrice: 13499,
      launchPrice: 11999,
      currentPrice: 11999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Amazon India / realme India',
    },
    display: {
      displaySize: 6.72,
      displayType: 'IPS LCD, 120Hz',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 950,
      hdr: 'None',
      protection: 'Toughened Glass',
      screenToBodyRatio: '86.5%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6100+ (6nm)',
      cpu: 'Octa-core (2x2.2 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['4GB', '6GB', '8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 415000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP)',
      mainCamera: '50 MP, f/1.8',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP depth sensor',
      frontCamera: '8 MP, f/2.0',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 45,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '165.6 x 76.1 x 7.69 mm',
      weight: 188,
      materials: 'Glass front, circular horizon camera deco back',
      waterResistance: 'IP54',
      colors: ['Ice Blue', 'Forest Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'realme UI 5.0',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.realme.com/in/realme-narzo-70x-5g',
      productPage: 'https://buy.realme.com/in/goods/704',
      specSheetUrl: 'https://www.realme.com/in/realme-narzo-70x-5g/specs',
      verifiedDate: '2024-04',
    },
  },

  // ── REALME C SERIES (Budget Entry-Level 5G) ──
  {
    id: 'realme-c65-5g',
    slug: 'realme-c65-5g',
    brand: 'realme',
    modelName: 'realme C65 5G',
    generation: 'C65',
    status: 'active',
    launchDate: '2024-04',
    pricing: {
      startingPrice: 10499,
      maximumPrice: 12499,
      launchPrice: 10499,
      currentPrice: 10499,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Flipkart / realme India',
    },
    display: {
      displaySize: 6.67,
      displayType: 'IPS LCD, 120Hz',
      resolution: '1604 x 720 pixels (HD+)',
      refreshRate: 120,
      peakBrightness: 625,
      hdr: 'None',
      protection: 'Toughened Glass',
      screenToBodyRatio: '85.0%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6300 (6nm)',
      cpu: 'Octa-core (2x2.4 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['4GB', '6GB'],
      storageOptions: ['64GB', '128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 405000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + auxiliary sensor)',
      mainCamera: '50 MP, f/1.8',
      ultrawideCamera: 'None',
      telephotoCamera: 'None',
      frontCamera: '8 MP, f/2.0',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 15,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM + microSD dedicated',
    },
    physical: {
      dimensions: '165.6 x 76.1 x 7.89 mm',
      weight: 190,
      materials: 'Light feather textured polycarbonate back',
      waterResistance: 'IP54',
      colors: ['Feather Green', 'Glowing Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'realme UI 5.0',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.realme.com/in/realme-c65-5g',
      productPage: 'https://buy.realme.com/in/goods/703',
      specSheetUrl: 'https://www.realme.com/in/realme-c65-5g/specs',
      verifiedDate: '2024-04',
    },
  },

  {
    id: 'realme-c63-5g',
    slug: 'realme-c63-5g',
    brand: 'realme',
    modelName: 'realme C63 5G',
    generation: 'C63',
    status: 'active',
    launchDate: '2024-08',
    pricing: {
      startingPrice: 10999,
      maximumPrice: 12999,
      launchPrice: 10999,
      currentPrice: 10999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Flipkart / realme India',
    },
    display: {
      displaySize: 6.67,
      displayType: 'IPS LCD, 120Hz',
      resolution: '1604 x 720 pixels (HD+)',
      refreshRate: 120,
      peakBrightness: 625,
      hdr: 'None',
      protection: 'Toughened Glass',
      screenToBodyRatio: '85.0%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6300 (6nm)',
      cpu: 'Octa-core (2x2.4 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['4GB', '6GB', '8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 405000,
    },
    cameras: {
      rearCameraSetup: 'Dual (32MP + auxiliary sensor)',
      mainCamera: '32 MP, f/1.85',
      ultrawideCamera: 'None',
      telephotoCamera: 'None',
      frontCamera: '8 MP, f/2.0',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 10,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '165.6 x 76.1 x 7.94 mm',
      weight: 192,
      materials: 'Vegan leather / shiny metallic plastic back',
      waterResistance: 'IP54',
      colors: ['Starry Gold', 'Forest Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'realme UI 5.0',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.realme.com/in/realme-c63-5g',
      productPage: 'https://buy.realme.com/in/goods/715',
      specSheetUrl: 'https://www.realme.com/in/realme-c63-5g/specs',
      verifiedDate: '2024-08',
    },
  },
];

const variants: MobileVariant[] = [
  // realme GT 7 Pro
  {
    id: 'realme-gt-7-pro-12-256',
    modelId: 'realme-gt-7-pro',
    ram: '12GB',
    storage: '256GB',
    price: 59999,
    mrp: 59999,
    colors: ['Mars Orange', 'Galaxy Grey'],
    status: 'active',
    verified: true,
    source: 'Amazon India / realme India',
  },
  {
    id: 'realme-gt-7-pro-16-512',
    modelId: 'realme-gt-7-pro',
    ram: '16GB',
    storage: '512GB',
    price: 65999,
    mrp: 65999,
    colors: ['Mars Orange', 'Galaxy Grey'],
    status: 'active',
    verified: true,
    source: 'Amazon India / realme India',
  },
  // realme GT 6
  {
    id: 'realme-gt-6-8-256',
    modelId: 'realme-gt-6',
    ram: '8GB',
    storage: '256GB',
    price: 38999,
    mrp: 40999,
    colors: ['Fluid Silver', 'Razor Green'],
    status: 'active',
    verified: true,
    source: 'Amazon India / realme India',
  },
  {
    id: 'realme-gt-6-16-512',
    modelId: 'realme-gt-6',
    ram: '16GB',
    storage: '512GB',
    price: 42999,
    mrp: 44999,
    colors: ['Fluid Silver', 'Razor Green'],
    status: 'active',
    verified: true,
    source: 'Amazon India / realme India',
  },
  // realme GT 6T
  {
    id: 'realme-gt-6t-8-128',
    modelId: 'realme-gt-6t',
    ram: '8GB',
    storage: '128GB',
    price: 30999,
    mrp: 30999,
    colors: ['Fluid Silver', 'Razor Green'],
    status: 'active',
    verified: true,
    source: 'Amazon India / realme India',
  },
  {
    id: 'realme-gt-6t-12-256',
    modelId: 'realme-gt-6t',
    ram: '12GB',
    storage: '256GB',
    price: 33999,
    mrp: 33999,
    colors: ['Fluid Silver', 'Razor Green'],
    status: 'active',
    verified: true,
    source: 'Amazon India / realme India',
  },
  // realme 13 Pro+ 5G
  {
    id: 'realme-13-pro-plus-5g-8-256',
    modelId: 'realme-13-pro-plus-5g',
    ram: '8GB',
    storage: '256GB',
    price: 29999,
    mrp: 32999,
    colors: ['Monet Gold', 'Emerald Green'],
    status: 'active',
    verified: true,
    source: 'Flipkart / realme India',
  },
  {
    id: 'realme-13-pro-plus-5g-12-512',
    modelId: 'realme-13-pro-plus-5g',
    ram: '12GB',
    storage: '512GB',
    price: 34999,
    mrp: 36999,
    colors: ['Monet Gold', 'Emerald Green'],
    status: 'active',
    verified: true,
    source: 'Flipkart / realme India',
  },
  // realme 13 Pro 5G
  {
    id: 'realme-13-pro-5g-8-128',
    modelId: 'realme-13-pro-5g',
    ram: '8GB',
    storage: '128GB',
    price: 26999,
    mrp: 26999,
    colors: ['Monet Gold', 'Monet Purple'],
    status: 'active',
    verified: true,
    source: 'Flipkart / realme India',
  },
  {
    id: 'realme-13-pro-5g-12-256',
    modelId: 'realme-13-pro-5g',
    ram: '12GB',
    storage: '256GB',
    price: 29999,
    mrp: 29999,
    colors: ['Monet Gold', 'Monet Purple'],
    status: 'active',
    verified: true,
    source: 'Flipkart / realme India',
  },
  // realme 13+ 5G
  {
    id: 'realme-13-plus-5g-8-128',
    modelId: 'realme-13-plus-5g',
    ram: '8GB',
    storage: '128GB',
    price: 22999,
    mrp: 22999,
    colors: ['Victory Gold', 'Speed Green'],
    status: 'active',
    verified: true,
    source: 'Flipkart / realme India',
  },
  {
    id: 'realme-13-plus-5g-12-256',
    modelId: 'realme-13-plus-5g',
    ram: '12GB',
    storage: '256GB',
    price: 26999,
    mrp: 26999,
    colors: ['Victory Gold', 'Speed Green'],
    status: 'active',
    verified: true,
    source: 'Flipkart / realme India',
  },
  // realme 13 5G
  {
    id: 'realme-13-5g-8-128',
    modelId: 'realme-13-5g',
    ram: '8GB',
    storage: '128GB',
    price: 17999,
    mrp: 17999,
    colors: ['Speed Green', 'Dark Purple'],
    status: 'active',
    verified: true,
    source: 'Flipkart / realme India',
  },
  {
    id: 'realme-13-5g-8-256',
    modelId: 'realme-13-5g',
    ram: '8GB',
    storage: '256GB',
    price: 19999,
    mrp: 19999,
    colors: ['Speed Green', 'Dark Purple'],
    status: 'active',
    verified: true,
    source: 'Flipkart / realme India',
  },
  // realme 12 Pro+ 5G
  {
    id: 'realme-12-pro-plus-5g-8-128',
    modelId: 'realme-12-pro-plus-5g',
    ram: '8GB',
    storage: '128GB',
    price: 27999,
    mrp: 29999,
    colors: ['Submarine Blue', 'Navigator Beige'],
    status: 'discontinued',
    verified: true,
    source: 'Flipkart / realme India',
  },
  {
    id: 'realme-12-pro-plus-5g-12-256',
    modelId: 'realme-12-pro-plus-5g',
    ram: '12GB',
    storage: '256GB',
    price: 31999,
    mrp: 33999,
    colors: ['Submarine Blue', 'Navigator Beige'],
    status: 'discontinued',
    verified: true,
    source: 'Flipkart / realme India',
  },
  // realme 12 Pro 5G
  {
    id: 'realme-12-pro-5g-8-128',
    modelId: 'realme-12-pro-5g',
    ram: '8GB',
    storage: '128GB',
    price: 23999,
    mrp: 25999,
    colors: ['Submarine Blue', 'Navigator Beige'],
    status: 'discontinued',
    verified: true,
    source: 'Flipkart / realme India',
  },
  {
    id: 'realme-12-pro-5g-8-256',
    modelId: 'realme-12-pro-5g',
    ram: '8GB',
    storage: '256GB',
    price: 25999,
    mrp: 27999,
    colors: ['Submarine Blue', 'Navigator Beige'],
    status: 'discontinued',
    verified: true,
    source: 'Flipkart / realme India',
  },
  // realme 12+ 5G
  {
    id: 'realme-12-plus-5g-8-128',
    modelId: 'realme-12-plus-5g',
    ram: '8GB',
    storage: '128GB',
    price: 18999,
    mrp: 20999,
    colors: ['Pioneer Green', 'Navigator Beige'],
    status: 'active',
    verified: true,
    source: 'Flipkart / realme India',
  },
  {
    id: 'realme-12-plus-5g-8-256',
    modelId: 'realme-12-plus-5g',
    ram: '8GB',
    storage: '256GB',
    price: 21999,
    mrp: 23999,
    colors: ['Pioneer Green', 'Navigator Beige'],
    status: 'active',
    verified: true,
    source: 'Flipkart / realme India',
  },
  // realme 12x 5G
  {
    id: 'realme-12x-5g-4-128',
    modelId: 'realme-12x-5g',
    ram: '4GB',
    storage: '128GB',
    price: 11999,
    mrp: 11999,
    colors: ['Twilight Purple', 'Woodland Green'],
    status: 'active',
    verified: true,
    source: 'Flipkart / realme India',
  },
  {
    id: 'realme-12x-5g-8-128',
    modelId: 'realme-12x-5g',
    ram: '8GB',
    storage: '128GB',
    price: 13999,
    mrp: 13999,
    colors: ['Twilight Purple', 'Woodland Green'],
    status: 'active',
    verified: true,
    source: 'Flipkart / realme India',
  },
  // realme P1 Pro 5G
  {
    id: 'realme-p1-pro-5g-8-128',
    modelId: 'realme-p1-pro-5g',
    ram: '8GB',
    storage: '128GB',
    price: 19999,
    mrp: 21999,
    colors: ['Parrot Blue', 'Phoenix Red'],
    status: 'active',
    verified: true,
    source: 'Flipkart / realme India',
  },
  {
    id: 'realme-p1-pro-5g-8-256',
    modelId: 'realme-p1-pro-5g',
    ram: '8GB',
    storage: '256GB',
    price: 21999,
    mrp: 23999,
    colors: ['Parrot Blue', 'Phoenix Red'],
    status: 'active',
    verified: true,
    source: 'Flipkart / realme India',
  },
  // realme P1 5G
  {
    id: 'realme-p1-5g-6-128',
    modelId: 'realme-p1-5g',
    ram: '6GB',
    storage: '128GB',
    price: 14999,
    mrp: 15999,
    colors: ['Peacock Green', 'Phoenix Red'],
    status: 'active',
    verified: true,
    source: 'Flipkart / realme India',
  },
  {
    id: 'realme-p1-5g-8-256',
    modelId: 'realme-p1-5g',
    ram: '8GB',
    storage: '256GB',
    price: 16999,
    mrp: 17999,
    colors: ['Peacock Green', 'Phoenix Red'],
    status: 'active',
    verified: true,
    source: 'Flipkart / realme India',
  },
  // realme P2 Pro 5G
  {
    id: 'realme-p2-pro-5g-8-128',
    modelId: 'realme-p2-pro-5g',
    ram: '8GB',
    storage: '128GB',
    price: 21999,
    mrp: 21999,
    colors: ['Parrot Green', 'Eagle Grey'],
    status: 'active',
    verified: true,
    source: 'Flipkart / realme India',
  },
  {
    id: 'realme-p2-pro-5g-12-256',
    modelId: 'realme-p2-pro-5g',
    ram: '12GB',
    storage: '256GB',
    price: 24999,
    mrp: 24999,
    colors: ['Parrot Green', 'Eagle Grey'],
    status: 'active',
    verified: true,
    source: 'Flipkart / realme India',
  },
  // realme Narzo 70 Pro 5G
  {
    id: 'realme-narzo-70-pro-5g-8-128',
    modelId: 'realme-narzo-70-pro-5g',
    ram: '8GB',
    storage: '128GB',
    price: 18999,
    mrp: 19999,
    colors: ['Glass Green', 'Glass Gold'],
    status: 'active',
    verified: true,
    source: 'Amazon India / realme India',
  },
  {
    id: 'realme-narzo-70-pro-5g-8-256',
    modelId: 'realme-narzo-70-pro-5g',
    ram: '8GB',
    storage: '256GB',
    price: 20999,
    mrp: 21999,
    colors: ['Glass Green', 'Glass Gold'],
    status: 'active',
    verified: true,
    source: 'Amazon India / realme India',
  },
  // realme Narzo 70 Turbo 5G
  {
    id: 'realme-narzo-70-turbo-5g-6-128',
    modelId: 'realme-narzo-70-turbo-5g',
    ram: '6GB',
    storage: '128GB',
    price: 16999,
    mrp: 16999,
    colors: ['Turbo Yellow', 'Turbo Green'],
    status: 'active',
    verified: true,
    source: 'Amazon India / realme India',
  },
  {
    id: 'realme-narzo-70-turbo-5g-8-128',
    modelId: 'realme-narzo-70-turbo-5g',
    ram: '8GB',
    storage: '128GB',
    price: 17999,
    mrp: 17999,
    colors: ['Turbo Yellow', 'Turbo Green'],
    status: 'active',
    verified: true,
    source: 'Amazon India / realme India',
  },
  // realme Narzo 70x 5G
  {
    id: 'realme-narzo-70x-5g-4-128',
    modelId: 'realme-narzo-70x-5g',
    ram: '4GB',
    storage: '128GB',
    price: 11999,
    mrp: 11999,
    colors: ['Ice Blue', 'Forest Green'],
    status: 'active',
    verified: true,
    source: 'Amazon India / realme India',
  },
  {
    id: 'realme-narzo-70x-5g-6-128',
    modelId: 'realme-narzo-70x-5g',
    ram: '6GB',
    storage: '128GB',
    price: 12999,
    mrp: 12999,
    colors: ['Ice Blue', 'Forest Green'],
    status: 'active',
    verified: true,
    source: 'Amazon India / realme India',
  },
  // realme C65 5G
  {
    id: 'realme-c65-5g-4-64',
    modelId: 'realme-c65-5g',
    ram: '4GB',
    storage: '64GB',
    price: 10499,
    mrp: 10499,
    colors: ['Feather Green', 'Glowing Black'],
    status: 'active',
    verified: true,
    source: 'Flipkart / realme India',
  },
  {
    id: 'realme-c65-5g-6-128',
    modelId: 'realme-c65-5g',
    ram: '6GB',
    storage: '128GB',
    price: 12499,
    mrp: 12499,
    colors: ['Feather Green', 'Glowing Black'],
    status: 'active',
    verified: true,
    source: 'Flipkart / realme India',
  },
  // realme C63 5G
  {
    id: 'realme-c63-5g-4-128',
    modelId: 'realme-c63-5g',
    ram: '4GB',
    storage: '128GB',
    price: 10999,
    mrp: 10999,
    colors: ['Starry Gold', 'Forest Green'],
    status: 'active',
    verified: true,
    source: 'Flipkart / realme India',
  },
  {
    id: 'realme-c63-5g-6-128',
    modelId: 'realme-c63-5g',
    ram: '6GB',
    storage: '128GB',
    price: 11999,
    mrp: 11999,
    colors: ['Starry Gold', 'Forest Green'],
    status: 'active',
    verified: true,
    source: 'Flipkart / realme India',
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    modelId: 'realme-gt-7-pro',
    modelName: 'realme GT 7 Pro',
    brand: 'realme',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/realme-gt7-pro.jpg',
        angle: 'front',
        source: 'realme Official (GSMArena CDN)',
        sourceUrl: 'https://www.realme.com/in/realme-gt-7-pro',
        verified: true,
        alt: 'realme GT 7 Pro front display view',
      },
    ],
  },
  {
    modelId: 'realme-gt-6',
    modelName: 'realme GT 6',
    brand: 'realme',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/realme-gt6.jpg',
        angle: 'front',
        source: 'realme Official (GSMArena CDN)',
        sourceUrl: 'https://www.realme.com/in/realme-gt-6',
        verified: true,
        alt: 'realme GT 6 front view',
      },
    ],
  },
  {
    modelId: 'realme-gt-6t',
    modelName: 'realme GT 6T',
    brand: 'realme',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/realme-gt-neo6-se.jpg',
        angle: 'front',
        source: 'realme Official (GSMArena CDN)',
        sourceUrl: 'https://www.realme.com/in/realme-gt-6t',
        verified: true,
        alt: 'realme GT 6T front view',
      },
    ],
  },
  {
    modelId: 'realme-13-pro-plus-5g',
    modelName: 'realme 13 Pro+ 5G',
    brand: 'realme',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/realme-13-pro-plus.jpg',
        angle: 'front',
        source: 'realme Official (GSMArena CDN)',
        sourceUrl: 'https://www.realme.com/in/realme-13-pro-plus',
        verified: true,
        alt: 'realme 13 Pro+ 5G front display view',
      },
    ],
  },
  {
    modelId: 'realme-13-pro-5g',
    modelName: 'realme 13 Pro 5G',
    brand: 'realme',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/realme-13-pro.jpg',
        angle: 'front',
        source: 'realme Official (GSMArena CDN)',
        sourceUrl: 'https://www.realme.com/in/realme-13-pro',
        verified: true,
        alt: 'realme 13 Pro 5G front view',
      },
    ],
  },
  {
    modelId: 'realme-13-plus-5g',
    modelName: 'realme 13+ 5G',
    brand: 'realme',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/realme-13-plus-5g.jpg',
        angle: 'front',
        source: 'realme Official (GSMArena CDN)',
        sourceUrl: 'https://www.realme.com/in/realme-13-plus-5g',
        verified: true,
        alt: 'realme 13+ 5G front view',
      },
    ],
  },
  {
    modelId: 'realme-13-5g',
    modelName: 'realme 13 5G',
    brand: 'realme',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/realme-13-5g.jpg',
        angle: 'front',
        source: 'realme Official (GSMArena CDN)',
        sourceUrl: 'https://www.realme.com/in/realme-13-5g',
        verified: true,
        alt: 'realme 13 5G front view',
      },
    ],
  },
  {
    modelId: 'realme-12-pro-plus-5g',
    modelName: 'realme 12 Pro+ 5G',
    brand: 'realme',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/realme-12-pro-plus.jpg',
        angle: 'front',
        source: 'realme Official (GSMArena CDN)',
        sourceUrl: 'https://www.realme.com/in/realme-12-pro-plus',
        verified: true,
        alt: 'realme 12 Pro+ 5G front view',
      },
    ],
  },
  {
    modelId: 'realme-12-pro-5g',
    modelName: 'realme 12 Pro 5G',
    brand: 'realme',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/realme-12-pro.jpg',
        angle: 'front',
        source: 'realme Official (GSMArena CDN)',
        sourceUrl: 'https://www.realme.com/in/realme-12-pro',
        verified: true,
        alt: 'realme 12 Pro 5G front view',
      },
    ],
  },
  {
    modelId: 'realme-12-plus-5g',
    modelName: 'realme 12+ 5G',
    brand: 'realme',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/realme-12-plus.jpg',
        angle: 'front',
        source: 'realme Official (GSMArena CDN)',
        sourceUrl: 'https://www.realme.com/in/realme-12-plus-5g',
        verified: true,
        alt: 'realme 12+ 5G front view',
      },
    ],
  },
  {
    modelId: 'realme-12x-5g',
    modelName: 'realme 12x 5G',
    brand: 'realme',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/realme-12x.jpg',
        angle: 'front',
        source: 'realme Official (GSMArena CDN)',
        sourceUrl: 'https://www.realme.com/in/realme-12x-5g',
        verified: true,
        alt: 'realme 12x 5G front view',
      },
    ],
  },
  {
    modelId: 'realme-p1-pro-5g',
    modelName: 'realme P1 Pro 5G',
    brand: 'realme',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/realme-p1-pro.jpg',
        angle: 'front',
        source: 'realme Official (GSMArena CDN)',
        sourceUrl: 'https://www.realme.com/in/realme-p1-pro-5g',
        verified: true,
        alt: 'realme P1 Pro 5G front curved display view',
      },
    ],
  },
  {
    modelId: 'realme-p1-5g',
    modelName: 'realme P1 5G',
    brand: 'realme',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/realme-p1.jpg',
        angle: 'front',
        source: 'realme Official (GSMArena CDN)',
        sourceUrl: 'https://www.realme.com/in/realme-p1-5g',
        verified: true,
        alt: 'realme P1 5G front view',
      },
    ],
  },
  {
    modelId: 'realme-p2-pro-5g',
    modelName: 'realme P2 Pro 5G',
    brand: 'realme',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/realme-p2-pro.jpg',
        angle: 'front',
        source: 'realme Official (GSMArena CDN)',
        sourceUrl: 'https://www.realme.com/in/realme-p2-pro-5g',
        verified: true,
        alt: 'realme P2 Pro 5G front view',
      },
    ],
  },
  {
    modelId: 'realme-narzo-70-pro-5g',
    modelName: 'realme Narzo 70 Pro 5G',
    brand: 'realme',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/realme-narzo-70-pro.jpg',
        angle: 'front',
        source: 'realme Official (GSMArena CDN)',
        sourceUrl: 'https://www.realme.com/in/realme-narzo-70-pro-5g',
        verified: true,
        alt: 'realme Narzo 70 Pro 5G front glass back view',
      },
    ],
  },
  {
    modelId: 'realme-narzo-70-turbo-5g',
    modelName: 'realme Narzo 70 Turbo 5G',
    brand: 'realme',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/realme-narzo-70-turbo.jpg',
        angle: 'front',
        source: 'realme Official (GSMArena CDN)',
        sourceUrl: 'https://www.realme.com/in/realme-narzo-70-turbo-5g',
        verified: true,
        alt: 'realme Narzo 70 Turbo 5G front view',
      },
    ],
  },
  {
    modelId: 'realme-narzo-70x-5g',
    modelName: 'realme Narzo 70x 5G',
    brand: 'realme',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/realme-narzo-70x.jpg',
        angle: 'front',
        source: 'realme Official (GSMArena CDN)',
        sourceUrl: 'https://www.realme.com/in/realme-narzo-70x-5g',
        verified: true,
        alt: 'realme Narzo 70x 5G front view',
      },
    ],
  },
  {
    modelId: 'realme-c65-5g',
    modelName: 'realme C65 5G',
    brand: 'realme',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/realme-c65.jpg',
        angle: 'front',
        source: 'realme Official (GSMArena CDN)',
        sourceUrl: 'https://www.realme.com/in/realme-c65-5g',
        verified: true,
        alt: 'realme C65 5G front view',
      },
    ],
  },
  {
    modelId: 'realme-c63-5g',
    modelName: 'realme C63 5G',
    brand: 'realme',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/realme-c63.jpg',
        angle: 'front',
        source: 'realme Official (GSMArena CDN)',
        sourceUrl: 'https://www.realme.com/in/realme-c63-5g',
        verified: true,
        alt: 'realme C63 5G front view',
      },
    ],
  },
];

export const realmeBundle: MobileBrandBundle = {
  brand: 'realme',
  models,
  variants,
  images,
};
