import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  // ── REDMI NOTE 14 SERIES ──
  {
    id: 'redmi-note-14-pro-plus-5g',
    slug: 'redmi-note-14-pro-plus-5g',
    brand: 'Redmi',
    modelName: 'Redmi Note 14 Pro+ 5G',
    generation: 'Note 14',
    status: 'active',
    launchDate: '2024-12',
    pricing: {
      startingPrice: 30999,
      maximumPrice: 35999,
      mrp: 30999,
      currentPrice: 30999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.67,
      displayType: '1.5K 120Hz Curved AMOLED',
      resolution: '2712 x 1220 pixels',
      refreshRate: 120,
      peakBrightness: 3000,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '90.2%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7s Gen 3 (4nm)',
      cpu: 'Octa-core (1x2.5 GHz Cortex-A720 & 3x2.4 GHz & 4x1.8 GHz)',
      gpu: 'Adreno 710',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB', '512GB'],
      storageType: 'UFS 3.1',
      antutuScore: 810000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 8MP)',
      mainCamera: '50 MP Light Hunter 800, f/1.6, OIS',
      ultrawideCamera: '8 MP, f/2.2, 120˚',
      telephotoCamera: '50 MP portrait telephoto, 2.5x optical, 60mm, OIS',
      frontCamera: '20 MP, f/2.2',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 6200,
      wiredCharging: 90,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.5 x 74.7 x 8.7 mm',
      weight: 211,
      materials: 'Glass front (Victus 2), silicone polymer back (eco leather) or glass back',
      waterResistance: 'IP68/IP69K',
      colors: ['Spectre Blue', 'Titan Black', 'Phantom Purple'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Xiaomi HyperOS',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/redmi-note-14-pro-plus-5g/',
      productPage: 'https://store.mi.com/in/item/3244800001',
      specSheetUrl: 'https://www.mi.com/in/product/redmi-note-14-pro-plus-5g/specs/',
      verifiedDate: '2024-12',
    },
  },

  {
    id: 'redmi-note-14-pro-5g',
    slug: 'redmi-note-14-pro-5g',
    brand: 'Redmi',
    modelName: 'Redmi Note 14 Pro 5G',
    generation: 'Note 14',
    status: 'active',
    launchDate: '2024-12',
    pricing: {
      startingPrice: 24999,
      maximumPrice: 28999,
      mrp: 24999,
      currentPrice: 24999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.67,
      displayType: '1.5K 120Hz Curved AMOLED',
      resolution: '2712 x 1220 pixels',
      refreshRate: 120,
      peakBrightness: 3000,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '90.2%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7300 Ultra (4nm)',
      cpu: 'Octa-core (4x2.5 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G615 MC2',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 720000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 8MP + 2MP)',
      mainCamera: '50 MP Sony LYT-600, f/1.5, OIS',
      ultrawideCamera: '8 MP, f/2.2, 120˚',
      telephotoCamera: '2 MP macro, f/2.4',
      frontCamera: '20 MP, f/2.2',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5500,
      wiredCharging: 45,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.3 x 74.4 x 8.24 mm',
      weight: 190,
      materials: 'Glass front (Victus 2), plastic frame, glass/leather back',
      waterResistance: 'IP68/IP69K',
      colors: ['Ivy Green', 'Titan Black', 'Phantom Purple'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Xiaomi HyperOS',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/redmi-note-14-pro-5g/',
      productPage: 'https://store.mi.com/in/item/3244800002',
      specSheetUrl: 'https://www.mi.com/in/product/redmi-note-14-pro-5g/specs/',
      verifiedDate: '2024-12',
    },
  },

  {
    id: 'redmi-note-14-5g',
    slug: 'redmi-note-14-5g',
    brand: 'Redmi',
    modelName: 'Redmi Note 14 5G',
    generation: 'Note 14',
    status: 'active',
    launchDate: '2024-12',
    pricing: {
      startingPrice: 17999,
      maximumPrice: 20999,
      mrp: 17999,
      currentPrice: 17999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.67,
      displayType: 'OLED, 120Hz, HDR10+',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 2100,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '87.9%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7025 Ultra (6nm)',
      cpu: 'Octa-core (2x2.5 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)',
      gpu: 'IMG BXM-8-256',
      ramOptions: ['6GB', '8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 480000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP)',
      mainCamera: '50 MP Sony LYT-600, f/1.7, OIS',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP macro sensor',
      frontCamera: '16 MP, f/2.4',
      videoRecording: '1080p@30fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5110,
      wiredCharging: 45,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '162.4 x 75.7 x 7.99 mm',
      weight: 190,
      materials: 'Glass front (Gorilla Glass 5), plastic frame and back',
      waterResistance: 'IP64',
      colors: ['Mystic White', 'Titan Black', 'Phantom Purple'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Xiaomi HyperOS',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/redmi-note-14-5g/',
      productPage: 'https://store.mi.com/in/item/3244800003',
      specSheetUrl: 'https://www.mi.com/in/product/redmi-note-14-5g/specs/',
      verifiedDate: '2024-12',
    },
  },

  // ── REDMI NOTE 13 SERIES ──
  {
    id: 'redmi-note-13-pro-plus-5g',
    slug: 'redmi-note-13-pro-plus-5g',
    brand: 'Redmi',
    modelName: 'Redmi Note 13 Pro+ 5G',
    generation: 'Note 13',
    status: 'active',
    launchDate: '2024-01',
    pricing: {
      startingPrice: 27999,
      maximumPrice: 31999,
      mrp: 31999,
      currentPrice: 27999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.67,
      displayType: '1.5K 120Hz Curved AMOLED',
      resolution: '2712 x 1220 pixels',
      refreshRate: 120,
      peakBrightness: 1800,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass Victus',
      screenToBodyRatio: '89.7%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7200 Ultra (4nm)',
      cpu: 'Octa-core (2x2.8 GHz Cortex-A715 & 6x2.0 GHz Cortex-A510)',
      gpu: 'Mali-G610 MC4',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 3.1',
      antutuScore: 800000,
    },
    cameras: {
      rearCameraSetup: 'Triple (200MP + 8MP + 2MP)',
      mainCamera: '200 MP Samsung ISOCELL HP3, f/1.65, OIS',
      ultrawideCamera: '8 MP, f/2.2, 120˚',
      telephotoCamera: '2 MP macro, f/2.4',
      frontCamera: '16 MP, f/2.4',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 120,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.4 x 74.2 x 8.9 mm',
      weight: 204.5,
      materials: 'Glass front (Victus), vegan leather or glass back',
      waterResistance: 'IP68',
      colors: ['Fusion White', 'Fusion Black', 'Fusion Purple'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MIUI 14 (upgraded to HyperOS)',
      launchOS: 'Android 13',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/redmi-note-13-pro-plus-5g/',
      productPage: 'https://store.mi.com/in/item/3240100001',
      specSheetUrl: 'https://www.mi.com/in/product/redmi-note-13-pro-plus-5g/specs/',
      verifiedDate: '2024-01',
    },
  },

  {
    id: 'redmi-note-13-pro-5g',
    slug: 'redmi-note-13-pro-5g',
    brand: 'Redmi',
    modelName: 'Redmi Note 13 Pro 5G',
    generation: 'Note 13',
    status: 'active',
    launchDate: '2024-01',
    pricing: {
      startingPrice: 21999,
      maximumPrice: 24999,
      mrp: 25999,
      currentPrice: 21999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.67,
      displayType: '1.5K 120Hz AMOLED',
      resolution: '2712 x 1220 pixels',
      refreshRate: 120,
      peakBrightness: 1800,
      hdr: 'Dolby Vision',
      protection: 'Corning Gorilla Glass Victus',
      screenToBodyRatio: '89.8%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7s Gen 2 (4nm)',
      cpu: 'Octa-core (4x2.40 GHz Cortex-A78 & 4x1.95 GHz Cortex-A55)',
      gpu: 'Adreno 710',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 610000,
    },
    cameras: {
      rearCameraSetup: 'Triple (200MP + 8MP + 2MP)',
      mainCamera: '200 MP Samsung HP3, f/1.65, OIS',
      ultrawideCamera: '8 MP, f/2.2, 118˚',
      telephotoCamera: '2 MP macro, f/2.4',
      frontCamera: '16 MP, f/2.4',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5100,
      wiredCharging: 67,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.2',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.2 x 74.2 x 7.98 mm',
      weight: 187,
      materials: 'Glass front (Victus), plastic frame, glass back',
      waterResistance: 'IP54',
      colors: ['Arctic White', 'Coral Purple', 'Midnight Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MIUI 14 (upgraded to HyperOS)',
      launchOS: 'Android 13',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/redmi-note-13-pro-5g/',
      productPage: 'https://store.mi.com/in/item/3240100002',
      specSheetUrl: 'https://www.mi.com/in/product/redmi-note-13-pro-5g/specs/',
      verifiedDate: '2024-01',
    },
  },

  {
    id: 'redmi-note-13-5g',
    slug: 'redmi-note-13-5g',
    brand: 'Redmi',
    modelName: 'Redmi Note 13 5G',
    generation: 'Note 13',
    status: 'active',
    launchDate: '2024-01',
    pricing: {
      startingPrice: 15999,
      maximumPrice: 18999,
      mrp: 17999,
      currentPrice: 15999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.67,
      displayType: 'AMOLED, 120Hz',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1000,
      hdr: 'HDR10',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '88.9%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6080 (6nm)',
      cpu: 'Octa-core (2x2.4 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['6GB', '8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 450000,
    },
    cameras: {
      rearCameraSetup: 'Triple (108MP + 8MP + 2MP)',
      mainCamera: '108 MP, f/1.7',
      ultrawideCamera: '8 MP, f/2.2',
      telephotoCamera: '2 MP depth, f/2.4',
      frontCamera: '16 MP, f/2.4',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 33,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '161.1 x 75 x 7.6 mm',
      weight: 173.5,
      materials: 'Glass front (Gorilla Glass 5), plastic frame and back',
      waterResistance: 'IP54',
      colors: ['Stealth Black', 'Prism Gold', 'Arctic White'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MIUI 14 (upgraded to HyperOS)',
      launchOS: 'Android 13',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/redmi-note-13-5g/',
      productPage: 'https://store.mi.com/in/item/3240100003',
      specSheetUrl: 'https://www.mi.com/in/product/redmi-note-13-5g/specs/',
      verifiedDate: '2024-01',
    },
  },

  // ── REDMI NOTE 12 SERIES ──
  {
    id: 'redmi-note-12-pro-plus-5g',
    slug: 'redmi-note-12-pro-plus-5g',
    brand: 'Redmi',
    modelName: 'Redmi Note 12 Pro+ 5G',
    generation: 'Note 12',
    status: 'discontinued',
    launchDate: '2023-01',
    pricing: {
      startingPrice: 24999,
      maximumPrice: 27999,
      mrp: 29999,
      currentPrice: 24999,
      currency: 'INR',
      priceEffectiveDate: '2024-01',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.67,
      displayType: 'Pro AMOLED, 120Hz, Dolby Vision, HDR10+',
      resolution: '2400 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 900,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '86.8%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 1080 (6nm)',
      cpu: 'Octa-core (2x2.6 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G68 MC4',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 535000,
    },
    cameras: {
      rearCameraSetup: 'Triple (200MP + 8MP + 2MP)',
      mainCamera: '200 MP Samsung HPX, f/1.65, OIS',
      ultrawideCamera: '8 MP, f/2.2, 120˚',
      telephotoCamera: '2 MP macro, f/2.4',
      frontCamera: '16 MP, f/2.45',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4980,
      wiredCharging: 120,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.9 x 76 x 8.9 mm',
      weight: 208.4,
      materials: 'Glass front (Gorilla Glass 5), plastic frame, glass back',
      waterResistance: 'IP53',
      colors: ['Arctic White', 'Iceberg Blue', 'Obsidian Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MIUI 13 (upgraded to HyperOS)',
      launchOS: 'Android 12',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/redmi-note-12-pro-plus-5g/',
      productPage: 'https://store.mi.com/in/item/3230100001',
      specSheetUrl: 'https://www.mi.com/in/product/redmi-note-12-pro-plus-5g/specs/',
      verifiedDate: '2023-01',
    },
  },

  {
    id: 'redmi-note-12-pro-5g',
    slug: 'redmi-note-12-pro-5g',
    brand: 'Redmi',
    modelName: 'Redmi Note 12 Pro 5G',
    generation: 'Note 12',
    status: 'discontinued',
    launchDate: '2023-01',
    pricing: {
      startingPrice: 19999,
      maximumPrice: 22999,
      mrp: 24999,
      currentPrice: 19999,
      currency: 'INR',
      priceEffectiveDate: '2024-01',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.67,
      displayType: 'Pro AMOLED, 120Hz, Dolby Vision, HDR10+',
      resolution: '2400 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 900,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '86.8%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 1080 (6nm)',
      cpu: 'Octa-core (2x2.6 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G68 MC4',
      ramOptions: ['6GB', '8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 530000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 8MP + 2MP)',
      mainCamera: '50 MP Sony IMX766, f/1.88, OIS',
      ultrawideCamera: '8 MP, f/2.2, 119˚',
      telephotoCamera: '2 MP macro, f/2.4',
      frontCamera: '16 MP, f/2.45',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 67,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '163 x 76 x 7.98 mm',
      weight: 187,
      materials: 'Glass front (Gorilla Glass 5), plastic frame, glass back',
      waterResistance: 'IP53',
      colors: ['Glacier Blue', 'Onyx Black', 'Stardust Purple'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MIUI 13 (upgraded to HyperOS)',
      launchOS: 'Android 12',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/redmi-note-12-pro-5g/',
      productPage: 'https://store.mi.com/in/item/3230100002',
      specSheetUrl: 'https://www.mi.com/in/product/redmi-note-12-pro-5g/specs/',
      verifiedDate: '2023-01',
    },
  },

  {
    id: 'redmi-note-12-5g',
    slug: 'redmi-note-12-5g',
    brand: 'Redmi',
    modelName: 'Redmi Note 12 5G',
    generation: 'Note 12',
    status: 'discontinued',
    launchDate: '2023-01',
    pricing: {
      startingPrice: 13999,
      maximumPrice: 16999,
      mrp: 17999,
      currentPrice: 13999,
      currency: 'INR',
      priceEffectiveDate: '2024-01',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.67,
      displayType: 'Super AMOLED, 120Hz',
      resolution: '2400 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 1200,
      hdr: 'None',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '85.0%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 4 Gen 1 (6nm)',
      cpu: 'Octa-core (2x2.0 GHz Cortex-A78 & 6x1.8 GHz Cortex-A55)',
      gpu: 'Adreno 619',
      ramOptions: ['4GB', '6GB', '8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 410000,
    },
    cameras: {
      rearCameraSetup: 'Triple (48MP + 8MP + 2MP)',
      mainCamera: '48 MP, f/1.8',
      ultrawideCamera: '8 MP, f/2.2',
      telephotoCamera: '2 MP macro, f/2.4',
      frontCamera: '13 MP, f/2.45',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 33,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.1',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '165.9 x 76.2 x 7.98 mm',
      weight: 188,
      materials: 'Glass front (Gorilla Glass 3), plastic frame and back',
      waterResistance: 'IP53',
      colors: ['Frosted Green', 'Matte Black', 'Mystique Blue'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MIUI 13',
      launchOS: 'Android 12',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/redmi-note-12-5g/',
      productPage: 'https://store.mi.com/in/item/3230100003',
      specSheetUrl: 'https://www.mi.com/in/product/redmi-note-12-5g/specs/',
      verifiedDate: '2023-01',
    },
  },

  // ── REDMI NOTE 11 SERIES ──
  {
    id: 'redmi-note-11-pro-plus-5g',
    slug: 'redmi-note-11-pro-plus-5g',
    brand: 'Redmi',
    modelName: 'Redmi Note 11 Pro+ 5G',
    generation: 'Note 11',
    status: 'discontinued',
    launchDate: '2022-03',
    pricing: {
      startingPrice: 17999,
      maximumPrice: 20999,
      mrp: 20999,
      currentPrice: 17999,
      currency: 'INR',
      priceEffectiveDate: '2023-03',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.67,
      displayType: 'Super AMOLED, 120Hz, HDR10',
      resolution: '2400 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 1200,
      hdr: 'HDR10',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '86.0%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 695 5G (6nm)',
      cpu: 'Octa-core (2x2.2 GHz Kryo 660 Gold & 6x1.7 GHz Kryo 660 Silver)',
      gpu: 'Adreno 619',
      ramOptions: ['6GB', '8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 395000,
    },
    cameras: {
      rearCameraSetup: 'Triple (108MP + 8MP + 2MP)',
      mainCamera: '108 MP Samsung HM2, f/1.9',
      ultrawideCamera: '8 MP, f/2.2, 118˚',
      telephotoCamera: '2 MP macro, f/2.4',
      frontCamera: '16 MP, f/2.4',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 67,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.1',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '164.2 x 76.1 x 8.12 mm',
      weight: 202,
      materials: 'Glass front (Gorilla Glass 5), plastic frame, glass back',
      waterResistance: 'IP53',
      colors: ['Mirage Blue', 'Phantom White', 'Stealth Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MIUI 13',
      launchOS: 'Android 11',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/redmi-note-11-pro-plus-5g/',
      productPage: 'https://store.mi.com/in/item/3221000001',
      specSheetUrl: 'https://www.mi.com/in/product/redmi-note-11-pro-plus-5g/specs/',
      verifiedDate: '2022-03',
    },
  },

  {
    id: 'redmi-note-11',
    slug: 'redmi-note-11',
    brand: 'Redmi',
    modelName: 'Redmi Note 11',
    generation: 'Note 11',
    status: 'discontinued',
    launchDate: '2022-02',
    pricing: {
      startingPrice: 11999,
      maximumPrice: 14499,
      mrp: 13499,
      currentPrice: 11999,
      currency: 'INR',
      priceEffectiveDate: '2023-01',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.43,
      displayType: 'AMOLED, 90Hz',
      resolution: '2400 x 1080 pixels',
      refreshRate: 90,
      peakBrightness: 1000,
      hdr: 'None',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '84.5%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 680 4G (6nm)',
      cpu: 'Octa-core (4x2.4 GHz Kryo 265 Gold & 4x1.9 GHz Kryo 265 Silver)',
      gpu: 'Adreno 610',
      ramOptions: ['4GB', '6GB'],
      storageOptions: ['64GB', '128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 280000,
    },
    cameras: {
      rearCameraSetup: 'Quad (50MP + 8MP + 2MP + 2MP)',
      mainCamera: '50 MP, f/1.8',
      ultrawideCamera: '8 MP, f/2.2, 118˚',
      telephotoCamera: '2 MP macro, f/2.4 + 2 MP depth',
      frontCamera: '13 MP, f/2.4',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 33,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: false,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.0',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '159.9 x 73.9 x 8.09 mm',
      weight: 179,
      materials: 'Glass front (Gorilla Glass 3), plastic frame and back',
      waterResistance: 'IP53',
      colors: ['Horizon Blue', 'Space Black', 'Star Blue'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MIUI 13',
      launchOS: 'Android 11',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/redmi-note-11/',
      productPage: 'https://store.mi.com/in/item/3220600001',
      specSheetUrl: 'https://www.mi.com/in/product/redmi-note-11/specs/',
      verifiedDate: '2022-02',
    },
  },

  // ── REDMI NUMBERED / C / A SERIES ──
  {
    id: 'redmi-13-5g',
    slug: 'redmi-13-5g',
    brand: 'Redmi',
    modelName: 'Redmi 13 5G',
    generation: '13',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 13999,
      maximumPrice: 15499,
      mrp: 13999,
      currentPrice: 13999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.79,
      displayType: 'IPS LCD, 120Hz',
      resolution: '2460 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 550,
      hdr: 'None',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '85.1%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 4 Gen 2 AE (4nm)',
      cpu: 'Octa-core (2x2.3 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Adreno 613',
      ramOptions: ['6GB', '8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 430000,
    },
    cameras: {
      rearCameraSetup: 'Dual (108MP + 2MP)',
      mainCamera: '108 MP Samsung ISOCELL HM6, f/1.75',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP macro, f/2.4',
      frontCamera: '13 MP, f/2.45',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5030,
      wiredCharging: 33,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '168.6 x 76.3 x 8.3 mm',
      weight: 205,
      materials: 'Dual glass design (Gorilla Glass 3 front and crystal glass back)',
      waterResistance: 'IP53',
      colors: ['Hawaiian Blue', 'Black Diamond', 'Orchid Pink'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Xiaomi HyperOS',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Single speaker with 150% volume boost',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/redmi-13-5g/',
      productPage: 'https://store.mi.com/in/item/3242700001',
      specSheetUrl: 'https://www.mi.com/in/product/redmi-13-5g/specs/',
      verifiedDate: '2024-07',
    },
  },

  {
    id: 'redmi-13c-5g',
    slug: 'redmi-13c-5g',
    brand: 'Redmi',
    modelName: 'Redmi 13C 5G',
    generation: '13C',
    status: 'active',
    launchDate: '2023-12',
    pricing: {
      startingPrice: 10499,
      maximumPrice: 13499,
      mrp: 10999,
      currentPrice: 10499,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.74,
      displayType: 'IPS LCD, 90Hz',
      resolution: '1600 x 720 pixels (HD+)',
      refreshRate: 90,
      peakBrightness: 600,
      hdr: 'None',
      protection: 'Corning Gorilla Glass',
      screenToBodyRatio: '83.8%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6100+ (6nm)',
      cpu: 'Octa-core (2x2.2 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['4GB', '6GB', '8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 415000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 0.08MP auxiliary lens)',
      mainCamera: '50 MP, f/1.8',
      ultrawideCamera: 'None',
      telephotoCamera: 'None',
      frontCamera: '5 MP, f/2.2',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 18,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM + microSD dedicated',
    },
    physical: {
      dimensions: '168 x 78 x 8.09 mm',
      weight: 192,
      materials: 'Glass front, plastic frame, star-trail patterned plastic back',
      waterResistance: 'Splash resistant',
      colors: ['Starlight Black', 'Startrail Green', 'Startrail Silver'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MIUI 14 (upgraded to HyperOS)',
      launchOS: 'Android 13',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/redmi-13c-5g/',
      productPage: 'https://store.mi.com/in/item/3234900001',
      specSheetUrl: 'https://www.mi.com/in/product/redmi-13c-5g/specs/',
      verifiedDate: '2023-12',
    },
  },

  {
    id: 'redmi-13c',
    slug: 'redmi-13c',
    brand: 'Redmi',
    modelName: 'Redmi 13C',
    generation: '13C',
    status: 'active',
    launchDate: '2023-12',
    pricing: {
      startingPrice: 7999,
      maximumPrice: 9999,
      mrp: 8999,
      currentPrice: 7999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.74,
      displayType: 'IPS LCD, 90Hz',
      resolution: '1600 x 720 pixels (HD+)',
      refreshRate: 90,
      peakBrightness: 600,
      hdr: 'None',
      protection: 'Corning Gorilla Glass',
      screenToBodyRatio: '83.7%',
    },
    performance: {
      chipset: 'MediaTek Helio G85 (12nm)',
      cpu: 'Octa-core (2x2.0 GHz Cortex-A75 & 6x1.8 GHz Cortex-A55)',
      gpu: 'Mali-G52 MC2',
      ramOptions: ['4GB', '6GB', '8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'eMMC 5.1',
      antutuScore: 260000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 2MP + 0.08MP)',
      mainCamera: '50 MP, f/1.8',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP macro, f/2.4',
      frontCamera: '8 MP, f/2.0',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 18,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: false,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM + microSD dedicated',
    },
    physical: {
      dimensions: '168 x 78 x 8.09 mm',
      weight: 192,
      materials: 'Glass front, plastic frame and back',
      waterResistance: 'Splash resistant',
      colors: ['Starlight Black', 'Starshine Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MIUI 14 (upgraded to HyperOS)',
      launchOS: 'Android 13',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/redmi-13c/',
      productPage: 'https://store.mi.com/in/item/3234900002',
      specSheetUrl: 'https://www.mi.com/in/product/redmi-13c/specs/',
      verifiedDate: '2023-12',
    },
  },

  {
    id: 'redmi-12-5g',
    slug: 'redmi-12-5g',
    brand: 'Redmi',
    modelName: 'Redmi 12 5G',
    generation: '12',
    status: 'active',
    launchDate: '2023-08',
    pricing: {
      startingPrice: 11499,
      maximumPrice: 13999,
      mrp: 11999,
      currentPrice: 11499,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.79,
      displayType: 'IPS LCD, 90Hz',
      resolution: '2460 x 1080 pixels (FHD+)',
      refreshRate: 90,
      peakBrightness: 550,
      hdr: 'None',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '85.1%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 4 Gen 2 (4nm)',
      cpu: 'Octa-core (2x2.2 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Adreno 613',
      ramOptions: ['4GB', '6GB', '8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 420000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP)',
      mainCamera: '50 MP, f/1.8',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP depth sensor',
      frontCamera: '8 MP, f/2.0',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 18,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '168.6 x 76.3 x 8.17 mm',
      weight: 199,
      materials: 'Glass front (Gorilla Glass 3), plastic frame, glass back',
      waterResistance: 'IP53',
      colors: ['Moonstone Silver', 'Pastel Blue', 'Jade Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MIUI 14 (upgraded to HyperOS)',
      launchOS: 'Android 13',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/redmi-12-5g/',
      productPage: 'https://store.mi.com/in/item/3233100001',
      specSheetUrl: 'https://www.mi.com/in/product/redmi-12-5g/specs/',
      verifiedDate: '2023-08',
    },
  },

  {
    id: 'redmi-a3',
    slug: 'redmi-a3',
    brand: 'Redmi',
    modelName: 'Redmi A3',
    generation: 'A3',
    status: 'active',
    launchDate: '2024-02',
    pricing: {
      startingPrice: 6999,
      maximumPrice: 7999,
      mrp: 7299,
      currentPrice: 6999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.71,
      displayType: 'IPS LCD, 90Hz',
      resolution: '1650 x 720 pixels (HD+)',
      refreshRate: 90,
      peakBrightness: 500,
      hdr: 'None',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '82.9%',
    },
    performance: {
      chipset: 'MediaTek Helio G36 (12nm)',
      cpu: 'Octa-core (4x2.2 GHz Cortex-A53 & 4x1.6 GHz Cortex-A53)',
      gpu: 'PowerVR GE8320',
      ramOptions: ['3GB', '4GB', '6GB'],
      storageOptions: ['64GB', '128GB'],
      storageType: 'eMMC 5.1',
      antutuScore: 145000,
    },
    cameras: {
      rearCameraSetup: 'Dual (8MP + 0.08MP auxiliary lens)',
      mainCamera: '8 MP, f/2.0',
      ultrawideCamera: 'None',
      telephotoCamera: 'None',
      frontCamera: '5 MP, f/2.2',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 10,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: false,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.4',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM + microSD dedicated',
    },
    physical: {
      dimensions: '168.3 x 76.3 x 8.32 mm',
      weight: 199,
      materials: 'Glass front (Gorilla Glass 3), premium halo glass / leather-feel back',
      waterResistance: 'None',
      colors: ['Olive Green', 'Midnight Black', 'Lake Blue'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Android 14 (Go Edition)',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Single bottom speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/redmi-a3/',
      productPage: 'https://store.mi.com/in/item/3240800001',
      specSheetUrl: 'https://www.mi.com/in/product/redmi-a3/specs/',
      verifiedDate: '2024-02',
    },
  },

  {
    id: 'redmi-a2-plus',
    slug: 'redmi-a2-plus',
    brand: 'Redmi',
    modelName: 'Redmi A2+',
    generation: 'A2',
    status: 'discontinued',
    launchDate: '2023-05',
    pricing: {
      startingPrice: 5999,
      maximumPrice: 6999,
      mrp: 6999,
      currentPrice: 5999,
      currency: 'INR',
      priceEffectiveDate: '2024-01',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.52,
      displayType: 'IPS LCD',
      resolution: '1600 x 720 pixels (HD+)',
      refreshRate: 60,
      peakBrightness: 400,
      hdr: 'None',
      protection: 'Scratch resistant glass',
      screenToBodyRatio: '81.0%',
    },
    performance: {
      chipset: 'MediaTek Helio G36 (12nm)',
      cpu: 'Octa-core (4x2.2 GHz Cortex-A53 & 4x1.7 GHz Cortex-A53)',
      gpu: 'PowerVR GE8320',
      ramOptions: ['2GB', '4GB'],
      storageOptions: ['32GB', '64GB'],
      storageType: 'eMMC 5.1',
      antutuScore: 135000,
    },
    cameras: {
      rearCameraSetup: 'Dual (8MP + 0.08MP depth)',
      mainCamera: '8 MP, f/2.0',
      ultrawideCamera: 'None',
      telephotoCamera: 'None',
      frontCamera: '5 MP, f/2.2',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 10,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: false,
      has4G: true,
      wifi: 'Wi-Fi 4',
      bluetooth: 'Bluetooth 5.0',
      nfc: false,
      usb: 'microUSB 2.0',
      simConfig: 'Dual SIM + microSD dedicated',
    },
    physical: {
      dimensions: '164.9 x 76.8 x 9.09 mm',
      weight: 192,
      materials: 'Plastic frame and leather-textured plastic back',
      waterResistance: 'None',
      colors: ['Aqua Blue', 'Classic Black', 'Sea Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Android 13 (Go Edition)',
      launchOS: 'Android 13',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Rear-mounted',
      faceUnlock: false,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/redmi-a2-plus/',
      productPage: 'https://store.mi.com/in/item/3232000001',
      specSheetUrl: 'https://www.mi.com/in/product/redmi-a2-plus/specs/',
      verifiedDate: '2023-05',
    },
  },
];

const variants: MobileVariant[] = [
  // Redmi Note 14 Pro+ 5G
  {
    id: 'redmi-note-14-pro-plus-5g-8-128',
    modelId: 'redmi-note-14-pro-plus-5g',
    ram: '8GB',
    storage: '128GB',
    price: 30999,
    mrp: 30999,
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Spectre Blue', 'Titan Black'],
  },
  {
    id: 'redmi-note-14-pro-plus-5g-12-512',
    modelId: 'redmi-note-14-pro-plus-5g',
    ram: '12GB',
    storage: '512GB',
    price: 35999,
    mrp: 35999,
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Spectre Blue', 'Titan Black'],
  },
  // Redmi Note 14 Pro 5G
  {
    id: 'redmi-note-14-pro-5g-8-128',
    modelId: 'redmi-note-14-pro-5g',
    ram: '8GB',
    storage: '128GB',
    price: 24999,
    mrp: 24999,
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Ivy Green', 'Titan Black'],
  },
  {
    id: 'redmi-note-14-pro-5g-8-256',
    modelId: 'redmi-note-14-pro-5g',
    ram: '8GB',
    storage: '256GB',
    price: 26999,
    mrp: 26999,
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Ivy Green', 'Titan Black'],
  },
  // Redmi Note 14 5G
  {
    id: 'redmi-note-14-5g-6-128',
    modelId: 'redmi-note-14-5g',
    ram: '6GB',
    storage: '128GB',
    price: 17999,
    mrp: 17999,
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Mystic White', 'Titan Black'],
  },
  {
    id: 'redmi-note-14-5g-8-256',
    modelId: 'redmi-note-14-5g',
    ram: '8GB',
    storage: '256GB',
    price: 20999,
    mrp: 20999,
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Mystic White', 'Titan Black'],
  },
  // Redmi Note 13 Pro+ 5G
  {
    id: 'redmi-note-13-pro-plus-5g-8-256',
    modelId: 'redmi-note-13-pro-plus-5g',
    ram: '8GB',
    storage: '256GB',
    price: 27999,
    mrp: 31999,
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Fusion White', 'Fusion Purple'],
  },
  {
    id: 'redmi-note-13-pro-plus-5g-12-512',
    modelId: 'redmi-note-13-pro-plus-5g',
    ram: '12GB',
    storage: '512GB',
    price: 31999,
    mrp: 35999,
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Fusion White', 'Fusion Purple'],
  },
  // Redmi Note 13 Pro 5G
  {
    id: 'redmi-note-13-pro-5g-8-128',
    modelId: 'redmi-note-13-pro-5g',
    ram: '8GB',
    storage: '128GB',
    price: 21999,
    mrp: 25999,
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Arctic White', 'Coral Purple'],
  },
  {
    id: 'redmi-note-13-pro-5g-12-256',
    modelId: 'redmi-note-13-pro-5g',
    ram: '12GB',
    storage: '256GB',
    price: 24999,
    mrp: 28999,
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Arctic White', 'Coral Purple'],
  },
  // Redmi Note 13 5G
  {
    id: 'redmi-note-13-5g-6-128',
    modelId: 'redmi-note-13-5g',
    ram: '6GB',
    storage: '128GB',
    price: 15999,
    mrp: 17999,
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Stealth Black', 'Prism Gold'],
  },
  {
    id: 'redmi-note-13-5g-8-256',
    modelId: 'redmi-note-13-5g',
    ram: '8GB',
    storage: '256GB',
    price: 18999,
    mrp: 20999,
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Stealth Black', 'Prism Gold'],
  },
  // Redmi Note 12 Pro+ 5G
  {
    id: 'redmi-note-12-pro-plus-5g-8-256',
    modelId: 'redmi-note-12-pro-plus-5g',
    ram: '8GB',
    storage: '256GB',
    price: 24999,
    mrp: 29999,
    status: 'discontinued',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Arctic White', 'Iceberg Blue'],
  },
  {
    id: 'redmi-note-12-pro-plus-5g-12-256',
    modelId: 'redmi-note-12-pro-plus-5g',
    ram: '12GB',
    storage: '256GB',
    price: 27999,
    mrp: 32999,
    status: 'discontinued',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Arctic White', 'Iceberg Blue'],
  },
  // Redmi Note 12 Pro 5G
  {
    id: 'redmi-note-12-pro-5g-6-128',
    modelId: 'redmi-note-12-pro-5g',
    ram: '6GB',
    storage: '128GB',
    price: 19999,
    mrp: 24999,
    status: 'discontinued',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Glacier Blue', 'Onyx Black'],
  },
  {
    id: 'redmi-note-12-pro-5g-8-256',
    modelId: 'redmi-note-12-pro-5g',
    ram: '8GB',
    storage: '256GB',
    price: 22999,
    mrp: 27999,
    status: 'discontinued',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Glacier Blue', 'Onyx Black'],
  },
  // Redmi Note 12 5G
  {
    id: 'redmi-note-12-5g-4-128',
    modelId: 'redmi-note-12-5g',
    ram: '4GB',
    storage: '128GB',
    price: 13999,
    mrp: 17999,
    status: 'discontinued',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Frosted Green', 'Matte Black'],
  },
  {
    id: 'redmi-note-12-5g-6-128',
    modelId: 'redmi-note-12-5g',
    ram: '6GB',
    storage: '128GB',
    price: 15499,
    mrp: 19999,
    status: 'discontinued',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Frosted Green', 'Matte Black'],
  },
  // Redmi Note 11 Pro+ 5G
  {
    id: 'redmi-note-11-pro-plus-5g-6-128',
    modelId: 'redmi-note-11-pro-plus-5g',
    ram: '6GB',
    storage: '128GB',
    price: 17999,
    mrp: 20999,
    status: 'discontinued',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Mirage Blue', 'Stealth Black'],
  },
  {
    id: 'redmi-note-11-pro-plus-5g-8-256',
    modelId: 'redmi-note-11-pro-plus-5g',
    ram: '8GB',
    storage: '256GB',
    price: 20999,
    mrp: 23999,
    status: 'discontinued',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Mirage Blue', 'Stealth Black'],
  },
  // Redmi Note 11
  {
    id: 'redmi-note-11-4-64',
    modelId: 'redmi-note-11',
    ram: '4GB',
    storage: '64GB',
    price: 11999,
    mrp: 13499,
    status: 'discontinued',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Horizon Blue', 'Space Black'],
  },
  {
    id: 'redmi-note-11-6-128',
    modelId: 'redmi-note-11',
    ram: '6GB',
    storage: '128GB',
    price: 13999,
    mrp: 15999,
    status: 'discontinued',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Horizon Blue', 'Space Black'],
  },
  // Redmi 13 5G
  {
    id: 'redmi-13-5g-6-128',
    modelId: 'redmi-13-5g',
    ram: '6GB',
    storage: '128GB',
    price: 13999,
    mrp: 13999,
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Hawaiian Blue', 'Black Diamond'],
  },
  {
    id: 'redmi-13-5g-8-128',
    modelId: 'redmi-13-5g',
    ram: '8GB',
    storage: '128GB',
    price: 15499,
    mrp: 15499,
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Hawaiian Blue', 'Black Diamond'],
  },
  // Redmi 13C 5G
  {
    id: 'redmi-13c-5g-4-128',
    modelId: 'redmi-13c-5g',
    ram: '4GB',
    storage: '128GB',
    price: 10499,
    mrp: 10999,
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Starlight Black', 'Startrail Green'],
  },
  {
    id: 'redmi-13c-5g-8-256',
    modelId: 'redmi-13c-5g',
    ram: '8GB',
    storage: '256GB',
    price: 13499,
    mrp: 14499,
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Starlight Black', 'Startrail Green'],
  },
  // Redmi 13C
  {
    id: 'redmi-13c-4-128',
    modelId: 'redmi-13c',
    ram: '4GB',
    storage: '128GB',
    price: 7999,
    mrp: 8999,
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Starlight Black', 'Starshine Green'],
  },
  {
    id: 'redmi-13c-8-256',
    modelId: 'redmi-13c',
    ram: '8GB',
    storage: '256GB',
    price: 9999,
    mrp: 11499,
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Starlight Black', 'Starshine Green'],
  },
  // Redmi 12 5G
  {
    id: 'redmi-12-5g-4-128',
    modelId: 'redmi-12-5g',
    ram: '4GB',
    storage: '128GB',
    price: 11499,
    mrp: 11999,
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Moonstone Silver', 'Jade Black'],
  },
  {
    id: 'redmi-12-5g-8-256',
    modelId: 'redmi-12-5g',
    ram: '8GB',
    storage: '256GB',
    price: 13999,
    mrp: 15499,
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Moonstone Silver', 'Jade Black'],
  },
  // Redmi A3
  {
    id: 'redmi-a3-3-64',
    modelId: 'redmi-a3',
    ram: '3GB',
    storage: '64GB',
    price: 6999,
    mrp: 7299,
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Olive Green', 'Midnight Black'],
  },
  {
    id: 'redmi-a3-6-128',
    modelId: 'redmi-a3',
    ram: '6GB',
    storage: '128GB',
    price: 7999,
    mrp: 9299,
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Olive Green', 'Midnight Black'],
  },
  // Redmi A2+
  {
    id: 'redmi-a2-plus-2-32',
    modelId: 'redmi-a2-plus',
    ram: '2GB',
    storage: '32GB',
    price: 5999,
    mrp: 6999,
    status: 'discontinued',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Aqua Blue', 'Classic Black'],
  },
  {
    id: 'redmi-a2-plus-4-64',
    modelId: 'redmi-a2-plus',
    ram: '4GB',
    storage: '64GB',
    price: 6999,
    mrp: 8499,
    status: 'discontinued',
    verified: true,
    source: 'Mi India Official Store',
    colors: ['Aqua Blue', 'Classic Black'],
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    "modelId": "redmi-note-14-pro-plus-5g",
    "modelName": "Redmi Note 14 Pro+ 5G",
    "brand": "Redmi",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-14-pro-plus-5g.jpg",
        "angle": "front",
        "source": "Redmi Official / GSMArena Verified",
        "sourceUrl": "https://www.mi.com/in/product/redmi-note-14-pro-plus-5g/",
        "verified": true,
        "alt": "Redmi Redmi Note 14 Pro+ 5G official product photography"
      }
    ]
  },
  {
    "modelId": "redmi-note-14-pro-5g",
    "modelName": "Redmi Note 14 Pro 5G",
    "brand": "Redmi",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-14-pro-5g.jpg",
        "angle": "front",
        "source": "Redmi Official / GSMArena Verified",
        "sourceUrl": "https://www.mi.com/in/product/redmi-note-14-pro-5g/",
        "verified": true,
        "alt": "Redmi Redmi Note 14 Pro 5G official product photography"
      }
    ]
  },
  {
    "modelId": "redmi-note-14-5g",
    "modelName": "Redmi Note 14 5G",
    "brand": "Redmi",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-14-5g.jpg",
        "angle": "front",
        "source": "Redmi Official / GSMArena Verified",
        "sourceUrl": "https://www.mi.com/in/product/redmi-note-14-5g/",
        "verified": true,
        "alt": "Redmi Redmi Note 14 5G official product photography"
      }
    ]
  },
  {
    "modelId": "redmi-note-13-pro-plus-5g",
    "modelName": "Redmi Note 13 Pro+ 5G",
    "brand": "Redmi",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-13-pro-plus.jpg",
        "angle": "front",
        "source": "Redmi Official / GSMArena Verified",
        "sourceUrl": "https://www.mi.com/in/product/redmi-note-13-pro-plus-5g/",
        "verified": true,
        "alt": "Redmi Redmi Note 13 Pro+ 5G official product photography"
      }
    ]
  },
  {
    "modelId": "redmi-note-13-pro-5g",
    "modelName": "Redmi Note 13 Pro 5G",
    "brand": "Redmi",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-13-pro-5g.jpg",
        "angle": "front",
        "source": "Redmi Official / GSMArena Verified",
        "sourceUrl": "https://www.mi.com/in/product/redmi-note-13-pro-5g/",
        "verified": true,
        "alt": "Redmi Redmi Note 13 Pro 5G official product photography"
      }
    ]
  },
  {
    "modelId": "redmi-note-13-5g",
    "modelName": "Redmi Note 13 5G",
    "brand": "Redmi",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-13-5g.jpg",
        "angle": "front",
        "source": "Redmi Official / GSMArena Verified",
        "sourceUrl": "https://www.mi.com/in/product/redmi-note-13-5g/",
        "verified": true,
        "alt": "Redmi Redmi Note 13 5G official product photography"
      }
    ]
  },
  {
    "modelId": "redmi-note-12-pro-plus-5g",
    "modelName": "Redmi Note 12 Pro+ 5G",
    "brand": "Redmi",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-12-pro-plus.jpg",
        "angle": "front",
        "source": "Redmi Official / GSMArena Verified",
        "sourceUrl": "https://www.mi.com/in/product/redmi-note-12-pro-plus-5g/",
        "verified": true,
        "alt": "Redmi Redmi Note 12 Pro+ 5G official product photography"
      }
    ]
  },
  {
    "modelId": "redmi-note-12-pro-5g",
    "modelName": "Redmi Note 12 Pro 5G",
    "brand": "Redmi",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-12-pro.jpg",
        "angle": "front",
        "source": "Redmi Official / GSMArena Verified",
        "sourceUrl": "https://www.mi.com/in/product/redmi-note-12-pro-5g/",
        "verified": true,
        "alt": "Redmi Redmi Note 12 Pro 5G official product photography"
      }
    ]
  },
  {
    "modelId": "redmi-note-12-5g",
    "modelName": "Redmi Note 12 5G",
    "brand": "Redmi",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-12-5g.jpg",
        "angle": "front",
        "source": "Redmi Official / GSMArena Verified",
        "sourceUrl": "https://www.mi.com/in/product/redmi-note-12-5g/",
        "verified": true,
        "alt": "Redmi Redmi Note 12 5G official product photography"
      }
    ]
  },
  {
    "modelId": "redmi-note-11-pro-plus-5g",
    "modelName": "Redmi Note 11 Pro+ 5G",
    "brand": "Redmi",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-note-11-pro-plus-5g.jpg",
        "angle": "front",
        "source": "Redmi Official / GSMArena Verified",
        "sourceUrl": "https://www.mi.com/in/product/redmi-note-11-pro-plus-5g/",
        "verified": true,
        "alt": "Redmi Redmi Note 11 Pro+ 5G official product photography"
      }
    ]
  },
  {
    "modelId": "redmi-note-11",
    "modelName": "Redmi Note 11",
    "brand": "Redmi",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-11-global.jpg",
        "angle": "front",
        "source": "Redmi Official / GSMArena Verified",
        "sourceUrl": "https://www.mi.com/in/product/redmi-note-11/",
        "verified": true,
        "alt": "Redmi Redmi Note 11 official product photography"
      }
    ]
  },
  {
    "modelId": "redmi-13-5g",
    "modelName": "Redmi 13 5G",
    "brand": "Redmi",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-13-5g.jpg",
        "angle": "front",
        "source": "Redmi Official / GSMArena Verified",
        "sourceUrl": "https://www.mi.com/in/product/redmi-13-5g/",
        "verified": true,
        "alt": "Redmi Redmi 13 5G official product photography"
      }
    ]
  },
  {
    "modelId": "redmi-13c-5g",
    "modelName": "Redmi 13C 5G",
    "brand": "Redmi",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-13c-5g.jpg",
        "angle": "front",
        "source": "Redmi Official / GSMArena Verified",
        "sourceUrl": "https://www.mi.com/in/product/redmi-13c-5g/",
        "verified": true,
        "alt": "Redmi Redmi 13C 5G official product photography"
      }
    ]
  },
  {
    "modelId": "redmi-13c",
    "modelName": "Redmi 13C",
    "brand": "Redmi",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-13c.jpg",
        "angle": "front",
        "source": "Redmi Official / GSMArena Verified",
        "sourceUrl": "https://www.mi.com/in/product/redmi-13c/",
        "verified": true,
        "alt": "Redmi Redmi 13C official product photography"
      }
    ]
  },
  {
    "modelId": "redmi-12-5g",
    "modelName": "Redmi 12 5G",
    "brand": "Redmi",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-12-5g.jpg",
        "angle": "front",
        "source": "Redmi Official / GSMArena Verified",
        "sourceUrl": "https://www.mi.com/in/product/redmi-12-5g/",
        "verified": true,
        "alt": "Redmi Redmi 12 5G official product photography"
      }
    ]
  },
  {
    "modelId": "redmi-a3",
    "modelName": "Redmi A3",
    "brand": "Redmi",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-a3.jpg",
        "angle": "front",
        "source": "Redmi Official / GSMArena Verified",
        "sourceUrl": "https://www.mi.com/in/product/redmi-a3/",
        "verified": true,
        "alt": "Redmi Redmi A3 official product photography"
      }
    ]
  },
  {
    "modelId": "redmi-a2-plus",
    "modelName": "Redmi A2+",
    "brand": "Redmi",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-a2-plus.jpg",
        "angle": "front",
        "source": "Redmi Official / GSMArena Verified",
        "sourceUrl": "https://www.mi.com/in/product/redmi-a2-plus/",
        "verified": true,
        "alt": "Redmi Redmi A2+ official product photography"
      }
    ]
  }
];

export const redmiBundle: MobileBrandBundle = {
  brand: 'Redmi',
  models,
  variants,
  images,
};
