import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  {
    id: 'samsung-galaxy-s25-ultra',
    slug: 'samsung-galaxy-s25-ultra',
    brand: 'Samsung',
    modelName: 'Galaxy S25 Ultra',
    generation: 'S25',
    status: 'active',
    launchDate: '2025-01',
    pricing: {
      startingPrice: 129999,
      maximumPrice: 159999,
      launchPrice: 129999,
      currentPrice: 129999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Samsung India Official Store',
    },
    display: {
      displaySize: 6.8,
      displayType: 'Dynamic LTPO AMOLED 2X',
      resolution: '3120 x 1440 pixels (QHD+)',
      refreshRate: 120,
      peakBrightness: 2600,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Armor',
      screenToBodyRatio: '89.8%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Elite for Galaxy',
      cpu: 'Octa-core (2x4.47 GHz Oryon V2 Phoenix & 6x3.53 GHz)',
      gpu: 'Adreno 830',
      ramOptions: ['12GB'],
      storageOptions: ['256GB', '512GB', '1TB'],
      storageType: 'UFS 4.0',
      antutuScore: 2850000,
      geekbenchSingle: 3210,
      geekbenchMulti: 9850,
    },
    cameras: {
      rearCameraSetup: 'Quad (200MP + 50MP + 50MP + 10MP)',
      mainCamera: '200 MP, f/1.7, 24mm (wide), 1/1.3", multi-directional PDAF, Laser AF, OIS',
      ultrawideCamera: '50 MP, f/1.9, 120˚, Dual Pixel PDAF',
      telephotoCamera: '50 MP periscope (5x optical zoom, OIS) + 10 MP telephoto (3x optical zoom, OIS)',
      frontCamera: '12 MP, f/2.2, 26mm, Dual Pixel PDAF, 4K60',
      videoRecording: '8K@30fps, 4K@30/60/120fps, 1080p@240fps, HDR10+, stereo sound',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 45,
      wirelessCharging: 15,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7 (802.11be)',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 3.2, DisplayPort, OTG',
      simConfig: 'Dual SIM (Nano-SIM and eSIM)',
    },
    physical: {
      dimensions: '162.8 x 77.6 x 8.2 mm',
      weight: 219,
      materials: 'Titanium frame (grade 5), Gorilla Armor front/back',
      waterResistance: 'IP68 (up to 1.5m for 30 min)',
      colors: ['Titanium Silver Shadow', 'Titanium Black', 'Titanium Gray', 'Titanium Blue'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'One UI 7.0',
      launchOS: 'Android 15',
      promisedMajorUpdates: 7,
      securityUpdatePolicy: '7 years of security patches',
    },
    audio: {
      speakers: 'Stereo speakers tuned by AKG',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Ultrasonic under display',
      faceUnlock: true,
      biometricNotes: 'Samsung Knox Vault security hardware',
    },
    keyHighlights: [
      'Snapdragon 8 Elite for Galaxy with flagship performance',
      'Quad camera system with 200MP main and dual OIS telephotos',
      'Anti-reflective Gorilla Armor glass reduces glare by 75%',
      'Integrated S Pen stylus with Bluetooth Air actions',
      'Industry-leading 7 years of OS upgrades and security updates',
    ],
    pros: [
      'Unrivaled display glare reduction and outdoor visibility',
      'Versatile 200MP + 5x + 3x zoom camera hardware',
      'Full 7 years of major OS and security support',
      'Integrated S Pen functionality',
      'Superb premium titanium build',
    ],
    cons: [
      'High starting price above ₹1.29 lakh',
      'Charging speed remains capped at 45W',
      'No charger in the box',
    ],
    sources: {
      officialWebsite: 'https://www.samsung.com/in/smartphones/galaxy-s25-ultra/',
      productPage: 'https://www.samsung.com/in/smartphones/galaxy-s25-ultra/buy/',
      specSheetUrl: 'https://www.samsung.com/in/smartphones/galaxy-s25-ultra/specs/',
      verifiedDate: '2025-01',
    },
  },

  {
    id: 'samsung-galaxy-s25-plus',
    slug: 'samsung-galaxy-s25-plus',
    brand: 'Samsung',
    modelName: 'Galaxy S25+',
    generation: 'S25',
    status: 'active',
    launchDate: '2025-01',
    pricing: {
      startingPrice: 99999,
      maximumPrice: 109999,
      launchPrice: 99999,
      currentPrice: 99999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Samsung India Official Store',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Dynamic LTPO AMOLED 2X',
      resolution: '3120 x 1440 pixels (QHD+)',
      refreshRate: 120,
      peakBrightness: 2600,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '91.8%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Elite for Galaxy',
      cpu: 'Octa-core (2x4.47 GHz Oryon & 6x3.53 GHz)',
      gpu: 'Adreno 830',
      ramOptions: ['12GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 2800000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 12MP + 10MP)',
      mainCamera: '50 MP, f/1.8, 24mm, 1/1.56", Dual Pixel PDAF, OIS',
      ultrawideCamera: '12 MP, f/2.2, 13mm, 120˚',
      telephotoCamera: '10 MP, f/2.4, 67mm, 3x optical zoom, OIS',
      frontCamera: '12 MP, f/2.2, 26mm, Dual Pixel PDAF',
      videoRecording: '8K@30fps, 4K@60fps, 1080p@240fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4900,
      wiredCharging: 45,
      wirelessCharging: 15,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 3.2, OTG',
      simConfig: 'Dual SIM (Nano-SIM + eSIM)',
    },
    physical: {
      dimensions: '158.4 x 75.7 x 7.3 mm',
      weight: 190,
      materials: 'Armor Aluminum frame, Gorilla Glass Victus 2 back',
      waterResistance: 'IP68',
      colors: ['Navy', 'Silver Shadow', 'Icy Blue', 'Mint'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'One UI 7.0',
      launchOS: 'Android 15',
      promisedMajorUpdates: 7,
      securityUpdatePolicy: '7 years of security patches',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Ultrasonic under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.samsung.com/in/smartphones/galaxy-s25-plus/',
      productPage: 'https://www.samsung.com/in/smartphones/galaxy-s25-plus/buy/',
      specSheetUrl: 'https://www.samsung.com/in/smartphones/galaxy-s25-plus/specs/',
      verifiedDate: '2025-01',
    },
  },

  {
    id: 'samsung-galaxy-s25',
    slug: 'samsung-galaxy-s25',
    brand: 'Samsung',
    modelName: 'Galaxy S25',
    generation: 'S25',
    status: 'active',
    launchDate: '2025-01',
    pricing: {
      startingPrice: 79999,
      maximumPrice: 89999,
      launchPrice: 79999,
      currentPrice: 79999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Samsung India Official Store',
    },
    display: {
      displaySize: 6.2,
      displayType: 'Dynamic LTPO AMOLED 2X',
      resolution: '2340 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 2600,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '91.2%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Elite for Galaxy',
      cpu: 'Octa-core (2x4.47 GHz Oryon & 6x3.53 GHz)',
      gpu: 'Adreno 830',
      ramOptions: ['12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 4.0',
      antutuScore: 2750000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 12MP + 10MP)',
      mainCamera: '50 MP, f/1.8, 24mm, 1/1.56", Dual Pixel PDAF, OIS',
      ultrawideCamera: '12 MP, f/2.2, 13mm, 120˚',
      telephotoCamera: '10 MP, f/2.4, 67mm, 3x optical zoom, OIS',
      frontCamera: '12 MP, f/2.2, 26mm, Dual Pixel PDAF',
      videoRecording: '8K@30fps, 4K@60fps, 1080p@240fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4000,
      wiredCharging: 25,
      wirelessCharging: 15,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 3.2, OTG',
      simConfig: 'Dual SIM (Nano-SIM + eSIM)',
    },
    physical: {
      dimensions: '146.9 x 70.4 x 7.2 mm',
      weight: 162,
      materials: 'Armor Aluminum frame, Gorilla Glass Victus 2 back',
      waterResistance: 'IP68',
      colors: ['Navy', 'Silver Shadow', 'Icy Blue', 'Mint'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'One UI 7.0',
      launchOS: 'Android 15',
      promisedMajorUpdates: 7,
      securityUpdatePolicy: '7 years of security patches',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Ultrasonic under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.samsung.com/in/smartphones/galaxy-s25/',
      productPage: 'https://www.samsung.com/in/smartphones/galaxy-s25/buy/',
      specSheetUrl: 'https://www.samsung.com/in/smartphones/galaxy-s25/specs/',
      verifiedDate: '2025-01',
    },
  },

  {
    id: 'samsung-galaxy-s24-ultra',
    slug: 'samsung-galaxy-s24-ultra',
    brand: 'Samsung',
    modelName: 'Galaxy S24 Ultra',
    generation: 'S24',
    status: 'active',
    launchDate: '2024-01',
    pricing: {
      startingPrice: 109999,
      maximumPrice: 139999,
      launchPrice: 129999,
      currentPrice: 109999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Samsung India Official Store',
    },
    display: {
      displaySize: 6.8,
      displayType: 'Dynamic LTPO AMOLED 2X',
      resolution: '3120 x 1440 pixels (QHD+)',
      refreshRate: 120,
      peakBrightness: 2600,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Armor',
      screenToBodyRatio: '88.5%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Gen 3 for Galaxy',
      cpu: 'Octa-core (1x3.39GHz Cortex-X4 & 5x3.1GHz & 2x2.2GHz)',
      gpu: 'Adreno 750',
      ramOptions: ['12GB'],
      storageOptions: ['256GB', '512GB', '1TB'],
      storageType: 'UFS 4.0',
      antutuScore: 2150000,
    },
    cameras: {
      rearCameraSetup: 'Quad (200MP + 50MP + 10MP + 12MP)',
      mainCamera: '200 MP, f/1.7, 24mm, OIS',
      ultrawideCamera: '12 MP, f/2.2, 120˚',
      telephotoCamera: '50 MP periscope (5x optical zoom, OIS) + 10 MP telephoto (3x optical zoom, OIS)',
      frontCamera: '12 MP, f/2.2, 26mm, 4K60',
      videoRecording: '8K@30fps, 4K@120fps, 1080p@240fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 45,
      wirelessCharging: 15,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 3.2, DisplayPort',
      simConfig: 'Dual SIM (Nano-SIM + eSIM)',
    },
    physical: {
      dimensions: '162.3 x 79.0 x 8.6 mm',
      weight: 232,
      materials: 'Titanium frame, Gorilla Armor front/back',
      waterResistance: 'IP68',
      colors: ['Titanium Gray', 'Titanium Black', 'Titanium Violet', 'Titanium Yellow'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'One UI 6.1.1 (Upgradable to One UI 7)',
      launchOS: 'Android 14',
      promisedMajorUpdates: 7,
      securityUpdatePolicy: '7 years of security patches',
    },
    audio: {
      speakers: 'Stereo speakers tuned by AKG',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Ultrasonic under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.samsung.com/in/smartphones/galaxy-s24-ultra/',
      productPage: 'https://www.samsung.com/in/smartphones/galaxy-s24-ultra/buy/',
      specSheetUrl: 'https://www.samsung.com/in/smartphones/galaxy-s24-ultra/specs/',
      verifiedDate: '2025-01',
    },
  },

  {
    id: 'samsung-galaxy-s24',
    slug: 'samsung-galaxy-s24',
    brand: 'Samsung',
    modelName: 'Galaxy S24',
    generation: 'S24',
    status: 'active',
    launchDate: '2024-01',
    pricing: {
      startingPrice: 62999,
      maximumPrice: 74999,
      launchPrice: 79999,
      currentPrice: 62999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Samsung India Official Store',
    },
    display: {
      displaySize: 6.2,
      displayType: 'Dynamic LTPO AMOLED 2X',
      resolution: '2340 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 2600,
      hdr: 'HDR10+',
      protection: 'Gorilla Glass Victus 2',
      screenToBodyRatio: '90.9%',
    },
    performance: {
      chipset: 'Samsung Exynos 2400 (India)',
      cpu: 'Deca-core (1x3.2GHz Cortex-X4 & 2x2.9GHz & 3x2.6GHz & 4x1.95GHz)',
      gpu: 'Xclipse 940',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB', '512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 1780000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 12MP + 10MP)',
      mainCamera: '50 MP, f/1.8, OIS',
      ultrawideCamera: '12 MP, f/2.2, 120˚',
      telephotoCamera: '10 MP, f/2.4, 3x optical, OIS',
      frontCamera: '12 MP, f/2.2, 4K60',
      videoRecording: '8K@30fps, 4K@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4000,
      wiredCharging: 25,
      wirelessCharging: 15,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 3.2',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '147.0 x 70.6 x 7.6 mm',
      weight: 167,
      materials: 'Armor Aluminum 2, Glass Victus 2',
      waterResistance: 'IP68',
      colors: ['Onyx Black', 'Marble Gray', 'Cobalt Violet', 'Amber Yellow'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'One UI 6.1.1',
      launchOS: 'Android 14',
      promisedMajorUpdates: 7,
      securityUpdatePolicy: '7 years of security patches',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Ultrasonic under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.samsung.com/in/smartphones/galaxy-s24/',
      productPage: 'https://www.samsung.com/in/smartphones/galaxy-s24/buy/',
      specSheetUrl: 'https://www.samsung.com/in/smartphones/galaxy-s24/specs/',
      verifiedDate: '2025-01',
    },
  },

  {
    id: 'samsung-galaxy-s24-fe',
    slug: 'samsung-galaxy-s24-fe',
    brand: 'Samsung',
    modelName: 'Galaxy S24 FE',
    generation: 'S24 FE',
    status: 'active',
    launchDate: '2024-09',
    pricing: {
      startingPrice: 54999,
      maximumPrice: 59999,
      launchPrice: 59999,
      currentPrice: 54999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Samsung India Official Store',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Dynamic AMOLED 2X',
      resolution: '2340 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1900,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass Victus+',
      screenToBodyRatio: '88.0%',
    },
    performance: {
      chipset: 'Samsung Exynos 2400e (4nm)',
      cpu: 'Deca-core (1x3.11 GHz Cortex-X4 & 2x2.90 GHz & 3x2.59 GHz & 4x1.96 GHz)',
      gpu: 'Xclipse 940',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1 / 4.0',
      antutuScore: 1650000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 12MP + 8MP)',
      mainCamera: '50 MP, f/1.8, 24mm (wide), Dual Pixel PDAF, OIS',
      ultrawideCamera: '12 MP, f/2.2, 123˚',
      telephotoCamera: '8 MP, f/2.4, 75mm, 3x optical zoom, OIS',
      frontCamera: '10 MP, f/2.4, 26mm',
      videoRecording: '8K@30fps, 4K@60fps, 1080p@240fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4700,
      wiredCharging: 25,
      wirelessCharging: 15,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 3.2, OTG',
      simConfig: 'Dual SIM (Nano-SIM + eSIM)',
    },
    physical: {
      dimensions: '162.0 x 77.3 x 8.0 mm',
      weight: 213,
      materials: 'Aluminum frame, Gorilla Glass Victus+ back',
      waterResistance: 'IP68',
      colors: ['Blue', 'Graphite', 'Gray', 'Mint', 'Yellow'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'One UI 6.1.1',
      launchOS: 'Android 14',
      promisedMajorUpdates: 7,
      securityUpdatePolicy: '7 years of security patches',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.samsung.com/in/smartphones/galaxy-s24-fe/',
      productPage: 'https://www.samsung.com/in/smartphones/galaxy-s24-fe/buy/',
      specSheetUrl: 'https://www.samsung.com/in/smartphones/galaxy-s24-fe/specs/',
      verifiedDate: '2025-01',
    },
  },

  {
    id: 'samsung-galaxy-s23',
    slug: 'samsung-galaxy-s23',
    brand: 'Samsung',
    modelName: 'Galaxy S23',
    generation: 'S23',
    status: 'active',
    launchDate: '2023-02',
    pricing: {
      startingPrice: 42999,
      maximumPrice: 47999,
      launchPrice: 74999,
      currentPrice: 42999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Samsung India Official Store',
    },
    display: {
      displaySize: 6.1,
      displayType: 'Dynamic AMOLED 2X',
      resolution: '2340 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 1750,
      hdr: 'HDR10+',
      protection: 'Gorilla Glass Victus 2',
      screenToBodyRatio: '86.8%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Gen 2 for Galaxy',
      cpu: 'Octa-core (1x3.36 GHz Cortex-X3 & 4x2.8 GHz & 3x2.0 GHz)',
      gpu: 'Adreno 740',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 4.0',
      antutuScore: 1520000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 12MP + 10MP)',
      mainCamera: '50 MP, f/1.8, OIS',
      ultrawideCamera: '12 MP, f/2.2, 120˚',
      telephotoCamera: '10 MP, f/2.4, 3x optical, OIS',
      frontCamera: '12 MP, f/2.2, 4K60',
      videoRecording: '8K@30fps, 4K@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 3900,
      wiredCharging: 25,
      wirelessCharging: 15,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 3.2',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '146.3 x 70.9 x 7.6 mm',
      weight: 168,
      materials: 'Armor Aluminum frame, Gorilla Glass Victus 2',
      waterResistance: 'IP68',
      colors: ['Phantom Black', 'Cream', 'Green', 'Lavender'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'One UI 6.1',
      launchOS: 'Android 13',
      promisedMajorUpdates: 4,
      securityUpdatePolicy: '5 years of security patches',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Ultrasonic under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.samsung.com/in/smartphones/galaxy-s23/',
      productPage: 'https://www.samsung.com/in/smartphones/galaxy-s23/buy/',
      specSheetUrl: 'https://www.samsung.com/in/smartphones/galaxy-s23/specs/',
      verifiedDate: '2025-01',
    },
  },

  {
    id: 'samsung-galaxy-z-fold-6',
    slug: 'samsung-galaxy-z-fold-6',
    brand: 'Samsung',
    modelName: 'Galaxy Z Fold 6',
    generation: 'Z Fold 6',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 164999,
      maximumPrice: 200999,
      launchPrice: 164999,
      currentPrice: 164999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Samsung India Official Store',
    },
    display: {
      displaySize: 7.6,
      displayType: 'Foldable Dynamic LTPO AMOLED 2X (Cover: 6.3")',
      resolution: '2160 x 1856 pixels (Cover: 2376 x 968)',
      refreshRate: 120,
      peakBrightness: 2600,
      hdr: 'HDR10+',
      protection: 'Gorilla Glass Victus 2',
      screenToBodyRatio: '91.0%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Gen 3 for Galaxy',
      cpu: 'Octa-core (1x3.39GHz & 5x3.1GHz & 2x2.2GHz)',
      gpu: 'Adreno 750',
      ramOptions: ['12GB'],
      storageOptions: ['256GB', '512GB', '1TB'],
      storageType: 'UFS 4.0',
      antutuScore: 2180000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 12MP + 10MP)',
      mainCamera: '50 MP, f/1.8, Dual Pixel PDAF, OIS',
      ultrawideCamera: '12 MP, f/2.2, 123˚',
      telephotoCamera: '10 MP, f/2.4, 3x optical, OIS',
      frontCamera: '4 MP Under-display + 10 MP Cover camera',
      videoRecording: '8K@30fps, 4K@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4400,
      wiredCharging: 25,
      wirelessCharging: 15,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E/7',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 3.2',
      simConfig: 'Dual SIM + eSIM',
    },
    physical: {
      dimensions: '153.5 x 132.6 x 5.6 mm (Folded: 153.5 x 68.1 x 12.1 mm)',
      weight: 239,
      materials: 'Armor Aluminum frame, Victus 2 glass',
      waterResistance: 'IP48 dust & water resistant',
      colors: ['Silver Shadow', 'Pink', 'Navy'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'One UI 6.1.1',
      launchOS: 'Android 14',
      promisedMajorUpdates: 7,
      securityUpdatePolicy: '7 years of security patches',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.samsung.com/in/smartphones/galaxy-z-fold6/',
      productPage: 'https://www.samsung.com/in/smartphones/galaxy-z-fold6/buy/',
      specSheetUrl: 'https://www.samsung.com/in/smartphones/galaxy-z-fold6/specs/',
      verifiedDate: '2025-01',
    },
  },

  {
    id: 'samsung-galaxy-z-flip-6',
    slug: 'samsung-galaxy-z-flip-6',
    brand: 'Samsung',
    modelName: 'Galaxy Z Flip 6',
    generation: 'Z Flip 6',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 109999,
      maximumPrice: 121999,
      launchPrice: 109999,
      currentPrice: 109999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Samsung India Official Store',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Foldable Dynamic LTPO AMOLED 2X (Cover: 3.4" Super AMOLED)',
      resolution: '2640 x 1080 pixels (Cover: 720 x 748)',
      refreshRate: 120,
      peakBrightness: 2600,
      hdr: 'HDR10+',
      protection: 'Gorilla Glass Victus 2',
      screenToBodyRatio: '85.5%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Gen 3 for Galaxy',
      cpu: 'Octa-core (1x3.39GHz & 5x3.1GHz & 2x2.2GHz)',
      gpu: 'Adreno 750',
      ramOptions: ['12GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 2050000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 12MP)',
      mainCamera: '50 MP, f/1.8, Dual Pixel PDAF, OIS',
      ultrawideCamera: '12 MP, f/2.2, 123˚',
      telephotoCamera: 'None (2x in-sensor crop)',
      frontCamera: '10 MP, f/2.2, 4K60',
      videoRecording: '4K@60fps, 1080p@240fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4000,
      wiredCharging: 25,
      wirelessCharging: 15,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 3.2',
      simConfig: 'Dual SIM (Nano-SIM + eSIM)',
    },
    physical: {
      dimensions: '165.1 x 71.9 x 6.9 mm (Folded: 85.1 x 71.9 x 14.9 mm)',
      weight: 187,
      materials: 'Armor Aluminum, Gorilla Glass Victus 2',
      waterResistance: 'IP48 dust & water resistant',
      colors: ['Silver Shadow', 'Yellow', 'Blue', 'Mint'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'One UI 6.1.1',
      launchOS: 'Android 14',
      promisedMajorUpdates: 7,
      securityUpdatePolicy: '7 years of security patches',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.samsung.com/in/smartphones/galaxy-z-flip6/',
      productPage: 'https://www.samsung.com/in/smartphones/galaxy-z-flip6/buy/',
      specSheetUrl: 'https://www.samsung.com/in/smartphones/galaxy-z-flip6/specs/',
      verifiedDate: '2025-01',
    },
  },

  {
    id: 'samsung-galaxy-a55-5g',
    slug: 'samsung-galaxy-a55-5g',
    brand: 'Samsung',
    modelName: 'Galaxy A55 5G',
    generation: 'A55',
    status: 'active',
    launchDate: '2024-03',
    pricing: {
      startingPrice: 36999,
      maximumPrice: 42999,
      launchPrice: 39999,
      currentPrice: 36999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Samsung India Official Store',
    },
    display: {
      displaySize: 6.6,
      displayType: 'Super AMOLED',
      resolution: '2340 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1000,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass Victus+',
      screenToBodyRatio: '85.8%',
    },
    performance: {
      chipset: 'Samsung Exynos 1480 (4nm)',
      cpu: 'Octa-core (4x2.75 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)',
      gpu: 'Xclipse 530 (AMD RDNA architecture)',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 720000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 12MP + 5MP)',
      mainCamera: '50 MP, f/1.8, (wide), 1/1.56", PDAF, OIS',
      ultrawideCamera: '12 MP, f/2.2, 123˚',
      telephotoCamera: 'None (5 MP Macro)',
      frontCamera: '32 MP, f/2.2, 26mm, 4K30',
      videoRecording: '4K@30fps, 1080p@60fps, gyro-EIS',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 25,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0, OTG',
      simConfig: 'Hybrid Dual SIM (Nano-SIM + eSIM/microSD)',
    },
    physical: {
      dimensions: '161.1 x 77.4 x 8.2 mm',
      weight: 213,
      materials: 'Metal frame (Key Island design), Gorilla Glass Victus+ back',
      waterResistance: 'IP67 dust/water resistant (up to 1m for 30 min)',
      colors: ['Awesome Iceblue', 'Awesome Navy', 'Awesome Lilac', 'Awesome Lemon'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'One UI 6.1',
      launchOS: 'Android 14',
      promisedMajorUpdates: 4,
      securityUpdatePolicy: '5 years of security patches',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.samsung.com/in/smartphones/galaxy-a55-5g/',
      productPage: 'https://www.samsung.com/in/smartphones/galaxy-a55-5g/buy/',
      specSheetUrl: 'https://www.samsung.com/in/smartphones/galaxy-a55-5g/specs/',
      verifiedDate: '2025-01',
    },
  },

  {
    id: 'samsung-galaxy-a35-5g',
    slug: 'samsung-galaxy-a35-5g',
    brand: 'Samsung',
    modelName: 'Galaxy A35 5G',
    generation: 'A35',
    status: 'active',
    launchDate: '2024-03',
    pricing: {
      startingPrice: 27999,
      maximumPrice: 30999,
      launchPrice: 30999,
      currentPrice: 27999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Samsung India Official Store',
    },
    display: {
      displaySize: 6.6,
      displayType: 'Super AMOLED',
      resolution: '2340 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 1000,
      hdr: 'HDR10+',
      protection: 'Gorilla Glass Victus+',
      screenToBodyRatio: '84.8%',
    },
    performance: {
      chipset: 'Samsung Exynos 1380 (5nm)',
      cpu: 'Octa-core (4x2.4 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G68 MP5',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 590000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 8MP + 5MP)',
      mainCamera: '50 MP, f/1.8, PDAF, OIS',
      ultrawideCamera: '8 MP, f/2.2, 123˚',
      telephotoCamera: 'None (5 MP Macro)',
      frontCamera: '13 MP, f/2.2, 4K30',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 25,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '161.7 x 78.0 x 8.2 mm',
      weight: 209,
      materials: 'Plastic frame, Glass back',
      waterResistance: 'IP67',
      colors: ['Awesome Iceblue', 'Awesome Navy', 'Awesome Lilac'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'One UI 6.1',
      launchOS: 'Android 14',
      promisedMajorUpdates: 4,
      securityUpdatePolicy: '5 years of security patches',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.samsung.com/in/smartphones/galaxy-a35-5g/',
      productPage: 'https://www.samsung.com/in/smartphones/galaxy-a35-5g/buy/',
      specSheetUrl: 'https://www.samsung.com/in/smartphones/galaxy-a35-5g/specs/',
      verifiedDate: '2025-01',
    },
  },

  {
    id: 'samsung-galaxy-a16-5g',
    slug: 'samsung-galaxy-a16-5g',
    brand: 'Samsung',
    modelName: 'Galaxy A16 5G',
    generation: 'A16',
    status: 'active',
    launchDate: '2024-10',
    pricing: {
      startingPrice: 15499,
      maximumPrice: 18999,
      launchPrice: 15499,
      currentPrice: 15499,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Samsung India Official Store',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Super AMOLED',
      resolution: '2340 x 1080 pixels (FHD+)',
      refreshRate: 90,
      peakBrightness: 800,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '86.0%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6300 (6nm)',
      cpu: 'Octa-core (2x2.4 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['6GB', '8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 420000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 5MP + 2MP)',
      mainCamera: '50 MP, f/1.8, AF',
      ultrawideCamera: '5 MP, f/2.2',
      telephotoCamera: 'None (2 MP Macro)',
      frontCamera: '13 MP, f/2.0',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 25,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '164.4 x 77.9 x 7.9 mm',
      weight: 200,
      materials: 'Plastic frame & back',
      waterResistance: 'IP54 splash resistant',
      colors: ['Blue Black', 'Light Blue', 'Gold'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'One UI 6.1',
      launchOS: 'Android 14',
      promisedMajorUpdates: 6,
      securityUpdatePolicy: '6 years of security patches',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.samsung.com/in/smartphones/galaxy-a16-5g/',
      productPage: 'https://www.samsung.com/in/smartphones/galaxy-a16-5g/buy/',
      specSheetUrl: 'https://www.samsung.com/in/smartphones/galaxy-a16-5g/specs/',
      verifiedDate: '2025-01',
    },
  },

  {
    id: 'samsung-galaxy-a06',
    slug: 'samsung-galaxy-a06',
    brand: 'Samsung',
    modelName: 'Galaxy A06',
    generation: 'A06',
    status: 'active',
    launchDate: '2024-09',
    pricing: {
      startingPrice: 8999,
      maximumPrice: 10999,
      launchPrice: 9999,
      currentPrice: 8999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Samsung India Official Store',
    },
    display: {
      displaySize: 6.7,
      displayType: 'PLS LCD',
      resolution: '1600 x 720 pixels (HD+)',
      refreshRate: 60,
      peakBrightness: 500,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '83.8%',
    },
    performance: {
      chipset: 'MediaTek Helio G85 (12nm)',
      cpu: 'Octa-core (2x2.0 GHz Cortex-A75 & 6x1.8 GHz Cortex-A55)',
      gpu: 'Mali-G52 MC2',
      ramOptions: ['4GB', '6GB'],
      storageOptions: ['64GB', '128GB'],
      storageType: 'eMMC 5.1',
      antutuScore: 265000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP)',
      mainCamera: '50 MP, f/1.8, AF',
      ultrawideCamera: 'None',
      telephotoCamera: 'None (2 MP Depth)',
      frontCamera: '8 MP, f/2.0',
      videoRecording: '1080p@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 25,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: false,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM + Dedicated microSD',
    },
    physical: {
      dimensions: '167.3 x 77.3 x 8.0 mm',
      weight: 189,
      materials: 'Plastic frame & back',
      waterResistance: 'None',
      colors: ['Black', 'Light Blue', 'Gold'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'One UI 6.1 Core',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '4 years of security patches',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.samsung.com/in/smartphones/galaxy-a06/',
      productPage: 'https://www.samsung.com/in/smartphones/galaxy-a06/buy/',
      specSheetUrl: 'https://www.samsung.com/in/smartphones/galaxy-a06/specs/',
      verifiedDate: '2025-01',
    },
  },

  {
    id: 'samsung-galaxy-m35-5g',
    slug: 'samsung-galaxy-m35-5g',
    brand: 'Samsung',
    modelName: 'Galaxy M35 5G',
    generation: 'M35',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 16999,
      maximumPrice: 20499,
      launchPrice: 19999,
      currentPrice: 16999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Samsung India Official Store',
    },
    display: {
      displaySize: 6.6,
      displayType: 'Super AMOLED',
      resolution: '2340 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1000,
      hdr: 'None',
      protection: 'Corning Gorilla Glass Victus+',
      screenToBodyRatio: '84.4%',
    },
    performance: {
      chipset: 'Samsung Exynos 1380 (5nm)',
      cpu: 'Octa-core (4x2.4 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G68 MP5',
      ramOptions: ['6GB', '8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 585000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 8MP + 2MP)',
      mainCamera: '50 MP, f/1.8, wide, PDAF, OIS',
      ultrawideCamera: '8 MP, f/2.2, 120˚',
      telephotoCamera: 'None (2 MP Macro)',
      frontCamera: '13 MP, f/2.2, 4K30',
      videoRecording: '4K@30fps, 1080p@30fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 6000,
      wiredCharging: 25,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '162.3 x 78.6 x 9.1 mm',
      weight: 222,
      materials: 'Plastic frame & patterned back, Gorilla Glass Victus+ front',
      waterResistance: 'None',
      colors: ['Moonlight Blue', 'Daybreak Blue', 'Thunder Grey'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'One UI 6.1',
      launchOS: 'Android 14',
      promisedMajorUpdates: 4,
      securityUpdatePolicy: '5 years of security patches',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.samsung.com/in/smartphones/galaxy-m35-5g/',
      productPage: 'https://www.samsung.com/in/smartphones/galaxy-m35-5g/buy/',
      specSheetUrl: 'https://www.samsung.com/in/smartphones/galaxy-m35-5g/specs/',
      verifiedDate: '2025-01',
    },
  },

  {
    id: 'samsung-galaxy-m15-5g',
    slug: 'samsung-galaxy-m15-5g',
    brand: 'Samsung',
    modelName: 'Galaxy M15 5G',
    generation: 'M15',
    status: 'active',
    launchDate: '2024-04',
    pricing: {
      startingPrice: 11999,
      maximumPrice: 14999,
      launchPrice: 13299,
      currentPrice: 11999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Samsung India Official Store',
    },
    display: {
      displaySize: 6.5,
      displayType: 'Super AMOLED',
      resolution: '2340 x 1080 pixels (FHD+)',
      refreshRate: 90,
      peakBrightness: 800,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '84.3%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6100+ (6nm)',
      cpu: 'Octa-core (2x2.2 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['4GB', '6GB', '8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 410000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 5MP + 2MP)',
      mainCamera: '50 MP, f/1.8, AF',
      ultrawideCamera: '5 MP, f/2.2',
      telephotoCamera: 'None (2 MP Macro)',
      frontCamera: '13 MP, f/2.0',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 6000,
      wiredCharging: 25,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '160.1 x 76.8 x 9.3 mm',
      weight: 217,
      materials: 'Plastic frame & back',
      waterResistance: 'None',
      colors: ['Blue Topaz', 'Celestial Blue', 'Stone Grey'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'One UI 6.1',
      launchOS: 'Android 14',
      promisedMajorUpdates: 4,
      securityUpdatePolicy: '5 years of security patches',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.samsung.com/in/smartphones/galaxy-m15-5g/',
      productPage: 'https://www.samsung.com/in/smartphones/galaxy-m15-5g/buy/',
      specSheetUrl: 'https://www.samsung.com/in/smartphones/galaxy-m15-5g/specs/',
      verifiedDate: '2025-01',
    },
  },

  {
    id: 'samsung-galaxy-m05',
    slug: 'samsung-galaxy-m05',
    brand: 'Samsung',
    modelName: 'Galaxy M05',
    generation: 'M05',
    status: 'active',
    launchDate: '2024-09',
    pricing: {
      startingPrice: 7499,
      maximumPrice: 7499,
      launchPrice: 7999,
      currentPrice: 7499,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Samsung India Official Store',
    },
    display: {
      displaySize: 6.7,
      displayType: 'PLS LCD',
      resolution: '1600 x 720 pixels (HD+)',
      refreshRate: 60,
      peakBrightness: 500,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '83.8%',
    },
    performance: {
      chipset: 'MediaTek Helio G85 (12nm)',
      cpu: 'Octa-core (2x2.0 GHz Cortex-A75 & 6x1.8 GHz Cortex-A55)',
      gpu: 'Mali-G52 MC2',
      ramOptions: ['4GB'],
      storageOptions: ['64GB'],
      storageType: 'eMMC 5.1',
      antutuScore: 260000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP)',
      mainCamera: '50 MP, f/1.8, AF',
      ultrawideCamera: 'None',
      telephotoCamera: 'None (2 MP Depth)',
      frontCamera: '8 MP, f/2.0',
      videoRecording: '1080p@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 25,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: false,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM + Dedicated microSD',
    },
    physical: {
      dimensions: '168.8 x 78.2 x 8.8 mm',
      weight: 195,
      materials: 'Plastic frame & back',
      waterResistance: 'None',
      colors: ['Mint Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'One UI 6.0 Core',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '4 years of security patches',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.samsung.com/in/smartphones/galaxy-m05/',
      productPage: 'https://www.samsung.com/in/smartphones/galaxy-m05/buy/',
      specSheetUrl: 'https://www.samsung.com/in/smartphones/galaxy-m05/specs/',
      verifiedDate: '2025-01',
    },
  },

  {
    id: 'samsung-galaxy-f55-5g',
    slug: 'samsung-galaxy-f55-5g',
    brand: 'Samsung',
    modelName: 'Galaxy F55 5G',
    generation: 'F55',
    status: 'active',
    launchDate: '2024-05',
    pricing: {
      startingPrice: 20999,
      maximumPrice: 24999,
      launchPrice: 26999,
      currentPrice: 20999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Samsung India Official Store',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Super AMOLED Plus',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1000,
      hdr: 'None',
      protection: 'Asahi Dragontrail Star 2',
      screenToBodyRatio: '86.4%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7 Gen 1 (4nm)',
      cpu: 'Octa-core (1x2.4 GHz Cortex-A710 & 3x2.36 GHz & 4x1.8 GHz)',
      gpu: 'Adreno 644',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 660000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 8MP + 2MP)',
      mainCamera: '50 MP, f/1.8, OIS',
      ultrawideCamera: '8 MP, f/2.2, 123˚',
      telephotoCamera: 'None (2 MP Macro)',
      frontCamera: '50 MP, f/2.4, 4K30',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 45,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '163.9 x 76.5 x 7.8 mm',
      weight: 180,
      materials: 'Vegan leather back with saddle-stitch design, plastic frame',
      waterResistance: 'None',
      colors: ['Apricot Crush', 'Raisin Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'One UI 6.1',
      launchOS: 'Android 14',
      promisedMajorUpdates: 4,
      securityUpdatePolicy: '5 years of security patches',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.samsung.com/in/smartphones/galaxy-f55-5g/',
      productPage: 'https://www.samsung.com/in/smartphones/galaxy-f55-5g/buy/',
      specSheetUrl: 'https://www.samsung.com/in/smartphones/galaxy-f55-5g/specs/',
      verifiedDate: '2025-01',
    },
  },
];

const variants: MobileVariant[] = [
  // S25 Ultra
  {
    id: 'samsung-galaxy-s25-ultra-12-256',
    modelId: 'samsung-galaxy-s25-ultra',
    ram: '12GB',
    storage: '256GB',
    price: 129999,
    mrp: 129999,
    colors: ['Titanium Silver Shadow', 'Titanium Black', 'Titanium Gray'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },
  {
    id: 'samsung-galaxy-s25-ultra-12-512',
    modelId: 'samsung-galaxy-s25-ultra',
    ram: '12GB',
    storage: '512GB',
    price: 141999,
    mrp: 141999,
    colors: ['Titanium Silver Shadow', 'Titanium Black', 'Titanium Gray', 'Titanium Blue'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },
  {
    id: 'samsung-galaxy-s25-ultra-12-1tb',
    modelId: 'samsung-galaxy-s25-ultra',
    ram: '12GB',
    storage: '1TB',
    price: 159999,
    mrp: 159999,
    colors: ['Titanium Black', 'Titanium Silver Shadow'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },

  // S25+
  {
    id: 'samsung-galaxy-s25-plus-12-256',
    modelId: 'samsung-galaxy-s25-plus',
    ram: '12GB',
    storage: '256GB',
    price: 99999,
    mrp: 99999,
    colors: ['Navy', 'Silver Shadow', 'Icy Blue'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },
  {
    id: 'samsung-galaxy-s25-plus-12-512',
    modelId: 'samsung-galaxy-s25-plus',
    ram: '12GB',
    storage: '512GB',
    price: 109999,
    mrp: 109999,
    colors: ['Navy', 'Silver Shadow'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },

  // S25
  {
    id: 'samsung-galaxy-s25-12-128',
    modelId: 'samsung-galaxy-s25',
    ram: '12GB',
    storage: '128GB',
    price: 79999,
    mrp: 79999,
    colors: ['Navy', 'Silver Shadow', 'Icy Blue', 'Mint'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },
  {
    id: 'samsung-galaxy-s25-12-256',
    modelId: 'samsung-galaxy-s25',
    ram: '12GB',
    storage: '256GB',
    price: 84999,
    mrp: 84999,
    colors: ['Navy', 'Silver Shadow', 'Icy Blue', 'Mint'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },

  // S24 Ultra
  {
    id: 'samsung-galaxy-s24-ultra-12-256',
    modelId: 'samsung-galaxy-s24-ultra',
    ram: '12GB',
    storage: '256GB',
    price: 109999,
    mrp: 129999,
    colors: ['Titanium Gray', 'Titanium Black', 'Titanium Violet'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },
  {
    id: 'samsung-galaxy-s24-ultra-12-512',
    modelId: 'samsung-galaxy-s24-ultra',
    ram: '12GB',
    storage: '512GB',
    price: 119999,
    mrp: 139999,
    colors: ['Titanium Gray', 'Titanium Black'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },

  // S24
  {
    id: 'samsung-galaxy-s24-8-128',
    modelId: 'samsung-galaxy-s24',
    ram: '8GB',
    storage: '128GB',
    price: 62999,
    mrp: 79999,
    colors: ['Onyx Black', 'Marble Gray', 'Cobalt Violet'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },
  {
    id: 'samsung-galaxy-s24-8-256',
    modelId: 'samsung-galaxy-s24',
    ram: '8GB',
    storage: '256GB',
    price: 67999,
    mrp: 84999,
    colors: ['Onyx Black', 'Marble Gray'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },

  // S24 FE
  {
    id: 'samsung-galaxy-s24-fe-8-128',
    modelId: 'samsung-galaxy-s24-fe',
    ram: '8GB',
    storage: '128GB',
    price: 54999,
    mrp: 59999,
    colors: ['Blue', 'Graphite', 'Mint'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },
  {
    id: 'samsung-galaxy-s24-fe-8-256',
    modelId: 'samsung-galaxy-s24-fe',
    ram: '8GB',
    storage: '256GB',
    price: 59999,
    mrp: 65999,
    colors: ['Blue', 'Graphite', 'Mint', 'Yellow'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },

  // S23
  {
    id: 'samsung-galaxy-s23-8-128',
    modelId: 'samsung-galaxy-s23',
    ram: '8GB',
    storage: '128GB',
    price: 42999,
    mrp: 74999,
    colors: ['Phantom Black', 'Cream', 'Green'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },
  {
    id: 'samsung-galaxy-s23-8-256',
    modelId: 'samsung-galaxy-s23',
    ram: '8GB',
    storage: '256GB',
    price: 47999,
    mrp: 79999,
    colors: ['Phantom Black', 'Cream'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },

  // Z Fold 6
  {
    id: 'samsung-galaxy-z-fold-6-12-256',
    modelId: 'samsung-galaxy-z-fold-6',
    ram: '12GB',
    storage: '256GB',
    price: 164999,
    mrp: 164999,
    colors: ['Silver Shadow', 'Navy', 'Pink'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },
  {
    id: 'samsung-galaxy-z-fold-6-12-512',
    modelId: 'samsung-galaxy-z-fold-6',
    ram: '12GB',
    storage: '512GB',
    price: 176999,
    mrp: 176999,
    colors: ['Silver Shadow', 'Navy'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },

  // Z Flip 6
  {
    id: 'samsung-galaxy-z-flip-6-12-256',
    modelId: 'samsung-galaxy-z-flip-6',
    ram: '12GB',
    storage: '256GB',
    price: 109999,
    mrp: 109999,
    colors: ['Silver Shadow', 'Blue', 'Mint', 'Yellow'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },
  {
    id: 'samsung-galaxy-z-flip-6-12-512',
    modelId: 'samsung-galaxy-z-flip-6',
    ram: '12GB',
    storage: '512GB',
    price: 121999,
    mrp: 121999,
    colors: ['Silver Shadow', 'Blue'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },

  // A55 5G
  {
    id: 'samsung-galaxy-a55-5g-8-128',
    modelId: 'samsung-galaxy-a55-5g',
    ram: '8GB',
    storage: '128GB',
    price: 36999,
    mrp: 39999,
    colors: ['Awesome Iceblue', 'Awesome Navy'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },
  {
    id: 'samsung-galaxy-a55-5g-8-256',
    modelId: 'samsung-galaxy-a55-5g',
    ram: '8GB',
    storage: '256GB',
    price: 39999,
    mrp: 42999,
    colors: ['Awesome Iceblue', 'Awesome Navy', 'Awesome Lilac'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },
  {
    id: 'samsung-galaxy-a55-5g-12-256',
    modelId: 'samsung-galaxy-a55-5g',
    ram: '12GB',
    storage: '256GB',
    price: 42999,
    mrp: 45999,
    colors: ['Awesome Navy', 'Awesome Iceblue'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },

  // A35 5G
  {
    id: 'samsung-galaxy-a35-5g-8-128',
    modelId: 'samsung-galaxy-a35-5g',
    ram: '8GB',
    storage: '128GB',
    price: 27999,
    mrp: 30999,
    colors: ['Awesome Iceblue', 'Awesome Navy'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },
  {
    id: 'samsung-galaxy-a35-5g-8-256',
    modelId: 'samsung-galaxy-a35-5g',
    ram: '8GB',
    storage: '256GB',
    price: 30999,
    mrp: 33999,
    colors: ['Awesome Iceblue', 'Awesome Navy'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },

  // A16 5G
  {
    id: 'samsung-galaxy-a16-5g-6-128',
    modelId: 'samsung-galaxy-a16-5g',
    ram: '6GB',
    storage: '128GB',
    price: 15499,
    mrp: 16999,
    colors: ['Blue Black', 'Light Blue', 'Gold'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },
  {
    id: 'samsung-galaxy-a16-5g-8-128',
    modelId: 'samsung-galaxy-a16-5g',
    ram: '8GB',
    storage: '128GB',
    price: 16999,
    mrp: 18499,
    colors: ['Blue Black', 'Light Blue'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },
  {
    id: 'samsung-galaxy-a16-5g-8-256',
    modelId: 'samsung-galaxy-a16-5g',
    ram: '8GB',
    storage: '256GB',
    price: 18999,
    mrp: 20499,
    colors: ['Blue Black', 'Gold'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },

  // A06
  {
    id: 'samsung-galaxy-a06-4-64',
    modelId: 'samsung-galaxy-a06',
    ram: '4GB',
    storage: '64GB',
    price: 8999,
    mrp: 9999,
    colors: ['Black', 'Light Blue', 'Gold'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },
  {
    id: 'samsung-galaxy-a06-4-128',
    modelId: 'samsung-galaxy-a06',
    ram: '4GB',
    storage: '128GB',
    price: 9999,
    mrp: 10999,
    colors: ['Black', 'Light Blue'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },

  // M35 5G
  {
    id: 'samsung-galaxy-m35-5g-6-128',
    modelId: 'samsung-galaxy-m35-5g',
    ram: '6GB',
    storage: '128GB',
    price: 16999,
    mrp: 19999,
    colors: ['Moonlight Blue', 'Daybreak Blue', 'Thunder Grey'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },
  {
    id: 'samsung-galaxy-m35-5g-8-128',
    modelId: 'samsung-galaxy-m35-5g',
    ram: '8GB',
    storage: '128GB',
    price: 18499,
    mrp: 21499,
    colors: ['Moonlight Blue', 'Daybreak Blue', 'Thunder Grey'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },
  {
    id: 'samsung-galaxy-m35-5g-8-256',
    modelId: 'samsung-galaxy-m35-5g',
    ram: '8GB',
    storage: '256GB',
    price: 20499,
    mrp: 23499,
    colors: ['Moonlight Blue', 'Thunder Grey'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },

  // M15 5G
  {
    id: 'samsung-galaxy-m15-5g-4-128',
    modelId: 'samsung-galaxy-m15-5g',
    ram: '4GB',
    storage: '128GB',
    price: 11999,
    mrp: 13299,
    colors: ['Blue Topaz', 'Celestial Blue', 'Stone Grey'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },
  {
    id: 'samsung-galaxy-m15-5g-6-128',
    modelId: 'samsung-galaxy-m15-5g',
    ram: '6GB',
    storage: '128GB',
    price: 13499,
    mrp: 14799,
    colors: ['Blue Topaz', 'Stone Grey'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },

  // M05
  {
    id: 'samsung-galaxy-m05-4-64',
    modelId: 'samsung-galaxy-m05',
    ram: '4GB',
    storage: '64GB',
    price: 7499,
    mrp: 7999,
    colors: ['Mint Green'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },

  // F55 5G
  {
    id: 'samsung-galaxy-f55-5g-8-128',
    modelId: 'samsung-galaxy-f55-5g',
    ram: '8GB',
    storage: '128GB',
    price: 20999,
    mrp: 26999,
    colors: ['Apricot Crush', 'Raisin Black'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },
  {
    id: 'samsung-galaxy-f55-5g-8-256',
    modelId: 'samsung-galaxy-f55-5g',
    ram: '8GB',
    storage: '256GB',
    price: 22999,
    mrp: 28999,
    colors: ['Apricot Crush', 'Raisin Black'],
    status: 'active',
    verified: true,
    source: 'Samsung India Official Store',
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    "modelId": "samsung-galaxy-s25-ultra",
    "modelName": "Galaxy S25 Ultra",
    "brand": "Samsung",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s25-ultra-sm-s938-1.jpg",
        "angle": "front",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy S25 Ultra front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s25-ultra-sm-s938-2.jpg",
        "angle": "back",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy S25 Ultra titanium back with quad camera"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s25-ultra-sm-s938-3.jpg",
        "angle": "side",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy S25 Ultra titanium frame profile"
      }
    ]
  },
  {
    "modelId": "samsung-galaxy-s25-plus",
    "modelName": "Galaxy S25+",
    "brand": "Samsung",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s25-plus-sm-s936-1.jpg",
        "angle": "front",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy S25+ front view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s25-plus-sm-s936-2.jpg",
        "angle": "back",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy S25+ rear triple camera view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s25-plus-sm-s936-3.jpg",
        "angle": "side",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy S25+ aluminum profile"
      }
    ]
  },
  {
    "modelId": "samsung-galaxy-s25",
    "modelName": "Galaxy S25",
    "brand": "Samsung",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s25-sm-s931-1.jpg",
        "angle": "front",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy S25 front view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s25-sm-s931-2.jpg",
        "angle": "back",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy S25 rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s25-sm-s931-3.jpg",
        "angle": "side",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy S25 profile"
      }
    ]
  },
  {
    "modelId": "samsung-galaxy-s24-ultra",
    "modelName": "Galaxy S24 Ultra",
    "brand": "Samsung",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s24-ultra-5g-sm-s928-0.jpg",
        "angle": "front",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy S24 Ultra front view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s24-ultra-5g-sm-s928-1.jpg",
        "angle": "back",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy S24 Ultra rear quad camera view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s24-ultra-5g-sm-s928-2.jpg",
        "angle": "side",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy S24 Ultra titanium profile"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s24-ultra-5g-sm-s928-3.jpg",
        "angle": "display",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy S24 Ultra display angle"
      }
    ]
  },
  {
    "modelId": "samsung-galaxy-s24",
    "modelName": "Galaxy S24",
    "brand": "Samsung",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s24-5g-sm-s921-1.jpg",
        "angle": "front",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy S24 front view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s24-5g-sm-s921-2.jpg",
        "angle": "back",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy S24 rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s24-plus-5g-sm-s926-3.jpg",
        "angle": "side",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy S24 profile"
      }
    ]
  },
  {
    "modelId": "samsung-galaxy-s24-fe",
    "modelName": "Galaxy S24 FE",
    "brand": "Samsung",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s24-fe-1.jpg",
        "angle": "front",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy S24 FE front view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s24-fe-2.jpg",
        "angle": "back",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy S24 FE rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s24-fe-3.jpg",
        "angle": "side",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy S24 FE profile"
      }
    ]
  },
  {
    "modelId": "samsung-galaxy-s23",
    "modelName": "Galaxy S23",
    "brand": "Samsung",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s23-5g-1.jpg",
        "angle": "front",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy S23 front view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s23-5g-2.jpg",
        "angle": "back",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy S23 rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s23-5g-3.jpg",
        "angle": "side",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy S23 profile"
      }
    ]
  },
  {
    "modelId": "samsung-galaxy-z-fold-6",
    "modelName": "Galaxy Z Fold 6",
    "brand": "Samsung",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-z-fold6-1.jpg",
        "angle": "front",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy Z Fold 6 unfolded front display"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-z-fold6-2.jpg",
        "angle": "back",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy Z Fold 6 rear cover and camera"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-z-fold6-3.jpg",
        "angle": "side",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy Z Fold 6 hinge profile"
      }
    ]
  },
  {
    "modelId": "samsung-galaxy-z-flip-6",
    "modelName": "Galaxy Z Flip 6",
    "brand": "Samsung",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-z-flip6-1.jpg",
        "angle": "front",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy Z Flip 6 unfolded front display"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-z-flip6-2.jpg",
        "angle": "back",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy Z Flip 6 flex window and rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-z-flip6-3.jpg",
        "angle": "side",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy Z Flip 6 side profile"
      }
    ]
  },
  {
    "modelId": "samsung-galaxy-a55-5g",
    "modelName": "Galaxy A55 5G",
    "brand": "Samsung",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-a55-1.jpg",
        "angle": "front",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy A55 5G front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-a55-2.jpg",
        "angle": "back",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy A55 5G rear glass back"
      }
    ]
  },
  {
    "modelId": "samsung-galaxy-a35-5g",
    "modelName": "Galaxy A35 5G",
    "brand": "Samsung",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-a35-1.jpg",
        "angle": "front",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy A35 5G front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-a35-2.jpg",
        "angle": "back",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy A35 5G rear view"
      }
    ]
  },
  {
    "modelId": "samsung-galaxy-a16-5g",
    "modelName": "Galaxy A16 5G",
    "brand": "Samsung",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-a16-5g-1.jpg",
        "angle": "front",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy A16 5G front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a16-5g.jpg",
        "angle": "back",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy A16 5G rear view"
      }
    ]
  },
  {
    "modelId": "samsung-galaxy-a06",
    "modelName": "Galaxy A06",
    "brand": "Samsung",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a06-1.jpg",
        "angle": "front",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy A06 front and rear official view"
      }
    ]
  },
  {
    "modelId": "samsung-galaxy-m35-5g",
    "modelName": "Galaxy M35 5G",
    "brand": "Samsung",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-m35-1.jpg",
        "angle": "front",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy M35 5G front view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-m35-2.jpg",
        "angle": "back",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy M35 5G rear view"
      }
    ]
  },
  {
    "modelId": "samsung-galaxy-m15-5g",
    "modelName": "Galaxy M15 5G",
    "brand": "Samsung",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-m15-1.jpg",
        "angle": "front",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy M15 5G front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-m15-2.jpg",
        "angle": "back",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy M15 5G rear view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-m15-3.jpg",
        "angle": "side",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy M15 5G profile"
      }
    ]
  },
  {
    "modelId": "samsung-galaxy-m05",
    "modelName": "Galaxy M05",
    "brand": "Samsung",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-m05-1.jpg",
        "angle": "front",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy M05 front view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m05.jpg",
        "angle": "back",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy M05 rear view"
      }
    ]
  },
  {
    "modelId": "samsung-galaxy-f55-5g",
    "modelName": "Galaxy F55 5G",
    "brand": "Samsung",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-f55-1.jpg",
        "angle": "front",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy F55 5G front display view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-f55-2.jpg",
        "angle": "back",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy F55 5G vegan leather back view"
      },
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f55.jpg",
        "angle": "display",
        "source": "Samsung Official (GSMArena CDN)",
        "verified": true,
        "alt": "Samsung Galaxy F55 5G overview angle"
      }
    ]
  }
];

export const samsungBundle: MobileBrandBundle = {
  models,
  variants,
  images,
};
