import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  // ── PHANTOM SERIES (Foldable & Flagship) ──
  {
    id: 'tecno-phantom-v-fold',
    slug: 'tecno-phantom-v-fold',
    brand: 'Tecno',
    modelName: 'Tecno Phantom V Fold',
    generation: 'Phantom V',
    status: 'discontinued',
    launchDate: '2023-04',
    pricing: {
      startingPrice: 69999,
      maximumPrice: 79999,
      launchPrice: 79999,
      currentPrice: 69999,
      currency: 'INR',
      priceEffectiveDate: '2024-03',
      source: 'Tecno India Store Archive',
    },
    display: {
      displaySize: 7.85,
      displayType: 'Foldable 120Hz LTPO AMOLED, 1100 nits + 6.42" 120Hz LTPO AMOLED Sub-Display',
      resolution: '2296 x 2000 pixels (Main) / 2550 x 1080 pixels (Cover)',
      refreshRate: 120,
      peakBrightness: 1100,
      hdr: 'None',
      protection: 'Corning Gorilla Glass Victus (Cover)',
      screenToBodyRatio: '90.1%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 9000+ (4nm)',
      cpu: 'Octa-core (1x3.20 GHz Cortex-X2 & 3x2.85 GHz Cortex-A710 & 4x1.80 GHz Cortex-A510)',
      gpu: 'Mali-G710 MC10',
      ramOptions: ['12GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 3.1',
      antutuScore: 1080000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP 2x Telephoto + 13MP Ultrawide)',
      mainCamera: '50 MP, f/1.8, 1/1.3", PDAF',
      ultrawideCamera: '13 MP, f/2.2, 120˚',
      telephotoCamera: '50 MP, f/2.0, 1/2.8", 2x optical zoom, PDAF',
      frontCamera: '16 MP (Cover) + 32 MP (Inner Display)',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 66,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '159.4 x 140.4 x 6.9 mm (unfolded) / 159.4 x 72 x 14.2 mm (folded)',
      weight: 299,
      materials: 'Recycled fiber leather back, aerospace-grade alloy hinge',
      waterResistance: 'None',
      colors: ['Black', 'White'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'HiOS 13 Fold',
      launchOS: 'Android 13',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Hi-Res Audio certification',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.tecno-mobile.in/phantom-v-fold/',
      productPage: 'https://www.amazon.in/dp/B0BY2CQM44',
      specSheetUrl: 'https://www.tecno-mobile.in/phantom-v-fold/',
      verifiedDate: '2023-04',
    },
  },
  {
    id: 'tecno-phantom-v-flip-5g',
    slug: 'tecno-phantom-v-flip-5g',
    brand: 'Tecno',
    modelName: 'Tecno Phantom V Flip 5G',
    generation: 'Phantom V Flip',
    status: 'discontinued',
    launchDate: '2023-10',
    pricing: {
      startingPrice: 49999,
      maximumPrice: 54999,
      launchPrice: 54999,
      currentPrice: 49999,
      currency: 'INR',
      priceEffectiveDate: '2024-04',
      source: 'Tecno India Store Archive',
    },
    display: {
      displaySize: 6.9,
      displayType: 'Foldable 120Hz LTPO AMOLED, 1000 nits + 1.32" Circular AMOLED Cover Screen',
      resolution: '2640 x 1080 pixels (Main) / 466 x 466 pixels (Cover)',
      refreshRate: 120,
      peakBrightness: 1000,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '85.2%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 8050 (6nm)',
      cpu: 'Octa-core (1x3.0 GHz Cortex-A78 & 3x2.6 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G77 MC9',
      ramOptions: ['8GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 740000,
    },
    cameras: {
      rearCameraSetup: 'Dual (64MP RGBW + 13MP Ultrawide)',
      mainCamera: '64 MP, f/1.7, 1/1.73", 0.8µm, PDAF',
      ultrawideCamera: '13 MP, f/2.2, 120˚, PDAF',
      telephotoCamera: 'None',
      frontCamera: '32 MP, f/2.5, Dual-microflash LED',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 4000,
      wiredCharging: 45,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.1',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '171.7 x 74.1 x 7 mm (unfolded) / 88.8 x 74.1 x 15 mm (folded)',
      weight: 194,
      materials: 'Eco leather back, planet-inspired circular outer screen, steel hinge',
      waterResistance: 'None',
      colors: ['Mystic Dawn', 'Iconic Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'HiOS 13.5 Flip',
      launchOS: 'Android 13',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.tecno-mobile.in/phantom-v-flip/',
      productPage: 'https://www.amazon.in/dp/B0CHYRPZ2K',
      specSheetUrl: 'https://www.tecno-mobile.in/phantom-v-flip/',
      verifiedDate: '2023-10',
    },
  },

  // ── CAMON SERIES (Professional Camera Imaging) ──
  {
    id: 'tecno-camon-30-premier-5g',
    slug: 'tecno-camon-30-premier-5g',
    brand: 'Tecno',
    modelName: 'Tecno Camon 30 Premier 5G',
    generation: 'Camon 30',
    status: 'active',
    launchDate: '2024-05',
    pricing: {
      startingPrice: 39999,
      maximumPrice: 39999,
      launchPrice: 39999,
      currentPrice: 39999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Tecno India / Amazon Store',
    },
    display: {
      displaySize: 6.77,
      displayType: '1.5K 120Hz LTPO AMOLED, 1400 nits peak',
      resolution: '2780 x 1264 pixels',
      refreshRate: 120,
      peakBrightness: 1400,
      hdr: 'None',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '90.5%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 8200 Ultimate (4nm) with Sony CXD5622GG Imaging ISP (PolarAce)',
      cpu: 'Octa-core (1x3.1 GHz Cortex-A78 & 3x3.0 GHz & 4x2.0 GHz)',
      gpu: 'Mali-G610 MC6',
      ramOptions: ['12GB'],
      storageOptions: ['512GB'],
      storageType: 'UFS 3.1',
      antutuScore: 970000,
    },
    cameras: {
      rearCameraSetup: 'Triple 50MP (50MP Sony IMX890 OIS + 50MP 3x Periscope OIS + 50MP Ultrawide)',
      mainCamera: '50 MP Sony IMX890, f/1.88, 1/1.56", OIS, PDAF',
      ultrawideCamera: '50 MP, f/2.2, 114˚, AF, macro',
      telephotoCamera: '50 MP periscope, f/2.2, 3x optical zoom, 60x hybrid, OIS',
      frontCamera: '50 MP, f/2.45, Eye-tracking AF, 4K@60fps',
      videoRecording: '4K@60fps PolarAce HDR video, 4K Ultra Night Vision',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 70,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.66 x 76.23 x 7.9 mm',
      weight: 202,
      materials: 'Action Dot breathing light, suede/leatherette tech-art back, aluminum frame',
      waterResistance: 'IP54 splash resistant',
      colors: ['Alps Snowy Silver', 'Hawaii Lava Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'HiOS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers tuned by Dolby Atmos',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'In-display optical',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.tecno-mobile.in/camon-30-premier-5g/',
      productPage: 'https://www.amazon.in/dp/B0D3DW91M6',
      specSheetUrl: 'https://www.tecno-mobile.in/camon-30-premier-5g/',
      verifiedDate: '2024-05',
    },
  },
  {
    id: 'tecno-camon-30-5g',
    slug: 'tecno-camon-30-5g',
    brand: 'Tecno',
    modelName: 'Tecno Camon 30 5G',
    generation: 'Camon 30',
    status: 'active',
    launchDate: '2024-05',
    pricing: {
      startingPrice: 22999,
      maximumPrice: 26999,
      launchPrice: 22999,
      currentPrice: 22999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Tecno India / Amazon Store',
    },
    display: {
      displaySize: 6.78,
      displayType: '120Hz FHD+ AMOLED, 1300 nits peak',
      resolution: '2436 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 1300,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '89.5%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7020 (6nm)',
      cpu: 'Octa-core (2x2.2 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)',
      gpu: 'IMG BXM-8-256',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 480000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP OIS + 2MP Depth + Light sensor)',
      mainCamera: '50 MP, f/1.9, 1/1.56", 1.0µm, PDAF, OIS',
      ultrawideCamera: 'None',
      telephotoCamera: 'None',
      frontCamera: '50 MP, f/2.45, Eye-tracking AF',
      videoRecording: '1440p@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 70,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5 (ac)',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '165.37 x 75.93 x 7.83 mm',
      weight: 199,
      materials: 'Classic camera design, vegan leather or glass back',
      waterResistance: 'IP53 splash resistant',
      colors: ['Iceland Basalt Dark', 'Uyuni Salt White', 'Emerald Lake Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'HiOS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers tuned by Dolby Atmos',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'In-display optical',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.tecno-mobile.in/camon-30-5g/',
      productPage: 'https://www.amazon.in/dp/B0D3DZ479H',
      specSheetUrl: 'https://www.tecno-mobile.in/camon-30-5g/',
      verifiedDate: '2024-05',
    },
  },

  // ── POVA SERIES (Performance & Battery) ──
  {
    id: 'tecno-pova-6-pro-5g',
    slug: 'tecno-pova-6-pro-5g',
    brand: 'Tecno',
    modelName: 'Tecno Pova 6 Pro 5G',
    generation: 'Pova 6',
    status: 'active',
    launchDate: '2024-04',
    pricing: {
      startingPrice: 19999,
      maximumPrice: 21999,
      launchPrice: 19999,
      currentPrice: 19999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Tecno India / Amazon Store',
    },
    display: {
      displaySize: 6.78,
      displayType: '120Hz FHD+ AMOLED, 1300 nits peak',
      resolution: '2436 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 1300,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '87.2%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6080 (6nm)',
      cpu: 'Octa-core (2x2.4 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 430000,
    },
    cameras: {
      rearCameraSetup: 'Triple (108MP + 2MP Depth + 0.08MP Light sensor)',
      mainCamera: '108 MP, f/1.89, 1/1.52", PDAF, 3x in-sensor zoom',
      ultrawideCamera: 'None',
      telephotoCamera: 'None',
      frontCamera: '32 MP, f/2.2, dual-color LED flash',
      videoRecording: '1440p@30fps, 1080p@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 6000,
      wiredCharging: 70,
      wirelessCharging: 0,
      reverseCharging: 10,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5 (ac)',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '165.5 x 76.1 x 7.88 mm',
      weight: 198.3,
      materials: 'Dynamic-Light Mini-LED cyber back (210 LEDs), plastic frame',
      waterResistance: 'IP53 splash resistant',
      colors: ['Meteorite Grey', 'Comet Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'HiOS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Dual stereo speakers tuned by Dolby Atmos, Hi-Res certified',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'In-display optical',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.tecno-mobile.in/pova-6-pro-5g/',
      productPage: 'https://www.amazon.in/dp/B0CX24T727',
      specSheetUrl: 'https://www.tecno-mobile.in/pova-6-pro-5g/',
      verifiedDate: '2024-04',
    },
  },
  {
    id: 'tecno-pova-5-pro',
    slug: 'tecno-pova-5-pro',
    brand: 'Tecno',
    modelName: 'Tecno Pova 5 Pro 5G',
    generation: 'Pova 5',
    status: 'discontinued',
    launchDate: '2023-08',
    pricing: {
      startingPrice: 14999,
      maximumPrice: 15999,
      launchPrice: 15999,
      currentPrice: 14999,
      currency: 'INR',
      priceEffectiveDate: '2024-03',
      source: 'Tecno India Store Archive',
    },
    display: {
      displaySize: 6.78,
      displayType: '120Hz FHD+ IPS LCD, 580 nits',
      resolution: '2460 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 580,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '84.8%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6080 (6nm)',
      cpu: 'Octa-core (2x2.4 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 410000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 0.08MP Depth)',
      mainCamera: '50 MP, f/1.6, PDAF',
      ultrawideCamera: 'None',
      telephotoCamera: 'None',
      frontCamera: '16 MP, f/2.0',
      videoRecording: '1440p@30fps, 1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 68,
      wirelessCharging: 0,
      reverseCharging: 10,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5 (ac)',
      bluetooth: 'Bluetooth 5.1',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dedicated Dual SIM + microSD',
    },
    physical: {
      dimensions: '168.5 x 76.5 x 9 mm',
      weight: 212,
      materials: 'Arc Interface 3D interactive LED backlight strip, mecha design',
      waterResistance: 'None',
      colors: ['Silver Fantasy', 'Dark Illusion'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'HiOS 13',
      launchOS: 'Android 13',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Hi-Res Audio and DTS sound',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.tecno-mobile.in/pova-5-pro-5g/',
      productPage: 'https://www.amazon.in/dp/B0CD7FL7V6',
      specSheetUrl: 'https://www.tecno-mobile.in/pova-5-pro-5g/',
      verifiedDate: '2023-08',
    },
  },

  // ── SPARK SERIES (Style & Budget) ──
  {
    id: 'tecno-spark-20-pro-plus',
    slug: 'tecno-spark-20-pro-plus',
    brand: 'Tecno',
    modelName: 'Tecno Spark 20 Pro Plus',
    generation: 'Spark 20',
    status: 'active',
    launchDate: '2024-02',
    pricing: {
      startingPrice: 15999,
      maximumPrice: 16999,
      launchPrice: 15999,
      currentPrice: 15999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Tecno India / Amazon Store',
    },
    display: {
      displaySize: 6.78,
      displayType: '120Hz 3D Curved AMOLED, 1000 nits peak',
      resolution: '2436 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 1000,
      hdr: 'None',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '89.0%',
    },
    performance: {
      chipset: 'MediaTek Helio G99 Ultimate (6nm)',
      cpu: 'Octa-core (2x2.2 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['8GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 425000,
    },
    cameras: {
      rearCameraSetup: 'Dual (108MP + 0.08MP Auxiliary)',
      mainCamera: '108 MP, f/1.75, 1/1.67", 3x in-sensor zoom, PDAF',
      ultrawideCamera: 'None',
      telephotoCamera: 'None',
      frontCamera: '32 MP, f/2.2, dual LED flash',
      videoRecording: '1440p@30fps, 1080p@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 33,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: false,
      has4G: true,
      wifi: 'Wi-Fi 5 (ac)',
      bluetooth: 'Bluetooth 5.2',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '164.65 x 75.04 x 7.55 mm',
      weight: 179,
      materials: 'Ultra-slim 3D double curved design, Magic Skin 2.0 eco leather',
      waterResistance: 'IP53 splash resistant',
      colors: ['Temporal Orbits', 'Lunar Frost', 'Radiant Starstream', 'Magic Skin 2.0 Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'HiOS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Dual stereo speakers tuned by DTS sound',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'In-display optical',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.tecno-mobile.in/spark-20-pro-plus/',
      productPage: 'https://www.amazon.in/dp/B0CSK2C3F6',
      specSheetUrl: 'https://www.tecno-mobile.in/spark-20-pro-plus/',
      verifiedDate: '2024-02',
    },
  },

  // ── POP SERIES (Entry-Level) ──
  {
    id: 'tecno-pop-8',
    slug: 'tecno-pop-8',
    brand: 'Tecno',
    modelName: 'Tecno Pop 8',
    generation: 'Pop 8',
    status: 'active',
    launchDate: '2024-01',
    pricing: {
      startingPrice: 5999,
      maximumPrice: 6999,
      launchPrice: 6599,
      currentPrice: 5999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Tecno India / Amazon Store',
    },
    display: {
      displaySize: 6.56,
      displayType: '90Hz HD+ IPS LCD, Dynamic Port notch',
      resolution: '1612 x 720 pixels',
      refreshRate: 90,
      peakBrightness: 480,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '84.6%',
    },
    performance: {
      chipset: 'Unisoc T606 (12nm)',
      cpu: 'Octa-core (2x1.6 GHz Cortex-A75 & 6x1.6 GHz Cortex-A55)',
      gpu: 'Mali-G57 MP1',
      ramOptions: ['4GB', '8GB'],
      storageOptions: ['64GB'],
      storageType: 'UFS 2.2',
      antutuScore: 240000,
    },
    cameras: {
      rearCameraSetup: 'Dual (12MP + AI Lens)',
      mainCamera: '12 MP, f/1.8, Dual-LED flash, PDAF',
      ultrawideCamera: 'None',
      telephotoCamera: 'None',
      frontCamera: '8 MP, Dual-LED flash',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 10,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: false,
      has4G: true,
      wifi: 'Wi-Fi 5 (ac)',
      bluetooth: 'Bluetooth 5.0',
      nfc: false,
      usb: 'USB Type-C',
      simConfig: 'Dedicated Dual SIM + microSD',
    },
    physical: {
      dimensions: '163.7 x 75.6 x 8.6 mm',
      weight: 185,
      materials: 'Plastic body, flat frame',
      waterResistance: 'None',
      colors: ['Mystery White', 'Alpenglow Gold', 'Gravity Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'HiOS 13 (Android 13 Go edition)',
      launchOS: 'Android 13 (Go edition)',
      promisedMajorUpdates: 1,
      securityUpdatePolicy: '2 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with DTS 400% Ultra Volume',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.tecno-mobile.in/pop-8/',
      productPage: 'https://www.amazon.in/dp/B0CQ7W64G4',
      specSheetUrl: 'https://www.tecno-mobile.in/pop-8/',
      verifiedDate: '2024-01',
    },
  },
];

const variants: MobileVariant[] = [
  // Phantom V Fold
  {
    id: 'tecno-phantom-v-fold-12-256',
    modelId: 'tecno-phantom-v-fold',
    name: 'Tecno Phantom V Fold (12GB RAM, 256GB)',
    ram: '12GB',
    storage: '256GB',
    color: 'Black',
    price: 69999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  // Phantom V Flip
  {
    id: 'tecno-phantom-v-flip-5g-8-256',
    modelId: 'tecno-phantom-v-flip-5g',
    name: 'Tecno Phantom V Flip 5G (8GB RAM, 256GB)',
    ram: '8GB',
    storage: '256GB',
    color: 'Mystic Dawn',
    price: 49999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  // Camon 30 Premier
  {
    id: 'tecno-camon-30-premier-5g-12-512',
    modelId: 'tecno-camon-30-premier-5g',
    name: 'Tecno Camon 30 Premier 5G (12GB RAM, 512GB)',
    ram: '12GB',
    storage: '512GB',
    color: 'Alps Snowy Silver',
    price: 39999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Camon 30 5G
  {
    id: 'tecno-camon-30-5g-8-256',
    modelId: 'tecno-camon-30-5g',
    name: 'Tecno Camon 30 5G (8GB RAM, 256GB)',
    ram: '8GB',
    storage: '256GB',
    color: 'Iceland Basalt Dark',
    price: 22999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Pova 6 Pro
  {
    id: 'tecno-pova-6-pro-5g-8-256',
    modelId: 'tecno-pova-6-pro-5g',
    name: 'Tecno Pova 6 Pro 5G (8GB RAM, 256GB)',
    ram: '8GB',
    storage: '256GB',
    color: 'Meteorite Grey',
    price: 19999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  {
    id: 'tecno-pova-6-pro-5g-12-256',
    modelId: 'tecno-pova-6-pro-5g',
    name: 'Tecno Pova 6 Pro 5G (12GB RAM, 256GB)',
    ram: '12GB',
    storage: '256GB',
    color: 'Comet Green',
    price: 21999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Pova 5 Pro
  {
    id: 'tecno-pova-5-pro-8-128',
    modelId: 'tecno-pova-5-pro',
    name: 'Tecno Pova 5 Pro 5G (8GB RAM, 128GB)',
    ram: '8GB',
    storage: '128GB',
    color: 'Silver Fantasy',
    price: 14999,
    currency: 'INR',
    status: 'discontinued',
    verified: true,
  },
  // Spark 20 Pro Plus
  {
    id: 'tecno-spark-20-pro-plus-8-256',
    modelId: 'tecno-spark-20-pro-plus',
    name: 'Tecno Spark 20 Pro Plus (8GB RAM, 256GB)',
    ram: '8GB',
    storage: '256GB',
    color: 'Temporal Orbits',
    price: 15999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
  // Pop 8
  {
    id: 'tecno-pop-8-4-64',
    modelId: 'tecno-pop-8',
    name: 'Tecno Pop 8 (4GB RAM, 64GB)',
    ram: '4GB',
    storage: '64GB',
    color: 'Gravity Black',
    price: 5999,
    currency: 'INR',
    status: 'active',
    verified: true,
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    modelId: 'tecno-phantom-v-fold',
    modelName: 'Tecno Phantom V Fold',
    brand: 'Tecno',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/tecno-phantom-v-fold.jpg',
        angle: 'front',
        source: 'Tecno Official (GSMArena CDN)',
        sourceUrl: 'https://www.tecno-mobile.in/phantom-v-fold/',
        verified: true,
        alt: 'Tecno Phantom V Fold front foldable view',
      },
    ],
  },
  {
    modelId: 'tecno-phantom-v-flip-5g',
    modelName: 'Tecno Phantom V Flip 5G',
    brand: 'Tecno',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/tecno-phantom-v-flip-5g.jpg',
        angle: 'front',
        source: 'Tecno Official (GSMArena CDN)',
        sourceUrl: 'https://www.tecno-mobile.in/phantom-v-flip/',
        verified: true,
        alt: 'Tecno Phantom V Flip 5G front flip view',
      },
    ],
  },
  {
    modelId: 'tecno-camon-30-premier-5g',
    modelName: 'Tecno Camon 30 Premier 5G',
    brand: 'Tecno',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/tecno-camon-30-pro.jpg',
        angle: 'front',
        source: 'Tecno Official (GSMArena CDN)',
        sourceUrl: 'https://www.tecno-mobile.in/camon-30-premier-5g/',
        verified: true,
        alt: 'Tecno Camon 30 Premier 5G front 1.5K LTPO display',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/tecno/tecno-camon-30-pro-1.jpg',
        angle: 'back',
        source: 'Tecno Official (GSMArena CDN)',
        sourceUrl: 'https://www.tecno-mobile.in/camon-30-premier-5g/',
        verified: true,
        alt: 'Tecno Camon 30 Premier 5G vintage camera rangefinder rear view',
      },
    ],
  },
  {
    modelId: 'tecno-camon-30-5g',
    modelName: 'Tecno Camon 30 5G',
    brand: 'Tecno',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/tecno-camon-30-5g.jpg',
        angle: 'front',
        source: 'Tecno Official (GSMArena CDN)',
        sourceUrl: 'https://www.tecno-mobile.in/camon-30-5g/',
        verified: true,
        alt: 'Tecno Camon 30 5G front display view',
      },
    ],
  },
  {
    modelId: 'tecno-pova-6-pro-5g',
    modelName: 'Tecno Pova 6 Pro 5G',
    brand: 'Tecno',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/tecno/tecno-pova-6-pro-02.jpg',
        angle: 'front',
        source: 'Tecno Official (GSMArena CDN)',
        sourceUrl: 'https://www.tecno-mobile.in/pova-6-pro-5g/',
        verified: true,
        alt: 'Tecno Pova 6 Pro 5G front display view',
      },
      {
        url: 'https://fdn2.gsmarena.com/vv/pics/tecno/tecno-pova-6-pro-02.jpg',
        angle: 'back',
        source: 'Tecno Official (GSMArena CDN)',
        sourceUrl: 'https://www.tecno-mobile.in/pova-6-pro-5g/',
        verified: true,
        alt: 'Tecno Pova 6 Pro 5G Dynamic-Light cyber back view',
      },
    ],
  },
  {
    modelId: 'tecno-pova-5-pro',
    modelName: 'Tecno Pova 5 Pro 5G',
    brand: 'Tecno',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/tecno-pova-5-pro.jpg',
        angle: 'front',
        source: 'Tecno Official (GSMArena CDN)',
        sourceUrl: 'https://www.tecno-mobile.in/pova-5-pro-5g/',
        verified: true,
        alt: 'Tecno Pova 5 Pro front display view',
      },
    ],
  },
  {
    modelId: 'tecno-spark-20-pro-plus',
    modelName: 'Tecno Spark 20 Pro Plus',
    brand: 'Tecno',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/tecno-spark-20-pro-plus.jpg',
        angle: 'front',
        source: 'Tecno Official (GSMArena CDN)',
        sourceUrl: 'https://www.tecno-mobile.in/spark-20-pro-plus/',
        verified: true,
        alt: 'Tecno Spark 20 Pro Plus front curved AMOLED view',
      },
    ],
  },
  {
    modelId: 'tecno-pop-8',
    modelName: 'Tecno Pop 8',
    brand: 'Tecno',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/tecno-pop8.jpg',
        angle: 'front',
        source: 'Tecno Official (GSMArena CDN)',
        sourceUrl: 'https://www.tecno-mobile.in/pop-8/',
        verified: true,
        alt: 'Tecno Pop 8 front display view',
      },
    ],
  },
];

export const tecnoBundle: MobileBrandBundle = {
  brand: 'Tecno',
  models,
  variants,
  images,
};
