import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  // ── VIVO X SERIES (Zeiss Co-Engineered Flagships) ──
  {
    id: 'vivo-x200-pro',
    slug: 'vivo-x200-pro',
    brand: 'Vivo',
    modelName: 'Vivo X200 Pro',
    generation: 'X200',
    status: 'active',
    launchDate: '2024-12',
    pricing: {
      startingPrice: 94999,
      maximumPrice: 94999,
      launchPrice: 94999,
      currentPrice: 94999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Vivo India Official Store',
    },
    display: {
      displaySize: 6.78,
      displayType: 'LTPO AMOLED, 1B colors, 120Hz, Dolby Vision, HDR10+',
      resolution: '2800 x 1260 pixels (1.5K)',
      refreshRate: 120,
      peakBrightness: 4500,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Armor Glass',
      screenToBodyRatio: '90.2%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 9400 (3nm)',
      cpu: 'Octa-core (1x3.63 GHz Cortex-X925 & 3x3.3 GHz Cortex-X4 & 4x2.4 GHz Cortex-A720)',
      gpu: 'Immortalis-G925',
      ramOptions: ['16GB'],
      storageOptions: ['512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 2880000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 200MP + 50MP) Zeiss T* Coating',
      mainCamera: '50 MP Sony LYT-818, 1/1.28", f/1.57, VCS 3.0, OIS',
      ultrawideCamera: '50 MP Samsung JN1, f/2.0, 119˚, AF',
      telephotoCamera: '200 MP Zeiss APO periscope telephoto, 3.7x optical, 85mm, OIS, macro',
      frontCamera: '32 MP, f/2.0',
      videoRecording: '4K@120fps, 8K@30fps, 10-bit Log',
      ois: true,
    },
    battery: {
      batteryCapacity: 6000,
      wiredCharging: 90,
      wirelessCharging: 30,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 3.2 Gen 1',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.36 x 75.95 x 8.2 mm',
      weight: 223,
      materials: 'Armor Glass front, aluminum frame, frosted glass back',
      waterResistance: 'IP68/IP69',
      colors: ['Titanium Grey', 'Carbon Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 15',
      launchOS: 'Android 15',
      promisedMajorUpdates: 4,
      securityUpdatePolicy: '5 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: '3D Ultrasonic under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.vivo.com/in/products/x200pro',
      productPage: 'https://shop.vivo.com/in/product/10332',
      specSheetUrl: 'https://www.vivo.com/in/products/param/x200pro',
      verifiedDate: '2024-12',
    },
  },

  {
    id: 'vivo-x200',
    slug: 'vivo-x200',
    brand: 'Vivo',
    modelName: 'Vivo X200',
    generation: 'X200',
    status: 'active',
    launchDate: '2024-12',
    pricing: {
      startingPrice: 65999,
      maximumPrice: 71999,
      launchPrice: 65999,
      currentPrice: 65999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Vivo India Official Store',
    },
    display: {
      displaySize: 6.67,
      displayType: 'AMOLED, 1B colors, 120Hz, HDR10+',
      resolution: '2800 x 1260 pixels (1.5K)',
      refreshRate: 120,
      peakBrightness: 4500,
      hdr: 'HDR10+',
      protection: 'Armor Glass',
      screenToBodyRatio: '90.1%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 9400 (3nm)',
      cpu: 'Octa-core (1x3.63 GHz Cortex-X925 & 3x3.3 GHz Cortex-X4 & 4x2.4 GHz Cortex-A720)',
      gpu: 'Immortalis-G925',
      ramOptions: ['12GB', '16GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 2800000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 50MP) Zeiss Optics',
      mainCamera: '50 MP Sony IMX921, 1/1.56", f/1.57, VCS, OIS',
      ultrawideCamera: '50 MP Samsung JN1, f/2.0, 119˚',
      telephotoCamera: '50 MP Sony IMX882 periscope telephoto, 3x optical, 70mm, OIS',
      frontCamera: '32 MP, f/2.0',
      videoRecording: '4K@60fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5800,
      wiredCharging: 90,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '160.27 x 74.81 x 7.99 mm',
      weight: 197,
      materials: 'Glass front, aluminum frame, glass back',
      waterResistance: 'IP68/IP69',
      colors: ['Aurora Green', 'Midnight Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 15',
      launchOS: 'Android 15',
      promisedMajorUpdates: 4,
      securityUpdatePolicy: '5 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.vivo.com/in/products/x200',
      productPage: 'https://shop.vivo.com/in/product/10333',
      specSheetUrl: 'https://www.vivo.com/in/products/param/x200',
      verifiedDate: '2024-12',
    },
  },

  {
    id: 'vivo-x100-pro',
    slug: 'vivo-x100-pro',
    brand: 'Vivo',
    modelName: 'Vivo X100 Pro',
    generation: 'X100',
    status: 'active',
    launchDate: '2024-01',
    pricing: {
      startingPrice: 89999,
      maximumPrice: 89999,
      launchPrice: 89999,
      currentPrice: 89999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Vivo India Official Store',
    },
    display: {
      displaySize: 6.78,
      displayType: 'LTPO AMOLED, 1B colors, 120Hz',
      resolution: '2800 x 1260 pixels',
      refreshRate: 120,
      peakBrightness: 3000,
      hdr: 'HDR10+',
      protection: 'Armor Glass',
      screenToBodyRatio: '89.8%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 9300 (4nm)',
      cpu: 'Octa-core (1x3.25 GHz Cortex-X4 & 3x2.85 GHz Cortex-X4 & 4x2.0 GHz Cortex-A720)',
      gpu: 'Immortalis-G720 MC12',
      ramOptions: ['16GB'],
      storageOptions: ['512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 2150000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 50MP) Zeiss APO',
      mainCamera: '50 MP 1-inch Sony IMX989, f/1.75, OIS',
      ultrawideCamera: '50 MP Samsung JN1, f/2.0, 119˚',
      telephotoCamera: '50 MP Zeiss APO 4.3x periscope, 100mm, OIS, macro',
      frontCamera: '32 MP, f/2.0',
      videoRecording: '8K@30fps, 4K@60fps, 4K Cinematic Portrait',
      ois: true,
    },
    battery: {
      batteryCapacity: 5400,
      wiredCharging: 100,
      wirelessCharging: 50,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 3.2 Gen 1',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '164.05 x 75.28 x 8.91 mm',
      weight: 225,
      materials: 'Glass front, aluminum frame, sun-halo ring glass back',
      waterResistance: 'IP68',
      colors: ['Asteroid Black', 'Sunset Orange'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.vivo.com/in/products/x100pro',
      productPage: 'https://shop.vivo.com/in/product/10292',
      specSheetUrl: 'https://www.vivo.com/in/products/param/x100pro',
      verifiedDate: '2024-01',
    },
  },

  {
    id: 'vivo-x100',
    slug: 'vivo-x100',
    brand: 'Vivo',
    modelName: 'Vivo X100',
    generation: 'X100',
    status: 'active',
    launchDate: '2024-01',
    pricing: {
      startingPrice: 63999,
      maximumPrice: 69999,
      launchPrice: 63999,
      currentPrice: 63999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Vivo India Official Store',
    },
    display: {
      displaySize: 6.78,
      displayType: 'LTPO AMOLED, 1B colors, 120Hz',
      resolution: '2800 x 1260 pixels',
      refreshRate: 120,
      peakBrightness: 3000,
      hdr: 'HDR10+',
      protection: 'Armor Glass',
      screenToBodyRatio: '89.8%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 9300 (4nm)',
      cpu: 'Octa-core (1x3.25 GHz Cortex-X4 & 3x2.85 GHz Cortex-X4 & 4x2.0 GHz Cortex-A720)',
      gpu: 'Immortalis-G720 MC12',
      ramOptions: ['12GB', '16GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 2100000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 64MP + 50MP) Zeiss Optics',
      mainCamera: '50 MP Sony IMX920, 1/1.49", f/1.57, VCS, OIS',
      ultrawideCamera: '50 MP Samsung JN1, f/2.0, 119˚',
      telephotoCamera: '64 MP OmniVision OV64B periscope, 3x optical, 70mm, OIS, macro',
      frontCamera: '32 MP, f/2.0',
      videoRecording: '4K@60fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 120,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '164.05 x 75.19 x 8.49 mm',
      weight: 206,
      materials: 'Glass front, aluminum frame, moon-halo glass back',
      waterResistance: 'IP68',
      colors: ['Stargaze Blue', 'Asteroid Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.vivo.com/in/products/x100',
      productPage: 'https://shop.vivo.com/in/product/10291',
      specSheetUrl: 'https://www.vivo.com/in/products/param/x100',
      verifiedDate: '2024-01',
    },
  },

  {
    id: 'vivo-x90-pro',
    slug: 'vivo-x90-pro',
    brand: 'Vivo',
    modelName: 'Vivo X90 Pro',
    generation: 'X90',
    status: 'discontinued',
    launchDate: '2023-04',
    pricing: {
      startingPrice: 74999,
      maximumPrice: 84999,
      launchPrice: 84999,
      currentPrice: 74999,
      currency: 'INR',
      priceEffectiveDate: '2024-01',
      source: 'Vivo India Official Store',
    },
    display: {
      displaySize: 6.78,
      displayType: 'AMOLED, 1B colors, 120Hz, HDR10+',
      resolution: '2800 x 1260 pixels (1.5K)',
      refreshRate: 120,
      peakBrightness: 1300,
      hdr: 'HDR10+',
      protection: 'Schott Xensation Up',
      screenToBodyRatio: '90.8%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 9200 (4nm)',
      cpu: 'Octa-core (1x3.05 GHz Cortex-X3 & 3x2.85 GHz Cortex-A715 & 4x1.80 GHz Cortex-A510)',
      gpu: 'Immortalis-G715 MC11',
      ramOptions: ['12GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 4.0',
      antutuScore: 1250000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50.3MP + 50MP + 12MP) Zeiss Optics',
      mainCamera: '50.3 MP 1.0-type Sony IMX989, f/1.75, OIS',
      ultrawideCamera: '12 MP Sony IMX663, f/2.0, 108˚',
      telephotoCamera: '50 MP Sony IMX758 2x portrait, 50mm, f/1.6, OIS',
      frontCamera: '32 MP, f/2.45',
      videoRecording: '8K@24fps, 4K@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4870,
      wiredCharging: 120,
      wirelessCharging: 50,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 3.2 Gen 1',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '164.07 x 74.53 x 9.34 mm',
      weight: 214.85,
      materials: 'Glass front, aluminum frame, vegan leather back with skyline metallic band',
      waterResistance: 'IP68',
      colors: ['Legend Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 13',
      launchOS: 'Android 13',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.vivo.com/in/products/x90pro',
      productPage: 'https://shop.vivo.com/in/product/10231',
      specSheetUrl: 'https://www.vivo.com/in/products/param/x90pro',
      verifiedDate: '2023-04',
    },
  },

  {
    id: 'vivo-x-fold-3-pro',
    slug: 'vivo-x-fold-3-pro',
    brand: 'Vivo',
    modelName: 'Vivo X Fold3 Pro',
    generation: 'X Fold',
    status: 'active',
    launchDate: '2024-06',
    pricing: {
      startingPrice: 159999,
      maximumPrice: 159999,
      launchPrice: 159999,
      currentPrice: 159999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Vivo India Official Store',
    },
    display: {
      displaySize: 8.03,
      displayType: 'Foldable LTPO AMOLED, 1B colors, 120Hz, Dolby Vision, HDR10+',
      resolution: '2480 x 2200 pixels',
      refreshRate: 120,
      peakBrightness: 4500,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'UTG ultra-thin glass / Armor Glass cover',
      screenToBodyRatio: '90.5%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Gen 3 (4nm)',
      cpu: 'Octa-core (1x3.3 GHz Cortex-X4 & 5x3.2 GHz & 2x2.3 GHz)',
      gpu: 'Adreno 750',
      ramOptions: ['16GB'],
      storageOptions: ['512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 2150000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 64MP + 50MP) Zeiss Optics',
      mainCamera: '50 MP OmniVision OV50H, 1/1.3", f/1.68, VCS, OIS',
      ultrawideCamera: '50 MP Samsung JN1, f/2.0, 119˚',
      telephotoCamera: '64 MP OmniVision OV64B 3x periscope, f/2.57, OIS, macro',
      frontCamera: 'Dual 32 MP (32MP internal + 32MP cover)',
      videoRecording: '8K@30fps, 4K@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5700,
      wiredCharging: 100,
      wirelessCharging: 50,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 3.2 Gen 2',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '159.96 x 142.4 x 5.2 mm (unfolded) / 159.96 x 72.55 x 11.2 mm (folded)',
      weight: 236,
      materials: 'Armor Glass, carbon fiber hinge, glass fiber back',
      waterResistance: 'IPX8',
      colors: ['Celestial Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: '3D Ultrasonic under display (dual screen)',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.vivo.com/in/products/xfold3pro',
      productPage: 'https://shop.vivo.com/in/product/10310',
      specSheetUrl: 'https://www.vivo.com/in/products/param/xfold3pro',
      verifiedDate: '2024-06',
    },
  },

  // ── VIVO V SERIES (Portraits & Sleek Design) ──
  {
    id: 'vivo-v40-pro',
    slug: 'vivo-v40-pro',
    brand: 'Vivo',
    modelName: 'Vivo V40 Pro',
    generation: 'V40',
    status: 'active',
    launchDate: '2024-08',
    pricing: {
      startingPrice: 49999,
      maximumPrice: 55999,
      launchPrice: 49999,
      currentPrice: 49999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Vivo India Official Store',
    },
    display: {
      displaySize: 6.78,
      displayType: '1.5K 120Hz 3D Curved AMOLED',
      resolution: '2800 x 1260 pixels',
      refreshRate: 120,
      peakBrightness: 4500,
      hdr: 'HDR10+',
      protection: 'Schott Xensation Up',
      screenToBodyRatio: '90.1%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 9200+ (4nm)',
      cpu: 'Octa-core (1x3.35 GHz Cortex-X3 & 3x3.0 GHz Cortex-A715 & 4x2.0 GHz Cortex-A510)',
      gpu: 'Immortalis-G715 MC11',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 3.1',
      antutuScore: 1500000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 50MP) Zeiss Multifocal',
      mainCamera: '50 MP Sony IMX921, f/1.88, OIS, Zeiss T*',
      ultrawideCamera: '50 MP, f/2.0, 119˚, AF',
      telephotoCamera: '50 MP Sony IMX816 2x telephoto, f/1.85, OIS',
      frontCamera: '50 MP Zeiss Group Selfie, f/2.0, 92˚, AF',
      videoRecording: '4K@60fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5500,
      wiredCharging: 80,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '164.36 x 75.1 x 7.58 mm',
      weight: 192,
      materials: 'Glass front, plastic frame, fluorite AG glass back',
      waterResistance: 'IP68',
      colors: ['Ganges Blue', 'Titanium Grey'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.vivo.com/in/products/v40pro',
      productPage: 'https://shop.vivo.com/in/product/10319',
      specSheetUrl: 'https://www.vivo.com/in/products/param/v40pro',
      verifiedDate: '2024-08',
    },
  },

  {
    id: 'vivo-v40',
    slug: 'vivo-v40',
    brand: 'Vivo',
    modelName: 'Vivo V40',
    generation: 'V40',
    status: 'active',
    launchDate: '2024-08',
    pricing: {
      startingPrice: 34999,
      maximumPrice: 41999,
      launchPrice: 34999,
      currentPrice: 34999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Vivo India Official Store',
    },
    display: {
      displaySize: 6.78,
      displayType: '1.5K 120Hz 3D Curved AMOLED',
      resolution: '2800 x 1260 pixels',
      refreshRate: 120,
      peakBrightness: 4500,
      hdr: 'HDR10+',
      protection: 'Schott Xensation Up',
      screenToBodyRatio: '90.1%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7 Gen 3 (4nm)',
      cpu: 'Octa-core (1x2.63 GHz Cortex-A715 & 4x2.4 GHz Cortex-A715 & 3x1.8 GHz Cortex-A510)',
      gpu: 'Adreno 720',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB', '512GB'],
      storageType: 'UFS 2.2',
      antutuScore: 820000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 50MP) Zeiss Optics',
      mainCamera: '50 MP Samsung ISOCELL GNJ, f/1.88, OIS, Zeiss T*',
      ultrawideCamera: '50 MP, f/2.0, 119˚, AF',
      telephotoCamera: 'None',
      frontCamera: '50 MP Zeiss wide selfie, f/2.0, 92˚, AF',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5500,
      wiredCharging: 80,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '164.16 x 74.93 x 7.58 mm',
      weight: 190,
      materials: 'Glass front, plastic frame, glass back',
      waterResistance: 'IP68',
      colors: ['Ganges Blue', 'Titanium Grey', 'Lotus Purple'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.vivo.com/in/products/v40',
      productPage: 'https://shop.vivo.com/in/product/10318',
      specSheetUrl: 'https://www.vivo.com/in/products/param/v40',
      verifiedDate: '2024-08',
    },
  },

  {
    id: 'vivo-v40e',
    slug: 'vivo-v40e',
    brand: 'Vivo',
    modelName: 'Vivo V40e',
    generation: 'V40',
    status: 'active',
    launchDate: '2024-09',
    pricing: {
      startingPrice: 28999,
      maximumPrice: 30999,
      launchPrice: 28999,
      currentPrice: 28999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Vivo India Official Store',
    },
    display: {
      displaySize: 6.77,
      displayType: '120Hz 3D Curved AMOLED',
      resolution: '2392 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 4500,
      hdr: 'HDR10+',
      protection: 'Toughened Glass',
      screenToBodyRatio: '90.3%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7300 (4nm)',
      cpu: 'Octa-core (4x2.5 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G615 MC2',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 710000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 8MP) Aura Light',
      mainCamera: '50 MP Sony IMX882, f/1.79, OIS',
      ultrawideCamera: '8 MP, f/2.2, 120˚',
      telephotoCamera: 'None',
      frontCamera: '50 MP Eye AF selfie, f/2.0',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5500,
      wiredCharging: 80,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.4',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '163.72 x 75.0 x 7.49 mm',
      weight: 183,
      materials: 'Glass front, plastic frame, luxury-textured back',
      waterResistance: 'IP64',
      colors: ['Royal Bronze', 'Mint Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.vivo.com/in/products/v40e',
      productPage: 'https://shop.vivo.com/in/product/10323',
      specSheetUrl: 'https://www.vivo.com/in/products/param/v40e',
      verifiedDate: '2024-09',
    },
  },

  {
    id: 'vivo-v30-pro',
    slug: 'vivo-v30-pro',
    brand: 'Vivo',
    modelName: 'Vivo V30 Pro',
    generation: 'V30',
    status: 'active',
    launchDate: '2024-03',
    pricing: {
      startingPrice: 41999,
      maximumPrice: 46999,
      launchPrice: 41999,
      currentPrice: 41999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Vivo India Official Store',
    },
    display: {
      displaySize: 6.78,
      displayType: '1.5K 120Hz 3D Curved AMOLED',
      resolution: '2800 x 1260 pixels',
      refreshRate: 120,
      peakBrightness: 2800,
      hdr: 'HDR10+',
      protection: 'Schott Xensation Up',
      screenToBodyRatio: '89.9%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 8200 (4nm)',
      cpu: 'Octa-core (1x3.1 GHz Cortex-A78 & 3x3.0 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G610 MC6',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 3.1',
      antutuScore: 980000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 50MP) Zeiss Optics',
      mainCamera: '50 MP Sony IMX920, f/1.88, OIS, Zeiss T*',
      ultrawideCamera: '50 MP Samsung JN1, f/2.0, 119˚',
      telephotoCamera: '50 MP Sony IMX816 2x portrait, f/1.85, 50mm',
      frontCamera: '50 MP Zeiss Eye AF selfie, f/2.0',
      videoRecording: '4K@60fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 80,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '164.36 x 75.1 x 7.45 mm',
      weight: 188,
      materials: 'Glass front, plastic frame, fluorite AG glass back',
      waterResistance: 'IP54',
      colors: ['Andaman Blue', 'Classic Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Single speaker with Hi-Res audio',
      stereo: false,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.vivo.com/in/products/v30pro',
      productPage: 'https://shop.vivo.com/in/product/10298',
      specSheetUrl: 'https://www.vivo.com/in/products/param/v30pro',
      verifiedDate: '2024-03',
    },
  },

  {
    id: 'vivo-v30',
    slug: 'vivo-v30',
    brand: 'Vivo',
    modelName: 'Vivo V30',
    generation: 'V30',
    status: 'active',
    launchDate: '2024-03',
    pricing: {
      startingPrice: 33999,
      maximumPrice: 37999,
      launchPrice: 33999,
      currentPrice: 33999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Vivo India Official Store',
    },
    display: {
      displaySize: 6.78,
      displayType: '1.5K 120Hz 3D Curved AMOLED',
      resolution: '2800 x 1260 pixels',
      refreshRate: 120,
      peakBrightness: 2800,
      hdr: 'HDR10+',
      protection: 'Schott Xensation Up',
      screenToBodyRatio: '89.9%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7 Gen 3 (4nm)',
      cpu: 'Octa-core (1x2.63 GHz Cortex-A715 & 4x2.4 GHz Cortex-A715 & 3x1.8 GHz Cortex-A510)',
      gpu: 'Adreno 720',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 820000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 50MP) Studio Aura Light',
      mainCamera: '50 MP OmniVision OV50E, f/1.79, OIS',
      ultrawideCamera: '50 MP, f/2.0, 119˚, AF',
      telephotoCamera: 'None',
      frontCamera: '50 MP wide selfie, f/2.0, AF',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 80,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.4',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '164.36 x 75.1 x 7.45 mm',
      weight: 186,
      materials: 'Glass front, plastic frame, 3D petal glass back',
      waterResistance: 'IP54',
      colors: ['Andaman Blue', 'Peacock Green', 'Classic Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.vivo.com/in/products/v30',
      productPage: 'https://shop.vivo.com/in/product/10297',
      specSheetUrl: 'https://www.vivo.com/in/products/param/v30',
      verifiedDate: '2024-03',
    },
  },

  {
    id: 'vivo-v29-pro',
    slug: 'vivo-v29-pro',
    brand: 'Vivo',
    modelName: 'Vivo V29 Pro',
    generation: 'V29',
    status: 'discontinued',
    launchDate: '2023-10',
    pricing: {
      startingPrice: 39999,
      maximumPrice: 42999,
      launchPrice: 39999,
      currentPrice: 39999,
      currency: 'INR',
      priceEffectiveDate: '2024-03',
      source: 'Vivo India Official Store',
    },
    display: {
      displaySize: 6.78,
      displayType: '1.5K 120Hz 3D Curved AMOLED',
      resolution: '2800 x 1260 pixels',
      refreshRate: 120,
      peakBrightness: 1300,
      hdr: 'HDR10+',
      protection: 'Schott Xensation Up',
      screenToBodyRatio: '90.3%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 8200 (4nm)',
      cpu: 'Octa-core (1x3.1 GHz Cortex-A78 & 3x3.0 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G610 MC6',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 920000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 12MP + 8MP) Smart Aura Light',
      mainCamera: '50 MP Sony IMX766, f/1.88, OIS',
      ultrawideCamera: '8 MP, f/2.2',
      telephotoCamera: '12 MP Sony IMX663 2x portrait telephoto, f/1.98',
      frontCamera: '50 MP Eye AF, f/2.0',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4600,
      wiredCharging: 80,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '164.18 x 74.37 x 7.46 mm',
      weight: 188,
      materials: 'Glass front, plastic frame, 3D magnetic particle glass back',
      waterResistance: 'None',
      colors: ['Himalayan Blue', 'Space Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 13',
      launchOS: 'Android 13',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.vivo.com/in/products/v29pro',
      productPage: 'https://shop.vivo.com/in/product/10271',
      specSheetUrl: 'https://www.vivo.com/in/products/param/v29pro',
      verifiedDate: '2023-10',
    },
  },

  // ── VIVO T SERIES (Performance & Flipkart Online Line) ──
  {
    id: 'vivo-t3-ultra',
    slug: 'vivo-t3-ultra',
    brand: 'Vivo',
    modelName: 'Vivo T3 Ultra',
    generation: 'T3',
    status: 'active',
    launchDate: '2024-09',
    pricing: {
      startingPrice: 31999,
      maximumPrice: 35999,
      launchPrice: 31999,
      currentPrice: 31999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Flipkart / Vivo India',
    },
    display: {
      displaySize: 6.78,
      displayType: '1.5K 120Hz 3D Curved AMOLED',
      resolution: '2800 x 1260 pixels',
      refreshRate: 120,
      peakBrightness: 4500,
      hdr: 'HDR10+',
      protection: 'Schott Xensation Up',
      screenToBodyRatio: '90.1%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 9200+ (4nm)',
      cpu: 'Octa-core (1x3.35 GHz Cortex-X3 & 3x3.0 GHz Cortex-A715 & 4x2.0 GHz Cortex-A510)',
      gpu: 'Immortalis-G715 MC11',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 1600000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 8MP) Sony IMX921 with OIS',
      mainCamera: '50 MP Sony IMX921, f/1.88, OIS, Aura Light',
      ultrawideCamera: '8 MP, f/2.2, 120˚',
      telephotoCamera: 'None',
      frontCamera: '50 MP Group Selfie, f/2.0, AF',
      videoRecording: '4K@60fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5500,
      wiredCharging: 80,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '164.16 x 74.93 x 7.58 mm',
      weight: 192,
      materials: 'Glass front, plastic frame, glass back',
      waterResistance: 'IP68',
      colors: ['Frost Green', 'Lunar Grey'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.vivo.com/in/products/t3-ultra',
      productPage: 'https://www.flipkart.com/vivo-t3-ultra-5g/p/itm123',
      specSheetUrl: 'https://www.vivo.com/in/products/param/t3-ultra',
      verifiedDate: '2024-09',
    },
  },

  {
    id: 'vivo-t3-pro-5g',
    slug: 'vivo-t3-pro-5g',
    brand: 'Vivo',
    modelName: 'Vivo T3 Pro 5G',
    generation: 'T3',
    status: 'active',
    launchDate: '2024-08',
    pricing: {
      startingPrice: 24999,
      maximumPrice: 26999,
      launchPrice: 24999,
      currentPrice: 24999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Flipkart / Vivo India',
    },
    display: {
      displaySize: 6.77,
      displayType: '120Hz 3D Curved AMOLED',
      resolution: '2392 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 4500,
      hdr: 'HDR10+',
      protection: 'Schott Xensation Up',
      screenToBodyRatio: '90.3%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7 Gen 3 (4nm)',
      cpu: 'Octa-core (1x2.63 GHz Cortex-A715 & 4x2.4 GHz Cortex-A715 & 3x1.8 GHz Cortex-A510)',
      gpu: 'Adreno 720',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 820000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 8MP)',
      mainCamera: '50 MP Sony IMX882, f/1.79, OIS',
      ultrawideCamera: '8 MP, f/2.2, 120˚',
      telephotoCamera: 'None',
      frontCamera: '16 MP, f/2.45',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5500,
      wiredCharging: 80,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.4',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '163.72 x 75.0 x 7.49 mm',
      weight: 184,
      materials: 'Glass front, plastic frame, vegan leather / matte back',
      waterResistance: 'IP64',
      colors: ['Sandstone Orange', 'Emerald Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.vivo.com/in/products/t3-pro-5g',
      productPage: 'https://www.flipkart.com/vivo-t3-pro-5g/p/itm124',
      specSheetUrl: 'https://www.vivo.com/in/products/param/t3-pro-5g',
      verifiedDate: '2024-08',
    },
  },

  {
    id: 'vivo-t3-5g',
    slug: 'vivo-t3-5g',
    brand: 'Vivo',
    modelName: 'Vivo T3 5G',
    generation: 'T3',
    status: 'active',
    launchDate: '2024-03',
    pricing: {
      startingPrice: 19999,
      maximumPrice: 21999,
      launchPrice: 19999,
      currentPrice: 19999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Flipkart / Vivo India',
    },
    display: {
      displaySize: 6.67,
      displayType: 'AMOLED, 120Hz, HDR10+',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1800,
      hdr: 'HDR10+',
      protection: 'Asahi Glass DT-Star2 Plus',
      screenToBodyRatio: '86.8%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7200 (4nm)',
      cpu: 'Octa-core (2x2.8 GHz Cortex-A715 & 6x2.0 GHz Cortex-A510)',
      gpu: 'Mali-G610 MC4',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 730000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP)',
      mainCamera: '50 MP Sony IMX882, f/1.79, OIS',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP depth sensor',
      frontCamera: '16 MP, f/2.0',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 44,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '163.17 x 75.81 x 7.83 mm',
      weight: 188,
      materials: 'Glass front, plastic frame, crystal textured back',
      waterResistance: 'IP54',
      colors: ['Crystal Flake', 'Cosmic Blue'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with 300% audio boost',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.vivo.com/in/products/t3-5g',
      productPage: 'https://www.flipkart.com/vivo-t3-5g/p/itm125',
      specSheetUrl: 'https://www.vivo.com/in/products/param/t3-5g',
      verifiedDate: '2024-03',
    },
  },

  {
    id: 'vivo-t3x-5g',
    slug: 'vivo-t3x-5g',
    brand: 'Vivo',
    modelName: 'Vivo T3x 5G',
    generation: 'T3',
    status: 'active',
    launchDate: '2024-04',
    pricing: {
      startingPrice: 13499,
      maximumPrice: 16499,
      launchPrice: 13499,
      currentPrice: 13499,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Flipkart / Vivo India',
    },
    display: {
      displaySize: 6.72,
      displayType: 'IPS LCD, 120Hz',
      resolution: '2408 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1000,
      hdr: 'None',
      protection: 'Toughened Glass',
      screenToBodyRatio: '86.4%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 6 Gen 1 (4nm)',
      cpu: 'Octa-core (4x2.2 GHz Cortex-A78 & 4x1.8 GHz Cortex-A55)',
      gpu: 'Adreno 710',
      ramOptions: ['4GB', '6GB', '8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 560000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP)',
      mainCamera: '50 MP, f/1.8',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP depth sensor',
      frontCamera: '8 MP, f/2.05',
      videoRecording: '4K@30fps, 1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 6000,
      wiredCharging: 44,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.1',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '165.7 x 76.0 x 7.99 mm',
      weight: 199,
      materials: 'Glass front, plastic frame, circular camera module finish',
      waterResistance: 'IP64',
      colors: ['Celestial Green', 'Crimson Bliss'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with 300% volume boost',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.vivo.com/in/products/t3x-5g',
      productPage: 'https://www.flipkart.com/vivo-t3x-5g/p/itm126',
      specSheetUrl: 'https://www.vivo.com/in/products/param/t3x-5g',
      verifiedDate: '2024-04',
    },
  },

  {
    id: 'vivo-t3-lite-5g',
    slug: 'vivo-t3-lite-5g',
    brand: 'Vivo',
    modelName: 'Vivo T3 Lite 5G',
    generation: 'T3',
    status: 'active',
    launchDate: '2024-06',
    pricing: {
      startingPrice: 10499,
      maximumPrice: 11499,
      launchPrice: 10499,
      currentPrice: 10499,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Flipkart / Vivo India',
    },
    display: {
      displaySize: 6.56,
      displayType: 'IPS LCD, 90Hz',
      resolution: '1612 x 720 pixels (HD+)',
      refreshRate: 90,
      peakBrightness: 840,
      hdr: 'None',
      protection: 'Toughened Glass',
      screenToBodyRatio: '83.9%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6300 (6nm)',
      cpu: 'Octa-core (2x2.4 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['4GB', '6GB'],
      storageOptions: ['128GB'],
      storageType: 'eMMC 5.1',
      antutuScore: 415000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP)',
      mainCamera: '50 MP Sony sensor, f/1.8',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP depth, f/2.4',
      frontCamera: '8 MP, f/2.0',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 15,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.4',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '163.63 x 75.58 x 8.53 mm',
      weight: 185,
      materials: 'Glass front, plastic frame and back',
      waterResistance: 'IP64',
      colors: ['Vibrant Green', 'Majestic Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.vivo.com/in/products/t3-lite-5g',
      productPage: 'https://www.flipkart.com/vivo-t3-lite-5g/p/itm127',
      specSheetUrl: 'https://www.vivo.com/in/products/param/t3-lite-5g',
      verifiedDate: '2024-06',
    },
  },

  // ── VIVO Y SERIES (Offline Retail Mainstays) ──
  {
    id: 'vivo-y200-5g',
    slug: 'vivo-y200-5g',
    brand: 'Vivo',
    modelName: 'Vivo Y200 5G',
    generation: 'Y200',
    status: 'active',
    launchDate: '2023-10',
    pricing: {
      startingPrice: 21999,
      maximumPrice: 23999,
      launchPrice: 21999,
      currentPrice: 21999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Vivo India Official Store',
    },
    display: {
      displaySize: 6.67,
      displayType: 'AMOLED, 120Hz, HDR10+',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 800,
      hdr: 'HDR10+',
      protection: 'Toughened Glass',
      screenToBodyRatio: '86.8%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 4 Gen 1 (6nm)',
      cpu: 'Octa-core (2x2.0 GHz Cortex-A78 & 6x1.8 GHz Cortex-A55)',
      gpu: 'Adreno 619',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 410000,
    },
    cameras: {
      rearCameraSetup: 'Dual (64MP + 2MP) Smart Aura Light',
      mainCamera: '64 MP, f/1.79, OIS',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP depth sensor',
      frontCamera: '16 MP, f/2.0',
      videoRecording: '1080p@30fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4800,
      wiredCharging: 44,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.1',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '162.35 x 74.85 x 7.69 mm',
      weight: 190,
      materials: 'Glass front, plastic frame, fluorite AG glass back',
      waterResistance: 'IP54',
      colors: ['Desert Gold', 'Jungle Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 13',
      launchOS: 'Android 13',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.vivo.com/in/products/y200-5g',
      productPage: 'https://shop.vivo.com/in/product/10276',
      specSheetUrl: 'https://www.vivo.com/in/products/param/y200-5g',
      verifiedDate: '2023-10',
    },
  },

  {
    id: 'vivo-y28-5g',
    slug: 'vivo-y28-5g',
    brand: 'Vivo',
    modelName: 'Vivo Y28 5G',
    generation: 'Y28',
    status: 'active',
    launchDate: '2024-01',
    pricing: {
      startingPrice: 13999,
      maximumPrice: 16999,
      launchPrice: 13999,
      currentPrice: 13999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Vivo India Official Store',
    },
    display: {
      displaySize: 6.56,
      displayType: 'IPS LCD, 90Hz',
      resolution: '1612 x 720 pixels (HD+)',
      refreshRate: 90,
      peakBrightness: 840,
      hdr: 'None',
      protection: 'Toughened Glass',
      screenToBodyRatio: '83.9%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6020 (7nm)',
      cpu: 'Octa-core (2x2.2 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['4GB', '6GB', '8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 395000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP)',
      mainCamera: '50 MP, f/1.8',
      ultrawideCamera: 'None',
      telephotoCamera: '2 MP depth sensor',
      frontCamera: '8 MP, f/2.0',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 15,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.1',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '163.74 x 75.43 x 8.09 mm',
      weight: 186,
      materials: 'Glass front, metallic high-gloss plastic frame and back',
      waterResistance: 'IP54',
      colors: ['Glitter Aqua', 'Crystal Purple'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Funtouch OS 13',
      launchOS: 'Android 13',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.vivo.com/in/products/y28-5g',
      productPage: 'https://shop.vivo.com/in/product/10290',
      specSheetUrl: 'https://www.vivo.com/in/products/param/y28-5g',
      verifiedDate: '2024-01',
    },
  },
];

const variants: MobileVariant[] = [
  // Vivo X200 Pro
  {
    id: 'vivo-x200-pro-16-512',
    modelId: 'vivo-x200-pro',
    ram: '16GB',
    storage: '512GB',
    price: 94999,
    mrp: 94999,
    colors: ['Titanium Grey', 'Carbon Black'],
    status: 'active',
    verified: true,
    source: 'Vivo India Official Store',
  },
  // Vivo X200
  {
    id: 'vivo-x200-12-256',
    modelId: 'vivo-x200',
    ram: '12GB',
    storage: '256GB',
    price: 65999,
    mrp: 65999,
    colors: ['Aurora Green', 'Midnight Black'],
    status: 'active',
    verified: true,
    source: 'Vivo India Official Store',
  },
  {
    id: 'vivo-x200-16-512',
    modelId: 'vivo-x200',
    ram: '16GB',
    storage: '512GB',
    price: 71999,
    mrp: 71999,
    colors: ['Aurora Green', 'Midnight Black'],
    status: 'active',
    verified: true,
    source: 'Vivo India Official Store',
  },
  // Vivo X100 Pro
  {
    id: 'vivo-x100-pro-16-512',
    modelId: 'vivo-x100-pro',
    ram: '16GB',
    storage: '512GB',
    price: 89999,
    mrp: 89999,
    colors: ['Asteroid Black', 'Sunset Orange'],
    status: 'active',
    verified: true,
    source: 'Vivo India Official Store',
  },
  // Vivo X100
  {
    id: 'vivo-x100-12-256',
    modelId: 'vivo-x100',
    ram: '12GB',
    storage: '256GB',
    price: 63999,
    mrp: 63999,
    colors: ['Stargaze Blue', 'Asteroid Black'],
    status: 'active',
    verified: true,
    source: 'Vivo India Official Store',
  },
  {
    id: 'vivo-x100-16-512',
    modelId: 'vivo-x100',
    ram: '16GB',
    storage: '512GB',
    price: 69999,
    mrp: 69999,
    colors: ['Stargaze Blue', 'Asteroid Black'],
    status: 'active',
    verified: true,
    source: 'Vivo India Official Store',
  },
  // Vivo X90 Pro
  {
    id: 'vivo-x90-pro-12-256',
    modelId: 'vivo-x90-pro',
    ram: '12GB',
    storage: '256GB',
    price: 74999,
    mrp: 84999,
    colors: ['Legend Black'],
    status: 'discontinued',
    verified: true,
    source: 'Vivo India Official Store',
  },
  // Vivo X Fold3 Pro
  {
    id: 'vivo-x-fold-3-pro-16-512',
    modelId: 'vivo-x-fold-3-pro',
    ram: '16GB',
    storage: '512GB',
    price: 159999,
    mrp: 159999,
    colors: ['Celestial Black'],
    status: 'active',
    verified: true,
    source: 'Vivo India Official Store',
  },
  // Vivo V40 Pro
  {
    id: 'vivo-v40-pro-8-256',
    modelId: 'vivo-v40-pro',
    ram: '8GB',
    storage: '256GB',
    price: 49999,
    mrp: 49999,
    colors: ['Ganges Blue', 'Titanium Grey'],
    status: 'active',
    verified: true,
    source: 'Vivo India Official Store',
  },
  {
    id: 'vivo-v40-pro-12-512',
    modelId: 'vivo-v40-pro',
    ram: '12GB',
    storage: '512GB',
    price: 55999,
    mrp: 55999,
    colors: ['Ganges Blue', 'Titanium Grey'],
    status: 'active',
    verified: true,
    source: 'Vivo India Official Store',
  },
  // Vivo V40
  {
    id: 'vivo-v40-8-128',
    modelId: 'vivo-v40',
    ram: '8GB',
    storage: '128GB',
    price: 34999,
    mrp: 34999,
    colors: ['Ganges Blue', 'Titanium Grey'],
    status: 'active',
    verified: true,
    source: 'Vivo India Official Store',
  },
  {
    id: 'vivo-v40-12-512',
    modelId: 'vivo-v40',
    ram: '12GB',
    storage: '512GB',
    price: 41999,
    mrp: 41999,
    colors: ['Ganges Blue', 'Titanium Grey'],
    status: 'active',
    verified: true,
    source: 'Vivo India Official Store',
  },
  // Vivo V40e
  {
    id: 'vivo-v40e-8-128',
    modelId: 'vivo-v40e',
    ram: '8GB',
    storage: '128GB',
    price: 28999,
    mrp: 28999,
    colors: ['Royal Bronze', 'Mint Green'],
    status: 'active',
    verified: true,
    source: 'Vivo India Official Store',
  },
  {
    id: 'vivo-v40e-8-256',
    modelId: 'vivo-v40e',
    ram: '8GB',
    storage: '256GB',
    price: 30999,
    mrp: 30999,
    colors: ['Royal Bronze', 'Mint Green'],
    status: 'active',
    verified: true,
    source: 'Vivo India Official Store',
  },
  // Vivo V30 Pro
  {
    id: 'vivo-v30-pro-8-256',
    modelId: 'vivo-v30-pro',
    ram: '8GB',
    storage: '256GB',
    price: 41999,
    mrp: 41999,
    colors: ['Andaman Blue', 'Classic Black'],
    status: 'active',
    verified: true,
    source: 'Vivo India Official Store',
  },
  {
    id: 'vivo-v30-pro-12-512',
    modelId: 'vivo-v30-pro',
    ram: '12GB',
    storage: '512GB',
    price: 46999,
    mrp: 46999,
    colors: ['Andaman Blue', 'Classic Black'],
    status: 'active',
    verified: true,
    source: 'Vivo India Official Store',
  },
  // Vivo V30
  {
    id: 'vivo-v30-8-128',
    modelId: 'vivo-v30',
    ram: '8GB',
    storage: '128GB',
    price: 33999,
    mrp: 33999,
    colors: ['Andaman Blue', 'Peacock Green'],
    status: 'active',
    verified: true,
    source: 'Vivo India Official Store',
  },
  {
    id: 'vivo-v30-12-256',
    modelId: 'vivo-v30',
    ram: '12GB',
    storage: '256GB',
    price: 37999,
    mrp: 37999,
    colors: ['Andaman Blue', 'Peacock Green'],
    status: 'active',
    verified: true,
    source: 'Vivo India Official Store',
  },
  // Vivo V29 Pro
  {
    id: 'vivo-v29-pro-8-256',
    modelId: 'vivo-v29-pro',
    ram: '8GB',
    storage: '256GB',
    price: 39999,
    mrp: 39999,
    colors: ['Himalayan Blue', 'Space Black'],
    status: 'discontinued',
    verified: true,
    source: 'Vivo India Official Store',
  },
  {
    id: 'vivo-v29-pro-12-256',
    modelId: 'vivo-v29-pro',
    ram: '12GB',
    storage: '256GB',
    price: 42999,
    mrp: 42999,
    colors: ['Himalayan Blue', 'Space Black'],
    status: 'discontinued',
    verified: true,
    source: 'Vivo India Official Store',
  },
  // Vivo T3 Ultra
  {
    id: 'vivo-t3-ultra-8-128',
    modelId: 'vivo-t3-ultra',
    ram: '8GB',
    storage: '128GB',
    price: 31999,
    mrp: 31999,
    colors: ['Frost Green', 'Lunar Grey'],
    status: 'active',
    verified: true,
    source: 'Flipkart / Vivo India',
  },
  {
    id: 'vivo-t3-ultra-12-256',
    modelId: 'vivo-t3-ultra',
    ram: '12GB',
    storage: '256GB',
    price: 35999,
    mrp: 35999,
    colors: ['Frost Green', 'Lunar Grey'],
    status: 'active',
    verified: true,
    source: 'Flipkart / Vivo India',
  },
  // Vivo T3 Pro 5G
  {
    id: 'vivo-t3-pro-5g-8-128',
    modelId: 'vivo-t3-pro-5g',
    ram: '8GB',
    storage: '128GB',
    price: 24999,
    mrp: 24999,
    colors: ['Sandstone Orange', 'Emerald Green'],
    status: 'active',
    verified: true,
    source: 'Flipkart / Vivo India',
  },
  {
    id: 'vivo-t3-pro-5g-8-256',
    modelId: 'vivo-t3-pro-5g',
    ram: '8GB',
    storage: '256GB',
    price: 26999,
    mrp: 26999,
    colors: ['Sandstone Orange', 'Emerald Green'],
    status: 'active',
    verified: true,
    source: 'Flipkart / Vivo India',
  },
  // Vivo T3 5G
  {
    id: 'vivo-t3-5g-8-128',
    modelId: 'vivo-t3-5g',
    ram: '8GB',
    storage: '128GB',
    price: 19999,
    mrp: 19999,
    colors: ['Crystal Flake', 'Cosmic Blue'],
    status: 'active',
    verified: true,
    source: 'Flipkart / Vivo India',
  },
  {
    id: 'vivo-t3-5g-8-256',
    modelId: 'vivo-t3-5g',
    ram: '8GB',
    storage: '256GB',
    price: 21999,
    mrp: 21999,
    colors: ['Crystal Flake', 'Cosmic Blue'],
    status: 'active',
    verified: true,
    source: 'Flipkart / Vivo India',
  },
  // Vivo T3x 5G
  {
    id: 'vivo-t3x-5g-4-128',
    modelId: 'vivo-t3x-5g',
    ram: '4GB',
    storage: '128GB',
    price: 13499,
    mrp: 13499,
    colors: ['Celestial Green', 'Crimson Bliss'],
    status: 'active',
    verified: true,
    source: 'Flipkart / Vivo India',
  },
  {
    id: 'vivo-t3x-5g-8-128',
    modelId: 'vivo-t3x-5g',
    ram: '8GB',
    storage: '128GB',
    price: 16499,
    mrp: 16499,
    colors: ['Celestial Green', 'Crimson Bliss'],
    status: 'active',
    verified: true,
    source: 'Flipkart / Vivo India',
  },
  // Vivo T3 Lite 5G
  {
    id: 'vivo-t3-lite-5g-4-128',
    modelId: 'vivo-t3-lite-5g',
    ram: '4GB',
    storage: '128GB',
    price: 10499,
    mrp: 10499,
    colors: ['Vibrant Green', 'Majestic Black'],
    status: 'active',
    verified: true,
    source: 'Flipkart / Vivo India',
  },
  {
    id: 'vivo-t3-lite-5g-6-128',
    modelId: 'vivo-t3-lite-5g',
    ram: '6GB',
    storage: '128GB',
    price: 11499,
    mrp: 11499,
    colors: ['Vibrant Green', 'Majestic Black'],
    status: 'active',
    verified: true,
    source: 'Flipkart / Vivo India',
  },
  // Vivo Y200 5G
  {
    id: 'vivo-y200-5g-8-128',
    modelId: 'vivo-y200-5g',
    ram: '8GB',
    storage: '128GB',
    price: 21999,
    mrp: 21999,
    colors: ['Desert Gold', 'Jungle Green'],
    status: 'active',
    verified: true,
    source: 'Vivo India Official Store',
  },
  {
    id: 'vivo-y200-5g-8-256',
    modelId: 'vivo-y200-5g',
    ram: '8GB',
    storage: '256GB',
    price: 23999,
    mrp: 23999,
    colors: ['Desert Gold', 'Jungle Green'],
    status: 'active',
    verified: true,
    source: 'Vivo India Official Store',
  },
  // Vivo Y28 5G
  {
    id: 'vivo-y28-5g-4-128',
    modelId: 'vivo-y28-5g',
    ram: '4GB',
    storage: '128GB',
    price: 13999,
    mrp: 13999,
    colors: ['Glitter Aqua', 'Crystal Purple'],
    status: 'active',
    verified: true,
    source: 'Vivo India Official Store',
  },
  {
    id: 'vivo-y28-5g-8-128',
    modelId: 'vivo-y28-5g',
    ram: '8GB',
    storage: '128GB',
    price: 16999,
    mrp: 16999,
    colors: ['Glitter Aqua', 'Crystal Purple'],
    status: 'active',
    verified: true,
    source: 'Vivo India Official Store',
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    modelId: 'vivo-x200-pro',
    modelName: 'Vivo X200 Pro',
    brand: 'Vivo',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-x200-pro.jpg',
        angle: 'front',
        source: 'Vivo Official (GSMArena CDN)',
        sourceUrl: 'https://www.vivo.com/in/products/x200pro',
        verified: true,
        alt: 'Vivo X200 Pro Zeiss APO telephoto front display view',
      },
    ],
  },
  {
    modelId: 'vivo-x200',
    modelName: 'Vivo X200',
    brand: 'Vivo',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-x200.jpg',
        angle: 'front',
        source: 'Vivo Official (GSMArena CDN)',
        sourceUrl: 'https://www.vivo.com/in/products/x200',
        verified: true,
        alt: 'Vivo X200 front view',
      },
    ],
  },
  {
    modelId: 'vivo-x100-pro',
    modelName: 'Vivo X100 Pro',
    brand: 'Vivo',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-x100-pro.jpg',
        angle: 'front',
        source: 'Vivo Official (GSMArena CDN)',
        sourceUrl: 'https://www.vivo.com/in/products/x100pro',
        verified: true,
        alt: 'Vivo X100 Pro Zeiss front display view',
      },
    ],
  },
  {
    modelId: 'vivo-x100',
    modelName: 'Vivo X100',
    brand: 'Vivo',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-x100.jpg',
        angle: 'front',
        source: 'Vivo Official (GSMArena CDN)',
        sourceUrl: 'https://www.vivo.com/in/products/x100',
        verified: true,
        alt: 'Vivo X100 front view',
      },
    ],
  },
  {
    modelId: 'vivo-x90-pro',
    modelName: 'Vivo X90 Pro',
    brand: 'Vivo',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-x90-pro.jpg',
        angle: 'front',
        source: 'Vivo Official (GSMArena CDN)',
        sourceUrl: 'https://www.vivo.com/in/products/x90pro',
        verified: true,
        alt: 'Vivo X90 Pro 1-inch sensor flagship front view',
      },
    ],
  },
  {
    modelId: 'vivo-x-fold-3-pro',
    modelName: 'Vivo X Fold3 Pro',
    brand: 'Vivo',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-x-fold3-pro.jpg',
        angle: 'front',
        source: 'Vivo Official (GSMArena CDN)',
        sourceUrl: 'https://www.vivo.com/in/products/xfold3pro',
        verified: true,
        alt: 'Vivo X Fold3 Pro foldable display view',
      },
    ],
  },
  {
    modelId: 'vivo-v40-pro',
    modelName: 'Vivo V40 Pro',
    brand: 'Vivo',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-v40-pro.jpg',
        angle: 'front',
        source: 'Vivo Official (GSMArena CDN)',
        sourceUrl: 'https://www.vivo.com/in/products/v40pro',
        verified: true,
        alt: 'Vivo V40 Pro front curved view',
      },
    ],
  },
  {
    modelId: 'vivo-v40',
    modelName: 'Vivo V40',
    brand: 'Vivo',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-v40.jpg',
        angle: 'front',
        source: 'Vivo Official (GSMArena CDN)',
        sourceUrl: 'https://www.vivo.com/in/products/v40',
        verified: true,
        alt: 'Vivo V40 front view',
      },
    ],
  },
  {
    modelId: 'vivo-v40e',
    modelName: 'Vivo V40e',
    brand: 'Vivo',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-v40e.jpg',
        angle: 'front',
        source: 'Vivo Official (GSMArena CDN)',
        sourceUrl: 'https://www.vivo.com/in/products/v40e',
        verified: true,
        alt: 'Vivo V40e curved AMOLED front view',
      },
    ],
  },
  {
    modelId: 'vivo-v30-pro',
    modelName: 'Vivo V30 Pro',
    brand: 'Vivo',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-v30-pro.jpg',
        angle: 'front',
        source: 'Vivo Official (GSMArena CDN)',
        sourceUrl: 'https://www.vivo.com/in/products/v30pro',
        verified: true,
        alt: 'Vivo V30 Pro Zeiss front view',
      },
    ],
  },
  {
    modelId: 'vivo-v30',
    modelName: 'Vivo V30',
    brand: 'Vivo',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-s18.jpg',
        angle: 'front',
        source: 'Vivo Official (GSMArena CDN)',
        sourceUrl: 'https://www.vivo.com/in/products/v30',
        verified: true,
        alt: 'Vivo V30 front view',
      },
    ],
  },
  {
    modelId: 'vivo-v29-pro',
    modelName: 'Vivo V29 Pro',
    brand: 'Vivo',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-v29-pro.jpg',
        angle: 'front',
        source: 'Vivo Official (GSMArena CDN)',
        sourceUrl: 'https://www.vivo.com/in/products/v29pro',
        verified: true,
        alt: 'Vivo V29 Pro front view',
      },
    ],
  },
  {
    modelId: 'vivo-t3-ultra',
    modelName: 'Vivo T3 Ultra',
    brand: 'Vivo',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-t3-ultra.jpg',
        angle: 'front',
        source: 'Vivo Official (GSMArena CDN)',
        sourceUrl: 'https://www.vivo.com/in/products/t3-ultra',
        verified: true,
        alt: 'Vivo T3 Ultra front view',
      },
    ],
  },
  {
    modelId: 'vivo-t3-pro-5g',
    modelName: 'Vivo T3 Pro 5G',
    brand: 'Vivo',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-t3-pro.jpg',
        angle: 'front',
        source: 'Vivo Official (GSMArena CDN)',
        sourceUrl: 'https://www.vivo.com/in/products/t3-pro-5g',
        verified: true,
        alt: 'Vivo T3 Pro 5G front view',
      },
    ],
  },
  {
    modelId: 'vivo-t3-5g',
    modelName: 'Vivo T3 5G',
    brand: 'Vivo',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-t3-.jpg',
        angle: 'front',
        source: 'Vivo Official (GSMArena CDN)',
        sourceUrl: 'https://www.vivo.com/in/products/t3-5g',
        verified: true,
        alt: 'Vivo T3 5G front view',
      },
    ],
  },
  {
    modelId: 'vivo-t3x-5g',
    modelName: 'Vivo T3x 5G',
    brand: 'Vivo',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-t3x.jpg',
        angle: 'front',
        source: 'Vivo Official (GSMArena CDN)',
        sourceUrl: 'https://www.vivo.com/in/products/t3x-5g',
        verified: true,
        alt: 'Vivo T3x 5G front view',
      },
    ],
  },
  {
    modelId: 'vivo-t3-lite-5g',
    modelName: 'Vivo T3 Lite 5G',
    brand: 'Vivo',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-t3-lite.jpg',
        angle: 'front',
        source: 'Vivo Official (GSMArena CDN)',
        sourceUrl: 'https://www.vivo.com/in/products/t3-lite-5g',
        verified: true,
        alt: 'Vivo T3 Lite 5G front view',
      },
    ],
  },
  {
    modelId: 'vivo-y200-5g',
    modelName: 'Vivo Y200 5G',
    brand: 'Vivo',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-y200-.jpg',
        angle: 'front',
        source: 'Vivo Official (GSMArena CDN)',
        sourceUrl: 'https://www.vivo.com/in/products/y200-5g',
        verified: true,
        alt: 'Vivo Y200 5G front view',
      },
    ],
  },
  {
    modelId: 'vivo-y28-5g',
    modelName: 'Vivo Y28 5G',
    brand: 'Vivo',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-y28-5g-.jpg',
        angle: 'front',
        source: 'Vivo Official (GSMArena CDN)',
        sourceUrl: 'https://www.vivo.com/in/products/y28-5g',
        verified: true,
        alt: 'Vivo Y28 5G front view',
      },
    ],
  },
];

export const vivoBundle: MobileBrandBundle = {
  brand: 'Vivo',
  models,
  variants,
  images,
};
