import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  {
    id: 'xiaomi-14-ultra',
    slug: 'xiaomi-14-ultra',
    brand: 'Xiaomi',
    modelName: 'Xiaomi 14 Ultra',
    generation: '14',
    status: 'active',
    launchDate: '2024-03',
    pricing: {
      startingPrice: 99999,
      maximumPrice: 99999,
      launchPrice: 99999,
      currentPrice: 99999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.73,
      displayType: 'LTPO AMOLED C8 panel',
      resolution: '3200 x 1440 pixels (WQHD+)',
      refreshRate: 120,
      peakBrightness: 3000,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Xiaomi Shield Glass (ceramic-infused)',
      screenToBodyRatio: '89.6%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Gen 3 (4nm)',
      cpu: 'Octa-core (1x3.3 GHz Cortex-X4 & 5x3.2 GHz & 2x2.3 GHz)',
      gpu: 'Adreno 750',
      ramOptions: ['16GB'],
      storageOptions: ['512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 2100000,
    },
    cameras: {
      rearCameraSetup: 'Quad (50MP + 50MP + 50MP + 50MP) Leica Summilux',
      mainCamera: '50 MP 1-inch Sony LYT-900, variable aperture f/1.63-f/4.0, stepless, HyperOIS',
      ultrawideCamera: '50 MP Sony IMX858, f/1.8, 122˚, 5cm macro',
      telephotoCamera: '50 MP 3.2x telephoto (OIS) + 50 MP 5x periscope (OIS, 30cm macro)',
      frontCamera: '32 MP, f/2.0, 4K60',
      videoRecording: '8K@30fps, 4K@60/120fps, 10-bit Dolby Vision HDR',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 90,
      wirelessCharging: 80,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 3.2 Gen 2',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.4 x 75.3 x 9.2 mm',
      weight: 219.8,
      materials: 'CNC Aluminum unibody frame, nano-tech vegan leather back',
      waterResistance: 'IP68',
      colors: ['Black', 'White'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Xiaomi HyperOS',
      launchOS: 'Android 14',
      promisedMajorUpdates: 4,
      securityUpdatePolicy: '5 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/xiaomi-14-ultra/',
      productPage: 'https://store.mi.com/in/item/3241000001',
      specSheetUrl: 'https://www.mi.com/in/product/xiaomi-14-ultra/specs/',
      verifiedDate: '2024-03',
    },
  },

  {
    id: 'xiaomi-14',
    slug: 'xiaomi-14',
    brand: 'Xiaomi',
    modelName: 'Xiaomi 14',
    generation: '14',
    status: 'active',
    launchDate: '2024-03',
    pricing: {
      startingPrice: 59999,
      maximumPrice: 69999,
      launchPrice: 69999,
      currentPrice: 59999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.36,
      displayType: 'LTPO OLED, 120Hz, Dolby Vision, HDR10+',
      resolution: '2670 x 1200 pixels',
      refreshRate: 120,
      peakBrightness: 3000,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass Victus',
      screenToBodyRatio: '89.3%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Gen 3 (4nm)',
      cpu: 'Octa-core (1x3.3 GHz Cortex-X4 & 5x3.2 GHz & 2x2.3 GHz)',
      gpu: 'Adreno 750',
      ramOptions: ['12GB'],
      storageOptions: ['512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 2050000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 50MP) Leica',
      mainCamera: '50 MP Light Hunter 900, f/1.6, 23mm, OIS',
      ultrawideCamera: '50 MP, f/2.2, 14mm, 115˚',
      telephotoCamera: '50 MP 3.2x optical zoom, 75mm, OIS, 10cm floating macro',
      frontCamera: '32 MP, f/2.0, 4K60',
      videoRecording: '8K@24fps, 4K@24/30/60fps, Dolby Vision HDR',
      ois: true,
    },
    battery: {
      batteryCapacity: 4610,
      wiredCharging: 90,
      wirelessCharging: 50,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 3.2 Gen 1',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '152.8 x 71.5 x 8.2 mm',
      weight: 193,
      materials: 'Aluminum frame, glass back',
      waterResistance: 'IP68',
      colors: ['Black', 'White', 'Jade Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Xiaomi HyperOS',
      launchOS: 'Android 14',
      promisedMajorUpdates: 4,
      securityUpdatePolicy: '5 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/xiaomi-14/',
      productPage: 'https://store.mi.com/in/item/3241000002',
      specSheetUrl: 'https://www.mi.com/in/product/xiaomi-14/specs/',
      verifiedDate: '2024-03',
    },
  },

  {
    id: 'xiaomi-14-civi',
    slug: 'xiaomi-14-civi',
    brand: 'Xiaomi',
    modelName: 'Xiaomi 14 Civi',
    generation: '14 Civi',
    status: 'active',
    launchDate: '2024-06',
    pricing: {
      startingPrice: 39999,
      maximumPrice: 44999,
      launchPrice: 42999,
      currentPrice: 39999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.55,
      displayType: '1.5K 120Hz Floating Quad-Curve AMOLED',
      resolution: '2750 x 1236 pixels',
      refreshRate: 120,
      peakBrightness: 3000,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '90.4%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8s Gen 3 (4nm)',
      cpu: 'Octa-core (1x3.0 GHz Cortex-X4 & 4x2.8 GHz & 3x2.0 GHz)',
      gpu: 'Adreno 735',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 1510000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 12MP) Leica',
      mainCamera: '50 MP Light Hunter 800, f/1.63, OIS',
      ultrawideCamera: '12 MP, f/2.2, 120˚',
      telephotoCamera: '50 MP 2x portrait telephoto, f/1.98',
      frontCamera: 'Dual 32 MP (32 MP wide + 32 MP ultrawide 100˚)',
      videoRecording: '4K@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4700,
      wiredCharging: 67,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '157.2 x 72.8 x 7.45 mm',
      weight: 177,
      materials: 'Metal frame, vegan leather / glass back',
      waterResistance: 'Splash resistant',
      colors: ['Matcha Green', 'Cruise Blue', 'Shadow Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Xiaomi HyperOS',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/xiaomi-14-civi/',
      productPage: 'https://store.mi.com/in/item/3242400001',
      specSheetUrl: 'https://www.mi.com/in/product/xiaomi-14-civi/specs/',
      verifiedDate: '2024-06',
    },
  },

  {
    id: 'xiaomi-13-pro',
    slug: 'xiaomi-13-pro',
    brand: 'Xiaomi',
    modelName: 'Xiaomi 13 Pro',
    generation: '13',
    status: 'discontinued',
    launchDate: '2023-02',
    pricing: {
      startingPrice: 74999,
      maximumPrice: 79999,
      launchPrice: 79999,
      currentPrice: 74999,
      currency: 'INR',
      priceEffectiveDate: '2024-03',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.73,
      displayType: 'LTPO AMOLED, 1B colors, 120Hz, Dolby Vision, HDR10+',
      resolution: '3200 x 1440 pixels (WQHD+)',
      refreshRate: 120,
      peakBrightness: 1900,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass Victus',
      screenToBodyRatio: '89.6%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Gen 2 (4nm)',
      cpu: 'Octa-core (1x3.2 GHz Cortex-X3 & 4x2.8 GHz & 3x2.0 GHz)',
      gpu: 'Adreno 740',
      ramOptions: ['12GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 4.0',
      antutuScore: 1550000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50.3MP + 50MP + 50MP) Leica',
      mainCamera: '50.3 MP 1.0-type Sony IMX989, f/1.9, HyperOIS',
      ultrawideCamera: '50 MP, f/2.2, 115˚, AF',
      telephotoCamera: '50 MP 3.2x optical zoom, 75mm, floating telephoto, OIS',
      frontCamera: '32 MP, f/2.0',
      videoRecording: '8K@24fps, 4K@60fps, 10-bit Dolby Vision HDR',
      ois: true,
    },
    battery: {
      batteryCapacity: 4820,
      wiredCharging: 120,
      wirelessCharging: 50,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.9 x 74.6 x 8.38 mm',
      weight: 229,
      materials: 'Aluminum frame, bio-ceramic back',
      waterResistance: 'IP68',
      colors: ['Ceramic Black', 'Ceramic White'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MIUI 14 (upgradable to HyperOS)',
      launchOS: 'Android 13',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '5 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/xiaomi-13-pro/',
      productPage: 'https://store.mi.com/in/item/3230800001',
      specSheetUrl: 'https://www.mi.com/in/product/xiaomi-13-pro/specs/',
      verifiedDate: '2023-02',
    },
  },

  {
    id: 'xiaomi-12-pro',
    slug: 'xiaomi-12-pro',
    brand: 'Xiaomi',
    modelName: 'Xiaomi 12 Pro',
    generation: '12',
    status: 'discontinued',
    launchDate: '2022-04',
    pricing: {
      startingPrice: 44999,
      maximumPrice: 49999,
      launchPrice: 62999,
      currentPrice: 44999,
      currency: 'INR',
      priceEffectiveDate: '2023-12',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.73,
      displayType: 'LTPO AMOLED, 1B colors, 120Hz, Dolby Vision, HDR10+',
      resolution: '3200 x 1440 pixels (WQHD+)',
      refreshRate: 120,
      peakBrightness: 1500,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass Victus',
      screenToBodyRatio: '89.6%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Gen 1 (4nm)',
      cpu: 'Octa-core (1x3.00 GHz Cortex-X2 & 3x2.50 GHz & 4x1.80 GHz)',
      gpu: 'Adreno 730',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 1020000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 50MP)',
      mainCamera: '50 MP Sony IMX707, f/1.9, 24mm, OIS',
      ultrawideCamera: '50 MP, f/2.2, 115˚',
      telephotoCamera: '50 MP 2x optical zoom, 48mm, f/1.9',
      frontCamera: '32 MP, f/2.5',
      videoRecording: '8K@24fps, 4K@30/60fps, HDR10+',
      ois: true,
    },
    battery: {
      batteryCapacity: 4600,
      wiredCharging: 120,
      wirelessCharging: 50,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.2',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '163.6 x 74.6 x 8.16 mm',
      weight: 205,
      materials: 'Aluminum frame, Gorilla Glass Victus front, glass back',
      waterResistance: 'None',
      colors: ['Noir Black', 'Couture Blue', 'Opera Mauve'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MIUI 13 (upgradable to HyperOS)',
      launchOS: 'Android 12',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Quad stereo speakers tuned by Harman Kardon',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/xiaomi-12-pro/',
      productPage: 'https://store.mi.com/in/item/3221600001',
      specSheetUrl: 'https://www.mi.com/in/product/xiaomi-12-pro/specs/',
      verifiedDate: '2022-04',
    },
  },

  {
    id: 'xiaomi-11t-pro-5g',
    slug: 'xiaomi-11t-pro-5g',
    brand: 'Xiaomi',
    modelName: 'Xiaomi 11T Pro 5G',
    generation: '11T',
    status: 'discontinued',
    launchDate: '2022-01',
    pricing: {
      startingPrice: 34999,
      maximumPrice: 39999,
      launchPrice: 39999,
      currentPrice: 34999,
      currency: 'INR',
      priceEffectiveDate: '2023-06',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.67,
      displayType: '10-bit AMOLED, 120Hz, Dolby Vision, HDR10+',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1000,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass Victus',
      screenToBodyRatio: '85.1%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 888 5G (5nm)',
      cpu: 'Octa-core (1x2.84 GHz Cortex-X1 & 3x2.42 GHz & 4x1.80 GHz)',
      gpu: 'Adreno 660',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 820000,
    },
    cameras: {
      rearCameraSetup: 'Triple (108MP + 8MP + 5MP)',
      mainCamera: '108 MP Samsung HM2, f/1.75',
      ultrawideCamera: '8 MP, f/2.2, 120˚',
      telephotoCamera: '5 MP telemacro, f/2.4, 50mm, AF',
      frontCamera: '16 MP, f/2.45',
      videoRecording: '8K@30fps, 4K@30/60fps, HDR10+',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 120,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '164.1 x 76.9 x 8.8 mm',
      weight: 204,
      materials: 'Glass front (Victus), aluminum frame, glass back',
      waterResistance: 'IP53',
      colors: ['Meteorite Gray', 'Moonlight White', 'Celestial Blue'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MIUI 12.5 (upgradable to MIUI 14)',
      launchOS: 'Android 11',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers tuned by Harman Kardon',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/xiaomi-11t-pro-5g/',
      productPage: 'https://store.mi.com/in/item/3220300001',
      specSheetUrl: 'https://www.mi.com/in/product/xiaomi-11t-pro-5g/specs/',
      verifiedDate: '2022-01',
    },
  },

  {
    id: 'xiaomi-11-lite-ne-5g',
    slug: 'xiaomi-11-lite-ne-5g',
    brand: 'Xiaomi',
    modelName: 'Xiaomi 11 Lite NE 5G',
    generation: '11 Lite',
    status: 'discontinued',
    launchDate: '2021-09',
    pricing: {
      startingPrice: 23999,
      maximumPrice: 26999,
      launchPrice: 26999,
      currentPrice: 23999,
      currency: 'INR',
      priceEffectiveDate: '2022-12',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.55,
      displayType: '10-bit AMOLED, 90Hz, Dolby Vision, HDR10+',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 90,
      peakBrightness: 800,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass 6',
      screenToBodyRatio: '85.3%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 778G 5G (6nm)',
      cpu: 'Octa-core (4x2.4 GHz Kryo 670 & 4x1.8 GHz Kryo 670)',
      gpu: 'Adreno 642L',
      ramOptions: ['6GB', '8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 530000,
    },
    cameras: {
      rearCameraSetup: 'Triple (64MP + 8MP + 5MP)',
      mainCamera: '64 MP, f/1.79, 26mm',
      ultrawideCamera: '8 MP, f/2.2, 119˚',
      telephotoCamera: '5 MP telemacro, f/2.4, AF',
      frontCamera: '20 MP, f/2.24',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 4250,
      wiredCharging: 33,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.2',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '160.5 x 75.7 x 6.81 mm',
      weight: 158,
      materials: 'Gorilla Glass 6 front, magnesium alloy midframe, glass back',
      waterResistance: 'IP53',
      colors: ['Truffle Black', 'Bubblegum Blue', 'Peach Pink', 'Diamond Dazzle'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'MIUI 12.5 (upgradable to MIUI 14)',
      launchOS: 'Android 11',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/xiaomi-11-lite-ne-5g/',
      productPage: 'https://store.mi.com/in/item/3213900001',
      specSheetUrl: 'https://www.mi.com/in/product/xiaomi-11-lite-ne-5g/specs/',
      verifiedDate: '2021-09',
    },
  },
];

const variants: MobileVariant[] = [
  // Xiaomi 14 Ultra
  {
    id: 'xiaomi-14-ultra-16-512',
    modelId: 'xiaomi-14-ultra',
    ram: '16GB',
    storage: '512GB',
    price: 99999,
    mrp: 99999,
    colors: ['Black', 'White'],
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
  },
  // Xiaomi 14
  {
    id: 'xiaomi-14-12-512',
    modelId: 'xiaomi-14',
    ram: '12GB',
    storage: '512GB',
    price: 59999,
    mrp: 69999,
    colors: ['Black', 'White', 'Jade Green'],
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
  },
  // Xiaomi 14 Civi
  {
    id: 'xiaomi-14-civi-8-256',
    modelId: 'xiaomi-14-civi',
    ram: '8GB',
    storage: '256GB',
    price: 39999,
    mrp: 42999,
    colors: ['Matcha Green', 'Cruise Blue', 'Shadow Black'],
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
  },
  {
    id: 'xiaomi-14-civi-12-512',
    modelId: 'xiaomi-14-civi',
    ram: '12GB',
    storage: '512GB',
    price: 44999,
    mrp: 47999,
    colors: ['Matcha Green', 'Cruise Blue', 'Shadow Black'],
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
  },
  // Xiaomi 13 Pro
  {
    id: 'xiaomi-13-pro-12-256',
    modelId: 'xiaomi-13-pro',
    ram: '12GB',
    storage: '256GB',
    price: 74999,
    mrp: 79999,
    colors: ['Ceramic Black', 'Ceramic White'],
    status: 'discontinued',
    verified: true,
    source: 'Mi India Official Store',
  },
  // Xiaomi 12 Pro
  {
    id: 'xiaomi-12-pro-8-256',
    modelId: 'xiaomi-12-pro',
    ram: '8GB',
    storage: '256GB',
    price: 44999,
    mrp: 62999,
    colors: ['Noir Black', 'Couture Blue'],
    status: 'discontinued',
    verified: true,
    source: 'Mi India Official Store',
  },
  {
    id: 'xiaomi-12-pro-12-256',
    modelId: 'xiaomi-12-pro',
    ram: '12GB',
    storage: '256GB',
    price: 49999,
    mrp: 66999,
    colors: ['Noir Black', 'Couture Blue'],
    status: 'discontinued',
    verified: true,
    source: 'Mi India Official Store',
  },
  // Xiaomi 11T Pro 5G
  {
    id: 'xiaomi-11t-pro-5g-8-128',
    modelId: 'xiaomi-11t-pro-5g',
    ram: '8GB',
    storage: '128GB',
    price: 34999,
    mrp: 39999,
    colors: ['Meteorite Gray', 'Celestial Blue'],
    status: 'discontinued',
    verified: true,
    source: 'Mi India Official Store',
  },
  {
    id: 'xiaomi-11t-pro-5g-12-256',
    modelId: 'xiaomi-11t-pro-5g',
    ram: '12GB',
    storage: '256GB',
    price: 39999,
    mrp: 43999,
    colors: ['Meteorite Gray', 'Celestial Blue'],
    status: 'discontinued',
    verified: true,
    source: 'Mi India Official Store',
  },
  // Xiaomi 11 Lite NE 5G
  {
    id: 'xiaomi-11-lite-ne-5g-6-128',
    modelId: 'xiaomi-11-lite-ne-5g',
    ram: '6GB',
    storage: '128GB',
    price: 23999,
    mrp: 26999,
    colors: ['Truffle Black', 'Diamond Dazzle'],
    status: 'discontinued',
    verified: true,
    source: 'Mi India Official Store',
  },
  {
    id: 'xiaomi-11-lite-ne-5g-8-128',
    modelId: 'xiaomi-11-lite-ne-5g',
    ram: '8GB',
    storage: '128GB',
    price: 25999,
    mrp: 28999,
    colors: ['Truffle Black', 'Diamond Dazzle'],
    status: 'discontinued',
    verified: true,
    source: 'Mi India Official Store',
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    "modelId": "xiaomi-14-ultra",
    "modelName": "Xiaomi 14 Ultra",
    "brand": "Xiaomi",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14-ultra.jpg",
        "angle": "front",
        "source": "Xiaomi Official / GSMArena Verified",
        "sourceUrl": "https://www.mi.com/in/product/xiaomi-14-ultra/",
        "verified": true,
        "alt": "Xiaomi Xiaomi 14 Ultra official product photography"
      }
    ]
  },
  {
    "modelId": "xiaomi-14",
    "modelName": "Xiaomi 14",
    "brand": "Xiaomi",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14.jpg",
        "angle": "front",
        "source": "Xiaomi Official / GSMArena Verified",
        "sourceUrl": "https://www.mi.com/in/product/xiaomi-14/",
        "verified": true,
        "alt": "Xiaomi Xiaomi 14 official product photography"
      }
    ]
  },
  {
    "modelId": "xiaomi-14-civi",
    "modelName": "Xiaomi 14 Civi",
    "brand": "Xiaomi",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14-civi.jpg",
        "angle": "front",
        "source": "Xiaomi Official / GSMArena Verified",
        "sourceUrl": "https://www.mi.com/in/product/xiaomi-14-civi/",
        "verified": true,
        "alt": "Xiaomi Xiaomi 14 Civi official product photography"
      }
    ]
  },
  {
    "modelId": "xiaomi-13-pro",
    "modelName": "Xiaomi 13 Pro",
    "brand": "Xiaomi",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-13-pro-black.jpg",
        "angle": "front",
        "source": "Xiaomi Official / GSMArena Verified",
        "sourceUrl": "https://www.mi.com/in/product/xiaomi-13-pro/",
        "verified": true,
        "alt": "Xiaomi Xiaomi 13 Pro official product photography"
      }
    ]
  },
  {
    "modelId": "xiaomi-12-pro",
    "modelName": "Xiaomi 12 Pro",
    "brand": "Xiaomi",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-12-pro.jpg",
        "angle": "front",
        "source": "Xiaomi Official / GSMArena Verified",
        "sourceUrl": "https://www.mi.com/in/product/xiaomi-12-pro/",
        "verified": true,
        "alt": "Xiaomi Xiaomi 12 Pro official product photography"
      }
    ]
  },
  {
    "modelId": "xiaomi-11t-pro-5g",
    "modelName": "Xiaomi 11T Pro 5G",
    "brand": "Xiaomi",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-11t-pro.jpg",
        "angle": "front",
        "source": "Xiaomi Official / GSMArena Verified",
        "sourceUrl": "https://www.mi.com/in/product/xiaomi-11t-pro-5g/",
        "verified": true,
        "alt": "Xiaomi Xiaomi 11T Pro 5G official product photography"
      }
    ]
  },
  {
    "modelId": "xiaomi-11-lite-ne-5g",
    "modelName": "Xiaomi 11 Lite NE 5G",
    "brand": "Xiaomi",
    "verifiedCoverage": true,
    "images": [
      {
        "url": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-11-lite-5g-ne.jpg",
        "angle": "front",
        "source": "Xiaomi Official / GSMArena Verified",
        "sourceUrl": "https://www.mi.com/in/product/xiaomi-11-lite-ne-5g/",
        "verified": true,
        "alt": "Xiaomi Xiaomi 11 Lite NE 5G official product photography"
      }
    ]
  }
];

export const xiaomiBundle: MobileBrandBundle = {
  brand: 'Xiaomi',
  models,
  variants,
  images,
};
