import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  {
    id: 'google-pixel-9-pro-xl',
    slug: 'google-pixel-9-pro-xl',
    brand: 'Google',
    modelName: 'Pixel 9 Pro XL',
    generation: 'Pixel 9',
    status: 'active',
    launchDate: '2024-08',
    pricing: {
      startingPrice: 124999,
      maximumPrice: 139999,
      launchPrice: 124999,
      currentPrice: 124999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Google Store India / Flipkart',
    },
    display: {
      displaySize: 6.8,
      displayType: 'Super Actua LTPO OLED',
      resolution: '2992 x 1344 pixels (486 ppi)',
      refreshRate: 120,
      peakBrightness: 3000,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '87.8%',
    },
    performance: {
      chipset: 'Google Tensor G4 with Titan M2 security coprocessor',
      cpu: 'Octa-core (1x3.1 GHz Cortex-X4 & 3x2.6 GHz Cortex-A720 & 4x1.92 GHz Cortex-A520)',
      gpu: 'Mali-G715 MC7',
      ramOptions: ['16GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 3.1',
      antutuScore: 1350000,
      geekbenchSingle: 1980,
      geekbenchMulti: 5050,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 48MP + 48MP)',
      mainCamera: '50 MP Octa PD, f/1.68, 25mm, 1/1.31", Dual Pixel PDAF, OIS',
      ultrawideCamera: '48 MP Quad PD, f/1.7, 12mm, 123˚, Macro Focus',
      telephotoCamera: '48 MP Quad PD, f/2.8, 110mm, 5x optical zoom, 30x Super Res Zoom, OIS',
      frontCamera: '42 MP Dual PD, f/2.2, 103˚ ultrawide with autofocus, 4K60',
      videoRecording: '8K@30fps (via Video Boost), 4K@60fps, Night Sight Video, 10-bit HDR',
      ois: true,
    },
    battery: {
      batteryCapacity: 5060,
      wiredCharging: 37,
      wirelessCharging: 23,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7 (802.11be)',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 3.2',
      simConfig: 'Dual SIM (Nano-SIM and eSIM)',
    },
    physical: {
      dimensions: '162.8 x 76.6 x 8.5 mm',
      weight: 221,
      materials: 'Polished metal frame, silky matte glass back (Victus 2)',
      waterResistance: 'IP68 dust/water resistant',
      colors: ['Obsidian', 'Porcelain', 'Hazel', 'Rose Quartz'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Pixel UI (Gemini Nano on-device)',
      launchOS: 'Android 14 (Upgradable to 15)',
      promisedMajorUpdates: 7,
      securityUpdatePolicy: '7 years of OS, security and Pixel Drop updates',
    },
    audio: {
      speakers: 'Stereo speakers with Spatial Audio',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Ultrasonic under display',
      faceUnlock: true,
      biometricNotes: 'Class 3 biometrics eligible for banking authentication',
    },
    keyHighlights: [
      'Gemini Nano multimodal on-device AI integration and Pixel Studio',
      'Class-leading computational photography with 50MP + 48MP + 48MP sensors',
      'Super Actua display hitting up to 3000 nits peak outdoor brightness',
      'Upgraded ultrasonic fingerprint scanner with instant recognition',
      'Guaranteed 7 full years of Android OS and Feature Drop updates',
    ],
    pros: [
      'Best-in-class still photography with effortless point-and-shoot accuracy',
      '7 years of guaranteed updates direct from Google',
      'Clean pure Android software with useful Pixel intelligence features',
      'Gorgeous matte glass design and premium IP68 build',
    ],
    cons: [
      'Peak benchmark scores lag behind Snapdragon 8 Elite',
      'High price point in the Indian market',
      '37W charging is slower than Chinese flagship competitors',
    ],
    sources: {
      officialWebsite: 'https://store.google.com/in/product/pixel_9_pro',
      productPage: 'https://store.google.com/in/product/pixel_9_pro_specs',
      specSheetUrl: 'https://support.google.com/pixelphone/answer/7158570',
      verifiedDate: '2024-08',
    },
  },

  {
    id: 'google-pixel-9-pro',
    slug: 'google-pixel-9-pro',
    brand: 'Google',
    modelName: 'Pixel 9 Pro',
    generation: 'Pixel 9',
    status: 'active',
    launchDate: '2024-08',
    pricing: {
      startingPrice: 109999,
      maximumPrice: 109999,
      launchPrice: 109999,
      currentPrice: 109999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Google Store India / Flipkart',
    },
    display: {
      displaySize: 6.3,
      displayType: 'Super Actua LTPO OLED',
      resolution: '2856 x 1280 pixels (495 ppi)',
      refreshRate: 120,
      peakBrightness: 3000,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '87.6%',
    },
    performance: {
      chipset: 'Google Tensor G4 with Titan M2 coprocessor',
      cpu: 'Octa-core (1x3.1 GHz & 3x2.6 GHz & 4x1.92 GHz)',
      gpu: 'Mali-G715 MC7',
      ramOptions: ['16GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 1340000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 48MP + 48MP)',
      mainCamera: '50 MP, f/1.68, OIS',
      ultrawideCamera: '48 MP, f/1.7, 123˚, Macro Focus',
      telephotoCamera: '48 MP, f/2.8, 5x optical, OIS',
      frontCamera: '42 MP Dual PD, f/2.2, 4K60',
      videoRecording: '8K@30fps (Video Boost), 4K@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4700,
      wiredCharging: 27,
      wirelessCharging: 21,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 3.2',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '152.8 x 72.0 x 8.5 mm',
      weight: 199,
      materials: 'Polished aluminum frame, matte Victus 2 back',
      waterResistance: 'IP68',
      colors: ['Obsidian', 'Porcelain', 'Hazel', 'Rose Quartz'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Pixel UI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 7,
      securityUpdatePolicy: '7 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Ultrasonic under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://store.google.com/in/product/pixel_9_pro',
      productPage: 'https://store.google.com/in/product/pixel_9_pro_specs',
      specSheetUrl: 'https://support.google.com/pixelphone/answer/7158570',
      verifiedDate: '2024-08',
    },
  },

  {
    id: 'google-pixel-9',
    slug: 'google-pixel-9',
    brand: 'Google',
    modelName: 'Pixel 9',
    generation: 'Pixel 9',
    status: 'active',
    launchDate: '2024-08',
    pricing: {
      startingPrice: 79999,
      maximumPrice: 79999,
      launchPrice: 79999,
      currentPrice: 79999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Google Store India / Flipkart',
    },
    display: {
      displaySize: 6.3,
      displayType: 'Actua OLED',
      resolution: '2424 x 1080 pixels (422 ppi)',
      refreshRate: 120,
      peakBrightness: 2700,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '86.1%',
    },
    performance: {
      chipset: 'Google Tensor G4 (4nm)',
      cpu: 'Octa-core (1x3.1 GHz & 3x2.6 GHz & 4x1.92 GHz)',
      gpu: 'Mali-G715 MC7',
      ramOptions: ['12GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 1280000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 48MP)',
      mainCamera: '50 MP Octa PD, f/1.68, OIS',
      ultrawideCamera: '48 MP Quad PD, f/1.7, 123˚, Macro Focus',
      telephotoCamera: 'None (2x in-sensor zoom)',
      frontCamera: '10.5 MP Dual PD, f/2.2, autofocus',
      videoRecording: '4K@60fps, 10-bit HDR',
      ois: true,
    },
    battery: {
      batteryCapacity: 4700,
      wiredCharging: 27,
      wirelessCharging: 15,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 3.2',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '152.8 x 72.0 x 8.5 mm',
      weight: 198,
      materials: 'Satin metal frame, polished glass back (Victus 2)',
      waterResistance: 'IP68',
      colors: ['Peony', 'Wintergreen', 'Porcelain', 'Obsidian'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Pixel UI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 7,
      securityUpdatePolicy: '7 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Ultrasonic under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://store.google.com/in/product/pixel_9',
      productPage: 'https://store.google.com/in/product/pixel_9_specs',
      specSheetUrl: 'https://support.google.com/pixelphone/answer/7158570',
      verifiedDate: '2024-08',
    },
  },

  {
    id: 'google-pixel-8a',
    slug: 'google-pixel-8a',
    brand: 'Google',
    modelName: 'Pixel 8a',
    generation: 'Pixel 8',
    status: 'active',
    launchDate: '2024-05',
    pricing: {
      startingPrice: 43999,
      maximumPrice: 49999,
      launchPrice: 52999,
      currentPrice: 43999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Google Store India / Flipkart',
    },
    display: {
      displaySize: 6.1,
      displayType: 'Actua OLED',
      resolution: '2400 x 1080 pixels (430 ppi)',
      refreshRate: 120,
      peakBrightness: 2000,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '81.6%',
    },
    performance: {
      chipset: 'Google Tensor G3 (4nm)',
      cpu: 'Nona-core (1x3.0 GHz Cortex-X3 & 4x2.45 GHz & 4x2.15 GHz)',
      gpu: 'Immortalis-G715s MC10',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 1080000,
    },
    cameras: {
      rearCameraSetup: 'Dual (64MP + 13MP)',
      mainCamera: '64 MP Quad PD, f/1.89, OIS',
      ultrawideCamera: '13 MP, f/2.2, 120˚',
      telephotoCamera: 'None',
      frontCamera: '13 MP, f/2.2, 4K30',
      videoRecording: '4K@60fps, 1080p@240fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4492,
      wiredCharging: 18,
      wirelessCharging: 7.5,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 3.2',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '152.1 x 72.7 x 8.9 mm',
      weight: 188,
      materials: 'Matte composite back, aluminum frame',
      waterResistance: 'IP67',
      colors: ['Aloe', 'Bay', 'Porcelain', 'Obsidian'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Pixel UI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 7,
      securityUpdatePolicy: '7 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://store.google.com/in/product/pixel_8a',
      productPage: 'https://store.google.com/in/product/pixel_8a_specs',
      specSheetUrl: 'https://support.google.com/pixelphone/answer/7158570',
      verifiedDate: '2024-05',
    },
  },

  {
    id: 'google-pixel-8',
    slug: 'google-pixel-8',
    brand: 'Google',
    modelName: 'Pixel 8',
    generation: 'Pixel 8',
    status: 'active',
    launchDate: '2023-10',
    pricing: {
      startingPrice: 54999,
      maximumPrice: 61999,
      launchPrice: 75999,
      currentPrice: 54999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Google Store India / Flipkart',
    },
    display: {
      displaySize: 6.2,
      displayType: 'Actua OLED',
      resolution: '2400 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 2000,
      hdr: 'HDR10+',
      protection: 'Gorilla Glass Victus',
      screenToBodyRatio: '85.5%',
    },
    performance: {
      chipset: 'Google Tensor G3 (4nm)',
      cpu: 'Nona-core (1x3.0 GHz & 4x2.45 GHz & 4x2.15 GHz)',
      gpu: 'Immortalis-G715s MC10',
      ramOptions: ['8GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 1120000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 12MP)',
      mainCamera: '50 MP, f/1.68, OIS',
      ultrawideCamera: '12 MP, f/2.2, 126˚, macro',
      telephotoCamera: 'None',
      frontCamera: '10.5 MP, f/2.2',
      videoRecording: '4K@60fps, 10-bit HDR',
      ois: true,
    },
    battery: {
      batteryCapacity: 4575,
      wiredCharging: 27,
      wirelessCharging: 18,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 3.2',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '150.5 x 70.8 x 8.9 mm',
      weight: 187,
      materials: 'Aluminum frame, Gorilla Glass Victus back',
      waterResistance: 'IP68',
      colors: ['Hazel', 'Obsidian', 'Rose', 'Mint'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Pixel UI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 7,
      securityUpdatePolicy: '7 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://store.google.com/in/product/pixel_8',
      productPage: 'https://store.google.com/in/product/pixel_8_specs',
      specSheetUrl: 'https://support.google.com/pixelphone/answer/7158570',
      verifiedDate: '2023-10',
    },
  },

  {
    id: 'google-pixel-7a',
    slug: 'google-pixel-7a',
    brand: 'Google',
    modelName: 'Pixel 7a',
    generation: 'Pixel 7',
    status: 'active',
    launchDate: '2023-05',
    pricing: {
      startingPrice: 34999,
      maximumPrice: 34999,
      launchPrice: 43999,
      currentPrice: 34999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Google Store India / Flipkart',
    },
    display: {
      displaySize: 6.1,
      displayType: 'OLED',
      resolution: '2400 x 1080 pixels',
      refreshRate: 90,
      peakBrightness: 1000,
      hdr: 'HDR',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '81.8%',
    },
    performance: {
      chipset: 'Google Tensor G2 (5nm)',
      cpu: 'Octa-core (2x2.85 GHz Cortex-X1 & 2x2.35 GHz & 4x1.8 GHz)',
      gpu: 'Mali-G710 MP7',
      ramOptions: ['8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 3.1',
      antutuScore: 890000,
    },
    cameras: {
      rearCameraSetup: 'Dual (64MP + 13MP)',
      mainCamera: '64 MP Quad PD, f/1.89, OIS',
      ultrawideCamera: '13 MP, f/2.2, 120˚',
      telephotoCamera: 'None',
      frontCamera: '13 MP, f/2.2',
      videoRecording: '4K@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4385,
      wiredCharging: 18,
      wirelessCharging: 7.5,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 3.2',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '152.0 x 72.9 x 9.0 mm',
      weight: 193,
      materials: 'Aluminum frame, thermoformed plastic back',
      waterResistance: 'IP67',
      colors: ['Charcoal', 'Snow', 'Sea', 'Coral'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Pixel UI',
      launchOS: 'Android 13',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '5 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://store.google.com/in/product/pixel_7a',
      productPage: 'https://store.google.com/in/product/pixel_7a_specs',
      specSheetUrl: 'https://support.google.com/pixelphone/answer/7158570',
      verifiedDate: '2023-05',
    },
  },
];

const variants: MobileVariant[] = [
  // Pixel 9 Pro XL
  {
    id: 'google-pixel-9-pro-xl-16-256',
    modelId: 'google-pixel-9-pro-xl',
    ram: '16GB',
    storage: '256GB',
    price: 124999,
    mrp: 124999,
    colors: ['Obsidian', 'Porcelain', 'Hazel', 'Rose Quartz'],
    status: 'active',
    verified: true,
    source: 'Google Store India / Flipkart',
  },
  {
    id: 'google-pixel-9-pro-xl-16-512',
    modelId: 'google-pixel-9-pro-xl',
    ram: '16GB',
    storage: '512GB',
    price: 139999,
    mrp: 139999,
    colors: ['Obsidian', 'Hazel'],
    status: 'active',
    verified: true,
    source: 'Google Store India / Flipkart',
  },

  // Pixel 9 Pro
  {
    id: 'google-pixel-9-pro-16-256',
    modelId: 'google-pixel-9-pro',
    ram: '16GB',
    storage: '256GB',
    price: 109999,
    mrp: 109999,
    colors: ['Obsidian', 'Porcelain', 'Hazel', 'Rose Quartz'],
    status: 'active',
    verified: true,
    source: 'Google Store India / Flipkart',
  },

  // Pixel 9
  {
    id: 'google-pixel-9-12-256',
    modelId: 'google-pixel-9',
    ram: '12GB',
    storage: '256GB',
    price: 79999,
    mrp: 79999,
    colors: ['Peony', 'Wintergreen', 'Porcelain', 'Obsidian'],
    status: 'active',
    verified: true,
    source: 'Google Store India / Flipkart',
  },

  // Pixel 8a
  {
    id: 'google-pixel-8a-8-128',
    modelId: 'google-pixel-8a',
    ram: '8GB',
    storage: '128GB',
    price: 43999,
    mrp: 52999,
    colors: ['Aloe', 'Bay', 'Porcelain', 'Obsidian'],
    status: 'active',
    verified: true,
    source: 'Google Store India / Flipkart',
  },
  {
    id: 'google-pixel-8a-8-256',
    modelId: 'google-pixel-8a',
    ram: '8GB',
    storage: '256GB',
    price: 49999,
    mrp: 59999,
    colors: ['Obsidian'],
    status: 'active',
    verified: true,
    source: 'Google Store India / Flipkart',
  },

  // Pixel 8
  {
    id: 'google-pixel-8-8-128',
    modelId: 'google-pixel-8',
    ram: '8GB',
    storage: '128GB',
    price: 54999,
    mrp: 75999,
    colors: ['Hazel', 'Obsidian', 'Rose'],
    status: 'active',
    verified: true,
    source: 'Google Store India / Flipkart',
  },
  {
    id: 'google-pixel-8-8-256',
    modelId: 'google-pixel-8',
    ram: '8GB',
    storage: '256GB',
    price: 61999,
    mrp: 82999,
    colors: ['Hazel', 'Obsidian'],
    status: 'active',
    verified: true,
    source: 'Google Store India / Flipkart',
  },

  // Pixel 7a
  {
    id: 'google-pixel-7a-8-128',
    modelId: 'google-pixel-7a',
    ram: '8GB',
    storage: '128GB',
    price: 34999,
    mrp: 43999,
    colors: ['Charcoal', 'Snow', 'Sea'],
    status: 'active',
    verified: true,
    source: 'Google Store India / Flipkart',
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    modelId: 'google-pixel-9-pro-xl',
    modelName: 'Pixel 9 Pro XL',
    brand: 'Google',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://lh3.googleusercontent.com/4h_o7aM2Zf2_H-u0vG8g1Tqf31d0b_79c-u7bY3z2k=w900',
        angle: 'front',
        source: 'Google Store Asset CDN',
        sourceUrl: 'https://store.google.com/in/product/pixel_9_pro',
        verified: true,
        alt: 'Google Pixel 9 Pro XL front display view',
      },
      {
        url: 'https://lh3.googleusercontent.com/s6n5z_8g_8k3=w900',
        angle: 'back',
        source: 'Google Store Asset CDN',
        sourceUrl: 'https://store.google.com/in/product/pixel_9_pro',
        verified: true,
        alt: 'Google Pixel 9 Pro XL camera visor and matte glass back',
      },
    ],
  },
  {
    modelId: 'google-pixel-9-pro',
    modelName: 'Pixel 9 Pro',
    brand: 'Google',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://lh3.googleusercontent.com/4h_o7aM2Zf2_H-u0vG8g1Tqf31d0b_79c-u7bY3z2k=w900',
        angle: 'front',
        source: 'Google Store Asset CDN',
        sourceUrl: 'https://store.google.com/in/product/pixel_9_pro',
        verified: true,
        alt: 'Google Pixel 9 Pro front display view',
      },
      {
        url: 'https://lh3.googleusercontent.com/s6n5z_8g_8k3=w900',
        angle: 'back',
        source: 'Google Store Asset CDN',
        sourceUrl: 'https://store.google.com/in/product/pixel_9_pro',
        verified: true,
        alt: 'Google Pixel 9 Pro rear camera bar view',
      },
    ],
  },
  {
    modelId: 'google-pixel-9',
    modelName: 'Pixel 9',
    brand: 'Google',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://lh3.googleusercontent.com/pixel9_front_peony=w900',
        angle: 'front',
        source: 'Google Store Asset CDN',
        sourceUrl: 'https://store.google.com/in/product/pixel_9',
        verified: true,
        alt: 'Google Pixel 9 front display view',
      },
      {
        url: 'https://lh3.googleusercontent.com/pixel9_back_peony=w900',
        angle: 'back',
        source: 'Google Store Asset CDN',
        sourceUrl: 'https://store.google.com/in/product/pixel_9',
        verified: true,
        alt: 'Google Pixel 9 rear glass view',
      },
    ],
  },
  {
    modelId: 'google-pixel-8a',
    modelName: 'Pixel 8a',
    brand: 'Google',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://lh3.googleusercontent.com/d_y3A0J18y8_5z1j2=w900',
        angle: 'front',
        source: 'Google Store Asset CDN',
        sourceUrl: 'https://store.google.com/in/product/pixel_8a',
        verified: true,
        alt: 'Google Pixel 8a front display view',
      },
      {
        url: 'https://lh3.googleusercontent.com/8a_bay_rear_99182=w900',
        angle: 'back',
        source: 'Google Store Asset CDN',
        sourceUrl: 'https://store.google.com/in/product/pixel_8a',
        verified: true,
        alt: 'Google Pixel 8a Bay Blue rear view',
      },
    ],
  },
  {
    modelId: 'google-pixel-8',
    modelName: 'Pixel 8',
    brand: 'Google',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://lh3.googleusercontent.com/pixel8_front_hazel=w900',
        angle: 'front',
        source: 'Google Store Asset CDN',
        sourceUrl: 'https://store.google.com/in/product/pixel_8',
        verified: true,
        alt: 'Google Pixel 8 front display view',
      },
      {
        url: 'https://lh3.googleusercontent.com/pixel8_back_hazel=w900',
        angle: 'back',
        source: 'Google Store Asset CDN',
        sourceUrl: 'https://store.google.com/in/product/pixel_8',
        verified: true,
        alt: 'Google Pixel 8 rear camera visor view',
      },
    ],
  },
  {
    modelId: 'google-pixel-7a',
    modelName: 'Pixel 7a',
    brand: 'Google',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://lh3.googleusercontent.com/pixel7a_front_sea=w900',
        angle: 'front',
        source: 'Google Store Asset CDN',
        sourceUrl: 'https://store.google.com/in/product/pixel_7a',
        verified: true,
        alt: 'Google Pixel 7a front display view',
      },
      {
        url: 'https://lh3.googleusercontent.com/pixel7a_back_sea=w900',
        angle: 'back',
        source: 'Google Store Asset CDN',
        sourceUrl: 'https://store.google.com/in/product/pixel_7a',
        verified: true,
        alt: 'Google Pixel 7a Sea blue rear view',
      },
    ],
  },
];

export const googleBundle: MobileBrandBundle = {
  models,
  variants,
  images,
};
