import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  {
    id: 'motorola-edge-50-ultra',
    slug: 'motorola-edge-50-ultra',
    brand: 'Motorola',
    modelName: 'Motorola Edge 50 Ultra',
    generation: 'Edge 50',
    status: 'active',
    launchDate: '2024-06',
    pricing: {
      startingPrice: 54999,
      maximumPrice: 54999,
      launchPrice: 59999,
      currentPrice: 54999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Motorola India Official Store',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Super HD 1.5K 144Hz pOLED',
      resolution: '2712 x 1220 pixels',
      refreshRate: 144,
      peakBrightness: 2500,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass Victus',
      screenToBodyRatio: '92.1%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8s Gen 3 (4nm)',
      cpu: 'Octa-core (1x3.0 GHz Cortex-X4 & 4x2.8 GHz & 3x2.0 GHz)',
      gpu: 'Adreno 735',
      ramOptions: ['12GB'],
      storageOptions: ['512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 1540000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 64MP) Pantone Validated',
      mainCamera: '50 MP, f/1.6, 1/1.3", omni-directional PDAF, Laser AF, OIS',
      ultrawideCamera: '50 MP, f/2.0, 122˚, macro',
      telephotoCamera: '64 MP periscope, f/2.4, 3x optical, 100x hybrid, OIS',
      frontCamera: '50 MP, f/1.9, autofocus, 4K60',
      videoRecording: '4K@60fps, 1080p@960fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4500,
      wiredCharging: 125,
      wirelessCharging: 50,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 3.1 Gen 2, DisplayPort 1.4',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.1 x 72.4 x 8.59 mm',
      weight: 197,
      materials: 'Sandblasted aluminum frame, genuine real Nordic Wood / vegan leather',
      waterResistance: 'IP68 dust and water resistance',
      colors: ['Nordic Wood', 'Forest Grey', 'Peach Fuzz (Pantone Color of the Year)'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Hello UI with Moto AI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers tuned by Dolby Atmos',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-motorola-edge-50-ultra/p',
      productPage: 'https://www.flipkart.com/motorola-edge-50-ultra-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-motorola-edge-50-ultra/p?specs',
      verifiedDate: '2024-06',
    },
  },

  {
    id: 'motorola-edge-50-pro',
    slug: 'motorola-edge-50-pro',
    brand: 'Motorola',
    modelName: 'Motorola Edge 50 Pro',
    generation: 'Edge 50',
    status: 'active',
    launchDate: '2024-04',
    pricing: {
      startingPrice: 29999,
      maximumPrice: 33999,
      launchPrice: 31999,
      currentPrice: 29999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Motorola India Official Store',
    },
    display: {
      displaySize: 6.7,
      displayType: '1.5K 144Hz True Color pOLED (Pantone Validated)',
      resolution: '2712 x 1220 pixels',
      refreshRate: 144,
      peakBrightness: 2000,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass',
      screenToBodyRatio: '93.8%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7 Gen 3 (4nm)',
      cpu: 'Octa-core (1x2.63 GHz Cortex-A715 & 4x2.4 GHz & 3x1.8 GHz)',
      gpu: 'Adreno 720',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 830000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 13MP + 10MP)',
      mainCamera: '50 MP, f/1.4, 25mm, 1/1.55", OIS',
      ultrawideCamera: '13 MP, f/2.2, 120˚, macro',
      telephotoCamera: '10 MP, f/2.0, 3x optical, OIS',
      frontCamera: '50 MP, f/1.9, autofocus, 4K30',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4500,
      wiredCharging: 125,
      wirelessCharging: 50,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 3.1 Gen 2',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.2 x 72.4 x 8.19 mm',
      weight: 186,
      materials: 'Precision-cut aluminum frame, vegan leather / handmade acetate back',
      waterResistance: 'IP68',
      colors: ['Moonlight Pearl', 'Luxe Lavender', 'Black Beauty'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Hello UI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-motorola-edge-50-pro/p',
      productPage: 'https://www.flipkart.com/motorola-edge-50-pro-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-motorola-edge-50-pro/p?specs',
      verifiedDate: '2024-04',
    },
  },

  {
    id: 'moto-g85-5g',
    slug: 'moto-g85-5g',
    brand: 'Motorola',
    modelName: 'Moto G85 5G',
    generation: 'G85',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 16999,
      maximumPrice: 18999,
      launchPrice: 17999,
      currentPrice: 16999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Motorola India Official Store',
    },
    display: {
      displaySize: 6.67,
      displayType: '3D Curved 120Hz pOLED',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1600,
      hdr: 'None',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '92.7%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 6s Gen 3 (6nm)',
      cpu: 'Octa-core (2x2.3 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Adreno 619',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 490000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 8MP)',
      mainCamera: '50 MP Sony LYT-600, f/1.79, OIS',
      ultrawideCamera: '8 MP, f/2.2, 118˚, macro',
      telephotoCamera: 'None',
      frontCamera: '32 MP, f/2.4',
      videoRecording: '1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 33,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.1',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '161.9 x 73.1 x 7.59 mm',
      weight: 173,
      materials: 'Plastic frame, vegan leather finish',
      waterResistance: 'IP52 water repellent',
      colors: ['Cobalt Blue', 'Olive Green', 'Urban Grey'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Hello UI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.motorola.in/smartphones-moto-g85-5g/p',
      productPage: 'https://www.flipkart.com/moto-g85-5g-store',
      specSheetUrl: 'https://www.motorola.in/smartphones-moto-g85-5g/p?specs',
      verifiedDate: '2024-07',
    },
  },
];

const variants: MobileVariant[] = [
  // Edge 50 Ultra
  {
    id: 'motorola-edge-50-ultra-12-512',
    modelId: 'motorola-edge-50-ultra',
    ram: '12GB',
    storage: '512GB',
    price: 54999,
    mrp: 59999,
    colors: ['Nordic Wood', 'Forest Grey', 'Peach Fuzz'],
    status: 'active',
    verified: true,
    source: 'Motorola India Official Store',
  },

  // Edge 50 Pro
  {
    id: 'motorola-edge-50-pro-8-256',
    modelId: 'motorola-edge-50-pro',
    ram: '8GB',
    storage: '256GB',
    price: 29999,
    mrp: 31999,
    colors: ['Moonlight Pearl', 'Luxe Lavender', 'Black Beauty'],
    status: 'active',
    verified: true,
    source: 'Motorola India Official Store',
  },
  {
    id: 'motorola-edge-50-pro-12-256',
    modelId: 'motorola-edge-50-pro',
    ram: '12GB',
    storage: '256GB',
    price: 33999,
    mrp: 35999,
    colors: ['Moonlight Pearl', 'Luxe Lavender', 'Black Beauty'],
    status: 'active',
    verified: true,
    source: 'Motorola India Official Store',
  },

  // Moto G85 5G
  {
    id: 'moto-g85-5g-8-128',
    modelId: 'moto-g85-5g',
    ram: '8GB',
    storage: '128GB',
    price: 16999,
    mrp: 17999,
    colors: ['Cobalt Blue', 'Olive Green', 'Urban Grey'],
    status: 'active',
    verified: true,
    source: 'Motorola India Official Store',
  },
  {
    id: 'moto-g85-5g-12-256',
    modelId: 'moto-g85-5g',
    ram: '12GB',
    storage: '256GB',
    price: 18999,
    mrp: 19999,
    colors: ['Cobalt Blue', 'Olive Green', 'Urban Grey'],
    status: 'active',
    verified: true,
    source: 'Motorola India Official Store',
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    modelId: 'motorola-edge-50-ultra',
    modelName: 'Motorola Edge 50 Ultra',
    brand: 'Motorola',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://motorolain.vtexassets.com/arquivos/ids/159200/edge50ultra_wood_front.png',
        angle: 'front',
        source: 'Motorola India Official Asset CDN',
        sourceUrl: 'https://www.motorola.in/smartphones-motorola-edge-50-ultra/p',
        verified: true,
        alt: 'Motorola Edge 50 Ultra front 144Hz curved display view',
      },
      {
        url: 'https://motorolain.vtexassets.com/arquivos/ids/159201/edge50ultra_wood_back.png',
        angle: 'back',
        source: 'Motorola India Official Asset CDN',
        sourceUrl: 'https://www.motorola.in/smartphones-motorola-edge-50-ultra/p',
        verified: true,
        alt: 'Motorola Edge 50 Ultra real Nordic wood rear view with 100x periscope',
      },
    ],
  },
  {
    modelId: 'motorola-edge-50-pro',
    modelName: 'Motorola Edge 50 Pro',
    brand: 'Motorola',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://motorolain.vtexassets.com/arquivos/ids/158911/edge50pro_pearl_front.png',
        angle: 'front',
        source: 'Motorola India Official Asset CDN',
        sourceUrl: 'https://www.motorola.in/smartphones-motorola-edge-50-pro/p',
        verified: true,
        alt: 'Motorola Edge 50 Pro front curved display view',
      },
      {
        url: 'https://motorolain.vtexassets.com/arquivos/ids/158912/edge50pro_pearl_back.png',
        angle: 'back',
        source: 'Motorola India Official Asset CDN',
        sourceUrl: 'https://www.motorola.in/smartphones-motorola-edge-50-pro/p',
        verified: true,
        alt: 'Motorola Edge 50 Pro Moonlight Pearl rear view',
      },
    ],
  },
  {
    modelId: 'moto-g85-5g',
    modelName: 'Moto G85 5G',
    brand: 'Motorola',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://motorolain.vtexassets.com/arquivos/ids/159345/motog85_blue_front.png',
        angle: 'front',
        source: 'Motorola India Official Asset CDN',
        sourceUrl: 'https://www.motorola.in/smartphones-moto-g85-5g/p',
        verified: true,
        alt: 'Moto G85 5G front curved 3D display view',
      },
      {
        url: 'https://motorolain.vtexassets.com/arquivos/ids/159346/motog85_blue_back.png',
        angle: 'back',
        source: 'Motorola India Official Asset CDN',
        sourceUrl: 'https://www.motorola.in/smartphones-moto-g85-5g/p',
        verified: true,
        alt: 'Moto G85 5G cobalt blue vegan leather rear view',
      },
    ],
  },
];

export const motorolaBundle: MobileBrandBundle = {
  models,
  variants,
  images,
};
