import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  // ── NOTHING ──
  {
    id: 'nothing-phone-2',
    slug: 'nothing-phone-2',
    brand: 'Nothing',
    modelName: 'Nothing Phone (2)',
    generation: 'Phone (2)',
    status: 'active',
    launchDate: '2023-07',
    pricing: {
      startingPrice: 36999,
      maximumPrice: 44999,
      launchPrice: 44999,
      currentPrice: 36999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Nothing India / Flipkart',
    },
    display: {
      displaySize: 6.7,
      displayType: 'LTPO OLED',
      resolution: '2412 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1600,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass',
      screenToBodyRatio: '87.2%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8+ Gen 1 (4nm)',
      cpu: 'Octa-core (1x3.0 GHz Cortex-X2 & 3x2.5 GHz & 4x1.8 GHz)',
      gpu: 'Adreno 730',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB', '512GB'],
      storageType: 'UFS 3.1',
      antutuScore: 1290000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 50MP) with Glyph Interface',
      mainCamera: '50 MP Sony IMX890, f/1.88, 1/1.56", OIS',
      ultrawideCamera: '50 MP Samsung JN1, f/2.2, 114˚',
      telephotoCamera: 'None',
      frontCamera: '32 MP Sony IMX615, f/2.45, 1080p@60fps',
      videoRecording: '4K@60fps, Live HDR',
      ois: true,
    },
    battery: {
      batteryCapacity: 4700,
      wiredCharging: 45,
      wirelessCharging: 15,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.1 x 76.4 x 8.6 mm',
      weight: 201.2,
      materials: '100% recycled aluminum midframe, transparent pillowed glass back with 33 Glyph LED zones',
      waterResistance: 'IP54 splash resistant',
      colors: ['Dark Grey', 'White'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Nothing OS 2.6 (Upgradable to 3.0)',
      launchOS: 'Android 13',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://in.nothing.tech/pages/phone-2',
      productPage: 'https://in.nothing.tech/products/phone-2',
      specSheetUrl: 'https://in.nothing.tech/pages/phone-2-specs',
      verifiedDate: '2023-07',
    },
  },

  {
    id: 'nothing-phone-2a-plus',
    slug: 'nothing-phone-2a-plus',
    brand: 'Nothing',
    modelName: 'Nothing Phone (2a) Plus',
    generation: 'Phone (2a)',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 27999,
      maximumPrice: 29999,
      launchPrice: 27999,
      currentPrice: 27999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Nothing India / Flipkart',
    },
    display: {
      displaySize: 6.7,
      displayType: 'Flexible 120Hz AMOLED',
      resolution: '2412 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 1300,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '91.65%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7350 Pro 5G (4nm co-engineered)',
      cpu: 'Octa-core (2x3.0 GHz Cortex-A715 & 6x2.0 GHz Cortex-A510)',
      gpu: 'Mali-G615 MC2',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 805000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 50MP)',
      mainCamera: '50 MP Samsung GN9, f/1.88, OIS',
      ultrawideCamera: '50 MP Samsung JN1, f/2.2, 114˚',
      telephotoCamera: 'None',
      frontCamera: '50 MP Samsung JN1, f/2.2, 4K30',
      videoRecording: '4K@30fps, 1080p@120fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 50,
      wirelessCharging: 0,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.7 x 76.3 x 8.5 mm',
      weight: 190,
      materials: 'Metallic sheen transparent plastic back with Glyph Trio lighting',
      waterResistance: 'IP54',
      colors: ['Metallic Grey', 'Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Nothing OS 2.6',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://in.nothing.tech/pages/phone-2a-plus',
      productPage: 'https://in.nothing.tech/products/phone-2a-plus',
      specSheetUrl: 'https://in.nothing.tech/pages/phone-2a-plus-specs',
      verifiedDate: '2024-07',
    },
  },

  {
    id: 'cmf-phone-1',
    slug: 'cmf-phone-1',
    brand: 'CMF',
    modelName: 'CMF Phone 1',
    generation: 'Phone 1',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 15999,
      maximumPrice: 17999,
      launchPrice: 15999,
      currentPrice: 15999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'CMF by Nothing India / Flipkart',
    },
    display: {
      displaySize: 6.67,
      displayType: 'Super AMOLED 120Hz',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 120,
      peakBrightness: 2000,
      hdr: 'Ultra HDR',
      protection: 'Glass front',
      screenToBodyRatio: '87.0%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 7300 5G (4nm)',
      cpu: 'Octa-core (4x2.5 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G615 MC2',
      ramOptions: ['6GB', '8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 665000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 2MP)',
      mainCamera: '50 MP Sony, f/1.8',
      ultrawideCamera: 'None',
      telephotoCamera: 'None (2 MP portrait)',
      frontCamera: '16 MP, f/2.0',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 33,
      wirelessCharging: 0,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '164.0 x 77.0 x 8.0 mm (Standard) / 9.0 mm (Vegan Leather)',
      weight: 197,
      materials: 'Modular interchangeable back cover with accessory point (stand/lanyard/card case)',
      waterResistance: 'IP52',
      colors: ['Black', 'Orange (Vegan Leather)', 'Light Green', 'Blue'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Nothing OS 2.6 (CMF Edition)',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Single bottom speaker',
      stereo: false,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://in.nothing.tech/pages/cmf-phone-1',
      productPage: 'https://in.nothing.tech/products/cmf-phone-1',
      specSheetUrl: 'https://in.nothing.tech/pages/cmf-phone-1-specs',
      verifiedDate: '2024-07',
    },
  },

  // ── ASUS ──
  {
    id: 'asus-rog-phone-8-pro',
    slug: 'asus-rog-phone-8-pro',
    brand: 'ASUS',
    modelName: 'ROG Phone 8 Pro',
    generation: 'ROG 8',
    status: 'active',
    launchDate: '2024-01',
    pricing: {
      startingPrice: 94999,
      maximumPrice: 119999,
      launchPrice: 94999,
      currentPrice: 94999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'ASUS India / Vijay Sales',
    },
    display: {
      displaySize: 6.78,
      displayType: 'Samsung E6 165Hz Flexible LTPO AMOLED',
      resolution: '2400 x 1080 pixels (FHD+)',
      refreshRate: 165,
      peakBrightness: 2500,
      hdr: 'HDR10',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '94.0%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Gen 3 (4nm)',
      cpu: 'Octa-core (1x3.3 GHz Cortex-X4 & 5x3.2 GHz & 2x2.3 GHz)',
      gpu: 'Adreno 750',
      ramOptions: ['16GB', '24GB'],
      storageOptions: ['512GB', '1TB'],
      storageType: 'UFS 4.0',
      antutuScore: 2210000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 32MP + 13MP) with 6-Axis Hybrid Gimbal Stabilizer',
      mainCamera: '50 MP Sony IMX890, f/1.9, 6-Axis Hybrid Gimbal Stabilizer 3.0',
      ultrawideCamera: '13 MP, f/2.2, 120˚ free-form lens',
      telephotoCamera: '32 MP, f/2.4, 3x optical zoom, OIS',
      frontCamera: '32 MP RGBW, f/2.05',
      videoRecording: '8K@24fps, 4K@60fps with Gimbal EIS',
      ois: true,
    },
    battery: {
      batteryCapacity: 5500,
      wiredCharging: 65,
      wirelessCharging: 15,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'Dual USB Type-C (Side-mounted USB 3.1 DP + Bottom USB 2.0)',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '163.8 x 76.8 x 8.9 mm',
      weight: 225,
      materials: 'Aluminum frame, AniMe Vision 341 mini-LED programmable matrix back',
      waterResistance: 'IP68 certified gaming flagship',
      colors: ['Phantom Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'ROG UI / Zen UI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual front-facing 5-magnet stereo speakers with Dirac Virtuo',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://rog.asus.com/in/phones/rog-phone-8-pro/',
      productPage: 'https://in.store.asus.com/rog-phone-8-pro',
      specSheetUrl: 'https://rog.asus.com/in/phones/rog-phone-8-pro/spec/',
      verifiedDate: '2024-01',
    },
  },
];

const variants: MobileVariant[] = [
  // Nothing Phone (2)
  {
    id: 'nothing-phone-2-8-128',
    modelId: 'nothing-phone-2',
    ram: '8GB',
    storage: '128GB',
    price: 36999,
    mrp: 44999,
    colors: ['Dark Grey', 'White'],
    status: 'active',
    verified: true,
    source: 'Nothing India / Flipkart',
  },
  {
    id: 'nothing-phone-2-12-256',
    modelId: 'nothing-phone-2',
    ram: '12GB',
    storage: '256GB',
    price: 39999,
    mrp: 49999,
    colors: ['Dark Grey', 'White'],
    status: 'active',
    verified: true,
    source: 'Nothing India / Flipkart',
  },
  {
    id: 'nothing-phone-2-12-512',
    modelId: 'nothing-phone-2',
    ram: '12GB',
    storage: '512GB',
    price: 44999,
    mrp: 54999,
    colors: ['Dark Grey', 'White'],
    status: 'active',
    verified: true,
    source: 'Nothing India / Flipkart',
  },

  // Nothing Phone (2a) Plus
  {
    id: 'nothing-phone-2a-plus-8-256',
    modelId: 'nothing-phone-2a-plus',
    ram: '8GB',
    storage: '256GB',
    price: 27999,
    mrp: 27999,
    colors: ['Metallic Grey', 'Black'],
    status: 'active',
    verified: true,
    source: 'Nothing India / Flipkart',
  },
  {
    id: 'nothing-phone-2a-plus-12-256',
    modelId: 'nothing-phone-2a-plus',
    ram: '12GB',
    storage: '256GB',
    price: 29999,
    mrp: 29999,
    colors: ['Metallic Grey', 'Black'],
    status: 'active',
    verified: true,
    source: 'Nothing India / Flipkart',
  },

  // CMF Phone 1
  {
    id: 'cmf-phone-1-6-128',
    modelId: 'cmf-phone-1',
    ram: '6GB',
    storage: '128GB',
    price: 15999,
    mrp: 15999,
    colors: ['Black', 'Light Green', 'Blue', 'Orange'],
    status: 'active',
    verified: true,
    source: 'CMF by Nothing India / Flipkart',
  },
  {
    id: 'cmf-phone-1-8-128',
    modelId: 'cmf-phone-1',
    ram: '8GB',
    storage: '128GB',
    price: 17999,
    mrp: 17999,
    colors: ['Black', 'Light Green', 'Orange'],
    status: 'active',
    verified: true,
    source: 'CMF by Nothing India / Flipkart',
  },

  // ASUS ROG Phone 8 Pro
  {
    id: 'asus-rog-phone-8-pro-16-512',
    modelId: 'asus-rog-phone-8-pro',
    ram: '16GB',
    storage: '512GB',
    price: 94999,
    mrp: 94999,
    colors: ['Phantom Black'],
    status: 'active',
    verified: true,
    source: 'ASUS India / Vijay Sales',
  },
  {
    id: 'asus-rog-phone-8-pro-24-1tb',
    modelId: 'asus-rog-phone-8-pro',
    ram: '24GB',
    storage: '1TB',
    price: 119999,
    mrp: 119999,
    colors: ['Phantom Black'],
    status: 'active',
    verified: true,
    source: 'ASUS India / Vijay Sales',
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    modelId: 'nothing-phone-2',
    modelName: 'Nothing Phone (2)',
    brand: 'Nothing',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://in.nothing.tech/cdn/shop/files/P2-DarkGrey-Front.png?v=1688647000',
        angle: 'front',
        source: 'Nothing Tech Official Assets',
        sourceUrl: 'https://in.nothing.tech/pages/phone-2',
        verified: true,
        alt: 'Nothing Phone (2) front display view',
      },
      {
        url: 'https://in.nothing.tech/cdn/shop/files/P2-DarkGrey-Back.png?v=1688647000',
        angle: 'back',
        source: 'Nothing Tech Official Assets',
        sourceUrl: 'https://in.nothing.tech/pages/phone-2',
        verified: true,
        alt: 'Nothing Phone (2) Glyph interface transparent back view',
      },
    ],
  },
  {
    modelId: 'nothing-phone-2a-plus',
    modelName: 'Nothing Phone (2a) Plus',
    brand: 'Nothing',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://in.nothing.tech/cdn/shop/files/phone-2a-plus-front.png?v=1722400000',
        angle: 'front',
        source: 'Nothing Tech Official Assets',
        sourceUrl: 'https://in.nothing.tech/pages/phone-2a-plus',
        verified: true,
        alt: 'Nothing Phone (2a) Plus front display view',
      },
      {
        url: 'https://in.nothing.tech/cdn/shop/files/phone-2a-plus-back.png?v=1722400000',
        angle: 'back',
        source: 'Nothing Tech Official Assets',
        sourceUrl: 'https://in.nothing.tech/pages/phone-2a-plus',
        verified: true,
        alt: 'Nothing Phone (2a) Plus metallic sheen rear Glyph view',
      },
    ],
  },
  {
    modelId: 'cmf-phone-1',
    modelName: 'CMF Phone 1',
    brand: 'CMF',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://in.nothing.tech/cdn/shop/files/cmf-phone-1-front.png?v=1720400000',
        angle: 'front',
        source: 'CMF Official Assets',
        sourceUrl: 'https://in.nothing.tech/pages/cmf-phone-1',
        verified: true,
        alt: 'CMF Phone 1 front display view',
      },
      {
        url: 'https://in.nothing.tech/cdn/shop/files/cmf-phone-1-back.png?v=1720400000',
        angle: 'back',
        source: 'CMF Official Assets',
        sourceUrl: 'https://in.nothing.tech/pages/cmf-phone-1',
        verified: true,
        alt: 'CMF Phone 1 modular customizable back with accessory dial',
      },
    ],
  },
  {
    modelId: 'asus-rog-phone-8-pro',
    modelName: 'ROG Phone 8 Pro',
    brand: 'ASUS',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://dlcdnwebimgs.asus.com/gain/477F3F19-5F1F-4389-913D-88223B8601BD/w800',
        angle: 'front',
        source: 'ASUS Official Asset Server',
        sourceUrl: 'https://rog.asus.com/in/phones/rog-phone-8-pro/',
        verified: true,
        alt: 'ASUS ROG Phone 8 Pro front 165Hz display view',
      },
      {
        url: 'https://dlcdnwebimgs.asus.com/gain/45FE6D7D-E447-4E90-A88E-3FB44614A51D/w800',
        angle: 'back',
        source: 'ASUS Official Asset Server',
        sourceUrl: 'https://rog.asus.com/in/phones/rog-phone-8-pro/',
        verified: true,
        alt: 'ASUS ROG Phone 8 Pro AniMe Vision mini-LED rear view',
      },
    ],
  },
];

export const nothingAsusBundle: MobileBrandBundle = {
  models,
  variants,
  images,
};
