import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  // ── INFINIX ──
  {
    id: 'infinix-gt-20-pro',
    slug: 'infinix-gt-20-pro',
    brand: 'Infinix',
    modelName: 'Infinix GT 20 Pro',
    generation: 'GT 20',
    status: 'active',
    launchDate: '2024-05',
    pricing: {
      startingPrice: 22999,
      maximumPrice: 24999,
      launchPrice: 24999,
      currentPrice: 22999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Infinix India / Flipkart',
    },
    display: {
      displaySize: 6.78,
      displayType: '144Hz FHD+ Bezel-less LTPS AMOLED',
      resolution: '2436 x 1080 pixels',
      refreshRate: 144,
      peakBrightness: 1300,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '94.3%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 8200 Ultimate (4nm) with Pixelworks X5 Turbo Gaming Display Chip',
      cpu: 'Octa-core (1x3.1 GHz Cortex-A78 & 3x3.0 GHz & 4x2.0 GHz)',
      gpu: 'Mali-G610 MC6',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 3.1',
      antutuScore: 950000,
    },
    cameras: {
      rearCameraSetup: 'Triple (108MP + 2MP + 2MP) with Mecha Loop LED',
      mainCamera: '108 MP Samsung HM6, f/1.75, OIS',
      ultrawideCamera: 'None',
      telephotoCamera: 'None (2 MP Macro + 2 MP Depth)',
      frontCamera: '32 MP, f/2.2',
      videoRecording: '4K@60fps, 1080p@120fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 45,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0 with Bypass Charging Mode',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '164.26 x 75.43 x 8.15 mm',
      weight: 194,
      materials: 'Cyber Mecha design with interactive RGB mini-LED loop lighting',
      waterResistance: 'IP54 splash resistant',
      colors: ['Mecha Silver', 'Mecha Blue', 'Mecha Orange'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Clean XOS 14 (Zero bloatware guarantee)',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers tuned by JBL',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://in.infinixmobility.com/gt-20-pro',
      productPage: 'https://www.flipkart.com/infinix-gt-20-pro-store',
      specSheetUrl: 'https://in.infinixmobility.com/gt-20-pro/specs',
      verifiedDate: '2024-05',
    },
  },

  {
    id: 'infinix-zero-40-5g',
    slug: 'infinix-zero-40-5g',
    brand: 'Infinix',
    modelName: 'Infinix Zero 40 5G',
    generation: 'Zero 40',
    status: 'active',
    launchDate: '2024-09',
    pricing: {
      startingPrice: 27999,
      maximumPrice: 30999,
      launchPrice: 27999,
      currentPrice: 27999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Infinix India / Flipkart',
    },
    display: {
      displaySize: 6.78,
      displayType: '144Hz 3D Curved AMOLED',
      resolution: '2436 x 1080 pixels',
      refreshRate: 144,
      peakBrightness: 1300,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '93.4%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 8200 Ultimate (4nm)',
      cpu: 'Octa-core (1x3.1 GHz & 3x3.0 GHz & 4x2.0 GHz)',
      gpu: 'Mali-G610 MC6',
      ramOptions: ['12GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 3.1',
      antutuScore: 940000,
    },
    cameras: {
      rearCameraSetup: 'Triple (108MP + 50MP + 2MP) with GoPro Mode',
      mainCamera: '108 MP Samsung ISOCELL HM6, f/1.75, OIS',
      ultrawideCamera: '50 MP, f/2.0, 120˚',
      telephotoCamera: 'None (2 MP depth)',
      frontCamera: '50 MP Samsung ISOCELL JN1, f/2.45, 4K60',
      videoRecording: '4K@60fps (front and rear) with Vlog mode and GoPro integration',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 45,
      wirelessCharging: 20,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '164.31 x 74.47 x 7.9 mm',
      weight: 195,
      materials: 'Curved glass back, aluminum midframe',
      waterResistance: 'IP54',
      colors: ['Violet Garden', 'Moving Titanium', 'Rock Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'XOS 14.5 with Folax AI',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers tuned by JBL',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://in.infinixmobility.com/zero-40-5g',
      productPage: 'https://www.flipkart.com/infinix-zero-40-5g-store',
      specSheetUrl: 'https://in.infinixmobility.com/zero-40-5g/specs',
      verifiedDate: '2024-09',
    },
  },

  // ── TECNO ──
  {
    id: 'tecno-camon-30-premier-5g',
    slug: 'tecno-camon-30-premier-5g',
    brand: 'Tecno',
    modelName: 'Tecno Camon 30 Premier 5G',
    generation: 'Camon 30',
    status: 'active',
    launchDate: '2024-05',
    pricing: {
      startingPrice: 36999,
      maximumPrice: 36999,
      launchPrice: 39999,
      currentPrice: 36999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Tecno India Official Store',
    },
    display: {
      displaySize: 6.77,
      displayType: '1.5K 120Hz LTPO AMOLED',
      resolution: '2780 x 1264 pixels',
      refreshRate: 120,
      peakBrightness: 1400,
      hdr: 'HDR10+',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '93.0%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 8200 Ultimate (4nm) with Sony CXD5622GG ISP',
      cpu: 'Octa-core (1x3.1 GHz & 3x3.0 GHz & 4x2.0 GHz)',
      gpu: 'Mali-G610 MC6',
      ramOptions: ['12GB'],
      storageOptions: ['512GB'],
      storageType: 'UFS 3.1',
      antutuScore: 960000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 50MP) with Action Dot notification LED',
      mainCamera: '50 MP Sony IMX890, f/1.88, 1/1.56", OIS',
      ultrawideCamera: '50 MP, f/2.2, 114˚, macro',
      telephotoCamera: '50 MP periscope telephoto, 3x optical, 70mm, 60x hybrid, OIS',
      frontCamera: '50 MP Eye-tracking autofocus, f/2.45',
      videoRecording: '4K@60fps (front and rear) with 4K 30fps HDR video',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 70,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.7 x 76.2 x 7.9 mm',
      weight: 210,
      materials: 'Aerospace-grade metal unibody frame, tech-art suede/vegan leather back',
      waterResistance: 'IP54 splash resistant',
      colors: ['Alps Snowy Silver', 'Hawaii Lava Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'HiOS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers tuned by Dolby Atmos',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.tecno-mobile.in/camon-30-premier-5g',
      productPage: 'https://www.amazon.in/dp/B0D4N69Y4K',
      specSheetUrl: 'https://www.tecno-mobile.in/camon-30-premier-5g/specs',
      verifiedDate: '2024-05',
    },
  },

  {
    id: 'tecno-pova-6-pro-5g',
    slug: 'tecno-pova-6-pro-5g',
    brand: 'Tecno',
    modelName: 'Tecno Pova 6 Pro 5G',
    generation: 'Pova 6',
    status: 'active',
    launchDate: '2024-04',
    pricing: {
      startingPrice: 18999,
      maximumPrice: 20999,
      launchPrice: 19999,
      currentPrice: 18999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Tecno India Official Store',
    },
    display: {
      displaySize: 6.78,
      displayType: '120Hz FHD+ AMOLED',
      resolution: '2436 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 1300,
      hdr: 'None',
      protection: 'Glass front',
      screenToBodyRatio: '87.2%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 6080 (6nm)',
      cpu: 'Octa-core (2x2.4 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Mali-G57 MC2',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB'],
      storageType: 'UFS 2.2',
      antutuScore: 430000,
    },
    cameras: {
      rearCameraSetup: 'Triple (108MP + 2MP + AI lens) with Dynamic-Light mini-LEDs',
      mainCamera: '108 MP, f/1.9, 3x in-sensor zoom',
      ultrawideCamera: 'None',
      telephotoCamera: 'None (2 MP depth)',
      frontCamera: '32 MP with dual-color LED flash',
      videoRecording: '1440p@30fps, 1080p@60fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 6000,
      wiredCharging: 70,
      wirelessCharging: 0,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.3',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM + Dedicated microSD',
    },
    physical: {
      dimensions: '165.5 x 76.1 x 7.88 mm',
      weight: 198,
      materials: 'Dynamic-Tech Design with 210 mini-LED lights',
      waterResistance: 'IP53',
      colors: ['Meteorite Grey', 'Comet Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'HiOS 14',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Dual stereo speakers with Dolby Atmos',
      stereo: true,
      headphoneJack: true,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.tecno-mobile.in/pova-6-pro-5g',
      productPage: 'https://www.amazon.in/dp/B0CX21C8S1',
      specSheetUrl: 'https://www.tecno-mobile.in/pova-6-pro-5g/specs',
      verifiedDate: '2024-04',
    },
  },
];

const variants: MobileVariant[] = [
  // Infinix GT 20 Pro
  {
    id: 'infinix-gt-20-pro-8-256',
    modelId: 'infinix-gt-20-pro',
    ram: '8GB',
    storage: '256GB',
    price: 22999,
    mrp: 24999,
    colors: ['Mecha Silver', 'Mecha Blue', 'Mecha Orange'],
    status: 'active',
    verified: true,
    source: 'Infinix India / Flipkart',
  },
  {
    id: 'infinix-gt-20-pro-12-256',
    modelId: 'infinix-gt-20-pro',
    ram: '12GB',
    storage: '256GB',
    price: 24999,
    mrp: 26999,
    colors: ['Mecha Silver', 'Mecha Blue', 'Mecha Orange'],
    status: 'active',
    verified: true,
    source: 'Infinix India / Flipkart',
  },

  // Infinix Zero 40 5G
  {
    id: 'infinix-zero-40-5g-12-256',
    modelId: 'infinix-zero-40-5g',
    ram: '12GB',
    storage: '256GB',
    price: 27999,
    mrp: 29999,
    colors: ['Violet Garden', 'Moving Titanium', 'Rock Black'],
    status: 'active',
    verified: true,
    source: 'Infinix India / Flipkart',
  },
  {
    id: 'infinix-zero-40-5g-12-512',
    modelId: 'infinix-zero-40-5g',
    ram: '12GB',
    storage: '512GB',
    price: 30999,
    mrp: 32999,
    colors: ['Moving Titanium', 'Rock Black'],
    status: 'active',
    verified: true,
    source: 'Infinix India / Flipkart',
  },

  // Tecno Camon 30 Premier 5G
  {
    id: 'tecno-camon-30-premier-5g-12-512',
    modelId: 'tecno-camon-30-premier-5g',
    ram: '12GB',
    storage: '512GB',
    price: 36999,
    mrp: 39999,
    colors: ['Alps Snowy Silver', 'Hawaii Lava Black'],
    status: 'active',
    verified: true,
    source: 'Tecno India Official Store',
  },

  // Tecno Pova 6 Pro 5G
  {
    id: 'tecno-pova-6-pro-5g-8-256',
    modelId: 'tecno-pova-6-pro-5g',
    ram: '8GB',
    storage: '256GB',
    price: 18999,
    mrp: 19999,
    colors: ['Meteorite Grey', 'Comet Green'],
    status: 'active',
    verified: true,
    source: 'Tecno India Official Store',
  },
  {
    id: 'tecno-pova-6-pro-5g-12-256',
    modelId: 'tecno-pova-6-pro-5g',
    ram: '12GB',
    storage: '256GB',
    price: 20999,
    mrp: 21999,
    colors: ['Meteorite Grey', 'Comet Green'],
    status: 'active',
    verified: true,
    source: 'Tecno India Official Store',
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    modelId: 'infinix-gt-20-pro',
    modelName: 'Infinix GT 20 Pro',
    brand: 'Infinix',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://in.infinixmobility.com/media/catalog/product/gt20pro_front.png',
        angle: 'front',
        source: 'Infinix Mobility Asset Server',
        sourceUrl: 'https://in.infinixmobility.com/gt-20-pro',
        verified: true,
        alt: 'Infinix GT 20 Pro front display view',
      },
      {
        url: 'https://in.infinixmobility.com/media/catalog/product/gt20pro_back.png',
        angle: 'back',
        source: 'Infinix Mobility Asset Server',
        sourceUrl: 'https://in.infinixmobility.com/gt-20-pro',
        verified: true,
        alt: 'Infinix GT 20 Pro Cyber Mecha RGB LED back view',
      },
    ],
  },
  {
    modelId: 'infinix-zero-40-5g',
    modelName: 'Infinix Zero 40 5G',
    brand: 'Infinix',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://in.infinixmobility.com/media/catalog/product/zero40_front.png',
        angle: 'front',
        source: 'Infinix Mobility Asset Server',
        sourceUrl: 'https://in.infinixmobility.com/zero-40-5g',
        verified: true,
        alt: 'Infinix Zero 40 5G front display view',
      },
      {
        url: 'https://in.infinixmobility.com/media/catalog/product/zero40_back.png',
        angle: 'back',
        source: 'Infinix Mobility Asset Server',
        sourceUrl: 'https://in.infinixmobility.com/zero-40-5g',
        verified: true,
        alt: 'Infinix Zero 40 5G circular camera array rear view',
      },
    ],
  },
  {
    modelId: 'tecno-camon-30-premier-5g',
    modelName: 'Tecno Camon 30 Premier 5G',
    brand: 'Tecno',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://www.tecno-mobile.in/media/catalog/product/camon30premier_front.png',
        angle: 'front',
        source: 'Tecno Mobile India CDN',
        sourceUrl: 'https://www.tecno-mobile.in/camon-30-premier-5g',
        verified: true,
        alt: 'Tecno Camon 30 Premier 5G front display view',
      },
      {
        url: 'https://www.tecno-mobile.in/media/catalog/product/camon30premier_back.png',
        angle: 'back',
        source: 'Tecno Mobile India CDN',
        sourceUrl: 'https://www.tecno-mobile.in/camon-30-premier-5g',
        verified: true,
        alt: 'Tecno Camon 30 Premier 5G vintage camera inspired rear view',
      },
    ],
  },
  {
    modelId: 'tecno-pova-6-pro-5g',
    modelName: 'Tecno Pova 6 Pro 5G',
    brand: 'Tecno',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://www.tecno-mobile.in/media/catalog/product/pova6pro_front.png',
        angle: 'front',
        source: 'Tecno Mobile India CDN',
        sourceUrl: 'https://www.tecno-mobile.in/pova-6-pro-5g',
        verified: true,
        alt: 'Tecno Pova 6 Pro 5G front display view',
      },
      {
        url: 'https://www.tecno-mobile.in/media/catalog/product/pova6pro_back.png',
        angle: 'back',
        source: 'Tecno Mobile India CDN',
        sourceUrl: 'https://www.tecno-mobile.in/pova-6-pro-5g',
        verified: true,
        alt: 'Tecno Pova 6 Pro 5G dynamic mini-LED rear view',
      },
    ],
  },
];

export const transsionBundle: MobileBrandBundle = {
  models,
  variants,
  images,
};
