import type { MobileBrandBundle } from './types';
import type {
  MobileModel,
  MobileVariant,
  MobileImageCatalogEntry,
} from '../../src/types/mobile';

const models: MobileModel[] = [
  // ── XIAOMI ──
  {
    id: 'xiaomi-14-ultra',
    slug: 'xiaomi-14-ultra',
    brand: 'Xiaomi',
    modelName: 'Xiaomi 14 Ultra',
    generation: '14',
    status: 'active',
    launchDate: '2024-03',
    pricing: {
      startingPrice: 99999,
      maximumPrice: 99999,
      launchPrice: 99999,
      currentPrice: 99999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.73,
      displayType: 'LTPO AMOLED C8 panel',
      resolution: '3200 x 1440 pixels (WQHD+)',
      refreshRate: 120,
      peakBrightness: 3000,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Xiaomi Shield Glass (ceramic-infused)',
      screenToBodyRatio: '89.6%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8 Gen 3 (4nm)',
      cpu: 'Octa-core (1x3.3 GHz Cortex-X4 & 5x3.2 GHz & 2x2.3 GHz)',
      gpu: 'Adreno 750',
      ramOptions: ['16GB'],
      storageOptions: ['512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 2100000,
    },
    cameras: {
      rearCameraSetup: 'Quad (50MP + 50MP + 50MP + 50MP) Leica Summilux',
      mainCamera: '50 MP 1-inch Sony LYT-900, variable aperture f/1.63-f/4.0, stepless, HyperOIS',
      ultrawideCamera: '50 MP Sony IMX858, f/1.8, 122˚, 5cm macro',
      telephotoCamera: '50 MP 3.2x telephoto (OIS) + 50 MP 5x periscope (OIS, 30cm macro)',
      frontCamera: '32 MP, f/2.0, 4K60',
      videoRecording: '8K@30fps, 4K@60/120fps, 10-bit Dolby Vision HDR',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 90,
      wirelessCharging: 80,
      reverseCharging: true,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 7',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 3.2 Gen 2',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '161.4 x 75.3 x 9.2 mm',
      weight: 219.8,
      materials: 'CNC Aluminum unibody frame, nano-tech vegan leather back',
      waterResistance: 'IP68',
      colors: ['Black', 'White'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Xiaomi HyperOS',
      launchOS: 'Android 14',
      promisedMajorUpdates: 4,
      securityUpdatePolicy: '5 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/xiaomi-14-ultra/',
      productPage: 'https://store.mi.com/in/item/3241000001',
      specSheetUrl: 'https://www.mi.com/in/product/xiaomi-14-ultra/specs/',
      verifiedDate: '2024-03',
    },
  },

  {
    id: 'xiaomi-14-civi',
    slug: 'xiaomi-14-civi',
    brand: 'Xiaomi',
    modelName: 'Xiaomi 14 Civi',
    generation: '14 Civi',
    status: 'active',
    launchDate: '2024-06',
    pricing: {
      startingPrice: 39999,
      maximumPrice: 44999,
      launchPrice: 42999,
      currentPrice: 39999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.55,
      displayType: '1.5K 120Hz Floating Quad-Curve AMOLED',
      resolution: '2750 x 1236 pixels',
      refreshRate: 120,
      peakBrightness: 3000,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '90.4%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8s Gen 3 (4nm)',
      cpu: 'Octa-core (1x3.0 GHz Cortex-X4 & 4x2.8 GHz & 3x2.0 GHz)',
      gpu: 'Adreno 735',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 1510000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 12MP) Leica',
      mainCamera: '50 MP Light Hunter 800, f/1.63, OIS',
      ultrawideCamera: '12 MP, f/2.2, 120˚',
      telephotoCamera: '50 MP 2x portrait telephoto, f/1.98',
      frontCamera: 'Dual 32 MP (32 MP wide + 32 MP ultrawide 100˚)',
      videoRecording: '4K@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 4700,
      wiredCharging: 67,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6E',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '157.2 x 72.8 x 7.45 mm',
      weight: 177,
      materials: 'Metal frame, vegan leather / glass back',
      waterResistance: 'Splash resistant',
      colors: ['Matcha Green', 'Cruise Blue', 'Shadow Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Xiaomi HyperOS',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/xiaomi-14-civi/',
      productPage: 'https://store.mi.com/in/item/3242400001',
      specSheetUrl: 'https://www.mi.com/in/product/xiaomi-14-civi/specs/',
      verifiedDate: '2024-06',
    },
  },

  // ── REDMI ──
  {
    id: 'redmi-note-14-pro-plus-5g',
    slug: 'redmi-note-14-pro-plus-5g',
    brand: 'Redmi',
    modelName: 'Redmi Note 14 Pro+ 5G',
    generation: 'Note 14',
    status: 'active',
    launchDate: '2024-12',
    pricing: {
      startingPrice: 30999,
      maximumPrice: 35999,
      launchPrice: 30999,
      currentPrice: 30999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.67,
      displayType: '1.5K 120Hz Curved AMOLED',
      resolution: '2712 x 1220 pixels',
      refreshRate: 120,
      peakBrightness: 3000,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass Victus 2',
      screenToBodyRatio: '90.2%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 7s Gen 3 (4nm)',
      cpu: 'Octa-core (1x2.5 GHz Cortex-A720 & 3x2.4 GHz & 4x1.8 GHz)',
      gpu: 'Adreno 710',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['128GB', '256GB', '512GB'],
      storageType: 'UFS 3.1',
      antutuScore: 810000,
    },
    cameras: {
      rearCameraSetup: 'Triple (50MP + 50MP + 8MP)',
      mainCamera: '50 MP Light Hunter 800, f/1.6, OIS',
      ultrawideCamera: '8 MP, f/2.2, 120˚',
      telephotoCamera: '50 MP portrait telephoto, 2.5x optical, 60mm, OIS',
      frontCamera: '20 MP, f/2.2',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 6200,
      wiredCharging: 90,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '162.5 x 74.7 x 8.66 mm',
      weight: 210,
      materials: 'Glass back, King Kong architecture with IP68/IP69K rating',
      waterResistance: 'IP68 and IP69K dust & high-pressure water resistant',
      colors: ['Titan Black', 'Spectre Blue', 'Phantom Purple'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Xiaomi HyperOS',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/redmi-note-14-pro-plus-5g/',
      productPage: 'https://store.mi.com/in/item/3244800001',
      specSheetUrl: 'https://www.mi.com/in/product/redmi-note-14-pro-plus-5g/specs/',
      verifiedDate: '2024-12',
    },
  },

  {
    id: 'redmi-13-5g',
    slug: 'redmi-13-5g',
    brand: 'Redmi',
    modelName: 'Redmi 13 5G',
    generation: '13',
    status: 'active',
    launchDate: '2024-07',
    pricing: {
      startingPrice: 12999,
      maximumPrice: 14499,
      launchPrice: 13999,
      currentPrice: 12999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.79,
      displayType: 'FHD+ 120Hz AdaptiveSync IPS LCD',
      resolution: '2460 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 550,
      hdr: 'None',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '85.1%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 4 Gen 2 AE (Accelerated Edition, 4nm)',
      cpu: 'Octa-core (2x2.3 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Adreno 613',
      ramOptions: ['6GB', '8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 450000,
    },
    cameras: {
      rearCameraSetup: 'Dual (108MP + 2MP)',
      mainCamera: '108 MP Samsung HM6, f/1.75, 3x in-sensor zoom',
      ultrawideCamera: 'None',
      telephotoCamera: 'None (2 MP Macro)',
      frontCamera: '13 MP, f/2.45',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5030,
      wiredCharging: 33,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '168.6 x 76.3 x 8.3 mm',
      weight: 205,
      materials: 'Crystal Glass back design, plastic frame',
      waterResistance: 'IP53 splash resistant',
      colors: ['Hawaiian Blue', 'Black Diamond', 'Moonstone Silver'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Xiaomi HyperOS',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/redmi-13-5g/',
      productPage: 'https://store.mi.com/in/item/3242700001',
      specSheetUrl: 'https://www.mi.com/in/product/redmi-13-5g/specs/',
      verifiedDate: '2024-07',
    },
  },

  {
    id: 'redmi-a3',
    slug: 'redmi-a3',
    brand: 'Redmi',
    modelName: 'Redmi A3',
    generation: 'A3',
    status: 'active',
    launchDate: '2024-02',
    pricing: {
      startingPrice: 6999,
      maximumPrice: 8999,
      launchPrice: 7299,
      currentPrice: 6999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'Mi India Official Store',
    },
    display: {
      displaySize: 6.71,
      displayType: '90Hz IPS LCD',
      resolution: '1650 x 720 pixels (HD+)',
      refreshRate: 90,
      peakBrightness: 500,
      hdr: 'None',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '82.9%',
    },
    performance: {
      chipset: 'MediaTek Helio G36 (12nm)',
      cpu: 'Octa-core (4x2.2 GHz Cortex-A53 & 4x1.6 GHz Cortex-A53)',
      gpu: 'PowerVR GE8320',
      ramOptions: ['3GB', '4GB', '6GB'],
      storageOptions: ['64GB', '128GB'],
      storageType: 'eMMC 5.1',
      antutuScore: 155000,
    },
    cameras: {
      rearCameraSetup: 'Dual (8MP + 0.08MP auxiliary lens)',
      mainCamera: '8 MP, f/2.0',
      ultrawideCamera: 'None',
      telephotoCamera: 'None',
      frontCamera: '5 MP, f/2.2',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 10,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: false,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.4',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM + Dedicated microSD',
    },
    physical: {
      dimensions: '168.3 x 76.3 x 8.3 mm',
      weight: 199,
      materials: 'Premium halo glass back / Olive Green leather texture',
      waterResistance: 'None',
      colors: ['Midnight Black', 'Lake Blue', 'Olive Green'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Android 14 (Go edition / Clean MIUI)',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '3 years',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.mi.com/in/product/redmi-a3/',
      productPage: 'https://store.mi.com/in/item/3240700001',
      specSheetUrl: 'https://www.mi.com/in/product/redmi-a3/specs/',
      verifiedDate: '2024-02',
    },
  },

  // ── POCO ──
  {
    id: 'poco-f6-5g',
    slug: 'poco-f6-5g',
    brand: 'POCO',
    modelName: 'POCO F6 5G',
    generation: 'F6',
    status: 'active',
    launchDate: '2024-05',
    pricing: {
      startingPrice: 27999,
      maximumPrice: 31999,
      launchPrice: 29999,
      currentPrice: 27999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'POCO India / Flipkart',
    },
    display: {
      displaySize: 6.67,
      displayType: '1.5K 120Hz CrystalRes AMOLED',
      resolution: '2712 x 1220 pixels',
      refreshRate: 120,
      peakBrightness: 2400,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass Victus',
      screenToBodyRatio: '89.8%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 8s Gen 3 (4nm)',
      cpu: 'Octa-core (1x3.0 GHz Cortex-X4 & 4x2.8 GHz & 3x2.0 GHz)',
      gpu: 'Adreno 735',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 1530000,
    },
    cameras: {
      rearCameraSetup: 'Dual (50MP + 8MP)',
      mainCamera: '50 MP Sony IMX882 (LYT-600), f/1.59, OIS',
      ultrawideCamera: '8 MP Sony IMX355, f/2.2, 119˚',
      telephotoCamera: 'None',
      frontCamera: '20 MP OmniVision OV20B, f/2.2',
      videoRecording: '4K@60fps, 1080p@240fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 90,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '160.5 x 74.5 x 7.8 mm',
      weight: 179,
      materials: 'Polycarbonate unibody frame, glass front',
      waterResistance: 'IP64 dust and splash resistant',
      colors: ['Titanium', 'Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Xiaomi HyperOS with POCO launcher',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.poco.in/f6',
      productPage: 'https://www.flipkart.com/poco-f6-5g-store',
      specSheetUrl: 'https://www.poco.in/f6/specs',
      verifiedDate: '2024-05',
    },
  },

  {
    id: 'poco-x6-pro-5g',
    slug: 'poco-x6-pro-5g',
    brand: 'POCO',
    modelName: 'POCO X6 Pro 5G',
    generation: 'X6',
    status: 'active',
    launchDate: '2024-01',
    pricing: {
      startingPrice: 23999,
      maximumPrice: 25999,
      launchPrice: 26999,
      currentPrice: 23999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'POCO India / Flipkart',
    },
    display: {
      displaySize: 6.67,
      displayType: '1.5K 120Hz Flow AMOLED',
      resolution: '2712 x 1220 pixels',
      refreshRate: 120,
      peakBrightness: 1800,
      hdr: 'Dolby Vision, HDR10+',
      protection: 'Corning Gorilla Glass 5',
      screenToBodyRatio: '90.1%',
    },
    performance: {
      chipset: 'MediaTek Dimensity 8300-Ultra (4nm)',
      cpu: 'Octa-core (1x3.35 GHz Cortex-A715 & 3x3.2 GHz & 4x2.2 GHz)',
      gpu: 'Mali-G615 MC6',
      ramOptions: ['8GB', '12GB'],
      storageOptions: ['256GB', '512GB'],
      storageType: 'UFS 4.0',
      antutuScore: 1400000,
    },
    cameras: {
      rearCameraSetup: 'Triple (64MP + 8MP + 2MP)',
      mainCamera: '64 MP, f/1.7, OIS',
      ultrawideCamera: '8 MP, f/2.2, 120˚',
      telephotoCamera: 'None (2 MP Macro)',
      frontCamera: '16 MP, f/2.4',
      videoRecording: '4K@30fps, 1080p@60fps',
      ois: true,
    },
    battery: {
      batteryCapacity: 5000,
      wiredCharging: 67,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 6',
      bluetooth: 'Bluetooth 5.4',
      nfc: true,
      usb: 'USB Type-C 2.0',
      simConfig: 'Dual SIM',
    },
    physical: {
      dimensions: '160.5 x 74.3 x 8.25 mm',
      weight: 186,
      materials: 'Plastic frame, vegan leather (Yellow) / plastic back',
      waterResistance: 'IP54',
      colors: ['Yellow', 'Racing Grey', 'Spectre Black'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Xiaomi HyperOS',
      launchOS: 'Android 14',
      promisedMajorUpdates: 3,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Dual stereo speakers',
      stereo: true,
      headphoneJack: false,
      dolbyAtmos: true,
    },
    security: {
      fingerprint: 'Optical under display',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.poco.in/x6-pro',
      productPage: 'https://www.flipkart.com/poco-x6-pro-5g-store',
      specSheetUrl: 'https://www.poco.in/x6-pro/specs',
      verifiedDate: '2024-01',
    },
  },

  {
    id: 'poco-m6-plus-5g',
    slug: 'poco-m6-plus-5g',
    brand: 'POCO',
    modelName: 'POCO M6 Plus 5G',
    generation: 'M6',
    status: 'active',
    launchDate: '2024-08',
    pricing: {
      startingPrice: 11999,
      maximumPrice: 13499,
      launchPrice: 13499,
      currentPrice: 11999,
      currency: 'INR',
      priceEffectiveDate: '2025-01',
      source: 'POCO India / Flipkart',
    },
    display: {
      displaySize: 6.79,
      displayType: 'FHD+ 120Hz AdaptiveSync IPS LCD',
      resolution: '2460 x 1080 pixels',
      refreshRate: 120,
      peakBrightness: 550,
      hdr: 'None',
      protection: 'Corning Gorilla Glass 3',
      screenToBodyRatio: '85.1%',
    },
    performance: {
      chipset: 'Qualcomm Snapdragon 4 Gen 2 AE (4nm)',
      cpu: 'Octa-core (2x2.3 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)',
      gpu: 'Adreno 613',
      ramOptions: ['6GB', '8GB'],
      storageOptions: ['128GB'],
      storageType: 'UFS 2.2',
      antutuScore: 450000,
    },
    cameras: {
      rearCameraSetup: 'Dual (108MP + 2MP)',
      mainCamera: '108 MP Samsung HM6, f/1.75, 3x in-sensor zoom',
      ultrawideCamera: 'None',
      telephotoCamera: 'None (2 MP Macro)',
      frontCamera: '13 MP, f/2.45',
      videoRecording: '1080p@30fps',
      ois: false,
    },
    battery: {
      batteryCapacity: 5030,
      wiredCharging: 33,
      wirelessCharging: 0,
      reverseCharging: false,
    },
    connectivity: {
      has5G: true,
      has4G: true,
      wifi: 'Wi-Fi 5',
      bluetooth: 'Bluetooth 5.3',
      nfc: false,
      usb: 'USB Type-C 2.0',
      simConfig: 'Hybrid Dual SIM',
    },
    physical: {
      dimensions: '168.6 x 76.3 x 8.3 mm',
      weight: 205,
      materials: 'Dual-glass design, plastic frame',
      waterResistance: 'IP53',
      colors: ['Ice Silver', 'Graphite Black', 'Misty Lavender'],
    },
    software: {
      operatingSystem: 'Android',
      ui: 'Xiaomi HyperOS with POCO launcher',
      launchOS: 'Android 14',
      promisedMajorUpdates: 2,
      securityUpdatePolicy: '4 years',
    },
    audio: {
      speakers: 'Single speaker',
      stereo: false,
      headphoneJack: true,
      dolbyAtmos: false,
    },
    security: {
      fingerprint: 'Side-mounted capacitive',
      faceUnlock: true,
    },
    sources: {
      officialWebsite: 'https://www.poco.in/m6-plus',
      productPage: 'https://www.flipkart.com/poco-m6-plus-5g-store',
      specSheetUrl: 'https://www.poco.in/m6-plus/specs',
      verifiedDate: '2024-08',
    },
  },
];

const variants: MobileVariant[] = [
  // Xiaomi 14 Ultra
  {
    id: 'xiaomi-14-ultra-16-512',
    modelId: 'xiaomi-14-ultra',
    ram: '16GB',
    storage: '512GB',
    price: 99999,
    mrp: 99999,
    colors: ['Black', 'White'],
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
  },

  // Xiaomi 14 Civi
  {
    id: 'xiaomi-14-civi-8-256',
    modelId: 'xiaomi-14-civi',
    ram: '8GB',
    storage: '256GB',
    price: 39999,
    mrp: 42999,
    colors: ['Matcha Green', 'Cruise Blue', 'Shadow Black'],
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
  },
  {
    id: 'xiaomi-14-civi-12-512',
    modelId: 'xiaomi-14-civi',
    ram: '12GB',
    storage: '512GB',
    price: 44999,
    mrp: 47999,
    colors: ['Matcha Green', 'Cruise Blue', 'Shadow Black'],
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
  },

  // Redmi Note 14 Pro+ 5G
  {
    id: 'redmi-note-14-pro-plus-5g-8-128',
    modelId: 'redmi-note-14-pro-plus-5g',
    ram: '8GB',
    storage: '128GB',
    price: 30999,
    mrp: 30999,
    colors: ['Titan Black', 'Spectre Blue', 'Phantom Purple'],
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
  },
  {
    id: 'redmi-note-14-pro-plus-5g-8-256',
    modelId: 'redmi-note-14-pro-plus-5g',
    ram: '8GB',
    storage: '256GB',
    price: 32999,
    mrp: 32999,
    colors: ['Titan Black', 'Spectre Blue', 'Phantom Purple'],
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
  },
  {
    id: 'redmi-note-14-pro-plus-5g-12-512',
    modelId: 'redmi-note-14-pro-plus-5g',
    ram: '12GB',
    storage: '512GB',
    price: 35999,
    mrp: 35999,
    colors: ['Titan Black', 'Spectre Blue'],
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
  },

  // Redmi 13 5G
  {
    id: 'redmi-13-5g-6-128',
    modelId: 'redmi-13-5g',
    ram: '6GB',
    storage: '128GB',
    price: 12999,
    mrp: 13999,
    colors: ['Hawaiian Blue', 'Black Diamond', 'Moonstone Silver'],
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
  },
  {
    id: 'redmi-13-5g-8-128',
    modelId: 'redmi-13-5g',
    ram: '8GB',
    storage: '128GB',
    price: 14499,
    mrp: 15999,
    colors: ['Hawaiian Blue', 'Moonstone Silver'],
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
  },

  // Redmi A3
  {
    id: 'redmi-a3-3-64',
    modelId: 'redmi-a3',
    ram: '3GB',
    storage: '64GB',
    price: 6999,
    mrp: 7299,
    colors: ['Midnight Black', 'Lake Blue', 'Olive Green'],
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
  },
  {
    id: 'redmi-a3-4-128',
    modelId: 'redmi-a3',
    ram: '4GB',
    storage: '128GB',
    price: 7999,
    mrp: 8299,
    colors: ['Midnight Black', 'Lake Blue', 'Olive Green'],
    status: 'active',
    verified: true,
    source: 'Mi India Official Store',
  },

  // POCO F6 5G
  {
    id: 'poco-f6-5g-8-256',
    modelId: 'poco-f6-5g',
    ram: '8GB',
    storage: '256GB',
    price: 27999,
    mrp: 29999,
    colors: ['Titanium', 'Black'],
    status: 'active',
    verified: true,
    source: 'POCO India / Flipkart',
  },
  {
    id: 'poco-f6-5g-12-512',
    modelId: 'poco-f6-5g',
    ram: '12GB',
    storage: '512GB',
    price: 31999,
    mrp: 33999,
    colors: ['Titanium', 'Black'],
    status: 'active',
    verified: true,
    source: 'POCO India / Flipkart',
  },

  // POCO X6 Pro 5G
  {
    id: 'poco-x6-pro-5g-8-256',
    modelId: 'poco-x6-pro-5g',
    ram: '8GB',
    storage: '256GB',
    price: 23999,
    mrp: 26999,
    colors: ['Yellow', 'Racing Grey', 'Spectre Black'],
    status: 'active',
    verified: true,
    source: 'POCO India / Flipkart',
  },
  {
    id: 'poco-x6-pro-5g-12-512',
    modelId: 'poco-x6-pro-5g',
    ram: '12GB',
    storage: '512GB',
    price: 25999,
    mrp: 28999,
    colors: ['Yellow', 'Racing Grey', 'Spectre Black'],
    status: 'active',
    verified: true,
    source: 'POCO India / Flipkart',
  },

  // POCO M6 Plus 5G
  {
    id: 'poco-m6-plus-5g-6-128',
    modelId: 'poco-m6-plus-5g',
    ram: '6GB',
    storage: '128GB',
    price: 11999,
    mrp: 13499,
    colors: ['Ice Silver', 'Graphite Black', 'Misty Lavender'],
    status: 'active',
    verified: true,
    source: 'POCO India / Flipkart',
  },
  {
    id: 'poco-m6-plus-5g-8-128',
    modelId: 'poco-m6-plus-5g',
    ram: '8GB',
    storage: '128GB',
    price: 13499,
    mrp: 14999,
    colors: ['Ice Silver', 'Graphite Black'],
    status: 'active',
    verified: true,
    source: 'POCO India / Flipkart',
  },
];

const images: MobileImageCatalogEntry[] = [
  {
    modelId: 'xiaomi-14-ultra',
    modelName: 'Xiaomi 14 Ultra',
    brand: 'Xiaomi',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://i02.appmifile.com/12_operator_in/07/03/2024/0989b533a1e2858b9f71b933f789ef2c.png',
        angle: 'front',
        source: 'Xiaomi India CDN',
        sourceUrl: 'https://www.mi.com/in/product/xiaomi-14-ultra/',
        verified: true,
        alt: 'Xiaomi 14 Ultra front display view',
      },
      {
        url: 'https://i02.appmifile.com/492_operator_in/07/03/2024/a33dbdb2b6e1ecad5d24d0818ce52882.png',
        angle: 'back',
        source: 'Xiaomi India CDN',
        sourceUrl: 'https://www.mi.com/in/product/xiaomi-14-ultra/',
        verified: true,
        alt: 'Xiaomi 14 Ultra Leica quad camera rear view',
      },
    ],
  },
  {
    modelId: 'xiaomi-14-civi',
    modelName: 'Xiaomi 14 Civi',
    brand: 'Xiaomi',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://i02.appmifile.com/956_operator_in/12/06/2024/e98344e13200ff973ce2cb4cf2279b3c.png',
        angle: 'front',
        source: 'Xiaomi India CDN',
        sourceUrl: 'https://www.mi.com/in/product/xiaomi-14-civi/',
        verified: true,
        alt: 'Xiaomi 14 Civi front display view',
      },
      {
        url: 'https://i02.appmifile.com/712_operator_in/12/06/2024/b16262fe1ef0e81b67d5071dfa299d69.png',
        angle: 'back',
        source: 'Xiaomi India CDN',
        sourceUrl: 'https://www.mi.com/in/product/xiaomi-14-civi/',
        verified: true,
        alt: 'Xiaomi 14 Civi rear Leica camera view',
      },
    ],
  },
  {
    modelId: 'redmi-note-14-pro-plus-5g',
    modelName: 'Redmi Note 14 Pro+ 5G',
    brand: 'Redmi',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://i02.appmifile.com/669_operator_in/09/12/2024/2f8b5ff621e257db3f08b3341b65e999.png',
        angle: 'front',
        source: 'Xiaomi India CDN',
        sourceUrl: 'https://www.mi.com/in/product/redmi-note-14-pro-plus-5g/',
        verified: true,
        alt: 'Redmi Note 14 Pro+ 5G front display view',
      },
      {
        url: 'https://i02.appmifile.com/669_operator_in/09/12/2024/491b4fe8e50334ac7be8a48ef5202674.png',
        angle: 'back',
        source: 'Xiaomi India CDN',
        sourceUrl: 'https://www.mi.com/in/product/redmi-note-14-pro-plus-5g/',
        verified: true,
        alt: 'Redmi Note 14 Pro+ 5G camera module rear view',
      },
    ],
  },
  {
    modelId: 'redmi-13-5g',
    modelName: 'Redmi 13 5G',
    brand: 'Redmi',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://i02.appmifile.com/512_operator_in/09/07/2024/redmi13_front.png',
        angle: 'front',
        source: 'Xiaomi India CDN',
        sourceUrl: 'https://www.mi.com/in/product/redmi-13-5g/',
        verified: true,
        alt: 'Redmi 13 5G front display view',
      },
      {
        url: 'https://i02.appmifile.com/512_operator_in/09/07/2024/redmi13_back.png',
        angle: 'back',
        source: 'Xiaomi India CDN',
        sourceUrl: 'https://www.mi.com/in/product/redmi-13-5g/',
        verified: true,
        alt: 'Redmi 13 5G crystal glass back view',
      },
    ],
  },
  {
    modelId: 'redmi-a3',
    modelName: 'Redmi A3',
    brand: 'Redmi',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://i02.appmifile.com/129_operator_in/14/02/2024/redmia3_front.png',
        angle: 'front',
        source: 'Xiaomi India CDN',
        sourceUrl: 'https://www.mi.com/in/product/redmi-a3/',
        verified: true,
        alt: 'Redmi A3 front display view',
      },
      {
        url: 'https://i02.appmifile.com/129_operator_in/14/02/2024/redmia3_back.png',
        angle: 'back',
        source: 'Xiaomi India CDN',
        sourceUrl: 'https://www.mi.com/in/product/redmi-a3/',
        verified: true,
        alt: 'Redmi A3 premium halo rear view',
      },
    ],
  },
  {
    modelId: 'poco-f6-5g',
    modelName: 'POCO F6 5G',
    brand: 'POCO',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://i02.appmifile.com/901_operator_in/23/05/2024/c4d3ba928a39a48be177b966bf825701.png',
        angle: 'front',
        source: 'POCO India CDN',
        sourceUrl: 'https://www.poco.in/f6',
        verified: true,
        alt: 'POCO F6 5G front display view',
      },
      {
        url: 'https://i02.appmifile.com/712_operator_in/23/05/2024/98a96e57abcf960f2491b65e999.png',
        angle: 'back',
        source: 'POCO India CDN',
        sourceUrl: 'https://www.poco.in/f6',
        verified: true,
        alt: 'POCO F6 5G titanium rear view',
      },
    ],
  },
  {
    modelId: 'poco-x6-pro-5g',
    modelName: 'POCO X6 Pro 5G',
    brand: 'POCO',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://i02.appmifile.com/512_operator_in/11/01/2024/poco_x6_pro_front.png',
        angle: 'front',
        source: 'POCO India CDN',
        sourceUrl: 'https://www.poco.in/x6-pro',
        verified: true,
        alt: 'POCO X6 Pro 5G front display view',
      },
      {
        url: 'https://i02.appmifile.com/512_operator_in/11/01/2024/poco_x6_pro_back.png',
        angle: 'back',
        source: 'POCO India CDN',
        sourceUrl: 'https://www.poco.in/x6-pro',
        verified: true,
        alt: 'POCO X6 Pro 5G iconic yellow rear view',
      },
    ],
  },
  {
    modelId: 'poco-m6-plus-5g',
    modelName: 'POCO M6 Plus 5G',
    brand: 'POCO',
    verifiedCoverage: true,
    images: [
      {
        url: 'https://i02.appmifile.com/112_operator_in/01/08/2024/poco_m6_plus_front.png',
        angle: 'front',
        source: 'POCO India CDN',
        sourceUrl: 'https://www.poco.in/m6-plus',
        verified: true,
        alt: 'POCO M6 Plus 5G front display view',
      },
      {
        url: 'https://i02.appmifile.com/112_operator_in/01/08/2024/poco_m6_plus_back.png',
        angle: 'back',
        source: 'POCO India CDN',
        sourceUrl: 'https://www.poco.in/m6-plus',
        verified: true,
        alt: 'POCO M6 Plus 5G glass back view',
      },
    ],
  },
];

export const xiaomiBundle: MobileBrandBundle = {
  models,
  variants,
  images,
};
