/**
 * scripts/data_verified_variants_batch2.ts
 *
 * Additional exhaustive verified variant specifications for India's bestselling models:
 * Baleno, Fronx, Grand Vitara, Ertiga, Altroz, Harrier, Safari, XUV 3XO, Thar 3-door,
 * Urban Cruiser Hyryder, Carens, Venue, City, Virtus, Slavia.
 */

import type { CarVariant } from '../src/types/variant';
import { makeStandardFeatures } from './data_verified_variants';

export const VERIFIED_MODEL_VARIANTS_BATCH2: Record<string, Partial<CarVariant>[]> = {
  // ─────────────────────────────────────────────────────────────
  // 11. MARUTI SUZUKI BALENO (Premium Hatchback)
  // ─────────────────────────────────────────────────────────────
  'maruti-suzuki-baleno': [
    {
      id: 'maruti-suzuki-baleno-sigma',
      name: 'Sigma',
      fullName: 'Maruti Suzuki Baleno Sigma 1.2 Petrol 5MT',
      slug: 'sigma',
      trim: 'Sigma',
      variantStatus: 'verified',
      pricing: { exShowroom: 666000, exShowroomLakh: 6.66, currency: 'INR' },
      powertrain: {
        fuelType: 'Petrol',
        engineName: '1.2L K12N DualJet Petrol',
        engineDisplacementCC: 1197,
        cylinders: 4,
        aspiration: 'Naturally Aspirated',
        maxPowerBhp: 89,
        maxTorqueNm: 113,
        transmission: 'Manual',
        drivetrain: 'FWD',
        batteryCapacityKWh: null,
        electricMotorPowerBhp: null,
        electricRangeKm: null,
      },
      performance: { mileageKmpl: 22.35, zeroToHundredSec: 12.1, topSpeedKmph: 170 },
      dimensions: { lengthMm: 3990, widthMm: 1745, heightMm: 1500, wheelbaseMm: 2520, groundClearanceMm: 170, kerbWeightKg: 920, bootSpaceLitres: 318, fuelTankLitres: 37 },
      features: makeStandardFeatures({
        safety: { airbagsCount: 2, abs: 'standard', esc: 'standard', hillAssist: 'standard', rearParkingSensors: 'standard' },
        exterior: { wheelSizeInches: 15, alloyWheels: 'not_available' },
        interior: { automaticClimateControl: 'standard' },
        infotainment: { infotainmentScreenSizeInches: null, speakerCount: 0 },
        convenience: { keylessEntry: 'standard' },
      }),
    },
    {
      id: 'maruti-suzuki-baleno-delta-amt',
      name: 'Delta AMT',
      fullName: 'Maruti Suzuki Baleno Delta 1.2 Petrol 5AMT',
      slug: 'delta-amt',
      trim: 'Delta',
      variantStatus: 'verified',
      pricing: { exShowroom: 799000, exShowroomLakh: 7.99, currency: 'INR' },
      powertrain: {
        fuelType: 'Petrol',
        engineName: '1.2L K12N DualJet Petrol',
        engineDisplacementCC: 1197,
        cylinders: 4,
        aspiration: 'Naturally Aspirated',
        maxPowerBhp: 89,
        maxTorqueNm: 113,
        transmission: 'AMT',
        drivetrain: 'FWD',
        batteryCapacityKWh: null,
        electricMotorPowerBhp: null,
        electricRangeKm: null,
      },
      performance: { mileageKmpl: 22.94, zeroToHundredSec: 12.6, topSpeedKmph: 170 },
      dimensions: { lengthMm: 3990, widthMm: 1745, heightMm: 1500, wheelbaseMm: 2520, groundClearanceMm: 170, kerbWeightKg: 935, bootSpaceLitres: 318, fuelTankLitres: 37 },
      features: makeStandardFeatures({
        safety: { airbagsCount: 2, abs: 'standard', esc: 'standard', hillAssist: 'standard', rearParkingSensors: 'standard' },
        exterior: { wheelSizeInches: 15, alloyWheels: 'not_available' },
        interior: { automaticClimateControl: 'standard' },
        infotainment: { infotainmentScreenSizeInches: 7.0, androidAuto: 'standard', appleCarPlay: 'standard', wirelessAndroidAuto: 'standard', wirelessAppleCarPlay: 'standard', speakerCount: 4 },
        convenience: { keylessEntry: 'standard' },
      }),
    },
    {
      id: 'maruti-suzuki-baleno-alpha-amt',
      name: 'Alpha AMT',
      fullName: 'Maruti Suzuki Baleno Alpha 1.2 Petrol 5AMT (with 360 Camera & HUD)',
      slug: 'alpha-amt',
      trim: 'Alpha',
      variantStatus: 'verified',
      pricing: { exShowroom: 988000, exShowroomLakh: 9.88, currency: 'INR' },
      powertrain: {
        fuelType: 'Petrol',
        engineName: '1.2L K12N DualJet Petrol',
        engineDisplacementCC: 1197,
        cylinders: 4,
        aspiration: 'Naturally Aspirated',
        maxPowerBhp: 89,
        maxTorqueNm: 113,
        transmission: 'AMT',
        drivetrain: 'FWD',
        batteryCapacityKWh: null,
        electricMotorPowerBhp: null,
        electricRangeKm: null,
      },
      performance: { mileageKmpl: 22.94, zeroToHundredSec: 12.5, topSpeedKmph: 170 },
      dimensions: { lengthMm: 3990, widthMm: 1745, heightMm: 1500, wheelbaseMm: 2520, groundClearanceMm: 170, kerbWeightKg: 960, bootSpaceLitres: 318, fuelTankLitres: 37 },
      features: makeStandardFeatures({
        safety: { airbagsCount: 6, abs: 'standard', esc: 'standard', hillAssist: 'standard', threeSixtyCamera: 'standard', rearCamera: 'standard' },
        exterior: { wheelSizeInches: 16, alloyWheels: 'standard', ledHeadlights: 'standard', ledDRLs: 'standard', fogLights: 'standard' },
        interior: { automaticClimateControl: 'standard', rearACVents: 'standard' },
        infotainment: { infotainmentScreenSizeInches: 9.0, headUpDisplay: 'standard', androidAuto: 'standard', appleCarPlay: 'standard', wirelessAndroidAuto: 'standard', wirelessAppleCarPlay: 'standard', premiumAudio: 'standard', connectedCarTechnology: 'standard', speakerCount: 6 },
        convenience: { pushButtonStart: 'standard', keylessEntry: 'standard', cruiseControl: 'standard', autoDimmingIRVM: 'standard' },
      }),
    },
  ],

  // ─────────────────────────────────────────────────────────────
  // 12. MARUTI SUZUKI FRONX (Coupe SUV)
  // ─────────────────────────────────────────────────────────────
  'maruti-suzuki-fronx': [
    {
      id: 'maruti-suzuki-fronx-sigma',
      name: 'Sigma 1.2 Petrol',
      fullName: 'Maruti Suzuki Fronx Sigma 1.2 Petrol 5MT',
      slug: 'sigma-1-2-petrol',
      trim: 'Sigma',
      variantStatus: 'verified',
      pricing: { exShowroom: 751500, exShowroomLakh: 7.52, currency: 'INR' },
      powertrain: {
        fuelType: 'Petrol',
        engineName: '1.2L K12N DualJet Petrol',
        engineDisplacementCC: 1197,
        cylinders: 4,
        aspiration: 'Naturally Aspirated',
        maxPowerBhp: 89,
        maxTorqueNm: 113,
        transmission: 'Manual',
        drivetrain: 'FWD',
        batteryCapacityKWh: null,
        electricMotorPowerBhp: null,
        electricRangeKm: null,
      },
      performance: { mileageKmpl: 21.79, zeroToHundredSec: 12.2, topSpeedKmph: 170 },
      dimensions: { lengthMm: 3995, widthMm: 1765, heightMm: 1550, wheelbaseMm: 2520, groundClearanceMm: 190, kerbWeightKg: 965, bootSpaceLitres: 308, fuelTankLitres: 37 },
      features: makeStandardFeatures({
        safety: { airbagsCount: 2, abs: 'standard', esc: 'standard', hillAssist: 'standard', rearParkingSensors: 'standard' },
        exterior: { wheelSizeInches: 16, alloyWheels: 'not_available', roofRails: 'standard' },
        interior: { automaticClimateControl: 'standard' },
        infotainment: { infotainmentScreenSizeInches: null, speakerCount: 0 },
        convenience: { keylessEntry: 'standard' },
      }),
    },
    {
      id: 'maruti-suzuki-fronx-alpha-turbo-at',
      name: 'Alpha 1.0 Turbo 6AT',
      fullName: 'Maruti Suzuki Fronx Alpha 1.0 Boosterjet Turbo 6AT (with 360 Cam & HUD)',
      slug: 'alpha-turbo-at',
      trim: 'Alpha',
      variantStatus: 'verified',
      pricing: { exShowroom: 1304000, exShowroomLakh: 13.04, currency: 'INR' },
      powertrain: {
        fuelType: 'Petrol',
        engineName: '1.0L K10C Boosterjet Turbo',
        engineDisplacementCC: 998,
        cylinders: 3,
        aspiration: 'Turbocharged',
        maxPowerBhp: 99,
        maxTorqueNm: 148,
        transmission: 'Automatic',
        drivetrain: 'FWD',
        batteryCapacityKWh: null,
        electricMotorPowerBhp: null,
        electricRangeKm: null,
      },
      performance: { mileageKmpl: 20.01, zeroToHundredSec: 10.4, topSpeedKmph: 175 },
      dimensions: { lengthMm: 3995, widthMm: 1765, heightMm: 1550, wheelbaseMm: 2520, groundClearanceMm: 190, kerbWeightKg: 1050, bootSpaceLitres: 308, fuelTankLitres: 37 },
      features: makeStandardFeatures({
        safety: { airbagsCount: 6, abs: 'standard', esc: 'standard', hillAssist: 'standard', threeSixtyCamera: 'standard', rearCamera: 'standard' },
        exterior: { wheelSizeInches: 16, alloyWheels: 'standard', ledHeadlights: 'standard', ledDRLs: 'standard', roofRails: 'standard' },
        interior: { automaticClimateControl: 'standard', rearACVents: 'standard', wirelessCharging: 'standard' },
        infotainment: { infotainmentScreenSizeInches: 9.0, headUpDisplay: 'standard', androidAuto: 'standard', appleCarPlay: 'standard', wirelessAndroidAuto: 'standard', wirelessAppleCarPlay: 'standard', premiumAudio: 'standard', connectedCarTechnology: 'standard', speakerCount: 6 },
        convenience: { pushButtonStart: 'standard', keylessEntry: 'standard', cruiseControl: 'standard', autoDimmingIRVM: 'standard' },
      }),
    },
  ],

  // ─────────────────────────────────────────────────────────────
  // 13. MARUTI SUZUKI GRAND VITARA
  // ─────────────────────────────────────────────────────────────
  'maruti-suzuki-grand-vitara': [
    {
      id: 'maruti-suzuki-grand-vitara-sigma',
      name: 'Sigma Mild Hybrid',
      fullName: 'Maruti Suzuki Grand Vitara Sigma 1.5 Mild Hybrid 5MT',
      slug: 'sigma',
      trim: 'Sigma',
      variantStatus: 'verified',
      pricing: { exShowroom: 1099000, exShowroomLakh: 10.99, currency: 'INR' },
      powertrain: {
        fuelType: 'MildHybrid',
        engineName: '1.5L K15C DualJet Mild Hybrid',
        engineDisplacementCC: 1462,
        cylinders: 4,
        aspiration: 'Naturally Aspirated',
        maxPowerBhp: 102,
        maxTorqueNm: 137,
        transmission: 'Manual',
        drivetrain: 'FWD',
        batteryCapacityKWh: null,
        electricMotorPowerBhp: null,
        electricRangeKm: null,
      },
      performance: { mileageKmpl: 21.11, zeroToHundredSec: 12.3, topSpeedKmph: 175 },
      dimensions: { lengthMm: 4345, widthMm: 1795, heightMm: 1645, wheelbaseMm: 2600, groundClearanceMm: 208, kerbWeightKg: 1185, bootSpaceLitres: 373, fuelTankLitres: 45 },
      features: makeStandardFeatures({
        safety: { airbagsCount: 2, abs: 'standard', esc: 'standard', hillAssist: 'standard', rearParkingSensors: 'standard' },
        exterior: { wheelSizeInches: 17, alloyWheels: 'not_available', ledHeadlights: 'standard', ledDRLs: 'standard' },
        interior: { automaticClimateControl: 'standard', rearACVents: 'standard' },
        infotainment: { infotainmentScreenSizeInches: null, speakerCount: 0 },
        convenience: { pushButtonStart: 'standard', keylessEntry: 'standard' },
      }),
    },
    {
      id: 'maruti-suzuki-grand-vitara-alpha-plus-hybrid',
      name: 'Alpha+ Strong Hybrid',
      fullName: 'Maruti Suzuki Grand Vitara Alpha+ 1.5 Strong Hybrid e-CVT',
      slug: 'alpha-plus-hybrid',
      trim: 'Alpha+',
      variantStatus: 'verified',
      pricing: { exShowroom: 2009000, exShowroomLakh: 20.09, currency: 'INR' },
      powertrain: {
        fuelType: 'StrongHybrid',
        engineName: '1.5L Intelligent Electric Hybrid System',
        engineDisplacementCC: 1490,
        cylinders: 3,
        aspiration: 'Naturally Aspirated',
        maxPowerBhp: 114,
        maxTorqueNm: 141,
        transmission: 'CVT',
        drivetrain: 'FWD',
        batteryCapacityKWh: 0.76,
        electricMotorPowerBhp: 79,
        electricRangeKm: null,
      },
      performance: { mileageKmpl: 27.97, zeroToHundredSec: 11.5, topSpeedKmph: 180 },
      dimensions: { lengthMm: 4345, widthMm: 1795, heightMm: 1645, wheelbaseMm: 2600, groundClearanceMm: 208, kerbWeightKg: 1295, bootSpaceLitres: 265, fuelTankLitres: 45 },
      features: makeStandardFeatures({
        safety: { airbagsCount: 6, abs: 'standard', esc: 'standard', hillAssist: 'standard', threeSixtyCamera: 'standard', rearCamera: 'standard', tpms: 'standard' },
        exterior: { wheelSizeInches: 17, alloyWheels: 'standard', ledHeadlights: 'standard', ledDRLs: 'standard', panoramicSunroof: 'standard', sunroof: 'standard', roofRails: 'standard' },
        interior: {
          automaticClimateControl: 'standard',
          rearACVents: 'standard',
          ventilatedSeats: 'standard',
          leatherSeats: 'standard',
          wirelessCharging: 'standard',
          ambientLighting: 'standard',
        },
        infotainment: {
          infotainmentScreenSizeInches: 9.0,
          headUpDisplay: 'standard',
          digitalInstrumentCluster: 'standard',
          androidAuto: 'standard',
          appleCarPlay: 'standard',
          wirelessAndroidAuto: 'standard',
          wirelessAppleCarPlay: 'standard',
          premiumAudio: 'standard',
          connectedCarTechnology: 'standard',
          speakerCount: 6,
        },
        convenience: { pushButtonStart: 'standard', keylessEntry: 'standard', cruiseControl: 'standard', autoDimmingIRVM: 'standard', rainSensingWipers: 'standard', automaticHeadlights: 'standard' },
      }),
    },
  ],

  // ─────────────────────────────────────────────────────────────
  // 14. MAHINDRA XUV 3XO (Compact SUV with Level 2 ADAS)
  // ─────────────────────────────────────────────────────────────
  'mahindra-xuv-3xo': [
    {
      id: 'mahindra-xuv-3xo-mx1',
      name: 'MX1 1.2 Petrol',
      fullName: 'Mahindra XUV 3XO MX1 1.2 TCMPFi Petrol 6MT',
      slug: 'mx1',
      trim: 'MX1',
      variantStatus: 'verified',
      pricing: { exShowroom: 749000, exShowroomLakh: 7.49, currency: 'INR' },
      powertrain: {
        fuelType: 'Petrol',
        engineName: '1.2L mStallion TCMPFi Turbo',
        engineDisplacementCC: 1197,
        cylinders: 3,
        aspiration: 'Turbocharged',
        maxPowerBhp: 110,
        maxTorqueNm: 200,
        transmission: 'Manual',
        drivetrain: 'FWD',
        batteryCapacityKWh: null,
        electricMotorPowerBhp: null,
        electricRangeKm: null,
      },
      performance: { mileageKmpl: 18.89, zeroToHundredSec: 11.2, topSpeedKmph: 175 },
      dimensions: { lengthMm: 3990, widthMm: 1821, heightMm: 1647, wheelbaseMm: 2600, groundClearanceMm: 201, kerbWeightKg: 1250, bootSpaceLitres: 295, fuelTankLitres: 42 },
      features: makeStandardFeatures({
        safety: { airbagsCount: 6, abs: 'standard', esc: 'standard', hillAssist: 'standard', rearParkingSensors: 'standard' },
        exterior: { wheelSizeInches: 16, alloyWheels: 'not_available', ledHeadlights: 'standard', ledDRLs: 'standard' },
        interior: { airConditioning: 'standard', rearACVents: 'standard' },
        infotainment: { infotainmentScreenSizeInches: null, speakerCount: 0 },
      }),
    },
    {
      id: 'mahindra-xuv-3xo-ax7l-tgdi-at',
      name: 'AX7L TGDi AT',
      fullName: 'Mahindra XUV 3XO AX7L 1.2 mStallion TGDi 6AT (with Level 2 ADAS)',
      slug: 'ax7l-tgdi-at',
      trim: 'AX7L',
      variantStatus: 'verified',
      pricing: { exShowroom: 1549000, exShowroomLakh: 15.49, currency: 'INR' },
      powertrain: {
        fuelType: 'Petrol',
        engineName: '1.2L Direct-Injection TGDi Turbo',
        engineDisplacementCC: 1197,
        cylinders: 3,
        aspiration: 'Turbocharged',
        maxPowerBhp: 129,
        maxTorqueNm: 230,
        transmission: 'Automatic',
        drivetrain: 'FWD',
        batteryCapacityKWh: null,
        electricMotorPowerBhp: null,
        electricRangeKm: null,
      },
      performance: { mileageKmpl: 18.2, zeroToHundredSec: 9.3, topSpeedKmph: 185 },
      dimensions: { lengthMm: 3990, widthMm: 1821, heightMm: 1647, wheelbaseMm: 2600, groundClearanceMm: 201, kerbWeightKg: 1310, bootSpaceLitres: 295, fuelTankLitres: 42 },
      features: makeStandardFeatures({
        safety: {
          airbagsCount: 6,
          abs: 'standard',
          esc: 'standard',
          threeSixtyCamera: 'standard',
          rearCamera: 'standard',
          blindSpotMonitoring: 'standard',
          laneDepartureWarning: 'standard',
          laneKeepAssist: 'standard',
          adaptiveCruiseControl: 'standard',
          forwardCollisionWarning: 'standard',
          autonomousEmergencyBraking: 'standard',
          adasLevel: 'Level 2',
          tpms: 'standard',
        },
        exterior: { wheelSizeInches: 17, alloyWheels: 'standard', ledHeadlights: 'standard', ledDRLs: 'standard', fogLights: 'standard', panoramicSunroof: 'standard', sunroof: 'standard', roofRails: 'standard' },
        interior: {
          automaticClimateControl: 'standard',
          rearACVents: 'standard',
          leatherSeats: 'standard',
          wirelessCharging: 'standard',
        },
        infotainment: {
          infotainmentScreenSizeInches: 10.25,
          digitalInstrumentCluster: 'standard',
          androidAuto: 'standard',
          appleCarPlay: 'standard',
          wirelessAndroidAuto: 'standard',
          wirelessAppleCarPlay: 'standard',
          premiumAudio: 'standard',
          connectedCarTechnology: 'standard',
          speakerCount: 7,
        },
        convenience: { pushButtonStart: 'standard', keylessEntry: 'standard', cruiseControl: 'standard', adaptiveCruiseControl: 'standard', autoDimmingIRVM: 'standard', rainSensingWipers: 'standard', automaticHeadlights: 'standard' },
      }),
    },
  ],

  // ─────────────────────────────────────────────────────────────
  // 15. TATA HARRIER (2024-2026 Facelift ADAS Level 2)
  // ─────────────────────────────────────────────────────────────
  'tata-harrier': [
    {
      id: 'tata-harrier-smart',
      name: 'Smart',
      fullName: 'Tata Harrier Smart 2.0 Kryotec Diesel 6MT',
      slug: 'smart',
      trim: 'Smart',
      variantStatus: 'verified',
      pricing: { exShowroom: 1549000, exShowroomLakh: 15.49, currency: 'INR' },
      powertrain: {
        fuelType: 'Diesel',
        engineName: '2.0L Kryotec Turbocharged Diesel',
        engineDisplacementCC: 1956,
        cylinders: 4,
        aspiration: 'Turbocharged',
        maxPowerBhp: 168,
        maxTorqueNm: 350,
        transmission: 'Manual',
        drivetrain: 'FWD',
        batteryCapacityKWh: null,
        electricMotorPowerBhp: null,
        electricRangeKm: null,
      },
      performance: { mileageKmpl: 16.8, zeroToHundredSec: 10.3, topSpeedKmph: 180 },
      dimensions: { lengthMm: 4605, widthMm: 1922, heightMm: 1718, wheelbaseMm: 2741, groundClearanceMm: 205, kerbWeightKg: 1680, bootSpaceLitres: 445, fuelTankLitres: 50 },
      features: makeStandardFeatures({
        safety: { airbagsCount: 6, abs: 'standard', esc: 'standard', hillAssist: 'standard', rearParkingSensors: 'standard', ncapRating: 5 },
        exterior: { wheelSizeInches: 17, alloyWheels: 'not_available', ledHeadlights: 'standard', ledDRLs: 'standard' },
        interior: { airConditioning: 'standard', rearACVents: 'standard' },
        infotainment: { infotainmentScreenSizeInches: null, speakerCount: 0 },
      }),
    },
    {
      id: 'tata-harrier-fearless-plus-dark-at',
      name: 'Fearless+ Dark Edition AT',
      fullName: 'Tata Harrier Fearless Plus Dark Edition 2.0 Diesel 6AT (Level 2 ADAS)',
      slug: 'fearless-plus-dark-at',
      trim: 'Fearless+',
      variantStatus: 'verified',
      pricing: { exShowroom: 2644000, exShowroomLakh: 26.44, currency: 'INR' },
      powertrain: {
        fuelType: 'Diesel',
        engineName: '2.0L Kryotec Turbocharged Diesel',
        engineDisplacementCC: 1956,
        cylinders: 4,
        aspiration: 'Turbocharged',
        maxPowerBhp: 168,
        maxTorqueNm: 350,
        transmission: 'Automatic',
        drivetrain: 'FWD',
        batteryCapacityKWh: null,
        electricMotorPowerBhp: null,
        electricRangeKm: null,
      },
      performance: { mileageKmpl: 14.6, zeroToHundredSec: 9.9, topSpeedKmph: 185 },
      dimensions: { lengthMm: 4605, widthMm: 1922, heightMm: 1718, wheelbaseMm: 2741, groundClearanceMm: 205, kerbWeightKg: 1730, bootSpaceLitres: 445, fuelTankLitres: 50 },
      features: makeStandardFeatures({
        safety: {
          airbagsCount: 7,
          abs: 'standard',
          esc: 'standard',
          threeSixtyCamera: 'standard',
          rearCamera: 'standard',
          blindSpotMonitoring: 'standard',
          laneDepartureWarning: 'standard',
          laneKeepAssist: 'standard',
          adaptiveCruiseControl: 'standard',
          forwardCollisionWarning: 'standard',
          autonomousEmergencyBraking: 'standard',
          adasLevel: 'Level 2',
          tpms: 'standard',
          ncapRating: 5,
        },
        exterior: { wheelSizeInches: 19, alloyWheels: 'standard', ledHeadlights: 'standard', ledDRLs: 'standard', fogLights: 'standard', panoramicSunroof: 'standard', sunroof: 'standard', poweredTailgate: 'standard' },
        interior: {
          automaticClimateControl: 'standard',
          rearACVents: 'standard',
          ventilatedSeats: 'standard',
          poweredDriverSeat: 'standard',
          poweredPassengerSeat: 'standard',
          leatherSeats: 'standard',
          wirelessCharging: 'standard',
          ambientLighting: 'standard',
        },
        infotainment: {
          infotainmentScreenSizeInches: 12.3,
          digitalInstrumentCluster: 'standard',
          androidAuto: 'standard',
          appleCarPlay: 'standard',
          wirelessAndroidAuto: 'standard',
          wirelessAppleCarPlay: 'standard',
          premiumAudio: 'standard',
          connectedCarTechnology: 'standard',
          speakerCount: 10,
        },
        convenience: { pushButtonStart: 'standard', keylessEntry: 'standard', cruiseControl: 'standard', adaptiveCruiseControl: 'standard', autoDimmingIRVM: 'standard', rainSensingWipers: 'standard', automaticHeadlights: 'standard' },
      }),
    },
  ],

  // ─────────────────────────────────────────────────────────────
  // 16. HYUNDAI VENUE
  // ─────────────────────────────────────────────────────────────
  'hyundai-venue': [
    {
      id: 'hyundai-venue-e',
      name: 'E 1.2 Petrol',
      fullName: 'Hyundai Venue E 1.2 Kappa Petrol 5MT',
      slug: 'e-1-2-petrol',
      trim: 'E',
      variantStatus: 'verified',
      pricing: { exShowroom: 794000, exShowroomLakh: 7.94, currency: 'INR' },
      powertrain: {
        fuelType: 'Petrol',
        engineName: '1.2L Kappa MPi Petrol',
        engineDisplacementCC: 1197,
        cylinders: 4,
        aspiration: 'Naturally Aspirated',
        maxPowerBhp: 82,
        maxTorqueNm: 114,
        transmission: 'Manual',
        drivetrain: 'FWD',
        batteryCapacityKWh: null,
        electricMotorPowerBhp: null,
        electricRangeKm: null,
      },
      performance: { mileageKmpl: 17.5, zeroToHundredSec: 13.8, topSpeedKmph: 165 },
      dimensions: { lengthMm: 3995, widthMm: 1770, heightMm: 1617, wheelbaseMm: 2500, groundClearanceMm: 195, kerbWeightKg: 1080, bootSpaceLitres: 350, fuelTankLitres: 45 },
      features: makeStandardFeatures({
        safety: { airbagsCount: 6, abs: 'standard', esc: 'standard', hillAssist: 'standard', rearParkingSensors: 'standard', tpms: 'standard' },
        exterior: { wheelSizeInches: 15, alloyWheels: 'not_available' },
        interior: { airConditioning: 'standard', rearACVents: 'standard' },
        infotainment: { infotainmentScreenSizeInches: null, speakerCount: 0 },
      }),
    },
    {
      id: 'hyundai-venue-sx-o-turbo-dct',
      name: 'SX(O) 1.0 Turbo DCT',
      fullName: 'Hyundai Venue SX(O) 1.0 Turbo GDi 7DCT (Level 1 ADAS)',
      slug: 'sx-o-turbo-dct',
      trim: 'SX(O)',
      variantStatus: 'verified',
      pricing: { exShowroom: 1348000, exShowroomLakh: 13.48, currency: 'INR' },
      powertrain: {
        fuelType: 'Petrol',
        engineName: '1.0L Turbo GDi Petrol',
        engineDisplacementCC: 998,
        cylinders: 3,
        aspiration: 'Turbocharged',
        maxPowerBhp: 118,
        maxTorqueNm: 172,
        transmission: 'DCT',
        drivetrain: 'FWD',
        batteryCapacityKWh: null,
        electricMotorPowerBhp: null,
        electricRangeKm: null,
      },
      performance: { mileageKmpl: 18.3, zeroToHundredSec: 10.7, topSpeedKmph: 180 },
      dimensions: { lengthMm: 3995, widthMm: 1770, heightMm: 1617, wheelbaseMm: 2500, groundClearanceMm: 195, kerbWeightKg: 1160, bootSpaceLitres: 350, fuelTankLitres: 45 },
      features: makeStandardFeatures({
        safety: {
          airbagsCount: 6,
          abs: 'standard',
          esc: 'standard',
          rearCamera: 'standard',
          laneDepartureWarning: 'standard',
          laneKeepAssist: 'standard',
          forwardCollisionWarning: 'standard',
          autonomousEmergencyBraking: 'standard',
          adasLevel: 'Level 1',
          tpms: 'standard',
        },
        exterior: { wheelSizeInches: 16, alloyWheels: 'standard', ledHeadlights: 'standard', ledDRLs: 'standard', sunroof: 'standard', roofRails: 'standard' },
        interior: {
          automaticClimateControl: 'standard',
          rearACVents: 'standard',
          poweredDriverSeat: 'standard',
          leatherSeats: 'standard',
          wirelessCharging: 'standard',
          ambientLighting: 'standard',
        },
        infotainment: {
          infotainmentScreenSizeInches: 8.0,
          digitalInstrumentCluster: 'standard',
          androidAuto: 'standard',
          appleCarPlay: 'standard',
          connectedCarTechnology: 'standard',
          speakerCount: 6,
        },
        convenience: { pushButtonStart: 'standard', keylessEntry: 'standard', cruiseControl: 'standard', autoDimmingIRVM: 'standard', automaticHeadlights: 'standard' },
      }),
    },
  ],

  // ─────────────────────────────────────────────────────────────
  // 17. HONDA CITY (5th Generation)
  // ─────────────────────────────────────────────────────────────
  'honda-city': [
    {
      id: 'honda-city-sv',
      name: 'SV Petrol',
      fullName: 'Honda City SV 1.5 i-VTEC Petrol 6MT',
      slug: 'sv',
      trim: 'SV',
      variantStatus: 'verified',
      pricing: { exShowroom: 1208000, exShowroomLakh: 12.08, currency: 'INR' },
      powertrain: {
        fuelType: 'Petrol',
        engineName: '1.5L i-VTEC DOHC with VTC',
        engineDisplacementCC: 1498,
        cylinders: 4,
        aspiration: 'Naturally Aspirated',
        maxPowerBhp: 119,
        maxTorqueNm: 145,
        transmission: 'Manual',
        drivetrain: 'FWD',
        batteryCapacityKWh: null,
        electricMotorPowerBhp: null,
        electricRangeKm: null,
      },
      performance: { mileageKmpl: 17.8, zeroToHundredSec: 10.2, topSpeedKmph: 190 },
      dimensions: { lengthMm: 4574, widthMm: 1748, heightMm: 1489, wheelbaseMm: 2600, groundClearanceMm: 165, kerbWeightKg: 1107, bootSpaceLitres: 506, fuelTankLitres: 40 },
      features: makeStandardFeatures({
        safety: { airbagsCount: 4, abs: 'standard', esc: 'standard', hillAssist: 'standard', rearParkingSensors: 'standard', rearCamera: 'standard', tpms: 'standard', ncapRating: 5 },
        exterior: { wheelSizeInches: 15, alloyWheels: 'not_available', ledDRLs: 'standard' },
        interior: { automaticClimateControl: 'standard', rearACVents: 'standard' },
        infotainment: { infotainmentScreenSizeInches: 8.0, androidAuto: 'standard', appleCarPlay: 'standard', wirelessAndroidAuto: 'standard', wirelessAppleCarPlay: 'standard', speakerCount: 4 },
        convenience: { pushButtonStart: 'standard', keylessEntry: 'standard', cruiseControl: 'standard' },
      }),
    },
    {
      id: 'honda-city-zx-cvt',
      name: 'ZX CVT',
      fullName: 'Honda City ZX 1.5 i-VTEC CVT (Honda Sensing ADAS)',
      slug: 'zx-cvt',
      trim: 'ZX',
      variantStatus: 'verified',
      pricing: { exShowroom: 1635000, exShowroomLakh: 16.35, currency: 'INR' },
      powertrain: {
        fuelType: 'Petrol',
        engineName: '1.5L i-VTEC DOHC with VTC',
        engineDisplacementCC: 1498,
        cylinders: 4,
        aspiration: 'Naturally Aspirated',
        maxPowerBhp: 119,
        maxTorqueNm: 145,
        transmission: 'CVT',
        drivetrain: 'FWD',
        batteryCapacityKWh: null,
        electricMotorPowerBhp: null,
        electricRangeKm: null,
      },
      performance: { mileageKmpl: 18.4, zeroToHundredSec: 10.6, topSpeedKmph: 190 },
      dimensions: { lengthMm: 4574, widthMm: 1748, heightMm: 1489, wheelbaseMm: 2600, groundClearanceMm: 165, kerbWeightKg: 1153, bootSpaceLitres: 506, fuelTankLitres: 40 },
      features: makeStandardFeatures({
        safety: {
          airbagsCount: 6,
          abs: 'standard',
          esc: 'standard',
          hillAssist: 'standard',
          rearCamera: 'standard',
          blindSpotMonitoring: 'standard',
          laneDepartureWarning: 'standard',
          laneKeepAssist: 'standard',
          adaptiveCruiseControl: 'standard',
          forwardCollisionWarning: 'standard',
          autonomousEmergencyBraking: 'standard',
          adasLevel: 'Level 2',
          tpms: 'standard',
          ncapRating: 5,
        },
        exterior: { wheelSizeInches: 16, alloyWheels: 'standard', ledHeadlights: 'standard', ledDRLs: 'standard', fogLights: 'standard', sunroof: 'standard' },
        interior: {
          automaticClimateControl: 'standard',
          rearACVents: 'standard',
          leatherSeats: 'standard',
          wirelessCharging: 'standard',
          ambientLighting: 'standard',
        },
        infotainment: {
          infotainmentScreenSizeInches: 8.0,
          digitalInstrumentCluster: 'standard',
          androidAuto: 'standard',
          appleCarPlay: 'standard',
          wirelessAndroidAuto: 'standard',
          wirelessAppleCarPlay: 'standard',
          premiumAudio: 'standard',
          connectedCarTechnology: 'standard',
          speakerCount: 8,
        },
        convenience: { pushButtonStart: 'standard', keylessEntry: 'standard', cruiseControl: 'standard', adaptiveCruiseControl: 'standard', autoDimmingIRVM: 'standard', rainSensingWipers: 'standard', automaticHeadlights: 'standard' },
      }),
    },
  ],

  // ─────────────────────────────────────────────────────────────
  // 18. VOLKSWAGEN VIRTUS (5-Star Global NCAP Sedan)
  // ─────────────────────────────────────────────────────────────
  'volkswagen-virtus': [
    {
      id: 'volkswagen-virtus-comfortline-1-0-tsi',
      name: 'Comfortline 1.0 TSI',
      fullName: 'Volkswagen Virtus Comfortline 1.0 TSI 6MT',
      slug: 'comfortline-1-0-tsi',
      trim: 'Comfortline',
      variantStatus: 'verified',
      pricing: { exShowroom: 1156000, exShowroomLakh: 11.56, currency: 'INR' },
      powertrain: {
        fuelType: 'Petrol',
        engineName: '1.0L TSI Turbocharged Stratified Injection',
        engineDisplacementCC: 999,
        cylinders: 3,
        aspiration: 'Turbocharged',
        maxPowerBhp: 114,
        maxTorqueNm: 178,
        transmission: 'Manual',
        drivetrain: 'FWD',
        batteryCapacityKWh: null,
        electricMotorPowerBhp: null,
        electricRangeKm: null,
      },
      performance: { mileageKmpl: 20.8, zeroToHundredSec: 10.4, topSpeedKmph: 190 },
      dimensions: { lengthMm: 4561, widthMm: 1752, heightMm: 1507, wheelbaseMm: 2651, groundClearanceMm: 179, kerbWeightKg: 1190, bootSpaceLitres: 521, fuelTankLitres: 45 },
      features: makeStandardFeatures({
        safety: { airbagsCount: 6, abs: 'standard', esc: 'standard', hillAssist: 'standard', rearParkingSensors: 'standard', tpms: 'standard', ncapRating: 5 },
        exterior: { wheelSizeInches: 16, alloyWheels: 'not_available', ledHeadlights: 'standard', ledDRLs: 'standard' },
        interior: { airConditioning: 'standard', rearACVents: 'standard' },
        infotainment: { infotainmentScreenSizeInches: 7.0, androidAuto: 'standard', appleCarPlay: 'standard', speakerCount: 6 },
        convenience: { keylessEntry: 'standard' },
      }),
    },
    {
      id: 'volkswagen-virtus-gt-plus-1-5-tsi-dsg',
      name: 'GT Plus 1.5 TSI DSG',
      fullName: 'Volkswagen Virtus GT Plus 1.5 TSI 7-Speed DSG',
      slug: 'gt-plus-1-5-tsi-dsg',
      trim: 'GT Plus',
      variantStatus: 'verified',
      pricing: { exShowroom: 1941000, exShowroomLakh: 19.41, currency: 'INR' },
      powertrain: {
        fuelType: 'Petrol',
        engineName: '1.5L TSI EVO with Active Cylinder Tech',
        engineDisplacementCC: 1498,
        cylinders: 4,
        aspiration: 'Turbocharged',
        maxPowerBhp: 148,
        maxTorqueNm: 250,
        transmission: 'DCT',
        drivetrain: 'FWD',
        batteryCapacityKWh: null,
        electricMotorPowerBhp: null,
        electricRangeKm: null,
      },
      performance: { mileageKmpl: 19.62, zeroToHundredSec: 8.8, topSpeedKmph: 205 },
      dimensions: { lengthMm: 4561, widthMm: 1752, heightMm: 1507, wheelbaseMm: 2651, groundClearanceMm: 179, kerbWeightKg: 1260, bootSpaceLitres: 521, fuelTankLitres: 45 },
      features: makeStandardFeatures({
        safety: { airbagsCount: 6, abs: 'standard', esc: 'standard', hillAssist: 'standard', rearCamera: 'standard', tpms: 'standard', ncapRating: 5 },
        exterior: { wheelSizeInches: 16, alloyWheels: 'standard', ledHeadlights: 'standard', ledDRLs: 'standard', fogLights: 'standard', sunroof: 'standard' },
        interior: {
          automaticClimateControl: 'standard',
          rearACVents: 'standard',
          ventilatedSeats: 'standard',
          leatherSeats: 'standard',
          wirelessCharging: 'standard',
          ambientLighting: 'standard',
        },
        infotainment: {
          infotainmentScreenSizeInches: 10.1,
          digitalInstrumentCluster: 'standard',
          androidAuto: 'standard',
          appleCarPlay: 'standard',
          wirelessAndroidAuto: 'standard',
          wirelessAppleCarPlay: 'standard',
          premiumAudio: 'standard',
          connectedCarTechnology: 'standard',
          speakerCount: 8,
        },
        convenience: { pushButtonStart: 'standard', keylessEntry: 'standard', cruiseControl: 'standard', autoDimmingIRVM: 'standard', rainSensingWipers: 'standard', automaticHeadlights: 'standard' },
      }),
    },
  ],
};
