/**
 * scripts/patch_inventory_audit.ts
 *
 * Implements the additions, corrections, and status updates discovered
 * during the October 2026 market coverage and data-quality audit.
 */

import * as fs from 'fs';
import * as path from 'path';

const inventoryFile = path.join(__dirname, 'build_full_inventory.ts');
let content = fs.readFileSync(inventoryFile, 'utf8');

// 1. Add VinFast to MANUFACTURERS_DATA if not present
if (!content.includes('vinfast-india')) {
  const vinfastManufacturer = `  {
    name: 'VinFast Auto India Private Limited',
    slug: 'vinfast-india',
    country: 'Vietnam',
    website: 'https://vinfastauto.in',
    status: 'ACTIVE',
    category: 'Mass Market',
    headquarters: 'Thoothukudi, Tamil Nadu, India',
    sourceUrl: 'https://vinfastauto.in',
    lastVerified: '2026-10-05',
    brands: [
      { name: 'VinFast', slug: 'vinfast', website: 'https://vinfastauto.in', status: 'ACTIVE' },
    ],
  },
];`;
  content = content.replace(/\];\s*\/\/\s*═+\s*\/\/\s*2\.\s*EXHAUSTIVE/, `${vinfastManufacturer}\n\n// ═══════════════════════════════════════════════════════════════════════════════\n// 2. EXHAUSTIVE`);
}

// 2. Remove duplicate Honda City e:HEV and merge into Honda City
if (content.includes('modelName: \'City e:HEV\'')) {
  // Update Honda City specs to include StrongHybrid
  const oldCityRegex = /{\s*manufacturerName:\s*'Honda Cars India Limited',\s*brandName:\s*'Honda',\s*brandSlug:\s*'honda',\s*modelName:\s*'City',[\s\S]*?verificationStatus:\s*'VERIFIED',\s*},\s*{\s*manufacturerName:\s*'Honda Cars India Limited',\s*brandName:\s*'Honda',\s*brandSlug:\s*'honda',\s*modelName:\s*'City e:HEV',[\s\S]*?verificationStatus:\s*'VERIFIED',\s*},/;

  const mergedCity = `{
    manufacturerName: 'Honda Cars India Limited',
    brandName: 'Honda',
    brandSlug: 'honda',
    modelName: 'City',
    slug: 'honda-city',
    status: 'ACTIVE',
    bodyType: 'Sedan',
    segment: 'C-Segment Mid-size Sedan (ICE & e:HEV Strong Hybrid)',
    fuelTypes: ['Petrol', 'StrongHybrid'],
    priceRangeLakhs: { min: 12.08, max: 20.55 },
    rebadgedFromOrSharedWith: null,
    notes: '5th generation mid-size sedan with 1.5L DOHC i-VTEC petrol and e:HEV dual-motor self-charging hybrid option with Honda Sensing ADAS.',
    source: 'Honda Cars India Official',
    sourceUrl: 'https://www.hondacarindia.com/honda-city',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },`;

  content = content.replace(oldCityRegex, mergedCity);
}

// 3. Remove Duster from DISCONTINUED_MODELS_DATA
const oldDusterRegex = /{\s*manufacturerName:\s*'Renault India Private Limited',\s*brandName:\s*'Renault',\s*brandSlug:\s*'renault',\s*modelName:\s*'Duster',[\s\S]*?verificationStatus:\s*'VERIFIED',\s*},/;
content = content.replace(oldDusterRegex, '');

// 4. Remove Kylaq and EV9 from UPCOMING_MODELS_DATA
const oldKylaqRegex = /{\s*manufacturerName:\s*'Skoda Auto Volkswagen India Private Limited',\s*brandName:\s*'Skoda',\s*brandSlug:\s*'skoda',\s*modelName:\s*'Kylaq',[\s\S]*?verificationStatus:\s*'VERIFIED',\s*},/;
content = content.replace(oldKylaqRegex, '');

const oldEv9Regex = /{\s*manufacturerName:\s*'Kia India Private Limited',\s*brandName:\s*'Kia',\s*brandSlug:\s*'kia',\s*modelName:\s*'EV9',[\s\S]*?verificationStatus:\s*'VERIFIED',\s*},/;
content = content.replace(oldEv9Regex, '');

// 5. Build additional active models
const newActiveModels = [
  // Nissan additions
  {
    manufacturerName: 'Nissan Motor India Private Limited',
    brandName: 'Nissan',
    brandSlug: 'nissan',
    modelName: 'Gravite',
    slug: 'nissan-gravite',
    status: 'ACTIVE',
    bodyType: 'MPV',
    segment: 'Sub-4m Modular 7-Seater MPV',
    fuelTypes: ['Petrol', 'CNG'],
    priceRangeLakhs: { min: 5.73, max: 9.38 },
    rebadgedFromOrSharedWith: 'Renault Triber (CMF-A+ Platform)',
    notes: 'Sub-4m modular 7-seater MPV with 1.0L petrol and CNG options, removable 3rd row, and 625L max boot space.',
    source: 'Nissan Motor India Official',
    sourceUrl: 'https://www.nissan.in/vehicles/new/gravite.html',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },
  {
    manufacturerName: 'Nissan Motor India Private Limited',
    brandName: 'Nissan',
    brandSlug: 'nissan',
    modelName: 'Tekton',
    slug: 'nissan-tekton',
    status: 'ACTIVE',
    bodyType: 'SUV',
    segment: 'Mid-size C-SUV (CMF-B Platform)',
    fuelTypes: ['Petrol'],
    priceRangeLakhs: { min: 10.49, max: 18.59 },
    rebadgedFromOrSharedWith: 'Renault Duster (CMF-B Platform)',
    notes: 'Premium midsize SUV with 1.0L Turbo and 1.3L Turbo (163 PS / 280 Nm) engines, 212mm ground clearance, and 5-star BNCAP safety rating.',
    source: 'Nissan Motor India Official',
    sourceUrl: 'https://www.nissan.in/vehicles/new/tekton.html',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },

  // Renault Duster (Reintroduced 2026)
  {
    manufacturerName: 'Renault India Private Limited',
    brandName: 'Renault',
    brandSlug: 'renault',
    modelName: 'Duster',
    slug: 'renault-duster',
    status: 'ACTIVE',
    bodyType: 'SUV',
    segment: 'Mid-size Rugged Monocoque SUV (CMF-B)',
    fuelTypes: ['Petrol', 'StrongHybrid'],
    priceRangeLakhs: { min: 10.49, max: 16.89 },
    rebadgedFromOrSharedWith: 'Nissan Tekton (CMF-B Platform)',
    notes: 'All-new 3rd-generation Duster launched March 2026 on CMF-B platform with TCe turbocharged petrol and E-Tech strong hybrid options.',
    source: 'Renault India Official Launch',
    sourceUrl: 'https://www.renault.co.in/cars/duster.html',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },

  // Skoda Kylaq (Launched Nov 2024)
  {
    manufacturerName: 'Skoda Auto Volkswagen India Private Limited',
    brandName: 'Skoda',
    brandSlug: 'skoda',
    modelName: 'Kylaq',
    slug: 'skoda-kylaq',
    status: 'ACTIVE',
    bodyType: 'Compact SUV',
    segment: 'Sub-4m Compact SUV (MQB-A0-IN)',
    fuelTypes: ['Petrol'],
    priceRangeLakhs: { min: 7.89, max: 14.40 },
    rebadgedFromOrSharedWith: null,
    notes: 'Sub-4m MQB-A0-IN compact SUV powered by 1.0L TSI (115 PS / 178 Nm); 5-star safety rating.',
    source: 'Skoda Auto India Official World Premiere',
    sourceUrl: 'https://www.skoda-auto.co.in/models/kylaq/kylaq',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },

  // Kia EV9 (Launched Oct 2024)
  {
    manufacturerName: 'Kia India Private Limited',
    brandName: 'Kia',
    brandSlug: 'kia',
    modelName: 'EV9',
    slug: 'kia-ev9',
    status: 'ACTIVE',
    bodyType: 'SUV',
    segment: 'Flagship 3-Row Electric Luxury SUV (E-GMP)',
    fuelTypes: ['Electric'],
    priceRangeLakhs: { min: 130.00, max: 130.00 },
    rebadgedFromOrSharedWith: null,
    notes: 'World Car of the Year 2024; 99.8 kWh battery with 561 km range and dual motor AWD (384 PS).',
    source: 'Kia India Official Launch',
    sourceUrl: 'https://www.kia.com/in/our-vehicles/ev9/showroom.html',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },

  // VinFast Active Lineup
  {
    manufacturerName: 'VinFast Auto India Private Limited',
    brandName: 'VinFast',
    brandSlug: 'vinfast',
    modelName: 'VF 6',
    slug: 'vinfast-vf-6',
    status: 'ACTIVE',
    bodyType: 'Compact SUV',
    segment: 'Electric Compact B-SUV',
    fuelTypes: ['Electric'],
    priceRangeLakhs: { min: 18.00, max: 22.00 },
    rebadgedFromOrSharedWith: null,
    notes: 'Compact electric SUV with 59.6 kWh battery, Pininfarina styling, and up to 399 km WLTP range.',
    source: 'VinFast Auto India Official',
    sourceUrl: 'https://vinfastauto.in/models/vf6',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },
  {
    manufacturerName: 'VinFast Auto India Private Limited',
    brandName: 'VinFast',
    brandSlug: 'vinfast',
    modelName: 'VF 7',
    slug: 'vinfast-vf-7',
    status: 'ACTIVE',
    bodyType: 'SUV',
    segment: 'Electric Mid-size C-SUV',
    fuelTypes: ['Electric'],
    priceRangeLakhs: { min: 24.00, max: 30.00 },
    rebadgedFromOrSharedWith: null,
    notes: 'Sporty electric SUV with 75.3 kWh battery, dual motor AWD producing 353 PS, and Torino Design styling.',
    source: 'VinFast Auto India Official',
    sourceUrl: 'https://vinfastauto.in/models/vf7',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },
  {
    manufacturerName: 'VinFast Auto India Private Limited',
    brandName: 'VinFast',
    brandSlug: 'vinfast',
    modelName: 'VF MPV 7',
    slug: 'vinfast-vf-mpv-7',
    status: 'ACTIVE',
    bodyType: 'MPV',
    segment: 'Electric 7-Seater Family MPV',
    fuelTypes: ['Electric'],
    priceRangeLakhs: { min: 22.00, max: 27.00 },
    rebadgedFromOrSharedWith: null,
    notes: 'Spacious 7-seater electric MPV designed for family touring and executive fleet transport.',
    source: 'VinFast Auto India Official',
    sourceUrl: 'https://vinfastauto.in/models/vf-mpv-7',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },

  // Audi additions
  {
    manufacturerName: 'Skoda Auto Volkswagen India Private Limited',
    brandName: 'Audi',
    brandSlug: 'audi',
    modelName: 'A8 L',
    slug: 'audi-a8-l',
    status: 'ACTIVE',
    bodyType: 'Sedan',
    segment: 'Pinnacle Luxury Flagship Sedan',
    fuelTypes: ['Petrol', 'MildHybrid'],
    priceRangeLakhs: { min: 134.00, max: 163.00 },
    rebadgedFromOrSharedWith: null,
    notes: 'Flagship long-wheelbase luxury sedan with 3.0L TFSI Quattro, rear executive seating, and predictive active suspension.',
    source: 'Audi India Official',
    sourceUrl: 'https://www.audi.in/in/web/en/models/a8/a8-l.html',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },
  {
    manufacturerName: 'Skoda Auto Volkswagen India Private Limited',
    brandName: 'Audi',
    brandSlug: 'audi',
    modelName: 'Q8 e-tron',
    slug: 'audi-q8-e-tron',
    status: 'ACTIVE',
    bodyType: 'SUV',
    segment: 'Flagship Luxury Electric SUV',
    fuelTypes: ['Electric'],
    priceRangeLakhs: { min: 115.00, max: 127.00 },
    rebadgedFromOrSharedWith: null,
    notes: 'Luxury electric SUV with 114 kWh battery pack, Quattro electric AWD, and up to 600 km WLTP range.',
    source: 'Audi India Official',
    sourceUrl: 'https://www.audi.in/in/web/en/models/q8-e-tron/q8-e-tron.html',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },
  {
    manufacturerName: 'Skoda Auto Volkswagen India Private Limited',
    brandName: 'Audi',
    brandSlug: 'audi',
    modelName: 'e-tron GT',
    slug: 'audi-e-tron-gt',
    status: 'ACTIVE',
    bodyType: 'Coupe',
    segment: 'Four-door Electric Gran Turismo',
    fuelTypes: ['Electric'],
    priceRangeLakhs: { min: 172.00, max: 205.00 },
    rebadgedFromOrSharedWith: null,
    notes: 'High-performance electric gran turismo sharing J1 platform with Porsche Taycan, up to 646 PS in RS guise.',
    source: 'Audi India Official',
    sourceUrl: 'https://www.audi.in/in/web/en/models/e-tron-gt/e-tron-gt.html',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },
  {
    manufacturerName: 'Skoda Auto Volkswagen India Private Limited',
    brandName: 'Audi',
    brandSlug: 'audi',
    modelName: 'RS5',
    slug: 'audi-rs5',
    status: 'ACTIVE',
    bodyType: 'Sedan',
    segment: 'High-Performance Sports Coupe / Sportback',
    fuelTypes: ['Petrol'],
    priceRangeLakhs: { min: 113.00, max: 113.00 },
    rebadgedFromOrSharedWith: null,
    notes: '2.9L twin-turbo V6 producing 450 hp and 600 Nm with Quattro permanent all-wheel drive.',
    source: 'Audi India Official',
    sourceUrl: 'https://www.audi.in/in/web/en/models/a5/rs-5-sportback.html',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },

  // BMW additions
  {
    manufacturerName: 'BMW India Private Limited',
    brandName: 'BMW',
    brandSlug: 'bmw',
    modelName: 'X3',
    slug: 'bmw-x3',
    status: 'ACTIVE',
    bodyType: 'SUV',
    segment: 'Mid-size Luxury SAV',
    fuelTypes: ['Petrol', 'Diesel'],
    priceRangeLakhs: { min: 72.50, max: 74.90 },
    rebadgedFromOrSharedWith: null,
    notes: 'Core luxury Sports Activity Vehicle assembled at BMW Chennai plant with xDrive and M Sport styling.',
    source: 'BMW India Official',
    sourceUrl: 'https://www.bmw.in/en/all-models/x-series/X3/2021/bmw-x3-highlights.html',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },
  {
    manufacturerName: 'BMW India Private Limited',
    brandName: 'BMW',
    brandSlug: 'bmw',
    modelName: 'M2',
    slug: 'bmw-m2',
    status: 'ACTIVE',
    bodyType: 'Coupe',
    segment: 'Pure High-Performance Sports Coupe',
    fuelTypes: ['Petrol'],
    priceRangeLakhs: { min: 99.90, max: 102.00 },
    notes: '3.0L twin-turbo S58 inline-6 (460 PS) with rear-wheel drive and available 6-speed manual transmission.',
    source: 'BMW India Official',
    sourceUrl: 'https://www.bmw.in/en/all-models/m-series/m2-coupe/2023/bmw-2-series-m-coupe-highlights.html',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },
  {
    manufacturerName: 'BMW India Private Limited',
    brandName: 'BMW',
    brandSlug: 'bmw',
    modelName: 'XM',
    slug: 'bmw-xm',
    status: 'ACTIVE',
    bodyType: 'SUV',
    segment: 'Flagship High-Performance M PHEV SAV',
    fuelTypes: ['PlugInHybrid'],
    priceRangeLakhs: { min: 260.00, max: 260.00 },
    rebadgedFromOrSharedWith: null,
    notes: 'Bespoke M division SUV featuring 4.4L M TwinPower Turbo V8 paired with an electric motor (653 PS / 800 Nm).',
    source: 'BMW India Official',
    sourceUrl: 'https://www.bmw.in/en/all-models/m-series/xm/2022/bmw-xm-highlights.html',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },
  {
    manufacturerName: 'BMW India Private Limited',
    brandName: 'BMW',
    brandSlug: 'bmw',
    modelName: 'Z4',
    slug: 'bmw-z4',
    status: 'ACTIVE',
    bodyType: 'Convertible',
    segment: 'Premium Two-Seater Open-Top Roadster',
    fuelTypes: ['Petrol'],
    priceRangeLakhs: { min: 90.90, max: 92.50 },
    rebadgedFromOrSharedWith: null,
    notes: 'Classic rear-wheel-drive roadster with M40i 3.0L inline-6 TwinPower Turbo (340 hp) and soft top.',
    source: 'BMW India Official',
    sourceUrl: 'https://www.bmw.in/en/all-models/z-series/z4/2022/bmw-z4-roadster-highlights.html',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },
  {
    manufacturerName: 'BMW India Private Limited',
    brandName: 'BMW',
    brandSlug: 'bmw',
    modelName: 'i5',
    slug: 'bmw-i5',
    status: 'ACTIVE',
    bodyType: 'Sedan',
    segment: 'Executive Electric Luxury Sedan',
    fuelTypes: ['Electric'],
    priceRangeLakhs: { min: 119.50, max: 125.00 },
    rebadgedFromOrSharedWith: null,
    notes: 'All-electric 5 Series executive sedan with 81.2 kWh battery, up to 516 km WLTP range, and M60 xDrive dual motor.',
    source: 'BMW India Official',
    sourceUrl: 'https://www.bmw.in/en/all-models/bmw-i/i5/2023/bmw-i5-highlights.html',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },

  // Mercedes-Benz additions
  {
    manufacturerName: 'Mercedes-Benz India Private Limited',
    brandName: 'Mercedes-Benz',
    brandSlug: 'mercedes-benz',
    modelName: 'GLB',
    slug: 'mercedes-benz-glb',
    status: 'ACTIVE',
    bodyType: 'SUV',
    segment: 'Three-Row Compact Luxury SUV',
    fuelTypes: ['Petrol', 'Diesel'],
    priceRangeLakhs: { min: 60.80, max: 66.90 },
    rebadgedFromOrSharedWith: null,
    notes: 'Versatile 7-seater luxury compact SUV with 4MATIC all-wheel drive and MBUX dual 10.25-inch displays.',
    source: 'Mercedes-Benz India Official',
    sourceUrl: 'https://www.mercedes-benz.co.in/passengercars/models/suv/glb/overview.html',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },
  {
    manufacturerName: 'Mercedes-Benz India Private Limited',
    brandName: 'Mercedes-Benz',
    brandSlug: 'mercedes-benz',
    modelName: 'EQB',
    slug: 'mercedes-benz-eqb',
    status: 'ACTIVE',
    bodyType: 'SUV',
    segment: 'Three-Row Electric Luxury SUV',
    fuelTypes: ['Electric'],
    priceRangeLakhs: { min: 70.90, max: 77.50 },
    rebadgedFromOrSharedWith: null,
    notes: '7-seater all-electric luxury SUV with 70.5 kWh battery pack, dual-motor 4MATIC, and up to 535 km range.',
    source: 'Mercedes-Benz India Official',
    sourceUrl: 'https://www.mercedes-benz.co.in/passengercars/models/suv/eqb/overview.html',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },
  {
    manufacturerName: 'Mercedes-Benz India Private Limited',
    brandName: 'Mercedes-Benz',
    brandSlug: 'mercedes-benz',
    modelName: 'EQE SUV',
    slug: 'mercedes-benz-eqe-suv',
    status: 'ACTIVE',
    bodyType: 'SUV',
    segment: 'Mid-size Luxury Electric SUV',
    fuelTypes: ['Electric'],
    priceRangeLakhs: { min: 139.00, max: 139.00 },
    rebadgedFromOrSharedWith: null,
    notes: '90.6 kWh battery with dual-motor AWD (408 hp / 858 Nm), MBUX Hyperscreen, and 590 km WLTP range.',
    source: 'Mercedes-Benz India Official',
    sourceUrl: 'https://www.mercedes-benz.co.in/passengercars/models/suv/eqe/overview.html',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },
  {
    manufacturerName: 'Mercedes-Benz India Private Limited',
    brandName: 'Mercedes-Benz',
    brandSlug: 'mercedes-benz',
    modelName: 'EQS SUV',
    slug: 'mercedes-benz-eqs-suv',
    status: 'ACTIVE',
    bodyType: 'SUV',
    segment: 'Flagship 7-Seater Luxury Electric SUV (CKD)',
    fuelTypes: ['Electric'],
    priceRangeLakhs: { min: 141.00, max: 162.00 },
    rebadgedFromOrSharedWith: null,
    notes: 'Locally assembled flagship electric SUV with massive 122 kWh battery, 544 hp dual motors, 809 km ARAI range, and 56-inch MBUX Hyperscreen.',
    source: 'Mercedes-Benz India Official',
    sourceUrl: 'https://www.mercedes-benz.co.in/passengercars/models/suv/eqs/overview.html',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },
  {
    manufacturerName: 'Mercedes-Benz India Private Limited',
    brandName: 'Mercedes-Benz',
    brandSlug: 'mercedes-benz',
    modelName: 'CLE',
    slug: 'mercedes-benz-cle',
    status: 'ACTIVE',
    bodyType: 'Coupe',
    segment: 'Luxury Grand Tourer Coupé & Cabriolet',
    fuelTypes: ['Petrol'],
    priceRangeLakhs: { min: 110.00, max: 135.00 },
    rebadgedFromOrSharedWith: null,
    notes: 'Two-door luxury coupé and cabriolet combining C-Class agility with E-Class space and prestige, including AMG CLE 53 4MATIC+.',
    source: 'Mercedes-Benz India Official',
    sourceUrl: 'https://www.mercedes-benz.co.in/passengercars/models/coupe/cle/overview.html',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },
  {
    manufacturerName: 'Mercedes-Benz India Private Limited',
    brandName: 'Mercedes-Benz',
    brandSlug: 'mercedes-benz',
    modelName: 'AMG GT',
    slug: 'mercedes-amg-gt',
    status: 'ACTIVE',
    bodyType: 'Coupe',
    segment: 'Flagship Super Sports Car & 4-Door Coupe',
    fuelTypes: ['Petrol', 'PlugInHybrid'],
    priceRangeLakhs: { min: 270.00, max: 330.00 },
    rebadgedFromOrSharedWith: null,
    notes: 'Handcrafted 4.0L biturbo V8 (up to 843 hp in GT 63 S E Performance), AMG Performance 4MATIC+, and carbon composite aerodynamics.',
    source: 'Mercedes-Benz India Official',
    sourceUrl: 'https://www.mercedes-benz.co.in/passengercars/models/coupe/amg-gt-coupe/overview.html',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },

  // Land Rover additions
  {
    manufacturerName: 'Jaguar Land Rover India Limited',
    brandName: 'Land Rover',
    brandSlug: 'land-rover',
    modelName: 'Discovery',
    slug: 'land-rover-discovery',
    status: 'ACTIVE',
    bodyType: 'SUV',
    segment: 'Full-size 7-Seater Luxury All-Terrain SUV',
    fuelTypes: ['Petrol', 'Diesel'],
    priceRangeLakhs: { min: 97.00, max: 138.00 },
    rebadgedFromOrSharedWith: null,
    notes: 'Full-size luxury family SUV with 7 full adult seats, Terrain Response 2, and 3,500 kg towing capacity.',
    source: 'Land Rover India Official',
    sourceUrl: 'https://www.landrover.in/discovery/discovery/index.html',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },
  {
    manufacturerName: 'Jaguar Land Rover India Limited',
    brandName: 'Land Rover',
    brandSlug: 'land-rover',
    modelName: 'Discovery Sport',
    slug: 'land-rover-discovery-sport',
    status: 'ACTIVE',
    bodyType: 'SUV',
    segment: 'Compact Luxury 5+2 Seater All-Terrain SUV',
    fuelTypes: ['Petrol', 'Diesel'],
    priceRangeLakhs: { min: 67.90, max: 67.90 },
    rebadgedFromOrSharedWith: null,
    notes: 'Compact luxury versatile SUV with 5+2 seating layout, Pivi Pro curved glass display, and Terrain Response.',
    source: 'Land Rover India Official',
    sourceUrl: 'https://www.landrover.in/discovery/discovery-sport/index.html',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },
  {
    manufacturerName: 'Jaguar Land Rover India Limited',
    brandName: 'Land Rover',
    brandSlug: 'land-rover',
    modelName: 'Range Rover Evoque',
    slug: 'range-rover-evoque',
    status: 'ACTIVE',
    bodyType: 'SUV',
    segment: 'Compact Luxury Urban SUV',
    fuelTypes: ['Petrol', 'Diesel'],
    priceRangeLakhs: { min: 67.90, max: 67.90 },
    rebadgedFromOrSharedWith: null,
    notes: 'Modern reductive luxury design with floating roofline, flush door handles, and 11.4-inch curved Pivi Pro infotainment.',
    source: 'Land Rover India Official',
    sourceUrl: 'https://www.landrover.in/range-rover/range-rover-evoque/index.html',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },

  // Lexus LC 500h
  {
    manufacturerName: 'Toyota Kirloskar Motor Private Limited',
    brandName: 'Lexus',
    brandSlug: 'lexus',
    modelName: 'LC 500h',
    slug: 'lexus-lc-500h',
    status: 'ACTIVE',
    bodyType: 'Coupe',
    segment: 'Flagship Luxury Hybrid Grand Tourer Coupe',
    fuelTypes: ['StrongHybrid'],
    priceRangeLakhs: { min: 239.00, max: 250.00 },
    rebadgedFromOrSharedWith: null,
    notes: 'Flagship rear-wheel-drive luxury coupe featuring multi-stage hybrid system with 3.5L V6 and 10-speed virtual multi-stage transmission.',
    source: 'Lexus India Official',
    sourceUrl: 'https://www.lexusindia.co.in/en/models/lc/lc-500h.html',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },

  // Volvo EX30
  {
    manufacturerName: 'Volvo Auto India Private Limited',
    brandName: 'Volvo',
    brandSlug: 'volvo',
    modelName: 'EX30',
    slug: 'volvo-ex30',
    status: 'ACTIVE',
    bodyType: 'SUV',
    segment: 'Compact Luxury Electric SUV',
    fuelTypes: ['Electric'],
    priceRangeLakhs: { min: 45.00, max: 50.00 },
    rebadgedFromOrSharedWith: null,
    notes: 'Smallest Volvo electric SUV built with the smallest carbon footprint of any Volvo to date; 69 kWh NMC battery and 476 km range.',
    source: 'Volvo Car India Official',
    sourceUrl: 'https://www.volvocars.com/in/cars/ex30-electric/',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },

  // Ferrari additions
  {
    manufacturerName: 'Ferrari S.p.A. India',
    brandName: 'Ferrari',
    brandSlug: 'ferrari',
    modelName: '12Cilindri',
    slug: 'ferrari-12cilindri',
    status: 'ACTIVE',
    bodyType: 'Coupe',
    segment: 'Flagship Front-Mid V12 Berlinetta',
    fuelTypes: ['Petrol'],
    priceRangeLakhs: { min: 850.00, max: 850.00 },
    rebadgedFromOrSharedWith: null,
    notes: '6.5-litre naturally aspirated 830 cv V12 revving to 9,500 rpm, paying homage to legendary Ferrari GTs of the 1950s and 60s.',
    source: 'Ferrari Official India Network',
    sourceUrl: 'https://www.ferrari.com/en-IN/auto/12cilindri',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },
  {
    manufacturerName: 'Ferrari S.p.A. India',
    brandName: 'Ferrari',
    brandSlug: 'ferrari',
    modelName: 'SF90 Stradale',
    slug: 'ferrari-sf90-stradale',
    status: 'ACTIVE',
    bodyType: 'Coupe',
    segment: 'Flagship PHEV Supercar',
    fuelTypes: ['PlugInHybrid'],
    priceRangeLakhs: { min: 750.00, max: 750.00 },
    rebadgedFromOrSharedWith: null,
    notes: 'Ferrari first PHEV series production supercar, combining 4.0L twin-turbo V8 with 3 electric motors for 1000 cv and AWD.',
    source: 'Ferrari Official India Network',
    sourceUrl: 'https://www.ferrari.com/en-IN/auto/sf90-stradale',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },

  // Lamborghini Temerario
  {
    manufacturerName: 'Skoda Auto Volkswagen India Private Limited',
    brandName: 'Lamborghini',
    brandSlug: 'lamborghini',
    modelName: 'Temerario',
    slug: 'lamborghini-temerario',
    status: 'ACTIVE',
    bodyType: 'Coupe',
    segment: 'High-Performance Electrified Vehicle (HPEV) Supercar',
    fuelTypes: ['PlugInHybrid'],
    priceRangeLakhs: { min: 600.00, max: 600.00 },
    rebadgedFromOrSharedWith: null,
    notes: 'All-new twin-turbo 4.0L flat-plane V8 hybrid revving to 10,000 rpm (920 CV), reaching 0-100 in 2.7s with 3 electric motors.',
    source: 'Automobili Lamborghini Official',
    sourceUrl: 'https://www.lamborghini.com/en-en/models/temerario',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },

  // Aston Martin DBX
  {
    manufacturerName: 'Aston Martin Lagonda India',
    brandName: 'Aston Martin',
    brandSlug: 'aston-martin',
    modelName: 'DBX',
    slug: 'aston-martin-dbx',
    status: 'ACTIVE',
    bodyType: 'SUV',
    segment: 'Ultra-Luxury High-Performance SUV',
    fuelTypes: ['Petrol'],
    priceRangeLakhs: { min: 382.00, max: 463.00 },
    rebadgedFromOrSharedWith: null,
    notes: '4.0L twin-turbo V8 developing up to 707 PS in the benchmark DBX707, featuring bonded aluminium chassis.',
    source: 'Aston Martin Lagonda Official',
    sourceUrl: 'https://www.astonmartin.com/en/models/dbx707',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },

  // Bentley Flying Spur
  {
    manufacturerName: 'Bentley Motors India',
    brandName: 'Bentley',
    brandSlug: 'bentley',
    modelName: 'Flying Spur',
    slug: 'bentley-flying-spur',
    status: 'ACTIVE',
    bodyType: 'Sedan',
    segment: 'Four-door Pinnacle Luxury Grand Touring Sedan',
    fuelTypes: ['PlugInHybrid', 'Petrol'],
    priceRangeLakhs: { min: 525.00, max: 710.00 },
    rebadgedFromOrSharedWith: null,
    notes: 'Ultimate luxury sedan with Ultra Performance Hybrid V8 (782 PS / 1000 Nm) and handcrafted Mulliner cabin.',
    source: 'Bentley Motors Official',
    sourceUrl: 'https://www.bentleymotors.com/en/models/flying-spur.html',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },

  // Rolls-Royce Phantom
  {
    manufacturerName: 'Rolls-Royce Motor Cars India',
    brandName: 'Rolls-Royce',
    brandSlug: 'rolls-royce',
    modelName: 'Phantom',
    slug: 'rolls-royce-phantom',
    status: 'ACTIVE',
    bodyType: 'Sedan',
    segment: 'Pinnacle Super-Luxury Motor Car (Series II)',
    fuelTypes: ['Petrol'],
    priceRangeLakhs: { min: 950.00, max: 1050.00 },
    rebadgedFromOrSharedWith: null,
    notes: 'The pinnacle luxury motor car in the world; Architecture of Luxury with 6.75L twin-turbo V12 and bespoke Gallery.',
    source: 'Rolls-Royce Motor Cars Official',
    sourceUrl: 'https://www.rolls-roycemotorcars.com/en_GB/showroom/phantom.html',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },

  // Lotus Emira
  {
    manufacturerName: 'Lotus Cars India',
    brandName: 'Lotus',
    brandSlug: 'lotus',
    modelName: 'Emira',
    slug: 'lotus-emira',
    status: 'ACTIVE',
    bodyType: 'Coupe',
    segment: 'Mid-Engine Premium Sports Car',
    fuelTypes: ['Petrol'],
    priceRangeLakhs: { min: 322.00, max: 350.00 },
    rebadgedFromOrSharedWith: null,
    notes: 'Mid-engine two-seater sports car with 3.5L supercharged V6 or 2.0L turbocharged 4-cylinder and bonded aluminium chassis.',
    source: 'Lotus Cars Official India',
    sourceUrl: 'https://www.lotuscars.com/en-IN/emira',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },

  // McLaren GTS
  {
    manufacturerName: 'McLaren Automotive India',
    brandName: 'McLaren',
    brandSlug: 'mclaren',
    modelName: 'GTS',
    slug: 'mclaren-gts',
    status: 'ACTIVE',
    bodyType: 'Coupe',
    segment: 'Lightweight High-Performance Grand Tourer',
    fuelTypes: ['Petrol'],
    priceRangeLakhs: { min: 615.00, max: 700.00 },
    rebadgedFromOrSharedWith: null,
    notes: '4.0L twin-turbo V8 developing 635 PS in a carbon fibre MonoCell II-T structure with 570L luggage space.',
    source: 'McLaren Automotive Official',
    sourceUrl: 'https://cars.mclaren.com/en/gts',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },

  // Maserati GranTurismo
  {
    manufacturerName: 'Maserati India',
    brandName: 'Maserati',
    brandSlug: 'maserati',
    modelName: 'GranTurismo',
    slug: 'maserati-granturismo',
    status: 'ACTIVE',
    bodyType: 'Coupe',
    segment: 'Iconic 2+2 Grand Tourer',
    fuelTypes: ['Petrol'],
    priceRangeLakhs: { min: 272.00, max: 315.00 },
    rebadgedFromOrSharedWith: null,
    notes: 'Iconic 2+2 grand tourer with Nettuno 3.0L twin-turbo V6 (up to 550 hp in Trofeo) and AWD.',
    source: 'Maserati India Official',
    sourceUrl: 'https://www.maserati.com/in/en/models/granturismo',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },
];

// Append newActiveModels into ACTIVE_MODELS_DATA
const activeModelsInsert = newActiveModels.map(m => `  ${JSON.stringify(m, null, 2).replace(/"([^"]+)":/g, '$1:').replace(/\\"/g, '"')},`).join('\n');

// Find end of ACTIVE_MODELS_DATA
const activeEndMarker = '];\n\n// ═══════════════════════════════════════════════════════════════════════════════\n// 3. DISCONTINUED';
content = content.replace(activeEndMarker, `${activeModelsInsert}\n${activeEndMarker}`);

// 6. Additional Discontinued Models
const newDiscontinuedModels = [
  {
    manufacturerName: 'Skoda Auto Volkswagen India Private Limited',
    brandName: 'Lamborghini',
    brandSlug: 'lamborghini',
    modelName: 'Huracán',
    slug: 'lamborghini-huracan',
    status: 'DISCONTINUED',
    bodyType: 'Coupe',
    segment: 'Naturally Aspirated V10 Supercar',
    fuelTypes: ['Petrol'],
    priceRangeLakhs: null,
    notes: 'Legendary 5.2L V10 supercar production concluded in 2024; succeeded by Temerario.',
    source: 'Automobili Lamborghini Official Heritage',
    sourceUrl: 'https://www.lamborghini.com/en-en/history/huracan',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },
  {
    manufacturerName: 'Jaguar Land Rover India Limited',
    brandName: 'Jaguar',
    brandSlug: 'jaguar',
    modelName: 'F-Type',
    slug: 'jaguar-f-type',
    status: 'DISCONTINUED',
    bodyType: 'Coupe',
    segment: 'Luxury Sports Coupe & Convertible',
    fuelTypes: ['Petrol'],
    priceRangeLakhs: null,
    notes: 'Iconic two-door sports car concluded production in June 2024 as Jaguar transitions to pure electric luxury.',
    source: 'Jaguar Heritage Archive',
    sourceUrl: 'https://www.jaguar.in/jaguar-range/f-type/index.html',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },
];

const discModelsInsert = newDiscontinuedModels.map(m => `  ${JSON.stringify(m, null, 2).replace(/"([^"]+)":/g, '$1:').replace(/\\"/g, '"')},`).join('\n');
const discEndMarker = '];\n\n// ═══════════════════════════════════════════════════════════════════════════════\n// 4. CONFIRMED UPCOMING';
content = content.replace(discEndMarker, `${discModelsInsert}\n${discEndMarker}`);

// 7. Additional Upcoming Models
const newUpcomingModels = [
  {
    manufacturerName: 'VinFast Auto India Private Limited',
    brandName: 'VinFast',
    brandSlug: 'vinfast',
    modelName: 'VF 3',
    slug: 'vinfast-vf-3',
    status: 'UPCOMING',
    bodyType: 'Micro SUV',
    segment: 'Compact Mini Electric City SUV',
    fuelTypes: ['Electric'],
    priceRangeLakhs: { min: 8.00, max: 10.00 },
    rebadgedFromOrSharedWith: null,
    notes: 'Sub-compact electric city car with rugged mini-SUV stance.',
    source: 'VinFast Auto India Official',
    sourceUrl: 'https://vinfastauto.in/models/vf3',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },
  {
    manufacturerName: 'Skoda Auto Volkswagen India Private Limited',
    brandName: 'Skoda',
    brandSlug: 'skoda',
    modelName: 'Superb',
    slug: 'skoda-superb',
    status: 'UPCOMING',
    bodyType: 'Sedan',
    segment: 'Flagship D-Segment Luxury Sedan (CBU)',
    fuelTypes: ['Petrol', 'Diesel'],
    priceRangeLakhs: { min: 55.00, max: 60.00 },
    rebadgedFromOrSharedWith: null,
    notes: 'Fourth-generation Superb returning as CBU import with 2.0L TDI and TSI powertrains.',
    source: 'Skoda Auto India Official Portal',
    sourceUrl: 'https://www.skoda-auto.co.in/models/superb',
    lastVerified: '2026-10-05',
    verificationStatus: 'VERIFIED',
  },
];

const upcModelsInsert = newUpcomingModels.map(m => `  ${JSON.stringify(m, null, 2).replace(/"([^"]+)":/g, '$1:').replace(/\\"/g, '"')},`).join('\n');
const upcEndMarker = '];\n\n// ═══════════════════════════════════════════════════════════════════════════════\n// 5. REBADGED VEHICLES';
content = content.replace(upcEndMarker, `${upcModelsInsert}\n${upcEndMarker}`);

fs.writeFileSync(inventoryFile, content, 'utf8');
console.log('Successfully patched build_full_inventory.ts with all audit findings!');
